### ISSUE TITLE
Firestore snapshot listener triggering changes locally even with setPersistenceEnabled(false)

### ISSUE THREAD

**Issue by MigoTiti** [firebase/firebase-android-sdk#1015]
Android Studio: 3.5.2
Firebase Firestore 21.3.0

I have a snapshot listener set to a collection and i set a new document without internet connection. I need to show the loading status so i wait for the snapshot listener to trigger to know that the document was set. The problem is that when i set the document, even without connection, the snapshot triggers and the loading disappears. I tried setting persistence enabled false to get changes from server only but it doesn't work. I also tried filtering the snapshot results with "isFromCache" but it doesn't trigger the moment i get back online, so i only get updated data when the collection gets updated again.

**Comment by aguatno** [comment]
Hi @MigoTiti Thanks for filing this issue!. Can you please provide the actual code to recreate this? It will make it easier to debug. If we can get code that demonstrates the issue, we'd be happy to dig into this. Thanks

**Comment by wu-hui** [comment]
Hi @MigoTiti 

It sounds like you might want to look into: https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore.html#waitForPendingWrites()

`waitForPendingWrites` will tell you when your writes (up to the point when it is called) are acknowledged by the backend, so you can set the document, show the loading status, and remove it when the `Task` returned from `wairForPendingWrites` is resolved.

**Comment by wu-hui** [comment]
Also, a little clarification about `setPersistenceEnabled`, this only changes where the cache and unacknowledged writes are stored at (in memory or on disk). This will not change the SDK's behavior during its lifetime. 

It matters when you close the app and re-open, in which case, with `setPersistenceEnabled(true)` the SDK is able to get all unacknowledged writes and send them to backend, while with `setPersistenceEnabled(false)`, those writes are lost.

**Comment by MigoTiti** [comment]
> Hi @MigoTiti Thanks for filing this issue!. Can you please provide the actual code to recreate this? It will make it easier to debug. If we can get code that demonstrates the issue, we'd be happy to dig into this. Thanks

So, i'm making a chat logic for my app where i use firestore to control the communication. I send and receive messages to a collection and in the snapshot listener i save the conversation locally using Room (for observable queries). I have a status for each message so i can know when the other end read my message. What i do is: i create the message document and get it's id. Then, i save the message in sqlite with the provided id and the status "pending", where i show a loading indicator (for each message) and i send to firestore the same message with status "sent". While the message is "pending", the screen shows the loading indicator next to the corresponding message. And when the snapshot listener is triggered, i override the message in the database with the same id and the status "sent", so my observable query triggers in my chat screen.

```
        val newDocument = firestore
            .collection(path)
            .document(chatId)
            .collection("messages")
            .document()

        val newMessage = Message(
            id = newDocument.id,
            text = message,
            chatId = chatId,
            status = MessageStatus.PENDING,
            isFromDriver = true,
            timestamp = Timestamp.now()
        )

        messageRepository
            .insertMessage(newMessage)
            .doOnError { error ->
                error.printStackTrace()
            }
            .subscribe()

        newDocument
            .set(
                hashMapOf(
                    "text" to message,
                    "timestamp" to newMessage.timestamp,
                    "status" to MessageStatus.SENT.name.toLowerCase(Locale.ROOT),
                    "type" to "provider"
                )
            )
```
The behaviour i was expecting was: i create locally the message with pending status and then when the snapshot triggers from server changes with the same message and different status, the loading indicator for that message is removed.

What is happening: the snapshot triggers from local changes and my message appears with sent status even without internet connection, and if i discard cache changes, the snapshot doesn't trigger again with server changes and i keep showing the loading status until the next server change.

**Comment by MigoTiti** [comment]
> Hi @MigoTiti
> 
> It sounds like you might want to look into: https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore.html#waitForPendingWrites()
> 
> `waitForPendingWrites` will tell you when your writes (up to the point when it is called) are acknowledged by the backend, so you can set the document, show the loading status, and remove it when the `Task` returned from `wairForPendingWrites` is resolved.

I think it wouldn't work as i expected because this method wait for all writes and i need a loading for each write.

**Comment by MigoTiti** [comment]
I think i could also listen to the set task in the document. It would work, but my suggestion is to enable a configuration to force snapshot triggers from server only.

**Comment by wu-hui** [comment]
Hi @MigoTiti 

I see. For your use case, listen to `Task` returned by `set` seems to be the best fit then. 

Forcing snapshot triggering from server only is interesting, but given the API around snapshot is already pretty complex, we feel a bit unsure to add it for a use case that can be solved by `set` already.

And IMHO, using `set` in this case makes the intention more explicit then config and listen to server updates only. 

I'd close this issue for now if you don't mind.

Thanks!
