### ISSUE TITLE
[inappmessaging-display] Allow usage of any image loader. 

### ISSUE THREAD

**Issue by niqo01** [firebase/firebase-android-sdk#1025]
## What feature would you like to see?

I would like firebase-inappmessaging-display to allow plugging in any image loader libraries instead of embedding Picasso by default.
 I am currently using Coil (https://github.com/coil-kt/coil), there are many popular image loading libraries.
All of them have non trivial impact on build size, method counts, ...

inappmessaging-display  could provide two dependencies `inappmessaging-display` and `inappmessaging-display-picasso` where `inappmessaging-display` would not embed an image loading library but enforce client applications to configure a custom one and `inappmessaging-display-picasso` for users who would like to use inappmessaging-display without any configuration.

## How would you use it?

This would help keep our app lean by embedding only one image loader instead of several.

**Comment by aguatno** [comment]
Thank you for sending this feature request. We will keep this FR open and update it as we prioritize new features. Thank you.

**Comment by JasonAHeron** [comment]
Hey, I think as of right now our thinking would be to improve our existing image loader rather than allow for a custom image loader to be provided. We would rather have this SDK just "do the right thing" when it comes to displaying messages.
