### ISSUE TITLE
Realm Crash Reports

### ISSUE THREAD

**Issue by sulemankhan447** [firebase/firebase-android-sdk#1032]
### [REQUIRED] Step 1: Describe your environment

  * Android Studio version: __3.5.2___
  * Firebase Component: ___2.10.1__ (Database, Firestore, Storage, Functions, etc)
  

#### Steps to reproduce:

Firebase Crashlytics doesnt capture realm crashes
Use realm change listener with realm database to refresh data from real results and try to do notify data set changed on list of recycler view

#### Relevant Code:
 private var sliderRealmChangeListener: RealmChangeListener<RealmResults<SliderResponseModel>> = RealmChangeListener {

        if (it!=null && it.size > 0) {
            imageArray.clear()
            for (i in 0 until it.size) {
                imageArray.add(ApiNames.ORIGIN+it[i]!!.mediaFile)
            }
            //TODO unsupported operation occurs sometimes
            homeBannerAdapter?.notifyDataSetChanged()

        }

    }

**Comment by aguatno** [comment]
Hi @sulemankhan44, thank you for taking time on filing this issue. I tried to reproduce, but wasn't able to replicate it. Could you provide a [simple repro](https://stackoverflow.com/help/minimal-reproducible-example) that we run locally & detailed steps to recreate this?
