### ISSUE TITLE
Having trouble making firebase go through client proxy, is there an extra configuration needed to make firebase use a proxy?

### ISSUE THREAD

**Issue by rodrigocasillas** [firebase/firebase-android-sdk#1036]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
This seems to be an issue more on the Firebase CLI tools, rather than an Android SDK. Please file issues with firebase-tools here:
https://github.com/firebase/firebase-tools/issues
