### ISSUE TITLE
Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.FirebaseException: An internal error has occurred. [ 7: ]

### ISSUE THREAD

**Issue by fcsd** [firebase/firebase-android-sdk#1060]
### Step 2: Describe your environment

  * Android device: Not depends on Android device
  * Android OS version: Not depends on Android version
  * Google Play Services version: Not depends on Google Play Services version
  * Firebase/Play Services SDK version: 19.1.0
  * FirebaseUI version: 6.1.0
  
### Step 3: Describe the problem:
App crashes when user gets FirebaseIdToken without internet connection.
I know, it relates to https://github.com/firebase/FirebaseUI-Android/issues/164, but that problem is reproduced now.

#### Steps to reproduce:

  1. Turn off Internet connection
  2. Get IdToken
  
#### Observed Results:
<img width="1066" alt="Screen Shot 2019-12-16 at 11 58 01" src="https://user-images.githubusercontent.com/17144698/70897462-59ad3f80-1ffb-11ea-8236-434d7b367c0b.png">
  
#### Expected Results:

Get exception on addOnCompleteListener without crash.
  
#### Relevant Code:

  ```
FirebaseAuth.getInstance().currentUser.getIdToken(true).addOnCompleteListener { ... }
  ```

**Comment by samtstern** [comment]
@fcsd are you able to reproduce this in your own testing?

**Comment by fcsd** [comment]
@samtstern Yes.

**Comment by aguatno** [comment]
Hi @fcsd this si similar to #988 and #944. 

> The issue has been fixed and indentified. The fix compose of better error handling that deals with network exceptions. However, I may not be able provide you with any specifics as to when will the fix be released in production. For now, try to catch the issue manually. Once the fix goes live, you'll not need to update to the new SDK version.
> 
> I'll close this when the fix is in prod.

**Comment by aguatno** [comment]
Thanks for patiently waiting. I got confirmation from our engineering team that this issue has been fixed externally. They just need to be using the newest release of Google Play services. SDK upgrade will not be needed. 

Closing this issue, please let us know if it's still happening and we can re-open it.
