### ISSUE TITLE
Firebase analytics debugview stopped working

### ISSUE THREAD

**Issue by Beta6484** [firebase/firebase-android-sdk#1067]
* Android Studio version: 3.5.3
  * Firebase Component: @ionic-native/firebase-analytics 4.20.0, cordova-plugin-firebase-analytics 4.0.0

I'm just a few days testing the register of system event logs in firebase analytics. Today around midday I stopped seeing the event logs in debugview. I already redid the whole configuration, configured new project and nothing, still unable to connect with debugview. I don't know what may be happening since very few people are talking about it.

**Comment by aguatno** [comment]
Hi @Beta6484 Could you provide your detailed steps how to reproduce the issue you're facing. A video clip indicating the steps can help.
