### ISSUE TITLE
Postpone getFiams()

### ISSUE THREAD

**Issue by C5FR7Q** [firebase/firebase-android-sdk#1068]
## What feature would you like to see?

I'd like getFiams() to be postponed till firebaseToken being Initialized. 
When user opens app first time, he woun't receive any in app messages. That's because there's no fetched messages. See the logs:
I/FIAM.Headless: Starting InAppMessaging runtime with Instance ID cuqDWIB8nLU
I/FIAM.Headless: Setting display event listener
I/FIAM.Headless: went foreground
I/FIAM.Headless: Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
I/FIAM.Headless: Recoverable exception while reading cache: /data/user/****/fiam_impressions_store_file (No such file or directory)
I/FIAM.Headless: FirebaseInstanceId not yet initialized, not attempting campaign fetch from service.
I/FIAM.Headless: Successfully fetched 0 messages from backend

## How would you use it?

It allows to send new users in app messages from the first open, not from the second one.

**Comment by aguatno** [comment]
Thank you for sending this feature request. We will keep this FR open and update it as we prioritize new features. Thank you.

**Comment by JasonAHeron** [comment]
Hey, this is now fixed past 19.0.5!
