### ISSUE TITLE
Service not registered: com.google.android.gms.common.internal.zzg

### ISSUE THREAD

**Issue by FzQ1940523** [firebase/firebase-android-sdk#1072]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component:Functions (Database, Firestore, Storage, Functions, etc)
  * Component version:17.1.1

#### Steps to reproduce:

com.google.android.gms:play-services-basement:17.1.1

crash info :
Service not registered: com.google.android.gms.common.internal.zzg@a68c420

com.google.android.gms.common.stats.ConnectionTracker.unbindService(SourceFile:25)

#### Relevant Code:
Didn't call the new method?

![unnamed (1)](https://user-images.githubusercontent.com/19216921/71248365-a07d9b00-2355-11ea-9862-61fa56ccb639.png)
![unnamed](https://user-images.githubusercontent.com/19216921/71248366-a1163180-2355-11ea-8c59-054be320cb18.png)

**Comment by FzQ1940523** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=c2d8e022e7&attid=0.2&permmsgid=msg-a:r-7454487032005046697&th=16f222dfacf21bb8&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ_kUlmrzliD2Uth4nZT1tbmfr15WXQcc8eQ_rNN6SDYQVlzeeWEuIA_1WYnYAKIiv5Q3iuzjJnTfjdud6Nc9i0LGWajka3n2OAMT1oYEt5Z8EtDqmpm1Q3Q-7k&disp=emb&realattid=ii_k4dtkgei1

https://mail.google.com/mail/u/0?ui=2&ik=c2d8e022e7&attid=0.1&permmsgid=msg-a:r-7454487032005046697&th=16f222dfacf21bb8&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ_xixe4yaoFCkcR_8MrfOxGuvkF_Q7ubYijlaSgjfqCcYRglyTHzmS6byntmqruYifwi0CMRtqukNfFjA-XbFKcL_L-1PK-m7mOvjO2cUmSrqo5xZK_QSBAMDo&disp=emb&realattid=ii_k4dtg82t0

**Comment by aguatno** [comment]
Hi @FzQ1940523 Could you provide your detailed steps how to reproduce the issue you're facing. A video clip indicating the steps can help.

**Comment by FzQ1940523** [comment]
We collected the crash, but could not replicate it

发自我的iPhone


------------------ Original ------------------

**Comment by aguatno** [comment]
As for reproducing the issue, I would need a runnable MCVE of your project for me to test it on my end and investigate more on what might be causing the issue. 

For now, possible workaround is to make sure all packages on build.gradle are the latest one.
