### ISSUE TITLE
SMS is Ilegible Firebase Auth

### ISSUE THREAD

**Issue by lucazin** [firebase/firebase-android-sdk#1080]
1º When i try to send SMS through Firebase Auth.. its send normally but Happens 2 problems

A) The SMS is ilegible, because i dont know why, i and others persons receive the message with @ between words.

B) Firebase Auth not callback when SMS received.  

Before 23/12/2019 was working normally.

Someone know what happen or can help me?  I send to firebase support but they are looking for yet and tell me dont find anyproblems.

But i'm not the owner of send service, firebase is so im just using API to send sms..but i receive this.

![a](https://user-images.githubusercontent.com/28266902/71480202-bc11f700-27d6-11ea-92bf-da10b254dbce.jpeg)

**Comment by aguatno** [comment]
Hi @lucazin thanks for filing this issue. SMS delivery problems can depend on a multitude of factors and are almost never issues with the SDK code so this repository is not the best place to file them.

Please contact Firebase Support who can better help you troubleshoot this issue:
https://firebase.google.com/support/contact/troubleshooting/

Thanks
