### ISSUE TITLE
Android Remote SDK 

### ISSUE THREAD

**Issue by ninate** [firebase/firebase-android-sdk#1082]
**

## What feature would you like to see?

Describe the feature you would like to add, ideally proposing a specific API.

## How would you use it?

Tell us how you'd use this feature in your app.

**Comment by aguatno** [comment]
Hi @ninate could you tell us more about this feature request? Thanks.

**Comment by samtstern** [comment]
@ninate please fill out the issue template when filing an issue, otherwise we can't help you.  I am going to clear this issue but feel free to open a new one with all of the required information.
