### ISSUE TITLE
Using ML Kit on specific phone can't download face-model properly

### ISSUE THREAD

**Issue by sandeep5193** [firebase/firebase-android-sdk#1089]
### Step 1: Describe your environment

  * Android device: Lenovo A6020a46
  * Android OS version: 5.1.1
  * Google Play Services version: 19.8.31(020408-284611645)
  * Firebase/Play Services SDK version: firebase-ml-vision:24.0.1
  
#### Steps to reproduce:

  This has started happening long back, when I was using firebase-ml-vision:15.0.0, targetSdkVersion=27. It was working very well in the same device for very long time, suddenly when I bumped up targetSdkVersion to 28, it started failing.

If I include face-model in Gradle Dependency, it works fine. I do not want to detect face contours, no landmark detection or classification either. I just want count of faces present. 
  
#### Observed Results:

  E/Vision: Error loading module com.google.android.gms.vision.face optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.

Once face-model is downloaded, it works once. App is crashing on 2nd run. Again when I run after the crash, it works for the first time.

I assume that some face-model is downloaded, otherwise it shouldn't work for the first instance as well, number of faces detected is accurate. It works perfectly fine on other test devices.

Logcat for the crash is attached [here](https://github.com/firebase/quickstart-android/files/3992403/logcat.txt). It's a native crash so I could not find anything in logs.

After clearing Play Services data, it downloads face-model again. It starts detecting faces once its downloaded. Vision TAG locat is attached [here](https://github.com/firebase/quickstart-android/files/3994977/logcat-services-clear-data.txt) for this. When I restart the app, it crashes.
  
#### Expected Results:

  face-model should have been downloaded properly and app shouldn't crash.
  
#### Relevant Code:

  Using this same repository, up to commit ID d14bf9cb018892c8eff94b95bd83f0d6a8b363a9

**Comment by aguatno** [comment]
Hi @sandeep5193  Could you also clarify what you mean by "Using this same repository", are you referring to firebase/quickstart-android? Thanks

**Comment by sandeep5193** [comment]
Yes, this issue was previously created on that repo.
