### ISSUE TITLE
Crashlytics deobuscation no longer getting uploaded with Gradle Plugin 3.5.3

### ISSUE THREAD

**Issue by toby78** [firebase/firebase-android-sdk#1091]
Exactly the same issue as in:

https://github.com/firebase/firebase-android-sdk/issues/745

This time with gradle plugin 3.5.3 and everything according to:

https://firebase.google.com/docs/crashlytics/get-started?authuser=0&platform=android

Happens both on Windows 7 and Mac when generated a singed release via Android Studio -> Build -> generated signed APK

app:crashlyticsUploadDeobsRelease just lasts forever.

-printmapping mapping.txt in proguard-rules.pro does not seem to make a different.

**Comment by toby78** [comment]
Ok, this one is hard to replicate. The same projects works in other environments that should be identical. I have no idea what other factors could be responsible. I am signing with v1 - I now tried with v1 and v2 but the same result. App Bundle has the same error here. 

Ideally there gradle task should automatically fall back to generating the mapping file locally without uploading if there is an error instead of keeping in a loop forever and not producing an apk.

**Comment by aguatno** [comment]
Hi @toby78 It seems this is a duplicate case you filed via Firebase Support Channel. For better tracking, we'll address the issue on this ticket#30443, and mark this as a duplicate to avoid confusion. Thanks.
