### ISSUE TITLE
Firebase realtime database unable to remove singleValueEventListener before getting callback.

### ISSUE THREAD

**Issue by Aswinhub** [firebase/firebase-android-sdk#1102]
In onCreate of an activity I have attached a valueEventListener for a query using `addListenerForSingleValueEvent()`. 

In onDestroy() of the activity `query.removeEventListener(valueEventListener);` added to remove the listener from the query. 

If the activity is destroyed before receiving any callbacks, the onDataChanged() in valueEventListener still receives callback even thought it is removed in onDestroy().

Is that the intended way of addListenerForSingleValueEvent() to be worked or it is not supposed to get any call backs after removing the event listener from the query  ?

**Comment by aguatno** [comment]
Hi @Aswinhub thanks for filing this issue, this sounds like a bug to me. Could you show piece of code that's not working as expected? Thanks

**Comment by Aswinhub** [comment]
@aguatno please check the following link for demo project https://github.com/Aswinhub/firebase-demo . I have added logs to track the flow.

**Comment by aguatno** [comment]
I just noticed that you're using an old SDK version (16.0.4'), could you try using the latest version (19.2.0) and see if the issue persists?

**Comment by Aswinhub** [comment]
The issue still exist in the latest version too and I have update the repository with latest gradle versions.
@aguatno

**Comment by schmidt-sebastian** [comment]
@Aswinhub Sorry this is not a supported use case of our `addListenerForSingleValueEvent()` API. Internally,  `addListenerForSingleValueEvent()` creates its own listener, which wraps the listener that you provide. Unfortunately, you would have to pass this wrapped listener into `removeEventListener()`, but we do not expose this listener.

You can work around this problem by using `addValueEventListener()`.

I am closing this issue for now. If there is more feedback, we can reconsider this implementation.
