### ISSUE TITLE
 Many Android 6.0.1 versions have crashed

### ISSUE THREAD

**Issue by dicallc** [firebase/firebase-android-sdk#1124]
# Step 1: Describe your environment
Android device: Galaxy J7 Prime
Android OS version: 6.0.1
Firebase/Play Services SDK version: 16.0.5

com.google.android.gms:play-services-measurement-base:16.0.5
'com.google.firebase:firebase-core:16.0.6' 
 implementation 'com.google.firebase:firebase-auth:16.1.0'
 implementation 'com.google.android.gms:play-services-auth:16.0.1'
 implementation 'com.google.firebase:firebase-auth:16.1.0'

# Step 2: Describe the problem:
Steps to reproduce:

In the firebase crash report, in many 6.0.1 mobile phones, the app crashed in the background. Is there no mobile phone compatible with this version?

bug log：
<pre>
Fatal Exception: java.lang.IllegalArgumentException
Service not registered: com.google.android.gms.common.internal.S@3d1a62e
android.app.LoadedApk.forgetServiceDispatcher (LoadedApk.java:1160)
android.app.ContextImpl.unbindService (ContextImpl.java:1475)
android.content.ContextWrapper.unbindService (ContextWrapper.java:644)
com.google.android.gms.common.stats.ConnectionTracker.unbindService (ConnectionTracker.java:25)
com.google.android.gms.common.internal.zzf.zzf (zzf.java:41)
com.google.android.gms.common.internal.zze.handleMessage (zze.java:53)
android.os.Handler.dispatchMessage (Handler.java:98)
com.google.android.gms.internal.common.zze.dispatchMessage (zze.java:8)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7406)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
</pre>

**Comment by aguatno** [comment]
Hi @dicallc can you please provide the actual code to recreate this? It will make it easier to debug, If we can get code that demonstrates the issue. Thanks

**Comment by dicallc** [comment]
I'm so sorry, I can't reproduce this problem now

Because this is only a case of some models, and all are 6.0.1 models.

I checked from firebase that 100% of the cases are due to the app switching to the background, and it took a while to find the crash.

And there are quite a lot of crashed models. I just wonder Is it that there are no models that are compatible with 6.0?

**Comment by aguatno** [comment]
Unfortunately, we'll have a hard time investigating this issue without repro steps. You may try updating your Firebase SDK to the latest version as they have the latest updates and bug fixes.
