### ISSUE TITLE
FirebaseVision.getInstance() returns null when inside an immediately accessed on-demand dynamic feature module

### ISSUE THREAD

**Issue by etiennecadicidean** [firebase/firebase-android-sdk#1169]
Having firebase-core on a base module, and using firebase-ml-vision on a on-demand feature-module

* Use SplitCompat to install an activity inside the on-demand feature module,
* When the feature module is installed thanks to SplitInstallManager, launch the activity
* The activity tries to access FirebaseVision.getInstance() or FirebaseVision.getInstance(FirebaseApp.getInstance()) but both return null.

What steps are mandatory to use Firebase Vision immediately after an on-demand install ?

Notes:

* Other firebase components are used in the base module
* After restarting the app, everything is fine

Which leads me to think the issue might be with the fact new manifest entries can't be accessed immediately after on-demand feature module install

https://developer.android.com/guide/playcore#access_downloaded_modules

Steps to reproduce :

* Use firebase-ml-vision inside a dedicated feature module, that is not present on app bundle install
* download the feature module
* try and access the feature module immediately
* call FirebaseVision.getInstance()

Conf:

* Android Studio version: 3.5.3
* Firebase Component: firebase-ml-vision
* Component version: 24.0.1

StackOverflow discussion here:

https://stackoverflow.com/questions/59966617/android-firebasevision-getinstance-returns-null-on-an-on-demand-feature-module

**Comment by etiennecadicidean** [comment]
Looks like it's heavily related to : 
https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

One work around I tried with success is to delete the FirebaseApp default instance and to call initializeApp(Application applicationContext), once the feature module is installed successfully :  
```
  FirebaseApp.getInstance().delete()
  FirebaseApp.initializeApp(context)
```

Couldn't it be possible to just trigger a scan of all available firebase components and init new ones ? (I didn't check the code much but something like making the FirebaseApp.initializeAllApis() public)

**Comment by etiennecadicidean** [comment]
Any news regarding this issue ? 
When mixing DynamicLinks in the base apk and FirebaseVision in the feature module, if launching the app with configuration "Default Apk" in AS and including the feature module; DynamicLinks.getInstance() then returns null (may be a problem with the merge of the AndroidManifests?)

**Comment by vkryachko** [comment]
Please file mlkit related issues to this repo https://github.com/googlesamples/mlkit
