### ISSUE TITLE
RuntimeException: Timestamp seconds out of range

### ISSUE THREAD

**Issue by rostopira** [firebase/firebase-android-sdk#1186]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.3
  * Firebase Component: Firestore
  * Component version: 19.0.0

#### Steps to reproduce:

I'm receiving some crash-reports with message "Internal error in Firestore (19.0.0)"
```
Caused by java.lang.IllegalArgumentException
Timestamp seconds out of range: 6787379236546125172
com.google.common.base.Preconditions.checkArgument
```
I don't know, what causes this issue and how to avoid it, but I do not expect app to crash due to invalid data in database as well as appearing such data in there

#### Relevant Code:

Unknown

**Comment by aguatno** [comment]
Hi @rostopira let's isolate if this is a coding issue or bug with the Firebase SDKs. Could you provide the following information so that I can have a clearer view of your issue:

- Changes you've made before the issue occurred (if there's any)
- Detailed or step by step instructions to reproduce the issue
- A minimal repro that I can replicate on my end

Please also try to use latest version of Firestore(21.3.1) as it contains updates and bug fixes.

**Comment by rostopira** [comment]
@aguatno issue appears in production, I can't reproduce it, only have reports from crashlytcis
I will release my app update and post if updated sdk fixes the issue

**Comment by arelguatno** [comment]
Thanks.

**Comment by aguatno** [comment]
Thanks

**Comment by wilhuff** [comment]
Could you post a full stack trace if you have it?

The exception you're seeing is coming from [here](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/Timestamp.java#L159). Superficially this means that somehow your application is trying to create a date well beyond the year 10,000.

The stack trace should help us figure out where that's coming from.

**Comment by rostopira** [comment]
@wilhuff There are three stacktraces from different threads
```
Caused by java.lang.IllegalArgumentException
Timestamp seconds out of range: 6783692629891908737
com.google.common.base.Preconditions.checkArgument (Preconditions.java:202)
com.google.firebase.Timestamp.validateRange (com.google.firebase:firebase-firestore@@19.0.0:165)
com.google.firebase.Timestamp.<init> (com.google.firebase:firebase-firestore@@19.0.0:65)
com.google.firebase.firestore.remote.RemoteSerializer.decodeTimestamp (com.google.firebase:firebase-firestore@@19.0.0:129)
com.google.firebase.firestore.local.LocalSerializer.decodeMutationBatch (com.google.firebase:firebase-firestore@@19.0.0:180)
com.google.firebase.firestore.local.SQLiteMutationQueue.decodeInlineMutationBatch (com.google.firebase:firebase-firestore@@19.0.0:437)
com.google.firebase.firestore.local.SQLiteMutationQueue.lambda$getNextMutationBatchAfterBatchId$4 (com.google.firebase:firebase-firestore@@19.0.0:236)
com.google.firebase.firestore.local.SQLiteMutationQueue$$Lambda$5.apply (com.google.firebase:firebase-firestore@@19.0.0)
com.google.firebase.firestore.local.SQLitePersistence$Query.firstValue (com.google.firebase:firebase-firestore@@19.0.0:476)
com.google.firebase.firestore.local.SQLiteMutationQueue.getNextMutationBatchAfterBatchId (com.google.firebase:firebase-firestore@@19.0.0:236)
com.google.firebase.firestore.local.LocalStore.getNextMutationBatch (com.google.firebase:firebase-firestore@@19.0.0:497)
com.google.firebase.firestore.remote.RemoteStore.fillWritePipeline (com.google.firebase:firebase-firestore@@19.0.0:574)
com.google.firebase.firestore.remote.RemoteStore.enableNetwork (com.google.firebase:firebase-firestore@@19.0.0:240)
com.google.firebase.firestore.remote.RemoteStore.start (com.google.firebase:firebase-firestore@@19.0.0:289)
com.google.firebase.firestore.core.FirestoreClient.initialize (com.google.firebase:firebase-firestore@@19.0.0:255)
com.google.firebase.firestore.core.FirestoreClient.lambda$new$2 (com.google.firebase:firebase-firestore@@19.0.0:116)
com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run (com.google.firebase:firebase-firestore@@19.0.0)
com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4 (com.google.firebase:firebase-firestore@@19.0.0:311)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call (com.google.firebase:firebase-firestore@@19.0.0)
com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3 (com.google.firebase:firebase-firestore@@19.0.0:287)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run (com.google.firebase:firebase-firestore@@19.0.0)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:423)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:269)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run (com.google.firebase:firebase-firestore@@19.0.0:205)
java.lang.Thread.run (Thread.java:818)
```
```
Caused by java.lang.RuntimeException
java.lang.IllegalArgumentException: Timestamp seconds out of range: 6783692629891908737
com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3 (com.google.firebase:firebase-firestore@@19.0.0:290)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run (com.google.firebase:firebase-firestore@@19.0.0)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:423)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:269)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run (com.google.firebase:firebase-firestore@@19.0.0:205)
java.lang.Thread.run (Thread.java:818)
```
```
Fatal Exception: java.lang.RuntimeException
Internal error in Firestore (19.0.0).
com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5 (com.google.firebase:firebase-firestore@@19.0.0:379)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run (com.google.firebase:firebase-firestore@@19.0.0)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5480)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
```

**Comment by wilhuff** [comment]
That's the worst case stack trace.

With offline persistence enabled (the default on Android), Firestore queues any writes you're making into a table in SQLite. When the network is available it reads them back. What this stack says is that it's failing while trying to read back a write and getting an invalid value for the local write time. Timestamps are validated no matter how they're created, and that means that local write time passed validation before it was written but is now failing when reading it back.

It's possible that the SQLite database has been corrupted, though this is the first time we've seen that in this way.

  * How widespread is this issue?
  * If this is localized to a specific device, is it possible to get a copy of the database files on the device?

**Comment by schmidt-sebastian** [comment]
As a drive-by comment: There is a small chance this is Timestamp could have been corrupted in memory, since Timestamps are Parcelable. The constructor that creates Timestamps from Parcels is the only constructor that does not validate the seconds range directly.

To explain the stacktrace, this would have needed to happen before the Timestamp was written to SQLite. This makes it even more unlikely, but it might be worth investigating if we need more leads.

**Comment by rostopira** [comment]
I've released new app version, just now got another crash report with the same stacktrace, using Firestore version 21.3.0 (used by latest flutter plugin, I can bet this issue will be in 21.4.0 as well)

**Comment by rostopira** [comment]
@wilhuff Sorry, I've missed you comment. Issue isn't widespread at all, it's very rare and happens in less than half percent of users

**Comment by FongMi** [comment]
I get same error

04-07 14:07:08.400 6203-6203/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fongmi.android.ltv, PID: 6203
    java.lang.RuntimeException: Internal error in Cloud Firestore (21.4.2).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3()
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run()
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5305)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: Timestamp seconds out of range: 6812843758347621709
        at com.google.firebase.firestore.util.Preconditions.checkArgument()
        at com.google.firebase.Timestamp.validateRange()
        at com.google.firebase.Timestamp.<init>()
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeTimestamp()
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeVersion()
        at com.google.firebase.firestore.remote.RemoteSerializer.decodeWatchChange()
        at com.google.firebase.firestore.remote.WatchStream.onNext()
        at com.google.firebase.firestore.remote.WatchStream.onNext()
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1()
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$2.run()
        at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run()
        at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext()
        at com.google.firebase.firestore.remote.FirestoreChannel$1.onMessage()
        at d.a.a0.onMessage()
        at d.a.a0.onMessage()
        at d.a.n1.q$d$b.a()
        at d.a.n1.y.run()
        at d.a.n1.z1.run()
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run()
        at java.lang.Thread.run(Thread.java:818)

**Comment by wilhuff** [comment]
@FongMi Are you able to see this happen reliably? If so, can you give us the steps you're using to see this?

**Comment by FongMi** [comment]
@wilhuff 

### **[READ] Step 1: Are you in the right place ?**
I have create test project to experiment
![image](https://user-images.githubusercontent.com/3471963/78733766-f1eb7d80-7978-11ea-87ec-b78f0a4135ef.png)

### **[REQUIRED] Step 2: Describe your environment**
Android Studio version: 3.6.2
Firebase Component: Firestore
Component version: 21.4.2
Emulator: Nox Player
### **[REQUIRED] Step 3: Describe the problem**
Steps to reproduce:
1. Create sample code
![image](https://user-images.githubusercontent.com/3471963/78733880-4b53ac80-7979-11ea-93d1-ea3f5595a83a.png)

2. Generate signed apk
![image](https://user-images.githubusercontent.com/3471963/78733926-6faf8900-7979-11ea-8470-4690698b90ee.png)

3. Put it to Nox Player and run
![image](https://user-images.githubusercontent.com/3471963/78733963-8ce45780-7979-11ea-963a-39023c82702a.png)

4. See the error
![image](https://user-images.githubusercontent.com/3471963/78733998-a6859f00-7979-11ea-9b4d-d77e81daab9f.png)
