### ISSUE TITLE
First-Class Kotlin Support

### ISSUE THREAD

**Issue by vkryachko** [firebase/firebase-android-sdk#120]
## What feature would you like to see?

Provide Kotlin-specific APIs around the Java SDKs to improve developer experience in that language

**Comment by samtstern** [comment]
cc @the-dagger @rosariopfernandes @supercilex

@vkryachko is going to be working on some Kotlin goodness as part of our internal "hack week" coming up, so feel free to let us know what you want to see!

**Comment by SUPERCILEX** [comment]
Woot! 👏

Off the top of my head, thry main experiences to be improved are those dealing with Java classes. All those APIs should use reified types.

**Comment by vkryachko** [comment]
@SUPERCILEX To clarify, did you mean improving instances of things like this with reified generics?
https://github.com/firebase/firebase-android-sdk/blob/ddda926/firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java#L182-L184

**Comment by SUPERCILEX** [comment]
Yep. Anything that accepts a `Class<T>`

**Comment by rosariopfernandes** [comment]
Thanks for pointing me to this @samtstern .

I would suggest creating extension functions for Firestore and Realtime Database. I have some of those in my library [fireXtensions](https://github.com/rosariopfernandes/fireXtensions), but it would be nice to have them on the SDK.

Some examples:
- [Cloud Firestore](https://github.com/rosariopfernandes/fireXtensions/blob/master/tutorials/cloud-firestore.md)
```kotlin
docRef.getDocument<City>() { city, exception ->
    city?.let {
        // update UI with city details
    }
    exception?.let {
    }
}
```
- [Realtime Database](https://github.com/rosariopfernandes/fireXtensions/blob/master/tutorials/realtime-database.md)
```kotlin
postReference.observe<Post> { post, exception ->
    post?.let {
        // Update the UI with received data
    }
    exception?.let {
        // an error occurred
    }
}
```

**Comment by SUPERCILEX** [comment]
@rosariopfernandes That looks interesting, but it should _not_ go in the Firestore SDK (could be a candidate for RTDB though it'll make leaking memory even easier so I'm hesitant to endorse it). Firestore uses the Play Services Tasks API which is a general purpose future implementation. This means that if we were to go with your design, it should be in a `play-services-tasks-ktx` module, not Firestore. Personally, I'm not a fan of those kinds of lambdas.

However, I'm all for [your `WriteBatch` extension function](https://github.com/rosariopfernandes/fireXtensions/blob/a089db0c65f02c1730b2400286d5e90278fff246/firestore/src/main/java/io/github/rosariopfernandes/firextensions/firestore/FirebaseFirestore.kt#L34-L40) as long as it's renamed to `batch` so it matches the native APIs. I have the same thing as a top-level `firestoreBatch` function, but I like your idea better so we don't clutter the global namespace. Good stuff. 😁

**Comment by rosariopfernandes** [comment]
I see, I see. :eyes:  Thanks for the tips @SUPERCILEX

**Comment by the-dagger** [comment]
This is a big step, kudos! 💯 
I don't have any specific requests off the top of my head, but will be happy to explore and suggest few things once we have an initial set of APIs ready.

**Comment by vkryachko** [comment]
@rosariopfernandes @SUPERCILEX 

Regarding extensions for task-returning methods. We can definitely consider this approach. Additionally I was thinking to provide `suspend` extensions for these to make Tasks more dev friendly when used with coroutines:

```kotlin
// Overload for `<T> Task<T> getDocument(Class<T> clazz)`
suspend fun <reified T> DocumentReference.getDocument(): T;
```

**Comment by SUPERCILEX** [comment]
@vkryachko please don't make it suspending. That would limit the applicable use cases since developers may want to save the task for later or not use coroutines at all. Instead, you can point them to the [official adapter](https://github.com/Kotlin/kotlinx.coroutines/blob/master/integration/kotlinx-coroutines-play-services/README.md).

Also, where is `getDocument(Class<T> clazz)`? I can't find it. I was thinking more along the lines of `DocumentSnapshot.toObject` and `QuerySnapshot.toObjects`.

**Comment by vkryachko** [comment]
> That would limit the applicable use cases since developers may want to save the task for later

@SUPERCILEX hm, I can't see how providing suspend functions would limit this use case, existing Java APIs already provide this functionality, right?

As for `getDocument`, I took it from @rosariopfernandes 's example above, I think it is called `get` in the firestore's Java SDK.

**Comment by vkryachko** [comment]
Yeah, definitely. I was not trying to suggest that we add new Kotlin-only functionality, I guess I just poorly chose the example. The only point I was trying to make is that I am considering adding suspend extension functions around `existing public task based APIs`.

**Comment by SUPERCILEX** [comment]
Gotya. Do you think that would add value over simply calling `task.await()`? If so, go for it! I'm concerned that it will set a precedent for auth, storage, etc to follow. It might also bloat the Kotlin namespace since you'll have two methods for every async API.

**Comment by vkryachko** [comment]
Fair enough, supporting/maintaining `task.await()` is essentially free as it is provided as an extension, while suspends have to be explicitly added for each method we want to be coroutine friendly. So it seems unjustified. Thanks for the input!

**Comment by samtstern** [comment]
@vkryachko is this issue still useful?  Maybe we should open more specific/actionable issues based on the discussions here and your findings from hack week.

**Comment by samtstern** [comment]
Closing this issue since the `-ktx` libraries now exist, so we can file more specific feature requests going forward.
