### ISSUE TITLE
Native symbols crashlyticsUploadSymbols{variant}  Crashlytics found no symbols for *.so skipping

### ISSUE THREAD

**Issue by Gark** [firebase/firebase-android-sdk#1220]
### [REQUIRED] Step 2: Describe your environment

* react-native                  0.61.5
* Gradle plugin version  3.5.3
* Gradle version              5.5
* Fabric                             1.31.2
* Crashlytics-ndk            2.1.1
* Crashlytics                    2.10.1

```
crashlytics {
    enableNdk true
    androidNdkOut 'build/intermediates/merged_native_libs'
    androidNdkLibsOut 'build/intermediates/stripped_native_libs'
}
```

### [REQUIRED] Step 3: Describe the problem

`./gradlew crashlyticsUploadSymbols{variant}`  command succeeded

but Crashlytics log file ~/Library/Caches/com.crashlytics/com.crashlytics.tools/crashlytics.log  says
```

(Daemon worker Thread 4) com.crashlytics  - Crashlytics found no symbols for /************/out/lib/x86_64/libyoga.so, skipping.
(Daemon worker Thread 4) com.crashlytics  - Generating cSYM for /************/out/lib/x86_64/librsjni.so
(Daemon worker Thread 4) com.crashlytics  - Using ELF data for cSYM generation.
(Daemon worker Thread 4) com.crashlytics  - Crashlytics found no symbols for /************/out/lib/x86_64/librsjni.so, skipping. 
```

Folders `stripped_native_libs` and `merged_native_libs` are not emty:
![Screenshot 2020-02-17 at 10 01 46](https://user-images.githubusercontent.com/1929368/74638722-bdbfc180-516c-11ea-8598-7e360e8906a4.png)

**Comment by kevinkokomani** [comment]
Hi Gark, this looks like an issue with the legacy Crashlytics SDK. Would you mind sending this request through support@fabric.io so we can dig deeper into this with you? Thanks!
