### ISSUE TITLE
Errors importing Storage SDK

### ISSUE THREAD

**Issue by axionnneeeel** [firebase/firebase-android-sdk#1237]
I want to modify Firebase Storage but i encounter some problems.

I cloned the repository.

Then, i copied the "firebase-storage" folder in my project and did the following steps:

added "include 'firebase-storage'" in settings.gradle
added "implementation project 'firebase-storage'" in my app build.gradle.
I got the following error i don't know how to fix.

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :firebase-storage.
Show Details
Affected Modules: app
ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :firebase-storage.
Show Details
Affected Modules: app
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :firebase-storage.
Show Details
Affected Modules: app

**Comment by samtstern** [comment]
@axionnneeeel if you're trying to "fork" the storage SDK by copying the folder from this repo into your project and adding it to your gradle build, that will not work.

Instead you should:

- Clone the repo, whole.
- Make the changes you want
- Publish a new version to your local or company maven repo (https://github.com/firebase/firebase-android-sdk#publishing)
