### ISSUE TITLE
Firebase Messaging 20.1.0 results in duplicate classes (firebase-inappmessaging-display)

### ISSUE THREAD

**Issue by ma-za-kpe** [firebase/firebase-android-sdk#1239]
These two lines are the ones causing the conflict.
    implementation 'com.google.firebase:firebase-inappmessaging-display:17.0.4'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'

**Comment by aguatno** [comment]
Hi @ma-za-kpe Please use the issue template when filing an issue so that we can help you solve your problem. I am going to close this issue but feel free to file a new one with all of the required information
