### ISSUE TITLE
Re: [firebase/firebase-android-sdk] Firebase Messaging 20.1.0 results in duplicate classes (firebase-inappmessaging-display)

### ISSUE THREAD

**Issue by ma-za-kpe** [firebase/firebase-android-sdk#1240]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _3.5.3____
  * Firebase Component: ___inappmessaging__ (Database, Firestore, Storage, Functions, etc)
  * Component version: ___19.0.3__

#### Steps to reproduce:

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-26.0-android.jar (com.google.guava:guava:26.0-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
    implementation 'com.google.firebase:firebase-inappmessaging-display:19.0.3'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'


```

**Comment by aguatno** [comment]
Hi @ma-za-kpe the crash is because of your dependency on Guava. Could you try this [answer](https://github.com/firebase/firebase-android-sdk/issues/596#issuecomment-528618001) to see if it helps resolve your issue?
