### ISSUE TITLE
VeraCode scan found CWE ID 331 in Firestore client

### ISSUE THREAD

**Issue by psimonazzi** [firebase/firebase-android-sdk#1245]
We are using the Firestore library in an environment that requires static security scans. The scan tool (VeraCode) found vulnerability CWE 331 (Insufficient Entropy) in:
`com.google.firebase.firestore.util.Util`
VeraCode support says it is most probably related to the use of `Random` instead of `SecureRandom`.

Since this can block adoption of the library in regulated environments, please consider changing this.

At a glance it seems that the method is used only in `CollectionReference` to create a new document reference client-side. 
If you could confirm that this is indeed the case, then this may be enough to conclude that usage is not in a critical security path. I'm also looking at #408 that wonders if it may be acceptable to use a non completely random generator for this use case.

  * Firebase Component: Firestore
  * Component version: tested in 21.3.1, 21.4

**Comment by wu-hui** [comment]
Hi @psimonazzi 

Thanks for reporting this, although it is not a security issue (it is only used to generate auto id, as you noted), it is better to not show up in security scans.

We will switch to use `SecureRandom` instead.

**Comment by wu-hui** [comment]
It is now using `SecureRandom`: https://github.com/firebase/firebase-android-sdk/pull/1250
