### ISSUE TITLE
Add coroutines Flow extension functions for Firestore

### ISSUE THREAD

**Issue by martinbonnin** [firebase/firebase-android-sdk#1251]
## What feature would you like to see?

Firestore has [DocumentReference.addSnapshotListener](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentReference.html#addSnapshotListener) and  [Query.addSnapshotListener](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/Query.html#addSnapshotListener).

Both of these are callback based and it would be nice to have coroutines equivalents. Something like: 

```kotlin
fun DocumentReference.toFlow(): Flow<DocumentSnapShot> { 
      TODO()
}

fun Query.toFlow(): Flow<QuerySnapShot> { 
      TODO()
}
```

## How would you use it?

This would be useful to leverage coroutines to make the code look nicer. Also it can be used together with coroutines scopes to bind Firestore queries to the Android lifecycle.

**Comment by aguatno** [comment]
Thank you for sending this feature request. We will keep this FR open and update it as we prioritize new features. Thank you.

**Comment by svenjacobs** [comment]
Also looking forward to this! I'm using my own implementations of `toFlow()` for `DocumentReference` and `Query` but would really like to use some official solution :)

**Comment by vkryachko** [comment]
This was added in firebase-firestore-ktx version 24.3.0
