### ISSUE TITLE
Firebase Remote Config connection leak

### ISSUE THREAD

**Issue by zallz** [firebase/firebase-android-sdk#1259]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.3
  * Firebase Component: Remote Config
  * Component version: com.google.firebase:firebase-perf:19.0.5

#### Steps to reproduce:

1) Add Firebase Performance Monitoring following the "Get started with Performance Monitoring" walkthrough. This will add Firebase Remote Config automatically.
2) Run your App.
3) In the Logcat you will see : OkHttpClient: A connection to https://firebaseremoteconfig.googleapis.com/ was leaked. Did you forget to close a response body?

**Comment by clp93** [comment]
I believe that the issue is caused by Android's underlying usage of OKHttp (https://github.com/square/okhttp/issues/2311)

Said issue has since been fixed, but it'd probably take some time for Android to pick up the fix

**Comment by zallz** [comment]
Seen on Android 8.1
Not seen on Android 10.0

**Comment by clp93** [comment]
Thanks for that, if so, it seems the Android change referenced in https://github.com/square/okhttp/issues/2311#issuecomment-502384379 solved the issue, and validates my hypothesis that this error is **not** actually being caused by the Remote Config SDK.
