### ISSUE TITLE
In-App Messaging Accessibility

### ISSUE THREAD

**Issue by patrycjasosnowska** [firebase/firebase-android-sdk#1277]
## What feature would you like to see?

I am working on Android app that has implemented accessibility by supporting TalkBack. I noticed that in-app message doesn't work well with this accessibility service. When the popup is displayed and TalkBack is on, there is no possibility to click on a button in the popup, because TalkBack can't focus on that button. Also, no element on this popup is labeled, even close button. In fact, when in-app messaging is displayed, visually impaired users have no idea how to deal with it properly. It would be nice to add some improvements for them by supporting TalkBack.

## How would you use it?

Tell us how you'd use this feature in your app.

**Comment by rosariopfernandes** [comment]
@patrycjasosnowska Which Android version are you using?

I tested InAppMessaging with TalkBack on Android 8.0 (Oreo) and it was able to focus on Text and Buttons, but not on Images.

When focused on Text and Text buttons, it was able to read the content out loud, but the same didn't happen when focused on the close button.

**Comment by JasonAHeron** [comment]
Hey @patrycjasosnowska we need more info to reproduce this. Please provide reproduction steps.

Thank you

**Comment by patrycjasosnowska** [comment]
Hi,
I checked it again on a few devices and now it seems that everything works fine. Unfortunately I don't remember OS version and device model on which I noticed the issue with no focus. If it happen again I will provide you more details. Thank you for your response.
