### ISSUE TITLE
Crashlytics not reporting custom keys

### ISSUE THREAD

**Issue by SammyJankis** [firebase/firebase-android-sdk#1278]
### Environment

  * Android Studio version: 3.5.3
  * Firebase Component: Crashlytics
  * Component version: 2.10.0

### Problem
Custom keys registered with these kind of methods : 
Crashlytics.getInstance().core.setString("ExampleCurrency", currencyCode)
are not registered in the Firebase crash KEYS section of each crash.

#### Steps to reproduce:
Just set the keys
Force the app to crash
Reopen the app to allow crashlytics to report the problem

**Comment by aguatno** [comment]
Hi @SammyJankis I was able to register a key based on the given code snippet. 

![image](https://user-images.githubusercontent.com/56451054/75269958-bc5d5b80-5834-11ea-88e1-0216311ba36d.png)

Could you try using the latest version of SDK(2.10.1) and see if this resolves the issue?

**Comment by SammyJankis** [comment]
Hi @aguatno, I have also tried with version 2.10.1 and nothing happens. We been through the migration process from Fabric to Firebase, and now we want to use this feature in our crashlytics reports, maybe this info will help you.

**Comment by TKBurner** [comment]
Hi folks, could you let me know how long afterward you are testing this. If you check a few hours later you should be able to see these values. Please let me know if it persists for 24 hours after the crash appears in the dashboard.

**Comment by SammyJankis** [comment]
@TKBurner yep, today we just checked crashes from 21 Feb - 24 Feb from the version where we add this feature and we have the same output, no keys shown :(

**Comment by kevinkokomani** [comment]
We've seen several instances where developers believe they are setting the keys but actually the crash occurs before the keys are set. Since we don't have the full code snippet, could you double check to make sure the values are absolutely getting set before the crash occurs?

If you can confirm that, then this seems like a strange issue that we would have to dig deeper into your app for, likely via a [submitted case to Firebase support](https://firebase.google.com/support/troubleshooter/contact).

**Comment by SammyJankis** [comment]
I'm gonna try this : https://firebase.google.com/docs/crashlytics/upgrade-sdk?authuser=0&platform=android
Because we suspect that this issue is related with the previos migration. I'll let you know the result

**Comment by SammyJankis** [comment]
FYI
We realized that we were using "Thread.setDefaultUncaughtExceptionHandler" and doing really weird things in there, so we just remove this code and the custom keys begin to appear in the crashlytics dashboard. 
Sorry guys, and thanks for the support, you can close this issue.
