### ISSUE TITLE
InApp Messaging | Postpone messages

### ISSUE THREAD

**Issue by Hospes** [firebase/firebase-android-sdk#1299]
Hi there,

I have issue with showing in-app messages on main activity.
When app launches first time it starts `SplashScreenActivity` and then finishes it and starts `MainActivity` also could be that it start `SignInActivity` betwwen them. So the issue that I need to show messages not on `SplashScreenActivity` but on `MainActivity` when it starts.
Unfortunatelly playing around methods:
```
FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true)
.....
FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)
```
Didn't help.

Can anyone help with it? I want to understand why messages not shown to user when i set `suppressed false`

I'm using button `Test on device` from firebase console to send messages and it needs to restart the app.

**Comment by tatsuhama** [comment]
@Hospes 
I have the same problem, too.
I think it could be solved by the following method.
```MainActivity.kt
override fun onResume() { // MainActivity.kt
    super.onResume()
    FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)
    Handler().postDelayed({
        FirebaseInAppMessagingDisplay.getInstance().onActivityResumed(this)
    }, 1000)
}
```

> why messages not shown to user when i set suppressed false

This is because only the flag has been changed and the display processing has not been called.
So, I call `FirebaseInAppMessagingDisplay.getInstance().onActivityResumed(this)` manually.

**Comment by Hospes** [comment]
@tatsuhama thank you !

**Comment by amatkivskiy** [comment]
@tatsuhama Didn't help me, still not messages.
