### ISSUE TITLE
Feature Request: Open Source Firebase Crashlytics SDK

### ISSUE THREAD

**Issue by maks** [firebase/firebase-android-sdk#13]
## What feature would you like to see?

It would be very useful to also have the [Firebase Crashlytics SDK](https://firebase.google.com/docs/crashlytics/get-started) available as open source.

## How would you use it?

Having the Crashlytics SDK available under an open source license would allow apps that are distributed via F-Droid to make use of it as it has a restriction of not allowing apps that have dependencies on non open source libraries.

**Comment by ashwinraghav** [comment]
Thanks for reaching out @maks. This is definitely something on our radar over the next few months. 
Looking at the [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/), it seems like F-Droid requires **all** dependencies, including transitive ones to be FLOSS.

While plausible for Crashlytics given its [dependencies](http://repo.spring.io/libs-release/com/crashlytics/sdk/android/crashlytics/2.9.3/crashlytics-2.9.3.pom), it behooves us to set realistic expectations that open sourcing transitive dependencies becomes much harder for many Firebase products that have a dependency on play services.

**Comment by maks** [comment]
Thanks for the very quick response @ashwinraghav !
Yes I didn't take into account possible transitive deps on closed src libs like play services that Crashlytics may have though in this case it looks promising so I will keep an eye out for any updates here. 

And yes agree about being realistic as looking through the gradle files for the firebase sdks that have been already open sourced here, I can see that most (including common) have deps on play services.

**Comment by long1eu** [comment]
how about the auth module? I'm doing a port to dart to be used with flutter. I did the common module, and half of the firestore.

**Comment by samtstern** [comment]
@long1eu have you seen [FlutterFire](https://github.com/flutter/plugins/blob/master/FlutterFire.md) it has support for Firebase Auth and Firestore in flutter.

**Comment by long1eu** [comment]
@samtstern yeah, but those are plugins not actual sdks

**Comment by long1eu** [comment]
so again what about the auth module?

**Comment by samtstern** [comment]
I can't give you a very satisfying answer. We want to open source all of the SDK modules eventually, but the timeline for doing so is different for each team.

Auth is trickier than most because it has some pieces that communicate with Google Play services.  The SDKs which have been open-sourced here so far don't communicate outside of your app process.

**Comment by long1eu** [comment]
I see. Thanks

**Comment by SUPERCILEX** [comment]
Tis done peeps! https://github.com/firebase/firebase-android-sdk/pull/1103

**Comment by samtstern** [comment]
@SUPERCILEX 
![giphy](https://user-images.githubusercontent.com/8466666/72193371-004bec80-33be-11ea-88a5-288a3651ee37.gif)
