### ISSUE TITLE
Run firebase on Device without Google play service.

### ISSUE THREAD

**Issue by wangjiejacques** [firebase/firebase-android-sdk#132]
## What feature would you like to see?

For now, my app is not able to run on devices without google play service, it is not ideal, as a lot of my users use android device without google play service.

**Comment by samtstern** [comment]
@wangjiejacques thanks for the feedback.  Actually all of the SDKs that have been open-sourced in this repository _should_ work on devices without Play services, although we don't extensively test that use case.

Can I ask which Firebase services you're not able to use on devices without Play services?  I assume Firebase Authentication, which is the most commonly requested.

**Comment by wangjiejacques** [comment]
@samedson yes, you are right, when I try to login with phone number, it shows me *title: Update Google Play services*, *Message: XX won't run unless you update Google Play services.*

**Comment by asadman1523** [comment]
Has the same issue. The notification always show "update Google play service" message even I didn't call any firebase init function.

**Comment by samtstern** [comment]
I am going to close this issue since there's nothing that can be done *in this repo* to fix it.  That said, we are definitely aware of this request and working to make more of our SDKs available for devices without Play services!
