### ISSUE TITLE
Screen class names are not reflecting for screen views in dashboard

### ISSUE THREAD

**Issue by mrudulamrudu** [firebase/firebase-android-sdk#1321]
I am using firebase-analytics:17.2.2 for Android. I am successfully able to log custom events and view them on dashboard in debug view. But screen names are not reflecting in screen_view events.
I am overriding the class name in onResume() using
`firebaseAnalytics.setCurrentScreen(this, "Login", LoginActivity.class.getSimpleName());`
When I filter user engagement with "screen name" screen class shows "not set".

Logcat:
Logging event: origin=auto,name=user_engagement(_e),params=Bundle[{ga_event_origin(_o)=auto, engagement_time_msec(_et)=299656, ga_screen_class(_sc)=LoginActivity, ga_screen_id(_si)=-7403121824905723112}]

**Comment by rlazo** [comment]
Hi @mrudulamrudu sorry for the long delay. Are you still hitting this issue? If so, please update to the latest version of `firebase-analytics` (18.0.0) and report back. Thanks!
