### ISSUE TITLE
In-app message Disappear Immediately 

### ISSUE THREAD

**Issue by pemassi** [firebase/firebase-android-sdk#1334]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.3
  * Firebase Component: In-app message
  * Component version: 19.0.3
```
    implementation 'com.google.firebase:firebase-analytics:17.2.3'
    implementation 'com.google.firebase:firebase-inappmessaging-display-ktx:19.0.3'
```

#### Steps to reproduce:

1. Show `Activity B` from `Activity A`, and finish `Activity A`
2. On `onResume()`, log the event with name 'screen_main'
3. The modal in-app message shows and it will be disappeared in 0.5 secs without doing anything.

#### Relevant Code:

```
    //Acitivty A
    launchActivitiy<ActivityB>()
    finish()

    //Activity B
    override fun onResume() {
        super.onResume()
        FirebaseAnalytics.getInstance(this).logEvent(FirebaseAnalysticConst.SCREEN_MAIN, null)
    }
```

**Comment by phildupuis** [comment]
I got the same issue only on the modal layout, but card, image only and top banner works perfectly.

**Comment by ashwinraghav** [comment]
Thanks for your patience on the issue. 
This has been fixed with the latest release of inappmessaging v 19.0.7
