### ISSUE TITLE
Your client does not have permission to get URL /identitytoolkit/v3/relyingparty/createAuthUri from this server

### ISSUE THREAD

**Issue by MattSkala** [firebase/firebase-android-sdk#1351]
We started to see the following crash quite frequently over the last few weeks:

```
Fatal Exception: com.google.firebase.FirebaseException: An internal error has occurred. [ <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/createAuthUri</code> from this server.  <ins>That’s all we know.</ins> ]
       at com.google.firebase.auth.api.internal.zzdv.zza(zzdv.java:18)
       at com.google.firebase.auth.api.internal.zzfc.zza(zzfc.java:21)
       at com.google.firebase.auth.api.internal.zzes.zza(zzes.java:34)
       at com.google.firebase.auth.api.internal.zzeu.zza(zzeu.java:74)
       at com.google.firebase.auth.api.internal.zzeb.zza(zzeb.java:18)
       at com.google.android.gms.internal.firebase_auth.zza.onTransact(zza.java:13)
       at android.os.Binder.execTransactInternal(Binder.java:1021)
       at android.os.Binder.execTransact(Binder.java:994)
```

SDK version: `com.google.firebase:firebase-auth:19.2.0`

The first crash occured in the build where we introduced Sign in with Apple, but it does not have to be necessarily related. We were not able to reproduce it on any device.

**Comment by MattSkala** [comment]
The issue still persists in auth 19.3.0

**Comment by MattSkala** [comment]
Still happens in 19.3.1. 

It would be great if there was at least a way to catch this exception. It is currently the most frequently occurring crash in our application (140 crashes over the last month).

**Comment by madebyfrancisco** [comment]
Same issue. It happens quite frequently to me as well.

**Comment by malcolmdeck** [comment]
Hey folks, Malcolm from Firebase here. Sorry that you're seeing this issue - this looks really, really bizarre. Do you have any context or bugreports for this crash? I've never seen this crash (nor have I been able to reproduce it now).

**Comment by MattSkala** [comment]
Hi, thanks for checking the issue. Unfortunately, I don't have much more context. It happens across all Android versions and a wide range of devices. From our logs, it seems it crashes shortly after the user authenticates with Facebook or Google successfully.

Here is the latest stack trace from auth 19.3.1. Are you able to deobfuscate method calls in the internal part of the SDK?

I can also share our Firebase project ID if that helps.

```
Fatal Exception: com.google.firebase.FirebaseException: An internal error has occurred. [ <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/createAuthUri</code> from this server.  <ins>That’s all we know.</ins> ]
       at com.google.firebase.auth.api.internal.zzeh.zza(zzeh.java:18)
       at com.google.firebase.auth.api.internal.zzfo.zza(zzfo.java:21)
       at com.google.firebase.auth.api.internal.zzfe.zza(zzfe.java:33)
       at com.google.firebase.auth.api.internal.zzfg.zza(zzfg.java:74)
       at com.google.firebase.auth.api.internal.zzen.zza(zzen.java:18)
       at com.google.android.gms.internal.firebase_auth.zza.onTransact(zza.java:13)
       at android.os.Binder.execTransact(Binder.java:739)
```

**Comment by nes123** [comment]
This is where it happens:

`

firebase
--
  | .auth()
  | .signInWithCredential(credential)

`

No matter what method - sign in with facebook, phone, email..all end up in the same error. For me it happens just with one android phone OS 4.4.2

`[auth/-] An internal error has occurred. [ <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/verifyAssertion</code> from this server.  <ins>That’s all we know.</ins> ] 
    Forbidden tle>Error 403
    unknown argin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and
    node_modules/@react-native-firebase/auth/lib/index.js:230:7 value
    AgrioApp/AuthPage.js:1238:13 anonymous
    native call
    node_modules/regenerator-runtime/runtime.js:45:39 p
    node_modules/regenerator-runtime/runtime.js:274:21 anonymous
    node_modules/regenerator-runtime/runtime.js:97:20 anonymous
    native call
    node_modules/regenerator-runtime/runtime.js:45:39 p
    node_modules/regenerator-runtime/runtime.js:135:19 o
    node_modules/regenerator-runtime/runtime.js:145:12 anonymous
    node_modules/promise/setimmediate/core.js:37:11 f`

**Comment by tcha-tcho** [comment]
I'm having the same problem with IOS and Web. Even accessing the URLs directly. Something has changed on Firebase these days.

**Comment by tcha-tcho** [comment]
Oh, I see. You will have to follow this:
https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_function_invocation

**Comment by fractalbob** [comment]
I'm seeing this problem with Android, not Web.

**Comment by malcolmdeck** [comment]
Sorry for the delay. I've filed a bug internally to see why this might happen (b/160169561).

**Comment by malcolmdeck** [comment]
Is this still an issue? We haven't had any reports of this kind in 6 months.

**Comment by fractalbob** [comment]
I have not seen this problem in a while. As far as I'm concerned, you can
close the bug report.

**Comment by NkosiM** [comment]
@malcolmdeck 
When i go to my site ...www.wesit.co.za,

i get the following error:

Error: Forbidden
Your client does not have permission to get URL /ssr/ from this server.

ref:_00D1Ux0Jq._5003p2U5cNR:ref
