### ISSUE TITLE
signInWithEmail:failure

### ISSUE THREAD

**Issue by ahmed-abo-bakr** [firebase/firebase-android-sdk#1364]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _3.5.2____
  * Firebase Component: _____ (Authentication)
  * Component version: _____

#### Steps to reproduce:

signInWithEmail:failure 
FirebaseAuthInvalidCredentialsException: The password is invalid or the user does not have a password.

```
```

**Comment by ashwinraghav** [comment]
We can help you better if you provide the information that we ask for in the issue template. Let us know if you continue facing issues
