### ISSUE TITLE
Veracode issue on firebase-installations

### ISSUE THREAD

**Issue by YessineM** [firebase/firebase-android-sdk#1376]
### Environment

  * Android Studio version: 3.6.1
  * Firebase Component: Messaging, Analytics
  * Component version: firebase-messaging:20.1.2 and firebase-analytics:17.2.3
  * Veracode

#### Description:

Veracode has found low severity issues in com.google.firebase:firebase-installations called:
 **Information Exposure Through Sent Data**, Sensitive information may be exposed as a result of outbound network connections made by the application.

#### Relevant Code:

com.google.firebase:firebase-installations@@16.0.0 249
com.google.firebase:firebase-installations@@16.0.0 309
com.google.firebase:firebase-installations@@16.0.0 337

**Comment by wilhuff** [comment]
Hi! Thanks for writing in.

Please list the file and line number where the issue was found along with the vulnerability reported. When you do we’ll be able to evaluate what’s reported and apply a fix.

As it stands this report isn’t anything we can act on.

**Comment by ankitaj224** [comment]
@andirayo for visibility.

**Comment by andirayo** [comment]
@YessineM :  
Thank you for reporting this!

As @wilhuff pointed out, it would really help us if you could share the **full error message** and if available a **full stack trace**. The problem with the given line numbers (249, 309, 337) is that they most likely belong to an obfuscated version of Firebase Installations and we have to run the line numbers through a deobfuscator before we can make sense of the error message.

**Comment by ankitaj224** [comment]
As @wilhuff mentioned in #1615 - there is no action to be taken in firebase-installations. I will be closing this issue. Please feel free to reopen it if required.

Thanks.
