### ISSUE TITLE
157239535: In android 10 can't open app from a firebase dynamic link(sumsang)

### ISSUE THREAD

**Issue by ljzyljc** [firebase/firebase-android-sdk#1380]
In android 10 I can't open app from a firebase dynamic link(sumsang) when app is in background, but in android 9 or android 8 it can work, google has Restrictions on starting activities from the background(In android 10)，firebase is google's product，so how should I do if I want to make the dynamic link can work in android 10,please help me,thanks!

**Comment by MeghaB** [comment]
Hi @ljzyljc - We're actively monitoring StackOverflow (and also have a great set of community members who are happy to help). These types of questions are best [asked over here](https://stackoverflow.com/questions/tagged/firebase) (questions on usage/etc).
