### ISSUE TITLE
I got this crash every time after first install 

### ISSUE THREAD

**Issue by ProfAhmed** [firebase/firebase-android-sdk#1381]
com.google.firebase.inappmessaging.model.Text$Builder.build (com.google.firebase:firebase-inappmessaging@@19.0.3:116)
com.google.firebase.inappmessaging.internal.InAppMessageStreamManager$$Lambda$12.apply (com.google.firebase:firebase-inappmessaging@@19.0.3)
io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess (MaybeFlatten.java:89)
io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext (FlowableElementAtMaybe.java:80)
io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain (FlowableFlattenIterable.java:313)
io.reactivex.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onNext (FlowableFlattenIterable.java:175)
io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext (FlowableMap.java:57)
io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete (DeferredScalarSubscription.java:118)
io.reactivex.internal.operators.flowable.FlowableToList$ToListSubscriber.onComplete (FlowableToList.java:86)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drainLoop (FlowableFlatMapMaybe.java:327)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drain (FlowableFlatMapMaybe.java:280)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onComplete (FlowableFlatMapMaybe.java:152)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drainLoop (FlowableFlatMapMaybe.java:327)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drain (FlowableFlatMapMaybe.java:280)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onComplete (FlowableFlatMapMaybe.java:152)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drainLoop (FlowableFlatMapMaybe.java:327)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.drain (FlowableFlatMapMaybe.java:280)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onComplete (FlowableFlatMapMaybe.java:152)
io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete (BasicFuseableSubscriber.java:120)
io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onComplete (BasicFuseableConditionalSubscriber.java:119)
io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onComplete (BasicFuseableConditionalSubscriber.java:119)
io.reactivex.internal.operators.flowable.FlowableFromIterable$IteratorConditionalSubscription.fastPath (FlowableFromIterable.java:338)
io.reactivex.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request (FlowableFromIterable.java:123)
io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.request (BasicFuseableConditionalSubscriber.java:152)
io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.request (BasicFuseableConditionalSubscriber.java:152)
io.reactivex.internal.subscribers.BasicFuseableSubscriber.request (BasicFuseableSubscriber.java:153)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onSubscribe (FlowableFlatMapMaybe.java:107)
io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe (BasicFuseableSubscriber.java:67)
io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onSubscribe (BasicFuseableConditionalSubscriber.java:66)
io.reactivex.internal.subscribers.BasicFuseableConditionalSubscriber.onSubscribe (BasicFuseableConditionalSubscriber.java:66)
io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribe (FlowableFromIterable.java:66)
io.reactivex.internal.operators.flowable.FlowableFromIterable.subscribeActual (FlowableFromIterable.java:47)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual (FlowableFilter.java:34)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual (FlowableFilter.java:34)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableFilter.subscribeActual (FlowableFilter.java:37)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual (FlowableFlatMapMaybe.java:54)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual (FlowableFlatMapMaybe.java:54)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe.subscribeActual (FlowableFlatMapMaybe.java:54)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableToList.subscribeActual (FlowableToList.java:44)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual (FlowableMap.java:38)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableFlattenIterable.subscribeActual (FlowableFlattenIterable.java:81)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual (FlowableElementAtMaybe.java:36)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeFlatten.subscribeActual (MaybeFlatten.java:42)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess (MaybeFlatten.java:97)
io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onSuccess (MaybeFlatten.java:120)
io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onSuccess (MaybeOnErrorNext.java:89)
io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess (MaybePeek.java:122)
io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess (MaybePeek.java:122)
io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess (MaybePeek.java:122)
io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onSuccess (MaybePeek.java:122)
io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual (MaybeFromCallable.java:61)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual (MaybePeek.java:56)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual (MaybePeek.java:56)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual (MaybePeek.java:56)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual (MaybePeek.java:56)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual (MaybeOnErrorNext.java:46)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onSuccess (MaybeFlatten.java:97)
io.reactivex.internal.operators.maybe.MaybeOnErrorNext$OnErrorNextMaybeObserver.onSuccess (MaybeOnErrorNext.java:89)
io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver$OtherMaybeObserver.onSuccess (MaybeSwitchIfEmpty.java:108)
io.reactivex.internal.operators.maybe.MaybeJust.subscribeActual (MaybeJust.java:36)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onComplete (MaybeSwitchIfEmpty.java:88)
io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onComplete (MaybePeek.java:167)
io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onComplete (MaybePeek.java:167)
io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver$OtherMaybeObserver.onComplete (MaybeSwitchIfEmpty.java:116)
io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onComplete (MaybePeek.java:167)
io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual (MaybeFromCallable.java:59)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual (MaybePeek.java:56)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onComplete (MaybeSwitchIfEmpty.java:88)
io.reactivex.internal.disposables.EmptyDisposable.complete (EmptyDisposable.java:58)
io.reactivex.internal.operators.maybe.MaybeEmpty.subscribeActual (MaybeEmpty.java:29)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual (MaybeSwitchIfEmpty.java:38)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual (MaybePeek.java:56)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual (MaybePeek.java:56)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual (MaybeSwitchIfEmpty.java:38)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual (MaybeOnErrorNext.java:46)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeFlatten.subscribeActual (MaybeFlatten.java:42)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeFlatten.subscribeActual (MaybeFlatten.java:42)
io.reactivex.Maybe.subscribe (Maybe.java:4073)
io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual (MaybeToFlowable.java:45)
io.reactivex.Flowable.subscribe (Flowable.java:14349)
io.reactivex.Flowable.subscribe (Flowable.java:14295)
io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain (FlowableConcatMap.java:344)
io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext (FlowableConcatMap.java:159)
io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runBackfused (FlowableObserveOn.java:441)
io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run (FlowableObserveOn.java:172)
io.reactivex.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:66)
io.reactivex.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:57)
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by vkryachko** [comment]
Is this still an issue?
