### ISSUE TITLE
inappmessaging uses invalid (stale) InstanceID

### ISSUE THREAD

**Issue by Wrywulf** [firebase/firebase-android-sdk#1382]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: firebase-inappmessaging
  * Component version: 19.0.4

### [REQUIRED] Step 3: Describe the problem
I see a problem when trying to send in-app messages to specific devices (instance ID) using the firebase console. 

Upon a clean install of the app, I retrieve the Instance ID from the logs as stated here https://firebase.google.com/docs/in-app-messaging/get-started?platform=android 

Then use the Firebase In-app Messaging console to "Send to device".

The message isn't picked up by the device and the log states an error:
`Service fetch error: INVALID_ARGUMENT: Request contains an invalid argument. `

If I kill the app process and relaunch, a *new* InstanceID is output in the logs. If I use that InstanceID in the firebase console to "send to device" then the in-app message comes through to the device.

So, it seems that the `FirebaseMessaging` instance is picking up a "stale" InstanceID during the first process launch and doesn't refresh after that until the next process re-creation.

I added logs to my (single Activity) onResume, logging the InstanceID retrieved from `FirebaseInstanceId.getInstance().instanceId.addOnCompleteListener`. I noticed that the InstanceID is `X` upon the first onResume after initial process launch (ie after clear storage). Then, if app is just backgrounded and foregrounded again, onResume logs a new instance ID `Y`. However, `Y` is only picked up by the In-app messaging lib if I kill -> restart the process.

#### Steps to reproduce:

1. Install app using Firebase In-app messaging
2. Monitor FIAM.Headless logs and retrieve Instance ID, as described in https://firebase.google.com/docs/in-app-messaging/get-started?platform=android
3. Go to Firebase Console, create new campaign (content irrelevant)
4. Send the in-app message to device using InstanceID from step #2
5. App background -> foreground
6. Note In-app message is not shown. Logs have FIAM.Headless error: `Service fetch error: INVALID_ARGUMENT: Request contains an invalid argument. `
7. kill app process (ie. using recents swipe-up)
8. restart app
9. Notice in FIAM.Headless logs that InstanceID is difference than in step #2
10. Use InstanceID from step #9 to "send to device" in firebase console
11. App background -> foreground
12. Verify in-app message is shown.

**Comment by ashwinraghav** [comment]
Thank you for the report. I've tried repro-ing your issue with version `19.0.7` and I have not been able to. Instance Ids are intended to be immutable through the lifetime of an app installation. The Ids can also be generated offline. Please double check whether you have any unintended invocations of [deleteInstanceId](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#deleteInstanceId())
