### ISSUE TITLE
FirebaseVisionImage.fromMediaImage did not convert to bitmap correctly

### ISSUE THREAD

**Issue by lunayo** [firebase/firebase-android-sdk#1389]
The result of `FirebaseVisionImage.fromMediaImage().bitmap` does not correctly render the image (strange horizontal scan line) compare to using renderscript `ScriptIntrinsicYuvToRGB`. The incoming image format `ImageFormat.YUV_420_888`.
Below is the result of using `FirebaseVisionImage.fromMediaImage()` and `ScriptIntrinsicYuvToRGB`. Notice that there is a visible scan line on the image when zooming in converted using `FirebaseVisionImage`.
Firebase
![firebase](https://user-images.githubusercontent.com/1026496/77528276-97f2ae80-6ec8-11ea-9bc8-b2ba56be2e89.png)
Renderscript
![renderscript](https://user-images.githubusercontent.com/1026496/77528309-a640ca80-6ec8-11ea-896d-48c902e62748.png)

**Comment by samtstern** [comment]
@lunayo I have transferred your bug over to this repository since it seems like you're reporting an issue in the MLKit SDK.

**Comment by argzdev** [comment]
Hi @lunayo, just bumping this thread. May I ask if you're still encountering this issue on the latest SDK?
