### ISSUE TITLE
When trying to get a token, the exception SERVICE_NOT_AVAILABLE is coming out on WEAR OS device

### ISSUE THREAD

**Issue by frodonumb** [firebase/firebase-android-sdk#1395]
### Describe your environment

  * Android Studio version: 3.5.1
  * Firebase Component: Firebase Core & Cloud Messaging
  * Component version: 
     firebase-messaging:20.1.3
     google-services:4.3.2
     firebase-analytics:17.2.3

### Describe the problem
WearOS devices connected to some of iPhone (but not for all iPhone devices, on some of them it's working fine) recently started getting SERVICE_NOT_AVAILABLE errors when calling FirebaseInstanceId.getInstanceId(). 

A watch os version: [Ticwatch](https://prnt.sc/ro6zw4)

#### Steps to reproduce:

Connect Ticwatch Pro to an iPhone device. Waiting for FirebaseMessagingService onNewToken but nothing happened, trying to get FirebaseInstanceId.getInstance().getInstanceId() and on callback task not successful with message SERVICE_NOT_AVAILABLE

#### Relevant Code:

```
FirebaseInstanceId.getInstance().getInstanceId()
                .addOnCompleteListener(task -> {
                    if (!task.isSuccessful()) {
                        Timber.e(task.getException());
                        return;
                    }
                    String token = Objects.requireNonNull(task.getResult()).getToken();
                    getSharedPreferences("_", MODE_PRIVATE).edit().putString("fb", token).apply();
                });
```

**Comment by andirayo** [comment]
@frodonumb :  This sounds like there might be Firebase options missing during initialization of Firebase, or otherwise misconfigured FirebaseApp instance that prevents the Firebase Installations SDK (FIS), a new dependency of FirebaseInstanceId, to successfully communicate to its servers.

A couple of questions to you:
* Do you have a full stack trace of the error that occurs.
* Are you willing to share either project number, project ID, or Firebase application ID, so I can check our logs for failing client requests to confirm/reject my assumption?

**Comment by frodonumb** [comment]
> @frodonumb : This sounds like there might be Firebase options missing during initialization of Firebase, or otherwise misconfigured `FirebaseApp` instance that prevents the Firebase Installations SDK (FIS), a new dependency of `FirebaseInstanceId`, to successfully communicate to its servers.
> 
> A couple of questions to you:
> 
> * Do you have a full stack trace of the error that occurs.
> * Are you willing to share either project number, project ID, or Firebase application ID (which is non-secret information about your application), so I can check our logs for failing client requests to confirm/reject my assumption?

@andirayo i don't think so, because on some of wear os devices connected to iPhone it works fine, and no problems with taking token from `FirebaseInstanceId`.
For first i haven't set up yet crashlytics, i'll give it as soon as possible.
For second i can share Firebase application ID : time-4a5b9.

**Comment by andirayo** [comment]
@frodonumb :  
The behavior described by you can be symptomatic for missing Firebase options.

#### Background
`FirebaseInstanceId` is an infrastructure service that is used by various Firebase services like Messaging (FCM).
With the recent version (v20.1.0), FirebaseInstanceId introduced a new dependency: The Firebase Installations SDK (FIS).

Firebase Installations is an infrastructure service (identity provider and authentication scheme) that is used under the hood by many Firebase services (like Analytics). Usually, you do not need to explicitly include it, but you will get it as transitive dependency (through Firebase InstanceId).

Different to most Firebase SDKs, `FirebaseInstanceId` did **not**  require a valid API key to function. However, Firebase Installations does. Thus, a misconfiguration might only have become apparent with the recent version update.

Old installations of your applications already have valid FCM registration tokens which are necessary to send push notifications. New installations might not be able to get those tokens and thus malfunction.

####  Your app
Thank you for sharing your Project ID. 
I looked into our server logs. However I can only see 5 (successful) requests in the last week for this project. Are you sure you gave me the correct identifier (and the ID of a test project)?

fyi: I will try to reach out to you via email to make debugging easier.

**Comment by frodonumb** [comment]
> @frodonumb :
> The behavior described by you can be symptomatic for missing Firebase options.
> 
> #### Background
> `FirebaseInstanceId` is an infrastructure service that is used by various Firebase services like Messaging (FCM).
> With the recent version (v20.1.0), FirebaseInstanceId introduced a new dependency: The Firebase Installations SDK (FIS).
> 
> Firebase Installations is an infrastructure service (identity provider and authentication scheme) that is used under the hood by many Firebase services (like Analytics). Usually, you do not need to explicitly include it, but you will get it as transitive dependency (through Firebase InstanceId).
> 
> Different to most Firebase SDKs, `FirebaseInstanceId` did **not** require a valid API key to function. However, Firebase Installations does. Thus, a misconfiguration might only have become apparent with the recent version update.
> 
> Old installations of your applications already have valid FCM registration tokens which are necessary to send push notifications. New installations might not be able to get those tokens and thus malfunction.
> 
> #### Your app
> Thank you for sharing your Project ID.
> I looked into our server logs. However I can only see 5 (successful) requests in the last week for this project. Are you sure you gave me the correct identifier (and the ID of a test project)?
> 
> fyi: I will try to reach out to you via email to make debugging easier.

@andirayo yes i'm sure, there are not many active users now, the project is under testing

**Comment by ankitaj224** [comment]
@frodonumb Really sorry not responding earlier. Are you still facing the same issue?
