### ISSUE TITLE
FirebaseVisionImage.fromMediaImage(cameraImage, rotationDegrees) is super slow.

### ISSUE THREAD

**Issue by homandiy** [firebase/firebase-android-sdk#1398]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.1_____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)

    // firebase
    implementation 'com.google.firebase:firebase-ml-vision:24.0.1'
    // If you want to detect face contours (landmark detection and classification
    // don't require this additional model):
    implementation 'com.google.firebase:firebase-ml-vision-face-model:19.0.0'
    implementation 'com.google.firebase:firebase-core:17.2.3'

  * Component version: _____
    // Use the most recent version of CameraX, currently that is alpha10.
    def camerax_version = '1.0.0-beta01'
    // CameraX core library using the camera2 implementation
    //implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    // If you want to use the CameraX View class
    implementation "androidx.camera:camera-view:1.0.0-alpha08"
    // If you want to use the CameraX Extensions library
    implementation "androidx.camera:camera-extensions:1.0.0-alpha08"
    // If you want to use the CameraX Lifecycle library
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"

### [REQUIRED] Step 3: Describe the problem
FirebaseVisionImage took 19 seconds to transform an image from YUV_420_888 format.

#### Steps to reproduce:

What happened? How can we make the problem occur?
I call from ImageAnalysis Use Case of CameraX beta 01.

            faceAnalysis = ImageAnalysis.Builder().apply {
                setTargetAspectRatio(screenAspectRatio)
                setTargetRotation(rotation)
                setImageQueueDepth(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
            }.build()
            val analyzer = FaceAnalyzer(rotation).apply {
                pointsListListener = { points ->
                    if (points.isNotEmpty()) faceContourImage.points = points
                }
                analysisSizeListener = {
                    //updateOverlayTransform(overlayRef.get(), it)
                }
            }
            faceAnalysis.setAnalyzer(executor, analyzer)

This could be a description, log/console output, etc.
logcat:
2020-03-30 00:06:43.192 32257-32413 I/MYLOG FaceAnalyzer: image: 1280 x 720 <= YUV_420_888
2020-03-30 00:06:43.192 32257-32413 I/MYLOG FaceAnalyzer: Before transform from YUV_420_888 to FirebaseVisionImage...
2020-03-30 00:07:02.852 32257-32413 I/MYLOG FaceAnalyzer: After transform from YUV_420_888 to FirebaseVisionImage...
2020-03-30 00:07:08.783 32257-32257 I/MYLOG FaceAnalyzer: FaceAnalyzer detected faces:   0

#### Relevant Code:
class FaceAnalyzer(_rotation: Int) : ImageAnalysis.Analyzer {
    private var lastAnalyzedTimestamp = 0L
    private val rotationDegrees = _rotation
    private var isAnalyzing = AtomicBoolean(false)

    // Surface rotation to firebase rotation
    private fun degreesToFirebaseRotation(rotationDegrees: Int): Int {
        return when (rotationDegrees) {
            Surface.ROTATION_0  -> FirebaseVisionImageMetadata.ROTATION_0
            Surface.ROTATION_90 -> FirebaseVisionImageMetadata.ROTATION_90
            Surface.ROTATION_180 -> FirebaseVisionImageMetadata.ROTATION_180
            Surface.ROTATION_270 -> FirebaseVisionImageMetadata.ROTATION_270
            else -> throw IllegalArgumentException("Rotation must be 0, 90, 180, or 270.")
        }
    }

    private val faceDetector: FirebaseVisionFaceDetector by lazy {
        val options = FirebaseVisionFaceDetectorOptions.Builder()
            .setContourMode(FirebaseVisionFaceDetectorOptions.ALL_CONTOURS)
            .build()
        FirebaseVision.getInstance().getVisionFaceDetector(options)
    }

    // Callback functions:
    // Grab the points from the successful analysis to Caller
    var pointsListListener: ((List<PointF>) -> Unit)? = null
    // Send this value back to Caller
    var analysisSizeListener: ((Size) -> Unit)? = null
    // Get face data
    //var facesCountListener: ((Int) -> Unit)? = null

    private fun getImageFormat(image: Image): String {
        var imgFormat = ""
        when (image.format) {
            ImageFormat.YUV_420_888 -> imgFormat = "YUV_420_888"
            ImageFormat.NV21 -> imgFormat = "NV21"
            ImageFormat.YV12 -> imgFormat = "YV21"
        }
        return imgFormat
    }

    @RequiresApi(Build.VERSION_CODES.P)
    @SuppressLint("UnsafeExperimentalUsageError")
    override fun analyze(image: ImageProxy) {

        val cameraImage = image.image ?: return
        lgv("image: ${cameraImage.width} x ${cameraImage.height} <= ${getImageFormat(cameraImage)}")

        // Detecting Face: Don't move on until the task is finished.
        if (isAnalyzing.get()) return
        isAnalyzing.set(true)

        // Set size
        analysisSizeListener?.invoke(Size(image.width, image.height))

        /*
        val imageByteArray = YUV_420_888toNV21(cameraImage)

        // Translate rotation to firebase vision style
        val imageRotation = degreesToFirebaseRotation(rotationDegrees)
        lgi("rotation = $rotationDegrees .... imageRotation = $imageRotation")

        val metadata = FirebaseVisionImageMetadata.Builder()
            .setWidth(image.width)
            .setHeight(image.height)
            .setFormat(FirebaseVisionImageMetadata.IMAGE_FORMAT_NV21)
            .setRotation(imageRotation)
            .build()
        */

        lgi ("Before transform from YUV_420_888 to FirebaseVisionImage...")
        val fvImage =
            FirebaseVisionImage.fromMediaImage(cameraImage, rotationDegrees)
        lgi ("After transform from YUV_420_888 to FirebaseVisionImage...")

        image.close()

        val result = faceDetector.detectInImage(fvImage)
            .addOnSuccessListener(successListener)
            .addOnFailureListener(failureListener)

    }

    private val successListener = OnSuccessListener<List<FirebaseVisionFace>> { faces ->
        isAnalyzing.set(false)

        val count = faces.size
        lgv("FaceAnalyzer detected faces:   $count")

        if (count > 0 ) {
            val points = mutableListOf<PointF>()
            for (face in faces) {
                val contours = face.getContour(FirebaseVisionFaceContour.ALL_POINTS)
                points += contours.points.map { PointF(it.x, it.y) }
            }

            // update points to the Caller
            pointsListListener?.invoke(points)
        } else {
            lgi( "Face Not Found...")
        }
    }

    private val failureListener = OnFailureListener { e ->
        isAnalyzing.set(false)
        lge("FaceAnalyzer-Face analysis failure.\n$e")
    }

    companion object {
        private val TAG = "MYLOG " + FaceAnalyzer::class.java.simpleName
        fun lge(s: String) { Log.e(TAG, s) }
        fun lgi(s: String) { Log.i(TAG, s) }
        fun lgd(s: String) { Log.i(TAG, s) }
        fun lgv(s: String) { Log.i(TAG, s) }
    }
}
```
// TODO(you): code here to reproduce the problem
I set a breakpoint at fvImage. You will see the problem. If I use bufferArray, the problem will be gone. But the ImageAnalysis is still clogged. The ImageAnalysis become a one time role because of FirebaseVisionImage.
```

**Comment by lunayo** [comment]
how about trying this firebase option for faster face tracking, and reduce your image size to 680x480
`FirebaseVisionFaceDetectorOptions.Builder()
                    .setPerformanceMode(FirebaseVisionFaceDetectorOptions.FAST)
                    .setContourMode(FirebaseVisionFaceDetectorOptions.ALL_CONTOURS)
                    .enableTracking()
                    .build()`

**Comment by argzdev** [comment]
Hi @homandiy, just bumping this thread. Since this issue has been stale for a while now, may I ask if you're still encountering the issue on the latest SDK version?
