### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by sskynomad** [firebase/firebase-android-sdk#1412]
Hello, I just want to clarify my current dilemma with firebase authentication for android. 

I can't log in with my "google sign-in" if I do "build & run" from unity, while my device is connected.

I feel that I am missing a certificate, and I only know enough to publish my app in the play store.

the one from my beta branch that is available on the play store, works perfectly fine.

I hope you guys can help me figure out what I'm missing here. thank you very much.

**Comment by malcolmdeck** [comment]
I'm totally guessing here, but I think that your local build probably has a different signing key than the one uploaded to the play store - you should check the signing certificate of each application and compare them. If they're different, add the missing one to the app's configuration for Google Sign-In and try again.

**Comment by sskynomad** [comment]
Hi, malcolmdeck, 

thank you for the response, I will compare my certificates on my signing Keystore, with firebase console and google play console, will update on the result.
