### ISSUE TITLE
Docs and code snippet for useFunctionsEmulator

### ISSUE THREAD

**Issue by jQrgen** [firebase/firebase-android-sdk#1416]
## What feature would you like to see?
Docs and code snippet for useFunctionsEmulator

## How would you use it?
To know how to test android apps with functions locally.

**Comment by jQrgen** [comment]
Related issue: https://github.com/firebase/quickstart-android/issues/562

**Comment by samtstern** [comment]
I added this comment:
https://github.com/firebase/quickstart-android/issues/562#issuecomment-607819116

Let's keep the discussion over there.
