### ISSUE TITLE
Move optional ML features to dynamic feature modules is not possible

### ISSUE THREAD

**Issue by b95505017** [firebase/firebase-android-sdk#1419]
https://firebase.google.com/docs/ml-kit/android/reduce-app-size#advanced_move_optional_ml_features_to_dynamic_feature_modules

The doc says that we could move ML to dynamic feature, but I think it will effect the whole firebase app modules because of `ComponentDiscoveryService`.

All firebase modules depends on registering the extended `ComponentRegistrar` classes so that `FirebaseApp` init will discover them via `AndroidManifest` once. This flow will cause firebase components can't move to dynamic feature while base module has other components.

**Comment by b95505017** [comment]
Anyone could help this issue?

**Comment by b95505017** [comment]
@andirayo Could you help me with this issue? Thanks

**Comment by ashwinraghav** [comment]
Thanks for raising this. Your observations are correct. This requires some ground up redesign of component discovery. The good news is that we are working on a fix. Please let us know if you would like to try the alpha and we'll give you an early release candidate.

**Comment by b95505017** [comment]
@ashwinraghav LGTM, please let me in. I'm also in the firebase alpha group.

**Comment by b95505017** [comment]
@ashwinraghav Any progress? It seems that ML features are moving to MlKit packages recently, not sure how this issue be tracked.

**Comment by vkryachko** [comment]
Moving this issue to new MLKit's repo: https://github.com/googlesamples/mlkit/issues/224
