### ISSUE TITLE
Smoke test flakiness, debug mode

### ISSUE THREAD

**Issue by gsoltis** [firebase/firebase-android-sdk#144]
CI failure, I think for RTDB, from a Firestore change: https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/68/smoke-tests-debug/1067542178764427268/

**Comment by rsgowman** [comment]
Also every PR I've tried to submit recently. Here's a few:

https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/135/smoke-tests-release/1067841275165675523/

https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/143/smoke-tests-release/1067548974551928832/

Arbitrarily assigning to Vlad (but feel free to redirect).

**Comment by wilhuff** [comment]
Still happening:

https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/188/smoke-tests-debug/1083872378095669248/

https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/192/smoke-tests-debug/1083874013949726724/

**Comment by mikelehen** [comment]
Still happening.  RTDB test failures blocking Firestore changes from going through CI:

```
I0205 00:44:23.664] com.google.firebase.testapps.database.TestActivityTest > testActivityTest[test(AVD) - 9] FAILED 
I0205 00:44:23.664] 	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
I0205 00:44:23.664] 	Root{application-window-token=android.view.ViewRootImpl$W@d1b53a4, window-token=android.view.ViewRootImpl$W@d1b53a4, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302f8
```

https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/68/smoke-tests-debug/1067542178764427268/

**Comment by mikelehen** [comment]
Again. Failed in both smoke-tests-debug and smoke-tests-release:
```
I0207 02:09:43.805] com.google.firebase.testapps.database.TestActivityTest > testActivityTest[test(AVD) - 9] FAILED 
I0207 02:09:43.805] 	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
I0207 02:09:43.806] 	Root{application-window-token=android.view.ViewRootImpl$W@4eba483, window-token=android.view.ViewRootImpl$W@4eba483, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302f8
```

https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/233/smoke-tests-release/1093328310659715076/
https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/233/smoke-tests-debug/1093328310659715075/

**Comment by mikelehen** [comment]
and again...

**Comment by mikelehen** [comment]
In case there was any doubt, this still happens!

https://storage.googleapis.com/android-ci/pr-logs/pull/firebase_firebase-android-sdk/233/smoke-tests-debug/1104108473362157572/build-log.txt

**Comment by vkryachko** [comment]
Closing, since smoke tests are no longer around
