### ISSUE TITLE
firebase runtransaction android null first time

### ISSUE THREAD

**Issue by kksingla** [firebase/firebase-android-sdk#1447]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository firebase realtime database. 

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: Database
  * Component version: Run Transaction

### [REQUIRED] Step 3: Describe the problem
I have used transaction much time and it is working fine as expected but in this project, I found a very weird bug:
firebase runtransaction gives me mutable data value null first time only.

I have tried without transaction it is working perfectly.

#### Steps to reproduce:

What happened? How can we make the problem occur?

tHead is null for the first time only.

#### Relevant Code:
dbRTD.child(FBConstant.TransactionHead.Head)
                .child(txnDO.tHeadId)
                .runTransaction(object : Transaction.Handler {
                    override fun onComplete(p0: DatabaseError?, p1: Boolean, p2: DataSnapshot?) {
                    }

                    override fun doTransaction(p0: MutableData): Transaction.Result {
                        val tHead = p0.getValue(TransactionHeadDO::class.java)
                        return if (tHead == null) {
                            sendError(listener, getString(R.string.server_error))
                            Transaction.abort()
                        } else {
                            tHead.amt = 0
                            tHead.notes = "Settled"
                            tHead.setModified()

                            p0.value = tHead

                            val ref = dbRTD.child(FBConstant.Transaction.Head)
                                    .child(tHead.id)
                                    .push()
                            txnDO.id = ref.key!!
                            txnDO.setCreated()
                            ref.setValue(txnDO)
                            sendResponse(listener, txnDO)
                            Transaction.success(p0)
                        }
                    }
                })

**Comment by schmidt-sebastian** [comment]
@kksingla Thanks for filing this issue!

The behavior you are describing is as designed. Transaction are first served from cache - if there is no cached value, the SDK uses "null". Only when we first attempt to commit the transaction do we obtain the actual values from the backend. This then allows us to provide non-null values for our second attempt.

For more information, please take a look at the answer here: https://stackoverflow.com/questions/35818946/firebase-runtransaction-not-working-mutabledata-is-null

**Comment by kksingla** [comment]
@schmidt-sebastian, so how I can verify the transaction, my use case is,

I'm creating an expense app, where I have a transaction head along with transaction details. Whenever a new transaction is added, I have to update the transaction head as a new balance.

Please suggest

**Comment by schmidt-sebastian** [comment]
If you want to follow the spirit of the transaction API:
- Handle `null` as "no balance exists" and create a new balance. The server will then reject the new balance if the the balance already existed and invoke your transaction loop again.

If you just want to unblock your usage:
- Return a random value if you know that data exist on the server but your transaction loop receives `null` as its input. Again, the server will reject the transaction and run it again.
