### ISSUE TITLE
Firebase Auth REST API for login using phone number

### ISSUE THREAD

**Issue by anotherdev** [firebase/firebase-android-sdk#1466]
## Firebase Auth REST API for login using phone number

I'm working on an SDK for Firebase Auth on Android devices without Google Play Services. I'm basing my implementation from [FirebaseExtended/auth-without-play-services](https://github.com/FirebaseExtended/auth-without-play-services) which use [Firebase Auth REST API](https://firebase.google.com/docs/reference/rest/auth). I was able to implement couple of auth providers, but phone number auth provider is missing from the official document.

I'm aware that Firebase team is working on a solution to allow Firebase Auth to work without GMS, but until then I need to support current apps to [authenticate with Firebase using a Phone Number](https://firebase.google.com/docs/auth/android/phone-auth).

## How would you use it?

The SDK will provide phone number login capability for apps on Android devices that doesn't have Google Play Services.

**Comment by katowulf** [comment]
Firebase Auth requires Google Play services.
