### ISSUE TITLE
Crashlytics still send crash report in debugging mode

### ISSUE THREAD

**Issue by anderscheow** [firebase/firebase-android-sdk#1481]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6,2
  * Firebase Component: Firebase Crashlytics (Database, Firestore, Storage, Functions, etc)
  * Component version: 17.0.0-beta04

#### Steps to reproduce:

During debugging mode, Crashlytics still send the crash report and visible in Firebase Crashlytics Dashboard

#### Relevant Code:

```
FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(BuildConfig.DEBUG.not())
```

```
debug {
            minifyEnabled false
            firebaseCrashlytics {
                // If you don't need crash reporting for your debug build,
                // you can speed up your build by disabling mapping file uploading.
                mappingFileUploadEnabled false
            }
        }
```

**Comment by kevinkokomani** [comment]
Hi there - could you give more info on what "BuildConfig.DEBUG.not()" is doing exactly? It looks like you're disabling the mapping file upload, not crash report upload. The way to disable crash reports can be found here: https://firebase.google.com/docs/crashlytics/customize-crash-reports-new-sdk?platform=android#enable-reporting

`FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(false);`
or, in your AndroidManifest.xml:
```
<meta-data
    android:name="firebase_crashlytics_collection_enabled"
    android:value="false" />
```

**Comment by anderscheow** [comment]
```FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(BuildConfig.DEBUG.not())```

equivalent to 

```
if (BuildConfig.DEBUG) {
FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(false)
} else {
FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true)
}
```

**Comment by anderscheow** [comment]
Alright, I'll test again and see whether the issue still persist.

**Comment by mrwillis21** [comment]
Closing this, as we haven't heard back. Please feel free to re-open if this is still a concern.
