### ISSUE TITLE
crashlyticsUploadDeobsProductionRelease takes long time

### ISSUE THREAD

**Issue by vivchar** [firebase/firebase-android-sdk#1483]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.3
  * Firebase Component: crashlytics
  * Component version: 2.10.1

#### Steps to reproduce:
run ./gradlew assembleRelease
Result: crashlyticsUploadDeobsProductionRelease takes long time ~20-40 mins
```
<===<=<============-> 99% EXECUTING [16m 55s]
> :application:crashlyticsUploadDeobsProductionRelease
```
Then you can see timeout error
```
> Task :application-paltalk:crashlyticsUploadDeobsProductionRelease
 WARN - Crashlytics had a problem uploading the deobs file. Please check network connectivity and try again...
```

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by kevinkokomani** [comment]
Which version of the Fabric Gradle plugin are you using? Here's the list of versions in case it's useful: https://docs.fabric.io/android/changelog.html#fabric-gradle-plugin.
