### ISSUE TITLE
Data always mapped with default boolean value

### ISSUE THREAD

**Issue by Merseyside** [firebase/firebase-android-sdk#1489]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1 Canary 5
  * Firebase Component: Firestore
  * Component version: 21.4.2

### [REQUIRED] Step 3: Describe the problem
It looks like a mirror of https://github.com/firebase/firebase-android-sdk/issues/544

Everything works well excluding mapping of boolean value. I checked names in firestore console and in my model, it is equals. Also I logged data from response object, it contains valid boolean value. But toObject doesn't work as expected, always returns me a model with default boolean value.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
val obj = response.toObject(T::class.javaObjectType)
```

**Comment by Merseyside** [comment]
I found a reason!

I changed type of variable to Int and it happened again. After that I changed name of key in console and model(isNew -> new). And now it works.

**Comment by schmidt-sebastian** [comment]
@Merseyside Thanks for reporting this. It sounds like you may have gotten your field names mixed up and that you were able to fix this issue. Based on this understanding, I will close this issue.

If my understanding is not correct, would you mind providing a small repro app for us? We can then re-open this issue and continue with our investigation of #544 in this issue.
