### ISSUE TITLE
Probability of occurrence in performace sdk 19.0.5 

### ISSUE THREAD

**Issue by nshzzu130** [firebase/firebase-android-sdk#1494]
from firebase Crashlytics console,I found some crash issue in performance sdk code,about 500+ everyday, crash rate 0.5% in my app,but i can't reproduce this issue, Probability of occurrence.

below is the log,can anyone who kindly help me? my google service version is 17.0.0

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.google.firebase.perf.internal.zzv.zzc(boolean)' on a null object reference
com.google.firebase.perf.internal.zzf.zzd (com.google.firebase:firebase-perf@@19.0.5:170)
com.google.firebase.perf.internal.zzi.run (com.google.firebase:firebase-perf@@19.0.5:2)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:762)

Fatal Exception: java.lang.IllegalStateException
com.google.firebase.iid.FirebaseInstanceId.zzl (com.google.firebase:firebase-iid@@20.1.1:75)
com.google.firebase.iid.FirebaseInstanceId.getId (com.google.firebase:firebase-iid@@20.1.1:49)
com.google.firebase.perf.internal.zzf.zzbu (com.google.firebase:firebase-perf@@19.0.5:181)
com.google.firebase.perf.internal.zzf.zzbt (com.google.firebase:firebase-perf@@19.0.5:44)
com.google.firebase.perf.internal.zzf.zzc (com.google.firebase:firebase-perf@@19.0.5:195)
com.google.firebase.perf.internal.zze.run (com.google.firebase:firebase-perf@@19.0.5:2)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)

**Comment by nshzzu130** [comment]
`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.google.firebase.perf.internal.zzv.zzc(boolean)' on a null object reference
com.google.firebase.perf.internal.zzf.zzd (com.google.firebase:firebase-perf@@19.0.5:170)
com.google.firebase.perf.internal.zzi.run (com.google.firebase:firebase-perf@@19.0.5:2)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:762)

Fatal Exception: java.lang.IllegalStateException
com.google.firebase.iid.FirebaseInstanceId.zzl (com.google.firebase:firebase-iid@@20.1.1:75)
com.google.firebase.iid.FirebaseInstanceId.getId (com.google.firebase:firebase-iid@@20.1.1:49)
com.google.firebase.perf.internal.zzf.zzbu (com.google.firebase:firebase-perf@@19.0.5:181)
com.google.firebase.perf.internal.zzf.zzbt (com.google.firebase:firebase-perf@@19.0.5:44)
com.google.firebase.perf.internal.zzf.zzc (com.google.firebase:firebase-perf@@19.0.5:195)
com.google.firebase.perf.internal.zze.run (com.google.firebase:firebase-perf@@19.0.5:2)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)`

**Comment by visumickey** [comment]
At a quick look of it, this issue is very similar to #1528 . Marking this as a duplicate as the other issue is tracking the progress.
