### ISSUE TITLE
Unboxing of "x" may produce a null pointer exception

### ISSUE THREAD

**Issue by Danbo84** [firebase/firebase-android-sdk#1504]
Hello I got this error during devloppement of my appliacation in java in android sutdio :

https://pastebin.com/5H0URydz

Here is the code whitch has a problem :

https://pastebin.com/99nm8ghT

Thanks for your help !
Hugo

**Comment by schmidt-sebastian** [comment]
@Danbo84 Thanks for filing this issue.

The Firestore code you are invoking is as follows:

```
  public Long getLong(@NonNull String field) {
    Number val = getTypedValue(field, Number.class);
    return val != null ? val.longValue() : null;
  }
```

That is, we either return a `long` (boxed into a `Long`) or `null`. If we return `null` and this is passed to a method that expects a primitive number type (such as `Float.valueOf(`), Java will attempt to unbox the supposed `Long` type via `Long.longValue()` (see https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.8). This then cause the NullPointerException you see.

I assume that your document does not have a value for `totalMoney` and we return null. Can you verify whether that is the case?
