### ISSUE TITLE
All ID ' s Property deserialize to Null

### ISSUE THREAD

**Issue by harunkaraca** [firebase/firebase-android-sdk#1505]
`@IgnoreExtraProperties
data class Item(
    var Name:String? = null,
    var ID:Int? = null)`
When i use above code. All ID's deserializing to null
<img width="310" alt="Screen Shot 2020-04-28 at 00 57 02" src="https://user-images.githubusercontent.com/11999913/80424996-7df32400-88eb-11ea-93ac-99bbae2217bf.png">

But below code works fine
`@IgnoreExtraProperties
data class Item(
    var Name:String? = null,
    @get:PropertyName("ID") var ID:Int = 0)`

<img width="297" alt="Screen Shot 2020-04-28 at 00 58 25" src="https://user-images.githubusercontent.com/11999913/80425011-83e90500-88eb-11ea-8a6a-01bbdfc0a9f4.png">

**Comment by schmidt-sebastian** [comment]
@harunkaraca Thanks for filing this.

I am unfortunately not able to reproduce this on my end.

```
@IgnoreExtraProperties
data class Pojo(var Name:String? = null, var ID:Int? = null)

var pojo = Pojo();
pojo.Name = "foo";
pojo.ID = 12;
firestore.document("foo/bar").set(pojo);
firestore.document("foo/bar").get().addOnSuccessListener { doc ->
   var pojo2 = doc.toObject(Pojo::class.java);
   println(pojo2?.ID);
}
```

![Screen Shot 2020-04-29 at 10 24 08 AM](https://user-images.githubusercontent.com/19397744/80626672-a66e4180-8a03-11ea-8eae-88b98879d3c2.png)

Do you mind providing a small example app for us?

**Comment by harunkaraca** [comment]
@schmidt-sebastian  i am using a firebase realtime db.
<img width="553" alt="Screen Shot 2020-04-29 at 22 32 00" src="https://user-images.githubusercontent.com/11999913/80638605-60e45f80-8a69-11ea-84ce-1fe80200babf.png">

I will make an example app. As soon as possible

**Comment by schmidt-sebastian** [comment]
I thought you were using Firestore :) I will try this again using the RTDB.

**Comment by schmidt-sebastian** [comment]
Same behavior for me using the RTDB. I will need a reproduction.
