### ISSUE TITLE
Incorrect namespace when using database emulator

### ISSUE THREAD

**Issue by anton9088-new** [firebase/firebase-android-sdk#1509]
production database URL looks like this:
https://chat-2df58.firebaseio.com

emulated database URL looks like this:
http://10.0.2.2:9000?ns=chat-2df58

When I initialize the database using this method:
`FirebaseDatabase.getInstance('<database_url>');`

Namespace is parsed from the URL as a substring from the beginning to the first dot.
It works correctly with the production URL, the namespace will be `chat-2df58`.
But if you want to connect to a database emulator, the namespace will be `10` which is completly wrong.

And because of this you cannot fetch the data in the right way:
http://localhost:9000/.json?ns=chat-2df58

Instead you must use following url:
http://localhost:9000/.json?ns=10

**Expected behavior:**
If the `ns` url parameter is present, use it as a namespace.
If not, parse namespace from the begginning of the URL to the first dot.

**Comment by schmidt-sebastian** [comment]
@anton9088-new Thanks for taking the time to file this issue.

What version of the RTDB SDK are you using? The `ns` query parameter is only supported as of version 19.1.0.

**Comment by anton9088-new** [comment]
I'm using the latest firebase_database 3.1.5 for Flutter
The Flutter library seems to be using an old version of the Android library - 17.0.0

**Comment by schmidt-sebastian** [comment]
I filed internal bug b/155236935 to get the dependency updated.

**Comment by greenlover1991** [comment]
Thanks for reporting this issue! This lead me to your fix https://github.com/firebase/firebase-android-sdk/pull/680 and found a workaround for my case (Flutter + Windows 10 + `firebase_database` 3.1.6). Sharing my workaround just in case anyone need it and while waiting for the dependency to be updated:

Workaround for your Flutter app in Android Emulator to connect to Local Firebase Emulator Suite:
1. Suppose your `databaseURL` is `http://10.0.2.2:9000/?ns=my-project-123`, [add a custom host](https://stackoverflow.com/questions/41117715) name inside your Android Emulator. The host name entry should look something like: `10.0.2.2 my-project-123.dummy.com`
2. Then in your Flutter code use it as: 
```dart
final dbRef = FirebaseDatabase(databaseURL: "http://my-project-123.dummy.com:9000")
        .reference()
```
3. The Flutter app will now connect to the local Firebase Emulator Suite

They should really place that in the Flutter or Firebase documents that the `firebase_database` plugin does not yet support the `ns` parameter.

**Comment by kroikie** [comment]
@anton9088-new The firebase_database and other plugins are in the process of being updated to use the latest versions of the Android SDKs. Sorry for the delay on this, we are working on it.

**Comment by rlazo** [comment]
The dep should be up to date now.  Thanks!
