### ISSUE TITLE
FirebaseCrashlytics setUserId parameter is annotated with NotNull instead of Nullable

### ISSUE THREAD

**Issue by niqo01** [firebase/firebase-android-sdk#1512]
**Description**
FirebaseCrashlytics should allow setting null user id in order to handle the use case where the user signs out of the application. This behavior was supported in Fabric.

**Issue**
Today, the FirebaseCrashlytics `setUserId` method has it's `identifier` parameter set with an `@NonNull` 
See source:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java#L157

**Proposed fix**
Simply update the annotation to `@Nullable` instead of `@NonNull`.

**Comment by ditn** [comment]
The docs do say that to clear an ID, [just pass an empty String](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#set-user-ids).

**Comment by ashwinraghav** [comment]
The recommended approach like @ditn mentioned is to pass an empty string.
