### ISSUE TITLE
Fetch document on Firestore return sometimes client.user must not be null

### ISSUE THREAD

**Issue by arseneHuot** [firebase/firebase-android-sdk#1522]
### Environment

  * Android Studio version: 4.0 canary 9
  * Firebase Component: firebase-firestore-ktx, firebase-auth
  * Component version Firestore: 21.4.3
  * Component version Auth: 19.3.1

### My problem

I'm using Auth Firebase sdk to signin/singup a user (email/password or gmail) and Firestore to retrieve user data.
Everything is working fine except for 5% of users which have sometimes problems to retrieve Firestore data after a successful login. 
The error is : **client.user must not be null**

I can't reproduce, i've tried a lot...

#### Sign in function with email/passwprd:

```
fun signin(
    email: String,
    password: String,
    callback: ((user: User?) -> Unit)
  ) {
    FirebaseAuth.getInstance().signInWithEmailAndPassword(email, password)
      .addOnCompleteListener { task ->
        if (task.isSuccessful) {
          val user = auth.currentUser
          user?.let {
            fetchUser(it.uid, callback)
         }
      }
  ...
  }
```

#### And firestore function to retrieve user data:

```
fun fetchUser(authId: String, callback: ((user: User?) -> Unit)?) {
    val db = Firebase.firestore
    db.collection("users")
      .document(authId)
      .get()
      .addOnSuccessListener { document ->
        try {
          if (document != null) {
            val user = document.toObject(User::class.java)
            user?.id = document.id
            callback?.let { it(user) }
          } else {
            callback?.let { it(null) }
          }
        } catch (ex: Exception) {
          manageError(ex)
          callback?.let { it(null) }
        }
      }.addOnFailureListener { e ->
        manageError(e)
        callback?.let { it(null) }
      }
  }
```

Regards

**Comment by var-const** [comment]
Sorry to hear about your issue. Do you have any additional details about the error? Do you happen to have a stack trace? Can you post a screenshot of the error?

**Comment by Bild78** [comment]
No hes just seen all y'alls info kope he gets out of my phone I'm done
changing phones email and carriers soon thanks

**Comment by arseneHuot** [comment]
> Sorry to hear about your issue. Do you have any additional details about the error? Do you happen to have a stack trace? Can you post a screenshot of the error?

I really have no more information, i know only that the error is happening in the second function, the fetch in Firestore (in the onfailure or catch part)

**Comment by var-const** [comment]
Thanks for providing the additional details. I cannot see the error message (`client.user must not be null`) being issued anywhere by Firestore or Auth. Could it be that the error is produced by some other dependency of your app? In either case, we would need more information to get traction on this issue:
* can you please provide a stack trace? It should be possible to log the stack trace of the exception in `manageError`.
* can you [enable Firestore logging](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/firestore/FirebaseFirestore#setLoggingEnabled(kotlin.Boolean)) and provide a log (please make sure to omit any sensitive information)?

**Comment by arseneHuot** [comment]
> Thanks for providing the additional details. I cannot see the error message (`client.user must not be null`) being issued anywhere by Firestore or Auth. Could it be that the error is produced by some other dependency of your app? In either case, we would need more information to get traction on this issue:
> 
> * can you please provide a stack trace? It should be possible to log the stack trace of the exception in `manageError`.
> * can you [enable Firestore logging](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/firestore/FirebaseFirestore#setLoggingEnabled(kotlin.Boolean)) and provide a log (please make sure to omit any sensitive information)?

I'm sure the error and the message is in the catch or onfailure of this fetch. I've added a log some weeks ago to log **e.localizedMessage**

```fun fetchUser(authId: String, callback: ((user: User?) -> Unit)?) {
    val db = Firebase.firestore
    db.collection("users")
      .document(authId)
      .get()
      .addOnSuccessListener { document ->
        try {
          if (document != null) {
            val user = document.toObject(User::class.java)
            user?.id = document.id
            callback?.let { it(user) }
          } else {
            callback?.let { it(null) }
          }
        } catch (ex: Exception) {
          manageError(ex)
          callback?.let { it(null) }
        }
      }.addOnFailureListener { e ->
        manageError(e)
        callback?.let { it(null) }
      }
  }
```

In firestore i see the line `Preconditions.checkNotNull(collectionPath, "Provided collection path must not be null.");`

But like you i don't see a "client.user must not be null"...

I will add more logs to retrieve stack trace and i'll keep you inform.

**Comment by arseneHuot** [comment]
I have removed some useless index of the database (on array field) and it seems to fix the problem. 2 hours without any errors...
Let's see

**Comment by arseneHuot** [comment]
Okkkkkk
I close the issue, my bad, the error is happening in the callback => catch part is fired... So it wasn't Firestore, sorry

Thanks for the help

**Comment by var-const** [comment]
No worries, glad to hear the error got resolved!
