### ISSUE TITLE
Firebase Crashlytics 2.0.0 plugin doesn't support incremental builds

### ISSUE THREAD

**Issue by clhols** [firebase/firebase-android-sdk#1523]
### [REQUIRED] Step 2: Describe your environment

====Platform information:====
AI-193.6911.18.40.6401094, JRE 1.8.0_242-release-1644-b3-6222593x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.4, screens 3440x1440

AS: 4.0 Beta 5; Kotlin plugin: 1.3.72-release-Studio4.0-1; Android Gradle Plugin: 4.0.0-beta05; Gradle: 6.3; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: 3.14.5

### [REQUIRED] Step 3: Describe the problem

I updated to:
'com.google.firebase:firebase-crashlytics-gradle:2.0.0'

Now Android Studio 4.0.0-beta05 complains about the plugin not being incremental:

At 12:55, May 04, 2020, Android Studio detected an issue with Gradle plugin com.google.firebase.crashlytics

Always-run Tasks
Task runs on every build because it declares no outputs.

```
Plugin: com.google.firebase.crashlytics
Task: injectCrashlyticsMappingFileIdPersonalDkDebug
Task type: com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask
Issue detected in 1 module(s), total execution time was 0.018 s (0.2%), by module:
  Execution mode: FULL, time: 0.018 s (0.2%), determines build duration: true, on critical path: false

====Build information:====
Execution date: 04/05/2020, 12.55
Total build duration: 15.795 s
Configuration time: 4.201 s (26.6%)
Critical path tasks time: 9.765 s (61.8%)
Critical path tasks size: 88
AGP versions: 4.0.0-beta05
```

Also I tried make the debug builds not call "injectCrashlyticsMappingFileIdPersonalDkDebug" by setting the following, but it doesn't work:
        <meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="false" />

I also have:
    debug {
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
    }

So how do you turn off the plugin for debug builds?

**Comment by ashwinraghav** [comment]
Thanks for the report.
Does your debug build proguard the app. I would imagine not?
Are you able to simply avoid applying the plugin in your debug builds?
```
if (!project.hasProperty("disable-crash-plugin"))  {
    apply plugin: 'com.google.firebase.firebase-perf' 
}
```
You would have to pass the param in while building your app. Say:
```
./gradlew <:app:assembleDebug>  -Pdisable-crash-plugin
```
@mrwillis21 @mrichards May be worth considering having options to disable uploads for debug builds even if they do proguard. We do this with [firebase performance](https://firebase.google.com/docs/perf-mon/disable-sdk?platform=android#disable-gradle-plugin) already.

**Comment by ramanpreetSinghKhinda** [comment]
I remember Crashlytics use to support [ext.enableCrashlytics](https://developer.android.com/studio/build/optimize-your-build#disable_crashlytics) flag. Is that not supported any more @mrwillis21 ?

Some Crahslytics References I encountered:
 - [CrashlyticsPlugin](https://github.com/crashlytics/android/blob/6ccaecd6b3732bfb55b980bec1f65372862ee832/gradlePlugins/crashlytics/src/main/groovy/com/crashlytics/tools/gradle/CrashlyticsPlugin.groovy#L666-L680)

 - b/112462278

## Firebase Performance References

### Regarding Incremental Build / Parallel Processing
We have internal tickets (b/120027470 and b/120494931) to track that implementation in Firebase Performance but we have not yet implemented it, so don't have much details there. However, the bug descriptions provides clear AI on how to achieve that.

### Regarding debug build disable option
Although Firebase Performance registers [Transform](https://google.github.io/android-gradle-dsl/javadoc/2.1/com/android/build/api/transform/Transform.html) but here's the cl/257028327 that provides support for that option in Firebase Performance. Specifically refer `registerExtension()` in `FirebasePerfPlugin.java`.

Let me know if you need any additional help or references from Firebase Performance side.

**Comment by wbervoets** [comment]
Also received this message when building a debug build with Android Studio 4.0 RC1 (no proguard)

**Comment by doniwinata0309** [comment]
> Thanks for the report.
> Does your debug build proguard the app. I would imagine not?
> Are you able to simply avoid applying the plugin in your debug builds?
> 
> ```
> if (!project.hasProperty("disable-crash-plugin"))  {
>     apply plugin: 'com.google.firebase.firebase-perf' 
> }
> ```
> 
> You would have to pass the param in while building your app. Say:
> 
> ```
> ./gradlew <:app:assembleDebug>  -Pdisable-crash-plugin
> ```
> 
> @mrwillis21 @mrichards May be worth considering having options to disable uploads for debug builds even if they do proguard. We do this with [firebase performance](https://firebase.google.com/docs/perf-mon/disable-sdk?platform=android#disable-gradle-plugin) already.
Hi @ashwinraghav , i tried to disable crashlytics plugin like perf monitor
if (!project.hasProperty("disable-crash-plugin"))  {
    apply plugin: 'com.google.firebase.firebase-perf' 
}
Eventhough i only add dependencies on the build.gradle (no other code reference craslhytics) `implementation 'com.google.firebase:firebase-crashlytics:17.0.1'`
However it return runtime error
```
Process: com.test.myapplication.crashlytics.test, PID: 11711
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.```

How to completely disable and reenable it based on build variant ?

**Comment by maxcruz** [comment]
Still having the same issue with the plugin 2.2.0. Any update on this?

**Comment by mrwillis21** [comment]
Hi folks, thanks for the conversation!

First of all, some context:

For obfuscated builds, the Crashlytics Gradle plugin injects a mapping file ID (as you might have guessed!) into your app which associates the particular mapping file uploaded for that build with that particular build's crashes.

If you are not obfuscating your app build, then this task should be always `UP-TO-DATE` (except on a clean build, of course).

If you *are* obfuscating your build, but don't need to upload a mapping file for a given build type or flavor, you can set `mappingFileUploadEnabled` to `false` in order to disable mapping file upload (and mapping file ID injection). More information on that can be found [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=android#keep_obfuscated_build_variants).

**Comment by mrwillis21** [comment]
Folks that are still confused, can I ask for more information?

I did see the original report suggested the `mappingFileUploadEnabled` setting wasn't working, can you give me a better idea of your full configuration, and what failure you're seeing?

**Comment by volodymyr-gz** [comment]
> In my own testing, the Build Analyzer only shows the "always-run" warning on a clean build. On subsequent builds, the task is UP-TO-DATE.

I was confused whether we always have to add `mappingFileUploadEnabled = false`, since AS 4.0 Build Analyzer was complaining about the task: 
```
At 18:57, Jul 21, 2020, Android Studio detected an issue with Gradle plugin com.google.firebase.crashlytics

Always-run Tasks
This task might be setting its up-to-date check to always return false.

Plugin: com.google.firebase.crashlytics
Task: injectCrashlyticsMappingFileIdQaDebug
Task type: com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask
Issue detected in 1 module(s), total execution time was 0.020 s (0.1%), by module:
  Execution mode: FULL, time: 0.020 s (0.1%), determines build duration: false, on critical path: false

====Build information:====
Execution date: 21.07.20, 18:57
Total build duration: 33.122 s
Configuration time: 1.572 s (4.7%)
Critical path tasks time: 26.619 s (80.4%)
Critical path tasks size: 101
AGP versions: 4.0.1
====Platform information:====
AI-193.6911.18.40.6626763, JRE 1.8.0_242-release-1644-b3-6222593x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.15.3, screens 1440x900; Retina

AS: 4.0.1; Kotlin plugin: 1.3.72-release-Studio4.0-5; Android Gradle Plugin: 4.0.1; Gradle: 6.4.1; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: 3.15.5
```

However, it only happens on a clean build (regardless of `mappingFileUploadEnabled` setting) and the warning is gone on subsequent builds (the task is `UP-TO-DATE`). So, I think it's a false-positive from the Build Analyzer side.

**Comment by clhols** [comment]
I can't reproduce the issue anymore.

We are now building with:
```
classpath "com.android.tools.build:gradle:4.0.0"
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
implementation 'com.google.firebase:firebase-crashlytics:17.1.1'
and
mappingFileUploadEnabled false for buildType debug
```

**Comment by mrwillis21** [comment]
Sounds like this is all set. Going to close this iss, but @volodymyr-gz @clhols if you have any other feedback, please feel free to post it here.
