### ISSUE TITLE
 FirebaseRemoteConfig.getInstance() causes IllegalStateException latest SDK

### ISSUE THREAD

**Issue by THEAccess** [firebase/firebase-android-sdk#1524]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.3
  * Firebase Component: RemoteConfig / Firebase Core
  * Component version: 19.1.4

### [REQUIRED] Step 3: Describe the problem

I'm using the latest Firebase and Play Services in my app. I have used Firebase for over a year in my app now without any problems. Recently I have decided to add Remote Config to my app. Unfortunately calling `FirebaseRemoteConfig.getInstance()` causes the following exception:
` java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process [redacted]. Make sure to call FirebaseApp.initializeApp(Context) first.`  Whereas `FirebaseAnalytics.getInstance(this).` works just fine, so I'm assuming my app is correctly initialized and this is SDK bug.

The problem appears whether or not `FirebaseApp.initialize(this)` is called in `Application#onCreate`

My dependencies: 
build.gradle:
` classpath "com.google.gms:google-services:${versions.playServices}"`
cloud/build.gradle (it's an multi module app):
```
 api(
            libraries.firebaseAnalytics,
            libraries.firebaseAds,
            libraries.crashlytics,
            libraries.firebaseConfig,

    )`
```
dependencies.gradle:
``` 
`ext {
versions = [
            playServices     : "4.3.3",
            firebaseAnalytics: "17.4.0",
            crashlytics      : "2.10.1",
            firebaseAds      : "19.1.0",
            firebaseConfig   : "19.1.4",
]
libraries = [
            crashlytics       : "com.crashlytics.sdk.android:crashlytics:${versions.crashlytics}",
            firebaseAds       : "com.google.firebase:firebase-ads:${versions.firebaseAds}",
            firebaseAnalytics : "com.google.firebase:firebase-analytics:${versions.firebaseAnalytics}",
            firebaseConfig    : "com.google.firebase:firebase-config:${versions.firebaseConfig}",
]
}
}
```

**Comment by andirayo** [comment]
Fly-by comment: `FirebaseRemoteConfig` `v19.1.4` introduced a new dependency on the Firebase infrastructure `FirebaseInstallations`.
I don't think this change should have any impact on the described issue, since both `FirebaseRemoteConfig` and `FirebaseInstallations` require a valid `Default FirebaseApp` to be initialized to function properly, but I wanted to mention it.

@THEAccess : Do you see the same issue with `FirebaseRemoteConfig` `v19.1.3`?

**Comment by THEAccess** [comment]
After downgrading to `v19.1.3` calling `FirebaseRemoteConfig.getInstance()` raises another exception: `java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault()' on a null object reference`.

I also noticed `W/ComponentDiscovery: Application info not found.; W/ComponentDiscovery: Application info not found.
Could not retrieve metadata, returning empty list of registrars.`  started to appear in my logs.
But adding the following service to my AndroidManifest.xml as suggested in [this issue](https://github.com/firebase/firebase-android-sdk/issues/685) doesn't resolve this problem.
```
      <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>
```

**Comment by Bild78** [comment]
What are you trying to tell me I'm not tech savvy help me understand

**Comment by danasilver** [comment]
Hi @THEAccess. You mentioned `app\build\generated\res\google-services\debug\values\values.xml` wasn't generated in the original issue. That's a hint there may be an issue with how Firebase is configured for your app. Can you check to see if you have the `google-services.json` file from Firebase and the line `apply plugin: 'com.google.gms.google-services'` in your app-level `build.gradle` as specified in https://firebase.google.com/docs/android/setup#add-config-file? You'll need those to initialize Firebase automatically.

I was able to reproduce your error removing the `apply plugin: 'com.google.gms.google-services'` and running a test app.

**Comment by THEAccess** [comment]
Thank you for your suggestions. Before I opened the issue I triple checked that `google-services.json` is present & up to date and `apply plugin: 'com.google.gms.google-services'` is present.
`app\build\generated\res\google-services\debug\values`
 is now being generated again. Apologies for any confusion I might have caused. 
For clarification: This is my app/build.gradle:
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'io.fabric'

apply plugin: 'com.google.gms.google-services'


android {
    compileSdkVersion versions.compileSdk
    buildToolsVersion versions.buildTools
    signingConfigs {
        config {
           [...]
        }
    }
    defaultConfig {
        applicationId "com.ignates.allFonts"
        minSdkVersion versions.minSdk
        targetSdkVersion versions.targetSdk
        versionCode config.versionCode
        versionName config.versionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
            [...]
        }
        debug {
            [...]
        }
    }




    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

  
}

dependencies {

    implementation(
            libraries.kotlinStdlb,
            libraries.firebaseConfig,
            project(':core'),
            project(':data'),
            project(':cloud'),
            project(':ui')

    )

    testImplementation (
            testLibraries.junit
    )

}
```
Unfortunately, despite all efforts, the issue still persists.

**Comment by THEAccess** [comment]
Thank you for your suggestions. Before I opened the issue I triple checked that `google-services.json` is present & up to date and `apply plugin: 'com.google.gms.google-services'` is present.
`app\build\generated\res\google-services\debug\values`
 is now being generated again. Apologies for any confusion I might have caused. 
For clarification: This is my app/build.gradle:
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'io.fabric'

apply plugin: 'com.google.gms.google-services'


android {
    compileSdkVersion versions.compileSdk
    buildToolsVersion versions.buildTools
    signingConfigs {
        config {
           [...]
        }
    }
    defaultConfig {
       [...]
        minSdkVersion versions.minSdk
        targetSdkVersion versions.targetSdk
        versionCode config.versionCode
        versionName config.versionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
            [...]
        }
        debug {
            [...]
        }
    }




    android {
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

  
}

dependencies {

    implementation(
            libraries.kotlinStdlb,
            libraries.firebaseConfig,
            project(':core'),
            project(':data'),
            project(':cloud'),
            project(':ui')

    )

    testImplementation (
            testLibraries.junit
    )

}
```
Unfortunately, despite all efforts, the issue still persists.

**Comment by danasilver** [comment]
Can you post the full stack trace from the exception? I see a few other issues open right now with an IllegalStateException (#1454 and #1528) and I wonder if they're related. You can also check on the values generated in `build/generated/res/google-services/(debug or release)/values/values.xml` to make sure the values for `google_api_key`, `google_app_id`, and `project_id` are set from your google-services.json. Those are the necessary keys to initialize `FirebaseApp`.

**Comment by THEAccess** [comment]
Sure, here you go:
_RemoteConfig 19.1.4_
```
Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault()' on a null object reference
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(com.google.firebase:firebase-config@@19.1.3:85)
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(com.google.firebase:firebase-config@@19.1.3:79)
        at com.luminarlab.cloud.RemoteConfigImpl.<init>(RemoteConfigImpl.kt:16)
        at com.luminarlab.font2.FontApp$kodein$1$7.invoke(FontApp.kt:52)
        at com.luminarlab.font2.FontApp$kodein$1$7.invoke(FontApp.kt:40)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(KodeinAware.kt:176)
        at org.kodein.di.KodeinAwareKt$Instance$1.invoke(Unknown Source:8)
        at org.kodein.di.KodeinProperty$provideDelegate$1.invoke(properties.kt:42)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.luminarlab.core.feature.BillingFeature$BillingActor.getConfig(Unknown Source:7)
        at com.luminarlab.core.feature.BillingFeature$BillingActor.access$getConfig$p(BillingFeature.kt:57)
        at com.luminarlab.core.feature.BillingFeature$BillingActor$invoke$3.invokeSuspend(BillingFeature.kt:71)
        at com.luminarlab.core.feature.BillingFeature$BillingActor$invoke$3.invoke(Unknown Source:10)
        at com.ignates.core2.bridge.BridgeKt$observableBuilder$1$1.invokeSuspend(Bridge.kt:30)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

The generated values match those in `google-services.json`

**Comment by danasilver** [comment]
Ah sorry, I meant the original stack trace for the `IllegalStateException` you saw in RemoteConfig 19.1.4. Since you're seeing a NullPointerException initializing in version 19.1.3 as well, the issue could be where in the app lifecycle you're calling `FirebaseRemoteConfig.getInstance()`.

**Comment by THEAccess** [comment]
The exception I posted occurs both in RemoteConfig 19.1.3 & 19.1.4. Initially, I encountered a `IlegalStateException` but it changed after I cleared caches.

**Comment by ashwinraghav** [comment]
> The exception I posted occurs both in RemoteConfig 19.1.3 & 19.1.4. Initially, I encountered a `IlegalStateException` but it changed after I cleared caches.

Can you share what it changed to?
