### ISSUE TITLE
FirebaseMessagingService keeps receiving messages after deleteInstanceId() was called

### ISSUE THREAD

**Issue by BulatMukhutdinov** [firebase/firebase-android-sdk#153]
* Android Studio version:  3.4 Canary 4
  * Firebase Component: Cloud Messaging
  * Component version: 17.3.0

1) Receive new token in onNewToken() and register it on backend
2) Turn off the Internet and call FirebaseInstanceId.getInstance().deleteInstanceId()
3) Send a few messages from your backend using token from step 1
4) Turn on the Internet
Actual result: a few messages are received in onMessageReceived(), after that onNewToken() is called
Expected result: onNewToken() is called, no new messages received

**Comment by faithfracture** [comment]
> This is a blocking function so do not call it on the main thread.
[Firebase Docs](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#deleteInstanceId())

If you aren't calling `deleteInstanceId()` from a background thread, you will see exactly the behavior you are describing.

**Comment by BulatMukhutdinov** [comment]
Executing thread is Schedulers.io()

**Comment by aguatno** [comment]
@BulatMukhutdinov are you still having this issue? If so, would you mind sharing updated steps you’ve taken that led to the error encountered (with a sample reproducible code would be great).

You may also consider upgrading your Cloud Messaging SDK to the latest version (20.0.0).

Thanks!

**Comment by BulatMukhutdinov** [comment]
It  was almost 2 years ago :) Let me close this issue
