### ISSUE TITLE
Crashlytics fatal crash storage limit

### ISSUE THREAD

**Issue by vinitamurthi** [firebase/firebase-android-sdk#1541]
Hi firebase team, 

We are working on integrating crashlytics into our [Android application](https://github.com/oppia/oppia-android)
Our application needs support for long-term offline storage since our users may not be connected to the internet for weeks or months together.
We noticed that while crashlytics stores 8 custom events, fatal crashes in crashlytics do not have any storage limits (none that we could find in the documentation or in the [persistEvent function](https://github.com/firebase/firebase-android-sdk/blob/b878917aba9b656fa61d7fe1207b9c538622e30f/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java#L142)
However we wanted to check with the team if that really is the case. Can we assume that crashlytics will store all of our crashes until the device is connected to the network once again (Given that the device may not be connected to the internet for a long period of time - like say few months)?

**Comment by ashwinraghav** [comment]
Thank you for the question. While we don't have a publicly documented limit, there are some limits we do enforce. Currently, that's at 10MB. Beyond this limit, incoming crashes get dropped. So it's sort of a [FIFO](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics)) mechanism

Note that most other Firebase products gracefully degrade offline as well.
 
https://github.com/firebase/firebase-android-sdk/blob/4498fccb497a897f2832599c8db42cb34abc5ce9/transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/TestEventStoreModule.java#L25

https://github.com/firebase/firebase-android-sdk/blob/4498fccb497a897f2832599c8db42cb34abc5ce9/transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java#L582-L586
