### ISSUE TITLE
Crashlytics with service on a different process

### ISSUE THREAD

**Issue by AndrewBloom** [firebase/firebase-android-sdk#1545]
## What feature would you like to see?
I'd like to be able to use crashlytics on a service run on a different process than the app. 
I'd like to compile the service as aar library and add that on my app project. 

Describe the feature you would like to add, ideally proposing a specific API.

## How would you use it?
I would compile my service run on a different process and build an aar file. This will contain ndk code, which is an audio player. Then I would add the aar file to my app project. My app project contains the UI for the player.

Tell us how you'd use this feature in your app.
I'd use it to log the crashes on the ndk side of the library, that happen cause I'm a very bad developer

**Comment by Duna** [comment]
Same issue here, no crashes were logged if my app has a different processes

**Comment by kennyli92** [comment]
I also have an app that creates foreground services on another process. I've been using Google Console to keep track of failures on these other process, but I'd like to able to track these failures on Crashlytics too! Thanks :)

**Comment by JessHolle** [comment]
Shouldn't there be documentation about the need to call `FirebaseApp.initializeApp(context.getApplicationContext());` for non-main processes?  I didn't see such -- and only bumped into this by eventually finding this issue.

**Comment by thismj** [comment]
> I think it's working. You have to initialize Firebase on your non-main process
> `FirebaseApp.initializeApp(context.getApplicationContext());`

This only works for Java crashes, but native crashes are unreported in all processes when you do that. That means If not initialize Firebase on your non-main process, The native crash will be successfully reported in your main process.

I am confused and don't know how to do  (T＿T) .

**Comment by JessHolle** [comment]
Ouch!  So we're currently forced to choose between Java-level crash reporting for all processes and native crash reporting in the main process.  That's clearly not an acceptable state of affairs!

**Comment by gargas** [comment]
Is there any update for this? I am also facing the same issue.

**Comment by mrichards** [comment]
Hi folks, Crashlytics 18.2.11 is now live and fixes this issue. Please reopen if you continue to experience unexpected behavior after updating!

**Comment by doubleo2** [comment]
@mrichards What does 18.2.11 fix exactly? Will Crashlytics initialize itself in non-main processes now? or do you still need to  initialize Crashlytics in non-main processes but now both JVM and native crashes be reported? Or is it both?

Are these the only [release notes](https://firebase.google.com/support/release-notes/android#crashlytics_v18-2-11) or is there a more detailed version somewhere?
