### ISSUE TITLE
Android forced to listen to all events in ChildEventListener

### ISSUE THREAD

**Issue by coolcool1994** [firebase/firebase-android-sdk#1551]
In iOS Firebase, you can listen to onChildAdded, onChildChanged, onChildRemoved, and onChildMoved separately in order to minimize the cost of data download ($1 per 1GB). For example, I can only listen to onChildAdded and onChildDeleted  for a parent node and listen to onChildChanged for one of the subnodes - and this is working very efficiently to reduce the data downloaded from Firebase.

However, in Android, you are forced to listen to all onChildAdded, onChildChanged, onChildRemoved, and onChildMoved for a specific node, which gives you no flexibility to save data downloaded from your bill. Just like in iOS, Android Firebase SDK must allow developers to subscribe to specific events and not forced to listen to all. For example, I would like to only observe onChildAdded and onChildRemoved for a specific node, and not onChildChanged, onChildMoved. I would say this is a bug in Android and should be addressed.

Could you guys fix this by when you do not override the function onChildChanged in ChildEventListener block, you do not get charged for data downloaded from onChildChanged? I only want to observer onChildAdded and onChildRemoved, and in scale, this is going to save a lot of money for us with data download ($1 per 1GB). iOS has already done that.

Official Firebase documents back my claim:
iOS: https://firebase.google.com/docs/database/ios/lists-of-data
Android: https://firebase.google.com/docs/database/android/lists-of-data#kotlin+ktx_1

Edit: even on the Web, you can individually subscribe to child_added, child_changed, child_removed, child_moved: https://firebase.google.com/docs/database/web/lists-of-data

**Comment by coolcool1994** [comment]
Could someone just verify this limitation in Android? Maybe there is a way to bypass this problem in Android. I just want someone to verify that this limitation exists in Android. Thanks in advance.

**Comment by schmidt-sebastian** [comment]
@coolcool1994 You are correct in that our API differs between iOS and Android. 

While this won't necessarily be good news to you, the implementation is similar though: The iOS client registers a listener for all events and post-filters in the SDK to only raise relevant events. Our network protocol is a synchronization protocol and the backend sends us snapshots of the subsections of your database that has changed. We require full snapshots to keep our cache consistent. If we filtered events at the protocol layer, the values in SQLite (or even in memory) would essentially represent a corrupt state that never existed.

While this is an interesting feature request, I don't think it is something that we can do in the SDK. For that reason, I am closing this. Thank you for filing!

**Comment by coolcool1994** [comment]
Is it true when you subscribe to childListener both in iOS and Android, you are getting charged for data downloaded for all onChildAdded, onChildChanged, onChildRemoved, and onChildMoved together, even if you only use one of them?

I don't see why you would get a corrupt state by only listening for onChildAdded, onChildChanged, onChildRemoved, or onChildMoved. When you get a snapshot, you can just update whatever snapshot is updated. When I child is added, just add that one child. Why would the data be corrupt?

I submitted a feature/support request to the support channel. I believe based on what you said this is something that is possible and should be done to be more efficient both for Firebase servers and reduce costs for developers in terms of data downloaded.

**Comment by schmidt-sebastian** [comment]
The synchronization protocol between the SDK and the backend does not support sending only a subset of changes.  To support your request without corrupting local state, we would need to evolve the protocol. We will take your input into account if we decide to do so, but please bear in mind that this is very unlikely.

Thank you for understanding.
