### ISSUE TITLE
Firebase Crashlytics plugin 2.1.0 -  gradle configuration issue

### ISSUE THREAD

**Issue by originx** [firebase/firebase-android-sdk#1560]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.3
  * Firebase Component: Crashlytics
  * Component version: 
firebaseCrashlyticsPlugin : '2.1.0'
firebaseCrashlytics       : '17.0.0'

### [REQUIRED] Step 3: Describe the problem

How our project looks like:
Our project does not use google-services.json due to various reasons (legacy and functional).
We have multiple apps (DE, IT, MX, PL, AT, etc.) and each one of them is an Android flavor, with **build flags** to upload and prepare the app for either: Prod, QA, Partners, etc.
Due to legacy reasons those apps have **separate projects** in Firebase, separate project IDs and also different way of distributions.

Sofar with all Firebase libraries we did the following:
We configure the Firebase when the app starts manually via https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseOptions

For gradle plugins from firebase we set the google-app id and/or other necessary properties via gradle groovy configurations as explained here: https://firebase.google.com/docs/app-distribution/android/distribute-gradle#step_3_configure_your_distribution_properties
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.google.firebase.appdistribution'
 
**The issue:**
We wanted to migrate to latest official supported crashlytics plugin called Firebase Crashlytics, so we followed the following guide:
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android
Sadly everything breaks for us and Firebase crashlytics is unusable after following all the instructions. 
It breaks due to the following plugin: 
apply plugin: 'com.google.firebase.crashlytics' 

With the issue:
Task :apps:dsa:uploadCrashlyticsMappingFileGermanyRelease FAILED
“Could not find the file generated by Google Services. Please check your Firebase project configuration ( https://firebase.google.com/docs/android/setup )“
 
We noticed that issue stems from the following class: com.google.firebase.crashlytics.buildtools.gradle.ProjectVariantState from firebase-crashlytics-gradle-2.0.0.jar

Our conclusion is that Firebase looks for google-app-id where to upload the mappings file for current release build (which app, project etc) via the pre-generated res values file that is generated from google-services.json files by Firebase plugins. As I mentioned above this cannot work for us since we have different Firebase projects for same app package between QA; partners, Production. 

 
**Expected/proposed behavior**:
Firebase crashlytics already provides 2-3 parameters that are configurable via groovy/gradle, for example:
firebaseCrashlytics {
                    nativeSymbolUploadEnabled true
                    mappingFileUploadEnabled true
                }
Can you please enable us to add all the required settings via this method, and this includes the googleAppId, so if its set via gradle/groovy configuration the above mentioned issue would not occur.
Firebase performance and distribution plugins already use this method and it works perfectly for us.

**Comment by Onlinedispatcher** [comment]
+1
Thanks @originx  for this detailed description. We have the same issue and this issue is really a need for us to continue with the new Firebase Crashlytics plugin (y) (y)

**Comment by ashwinraghav** [comment]
Thank you for the detailed explanation and the suggested workarounds. Firebase plugins in general are susceptible to the scenario you describe of having a mix and match of package names and (Firebase Projects/Apps). Note that Firebase APIs *do* support this situation a lot better.

## Temporary workaround
We're happy to consider the work around you are suggesting. In the mean time, here's a way for you to work around
The crashlytics gradle plugin looks for these files in this path
```groovy
project.file(project.buildDir.getAbsolutePath() + "/generated/res/google-services/"
                + variant.dirName + "/values/values.xml")
```

If you have (say) 4 different google-services.json files for your projects, one option is to copy the right one into the path above. You could do this inside your gradle builds and base it on the build flags you pass in or as a preprocessing step (like a shell script) before generating your app build.

**Comment by originx** [comment]
@ashwinraghav thank you for the detail how it works, I think the workaround would work if only 1 flavor/build type is being built
Sadly our CI runs the builds in parallel (e.g. assemble/bundleRelease) and I think this would cause conflicting issues which file is used (maybe there is a way to do it with gradle-fu by hooking up just before the required task but I do not have enough info on the inner workings of firebase plugins to try to attack it from this side).

hopefully you guys will find time to implement the suggested solution.

thanks

**Comment by mrwillis21** [comment]
Hi folks - thanks for the report! Wanted to let you all know that this is on our radar for a fix. Not sure yet what the timeline is, but I'll let you know once we have a better idea. :)

**Comment by originx** [comment]
any update on this issue?

**Comment by mrichards** [comment]
Short update on this: The [workaround](https://github.com/firebase/firebase-android-sdk/issues/1560#issuecomment-630350787) above should work for most use cases. We will be supporting this more naturally in our Gradle plugin in a future release, as we've been refactoring how all Crashlytics task inputs/outputs work to support of the Gradle configuration cache. But it still may be a few releases away.

**Comment by mrichards** [comment]
Starting with Crashlytics Gradle plugin 2.7.0, we have improved support for customers not using the GMS plugin.

You will need to create an XML resource file for each flavor. The resource file should matches the content of the Google services plugin that in a typical build would end up here: `"buid/generated/res/google-services/${variant.dirName}/values/values.xml"`

Then in your app's build.gradle, override the flavor-specific inputs for the `uploadCrashlyticsSymbolFile<VARIANT>` and uploadCrashlyticsMappingFile<VARIANT> tasks to point to the parent of the `values/values.xml` directory:

```
project.afterEvaluate {
    tasks.named("uploadCrashlyticsSymbolFileRelease") {
        DirectoryProperty myDirProp = 
            project.objects.directoryProperty().fileValue(file("${fakeGmsOutput}/release"))
        googleServicesResourceRoot.value(myDirProp)
    }
 ```

The "release" directory specified in the above example should include a "values" directory that contains a "values.xml" file. That may seem a little unwieldy but it matches the way that the Google Services plugin works, so it was the most straightforward implementation.
