### ISSUE TITLE
Crashlytics plugin selects wrong applicationId - doesn't honour changes by setApplicationId()

### ISSUE THREAD

**Issue by darrentaft** [firebase/firebase-android-sdk#1564]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0 RC1
  * Firebase Component: Crashlytics Gradle Plugin
  * Component version: 2.1.0

### [REQUIRED] Step 3: Describe the problem

My project uses a combination of flavorDimensions and buildTypes to generate 4 different apps with different app IDs.  To do this, I use an "applicationVariants.all" loop to process the combination of flavors and types to decide on the applicationId to use.

The problem is that the Crashlytics plugin doesn't appear to honour the result - it's extracting config from google-services.json based on the default applicationId specified within the flavorDimension, rather than the dynamically configured one.

If I don't specify an applicationId in the flavors, it appears to read the package from the AndroidManifest.xml - which also isn't correct. 

I can't see any way to tell Crashlytics which applicationId to use.

#### Steps to reproduce:

See test gradle config extract below.
Building "productaProdRelease" will correctly use applicationId "com.producta.app".
Building "productaNightlyRelease" will also use that same applicationId when deciding which part of google-services.json to use, even thought application will be built with applicationId "com.development-producta.app.something" as set by setApplicationId().

This results in crash reports being sent (according to the logcat console) but never actually appearing on the web site (I assume because they're sent to one project, with the applicationId from a different one).

#### Relevant Code:

```
flavorDimensions "PRODUCT", "TARGET"

productFlavors {
    producta {
        dimension "PRODUCT"
        applicationId "com.producta.app"
    }
    productb {
        dimension "PRODUCT"
        applicationId "com.productb.app"
    }
    nightly {
        dimension "TARGET"
    }
    sprint {
        dimension "TARGET"
    }
    prod {
        dimension "TARGET"
    }
}

buildTypes {
    debug {
    }
    release {
    }
    penTest {
    }
    store {
    }
}
    
applicationVariants.all { variant ->
    def mergedFlavor = variant.mergedFlavor

    if (variant.flavorName.startsWith("producta")) {
        if (variant.flavorName.contains("Prod")) {
            mergedFlavor.setApplicationId("com.producta.app")
        } else {
            mergedFlavor.setApplicationId("com.development-producta.app.something")
        }
    } else {
        if (variant.flavorName.contains("Prod")) {
            mergedFlavor.setApplicationId("com.productb.app")
        } else {
            mergedFlavor.setApplicationId("com.unrelated.app.something")
        }
    }
}
```

**Comment by JonWatson** [comment]
Seeing the same problematic behavior, thanks in advance

**Comment by mrwillis21** [comment]
Hi there! Just wanted to let folks know we're aware of this issue and working on getting a fix in for it. :)

Thanks for the report!

**Comment by soenkegissel** [comment]
Seeing the same problematic behavior, thanks in advance

**Comment by karthikrpandian** [comment]
We are also struggling with same issue

**Comment by soenkegissel** [comment]
@mrwillis21 Could you please work in this issue next? Would be so happy.

**Comment by mrwillis21** [comment]
Hi @darrentaft (and others). I've been digging a bit more into this, and I'm not sure this is actually describing the issue I'd mentioned before that we knew about.  I could use a bit more information. You mentioned:

> The problem is that the Crashlytics plugin doesn't appear to honour the result - it's extracting config from google-services.json based on the default applicationId specified within the flavorDimension, rather than the dynamically configured one.
>
> If I don't specify an applicationId in the flavors, it appears to read the package from the AndroidManifest.xml - which also isn't correct.

Can you give me a sense of where you're seeing the incorrect application ID being used? I know you'd mentioned that you're not seeing your crash reports being sent up, but I'd like to understand better what you mean by "it's extracting config...". Can you give me an example of your build/run process where you're seeing the incorrect behavior?

**Comment by mrwillis21** [comment]
@soenkegissel or @karthikrpandian if you have examples of how this is affecting you, that would also help. :)

**Comment by JonWatson** [comment]
@mrwillis21 Do you have access to the support tickets from firebase-support@google.com?  I have a case open with a lot of info.  

Case 00061830

**Comment by soenkegissel** [comment]
@mrwillis21 I can describe my issues as the exact same as mentioned by @JonWatson.

The following will work with no problems. If I build for debug the google-services.json will search for com.company.coffeecup.debug. If this ID is not found build will fail. So everything as expected.
```
defaultConfig {
    applicationId "com.company.coffeecup"
}

buildTypes {
        debug {
            applicationIdSuffix = ".debug"
        }
}
```
This will work as well. If in firebase console no com.company.coffeecup.huawei.debug or com.company.coffeecup.samsung is found, build will fail. Expected.
```
defaultConfig {
    applicationId "com.company.coffeecup"
}

buildTypes {
        debug {
            applicationIdSuffix = ".debug"
        }
}

productFlavors {
HUAWEI {
    dimension "vendor"
        applicationIdSuffix = ".huawei"
}
SAMSUNG {
    dimension "vendor"
       applicationIdSuffix = ".samsung"
}
}
```
But here comes the problem. If I dynamically assign applicationIds with the following. Firebase (not only Crashyltics, but Analytics as well) will no honour this. It will look for e.g com.company.coffeecup.huawei.
```
applicationVariants.all { variant ->
        def mergedFlavor = variant.mergedFlavor
        if (variant.productFlavors[2].name == "HUAWEI") {
            mergedFlavor.setApplicationId("com.company.coffeecup.huawei.christmasedition")
        } else if (variant.productFlavors[2].name == "SAMSUNG") {
            mergedFlavor.setApplicationId("com.company.coffeecup.samsung.summeredition")
        }
    }
```
Gradle will honour the setApplicationId function and does correctly set ID. This screenshot is from Samsung Galaxy Store Dashboard

**Comment by soenkegissel** [comment]
Use this example to test:
```
defaultConfig {
    applicationId "com.company.coffeecup"
}

buildTypes {
    productFlavors {
        HUAWEI {
            dimension "vendor" 
        }
        SAMSUNG {
            dimension "vendor"
        }
}

applicationVariants.all { variant ->
        //println("Iterating variant: " + variant.getName())
        def mergedFlavor = variant.mergedFlavor
        if (variant.productFlavors[1].name == "HUAWEI") {
            mergedFlavor.setApplicationId("com.company.coffeecup.willnotworkfor.huawei")
        } else if (variant.productFlavors[1].name == "SAMSUNG") {
            mergedFlavor.setApplicationId("com.company.coffeecup.willnotworkfor.samsung")
        }
    }
```
This example will only look for com.company.coffeecup in google-services.json and does register both flavours as com.company.coffeecup.

**Comment by mrwillis21** [comment]
Thanks everyone for the examples!

>Firebase (not only Crashyltics, but Analytics as well)

This is why I was asking -- I believe the problem is broader than the Crashlytics plugin. Let me take all this info back to the team, and I'll let you know when I have more information to share. Thanks again!

**Comment by soenkegissel** [comment]
> This is why I was asking -- I believe the problem may be broader than the Crashlytics plugin. Let me take all this info back to the team, and I'll let you know when I have more information to share. Thanks again!

Yes please take it to the team. I think there is a huge dark figure on this issue.

**Comment by mrwillis21** [comment]
Hi folks,

For those of you experiencing this issue, do you have an app created in Firebase for each of your dynamic app IDs? For example, if you have `com.foo`, with two dynamic IDs: `com.foo.debug` and `com.foo.release` - do you have separate apps in the Firebase console for `com.foo`, `com.foo.debug`, and `com.foo.release`?

**Comment by soenkegissel** [comment]
do you have separate apps in the Firebase console for `com.foo`, `com.foo.debug`, and `com.foo.release`?

Yes

> Also, are your apps migrated from Fabric, or newly onboarded in Firebase?

Newly in firebase

**Comment by mrwillis21** [comment]
Hello again everyone!

We believe we've tracked down the issue. It's related to the dynamically-set application ID not being picked up by the *Google Services Plugin*. This does cause downstream effects in Crashlytics, but also in other Firebase products, as has been shown.

While we work to determine the best solution to this problem, we've found a simple workaround, which is to apply the Google Services Plugin _after_ setting the application IDs in your `applicationVariants` block. So given the previous example:

```
defaultConfig {
    applicationId "com.company.coffeecup"
}

buildTypes {
    productFlavors {
        HUAWEI {
            dimension "vendor" 
        }
        SAMSUNG {
            dimension "vendor"
        }
    }
}

applicationVariants.all { variant ->
      def mergedFlavor = variant.mergedFlavor
      if (variant.productFlavors[1].name == "HUAWEI") {
          mergedFlavor.setApplicationId("com.company.coffeecup.willnotworkfor.huawei")
      } else if (variant.productFlavors[1].name == "SAMSUNG") {
          mergedFlavor.setApplicationId("com.company.coffeecup.willnotworkfor.samsung")
      }
  }

apply plugin: 'com.google.gms.google-services' // <--- MOVE THIS HERE
```

Try this out and let us know how it goes, and I'll let you know when we have more details to share on this. :)

**Comment by vuhomobytelab** [comment]
> Hello again everyone!
> 
> We believe we've tracked down the issue. It's related to the dynamically-set application ID not being picked up by the **Google Services Plugin**. This does cause downstream effects in Crashlytics, but also in other Firebase products, as has been shown.
> 
> While we work to determine the best solution to this problem, we've found a simple workaround, which is to apply the Google Services Plugin _after_ setting the application IDs in your `applicationVariants` block. So given the previous example:
> 
> ```
> android {
>     ...
> 
>     defaultConfig {
>         applicationId "com.company.coffeecup"
>     }
> 
>     flavorDimensions "vendor"
>     productFlavors {
>         HUAWEI {
>             dimension "vendor" 
>         }
>         SAMSUNG {
>             dimension "vendor"
>         }
>     }
> 
>     applicationVariants.all { variant ->
>         def mergedFlavor = variant.mergedFlavor
>         if (variant.productFlavors[0].name == "HUAWEI") {
>             mergedFlavor.setApplicationId("com.company.coffeecup.willnotworkfor.huawei")
>         } else if (variant.productFlavors[0].name == "SAMSUNG") {
>             mergedFlavor.setApplicationId("com.company.coffeecup.willnotworkfor.samsung")
>         }
>     }
> 
>     ...
> }
> 
> apply plugin: 'com.google.gms.google-services' // <--- MOVE THIS HERE
> ```
> 
> Try this out and let us know how it goes, and I'll let you know when we have more details to share on this. :)

Hi,
I followed your solution but nothing happen.
Crashlytics still show default config application ID even though I did have many flavors application ID.

Thanks.

**Comment by mrwillis21** [comment]
Quick update to let you know that recent versions of the Google Services Plugin should no longer require this workaround. :)
