### ISSUE TITLE
Phone verification stopped working and keeps failing

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [firebase/firebase-android-sdk#1569]
* Android device: Samsung Galaxy S2 (SM-T815Y)
  * Android OS version: 7.0
  * Google Play Services version: 17.0.0
  * Firebase/Play Services SDK version: 21.4.3

I followed the documentation and successfully implemented phone verification (without AuthUI) and it worked great. However, I was playing around with the FirebaseAuth class, specifically the claims `getClaims().get("admin")` code and this is when the app's auth mechanism stopped working. I'm unsure if that it is the cause because it was almost an hour since I did my last logout-login but when I logged off and tried to login, the app completely failed to login. And then I saw these log message appear continuously:

```
I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
I/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@e414399
W/FirebaseAuth: [PhoneVerificationSession] PhoneVerificationSession constructor
W/FirebaseAuth: [PhoneNumberAuthPostProcessor] postProcess starts
W/FirebaseAuth: [PhoneVerificationSession] PhoneVerificationSession terminated
W/FirebaseAuth: [PhoneNumberAuthPostProcessor] postProcess ends
W/FirebaseAuth: [PhoneVerificationSession] onFailure
I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
D/FirebaseAuth: Notifying id token listeners about a sign-out event.
D/FirebaseAuth: Notifying auth state listeners about a sign-out event.
I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
```

I could no longer make phone auth logins. I tried rolling back commits too and then deploying the app but it didn't solve it and I feel that some kind of device-level block occurred... I tried auth using different phone number but that didn't work as well. In the end, I borrowed my friend's phone and tried login with the older APK and it worked fine. I'm not sure how to fix this and I'm totally locked out of running the app thro' my development device which is bad, nor can I borrow my friend's device. I think switching to emulator is gonna be my option until a solution comes out. Ideas on what may have happened would help. Thanks.

**Comment by samtstern** [comment]
@SaifurRahmanMohsin I have transferred this issue over to the Firebase Android SDK

**Comment by SaifurRahmanMohsin** [comment]
This issue was fixed for me after 24-hours i.e. my device seems to be working fine now. You may close the issue if you’d like. Although, it would also be better if the Firebase Android SDK team would check and take a look at it so that future users don’t have to deal with this.

**Comment by ashwinraghav** [comment]
Thanks for the report @SaifurRahmanMohsin . We'll take a quick peek and close it out if there;s nothing acitonable.

**Comment by yuchenshi** [comment]
Would you mind contacting Firebase Support? As you have mentioned, rolling back the build, etc. don't help, so I doubt there is anything on the SDK side. Instead, the Firebase Support is the best channel for these issues -- you can tell them the exact project IDs, device IPs, etc., and they have access to your project and can help to check if there were any known issues, outages or rate limits.

**Comment by yuchenshi** [comment]
@ashwinraghav Thanks for looping me in. If you don't mind, please add the `api: auth` tag next time for visibility.
