### ISSUE TITLE
Firebase using deprecated API

### ISSUE THREAD

**Issue by jayshildave1983** [firebase/firebase-android-sdk#1573]
There was a ticket created for the firebase using the install referrer which was recently deprecated by Google. 

Based on the ticket it was mentioned it was closed in version 17.2.0.
However, while using firebase analytics version 17.2.1 i still see that the install referrer broadcast is present in my merged manifest.

`        <receiver
            android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver"
            android:enabled="true"
            android:exported="true"
            android:permission="android.permission.INSTALL_PACKAGES" >
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>`

By looking further it seems because of below:

` 

    <uses-sdk android:minSdkVersion="14" />

    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />

    <application>
        <receiver
            android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver"
            android:enabled="true"
            android:exported="true"
            android:permission="android.permission.INSTALL_PACKAGES" >
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
    </application>

</manifest> `

However this ticket was closed for the same reason. https://github.com/firebase/quickstart-unity/issues/538

Google blog notifying the move below:
https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html

Could you please let us know which version of firebase SDK should be  used if this has been fixed. If not is there any plan to fix this issue?

**Comment by jayshildave1983** [comment]
Since the manifest was not getting posted correctly. I have added it additionally in the comment.
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.firebase.measurement_impl" >

**Comment by catman-19** [comment]
Hi @jayshildave1983, sorry for the delay here. The Install Referrer Broadcast Receiver should've been removed on Analytics v18.0.0 (https://firebase.google.com/support/release-notes/android#2020-10-27).
