### ISSUE TITLE
Caused by: java.lang.RuntimeException: Stub! at com.google.firebase.perf.internal.zza.onActivityPreCreated(Unknown Source:170)

### ISSUE THREAD

**Issue by cjohnrajan** [firebase/firebase-android-sdk#1574]
* Android Studio version: 3,6,2
  * Firebase Component: (Firebase Performance
  * Component version: 19.0.7

Issue:
App crashes on Launch after integration with firebase performance monitoriing

Logs:

Caused by: java.lang.R2020-05-20 05:27:28.305 22508-22508/com.cat.abc:E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cat.abc, PID: 22508
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cat.abc/com.cat.abc.activity.LoginActivity}: java.lang.RuntimeException: Stub!
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: java.lang.RuntimeException: Stub!untimeException: Stub!
        at com.google.firebase.perf.internal.zza.onActivityPreCreated(Unknown Source:170)
        at android.app.Application.dispatchActivityPreCreated(Application.java:380)
        at android.app.Activity.dispatchActivityPreCreated(Activity.java:1221)
        at android.app.Activity.performCreate(Activity.java:7949)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)

#### Relevant Code:
**Depenedencies in App level Build.gradle**
ependencies {

    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')

    // HttpClient library
    api('org.apache.httpcomponents:httpmime:4.5.11') {
        exclude module: 'httpclient'
    }
    // JSONApi Library
    //api project(path: ':JsonAPI', configuration: 'default')
    api 'com.gustavofao:JSONApi:1.0.9.3@aar'

    // Analytics / External
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    // Intercom.io
    api('io.intercom.android:intercom-sdk-base:4.1.9') {
        transitive = true
        exclude group: "com.google.auto.value"
        exclude group: "com.google.android.gms"
    }
    api 'io.intercom.android:intercom-sdk-fcm:4.1.9'
    api 'com.github.jgabrielfreitas:BlurImageView:1.0.1'
    api 'com.google.maps.android:android-maps-utils:0.6.2'

    // Google Services

    implementation 'javax.annotation:jsr250-api:1.0'

    **api 'com.google.firebase:firebase-ml-vision:24.0.1'
    implementation 'com.google.firebase:firebase-perf:19.0.7'
    implementation 'com.google.firebase:firebase-core:17.2.3'
    implementation 'com.google.firebase:firebase-messaging:20.1.5'
    implementation 'com.google.android.gms:play-services-analytics:17.0.0'
    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'com.google.android.gms:play-services-wearable:17.0.0'**

    // Android X

    implementation "androidx.appcompat:appcompat:$androidXVersion"
    implementation "androidx.recyclerview:recyclerview:$androidXVersion"
    implementation "androidx.vectordrawable:vectordrawable-animated:$androidXVersion"
    androidTestImplementation "androidx.annotation:annotation:$androidXVersion"

    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.core:core:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    annotationProcessor 'androidx.lifecycle:lifecycle-compiler:2.2.0'

    // ButterKnife
    implementation "com.jakewharton:butterknife:$butterKnifeVersion"
    annotationProcessor "com.jakewharton:butterknife-compiler:$butterKnifeVersion"

    // Dagger
    annotationProcessor "com.google.dagger:dagger-android-processor:$daggerVersion"
    annotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
    implementation "com.google.dagger:dagger-android:$daggerVersion"
    // If you're using classes in dagger.android
    implementation("com.google.dagger:dagger-android-support:$daggerVersion") {
        exclude module: 'support-compat'
    }

    // UI Related
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'de.halfbit:pinned-section-listview:1.0.0'
    implementation 'com.nhaarman.listviewanimations:lib-core:3.1.0@aar'
    implementation 'com.nhaarman.listviewanimations:lib-manipulation:3.1.0@aar'
    implementation 'com.nhaarman.listviewanimations:lib-core-slh:3.1.0@aar'
    implementation 'com.github.apl-devs:appintro:v4.2.2'
    implementation 'com.github.nirhart:parallaxscroll:1.0'
    implementation 'com.github.amlcurran.showcaseview:library:5.4.3'
    implementation 'joda-time:joda-time:2.7'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v2.2.4'

    // Network Related
    implementation 'com.squareup:android-times-square:1.7.10@aar'
    implementation 'com.google.guava:guava:20.0'
    implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.github.kevinsawicki:http-request:6.0'
    implementation 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.auth0.android:lock:2.2.1'
    implementation 'com.facebook.stetho:stetho-okhttp:1.5.1'
    implementation 'com.steelkiwi:cropiwa:1.0.3'
    implementation 'com.github.tgio:rncryptor-native:0.0.9'
    implementation files('libs/java-json.jar')

    // Here Map
    implementation files('libs/HERE-sdk.aar')

    //Testing
    api 'junit:junit:4.13'
    testImplementation 'junit:junit:4.13'
    testImplementation 'org.mockito:mockito-core:1.9.5'
    testImplementation 'org.apache.maven:maven-ant-tasks:2.1.3'
    testImplementation 'org.robolectric:robolectric:4.3.1'
    testImplementation 'org.robolectric:multidex:3.4.2'
    testImplementation 'org.robolectric:shadows-httpclient:4.3.1'
    testImplementation 'org.assertj:assertj-core:3.15.0'
    testImplementation 'com.jayway.android.robotium:robotium-solo:5.6.3'
    testImplementation('com.squareup.assertj:assertj-android:1.2.0') {
        exclude group: 'com.android.support'
    }
    implementation 'javax.annotation:jsr250-api:1.0'

    // Log DNA
    implementation 'com.github.mazenrashed:LogDNA-Android-Client:1.0.1'
    //implementation files('libs/logdna-cm.jar')

    // Cloudinary
    implementation group: 'com.cloudinary', name: 'cloudinary-android', version: '1.26.0'

Plugins in App Level build.gradle

apply plugin: 'com.android.application'
apply plugin: 'dexguard'
apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.firebase-perf'

// TODO(you): code here to reproduce the problem
```


Root level Build.gradle

Buildscript {
    repositories {
        google()
        jcenter()
        mavenLocal()
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath ('com.google.firebase:perf-plugin:1.3.1') {
            exclude group: 'com.google.guava', module: 'guava-jdk5'
        }
    }
}

allprojects {
    repositories {
        google()
        jcenter()

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by visumickey** [comment]
Internally tracked at b/160238041. Attempted on reproducing this issue and could not.

@cjohnrajan Do you have a sample app that can have this issue reproduced?
