### ISSUE TITLE
Document/support AAR-level Crashlytics native symbol generation/upload

### ISSUE THREAD

**Issue by JessHolle** [firebase/firebase-android-sdk#1599]
Document and support AAR-level Crashlytics native symbol generation such that this is done as part of the AAR build and re-used by all downstream apps, e.g. by pushing the symbol files to Maven as a separate artifact and pulling these into app builds.

Far better would be to allow AAR-level _upload_ of native symbols and to have Crashlytics build tooling automatically cross-reference this at the app level based on Maven dependencies.

**Comment by ashwinraghav** [comment]
Thanks for the suggestion.
IIUC, your feature request is for developers who distribute SDKs. The tooling tooling you suggest would allow these developers to supplement their maven artifacts with accompanying symbol mapping files.
The destination app' s Gradle build would unpack this accompanying symbol file an include it while uploading the app's symbol to crashlytics itself.

If that is a fair summary, can you speak to why the current crashlytics mechanism does not satisfy your requirement? Third party library symbols included in your app's apk are already recognized by crashlytics.

**Comment by JessHolle** [comment]
I'm not suggesting this for SDKs but rather for an AAR that is used by multiple APKs/AABs from one vendor, not so much to avoid the OOME but rather so that we could just process the native libraries for each AAR in the build for that AAR.  The Java for each AAR is a different matter -- processing that at the APK/AAB level seems fine by me.  But the AAR doesn't normally contain unstripped .so's and putting *those* in Maven is much ugly compared to the alternatives I've suggested.

**Comment by emreakcan** [comment]
> Thanks for the suggestion. I suspect you are suggesting this in the interest of efficiency, to avoid the OOM error you are facing in #1588 .
> 
> IIUC, your feature request is for developers who distribute SDKs. The tooling tooling you suggest would allow these developers to supplement their maven artifacts with accompanying symbol mapping files. The destination app' s Gradle build would unpack this accompanying symbol file an include it while uploading the app's symbol to crashlytics itself.
> 
> This may not be possible since there are no guarantees that the symbols that accompany these maven artifacts are identical to those that land in the app, because of tools like proguard and R8. So we would have to process the entire app anyway.

So how can we upload our symbols ? What is the suggested way?
https://stackoverflow.com/questions/62051386/firebase-crashlytics-uploadcrashlyticssymbolfile-outofmemoryerror-java-heap

**Comment by JessHolle** [comment]
So there are 2 separate issues as I see it here:

1. The OOME issue that the Firebase Crashlytics SDK has no workaround for -- but the Fabric Crashlytics SDK does.
1. The inconvenience and manageability issue when you have one or more projects that build native libraries, e.g. for distribution within an AAR, for internal use by multiple apps.  In this case, the only reasonable approach I've found is to upload all the unstripped .so's to our internal Maven repository along with the AARs -- and then download these in each app and generate and upload the library symbols in each app.  Given that the unstripped .so's are huge and that this requires extra build wiring in each app using such library, this is not so nice.

So this issue is all about the latter of these issue.

**Comment by JessHolle** [comment]
I'm not clear what additional information you need.  I provided information 7 days ago and got no follow up queries thereafter.  Can you please be explicit about what remaining information you are looking for?

**Comment by AndrewBloom** [comment]
Hi JessHolle, I don't know if you are aware, you can include unstripped version of your libraries on your AAR. check my answer here: https://stackoverflow.com/questions/48829644/how-to-avoid-stripping-native-library-packaged-in-an-aar-for-debug-build-type-on/61654966#61654966
This is what i actually tried to upload native symbols to crashlytics, but without any luck on my end. I had also the complication that my AAR generated a service in a different process, and didn't hear anything from the guys here how to make my situation crashlytics friendly.

**Comment by mrwillis21** [comment]
Hi folks, please check out Crashlytics NDK 17.3.1 and Crashlytics Gradle plugin 2.4.1. These should solve any symbol generation issues you might have.

**Comment by JessHolle** [comment]
I missed your note, but the underlying issue is quite simple:

When building one or more APKs using multiple AARs, we need proper native symbols for crash stacks for all the AARs -- with minimal fuss.

There are actually 2 ideal approaches as I see it:

1. This simply works when you build the APK -- as long as you've not stripped the .so's residing in the AAR -- without any special effort or intervention beyond basic Crashlytics (including NDK) configuration of the APK build.
2. The symbol generation/upload is done at the AAR level and re-used by downstream APK builds.

I had originally been thinking (2) here in this issue, but frankly re-use may be over-rated.  The important thing is that this just work simply and easily.  At this point, (2) may also run into issues because at least in our case some of the libraries are built purely by Conan/CMake and just pulled into AARs from repositories.

Right now `unstrippedNativeLibsDir` is not simple or easy due to interactions with build flavors, etc.  The instructions imply that you must provide stripped and unstripped versions of the .so's from your AARs.  That seems quite unnecessary if you simply do not strip the libraries in your AARs (as the APK build will do this for you).  If you do strip the .so's in your AARs, then the process still seems rather error prone.  Having a custom configuration/dependency type that refers to an AAR-like zip that contains only the unstrippped libraries would seem preferable.

In the end this is all just too hard and error prone by the instructions provided at this time.  And the log feedback as to whether you've got it right or wrong isn't great either.  In the end we lack symbols in many of our native crashes (even with the latest tooling versions), are left wondering if it is us or not, and have ugly, messy stuff in our build.gradle files to try to deal with all of this.  So this issue may well be the wrong stab at a solution and worth closing.  The larger issue remains, however.

**Comment by mrwillis21** [comment]
Hi @JessHolle - Crashlytics NDK 17.3.1 with Gradle plugin version 2.4.1 no longer requires that you set the `strippedNativeLibsDir` field, so it should make things simpler for you. Can you try that out and let me know if being able to remove that field helps? Thanks!

**Comment by JessHolle** [comment]
Are you saying that if I have AARs rolled into my APK and those AARs contain unstripped .so's that things will "just work"?

If so, that'd be fabulous and I'd definitely give that a try!

**Comment by mrwillis21** [comment]
@JessHolle I can't say for certain without better understanding your build setup, but it should do! Do let me know if there's still a sticking point, though. :)

**Comment by JessHolle** [comment]
So... if I don't spell out the stripped and unstripped directories, the latest Crashlytics Gradle plugin (v2.5.0 and with Crashlytics NDK v17.3.1) fails -- perhaps because this Gradle project itself has no native build stage?

I'm hoping I can now at least just do:
```
    buildTypes {
        release {
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                // TODO: remove next lines once Firebase Crashlytics SDK is smart enough to figure this out on its own
                unstrippedNativeLibsDir 'build/intermediates/merged_native_libs/release/out/lib'
                strippedNativeLibsDir 'build/intermediates/stripped_native_libs/release/out/lib'
            }
        ...
```

and just not strip any .so's obtained from dependencies, so I'll give that a go...

**Comment by mrwillis21** [comment]
Hi @JessHolle - just wanted to check back in on this to see if it worked out for you. I'll also add that in the latest Gradle plugin release ([v. 2.5.1](https://firebase.google.com/support/release-notes/android#crashlytics_gradle_plugin_v2-5-1)) we fixed the bug causing the build to fail if you don't specify `strippedNativeLibsDir`, so you really can remove that now. :)

Also, I'm going to be handing this issue off to my colleague, @mrichards, for any further follow up.

**Comment by JessHolle** [comment]
Ah, I'll have to try again with 2.5.1.

I had tried with 2.5.0 and ran into the bug you noted.  But ... once I specified the build processes' normal stripped and unstripped directories I actually did get a symbol for an externally built library showing up in a crash -- without any special work besides not stripping it prior to the app build.

**Comment by JessHolle** [comment]
So I can drop `strippedNativeLibsDir`, but I can't drop `unstrippedNativeLibsDir` in 2.5.1.  That saves 1 line, but still seems equally fragile.

**Comment by JessHolle** [comment]
FYI, now with the 2.6.0 plugin I'm not sure how to even get this working at all if one has build flavors.

**Comment by mrichards** [comment]
Hey, our apologies for dropping this issue. There are no plans at this time to implement AAR-based symbol uploading for Crashlytics. We have increased flexibility in how symbol files are uploaded with new commands in the [Firebase CLI](https://firebase.google.com/docs/crashlytics/ndk-reports#upload-symbols-non-gradle-builds). 

Please reopen this issue if the above does not meet your needs.
