### ISSUE TITLE
Google Firebase sending a reminder is not accurate

### ISSUE THREAD

**Issue by stiffy220** [firebase/firebase-android-sdk#1604]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

The user set up a 5-minute reminder ,But it took six minutes to send the reminder

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ashwinraghav** [comment]
Could you add more information about what Firebase  products you are referring to and what your implementation looks like.
