### ISSUE TITLE
R8 configuration in Firebase Crashlytics

### ISSUE THREAD

**Issue by quiro91** [firebase/firebase-android-sdk#1607]
## What feature would you like to see?

Looking at the [official guide](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=android),  it's recommended to add the following configuration for "faster, obfuscated build with ProGuard".

```
-keep class com.google.firebase.crashlytics.** { *; }
-dontwarn com.google.firebase.crashlytics.**
```

Is this required also for R8? If yes, could it be bundled with the SDK?

**Comment by ashwinraghav** [comment]
Thanks for pointing that out. Seems like we should be able to add these to the SDK

**Comment by quiro91** [comment]
Before adding it, are those actually required? I was testing it before and
it looks like everything works fine without those rules

**Comment by mrwillis21** [comment]
Hi @quiro91 - we've had these as part of the Crashlytics SDK docs for a long time, and it's definitely worth asking the question of whether they're still relevant! I'll raise this up to the team and see how we can best clean this up. Thanks!

**Comment by mrwillis21** [comment]
Hi folks - this has been cleaned up, and should be reflected in the official docs soon. Thanks for the report!
