### ISSUE TITLE
com.google.firebase:firebase-firestore:17.1.4 fails with JetifyTransform

### ISSUE THREAD

**Issue by gustavjon** [firebase/firebase-android-sdk#161]
After updating from com.google.firebase:firebase-firestore:17.1.3 to com.google.firebase:firebase-firestore:17.1.4 my build started failing. My understanding is that this is due to the JetifyTransform task failing for some unknown reason. This is probably not a bug in the code of com.google.firebase:firebase-firestore but I would argue that those dependencies should not be on the compile classpath in the first place. I don't see any obvious reason why for example org.codehaus.mojo:animal-sniffer-annotations should be there anyway.

Android Studio: 3.4 Canary 7
Gradle: 5.0
Build Tools:
```
dependencies {
    classpath("com.android.tools.build:gradle:3.4.0-alpha07")
    classpath(kotlin("gradle-plugin", version = "1.3.11"))
    classpath("com.google.gms:google-services:4.2.0")
    classpath("io.fabric.tools:gradle:1.25.4")
}
```

Build log failure:
-------------------------------------------------------------------------------------------------------------------
```
Transform koin-android.aar (org.koin:koin-android:1.0.2) with AarTransform
> Transform j2objc-annotations.jar (com.google.j2objc:j2objc-annotations:1.1) with JetifyTransform
> Transform j2objc-annotations.jar (com.google.j2objc:j2objc-annotations:1.1) with IdentityTransform
> Transform checker-compat-qual.jar (org.checkerframework:checker-compat-qual:2.5.2) with JetifyTransform
> Transform checker-compat-qual.jar (org.checkerframework:checker-compat-qual:2.5.2) with IdentityTransform
> Transform animal-sniffer-annotations.jar (org.codehaus.mojo:animal-sniffer-annotations:1.17) with JetifyTransform
> Transform animal-sniffer-annotations.jar (org.codehaus.mojo:animal-sniffer-annotations:1.17) with IdentityTransform
> Transform jsr305.jar (com.google.code.findbugs:jsr305:3.0.2) with JetifyTransform
> Transform jsr305.jar (com.google.code.findbugs:jsr305:3.0.2) with IdentityTransform

> Transform error_prone_annotations.jar (com.google.errorprone:error_prone_annotations:2.2.0) with JetifyTransform
ERROR: [TAG] Failed to resolve variable '${junit.version}'

> Transform error_prone_annotations.jar (com.google.errorprone:error_prone_annotations:2.2.0) with IdentityTransform
> Transform opencensus-api.jar (io.opencensus:opencensus-api:0.12.3) with JetifyTransform
> Transform opencensus-api.jar (io.opencensus:opencensus-api:0.12.3) with IdentityTransform
> Transform opencensus-contrib-grpc-metrics.jar (io.opencensus:opencensus-contrib-grpc-metrics:0.12.3) with JetifyTransform
> Transform opencensus-contrib-grpc-metrics.jar (io.opencensus:opencensus-contrib-grpc-metrics:0.12.3) with IdentityTransform
> Transform grpc-context.jar (io.grpc:grpc-context:1.16.1) with JetifyTransform
> Transform grpc-context.jar (io.grpc:grpc-context:1.16.1) with IdentityTransform

> Transform guava.jar (com.google.guava:guava:26.0-android) with JetifyTransform
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'

> Transform guava.jar (com.google.guava:guava:26.0-android) with IdentityTransform
> Transform okio.jar (com.squareup.okio:okio:1.13.0) with JetifyTransform
> Transform okio.jar (com.squareup.okio:okio:1.13.0) with IdentityTransform
```

**Comment by samtstern** [comment]
@gustavjon I don't believe this is related to Firebase.  Could you try using a more stable version of the Android Gradle plugin? `com.android.tools.build:gradle:3.4.0-alpha07` is a very recent alpha version and may have some bugs.  I'd try either `3.3.0-rc02` or `3.2.1`.  If your problem persists with a clean build using one of those plugins, please let me know.

**Comment by gustavjon** [comment]
I agree that the alpha is not very stable, though it works fine for version 17.1.3 so the bug was at the very least exposed by the upgrade to 17.1.4. I do think this is a real problem introduced by those new transitive dependencies and I can't really see why those dependencies are needed on the compile classpath at all.

**Comment by samtstern** [comment]
@gustavjon agree, but I think this bug should be filed on the Android bug tracker so that the AGP developers can take a look at it.  If you need help with that let me know!
