### ISSUE TITLE
.info/connected doesn't come back online if app starts offline

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-android-sdk#1614]
If you start the app without an internet connection the following code:

```
    implementation 'com.google.firebase:firebase-database:19.3.0'
```

```
        println("FIREBASE - addValueEventListener")
        FirebaseDatabase.getInstance().getReference(".info/connected").addValueEventListener(object : ValueEventListener {
            override fun onCancelled(p0: DatabaseError) {
                println("FIREBASE - " + p0)
            }

            override fun onDataChange(p0: DataSnapshot) {
                println("FIREBASE - " + p0.value)
            }
        })
```
logs this on startup
```
2020-06-04 01:21:28.750 21655-21655/dev.gitlive.GitLive I/System.out: FIREBASE - addValueEventListener
2020-06-04 01:21:29.048 21655-21655/dev.gitlive.GitLive I/System.out: FIREBASE - false
```

But doesn't log true after coming back online.

**Comment by ashwinraghav** [comment]
Please include the versions of your SDKs

**Comment by nbransby** [comment]
@ashwinraghav added

**Comment by ashwinraghav** [comment]
On Android, Firebase automatically manages connection state to reduce bandwidth and battery usage. When a client has no active listeners, no pending write or onDisconnect operations, and is not explicitly disconnected by the goOffline method, Firebase closes the connection after 60 seconds of inactivity [[Source](https://firebase.google.com/docs/database/android/offline-capabilities#kotlin+ktx_8)].

If you are purely doing a connection test, you would need a listener to any other node in your database and this would work as you are expecting.
```java
val myConnectionRef2 = database.getReference("/users/joe/lastOnline");
```


Related SO posts: [1](https://stackoverflow.com/questions/47265074/firebase-listener-does-not-identify-or-resume-connection-after-idle-time),[2](https://stackoverflow.com/questions/53069484/firebase-realtime-database-info-connected-false-when-it-should-be-true)

**Comment by nbransby** [comment]
thanks for the clarification
