### ISSUE TITLE
Veracode issue on Firebase in-app messaging CWE ID 327

### ISSUE THREAD

**Issue by cah-deepak-barad** [firebase/firebase-android-sdk#1615]
Environment
Android Studio version: 3.6.1
Firebase Component: Messaging, Analytics
Component version: com.google.firebase:firebase-inappmessaging-display-ktx:19.0.6 , com.google.firebase:firebase-installations

Problem Description:
Veracode has found high severity issues in com.google.firebase:firebase-inappmessaging and  com.google.firebase:firebase-installations related to use of a Broken or Risky Cryptographic Algorithm (CWE ID 327)(2 flaws)

The use of a broken or risky cryptographic algorithm is an unnecessary risk that may result in the disclosure ofsensitive information.

Relevant Code:
com.google.firebase:firebase-inappmessaging@@19.0.6 87
com.google.firebase:firebase-installations@@16.2.1 177

Please advice.

**Comment by cah-rajkumar-ramanathan** [comment]
Hey Hello Wilhuff,(on behalf of @cah-deepak-barad )

Thanks for the timely response so the findings u am posting here
below are the report we got from Vera code

 Medium severity issues

6/28/2019 12:52 PM EDT | OEPlusAndroid-6.1.0-790-prod-release _1_.apk | PlatformRandom.kt: 50 |   | New | None |   |  
-- | -- | -- | -- | -- | -- | -- | --
4 |   | Unlikely |   | 6/28/2019 12:52 PM EDT | OEPlusAndroid-6.1.0-790-prod-release _1_.apk | PlatformRandom.kt: 45 | 
5 |   | Unlikely |   | 6/28/2019 12:52 PM EDT | OEPlusAndroid-6.1.0-790-prod-release _1_.apk | PlatformRandom.kt: 46 |  
6 |   | Unlikely |   | 6/28/2019 12:52 PM EDT | OEPlusAndroid-6.1.0-790-prod-release _1_.apk | PlatformRandom.kt: 44 |  
7 |   | Unlikely |   | 6/28/2019 12:52 PM EDT | OEPlusAndroid-6.1.0-790-prod-release _1_.apk | PlatformRandom.kt: 42 |  

all the above are the same CWE ID & Name of Insufficient Entropy

Please let me know if the clarity if needed more on this.

**Comment by cah-rajkumar-ramanathan** [comment]
One more

3 |   | Unlikely | 331  Insufficient Entropy | 6/28/2019 12:52 PM EDT | OEPlusAndroid-6.1.0-790-prod-release _1_.apk | PlatformRandom.kt: 50 | 1 Path | New | None
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by cah-rajkumar-ramanathan** [comment]
3 |   | Unlikely | 331  Insufficient Entropy | 6/28/2019 12:52 PM EDT | OEPlusAndroid-6.1.0-790-prod-release _1_.apkOEPlusAndroid-6.1.0-790-prod-release _1_.apk | PlatformRandom.kt: 50 | 1 Path | New | None
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by wilhuff** [comment]
I don't think that really helps. As far as I can tell, this is giving you information about _your_ binary, but that doesn't help us identify which APIs your tool actually thinks are risky. For starters, there is no `PlatformRandom.kt` in any of our sources.

If you can identify what specifically this tool is complaining out in the Firebase sources, we'll happily look at it and potentially address it, if there is a real issue. As it stands I can't connect this report to any of the things we actually do.

**Comment by cah-rajkumar-ramanathan** [comment]
thats quick. will check with veracode team and update.

**Comment by cah-rajkumar-ramanathan** [comment]
Below are the sources with line number causing


Flaw ID | Comment
-- | --
13 | https://github.com/firebase/firebase-android-sdk/blob/0e93870a9bfd6f0f1603d82dca2e5dfd91425726/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java#L434
16 | https://github.com/firebase/firebase-android-sdk/blob/443d6e74da404925b15cc0b62963584c537e23ef/firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java#L150
17 | https://github.com/firebase/firebase-android-sdk/blob/c7e06bc8e31da29a168fff9d802962ea2b37b9a4/firebase-installations/src/main/java/com/google/firebase/installations/local/IidStore.java#L179
18 | https://github.com/firebase/firebase-android-sdk/blob/6e293abbfaa8f6a36edde6ddde1dc496d78b2746/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/GrpcClientModule.java#L89
19 | https://github.com/firebase/firebase-android-sdk/blob/455e48371ef627b1aa387126f1ff5bd91544fe3c/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L297
20 | https://github.com/firebase/firebase-android-sdk/blob/455e48371ef627b1aa387126f1ff5bd91544fe3c/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L372
21 | https://github.com/firebase/firebase-android-sdk/blob/455e48371ef627b1aa387126f1ff5bd91544fe3c/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L203
22 | https://github.com/firebase/firebase-android-sdk/blob/455e48371ef627b1aa387126f1ff5bd91544fe3c/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L420

**Comment by cah-rajkumar-ramanathan** [comment]
More detailed analysis PDF attaching here. PFA
[veracode-firebase-issues.pdf](https://github.com/firebase/firebase-android-sdk/files/4762402/veracode-firebase-issues.pdf)

**Comment by andirayo** [comment]
I had a brief look at all cases regarding `FirebaseInstallations`. \
All usages seem to be fine and do not pose risks for security or confidentiality. \

To give an example of the raised issues:
```
The application calls the java.net.URL.openConnection()
function, which will result in data being transferred out of the application (via
the network or another medium). [...]
```
It is correct that data is being transferred out of the application, but this is desired behavior: In order to enable Firebase functionality, Firebase SDKs have to send requests and data to Firebase server APIs.

**Comment by cah-rajkumar-ramanathan** [comment]
@andirayo  There some issue description provided in the PDF i have shared. please have a look at them for the detailed context of the each issues.

**Comment by wilhuff** [comment]
These are non-issues.

  * Flaw 13 flags the use of `Random` instead of `SecureRandom`, but this isn't a cryptographic use; we're just randomizing the time interval for retrying after backoff
  * Flaw 16 flags the use of `File.createTempFile` but this is a non-issue on Android
  * Several flaws flag the use of SHA1, but this is done for compatibility reasons and does not handle credentials
  * As @andirayo notes, the use of connections to external servers is expected and intended because this forms the basis of product behavior.

Thanks for raising the issue, but there's no action to be taken here.
