### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by 2ZeroSix** [firebase/firebase-android-sdk#1616]
* Firebase Component: Auth

## What feature would you like to see?

Is there any plans to add multi-tenancy support?
It's available in js client/admin sdk https://cloud.google.com/identity-platform/docs/multi-tenancy-authentication

## How would you use it?

Same as in js client package.

**Comment by ashwinraghav** [comment]
Thank you for the feature request. We do have plans to support this soon. I don't have an actual date however. I'll keep the ticket open and post back when we know more!
Thanks!

**Comment by rosariopfernandes** [comment]
The Release Notes for [Firebase Auth 19.4.0](https://firebase.google.com/support/release-notes/android#auth_v19-4-0) says Multi-tenancy is now supported.

I think we can close this issue now.
