### ISSUE TITLE
Firebase-crashlytics Gradle plugin: kotlin dsl support

### ISSUE THREAD

**Issue by sboishtyan** [firebase/firebase-android-sdk#1622]
## What feature would you like to see?

I want to be able to configure `firebase-crashlytics` Gradle plugin in `build.gradle.kts` files

## How would you use it?

It helps me to remove `apply(from = *.gradle)`

**Comment by vkryachko** [comment]
It is actually supported, to use it try the following in your `build.gradle.kts`

```
plugins {
  //...
  id("com.google.firebase.crashlytics")
}

android {
  buildTypes {
    getByName("release") {
            (this as ExtensionAware).configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = true
                nativeSymbolUploadEnabled = true
                // etc.
            }
    }
  }
}
    }
  }
}
```

feel free to re-open if it does not work for you.

**Comment by sboishtyan** [comment]
@vkryachko ExtensionAware helped
But I couldn't apply plugin in `plugins` block, so I used legacy `apply` block
