### ISSUE TITLE
SignInButton does not render Hindi font on api level 19

### ISSUE THREAD

**Issue by rinav** [firebase/firebase-android-sdk#163]
### Step 2: Describe your environment

  * Android Studio version: 3.3 RC2
  * Firebase Component: Auth
  * Component version: firebase-auth:16.1.0 and play-services-auth:16.0.1

### Step 3: Describe the problem
I am developing an app in Hindi and using Firebase auth for Google SignIn. My default font is Hindi and 
`SignInButton` button does not render hindi font on API level 19.
Moreover the button text is blank.

#### Steps to reproduce:

If you run this code on API Level 19, with Hindi font it does not render it.

#### Relevant Code:

```
<com.google.android.gms.common.SignInButton
                android:id="@+id/google_sign_in"
                android:layout_width="300dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="8dp"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="8dp"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/auth_message"/>
```

Need a way to change font based on locale either programmatically or via XML `android:fontFamily="@font/hindi_font"`

![device-2018-12-13-170244](https://user-images.githubusercontent.com/3099775/49936337-aeeed680-fef9-11e8-97a5-1061b531b7a7.png)

**Comment by samtstern** [comment]
@rinav thanks for filing this!  This is not a Firebase issue so I am going to close it here (there's nothing I can do about it personally) but I am going to copy all of this into an internal bug report with the Google Sign In team so they can hopefully fix it.
