### ISSUE TITLE
Firebase Analytics begin_checkout Items not send

### ISSUE THREAD

**Issue by beli63** [firebase/firebase-android-sdk#1631]
### Step 2: Describe your environment

  * Android Studio version: 3.6.3
  * Firebase Component: Analytics
  * Component version: 17.4.3

### Step 3: Describe the problem

Recently, I've implemented **FirebaseAnalytics.Event.BEGIN_CHECKOUT** event. But it seems **FirebaseAnalytics.Param.ITEMS** not be sent to Firebase.

#### Steps to reproduce:

This code is the tutorial code from Firebase.

It seems **FirebaseAnalytics.Param.ITEMS** not been send, but if I send **item_id** and **item_name**, these 2 fields appear on my event datas

Any solution ?

#### Relevant Code:

```
val itemJeggings1 = Bundle().apply {
            putString(FirebaseAnalytics.Param.ITEM_ID, "SKU_123")
            putString(FirebaseAnalytics.Param.ITEM_NAME, "jeggings")
            putString(FirebaseAnalytics.Param.ITEM_CATEGORY, "pants")
            putString(FirebaseAnalytics.Param.ITEM_VARIANT, "black")
            putString(FirebaseAnalytics.Param.ITEM_BRAND, "Google")
            putDouble(FirebaseAnalytics.Param.PRICE, 9.99)
        }
val itemJeggings2 = Bundle().apply {
            putString(FirebaseAnalytics.Param.ITEM_ID, "SKU_12309")
            putString(FirebaseAnalytics.Param.ITEM_NAME, "jeggings")
            putString(FirebaseAnalytics.Param.ITEM_CATEGORY, "pants")
            putString(FirebaseAnalytics.Param.ITEM_VARIANT, "black")
            putString(FirebaseAnalytics.Param.ITEM_BRAND, "Levis")
            putDouble(FirebaseAnalytics.Param.PRICE, 16.99)
        }
Firebase.analytics.logEvent(FirebaseAnalytics.Event.BEGIN_CHECKOUT) {
            param(FirebaseAnalytics.Param.CURRENCY, "EUR")
            param(FirebaseAnalytics.Param.VALUE, 36.0)
            param(FirebaseAnalytics.Param.COUPON, "SUMMER_FUN")
            param(FirebaseAnalytics.Param.ITEMS, arrayOf(itemJeggings1, itemJeggings2))
        }
```

**Comment by ashwinraghav** [comment]
Thanks for the report folks. 
I sense this may be a problem better suited for [support](https://firebase.google.com/support), since it seems to affect a specific set of projects and may require that you share provide info not suitable for sharing publicly on GitHub. 
Please file tickets with specific projects/apps that this affects and we'll be able to help you better.
