### ISSUE TITLE
ANR during firebase initialisation

### ISSUE THREAD

**Issue by sallukp** [firebase/firebase-android-sdk#1632]
Our users encounters ANR while initializing firebase. I added the stack trace below

```
"firebase-installations-executor-1" prio=5 tid=24 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x162c2088 self=0x8bc13a00
  | sysTid=2487 nice=0 cgrp=default sched=0/0 handle=0x8ae67970
  | state=S schedstat=( 2596299 1043855 27 ) utm=0 stm=0 core=5 HZ=100
  | stack=0x8ad64000-0x8ad66000 stackSize=1042KB
  | held mutexes=
  at android.app.ContextImpl.getFilesDir (ContextImpl.java:647)
- waiting to lock <0x0ef8f412> (a java.lang.Object) held by thread 1
  at android.content.ContextWrapper.getFilesDir (ContextWrapper.java:239)
  at com.google.firebase.installations.b.a
  at com.google.firebase.installations.g.i
  at com.google.firebase.installations.g.c
  at com.google.firebase.installations.g.h
  at com.google.firebase.installations.g.a
  at com.google.firebase.installations.c.run
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by rlazo** [comment]
Thanks for reporting. We need some help from you to triage this, could you please add the products and versions you're using?

**Comment by ashwinraghav** [comment]
It also seems like your application is proguarded. 
We'd be able to map things back to code in the SDK if you provide a de-obfuscated log.

**Comment by sallukp** [comment]
Thank you for the responses. 

@rlazo We use the following products
`  
    implementation 'com.google.firebase:firebase-core:17.4.0'
    implementation 'com.google.firebase:firebase-analytics:17.4.0'
    // Add the Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:17.0.0'
    implementation 'com.google.firebase:firebase-crashlytics-ndk:17.0.0'
    implementation 'com.google.firebase:firebase-ml-natural-language:22.0.0'
    implementation 'com.google.firebase:firebase-ml-natural-language-smart-reply-model:20.0.7'`

@ashwinraghav We could not reproduce this ANR in our devices. We found this ANR in play store console. So we don't have de-obfuscated log.
