### ISSUE TITLE
The request is missing the reCaptcha token

### ISSUE THREAD

**Issue by mwaked** [firebase/firebase-android-sdk#1634]
Hello, 
I hope all is well,
I use firebase phone authentication and this error message "The request is missing the reCaptcha token" is return in `onVerificationFailed` method only on some Android devices, why this error happened? and how can i fix this error?

**Device Details**
- Device: Huawei
- Android version: Android 10
- Google Mobile Services (GMS) is available

**Android Code**
````
PhoneAuthProvider.getInstance().verifyPhoneNumber(
        phoneNumber,
        60,
        TimeUnit.SECONDS,
        this,
        mCallbacks);

private PhoneAuthProvider.OnVerificationStateChangedCallbacks mCallbacks = new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {

    @Override
    public void onVerificationFailed(@NonNull FirebaseException e) {
      
        Log.w(TAG, "onVerificationFailed", e);

    }

    @Override
    public void onVerificationCompleted(@NonNull PhoneAuthCredential credential) {

        Log.d(TAG, "onVerificationCompleted: " + credential);

    }

    @Override
    public void onCodeSent(@NonNull String verificationId,
                           @NonNull PhoneAuthProvider.ForceResendingToken token) {

        Log.d(TAG, "onCodeSent:" + verificationId);

    }
};

@Override
public void onOtpCompleted(String otp) {
   PhoneAuthCredential credential = PhoneAuthProvider.getCredential(mVerificationId, otp);
 sigintWithCredential(credential);
}
private void sigintWithCredential(PhoneAuthCredential credential) {
    showLoadingView();

    mAuth.signInWithCredential(credential)
            .addOnCompleteListener(this, task -> {
                if (task.isSuccessful()) {

                    Log.d(TAG, "signInWithCredential:success");

                    FirebaseUser user = Objects.requireNonNull(task.getResult()).getUser();

                } else {

                    String errorMessage = Objects.requireNonNull(task.getException()).getLocalizedMessage();

                    if (task.getException() instanceof FirebaseAuthInvalidCredentialsException) errorMessage = getString(R.string.invalid_code);

                    Log.w(TAG, "signInWithCredential:failure", task.getException());

     

                }
            });

}

**Comment by CoderJava** [comment]
Yeah

> Hello,
> I hope all is well,
> I use firebase phone authentication and this error message "The request is missing the reCaptcha token" is return in `onVerificationFailed` method only on some Android devices, why this error happened? and how can i fix this error?
> 
> **Device Details**
> 
> * Device: Huawei
> * Android version: Android 10
> * Google Mobile Services (GMS) is available
> 
> **Android Code**
> 
> ```
> PhoneAuthProvider.getInstance().verifyPhoneNumber(
>         phoneNumber,
>         60,
>         TimeUnit.SECONDS,
>         this,
>         mCallbacks);
> 
> private PhoneAuthProvider.OnVerificationStateChangedCallbacks mCallbacks = new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
> 
>     @Override
>     public void onVerificationFailed(@NonNull FirebaseException e) {
>       
>         Log.w(TAG, "onVerificationFailed", e);
> 
>     }
> 
>     @Override
>     public void onVerificationCompleted(@NonNull PhoneAuthCredential credential) {
> 
>         Log.d(TAG, "onVerificationCompleted: " + credential);
> 
>     }
> 
>     @Override
>     public void onCodeSent(@NonNull String verificationId,
>                            @NonNull PhoneAuthProvider.ForceResendingToken token) {
> 
>         Log.d(TAG, "onCodeSent:" + verificationId);
> 
>     }
> };
> 
> @Override
> public void onOtpCompleted(String otp) {
>    PhoneAuthCredential credential = PhoneAuthProvider.getCredential(mVerificationId, otp);
>  sigintWithCredential(credential);
> }
> private void sigintWithCredential(PhoneAuthCredential credential) {
>     showLoadingView();
> 
>     mAuth.signInWithCredential(credential)
>             .addOnCompleteListener(this, task -> {
>                 if (task.isSuccessful()) {
> 
>                     Log.d(TAG, "signInWithCredential:success");
> 
>                     FirebaseUser user = Objects.requireNonNull(task.getResult()).getUser();
> 
>                 } else {
> 
>                     String errorMessage = Objects.requireNonNull(task.getException()).getLocalizedMessage();
> 
>                     if (task.getException() instanceof FirebaseAuthInvalidCredentialsException) errorMessage = getString(R.string.invalid_code);
> 
>                     Log.w(TAG, "signInWithCredential:failure", task.getException());
> 
>      
> 
>                 }
>             });
> 
> }
> ```

I have the same problem.

**Comment by herotha** [comment]
I meet this problem too.
Here log from crashlytic.
![image text](https://res.cloudinary.com/dbvxwnxew/image/upload/v1600258146/Screen_Shot_2020-09-16_at_7.08.55_PM_larrfn.png)
![image text](https://res.cloudinary.com/dbvxwnxew/image/upload/v1600257906/Screen_Shot_2020-09-16_at_6.55.12_PM_t3gl4x.png)

**Comment by malcolmdeck** [comment]
Hey folks,

I can speak to this one a little bit. There are two pieces here. 

(1) Our error code says the wrong thing - I've filed b/169071896 to track that getting fixed internally. 
(2) These devices aren't passing security checks when contacting our Phone Authentication APIs. There's no real remedy to this right now - some users use rooted or otherwise tampered-with Android devices, and that's not allowed when calling our Phone Auth APIs.

Hope that helps!
~Malcolm

**Comment by sotiris08** [comment]
What about the emulators?

**Comment by malcolmdeck** [comment]
I should have closed this issue a while ago - it is no longer relevant to how new versions of the SDK function.

@sotiris08 if you're having an problem, please file a new Github issue with the details of what you're seeing :)
