### ISSUE TITLE
[crashlytics ndk] Make crashlytics.h compatible with C

### ISSUE THREAD

**Issue by rpattabi** [firebase/firebase-android-sdk#1641]
Firebase Crashlytics now provides `crashlytics.h` to add info to crash reports from C++. However this is not compatible with C.

Making `crashlytics.h` C compatible would help as we can log from critical C code as well.

**Comment by kmandrika** [comment]
Hi @rpattabi,

Thanks for the feedback! For now, you can try using the initial version of [crashlytics.h](https://github.com/firebase/firebase-android-sdk/blob/8f02834e94f8b24a7cf0f777562cad73c6b9a40f/firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/external/crashlytics.h), it should still work. Apologies that we don't have a better workaround for you!

**Comment by ashwinraghav** [comment]
Given that this is expected to work, it would help to have more info on whether you see actual failures when you use it in C.

**Comment by rpattabi** [comment]
@ashwinraghav It is a C++ only header now unlike earlier version. If I use this in C, currently I get the following error as C doesn't have `cstddef`.

```
  ../../../../src/main/cpp/crashlytics.h:17:10: fatal error: 'cstddef' file not found
  #include <cstddef>
           ^~~~~~~~~
```

 There will be other errors as C doesn't know about C++'s `namespace`, etc.

**Comment by ashwinraghav** [comment]
Thanks, I may have misunderstood. Thanks for clarifying
