### ISSUE TITLE
Android NDK crashlytics symbols not uploading

### ISSUE THREAD

**Issue by rgipd** [firebase/firebase-android-sdk#1642]
Hello.

  My configuration is:
```
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.1.1'
    implementation 'com.google.firebase:firebase-crashlytics-ndk:17.0.1' (tried with 17.0.0 as well)
```

  And, for debug and release is the same:
```
      buildTypes {
        debug {
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
            }
        }
```

  After build debug: ```./gradlew app:uploadCrashlyticsSymbolFileDebug```
  After build release: ```./gradlew app:uploadCrashlyticsSymbolFileRelease```

  Info: All the symbols are successfully uploaded. Tested even with signed apk uploaded to Google Play Store.
  

  **Problem**  
  I make some forced crash in NDK using ```assert(false); // debug``` or ```abort(); // debug and release```, the app crashes in emulator and in real devices.
  The Firebase Crashlytics Console appears the error, but with "???" and "Missing()".

  I even uploaded debug, tested. Then uploaded release, tested again.
  Changed from 17.0.1 to 17.0.0, but the symbols are missing.

  In iOS version, it works flawless (Objective-C).
  In Android with kotlin, also work showing all classes.
  The problem is the Native NDK library. I'm using CMake and one library without anything as external build.

Can someone has any idea of how can I debug or show some debug of symbols uploading? Or it's missing something for NDK specifically? 

Thanks in advance.

**Comment by ashwinraghav** [comment]
Possible duplicate #1599 #1316
