### ISSUE TITLE
Invalid instruction 'tagetApi' after upgrading to crashlytics 17.0.0

### ISSUE THREAD

**Issue by laitooo** [firebase/firebase-android-sdk#1660]
Iam using Android studio 2.2 
compile sdk version 28
minSdkVersion 16
buildToolsVersion 28.0.3

After upgrading to firebase-crashlytics 17.0.0
Thus error started to show :
>Error:Execution failed for task ':app:processDebugManifest'.
 [com.google.firebase:firebase-common:19.3.0] Z:\Projects\Android\MangaOnline\app\build\intermediates\exploded-aar\com.google.firebase\firebase-common\19.3.0\AndroidManifest.xml:32:9-36:35: Error: Invalid instruction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT

i realized there's a 'targetapi=n' in firebase common's manifest
but i cant change it

what should i do?

**Comment by ashwinraghav** [comment]
I get the impression you are using an old version of the Android SDK. Try upgrading and let us know.
