### ISSUE TITLE
Missing Source for firebase-bom

### ISSUE THREAD

**Issue by jkasten2** [firebase/firebase-android-sdk#1661]
## What feature would you like to see?
This repo is missing the `firebase-bom` module and having the source code for this would be useful. Even if it is just a config file.

## How would you use it?
It will make it easier to:
* Know which exact modules will be used from the `com.google.firebase` group.
  - Without have to build a Gradle project to find the result
* Debug dependency issues when they come up such as these issues.
   -  [Some which have come up in the past](https://github.com/search?q=firebase-bom+repo%3Afirebase%2Ffirebase-android-sdk+label%3A%22api%3A+bom%22&type=Issues&ref=advsearch&l=&l=)

**Comment by ashwinraghav** [comment]
Thanks for the request. We'll consider this going forward. For what it's worth, these are the artifacts in the bom. The general idea we have it to ensure all FIrebase versions work at their latest versions. So at any point, the latest BoM is expected to codify the latest versions of these SDKs available at maven.google.com.
```
com.crashlytics.sdk.android:crashlytics
com.google.firebase:firebase-ads
com.google.firebase:firebase-ads-lite
com.google.firebase:firebase-analytics
com.google.firebase:firebase-analytics-ktx
com.google.firebase:firebase-appindexing
com.google.firebase:firebase-auth
com.google.firebase:firebase-auth-ktx
com.google.firebase:firebase-config
com.google.firebase:firebase-config-ktx
com.google.firebase:firebase-core
com.google.firebase:firebase-crash
com.google.firebase:firebase-crashlytics
com.google.firebase:firebase-crashlytics-buildtools
com.google.firebase:firebase-crashlytics-gradle
com.google.firebase:firebase-crashlytics-ndk
com.google.firebase:firebase-database
com.google.firebase:firebase-database-ktx
com.google.firebase:firebase-dynamic-links
com.google.firebase:firebase-dynamic-links-ktx
com.google.firebase:firebase-firestore
com.google.firebase:firebase-firestore-ktx
com.google.firebase:firebase-functions
com.google.firebase:firebase-functions-ktx
com.google.firebase:firebase-inappmessaging
com.google.firebase:firebase-inappmessaging-display
com.google.firebase:firebase-inappmessaging-display-ktx
com.google.firebase:firebase-inappmessaging-ktx
com.google.firebase:firebase-invites
com.google.firebase:firebase-messaging
com.google.firebase:firebase-messaging-directboot
com.google.firebase:firebase-ml-model-interpreter
com.google.firebase:firebase-ml-natural-language
com.google.firebase:firebase-ml-natural-language-language-id-model
com.google.firebase:firebase-ml-natural-language-smart-reply
com.google.firebase:firebase-ml-natural-language-smart-reply-model
com.google.firebase:firebase-ml-natural-language-translate
com.google.firebase:firebase-ml-natural-language-translate-model
com.google.firebase:firebase-ml-vision
com.google.firebase:firebase-ml-vision-automl
com.google.firebase:firebase-ml-vision-barcode-model
com.google.firebase:firebase-ml-vision-face-model
com.google.firebase:firebase-ml-vision-image-label-model
com.google.firebase:firebase-ml-vision-object-detection-model
com.google.firebase:firebase-perf
com.google.firebase:firebase-storage
com.google.firebase:firebase-storage-ktx
```

**Comment by jkasten2** [comment]
@ashwinraghav Thanks for super quick reply!
I just discovered [Gradle's BOM feature](https://docs.gradle.org/6.5/userguide/platforms.html#sub:bom_import) after I stumbled upon a project using `firebase-pom`. Super useful feature to ensure compatible versions of modules are used as you noted, glad to see Firebase has this!

When I went through the [Firebase FCM Android setup guide](https://firebase.google.com/docs/cloud-messaging/android/client) it didn't recommend using `firebase-bom`.
Might be a good idea to use it in part 1 step 3 like this:
```gradle
implementation platform('com.google.firebase:firebase-bom:25.4.1')
implementation 'com.google.firebase:firebase-messaging'
```

Might be a good idea to put a link to the ["Control library versioning with a Firebase Bill of Materials (BoM)"](https://firebase.google.com/docs/android/setup#firebase-bom) section in each of your specific Firebase setup guides too, not just FCM.

---

Back to the topic, I found these links useful to know which versions `firebase-pom` is recommending:
* https://firebase.google.com/support/release-notes/android#bom_v25-4-1
* https://maven.google.com/com/google/firebase/firebase-bom/25.4.1/firebase-bom-25.4.1.pom

**Comment by ashwinraghav** [comment]
Cc @rachelsaunders

**Comment by thatfiredev** [comment]
It's been 2 years since this issue was first opened, I thought I would share 2 relevant updates here:

1. The BoM generator has been [open sourced](https://github.com/firebase/firebase-android-sdk/tree/master/buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator) and the list of modules can be found in the [BomGeneratorTask.java](https://github.com/firebase/firebase-android-sdk/blob/master/buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java) file:
    https://github.com/firebase/firebase-android-sdk/blob/939f90edd74373d42772518d04826657c2ef2e21/buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java#L51-L95
1.  Our Release Notes page now includes a ["Compare BoM versions" widget](https://firebase.google.com/support/release-notes/android#compare-bom-versions) which lets you compare the module versions included in different versions of the Firebase BoM.

**Comment by rachelsaunders** [comment]
Thanks [jkasten2](https://github.com/jkasten2) for providing this feedback about the BoM -- we're glad that you're finding it useful.  And thanks for providing some of the relevant updates, [thatfiredev](https://github.com/thatfiredev) :-D

In addition to the 2 places that @thatfiredev listed, for each release of the BoM, we list the BoM in the [Firebase release notes for Android](https://firebase.google.com/support/release-notes/android). In the BoM's release notes entry, you can expand the `Firebase Android SDKs mapped to this BoM version` line to view a table of which versions are in the new release, as well as highlights of which libraries are versioning.  Here's a recent example: https://firebase.google.com/support/release-notes/android#bom_v30-2-0

I wanted to also call out that a while back, we also updated all our getting started materials to recommend using the BoM! for example: https://firebase.google.com/docs/android/setup#add-sdks and https://firebase.google.com/docs/cloud-messaging/android/first-message#add_firebase_sdks_to_your_app

**Comment by jkasten2** [comment]
Thanks for getting back to me, these links are helpful!

I also noticed a POM file with the `<dependencyManagement>` tag is available with these too:
https://maven.google.com/web/index.html?q=firebase-bom#com.google.firebase:firebase-bom:30.2.0

Closing this issue since these resolve my issue.
