### ISSUE TITLE
Improper Output Neutralization for Logs

### ISSUE THREAD

**Issue by Yesferal** [firebase/firebase-android-sdk#1666]
###  Step 2: Describe your environment

  * Android Studio version: 3.6
  * Firebase Component: Analytics
  * Component version: 17.0.1

#### Steps to reproduce:

Hello Firebase, I use your Android SDK in my application. I test my app in a Vulnerability Assessment Scanner Tools. One of the errors found by the tool is the incorrect use of the Android log in the class FirebaseInstallationServiceClient.java ([github](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java)). I would be very grateful if you could inspect the issue. If you would like to ask me any questions, please feel free to do so.

#### Scanner Tool Description:
CWEID 117 - FLAWID 397 - PCI Related - Improper Output Neutralization for Logs

DESCRIPTION: A function call could result in a log forging attack. Writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files. Corrupted log files can be used to cover an attacker's tracks or as a delivery mechanism for an attack on a log viewing or processing utility. For example, if a web administrator uses a browser-based utility to review logs, a cross-site scripting attack might be possible.

RECOMMENDED: This call to android.util.Log.w() could result in a log forging attack. Writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files. Corrupted log files can be used to cover an attacker's tracks or as a delivery mechanism for an attack on a log viewing or processing utility. For example, if a web administrator uses a browser-based utility to review logs, a cross-site scripting attack might be possible. The second argument to w() contains tainted data from the variable logString. The tainted data originated from earlier calls to javax.net.ssl.HttpsURLConnection.getResponseMessage, java.net.HttpURLConnection.getResponseMessage, javax.net.ssl.HttpsURLConnection.getErrorStream, and java.net.HttpURLConnection.getErrorStream.

Avoid directly embedding user input in log files when possible. Sanitize untrusted data used to construct log entries by using a safe logging mechanism such as the OWASP ESAPI Logger, which will automatically remove unexpected carriage returns and line feeds and can be configured to use HTML entity encoding for non-alphanumeric data. Alternatively, some of the XSS escaping functions from the OWASP Java Encoder project will also sanitize CRLF sequences. Only write custom blacklisting code when absolutely necessary. Always validate untrusted input to ensure that it conforms to the expected format, using centralized data validation routines when possible.

#### Relevant Code:

Issue Location
SOURCEFILE: FirebaseInstallationServiceClient.java
SOURCEFILEPATH: com/google/firebase/installations/remote
LINE 532

**Comment by ashwinraghav** [comment]
Thanks for the really clear description. If I understand correctly, this attack makes it possible for a bad actor to dilute the validity of logs, to remove any footprint they may have left behind. Seems like the most common case is to avoid printing logs that have any form of use input.

In this case, it seems like we are printing the output of the response from a service. 
- Do you have thoughts on why that may be considered user input and what a potential attack looks like ?

https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java#L576-L580

**Comment by Yesferal** [comment]
Hi, I read more about the issue and the function that have the problem. The tool considered this as a potencial attack because  the response of service could contain `\n`. E.g.  the fake message could has the line `\n No Error: The response was successful\n`. So, in your logs you could read 

- Error when communicating with the Firebase Installations server API. HTTP response: [var1 var2: var3]
- No Error: The response was successful

**Comment by ashwinraghav** [comment]
Thanks for the response. How would the fake message `\n No Error: The response was successful\n` be injected into the logs  ?
