### ISSUE TITLE
Reenable firebase_crashlytics_collection_enabled will send previous crash report

### ISSUE THREAD

**Issue by doniwinata0309** [firebase/firebase-android-sdk#1669]
Suppose i set firebase_crashlytics_collection_enabled = false on debug variant to disable crash report. Then i build release (both debug and release has the same package) where  firebase_crashlytics_collection_enabled = true. When i force crash on release, somehow the crash on debug also uploaded to firebase crashlytics. 

1. Is this expected ?
2. How to avoid uploading crash report from debug while firebase_crashlytics_collection_enabled is already false ?

**Comment by ashwinraghav** [comment]
Unfortunately we don't make a distinction at runtime about what variants caused the crash. Once the flag is enabled, crashes on disk are flushed out to the backend.
In practice, this should cause an issue if your audiences for your debug builds and release builds are different. I understand that you will run into this situation developer devices.
 
I don't think this is a distinction that we can make effectively without introducing other forms of unexpected behavior.

https://github.com/firebase/firebase-android-sdk/blob/0e93870a9bfd6f0f1603d82dca2e5dfd91425726/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java#L446-L462

**Comment by prempalsingh** [comment]
@ashwinraghav Is there any way to completely disable Crashlytics on debug and not even store the crashes on disk?
