### ISSUE TITLE
Open source the code for `com.google.firebase:firebase-iid`

### ISSUE THREAD

**Issue by yogurtearl** [firebase/firebase-android-sdk#1679]
## What feature would you like to see?

Open source the code for `com.google.firebase:firebase-iid`

## How would you use it?

To troubleshoot/debug related problems and better understand the usages in the existing OSS codebase.

**Comment by ashwinraghav** [comment]
Unfortunately, this is something that we're not going to be able to do. But, we do plan to have products migrate off of iid and use firebase-installations, which is already open source. There's already a couple of products that have already migrated. You can expect all of Firebase to be off of iid over the next few months!
