### ISSUE TITLE
MLkit barcode scanner cannot decode simple 1D code, Example "2"

### ISSUE THREAD

**Issue by longld103** [firebase/firebase-android-sdk#1698]
<img width="251" alt="Screen Shot 2020-06-17 at 10 26 38 AM" src="https://user-images.githubusercontent.com/8160105/84997259-86900a00-b178-11ea-8581-82b93135ab3b.png">

### Environment

  * Android device: Samsung galaxy note10 (N975F)
  * Android OS version: Android 10
  * Google Play Services version: com.google.gms:google-services:4.3.3
  * Firebase/Play Services SDK version: com.google.firebase:firebase-ml-vision:24.0.3
  
### Describe the problem:
I can't see any barcode result appear on the live camera stream when run this sample
#### Steps to reproduce:

  1. live stream camera view and focus to the barcode
  
#### Observed Results:

  * there is no barcode appeared
  
#### Expected Results:

  * Barcode should appeared with value is "2"

**Comment by samtstern** [comment]
@longld103 I have moved this over to the `firebase-android-sdk` repo.  In your other issues you have demonstrated that you do know how to read a barcode successfully using MLKit, which implies that this may be a real bug in the SDK with very small codes.

**Comment by zhouyiself** [comment]
@longld103, thanks for the report! Have filed an internal bug to track this, will ping here when there's update.

**Comment by zhouyiself** [comment]
We internally have a minimum barcode length setup to prevent false positives (currently is 2), so this is work as intended.

**Comment by longld103** [comment]
@zhouyiself  thank for your support 😘

**Comment by vkryachko** [comment]
Moved this issue to the mlkit repo: https://github.com/googlesamples/mlkit/issues/225
