### ISSUE TITLE
Message: "Crashlytics could not find NDK build tasks on which to depend."

### ISSUE THREAD

**Issue by kenmorse** [firebase/firebase-android-sdk#1700]
### Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: Crashlytics, firebase-crashlytics-gradle plugin
  * Component version: 2.2.0

### Describe the problem

The problem with specifying NDK library paths was helpfully fixed as part of issue #1199; however, the new version 2.2.0 of the firebase-crashlytics-gradle plugin now produces this message:

> Crashlytics could not find NDK build tasks on which to depend. You many need to manually enforce task dependencies for generateCrashlyticsSymbolFileFlavorAmazonRelease

The message does not stop the build, but there is also no indication of whether there is a significant problem or not. I suspect the message is due to the NDK being part of a Gradle/Android subproject, and not the ":app" project itself.

#### Steps to reproduce:

`./gradlew app:uploadCrashlyticsSymbolFileBUILD_VARIANT`reproduces the "could not find NDK build tasks" message.

**Comment by kevinkokomani** [comment]
Thanks for letting us know about this. If you do notice that this causes any issues with your symbol file upload, your build, or the symbolication of your NDK crashes, please update this issue with your findings!

**Comment by kenmorse** [comment]
@kevinkokomani — thanks Kevin. I've got a simple reproducible case with a test app that includes a native Android library. When crashing in the native code the C++ code is not referenced in the stack trace information. What's the best way to proceed?

**Comment by kevinkokomani** [comment]
Thanks for working on that Ken - I think the best way forward is to [submit a case to Firebase support](https://firebase.google.com/support/troubleshooter/contact), linking this GitHub issue that you opened, and attaching the repro you've created. Submitting a case will ensure that if support can't help with the issue, it will get routed directly to the Crashlytics NDK team for review.

**Comment by kenmorse** [comment]
Case submitted with repo — thanks @kevinkokomani.

**Comment by kevinkokomani** [comment]
Thanks @kenmorse!

**Comment by MassimoMessore** [comment]
> 
> 
> Case submitted with repo — thanks @kevinkokomani.

Same problem here using the same Android Studio and Component version when I try to generate and upload symbols of native libraries (externally generated using autotools).

I successfully configured _unstrippedNativeLibsDir_ and _strippedNativeLibsDir_ paths and I can see in gradle logs the same warning about **Crashlytics could not find NDK build tasks on which to depend** even if the symbols are apparently generated and successfully uploaded via HTTP PUTs on server side.

Unfortunately I can't see the stack trace information on Crashlytics console when a native crash occurs (missing symbols).

Is there an issue tracker to track down this case?

Regards

**Comment by kevinkokomani** [comment]
This would be the issue tracker. Would you be comfortable with posting your relevant setup details here, in terms of how you're configuring NDK and how you're including your native libraries into your app? It would help us to reproduce this issue as well as confirm that you're running into the same issue as kenmorse. 

Thanks!

**Comment by MassimoMessore** [comment]
Hi @kevinkokomani, thanks for your quick reply.

My project tree is structured as follows:

<pre>
appProject
 |
 | -- androidLibraryModule
 |    | 
 |    | -- src
 |    | -- libs
 |    | -- obj
 |    | ...
 |    | -- build.gradle
 | 
 | -- app
 |    |
 |    | -- src
 |    | ...
 |    | -- build.gradle
 |
 | -- build.gradle 
</pre>

The app module depends on the androidLibraryModule which contains the native shared libraries (built using an external autotools-based script with NDK r17c standalone GCC toolchains) in the two folders:

- libs: stripped libraries
- obj: unstripped libraries

These two folders are structured as expected with the proper ABI folders (arm64-v8a, x86, etc.).

Following the [Fabric to Firebase Crashlytics migration guidelines for Android](https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android) I upgraded my build.gradle files as follows:

**androidLibraryModule/build.gradle**

<pre>
apply plugin: 'com.android.library'
[...]

repositories {
    google()
}

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation "com.google.firebase:firebase-crashlytics:17.1.1"
    implementation "com.google.firebase:firebase-analytics:17.4.4"
}
[...]

}
</pre>

**app/build.gradle**
<pre>
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"
    }
}

android {
    [...]
    
    buildTypes {
        debug {
            
        }
        release {
            minifyEnabled true
            [...]
            
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir "../androidLibraryModule/obj"
                strippedNativeLibsDir "../androidLibraryModule/libs"
            }
        }
    }
   [...]

    splits {
        abi {
            enable false
            reset()
            include 'x86', 'armeabi-v7a', 'arm64-v8a', 'x86_64'
            universalApk true
        }
    }
    packagingOptions {
        exclude 'lib/armeabi/libcrashlytics.so'
    }
}

dependencies {
    implementation project(':androidLibraryModule')
    implementation "com.google.firebase:firebase-crashlytics:17.1.1"
    implementation "com.google.firebase:firebase-analytics:17.4.4"
    implementation "com.google.firebase:firebase-crashlytics-ndk:17.1.1"
    [...]
}
</pre>

**appProject/build.gradle**
<pre>
buildscript {
    [...]

    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"
        classpath "com.google.gms:google-services:4.3.3"
        // Firebase Crashlytics Gradle plugin.
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }
    repositories {
        google()
        jcenter()
    }
}

[...]
</pre>

Hope that the given details will be useful to clarify this issue I didn't face before when using Fabric SDK.

Regards.
Massimo

**Comment by ivanuschak** [comment]
Hi @kevinkokomani, @MassimoMessore,

Just wanted to confirm I'm facing the same issue as Massimo.
I have similar Android Studio project and native libraries built separately from this project (also using NDK r17c), libraries are placed in two folders (stripped(release libs) and unstripped(debug libs)), which are pointed in the application build.gradle file (_unstrippedNativeLibsDir_ and _strippedNativeLibsDir_ properties).
I'm building the project in Debug mode, so the _uploadCrashlyticsSymbolFileDebug_ task is performed successfully (there is no warnings/errors) and also I checked that all the *.cSYM files are successfully uploaded to the firebase during this task execution.
I tried to use different 'firebase-crashlytics-ndk' versions (17.0.0-beta, 17.0.1 and 17.1.1), but eventually I always have _'missing symbols'_ in crash report stack trace in the firebase console.
I double checked the settings related to firebase and assured that everything set up in accordance with the crachlytics-ndk documentation.
Of course there may be a mistake in my configuration, but I double checked everything and currently for me it looks like a bug in firebase.

Best Regards,
Nikolay

**Comment by calvarez-ov** [comment]
I found this log in our latest release build, and it also happens that our native crashes are no longer deobfuscated.

**Comment by antonkovalyov351** [comment]
I had same issue with missing stacktrace and this what I received from support: 

>  ...try to add the following information to your AndroidManifest.xml file and see if this will resolve the issue:
> ```
> <application
>     android:extractNativeLibs="true"'
>     ...
> </application>
> ```
> Note that this may increase the size of the final binary at the end of the build by a little.  ...

I have tried it and it worked. At least for stack entries which belong to my own native code.
Hope this will help.

**Comment by calvarez-ov** [comment]
@antonkovalyov351 Thanks for this tip. But it doesn't resolve our issue of obfsucated stacktraces :( What version of Android Gradle Plugin did you use in the build that worked for you?

**Comment by antonkovalyov351** [comment]
> @antonkovalyov351 Thanks for this tip. But it doesn't resolve our issue of obfsucated stacktraces :( What version of Android Gradle Plugin did you use in the build that worked for you?

4.0.0

**Comment by calvarez-ov** [comment]
🤔 
I've tried:
* agp 4.0.1 + `extractNativeLibs` not specified
* agp 4.0.1 + `extractNativeLibs` true
* agp 4.0.0 + `extractNativeLibs` true
* agp 4.0.0 + `extractNativeLibs` false

None of them result in deobfuscated stacktraces

The first three all seem to have identical apk sizes.
The last one nearly doubles the size of the apk. from 21 Mb to 40 Mb.

Our project doesn't build the native code, but we do have access to the debug symbols for the native code. That's how deobfuscation worked up until our recent upgrade to agp 4.0.x: we copy the symbols to the configured folders as [documented](https://firebase.google.com/docs/crashlytics/ndk-reports#upload-external-dependencies) and run `./gradlew assembleRelease uploadCrashlyticsSymbolFileRelease`

**Comment by calvarez-ov** [comment]
Here's a sample project which reproduces the missing stack traces:

https://github.com/libon/CrashObfuscationTest

**Comment by calvarez-ov** [comment]
Opened #1978 for the missing ndk stacktrace info, as it appears unrelated to the original issue reported here.

**Comment by rodly** [comment]
Any word on this?

**Comment by mrichards** [comment]
Version 2.5.1 of the Crashlytics gradle plugin refactors how we manage task dependencies and the `unstrippedNativeLibsDir`, which should (hopefully) resolve any remaining issues folks have had with this. If you are using the new version and continue to have problems, please open a new GitHub issue and/or consider emailing our support team, which may be a faster path to getting hands-on help.

(Unfortunately there is a bug in how Crashlytics names its build subdirectory introduced in 2.5.1, which is causing build problems for some Windows customers. So you may want to wait until 2.5.2 releases within the next week or so.)  

The warning message about not finding the "tasks on which to depend" is safe to ignore, if you are using the unstripped native libs directory override and using pre-built native binaries. That warning was intended to indicate that the Crashlytics plugin could not determine which other Gradle task (if any) was responsible for building your native libs, so it wasn't possible to guarantee Crashlytics generated symbols for the binaries from this build or a previous build. Based on feedback, we've realized this message (especially as a warning) is confusing. We're going to revise the wording and when we show it in an upcoming release.
