### ISSUE TITLE
Disabling auto data collection

### ISSUE THREAD

**Issue by ikocijan** [firebase/firebase-android-sdk#1703]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: Analytics
  * Component version: 17.2.1

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Based on the [answer](https://github.com/firebase/quickstart-android/issues/370) from 3 months ago there is no way to disable auto data collection. However, when calling `setAnalyticsCollectionEnabled(false)` (https://firebase.google.com/docs/analytics/configure-data-collection?platform=android) default events and screen views are not sent. Is this a bug or desired behaviour because it contradicts the answer from firebase issue tracker.

**Comment by ashwinraghav** [comment]
Thanks for the question. Like you mentioned, `setAnalyticsCollectionEnabled` helps you toggle automatic events that are collected by analytics. I am not sure what part of the issue you point to contradicts this message. Let us know if you have more questions
