### ISSUE TITLE
FirebaseInstanceId.getInstance() token crash

### ISSUE THREAD

**Issue by BinaryPigStudio** [firebase/firebase-android-sdk#1716]
Step 1: Are you in the right place?
    Yes

Step 2: Describe your environment
    Android Studio version: 4.0
    Firebase Component: Messaging
    Component version: 20.2.1

Step 3: Describe the problem
    Trying to retrieve then token either by using
`FirebaseInstanceId.getInstance().getInstanceId().addOnCompleteListener`
or
`FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener`
 
crashes the app with the following error :

`Erro: java.lang.IllegalArgumentException: Please set a valid API key. A Firebase API key is required to communicate with Firebase server APIs: It authenticates your project with Google.Please refer to https://firebase.google.com/support/privacy/init-options. at com.google.android.gms.common.internal.Preconditions.checkArgument(Unknown Source:35) at com.google.firebase.iid.FirebaseInstanceId.zza(com.google.firebase:firebase-iid@@20.2.1:68) at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.1:2) at com.google.firebase.iid.FirebaseInstanceId.getInstance(com.google.firebase:firebase-iid@@20.2.1:1) at `

Downgrading the dependency to 20.1.0 and the core dependency to 17.2.2 fixes the issue

**Comment by ashwinraghav** [comment]
https://github.com/firebase/firebase-android-sdk/blob/93cdb04c32e8b11e7619b3caa6ea4bb2c47730c1/firebase-installations/src/main/java/com/google/firebase/installations/Utils.java#L27

This is the pattern we validate the API Key against.
The error seems to indicate that you may either not have a key or not be using one that's valid. This may not be the right venue to share your Key. I sense this may be a problem better suited for [support](https://firebase.google.com/support). Please reach us through those channels to get better help.
