### ISSUE TITLE
FirebaseMessagingService Issue when device is restarted

### ISSUE THREAD

**Issue by ramvdixit** [firebase/firebase-android-sdk#1721]
[READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in the code in this repository.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

For general technical questions, post a question on StackOverflow
with the firebase tag.
For general Firebase discussion, use the firebase-talk
google group.
For help troubleshooting your application that does not fall under one
of the above categories, reach out to the personalized
Firebase support channel.
[REQUIRED] Step 2: Describe your environment

Android Studio version: _____4.0
Firebase Component: Firestore_ (Database, Firestore, Storage, Functions, Firebase Cloud Messaging, etc)
Component version: _____21.4.3
[REQUIRED] Step 3: Describe the problem
When the device is restarted,  onMessageReceived() method of the Custom Service extending from FirebaseMessagingService fires but cannot proceed and ends with an exception as follows:
Message: Failed to get document because the client is offline.
Stacktrace: [com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(com.google.firebase:firebase-firestore@@21.4.3:330), com.google.firebase.firestore.DocumentReference$$Lambda$2.onEvent(Unknown Source:8), com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.4.3:504), com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent(Unknown Source:6), com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.4.3:42), com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6), com.google.firebase.firestore.util.Executors$$Lambda$1.execute(Unknown Source:0), com.google.firebase.firestore.core.AsyncEventListener.onEvent(com.google.firebase:firebase-firestore@@21.4.3:39), com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(com.google.firebase:firebase-firestore@@21.4.3:176), com.google.firebase.firestore.core.QueryListener.onOnlineStateChanged(com.google.firebase:firebase-firestore@@21.4.3:116), com.google.firebase.firestore.core.EventManager.handleOnlineStateChange(com.google.firebase:firebase-firestore@@21.4.3:178), com.google.firebase.firestore.core.SyncEngine.handleOnlineStateChange(com.google.firebase:firebase-firestore@@21.4.3:361), com.google.firebase.firestore.core.FirestoreClient.handleOnlineStateChange(com.google.firebase:firebase-firestore@@21.4.3:332), com.google.firebase.firestore.remote.RemoteStore$$Lambda$1.handleOnlineStateChange(Unknown Source:2), com.google.firebase.firestore.remote.OnlineStateTracker.setAndBroadcastState(com.google.firebase:firebase-firestore@@21.4.3:176), com.google.firebase.firestore.remote.OnlineStateTracker.lambda$handleWatchStreamStart$0(com.google.firebase:firebase-firestore@@21.4.3:116), com.google.firebase.firestore.remote.OnlineStateTracker$$Lambda$1.run(Unknown Source:2), com.google.firebase.firestore.util.AsyncQueue$DelayedTask.handleDelayElapsed(com.google.firebase:firebase-firestore@@21.4.3:139), com.google.firebase.firestore.util.AsyncQueue$DelayedTask.access$lambda$0(Unknown Source:0), com.google.firebase.firestore.util.AsyncQueue$DelayedTask$$Lambda$1.run(Unknown Source:2), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641), com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.4.3:229), java.lang.Thread.run(Thread.java:919)]

Steps to reproduce:

1. Restart device and wait for the device to come online
2. Firebase Cloud function sends a data payload when something is changed in the Firestore collection/document
3. onMessageReceived() method fires
4. Ends in an exception with the above Stacktrace and message 

Relevant Code:
```
public class MyFirebaseMessagingService extends FirebaseMessagingService {
    private static int SYNC_NOTIFICATION_ID = 121;
    private static String BROADCAST_ACTION = "com.app.muster.FMS_ROUTED_BROADCAST";
    private static String TAG = "FMS";
    private FirebaseFirestore firebaseFirestore;
    private FirebaseAuth firebaseAuth;

    public MyFirebaseMessagingService() {

    }

    @Override
    public void onCreate() {
        super.onCreate();
        firebaseAuth = FirebaseAuth.getInstance();
        firebaseFirestore = ((App) getApplicationContext()).getFirestoreDB();
    }

    @Override
    public void onNewToken(String s) {
        super.onNewToken(s);
        Log.d(TAG, "New FCM Token was generated: " + s);
        // Save token to server
    }

    @Override
    public void onMessageReceived(@NonNull RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);
 		
 		if (firebaseAuth.getCurrentUser() != null) {
        	Log.d(TAG, "Incoming payload");
        	processConversationGatewayInfo(remoteMessage.getData().get("dataContext"));
        }
    }

    private void processConversationGatewayInfo(String dataContext) {
    	firebaseFirestore.collection("books")
                .document(dataContext)
                .get()
                .addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {
                    @Override
                    public void onSuccess(DocumentSnapshot documentSnapshot) {
                    	// further processing...
                    }
                })
                .addOnFailureListener(e -> {
                	// This is where it jumps to...

                    Log.d(TAG, "Failure: " + e.getMessage());
                    Log.d(TAG, "Stacktrace: " + Arrays.toString(e.getStackTrace()));
                });
    }
}

**Comment by ashwinraghav** [comment]
Thanks for the report. I've not been able to repro your issue. Is there a chance your device is offline again when your callbacks are executed ? 

>> Firebase Cloud function sends a data payload when something is changed in the Firestore collection/document

I am not sure what your objective is, but notifying clients of changing values in a collection is best modelled with Firestore's [snapshot listener](https://firebase.google.com/docs/firestore/query-data/listen).

I sense this may be a problem better suited for [support](https://firebase.google.com/support) or [firebase-talk](https://groups.google.com/d/forum/firebase-talk). Please reach us through those channels to get better help.

**Comment by ramvdixit** [comment]
Hi,

Thank you for the response. I now notice that one of my test devices (One Plus 7T Pro) has this issue, while the others don't have the problem, with all of them working as they should. On the "One Plus" device, while the onMessageReceived() fires with the data payload, it fails to connect to Firestore to further download data based on the parameters received in the payload and results in a "client is offline" exception. I notice that it takes a while - about a min or two and everything works. I guess it could be a manufacturer centric problem. I will continue to study this and report back if I find anything.

Thanks again
