### ISSUE TITLE
FirebaseFirestoreException: Failed to get document from cache. (However, this document may exist on the server. Run again without setting source to CACHE to attempt to retrieve the document from the server.)

### ISSUE THREAD

**Issue by vlonjatg** [firebase/firebase-android-sdk#173]
Environment

  * Android Studio version: 3.2.1
  * Firebase Component: Firestore
  * Component version: 17.1.4

#### Steps to reproduce:

When fetching from `DocumentReference` with `Source.CACHE` and the object doesn't exist in cache, Firestore SDK throws a FirebaseFirestoreException. But would it make more sense to return a null object since object not existing in cache is a valid scenario?

**Comment by mikelehen** [comment]
To be clear, is it throwing an exception?  Or returning a failed Future?  I'd expect the latter.

**Comment by wilhuff** [comment]
This is a tricky part of the API to get right, but there are essentially three possible results that we wanted to convey:

  * Document is available
  * Document is known not to exist
  * Document is in an unknown state

It's the last of these that creates an exception (available via Task.getException). We'd like to preserve the ability to distinguish these last two cases for applications that need it.

A way to collapse the known-not-to-exist and unknown states is to wrap the resulting task in an adapter like the following:

```java
Task<DocumentSnapshot> hideUnavailable(Task<DocumentSnapshot> docTask) {
  return docTask.continueWith(Executors.DIRECT_EXECUTOR, task -> {
    if (task.isSuccessful()) {
      DocumentSnapshot snap = task.getResult();
      if (snap.exists()) {
        return snap;
      } else {
        return null;
      }
    }

    Exception exception = task.getException();
    if (exception instanceof FirebaseFirestoreException) {
      FirebaseFirestoreException firestoreException = (FirebaseFirestoreException)exception;
      if (firestoreException.getCode() == FirebaseFirestoreException.Code.UNAVAILABLE) {
        return null;
      }
    }

    throw exception;
  });
}
```

**Comment by wilhuff** [comment]
Oh and if this really is throwing rather than returning a failed Task in this case, please reopen. As it stands, this is intended behavior.
