### ISSUE TITLE
160167212: Is it possible to get initial link/source of Firebase Dynamic Link?

### ISSUE THREAD

**Issue by yeltayev22** [firebase/firebase-android-sdk#1731]
When I receive a dynamic link in my app I process the deep link inside, also I need to log analytics with the information such as the source of the dynamic link (campaign or etc.), user_id and phone_number?

Is it possible to get an initial link, source or campaign of the dynamic link?

I know that there is a default dynamic_link_app_open event, however, I cannot customize it by adding user_id and phone_number.

Or are there any other options?

**Comment by MeghaB** [comment]
Hi @yeltayev22 - We're actively monitoring StackOverflow (and also have a great set of community members who are happy to help). These types of questions are best [asked over here](https://stackoverflow.com/questions/tagged/firebase) (questions on usage/etc).
