### ISSUE TITLE
Make Crashlytics plugin compatible with Gradle configuration cache

### ISSUE THREAD

**Issue by CristianGM** [firebase/firebase-android-sdk#1750]
## What feature would you like to see?

The configuration cache is a feature that significantly improves build performance by caching the result of the configuration phase and reusing this for subsequent builds.

Implementing support for the configuration cache in this plugin would improve users experience.

See https://docs.gradle.org/nightly/userguide/configuration_cache.html

The configuration cache will be introduced in Gradle 6.6.
But this can already be tested using 6.6-milestone-2.

I tried running assemble with a Gradle 6.6-milestone-2, com.google.firebase:firebase-crashlytics-gradle:2.2.0 and the configuration cache enabled.
The first time it works because the configuration is not from the cache but when "Reusing configuration cache" it breaks the build with:
* What went wrong:
Execution failed for task ':app:injectCrashlyticsMappingFileIdDebug'.
> No such property: resourceFile for class: java.lang.Object

## How would you use it?

It would just make every build faster.

**Comment by ashwinraghav** [comment]
Thanks for the feature request. This is on the roadmap. We'll use this issue for comms going forward.

**Comment by CristianGM** [comment]
Gradle 6.6 released
Kotlin 1.4 in RC
AGP 4.1 RC 1

it seems tools are going to be GA soon, even if the feature will be still experimental, and this plugin seems to be the only blocker for use configuration-cache while developing (we can do hacks to not apply the plugin if we are not at CI, but it's the kind of thing that someday will break something and loosing the crashes from Production is too risky)

**Comment by CristianGM** [comment]
Sorry to bother you again, all the tooling to user Configuration Cache is ready in stable versions, and this issue is the only one preventing users to adopt Configuration Cache.
Is there any progress or ETA?

**Comment by CristianGM** [comment]
com.google.firebase:firebase-crashlytics-gradle:2.4.1
still has the same issue

**Comment by jgavazzisp** [comment]
Any update on this team?

**Comment by mrichards** [comment]
Hi folks, thanks for your patience on this. I have good news! The next release of the Crashlytics Gradle Plugin adds support for the Gradle configuration cache, for all non-NDK Crashlytics tasks. Look for v2.5.0 of our plugin to be released within the next week or so.

We're currently working on configuration cache support for the Crashlytics NDK tasks (specifically `generateCrashlyticsSymbolFile` and `uploadCrashlyticsSymbolFile`). That will ship in an upcoming release, so our NDK customers will need to wait a bit longer to enable the config cache. I don't have an ETA, but it will be soon!

**Comment by mrichards** [comment]
Crashlytics Gradle plugin [2.5.0](https://firebase.google.com/support/release-notes/android#crashlytics_gradle_plugin_v2-5-0) is now available, with configuration cache support for all non-NDK customers. 

Support for NDK tasks is still in development but will be out soon.

**Comment by ericntd** [comment]
[Still happening for me on 2.5.0](https://stackoverflow.com/questions/66213063/could-not-create-task-appinjectcrashlyticsmappingfileiddebug)
And people are saying downgrade to 2.2.0 works
Could you guys double confirm? 🙏

**Comment by mrichards** [comment]
@ericntd It seems there's a gap in our supported versions of Gradle that we missed during testing: You may see that error when using a Gradle version between 6.1 and 6.4.1 (inclusive). I can fix backwards compatibility in a forthcoming release. 

Upgrading to Gradle 6.5+ should fix the issue and will result in better performance of `--configuration-cache.` Newer versions of the Android Gradle plugin (such as 4.1.2 or the latest 4.2 beta) also have improved configuration cache support.

**Comment by mrichards** [comment]
That bug affecting Gradle 6.1-6.4.1 will be fixed in our upcoming Crashlytics Gradle plugin v2.5.1, which should be released in a week or two.

**Comment by Kedar-jirel** [comment]
Hey All ,  there if the problem while integration the package and running the project id debug mode 
Here is the crash logs 
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugResources'.
> Could not create task ':app:injectCrashlyticsMappingFileIdDebug'.
   > No signature of method: org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$ValueSourceProvider.forUseAtConfigurationTime() is applicable for argument types: () values: []
