### ISSUE TITLE
160610872: Dynamic link data not cleared after being read.

### ISSUE THREAD

**Issue by aidanas** [firebase/firebase-android-sdk#1755]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4
  * Firebase Component: Dynamic LInks
  * Component version: com.google.firebase:firebase-dynamic-links:19.1.0

### [REQUIRED] Step 3: Describe the problem
As stated in official documentation [HERE](https://firebase.google.com/docs/dynamic-links/android/receive)
> Calling `getDynamicLink()` retrieves the link and clears that data so it is only processed once by your app.

However when testing on a basic HelloWorld test app once users click on an deep link and the app is started (or brought to foreground if meanwhile was running in the background) then repeated calls to  `getDynamicLink()` always resolve to an app link.

#### Steps to reproduce:
* Have an app with deep link set up.
* Have a button with its click listener just calling upon `FirebaseDynamicLinks.getInstance().getDynamicLink(intent).addOnSuccessListener...` and print its results to log.
* To web browser and click on a deep link for the app.
* Click the button on the app multiple times
* Inspect the logs for the click
* Observe that each click resolved to an app link
* Expected behaviour: Only the first call to `.getDynamicLink()` to resolve to app link and subsequent ones should not.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
            @Override
            public void onClick(View view) {
                Log.d(TAG, "Click received" );
                Activity activity = getActivity();
                final Intent intent = activity.getIntent();
                FirebaseDynamicLinks.getInstance()
                        .getDynamicLink(intent) // This should clear link data after reading once!
                        .addOnSuccessListener(activity, new OnSuccessListener<PendingDynamicLinkData>() {
                            @Override
                            public void onSuccess(PendingDynamicLinkData pendingDynamicLinkData) {
                                // Get deep link from result (may be null if no link is found)
                                Uri deepLink = null;
                                Log.d(TAG, "pendingDynamicLinkData:" + pendingDynamicLinkData );

                                if (pendingDynamicLinkData != null) {
                                    deepLink = pendingDynamicLinkData.getLink();
                                    Log.d(TAG, "deepLink:" + deepLink );
                                }
                            }
                        })
                        .addOnFailureListener(activity, new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {
                                Log.w(TAG, "getDynamicLink:onFailure", e);
                            }
                        });
            }

```

**Comment by MeghaB** [comment]
Internally tracking via b/160610872

Hey @aidanas - to help us investigate this further - does the getDynamicLink still return the fdl once the app is relaunched? Trying to determine which of the following cases you're running into:

1. Click FDL -> Open App -> all calls the getDynamicLink returns the fdl -> close app -> re-open app -> getDynamicLink is empty
or 
2. Click FDL -> Open App -> all calls the getDynamicLink returns the fdl -> close app -> re-open app -> getDynamicLink returns the original fdl

**Comment by qrezet** [comment]
I believe I am experiencing the same issue.

This is what I am experiencing:

Click FDL -> Open App -> all calls the getDynamicLink returns the fdl -> close app -> re-open app -> getDynamicLink returns the original fdl

**Comment by artakka** [comment]
Having a similar issue

**Comment by rmazajev** [comment]
Same issue here. My case is like this:

Click on FDL -> App opens -> getDynamicLink gets the deeplink (expected result) -> minimize app -> Click on FDL -> App opens -> getDynamicLink gets the deeplink (expected result) -> minimize app -> resume the app from recents -> getDynamicLink gets the deeplink (**wrong result**) -> minimize app -> resume the app from recents -> getDynamicLink gets the deeplink (**wrong result**) 

So in my case I'm getDynamicLink  returns deeplink on resume, but only if I click on FDL second time. Second time app was in background.

**Comment by isamotiuc** [comment]
Having the same issue.
In documentation is said that:

> You must call getDynamicLink() in every activity that might be launched by the link, even though the link might be available from the intent using getIntent().getData(). Calling getDynamicLink() retrieves the link and clears that data so it is only processed once by your app.

But I receive this link each time, I have link handler in `onReasume` method

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
