### ISSUE TITLE
Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ordinaryman09** [firebase/firebase-android-sdk#1768]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4
  * Firebase Component: Crashlytics
  * Component version: 17.1.1

### [REQUIRED] Step 3: Describe the problem
I migrated from Fabric to Firebase crashlytics. Followed the steps from:
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

I am getting 
```Error is The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration```
for every other compile
#### Steps to reproduce:
1. Compile new build 1 -> This works, and every subsequent app open works fine.
2. Compile new build 2 -> This doesnt work, outputting the error crashlytics build id is missing. Every subsequent app open crashes
3. Compile new build 3 -> This works again.
4. Compile new build 4 -> This doesnt work again. 

I noticed the error happens every other install.

**Comment by ashwinraghav** [comment]
Thanks for reaching out. You are going to be better served at one of our [support channels](https://firebase.google.com/support), since this seems like an onboarding challenge and not a bug in the SDK itself

**Comment by ordinaryman09** [comment]
@ashwinraghav someone had the exact same issue on SO
https://stackoverflow.com/questions/62657080/firebase-crashlytics-crashed-in-runtime-after-updated-from-fabric-crashlytics

The solution was to set minifyEnabled to true. Why is this?
