### ISSUE TITLE
Crashlytics do not log crashes when multiprocess app

### ISSUE THREAD

**Issue by Duna** [firebase/firebase-android-sdk#1769]
The main issue is that I have the latest and greatest sdk crashlytics and 2 processes per app. 
All crashes from my content provider, which runs on separate process, are not logged by the crashlytics.

How do we enable the crashes logs on multiprocess applications? it seems is not working

**Comment by ashwinraghav** [comment]
Duplicate of https://github.com/firebase/firebase-android-sdk/issues/1545
Pls upvote instead.
