### ISSUE TITLE
Improve native crashes stack traces with a stripped library

### ISSUE THREAD

**Issue by guillaume-tgl** [firebase/firebase-android-sdk#1770]
## What feature would you like to see?

When a native crash happens in a stripped library, the report is useless in Firebase compared to what we get in the Google Play Console.
I think it's possible to display more information, even without a properly symbolicated library, and that would allow us to deobfuscate stack traces manually.

I don't have the same crashes in both consoles but these screenshots should show what I mean.

In the Google Play console:

![Screenshot 2020-07-09 at 15 29 58](https://user-images.githubusercontent.com/2244170/87046598-afe10a80-c1f9-11ea-8fb8-6bcd87509a71.png)

In the Firebase console:

![Screenshot 2020-07-09 at 15 29 45](https://user-images.githubusercontent.com/2244170/87046612-b3749180-c1f9-11ea-9996-cfe8189db2b0.png)

**Comment by ashwinraghav** [comment]
I'll leave this open as a feature request, although it does not really seem scoped strictly to the SDK.

**Comment by guillaume-tgl** [comment]
Should I report this problem somewhere else?

**Comment by kevinkokomani** [comment]
I think this is the best place for it. Appreciate the feedback!

**Comment by kevinkokomani** [comment]
Brought this back to the team for comment. This is a great idea and we're planning to look into it for the future, and we'll let you know here if there are any updates or changes to this.

**Comment by mrwillis21** [comment]
We're currently working on a number of initiatives to improve stack trace quality, and we'll keep this in mind. Thanks!
