### ISSUE TITLE
Why firebase messaging does not support VoIP

### ISSUE THREAD

**Issue by tbm98** [firebase/firebase-android-sdk#1782]
## What feature would you like to see?

VoIP, show calling screen by push notification
## How would you use it?

show calling screen by push notification

**Comment by ashwinraghav** [comment]
It is possible to implement what you are describing. You could send a 'X is calling you' notification that opens the app when the user taps on it in the system tray.

https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages

**Comment by tbm98** [comment]
But how I can show calling screen by push notification. Because it has long
sound and vibrate.
