### ISSUE TITLE
descarga-video-de

### ISSUE THREAD

**Issue by junior10875** [firebase/firebase-android-sdk#1784]
// I'm removing the description since it (possibly) includes secrets that should not be shared publicly.

**Comment by junior10875** [comment]
// ...

dependencies {
  // ...

  // Add the dependency for the Performance Monitoring library
  implementation 'com.google.firebase:firebase-perf:19.0.7'
}

**Comment by junior10875** [comment]
``

**Comment by rlazo** [comment]
Hi @junior10875 it's not clear from your report what's the issue, could you please clarify?

**Comment by junior10875** [comment]
hi i want to see the statistic in google analytics and firebase

**Comment by rlazo** [comment]
@junior10875 Did you follow the instructions in https://firebase.google.com/docs/analytics?
