### ISSUE TITLE
FirebaseRemoteConfig Error “No value of type 'String' exists for parameter key”

### ISSUE THREAD

**Issue by cubuspl42** [firebase/firebase-android-sdk#1786]
Firebase Performance Android SDK spams the logs, all the time, repeatedly, with messages like:

```
W/FirebaseRemoteConfig( 5294): No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
W/FirebaseRemoteConfig( 5294): No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
```

You don't need to do anything in particular to trigger this behavior. It starts happening when you start to depend on Firebase Performance.

It was first observed [over a year ago](https://stackoverflow.com/questions/55510223/firebaseremoteconfig-error-no-value-of-type-string-exists-for-parameter-key). I confirm that it's happening in the newest Flutter plugin `firebase_performance: 0.3.2` (from May 25, 2020). It's been [reported](https://stackoverflow.com/questions/55510223/firebaseremoteconfig-error-no-value-of-type-string-exists-for-parameter-key#comment109741490_56064715) to happen also in the newest Android (Java) `firebase-perf: 19.0.7` (from Apr, 2020).

**Comment by zijianjoy** [comment]
Hello @cubuspl42, please see the answer below:

## Solution

Firebase Performance released version `19.0.8` last week to address log spam issue. (see Release Note https://firebase.google.com/support/release-notes/android#2020-07-17) You can update your dependency `com.google.firebase:firebase-perf` to be the same or higher version to validate the fix.

## Explaination

To explain more about the reason of this issue: **Firebase Performance** utilizes **Firebase Remote Config** to sample down number of events being sent to Firebase, so it will call Firebase Remote Config API [getValue(String key)](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#getValue(java.lang.String)) every time it needs the sampling configuration value. 

However, Firebase Remote Config fetch happens every 12 hours. It is possible that **configuration value doesn't exist** by the time of development. In this case, Firebase Performance SDK will use **default value**. 

When the configuration value doesn't exist, **Firebase Remote Config** will generate this log for warning, which is the source of log spam for Firebase Performance users. (See [Source Code](https://github.com/firebase/firebase-android-sdk/blob/5301121df4727b357293b3b7de00555362f90170/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigGetParameterHandler.java#L412))

We have reduced **Firebase Performance**'s call frequency to **Firebase Remote Config** to avoid triggering this log. 

## Next Step

Would you like to validate if the log spam is eliminated after upgrading to the new version?

**Comment by cubuspl42** [comment]
Thank you for your answer!

> Firebase Performance utilizes Firebase Remote Config [...]

I'm not quite sure if I understood this part correctly. Does it mean that...
a) Firebase Performance Android SDK uses Remote Config _internally_, as an implementation detail, meaning that there's a separate private Firebase project owned by the Firebase team, and keys `sessions_max_length_minutes`/`sessions_feature_enabled` should be defined there
b) Firebase Performance Android SDK uses _my_ Firebase project and the mentioned key should be defined there?

**Comment by zijianjoy** [comment]
@cubuspl42 

a) As a high level understanding, it is correct that Firebase Performance has its own `scope` for storing those flags when utilizing Remote Config, therefore you won't see these flags when using Remote Config directly.

b) Firebase Performance doesn't use `your` Firebase project for Remote Config, and Firebase Performance is unaware of the Remote Config flags you defined.

This logging is useful to developers who use Remote Config directly, but agree that it is a different topic. I would love to share the source code with you about firebase-perf, but it is not open sourced yet. We are aiming towards open sourcing.

As a follow-up, would you like to confirm if you stop seeing those log spam? Thank you so much!

**Comment by cubuspl42** [comment]
As I stated in the original message, I'm using `firebase-perf` indirectly, through `firebase_performance` Flutter plugin. The newest version of the mentioned plugin depends on the older version of `firebase-perf`. I will let you know when that version is bumped.

**Comment by zijianjoy** [comment]
Thanks @cubuspl42, I have filed a bug to Flutter plugin for upgrading Firebase Performance dependency version to the latest: https://github.com/FirebaseExtended/flutterfire/issues/3008. Let's follow up in that issue, and feel free to reopen the current thread if the issue persists after Flutter plugin upgrade.
