### ISSUE TITLE
Support custom domains for production environments on Cloud Functions

### ISSUE THREAD

**Issue by rencsaridogan** [firebase/firebase-android-sdk#1797]
## What feature would you like to see?

We would like to see the proper support of custom domains on client side SDK(s). Currently, there is:

https://github.com/firebase/firebase-android-sdk/blob/3f4b32de9dc483b94c50a1181cb5406e0d4382f5/firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java#L222

available. However, this is documented for test purposes and Emulator usage. Therefore, it does not feel like the right way to move forward for such a need. 

We would like to see the same functionality to be able to configure our Cloud Functions to use a different domain for production environment.

## How would you use it?

We would route our [callable backend functions](https://firebase.google.com/docs/functions/callable) from a custom domain of ours. There are few reasons why we want this:

- We would like to route the traffic on a designated domain for our business.
- Provide isolation for possible temporary blockages that might happen on any carrier or due to any specific software (ex: ad blockers), on a more generic domain if not customized, simply because used by many other services.

**Comment by rencsaridogan** [comment]
Is there any thought given into this? Please do kindly let me know.

**Comment by rlazo** [comment]
Hi @rencsaridogan release [functions 19.2.0](https://firebase.google.com/support/release-notes/android#functions-client_v19-2-0) adds support for custom domains.
