### ISSUE TITLE
[BUG] Analytics duplicates events on RELEASE build.

### ISSUE THREAD

**Issue by vados60** [firebase/firebase-android-sdk#180]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.2.1
  * Firebase Component: Analytics
  * Component version: 16.0.4

### [REQUIRED] Step 3: Describe the problem

In application I use custom logs. 

On 'dev' environment everything works as expected, but on 'release' build those events get duplicated + after export to BigQuery I see that 'int' or 'long' values are inserted into 'string' column for second row.
Because of this issue all Firebase analytics data gets invalid and double-inflated.

#### Steps to reproduce:

Event recorded: Event{appId='...', name='Story_Page_View', params=Bundle[{storyID=226493992, versionID=96, firebase_event_origin(_o)=app, firebase_screen_class(_sc)= TabActivity, firebase_screen_id(_si)=-7287724136106664938, firebase_screen(_sn)= TabActivity, page=1, total=26}]}
Event recorded: Event{appId='...', name='Story_Page_View', params=Bundle[{storyID=226493992, versionID=96, firebase_event_origin(_o)=fab, firebase_screen_class(_sc)= TabActivity, firebase_screen_id(_si)=-7287724136106664938, firebase_screen(_sn)= TabActivity, page=1, total=26}]}

#### Relevant Code:

```
@Override
  public void storyPageView(int storyId, int page, int totalPagesCount) {
    Bundle bundle = = new Bundle();
    bundle.putInt("versionID", BuildConfig.VERSION_CODE);
    bundle.putInt("storyID",  storyId);
    bundle.putInt("page",  page);
    bundle.putInt("total",  totalPagesCount);
    firebase.logEvent("Story_Page_View", bundle);
  }
```

Google or StackOverflow can't answer this question.
Also, Fabric logs event correctly. without duplications

**Comment by vados60** [comment]
![image](https://user-images.githubusercontent.com/3134695/50437217-856a7d80-08f1-11e9-87fc-e93c3be93ef4.png)
This happens regardles data types inside payload.
Happens only with custom events.
All native ones are fired as expected

**Comment by RamyFRadwan** [comment]
I have an issue to with this regarding events reported from fragments they get reported twice in debugview

**Comment by aguatno** [comment]
@vados60 are you still having this issue? Per checking, It seems the custom events is no longer duplicated:
![Screenshot from 2019-10-24 23-00-40](https://user-images.githubusercontent.com/56451054/67498656-658f1c00-f6b2-11e9-932c-99413910876b.png)

You may also consider upgrading your Firebase Analytics SDK to the latest version (17.2.0).

Thanks!
