### ISSUE TITLE
Change Sound Path

### ISSUE THREAD

**Issue by gonzalovinas** [firebase/firebase-android-sdk#181]
I'm trying to play an internal phone notification sound. As documentation says Default search path is Library/Sound or a raw/res file.

Thanks in advance.

**Comment by gonzalovinas** [comment]
With Android O or above it is now possible to let the user change this behaviour, although its not an APP feature per-se.

Previous to Android O. I would need to show some screen with the list of the users' internal sounds store and then send a push notification with that (per phone) path to catch that sound, possibly not being in Library/Sound.

**Comment by samtstern** [comment]
@gonzalovinas sorry I am still a bit confused how this relates to Firebase.  Could you provide a code sample that's not working for you?
