### ISSUE TITLE
PersistedInstallation file content is not encrypted

### ISSUE THREAD

**Issue by alaksmana** [firebase/firebase-android-sdk#1822]
When we open / rooted our Android app, we found below:

File with name PersistedInstallation.W0RFRkFVTFRd+MTo3MTM2MzQ5xxxxNjphbmRyb2lkOmU4MGFhNjJhN2IxMDc2MXXXZTQyMGQ.json
is found with content:

{"Fid":"focIxxxRRv2uigGucw-XXX","Status":3,"AuthToken":"eyJhbGxxxiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaWQiOiJmb2NJUDNiUlJ2MnVxxxd1Y3ctVEJXIiwicHJvamVjdE51bWJlciIxxxEzNjM0OTU0MTYsImV4cCI6MTU5NjM1NzMwMiwiYXBwSWQiOiIxOjcxMzYzNDk1NDE2OmFuZHJvaWQ6ZTgwYWE2MmE3YjEwNzYzMmJlNDIwZCJ9.AB2LPV8wRQIgb4KZUgd7lYxYFTUfgl1SgYvgngoK6bV1L65Y0cj8jSUCIQCl1q0LgjXSLcN4FRCOgmPjMJ5Rm66W0__pJxxxdfwLNA","RefreshToken":"2_sNwR8zSrTOSqUR9zudJxxxxcScfEd6VJYoznomMTxxxqmwXG9qxxxvN-6VBlJCAJ","TokenCreationEpochInSecs":1595752501,"ExpiresInSecs":604800}

Is this information encrypted? Will it compromise our Firebase account?

**Comment by ashwinraghav** [comment]
We don't generally encrypt these tokens on the client since the marginal costs outweigh the benefits. These tokens are per client and do not put you at risk of having your firebase account being compromised.
Thank you for checking!

**Comment by AlexZvonik** [comment]
@ashwinraghav If someone get their hands on these tokens they can access the firebase account, no?
What is accessible with this token?
Also, do you know for how long these tokens are valid for? Especially the refresh token..

**Comment by ashwinraghav** [comment]
Some firebase services are accessible with these tokens. Firebase accounts of the  developer is not. @ankitaj224 could you share the lifetime of the refresh token pls ?

**Comment by asaf-eden** [comment]
@ashwinraghav Can you please elaborate on which services exactly are accessible with these tokens?
Seems like a malicious attacker can gain these tokens fairly easy (via physical access or malware installed), so the question is what can be compromised? 
Thanks.

**Comment by ashwinraghav** [comment]
At the moment, it would be possible to use the installation token to access some firebase services, which have no inherent notion of user authentication. **I am intentionally not providing a list to keep things obscure for the sake of safety**. If you are worried about them accessing your Firebase account, there is no risk. For Baas products that have user auth configured, no risks are posed. The compromise is scoped to services that have the inherent risks that application authentication poses.

Attack vectors involving gaining physical access to the device are scoped to the instance they have gained access to, and cannot affect other users of the app. 
As far as malware is concerned, we could consider encrypting these using hardware backed keystores, but that really benefits only API 24 or higher, and this use case does not really demand that.

If you have further questions, please reach out support channels where security issues are better dealt with.

**Comment by ankitaj224** [comment]
@ashwinraghav The refresh token is valid for the lifetime of a Firebase Installation. Auth toke is valid for 7 days. We have an internal effort tracked in b/161510321 to evaluate alternatives on ways to secure refresh tokens.
