### ISSUE TITLE
Application not opening after clicking the notification with click_action

### ISSUE THREAD

**Issue by akumar-atheer** [firebase/firebase-android-sdk#1839]
### Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: FCM Push Notificaitons
  * Component version: 20.2.3

### Describe the problem

Application does not open, when clicking a notificaiton with click_action. I keep getting error  
`E/FirebaseMessaging: Notification pending intent canceled`

#### Steps to reproduce:

What happened? How can we make the problem occur?
I am using cURL to send the push notification and I am receiving the notification on target device.
cURL:
`curl -X POST --header "Authorization: key=<AUTHORIZATION_TOKEN>" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"to\":\"/topics/weather\",\"notification\":{\"body\":\"Yellow1\",\"click_action\":\".EntryChoiceActivity\"},\"priority\":10}"`

Clicking the above notification does not open the Android app. If I remove `click_action` in the notification, the app opens up after clicking the notification.

**Comment by catman-19** [comment]
Hi @akumar-atheer, apologies for the delay here. 

Per doc (https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support):

> click_action - The action associated with a user click on the notification. If specified, an activity with a matching intent filter is launched when a user clicks on the notification.


Please make sure that the activity that you want to open has an intent filter with the name set to that action. See this similar discussion for reference https://stackoverflow.com/a/41196132.
