### ISSUE TITLE
Possibility to reset Firebase Functions instance after useFunctionsEmulator was used

### ISSUE THREAD

**Issue by audkar** [firebase/firebase-android-sdk#1846]
## What feature would you like to see?

Revert `useFunctionsEmulator(origin)` call to use production url.

## How would you use it?

After using `useFunctionsEmulator(origin)` there is no other way to reset Functions instance but only by killing application. This is very inconvenient.

**Comment by ashwinraghav** [comment]
Thanks for the feature request. I see the value of being able to do that, but that could come at the cost of some confusion when combined with the API that functions currently has. Given the asynchronous nature of the Tasks framework, changing out what amounts to a 'global' setting while a `call` is in progress may yield an unintuitive API.

Will it work for your use case to create a new instance of `FirebaseFunctions.getInstance(...)` instead ?

**Comment by audkar** [comment]
> Will it work for your use case to create a new instance of FirebaseFunctions.getInstance(...) instead ?

Yes. That would be a preferred way!

**Comment by ashwinraghav** [comment]
Sweet. So safe to close for now since that provides a workaround ?

**Comment by audkar** [comment]
Umm. No. I don't think there is a way to get a new Functions instance https://github.com/firebase/firebase-android-sdk/blob/ed4d371cd16f78c376c6c1433d99773bc165f15a/firebase-functions/src/main/java/com/google/firebase/functions/FunctionsMultiResourceComponent.java#L45

**Comment by samtstern** [comment]
@audkar you can create a new Functions instance by creating a new `FirebaseApp` and then calling `FirebaseFunctions.getInstance(app)`.  

If your app needs to communicate with both the emulators and production in a single run (which is rare) then I suggest you initialize two FirebaseApp instances from the start and then always use one for production and one for the emulators.

Going to close this as we won't be adding a "reset" method to `FirebaseFunctions` however I am curious to hear more about why your app needs to switch between emulators and production at runtime.
