### ISSUE TITLE
166508275: Fatal Exception: ArrayIndexOutOfBoundsException in-app messaging

### ISSUE THREAD

**Issue by jchau207** [firebase/firebase-android-sdk#1848]
### Environement

  * Android Studio version: 4.0.1
  * Firebase Component: In-AppMessaging (Database, Firestore, Storage, Functions, etc)
  * Component version:
 
compileSdkVersion 29

```
'com.google.firebase:firebase-core:17.4.4' 
'com.google.firebase:firebase-messaging:20.1.5' 
'com.google.firebase:firebase-inappmessaging-display:19.1.0'
'com.google.firebase:firebase-analytics-ktx:17.4.4'

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.11.4'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.30.1'
        }
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option 'lite'
                }
            }

            task.plugins {
                grpc {
                    // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
}
```

### Exception 

Following Fatal Exception occurs shortly after displaying in-app message:

```
FATAL EXCEPTION: main
    java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
        at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
        at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
        at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
        at com.google.firebase.inappmessaging.CampaignAnalytics$Builder.setClientApp(CampaignAnalytics.java:1049)
        at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createCampaignAnalyticsBuilder(MetricsLoggerClient.java:191)
        at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createEventEntry(MetricsLoggerClient.java:168)
        at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.lambda$logImpression$0(MetricsLoggerClient.java:106)
        at com.google.firebase.inappmessaging.internal.MetricsLoggerClient$$Lambda$1.onSuccess(Unknown Source:6)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.0.2:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.0.2:6)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
```
I/FIAM.Headless: Starting InAppMessaging runtime with Installation ID e9kZTNGCQ4qvUu4zVEeBAL
I/FIAM.Headless: went foreground
I/FIAM.Display: Binding to activity: com.bitcoin.mwallet.OnBoardingActivity
I/FIAM.Headless: Setting display event component
I/FIAM.Headless: Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
I/FIAM.Headless: Fetching campaigns from service.
I/FIAM.Headless: Successfully fetched 1 messages from backend
I/FIAM.Headless: Already impressed campaign Android Test 2 ? : false
I/FIAM.Headless: Already impressed campaign Android Test 2 ? : false
I/FIAM.Display: Impression timer onFinish for: 11550505989228724224
```

#### Steps to reproduce:
1. Created a campaign on Firebase console with scheduler to trigger on specific event
2. Have your activity trigger event onCreate

#### Relevant Code:

```
FirebaseInAppMessaging.getInstance().triggerEvent("main_activity_ready")
```

**Comment by ashwinraghav** [comment]
Thanks for the report. Do you see these with older versions of inappmessaging too ?
`19.0.[6|7]`
Also, I assumed you have the proto plugins applied since you use the grpc stack on your app?

**Comment by jchau207** [comment]
@ashwinraghav using older version gives me duplicate class errors:

```
Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-javalite-3.12.0.jar (com.google.protobuf:protobuf-javalite:3.12.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules protobuf-javalite-3.12.0.jar (com.google.protobuf:protobuf-javalite:3.12.0) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)

...
```

and yes, we are using grpc stack in our app.

**Comment by JasonAHeron** [comment]
Hmmm this error seems to be coming from the proto message builder, let me take a look

**Comment by jchau207** [comment]
Any updates on this issue or a work around? 

If I choose to use an older version, whats the best way to resolve the duplicate conflicts?

**Comment by elivity** [comment]
Unfortunately, I have the exact same problem as @jchau207, 19.1.0 giving me the ArrayIndexOutOfBoundsException, and versions 19.0.6 and 19.0.7 giving me Duplicate Class Errors.

compileSdkVersion 28

Relevant imports:
implementation 'com.google.firebase:firebase-crashlytics:17.2.1'
implementation "com.google.firebase:firebase-messaging:20.2.4"
implementation "com.google.firebase:firebase-analytics:17.5.0"
implementation 'com.google.firebase:firebase-inappmessaging-display:19.1.0'
implementation 'com.google.firebase:firebase-perf:19.0.8'

implementation "com.google.protobuf:protobuf-javalite:3.13.0"

Any Ideas? Thanks in advance :)

**Comment by hiddow** [comment]
same issue 
implementation 'com.google.firebase:firebase-inappmessaging-display:19.1.1'
implementation group: 'com.google.api.grpc', name: 'grpc-google-cloud-speech-v1', version: '1.24.0'
implementation 'io.grpc:grpc-okhttp:1.28.0'

**Comment by hwangjaewoo** [comment]
I have same issue too.
all of libraries are up-to-date.
Who anyone explain this issue?? How to avoid this??

**Comment by maduwatas** [comment]
same issue. My configuration:

 implementation files('libs/polar-ble-sdk.aar')
    implementation files('libs/polar-protobuf-release.aar')
    implementation 'com.google.protobuf:protobuf-java:3.13.0'
...
 implementation 'com.google.firebase:firebase-analytics:18.0.0'
    implementation('com.google.firebase:firebase-inappmessaging-display:19.1.2') {
        exclude group: 'com.google.protobuf'
        exclude module: 'protolite-well-known-types'

    }

**Comment by animesh-sharama** [comment]
Same issue, is there any older version that we can use?

**Comment by maduwatas** [comment]
> Same issue, is there any older version that we can use?

My configuration that works:

implementation files('libs/polar-ble-sdk.aar')
    implementation files('libs/polar-protobuf-release.aar')
    implementation 'com.google.protobuf:protobuf-java:3.8.0'
    implementation 'io.reactivex.rxjava3:rxjava:3.0.0'
    implementation group: 'commons-io', name: 'commons-io', version: '2.4'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    //Add the Firebase Auth SDK.
    implementation 'com.firebaseui:firebase-ui-auth:6.2.0'

    //Add the Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:17.2.1'

    // Recommended: Add the Google Analytics SDK.
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    implementation('com.google.firebase:firebase-inappmessaging-display:19.1.2') {
        exclude group: 'com.google.protobuf'
        exclude module: 'protolite-well-known-types'

    }

}
hope it helps

**Comment by SaqibJDev** [comment]
I faced the same issue using firebase bom. In my case one of my dependency was using `com.google.protobuf:protobuf-javalite:3.13.0` whereas firebase pref uses `com.google.protobuf:protobuf-javalite:3.11.0`. Excluding the 3.13.0 fixed the issue for firebase. But I think firebase should update to protobuf-javalite:3.13.0

**Comment by rlazo** [comment]
Hi! On Dec 16th we released a new versions of the SDKs pointing to the latest released version of protobuf-javalite at the time.  See the [release notes](https://firebase.google.com/support/release-notes/android#2020-12-16)
