### ISSUE TITLE
in_app_purchase is counted twice sometimes.

### ISSUE THREAD

**Issue by nes123** [firebase/firebase-android-sdk#1854]
This is a problem with firebase analytics. The event will show twice and is not aligned with the number that I see on the google play console.

**Comment by ashwinraghav** [comment]
Thanks for the report.
How frequently does this happen ?
The nature of analytics is that a lot of operations are guaranteed to be at least once. Unless you see this happening at scale, I would say this works as intended.

**Comment by ashwinraghav** [comment]
If you see this issue at scale, this may be a problem better suited for [support](https://firebase.google.com/support) or [firebase-talk](https://groups.google.com/d/forum/firebase-talk). Please reach us through those channels to get better help.

**Comment by nes123** [comment]
it is a big issue...in the last year, it gives me a 150% more event on a daily basis.
