### ISSUE TITLE
App status: Rejected - Your app has been rejected and wasn't published due to a policy violation.

### ISSUE THREAD

**Issue by MS893** [firebase/firebase-android-sdk#1867]
### [READ] Step 1: Are you in the right place?

YES

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component:
    // firebase
    implementation 'com.google.firebase:firebase-crash:16.2.1'
    implementation 'com.google.firebase:firebase-core:17.4.4'
    implementation('com.crashlytics.sdk.android:crashlytics:2.10.1') {
        transitive = true
    }
  * Component version: _____

### [REQUIRED] Step 3:

I have done a new version of my app, I've just changed one sentence in a text message.

When I tried to publish my app, I received an email with:

App status: RejectedYour app has been rejected and wasn't published due to a policy violation. If you submitted an update, the previous version of your app is still available on Google Play. | App status: Rejected | Your app has been rejected and wasn't published due to a policy violation. If you submitted an update, the previous version of your app is still available on Google Play.
-- | -- | --
App status: Rejected
Your app has been rejected and wasn't published due to a policy violation. If you submitted an update, the previous version of your app is still available on Google Play.

There is NO other detail, NO explaination, I searched long time to find this in the Console:

We have detected... Version : 84, SDK : AdMob

And it ask me to change my app in relation with ads.

MY APP DOESN'T HAVE ADS !!!!!!!

I will not say it has because it's NOT............

PLEASE IMPROVE YOUR ERROR MESSAGES, GIVE MORE DETAILS, AND ADD AN EXPLAINATION HOW TO SOLVE THE PROBLEM

MAKE THE CONSOLE MORE READABLE, EASIER TO FIND WHAT MAKES THE APP REJECTED !!!!!

PLEASE !!!!!!!!!!!!!!!!

#### Steps to reproduce:

YES it is 

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by dimitribocquet** [comment]
I have the same issue, I have no detailed message about the problem, and how to solve this.

Please make it more readable for us.

**Comment by carlonzo** [comment]
Hi, how this is related to Firebase SDK?
I guess when you mentioned "console" you are referring to Google Play Console?

**Comment by MS893** [comment]
Google said "if you need help about violation problem, go to Firebase SDK gitHub" (something like that !)

And Yes the Google Play Console ask me to say my app contains ads (it's NOT)

But the violation seems to be about launching other app from my app... My app, for a long time, can launch Twitter directly, and that's all ! And in my last update, I just changed a text message.

So I really don't know and don't understand what is the problem !

So can Google be more CLEARED:
- WHERE to find help ?
- WHAT is exactly the problem ?
- HOW to correct my app to be OK with the rules ?

THANK YOU I'm lost

**Comment by MS893** [comment]
In fact, the message to find help here was in relation with the adMob SDK (how to remove it from app). But as I said, I don't know what is the problem (adMob or launching app)...

AdMob is mentionned in Google Play Console (Version : 84, SDK : AdMob), I don't know how to solve that (even if it's not my violation problem). My app doens't use ads.

**Comment by carlonzo** [comment]
Try to run in your terminal `./gradlew app:dependencies` and check if you have admob there

**Comment by ashwinraghav** [comment]
Thanks for reaching out. I am a bit flummoxed by why this is Firebase related. 
If this is truly Firebase related, this may be a problem better suited for [support](https://firebase.google.com/support) or [firebase-talk](https://groups.google.com/d/forum/firebase-talk). Please reach us through those channels to get better help. 

> Google said "if you need help about violation problem, go to Firebase SDK gitHub" (something like that !)
Can you be more specific about the error message and where you saw it when you reach us via the support channels.

**Comment by MS893** [comment]
@carlonzo 
Thanks for your answer, the command return this error message:
FAILURE: Build failed with an exception.
* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

@ashwinraghav 
Thanks also, in fact I have 2 problems.
First my app update is rejected (for the story, I received an email that said "We’ve accepted your appeal..." and resubmit your app, but I can't because it's still rejected), this is a violation rules problem and there is no relation with Firebase, that's right. 
Second problem is related with AdMob SDK, I don't use AdMob in my app, I have NO ADS in  my app, so it is not normal.
Anyway, I will use the 2 links you siggested to find more help.

**Comment by carlonzo** [comment]
@MS893 I'm sorry you have an issue there. to explain what I wanted to do with that command was: as you believe there is no admob included in your application, running `./gradlew app:dependencies` it will print all the dependencies used by the app so you could investigate where admob is coming from and if its really included in your code.
about the problem you mentioned, I would suggest you to google the error. I gave a quick look and should be a gradle issue. make sure you updated to the latest gradle wrapper 6.5.1 and that you run a `./gradlew wrapper` to produce the latest gradle wrapper binaries. good luck!

**Comment by MS893** [comment]
Thank you Carlo, I will try 👍
