### ISSUE TITLE
Firebase Remote Config NullPointerException on Initialization

### ISSUE THREAD

**Issue by arora-vishal** [firebase/firebase-android-sdk#1868]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: Remote Config
  * Component version: 19.0.3

Devices - 97% Samsung, 2% Xiaomi, <1% One plus 

### [REQUIRED] Step 3: Describe the problem
Getting the following crash on some devices in production.

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'r1.j.c.n.f r1.j.c.n.k.a(java.lang.String)' on a null object reference
       at com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault(RemoteConfigComponent.java:140)
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:83)
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:77)
       at com.ixigo.lib.components.framework.RemoteConfig.<init>(RemoteConfig.java:65)
       at com.ixigo.lib.components.framework.RemoteConfig.init(RemoteConfig.java:43)
       at com.ixigo.IxigoApplication.onCreate(IxigoApplication.java:99)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6041)
       at android.app.ActivityThread.access$1700(ActivityThread.java:211)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1766)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6946)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

#### Steps to reproduce:

I was unable to reproduce this issue.

#### Relevant Code:

Initializing firebase remote config as - 

        ```
       if (FirebaseApp.getApps(context).isEmpty()) {  
            FirebaseApp.initializeApp(context, FirebaseOptions.fromResource(context));
        } 
        FirebaseRemoteConfigSettings.Builder builder = new FirebaseRemoteConfigSettings.Builder();
        if (BuildConfig.DEBUG) {
            builder.setMinimumFetchIntervalInSeconds(0);
        } else {
            //Setting minimum fetch seconds to be a small number(>0) to avoid accidental multiple fetches during same app start
            builder.setMinimumFetchIntervalInSeconds(3);
        }
        FirebaseRemoteConfigSettings configSettings = builder.build();

        FirebaseRemoteConfig firebaseRemoteConfig = FirebaseRemoteConfig.getInstance();`


Initial Investigation pointed to line no 140 in this file - 

[RemoteConfigComponent](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java)

`  FirebaseRemoteConfig getDefault() {                                                                                                                                                   
    return get(DEFAULT_NAMESPACE); // line no. 140 ... throws NPE at this line.
  }     `

`getDefault()` is an instance method on `RemoteConfigComponent` and it further invokes another instance method `get(DEFAULT_NAMESPACE)`. get() method invocation is resulting in NPE. What I fail to understand is how can RemoteConfigComponent  instance is deferenced between invocation of getDefault() and get(DEFAULT_NAMESPACE) method resulting in NPE.

**Comment by danasilver** [comment]
This might be happening if the FirebaseApp isn't initialized correctly or if there's an issue with dependencies clashing. It might be easier to initialize automatically as described here: https://firebase.google.com/docs/android/setup

If that doesn't fix the issue, can you share your dependencies either from your Gradle file or by running `./gradlew :app:dependencies`?

As an aside, we'd recommend using a minimum fetch interval greater than 3s in production (the default is 12h) to avoid rate limiting issues.

**Comment by ashwinraghav** [comment]
@vkryachko could be related to the class of issues you mentioned about Firebase App not being initialized on some devices. Feel free to close as duplicate if you are triaging ensewhere.

**Comment by arora-vishal** [comment]
@danasilver FirebaseApp is initialized automatically as suggested on setup page. The following code block is added as a fix for this error [Firebase App Different Process initialization error]( https://stackoverflow.com/questions/37376107/new-firebase-initialize-crashes)

`if (FirebaseApp.getApps(context).isEmpty()) {  
        FirebaseApp.initializeApp(context, FirebaseOptions.fromResource(context));
    } `

The problem is that I am unable to reproduce this issue locally. But I am getting significant number of crashes on production. 

I have attached the dependencies list in this file -
[Dependencies.txt](https://github.com/firebase/firebase-android-sdk/files/5055195/Dependencies.txt)

@ashwinraghav @vkryachko I have already checked out other issues raised with similar or related exceptions. But all of those issues were closed due to inactivity without any resolution. That is why I have created a separate issue. 

@danasilver Can you help me understand the reason for this crash? How can `this` reference all of a sudden be deferenced after invocation of `getDefault` but before invocation of `get(DEFAULT_NAMESPACE)` since both are instance methods of the same class? Is the stacktrace misleading?

**Comment by vkryachko** [comment]
@arora-vishal The stacktrace indeed looks suspicious, i.e. why is most of it deobfuscated with the exception of `r1.j.c.n.f r1.j.c.n.k.a(java.lang.String)` - what does it correspond to?

**Comment by arora-vishal** [comment]
@vkryachko Attaching a screenshot of the stacktrace from Firebase Crashlytics Dashboard -
<img width="1146" alt="Screenshot 2020-08-11 at 10 42 18 PM" src="https://user-images.githubusercontent.com/27269376/89927467-faeca400-dc23-11ea-977c-6cf06749218a.png">

**Comment by arora-vishal** [comment]
@vkryachko Do you need any other information to help analyze the issue?

**Comment by vkryachko** [comment]
@arora-vishal Is your app obfuscated? i.e. has `minifyEnabled = true`?
If so, what does `r1.j.c.n.f r1.j.c.n.k.a(java.lang.String)` correspond to in your mapping file?

**Comment by arora-vishal** [comment]
@vkryachko Yes app is obfuscated and below is the mapping - 
`com.google.firebase.remoteconfig.FirebaseRemoteConfig -> r1.j.c.n.f:`
```
com.google.firebase.remoteconfig.RemoteConfigComponent -> r1.j.c.n.k:
    java.util.Map frcNamespaceInstances -> a
    java.util.Random DEFAULT_RANDOM -> k
    com.google.firebase.abt.FirebaseABTesting firebaseAbt -> f
    android.content.Context context -> b
    com.google.firebase.FirebaseApp firebaseApp -> d
    java.lang.String appId -> h
    java.util.Map customHeaders -> i
    java.util.concurrent.ExecutorService executorService -> c
    com.google.firebase.iid.FirebaseInstanceId firebaseInstanceId -> e
    com.google.android.gms.common.util.Clock DEFAULT_CLOCK -> j
    com.google.firebase.analytics.connector.AnalyticsConnector analyticsConnector -> g
    1:2:void <clinit>():70:71 -> <clinit>
    1:1:void 

```

**Comment by vkryachko** [comment]
Thanks, I can't see the `r1.j.c.n.k.a(java.land.String)` *method*, but I assume it's, as you mentioned above, a call to `get(DEFAULT_NAMESPACE)`. If that's the case I don't see how `this` could be null as you rightly noticed.

I would need repro steps to make further progress on this issue. Also, how widespread is this crash for you?

**Comment by arora-vishal** [comment]
@vkryachko That is the issue. I am unable to reproduce this on any device locally. 
This is the highest-grossing crash on my app. Attaching a screenshot of the last 90 days account of this crash - 
<img width="1179" alt="Screenshot 2020-08-15 at 12 52 15 AM" src="https://user-images.githubusercontent.com/27269376/90285498-ac444180-de91-11ea-9204-0f8787a7bf90.png">

**Comment by arora-vishal** [comment]
@vkryachko Can you suggest any workaround meanwhile?

**Comment by vkryachko** [comment]
@arora-vishal not really, as I don't understand what's going on without repro steps, sorry
