### ISSUE TITLE
Another way to log exceptions is required.

### ISSUE THREAD

**Issue by sandinexciting** [firebase/firebase-android-sdk#1875]
## What feature would you like to see?
In place of recordException(exception) in crashlytics I need the same functionality as recordExceptionModel on iOS.

iOS crashlytics sdk use likely
(void)recordExceptionModel:(FIRExceptionModel *)exceptionModel

or directly use recordException(TrimmedThrowableData data); 

Describe the feature you would like to add, ideally proposing a specific API.

## How would you use it?
recordException(TrimmedThrowableData data);
Tell us how you'd use this feature in your app.

**Comment by kevinkokomani** [comment]
Thanks for leaving this feature request! Could you add some more detail as to what this would give you that would be useful over what you're currently able to get out of recordException?
