### ISSUE TITLE
Firebase SDK doesn`t receive data message when app is killed for first time sending notificiation

### ISSUE THREAD

**Issue by mohammaddvi** [firebase/firebase-android-sdk#1889]
### [READ] Step 1: Are you in the right place?

I didn't found this problem in SOF

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: Cloud Messaging(Database, Firestore, Storage, Functions, etc)
  * Component version: 20.2.4

### [REQUIRED] Step 3: Describe the problem
Firebase SDK wont receive the message and onMessageReceive wont call when open application for the first time and kill it and send a notification with data message. After one restart application everything is going well.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
I test with the sample Firebase SDK code in https://github.com/firebase/quickstart-android
```

**Comment by ashwinraghav** [comment]
Thanks for the report.
Can you outline the set of repro steps. It is unclear whether the message is not received after you kill the application or even before. Can you link us to the SO posts you are referring to?

**Comment by mohammaddvi** [comment]
I have tested this scenario on sample Firebase Messaging:
1. Come to the app for the first time and close application.
2. send a notification with Firebase Messaging API(legacy one)(with data message).
3. you won`t receive that and onMessageReceive won`t call(I think the service has been killed).
4. after you reopen application everything is going to be fine even kill the app.

**Comment by mohammaddvi** [comment]
This issue is open still, did you found this problem or not?

**Comment by catman-19** [comment]
Hi @mohammaddvi, sorry for the delay here. Could you please clarify how the app was "killed" ? Specifically, was the app swiped from your Recents screen or was it force-stopped from your app settings?

The Android framework advises that apps that have been stopped (i.e. killed/force-stopped from Settings) should not be started without explicit user interaction. FCM follows this recommendation and thus, does not deliver messages to stopped apps.
