### ISSUE TITLE
[Firebase Crashlytics] Missing User ID on dashboard

### ISSUE THREAD

**Issue by reactivedroid** [firebase/firebase-android-sdk#1909]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics
  * Component version: 17.1.1

### [REQUIRED] Step 3: Describe the problem

To uniquely identify a crash and debug further, we started sending `user_id` to Crashlytics. While it initially showed up on the dashboard for a couple of days, now we are not able to find any crash with UserID information.

#### Steps to reproduce:

We just updated the crashlytics version. Even on the latest version `17.2.1`, this issue has not been addressed.

#### Relevant Code:

```
FirebaseCrashlytics.getInstance().setUserId(<userId>)
```

**Comment by mrwillis21** [comment]
Hi @reactivedroid - that's definitely strange. Has user ID information disappeared from your existing crash reports, or is it that new crash reports are missing expected user ID data?

**Comment by reactivedroid** [comment]
@mrwillis21 Apparently I cannot see userId information on any of the crash report now. 🤔

**Comment by reactivedroid** [comment]
We faced this issue for the users who updated the app. We were logging `userId` only when the user signs into the app. Since the user has already signed into the app and just updated the app, for the logged-in user `userId` never fired.  This created an issue where the `userId` was not displayed on the crashlytics dashboard. We identified this issue and now it is working fine in production.
