### ISSUE TITLE
166130812: [In-App Messaging] Cannot disable Jetifier 

### ISSUE THREAD

**Issue by reactivedroid** [firebase/firebase-android-sdk#1910]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: In-App Messaging Display
  * Component version: 19.1.0

### [REQUIRED] Step 3: Describe the problem

While making the app fully migrate to AndroidX, the dependencies underneath should also be migrated. When we used the gradle plugin [canIDropJetifier](https://github.com/plnice/can-i-drop-jetifier), it showed the dependency on In-App Messaging display. This is blocking us to remove `android.enableJetifier=true` from `gradle.properties`. 

#### Steps to reproduce:

When we went through [In-App Messaging Display Gradle](https://github.com/firebase/firebase-android-sdk/blob/2843beafefcb03e4d2533d589a2251a7ac4e78fb/firebase-inappmessaging-display/firebase-inappmessaging-display.gradle#L72), we found that all dependencies are already on AndroidX. 

One probable cause can be `robolectric` which brings in implicit dependency from messaging. Note that, having `robolectric` also hinders in disabling Jetification.
<img width="858" alt="Screenshot 2020-08-24 at 2 21 57 PM" src="https://user-images.githubusercontent.com/12267638/91025213-b21aef00-e616-11ea-9343-229469b144ec.png">

#### Relevant Code:

Try 
```
android.enableJetifier=false
```

**Comment by rosariopfernandes** [comment]
Looks like #1874 intends to fix this.

**Comment by Hospes** [comment]
Any news here ?

**Comment by reactivedroid** [comment]
By using ktx library of in-app messaging `firebase-inappmessaging-display-ktx:19.1.1`, I can now disable jetifier from the project 🎉
