### ISSUE TITLE
Config Diff on Remote config dashboard

### ISSUE THREAD

**Issue by reactivedroid** [firebase/firebase-android-sdk#1911]
## What feature would you like to see?

The current Remote Config dashboard has `Change History` where all config changes are versioned and shown. This change history does not help much to the end-user since every log has the full config being shown. This typically means that, if a project has 200 key-value pairs, changing even a single key, will show the full changelog in the version history. This makes it really difficult to identify as to what key-value pairs have actually been changed. 

For eg: There is a pretty neat [Remote config monitor](https://github.com/eBay/firebase-remote-config-monitor) which displays the actual diff and posts on Slack. 

## How would you use it?

1. Having this feature will help many developers to properly manage the remote config. 
2. Providing a proper changelog with what has actually changed/edited/deleted on the Remote Config dashboard, will give faster feedback about the change.
3. Any issues occurring via RC changes can be resolved faster by going through the actual diffs on different versions.

**Comment by danasilver** [comment]
Hey @reactivedroid, have you seen the parameter comparison view under Change History? It sounds like it might have what you're looking for. When you select another version from Change History, if you click the 3-dots icon there's an item for "Compare with selected version" that'll bring up a parameter-to-parameter comparison view. It highlights parameters that have changed and there's a toggle at the top to only show changed parameters ("Show differences only").

![Screen Shot 2020-08-24 at 10 17 50 AM](https://user-images.githubusercontent.com/3270544/91075845-89cdc900-e5f3-11ea-9e91-8c4e1020534f.png)

**Comment by reactivedroid** [comment]
> Hey @reactivedroid, have you seen the parameter comparison view under Change History? It sounds like it might have what you're looking for. When you select another version from Change History, if you click the 3-dots icon there's an item for "Compare with selected version" that'll bring up a parameter-to-parameter comparison view. It highlights parameters that have changed and there's a toggle at the top to only show changed parameters ("Show differences only").
> 
> ![Screen Shot 2020-08-24 at 10 17 50 AM](https://user-images.githubusercontent.com/3270544/91075845-89cdc900-e5f3-11ea-9e91-8c4e1020534f.png)

Ahh, this is great...this is exactly what I wanted...A feature that is so powerful looks a little hidden to me. Probably a better UX will help more. 💯 👍
