### ISSUE TITLE
Why did my billing start to charge before reaching the 5GB quota?

### ISSUE THREAD

**Issue by LukeDaniel16** [firebase/firebase-android-sdk#1921]
I believed that Firebase Storage only started charging values ​​from 5Gb exceeded, however, I was charged a very small amount and I don't even have 10% of the quota value reached, is this a bug or something?

> <blockquote class="imgur-embed-pub" lang="en" data-id="a/YNF9KyO"  ><a href="//imgur.com/a/YNF9KyO">lontra store</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by LukeDaniel16** [comment]
Quote currently: 

> <blockquote class="imgur-embed-pub" lang="en" data-id="a/xcIzHg4"  ><a href="//imgur.com/a/xcIzHg4">lontrarina</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by wilhuff** [comment]
We can't help you with account-related issues here because we don't have access to your account or usage data.

The best way to proceed is to open a ticket with support: https://firebase.google.com/support.

**Comment by LukeDaniel16** [comment]
Okay, thanks and sorry for inadequate ask.
