### ISSUE TITLE
Bug: Getting error log: "Firebase Installations can not communicate with Firebase server APIs ..."

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [firebase/firebase-android-sdk#1928]
### [READ] Step 1: Are you in the right place?
Yes.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: 

```
    implementation 'com.google.firebase:firebase-core:17.2.1'
    implementation "com.google.firebase:firebase-messaging:20.0.0"
    implementation "com.google.firebase:firebase-invites:17.0.0"
    implementation "com.google.firebase:firebase-config:19.0.3"
    implementation "com.google.firebase:firebase-auth:19.1.0"
    implementation 'com.google.firebase:firebase-database:19.2.0'
```

  * Component version: 
Anything newer than what I wrote above will trigger the issue, especially if I update them all, including when I add this:

```
   implementation 'com.google.firebase:firebase-installations:16.3.3'
```
And this instead of the core:
```
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
```

### [REQUIRED] Step 3: Describe the problem
I got an old project to work on, and it works fine with Firebase as long as I don't update the dependencies I wrote above.

When I do try to update, I get errors on the logs.

#### Steps to reproduce:
If I update to these, for example:

```
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
    implementation "com.google.firebase:firebase-messaging:20.2.4"
    implementation "com.google.firebase:firebase-invites:17.0.0"
    implementation "com.google.firebase:firebase-config:19.2.0"
    implementation "com.google.firebase:firebase-auth:19.3.2"
    implementation 'com.google.firebase:firebase-database:19.4.0'
    //workaround for this issue: https://github.com/firebase/firebase-android-sdk/issues/1918 https://github.com/firebase/firebase-android-sdk/issues/1915
    implementation 'com.google.firebase:firebase-installations:16.3.3'
```

Or just to this:

```
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
    implementation "com.google.firebase:firebase-messaging:20.2.4"
    implementation "com.google.firebase:firebase-invites:17.0.0"
    implementation "com.google.firebase:firebase-config:19.2.0"
    implementation "com.google.firebase:firebase-auth:19.3.2"
    implementation 'com.google.firebase:firebase-database:19.4.0'
```

The exception I get is:

```
E: Firebase Installations can not communicate with Firebase server APIs due to invalid configuration. Please update your Firebase initialization process and set valid Firebase options (API key, Project ID, Application ID) when initializing Firebase.
E: Failed to get FIS auth token
    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException
        at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.2.0:69)
        at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.2.0:23)
        at com.google.firebase.iid.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-iid@@20.2.3:55)
        at com.google.firebase.iid.GmsRpc.startRpc(com.google.firebase:firebase-iid@@20.2.3:37)
        at com.google.firebase.iid.GmsRpc.getToken(com.google.firebase:firebase-iid@@20.2.3:13)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(com.google.firebase:firebase-iid@@20.2.3:164)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$4.start(Unknown Source:8)
        at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-iid@@20.2.3:14)
        at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$3$FirebaseInstanceId(com.google.firebase:firebase-iid@@20.2.3:163)
        at com.google.firebase.iid.FirebaseInstanceId$$Lambda$1.then(Unknown Source:6)
        at com.google.android.gms.tasks.zzf.run(com.google.android.gms:play-services-tasks@@17.2.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.4.0:6)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.google.firebase.installations.FirebaseInstallationsException
        at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:382)
        at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:350)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923) 
```

#### Relevant Code:
Not sure. I think the class that extends Application has this that's related :

```
    public static void init(final Application app) {
        ...
        final Context context = app.getApplicationContext();
        FirebaseApp.initializeApp(context);
        final Fabric fabric = new Fabric.Builder(app).kits(new CrashlyticsCore()).debuggable(BuildConfig.DEBUG).build();
        Fabric.with(fabric);
        ...
```

I tried searching about this on the Internet, and found [this](https://stackoverflow.com/a/61529757/878126), so i tried to re-generate an API key and get the json file and use it, but it didn't help.

**Comment by ankitaj224** [comment]
@AndroidDeveloperLB  Have you tried enabling the [Firebase Installations API](https://console.cloud.google.com/apis/library/firebaseinstallations.googleapis.com)?

**Comment by AndroidDeveloperLB** [comment]
@ankitaj224 No. Why do I need it? What does it do?
I only added it as a dependency because of some tip I found here:
https://github.com/firebase/firebase-android-sdk/issues/1918

**Comment by ankitaj224** [comment]
Firebase Android SDK updates [after February 27 2020](https://firebase.google.com/support/release-notes/android#2020-02-27) introduced the Firebase Installations SDK which comes with a dependency on the [Firebase Installations API](https://console.cloud.google.com/apis/library/firebaseinstallations.googleapis.com).

Firebase Installations requires valid Firebase options: API key, project ID, and application ID (a.k.a. "appId") in order to successfully communicate with Firebase servers.

Can you please verify if the  [Firebase Installations API](https://console.cloud.google.com/apis/library/firebaseinstallations.googleapis.com) is enabled for your project and the newly generated API key is valid for this API?

**Comment by AndroidDeveloperLB** [comment]
It isn't, because I don't need it, and I don't even know what it is.
How is it related here exactly?
I already wrote that this issue appears whether I add "firebase-installations" or not.

**Comment by ankitaj224** [comment]
When you update your dependencies for Firebase SDKs  Eg: implementation "com.google.firebase:firebase-messaging:20.2.4", these SDKs transitively depend on "com.google.firebase:firebase-installations" SDK. 

"firebase-installations" SDK requires [Firebase Installations API](https://console.cloud.google.com/apis/library/firebaseinstallations.googleapis.com) enabled to successfully communicate with Firebase servers and generates an unique identifier for an app installation required by other Firebase services such as FCM, Analytics etc.

**Comment by AndroidDeveloperLB** [comment]
@ankitaj224 So this means that even though the app doesn't need it, I need to create a new key that allows it?
Does it also mean I need to add additional code for it?

**Comment by AndroidDeveloperLB** [comment]
@ankitaj224 Also, it's already enabled:

![image](https://user-images.githubusercontent.com/5357526/91961149-76b5aa00-ed13-11ea-935a-a413a0c395ae.png)

Please explain exactly what needs to be done.

**Comment by ankitaj224** [comment]
@AndroidDeveloperLB I wont have access to your key, gson file/cloud project. 

To mitigate the issue:
- make sure that your application is using valid Firebase options from the latest google-services.json file from your Firebase console: [Firebase options: instructions and background](https://firebase.google.com/support/privacy/init-options).
- If you use API restrictions, make sure that the API key used by your application is white-listed for the Firebase Installations API (and for your application): [API restrictions: instructions and background](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/API_KEY_RESTRICTIONS.md)
- Regarding Application restrictions: Either set the radio button to None or make sure that your app is white-listed (with the correct SHA-1 certificate).

The error seems to indicate that either API key, Project ID, Application ID is not valid. This may not be the right place to share your Api Key. This problem can be better addressed by [Firebase support](https://firebase.google.com/support). Please reach us through those channels to get better help.

Thank you.

**Comment by AndroidDeveloperLB** [comment]
@ankitaj224 Sadly I already did this.
As I wrote you, I already tried to create a new key that includes the "installation",
And I've added my PC to the SHA-1 list.
The weird thing is that the gson generation doesn't allow me to choose which key to use (old vs new). It seems to even use a very old one instead. I had to manually change it.

**Comment by AndroidDeveloperLB** [comment]
About the website you offer, it keeps resetting to my private account instead of the one that's used for the project, BTW. Please fix this.
