### ISSUE TITLE
Firebase real time database is not working on ipv6 .

### ISSUE THREAD

**Issue by fridayowl** [firebase/firebase-android-sdk#1948]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by nipa87** [comment]
Yes I am also facing this problem

**Comment by nipa87** [comment]
The app is working on emulator but not in device

**Comment by nipa87** [comment]
Have you got any solution about it

**Comment by fridayowl** [comment]
change the APN of your internet connection to ipv4 then it will work it wont work on ipv6 .

**Comment by schmidt-sebastian** [comment]
@fridayowl Thanks for filing this issue and sorry about the slow response. We are looking at this with the backend team.

**Comment by schmidt-sebastian** [comment]
Please see comments in https://github.com/firebase/firebase-android-sdk/issues/1937, which has more data that the issue here. Therefore, I am closing this as a duplicate.
