### ISSUE TITLE
172245316: FLD not taking to the play store in some devices while link tapped from Skype.

### ISSUE THREAD

**Issue by ronem123** [firebase/firebase-android-sdk#1949]
I have created a Firebase dynamic link, implemented in the app works fine for the device which has the app installed. 
Further, I published the app as (close testing) alpha release to get the FLD test done. While taping on the dynamic link from the skype message box some of the devices do not redirect to the play store, instead, it opens the app download page in the internal browser. 
Also, I have another weird issue that In some of the devices while installing the app from FDL the **open** button is shown instead of **continue**.

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
