### ISSUE TITLE
The app crashes as soon as it starts

### ISSUE THREAD

**Issue by hyeonsu94** [firebase/firebase-android-sdk#1966]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment
- Android Studio version: 4.0.2
- build.gradle
implementation 'com.google.firebase:firebase-core:17.2.1'
implementation 'com.google.firebase:firebase-messaging:20.0.1'
implementation 'com.google.firebase:firebase-perf:19.0.4'
releaseImplementation('com.crashlytics.sdk.android:crashlytics:2.10.1@aar') {
    transitive = true;
 }

### [REQUIRED] Step 3: Describe the problem
- description
Our app is launcher app on ATV Device. After the device is turned on, the launcher app(our app) is launched, but immediately after the app is launched, it crashes and operation is impossible. It is also impossible to open the setting menu to enable USB debugging (continous black screen). The following log was obtained by the native log collector installed in the device.

- exception stack trace:
_SharedPreferencesImpl:Attempt to read preferences file /data/user/0/{our app package name}/shared_prefs/FirebasePerfSharedPrefs.xml without permission 
FirebasePerformance:  Creating a new Non Verbose Session: 311f9e2684284ba096e5e6f841a72b3e 
FirebasePerformance:  Creating a new Non Verbose Session: 5846ebbaeeee4d73b4d5442da13d427b 
SharedPreferencesImpl:Cannot read /data/user/0/{our app package name}/shared_prefs/com.google.android.gms.appid.xml 
SharedPreferencesImpl:org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @2:568 in java.io.InputStreamReader@c92fb1e)  
SharedPreferencesImpl:	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1220) 
SharedPreferencesImpl:	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1402) 
SharedPreferencesImpl:	at org.kxml2.io.KXmlParser.next(KXmlParser.java:393) 
SharedPreferencesImpl:	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313) 
SharedPreferencesImpl:	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1405) 
SharedPreferencesImpl:	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740) 
SharedPreferencesImpl:	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:153) 
SharedPreferencesImpl:	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54) 
SharedPreferencesImpl:	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:122) 
SharedPreferencesImpl:Attempt to read preferences file /data/user/0/{our app package name}/shared_prefs/frc_1:88488171453:android:922ac05566b7437a_fireperf_settings.xml without permission 
AndroidRuntime:       Shutting down VM 
AndroidRuntime:       FATAL EXCEPTION: main 
AndroidRuntime:       Process: {our app package name}, PID: 30213 
AndroidRuntime:       java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: java.lang.IllegalArgumentException: tv_nsec value 1069893188 is not in [0, 999999999] 
AndroidRuntime:       	at android.app.ActivityThread.installProvider(ActivityThread.java:6418) 
AndroidRuntime:       	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5960) 
AndroidRuntime:       	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5875) 
AndroidRuntime:       	at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
AndroidRuntime:       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
AndroidRuntime:       	at android.os.Handler.dispatchMessage(Handler.java:106) 
AndroidRuntime:       	at android.os.Looper.loop(Looper.java:193) 
AndroidRuntime:       	at android.app.ActivityThread.main(ActivityThread.java:6691) 
AndroidRuntime:       	at java.lang.reflect.Method.invoke(Native Method) 
AndroidRuntime:       	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
AndroidRuntime:       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
AndroidRuntime:       Caused by: java.lang.IllegalStateException: java.lang.IllegalArgumentException: tv_nsec value 1069893188 is not in [0, 999999999] 
AndroidRuntime:       	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:265) 
AndroidRuntime:       	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:309) 
AndroidRuntime:       	at com.google.firebase.remoteconfig.internal.ConfigMetadataClient.getFetchTimeoutInSeconds(com.google.firebase:firebase-config@@19.0.4:87) 
AndroidRuntime:       	at com.google.firebase.remoteconfig.RemoteConfigComponent.getFrcBackendApiClient(com.google.firebase:firebase-config@@19.0.4:232) 
AndroidRuntime:       	at com.google.firebase.remoteconfig.RemoteConfigComponent.getFetchHandler(com.google.firebase:firebase-config@@19.0.4:246) 
AndroidRuntime:       	at com.google.firebase.remoteconfig.RemoteConfigComponent.get(com.google.firebase:firebase-config@@19.0.4:164) 
AndroidRuntime:       	at com.google.firebase.perf.zza.create(com.google.firebase:firebase-perf@@19.0.4:5) 
AndroidRuntime:       	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69) 
AndroidRuntime:       	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4) 
AndroidRuntime:       	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53) 
AndroidRuntime:       	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158) 
AndroidRuntime:       	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563) 
AndroidRuntime:       	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304) 
AndroidRuntime:       	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268) 
AndroidRuntime:       	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253) 
AndroidRuntime:       	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51) 
AndroidRuntime:       	at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
AndroidRuntime:       	at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
AndroidRuntime:       	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45) 
AndroidRuntime:       	at android.app.ActivityThread.installProvider(ActivityThread.java:6413) 
AndroidRuntime:       	... 10 more 
AndroidRuntime:       Caused by: java.lang.IllegalArgumentException: tv_nsec value 1069893188 is not in [0, 999999999] 
AndroidRuntime:       	at android.system.StructTimespec.<init>(StructTimespec.java:35) 
AndroidRuntime:       	at libcore.io.Linux.stat(Native Method) 
AndroidRuntime:       	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328) 
AndroidRuntime:       	at android.system.Os.stat(Os.java:565) 
AndroidRuntime:       	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:147) 
AndroidRuntime:       	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54) 
AndroidRuntime:       	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:122) 
ActivityManager:        Force finishing activity {our app package name}/.{our app activity name}_

**Comment by yalunqin** [comment]
Internally tracked at b/168561341

**Comment by jposuna** [comment]
Hi hyeonsu94,

I'm not 100% sure of the cause here, especially because we don't have official support for ATV and if things don't work out-of-the-box it's hard for us to debug and fix them.

It looks like the issue is with tv_nsec being outside of a valid range `[0, 999999999]`. https://www.gnu.org/software/libc/manual/html_node/Time-Types.html also mentions this same range, and it looks like the actual value is too big (`1069893188`).

Can you try removing the dependency for `com.google.firebase:firebase-perf` and see if the issue still occurs?
