### ISSUE TITLE
Firestore realtime query stops working after few updates

### ISSUE THREAD

**Issue by MahmoudiOussama** [firebase/firebase-android-sdk#1971]
### [READ] Step 1: Are you in the right place?
**Yes, I am.**

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio v 4.0.1
  * Firebase Component: Firestore
  * Component version: 21.6.0

#### Describe the problem
  After i updated all firebase libs to the latest stable versions, and implemented the firebase-crashlytics lib instead of the fabric crashlytics, Firestore queries started to not work as usual/expected, i tried both single read/write queries, and realtime queries, they both have issues.

#### Steps to reproduce:  
  * If i start a realtime query (snapshot listener) on a single document, and that document contains few fields, everything works fine, each time the document is updated, the **onEvent** method will work. see below screen recording GIF: 

![Firestore-sample1](https://user-images.githubusercontent.com/25067744/92808151-66589b80-f3b3-11ea-9b49-b698f017adca.gif)

  * Now, if i try to make a realtime query on a single document that contains much more fields, the **onEvent** method will either never be triggered (even once), or it could get triggered few times, then stops. see below screen recording GIF : 

![Firestore-sample2](https://user-images.githubusercontent.com/25067744/92808785-f1d22c80-f3b3-11ea-831a-b4dc9dc9803d.gif)

  * Finally, i even tried write queries, where i am updating a single field in a document, it may work for several tries, then it stops sending updates to the document.

#### Relevant Code:

I created a sample Android project with minimum possible code to reproduce the problem (the project may appear to be bigger than minimal code, but believe me it is)
I put the sample project inside of a public github repository where i explained everything in the readme file : 
[repository from here](https://github.com/MahmoudiOussama/firestore-sample)

I trust you all Firebase team, please make this work perfect as before.

My sincere greetings.

**Comment by MahmoudiOussama** [comment]
After further investigation and test, we (work team) concluded that this issue only occurs when the document contains a field of type Map which contains multiple key values (in our test case, we had a Map with 5 levels, with multi key-value pairs).

**Comment by MahmoudiOussama** [comment]
Also, i wanted to say that if I downgrade the firebase-firestore lib from v21.6.0 to v20.1.0 everything works perfect.

**Comment by wilhuff** [comment]
Thanks for your sample project--I'll try to reproduce and see what's going on.

**Comment by wilhuff** [comment]
So digging into this, what's actually happening is that your app is becoming CPU and GC bound. It isn't that the listener stops firing, it's that your writes are taking a very long time to send (sometimes well over a minute).

Profiling, I see that you're spending a lot of time in `protobuf.AbstractMessage.equals`, which was a regression introduced in Firestore 21.5.0 with the upgrade to protobuf-javalite (previously reported in #1906). Large messages exacerbate this performance problem.

We submitted a fix (#1920) essentially just after the freeze for the last release so it didn't make it into 21.6.0. This fix should go out with the upcoming release. Any version prior to 21.5.0 should be unaffected.

Apologies for the trouble this caused you but I'm glad this isn't a new issue :-).

Cheers!

**Comment by MahmoudiOussama** [comment]
Thank you for answering sir. I hope the next update won't take long.
