### ISSUE TITLE
Firebase Analytics keeps tracking screens automatically

### ISSUE THREAD

**Issue by RankoR** [firebase/firebase-android-sdk#1976]
* Android Studio version: 4.0.1
  * Firebase Component: Analytics-KTX
  * Component version: 17.5.0
  * Google Services plugin version: 4.3.3

I have a single-activity application and I want to track my screens manually.

I use the `FirebaseAnalytics.Event.SCREEN_VIEW` event for this, and I've disabled auto tracking as it's specified in the docs:

```
<application>
... 
 <meta-data
            android:name="google_analytics_automatic_screen_reporting_enabled"
            android:value="false" />
</application>
```

I report the screens like this:

```
    override fun reportEvent(name: String, params: Map<String, Any?>) {
        Timber.d("Logging event \"$name\"")

        analytics
            .logEvent(name) {
                params
                    .keys
                    .forEach { paramName ->
                        when (val value = params[paramName]) {
                            is String -> param(name, value)
                            is Int -> param(name, value.toLong())
                            is Long -> param(name, value)
                            is Float -> param(name, value.toDouble())
                            is Double -> param(name, value.toDouble())
                            is Boolean -> param(name, value.toString())
                            else -> {
                                Timber.w("Unsupported value for param $paramName")
                            }
                        }
                    }
            }
    }

    override fun logScreenView(activity: Activity, name: String) {
        Timber.d("Tracking screen with name $name")

        reportEvent(
            FirebaseAnalytics.Event.SCREEN_VIEW,
            mapOf(
                FirebaseAnalytics.Param.SCREEN_NAME to name,
                FirebaseAnalytics.Param.SCREEN_CLASS to name
            )
        )
    }
```

I use correct screen names like `Sections` (note: I use the same value for `class` and `name`).

But in the dashboard I still see only `MainActivity` class (which should not be tracked at all):

<img width="514" alt="image" src="https://user-images.githubusercontent.com/71142/92946469-61e9bc80-f45f-11ea-8965-5fab72d58877.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/71142/92946511-6f06ab80-f45f-11ea-95a6-68cce4eea12e.png">

I've selected only the latest version of the app, where auto tracking is disabled.

**Comment by piotr767** [comment]
Any news on this bug? I also noticed that disabling automatic screen tracking doesn't work (I used firebase-analytics:17.6.0).

**Comment by Manc** [comment]
It looks like my app is using firebase-analytics:18.0.0, I added `<meta-data android:name="google_analytics_automatic_screen_reporting_enabled" android:value="false" />` to the `<application>` section of the AndroidManifest.xml file, yet it's still auto-logging screen views. The app is a React Native app with only one activity.

When I start the app, log cat prints:

```
2020-11-28 10:15:30.942 7442-24006/? V/FA-SVC: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=5282144728167676718}]
2020-11-28 10:16:24.584 7442-24741/? V/FA-SVC: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=2534753336748792289}]
```

(Yes, twice.)

- Android Studio version: 4.1.1
- Firebase Component: Analytics-Java (com.google.firebase.firebase_analytics)
- Component version: 18.0.0

**Comment by piotr767** [comment]
It's not working again... About a month ago no screen_view events with origin == auto were sent when this option was disabled (this included both screen_view events tracked by firebase when launching an activity and screen_view events tracked when calling setCurrentScreen() method), which was what I expected.
Now all those events are being sent again.

Guys, we need some feedback on this issue because there is no way we can debug it ourselves. There is no source code for firebase-analytics library and its behaviour changes despite the version being unchanged.

**Comment by argzdev** [comment]
Hi all, given that the behavior changed despite the version, I believe it is best to reach out to the [Firebase support team](https://firebase.google.com/support/troubleshooter/contact), since the backend is the most definite culprit, and there's not much we can do on the SDK side. That said, given that this has been resolved, I'll close this now. Thanks!
