### ISSUE TITLE
Crashlytics not work with mapping.txt for Dexguard (upload automatically)

### ISSUE THREAD

**Issue by charleston10** [firebase/firebase-android-sdk#1987]
### Describe your environment
Android Studio version: 4.0.1
Firebase Component: Firebase Crashlytics
Component version: 17.2.1

### Describe the problem

My project contains Dexguard to guarantee a level of security
When I migrated from Crashlytics to FirebaseCrashlytics the firebase panel in the Firebase Console, I started logging the classes with the name "????"
So I need to include the mapping.txt file for firebase to be able to log crashes correctly

Below I tried to make the configuration to upload the mapping file automatically add firebaseCrashlytics.mappingFileUploadEnabled true

but it didn't work

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:uploadCrashlyticsMappingFileHomolog'.
> Expected file collection to contain exactly one file, however, it contains no files.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:uploadCrashlyticsMappingFileHomolog'

Caused by: java.lang.IllegalStateException: Expected file collection to contain exactly one file, however, it contains no files.
at com.google.firebase.crashlytics.buildtools.gradle.tasks.UploadMappingFileTask.uploadMappingFile(UploadMappingFileTask.groovy:60)
```

**Steps to reproduce:**
Only build project with these settings

**Relevant Code:**

```
homolog {
            proguardFile getDefaultDexGuardFile('dexguard-release-aggressive.pro')
            proguardFile getDefaultDexGuardFile('dexguard-androidx.pro')
            proguardFile 'dexguard-project.txt'

            firebaseCrashlytics {
                mappingFileUploadEnabled true
            }
        }
...

implementation "com.google.firebase:firebase-analytics:17.5.0"
implementation 'com.google.firebase:firebase-crashlytics:17.2.1'
```

```
class ProjectApplication : Application {
...
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true)
...
}
```

Dexguard
```
### Code to run Crashlytics
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keep public class * extends java.lang.Exception
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**
```

**Comment by pablopatarca** [comment]
Hi @charleston10 !
It seems that DexGuard is not generating the mapping file and when the `upload` task starts doesn't find anything.
You can do it adding the next rule:
```
-printmapping build/outputs/mapping/release/mapping.txt
```

**Comment by charleston10** [comment]
@pablopatarca 
> Hi @charleston10 !
> It seems that DexGuard is not generating the mapping file and when the `uploadCrashlyticsMappingFile` task starts doesn't find anything.
> You can do it adding the next rule:
> 
> ```
> -printmapping build/outputs/mapping/release/mapping.txt
> ```

I tried now and it didn't work
What version are you using dexguard?

**Comment by Bersh** [comment]
Today I learned that if you apply `firebase-crashlytics` gradle plugin declaratively, using the `plugins {}` block the mapping file upload tasks are not created. In order to make it work I had to apply the plugin imperatively, using the legacy `apply(..)` function. This is what I have in the project now:
```
apply(plugin = "com.google.firebase.crashlytics")

plugins {
    //other plugins
}
```

Not sure if it helps in your case but probably worth trying

**Comment by charleston10** [comment]
I solved the problem 

dexguard file
```
### Code to run Crashlytics
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keep public class * extends java.lang.Exception
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**
-keepresourcexmlelements manifest/application/service/meta-data@value=cct
```

```
 firebaseCrashlytics {
    mappingFile("build/outputs/mapping/release/mapping.txt")
    mappingFileUploadEnabled true
}
```
