### ISSUE TITLE
Firebase Crashlytics assumes use of proguard rules shipped with the android SDK

### ISSUE THREAD

**Issue by jzbrooks** [firebase/firebase-android-sdk#1996]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics (Database, Firestore, Storage, Functions, etc)
  * Component version: 17.2.1

### [REQUIRED] Step 3: Describe the problem

Our team doesn't use the default proguard ruleset. Being more specific with what we keep and don't keep helps us keep our app lean. Since that ruleset isn't included, we don't keep `values()` methods on every enum in the system.

This causes a crash when uploading crashes to firebase. [`Priority`](https://github.com/firebase/firebase-android-sdk/blob/master/transport/transport-api/src/main/java/com/google/android/datatransport/Priority.java) is used reflectively in the `EnumMap` within `PriorityMapping`.

```
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: com.faithlife.mobile, PID: 7912
                         E  java.lang.RuntimeException: Testing crashlytics sdk upgrade
                         E      at com.faithlife.mobile.mainmenu.MainMenuFragment.O0(MainMenuFragment.kt:10)
                         E      at com.faithlife.mobile.mainmenu.MainMenuFragment$onViewCreated$3.d(MainMenuFragment.kt:3)
                         E      at at.onClick(Unknown Source:2)
                         E      at android.view.View.performClick(View.java:6597)
                         E      at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
                         E      at android.view.View.performClickInternal(View.java:6574)
                         E      at android.view.View.access$3100(View.java:778)
                         E      at android.view.View$PerformClick.run(View.java:25885)
                         E      at android.os.Handler.handleCallback(Handler.java:873)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:193)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6669)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                         E  FATAL EXCEPTION: pool-6-thread-1
                         E  Process: com.faithlife.mobile, PID: 7912
                         E  java.lang.AssertionError: impossible
                         E      at java.lang.Enum$1.create(Enum.java:272)
                         E      at java.lang.Enum$1.create(Enum.java:262)
                         E      at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
                         E      at java.lang.Enum.getSharedConstants(Enum.java:289)
                         E      at java.lang.Class.getEnumConstantsShared(Class.java:2423)
                         E      at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
                         E      at java.util.EnumMap.<init>(EnumMap.java:138)
                         E      at iF.<clinit>(PriorityMapping.java:2)
                         E      at iF.a(PriorityMapping.java:1)
                         E      at RE.f(SQLiteEventStore.java:7)
                         E      at RE.F(SQLiteEventStore.java:7)
                         E      at dE.a(DefaultScheduler.java:9)
                         E      at RE.V(SQLiteEventStore.java:5)
                         E      at eE.a(DefaultScheduler.java:13)
                         E      at cE.run(Unknown Source:8)
                         E      at ID.run(SafeLoggingExecutor.java:1)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:764)
                         E  Caused by: java.lang.NoSuchMethodException: values []
                         E      at java.lang.Class.getMethod(Class.java:2068)
                         E      at java.lang.Class.getDeclaredMethod(Class.java:2047)
                         E      at java.lang.Enum$1.create(Enum.java:268)
                         E      ... 18 more
```

I'd expect firebase to provide a specific keep rule in this situation, or at least specific to a certain package granularity so that we don't end up keeping code in dex files that we don't need. Ideally, they'd ship in the appropriate metadata location so that R8 can automatically pick up the third party rules.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Build an android app with the above environment, using R8. Do not include the proguard rules shipped in the android sdk.

#### Relevant Code:

I can work around the problem with the following keep rule, but it would be ideal to ship that rule with the library so that others may benefit.

```
-keepclassmembers enum com.google.android.datatransport.Priority {
    public static **[] values();
}
```

**Comment by mrichards** [comment]
Thanks for reporting this! I've reproduced the issue and I'll post an update here when the fix is merged and we have an ETA for release.

**Comment by mrichards** [comment]
The fix has been merged and will go out in the next release. As you can see in the PR, rather than adding a Proguard rule, we changed the underlying implementation to avoid the reflection call.
