### ISSUE TITLE
Crashlytics report could not be enqueued to DataTransport (IllegalArgumentException)

### ISSUE THREAD

**Issue by pablopatarca** [firebase/firebase-android-sdk#1998]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Firebase Crashlytics & Firebase Crashlytics Gradle
  * Component version: 17.2.1 & 2.2.0

### [REQUIRED] Step 3: Describe the problem
App built with DexGuard doesn't report to Firebase Console, I cant even see the build version in the filter console.
Every time what the app is launched produce the same exception:

```
D/FirebaseCrashlytics: Checking for crash reports...
D/FirebaseCrashlytics: Found crash report /data/user/0/com.xxxxxxx/files/.com.google.firebase.crashlytics/nonfatal-sessions/5F64E11E01BD-0001-6C5D-32B9DF9F8C8E.cls
D/FirebaseCrashlytics: Reports are being sent.
D/FirebaseCrashlytics: Starting report processing in 1.0 second(s)...
D/FirebaseCrashlytics: No log data to include with this event.
D/FirebaseCrashlytics: Update app request ID: aca879994130dcc6ab3f551k2j4bjj23
D/FirebaseCrashlytics: No log data to include with this event.
D/FirebaseCrashlytics: Result was 204
D/FirebaseCrashlytics: Crashlytics report could not be enqueued to DataTransport
    java.lang.IllegalArgumentException: Transport backend 'cct' is not registered
        at com.google.android.datatransport.runtime.scheduling.DefaultScheduler$$Lambda$1.run(:1077)
        at com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Instead if the app is built in debug (without dexguard), it works.

#### Steps to reproduce:

Building the project with the next configuration:

**build.gradle**
```
apply plugin: 'com.android.application'
apply plugin: 'dexguard'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'
apply plugin: 'com.google.android.gms.strict-version-matcher-plugin'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
...
release {
           firebaseCrashlytics {
                mappingFileUploadEnabled true
            }
...
dependencies {
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-crashlytics:17.1.1'
...
```

**dexguard-rules.pro**
```
-keepattributes SourceFile,LineNumberTable
-keep public class * extends java.lang.Exception
```

**Comment by charleston10** [comment]
@pablopatarca Hi
If you can solve your problem, out of the issue let me know, pls
I am facing almost the same problem with dexguard (#1987 )

**Comment by omesquita** [comment]
i have too same problem and not find a solution.

**Comment by GauravP123** [comment]
I am also getting the same issue .Using 17.2.1

**Comment by pablopatarca** [comment]
I've found a solution for this issue provided from the DexGuard documentation:
source: [](https://www.guardsquare.com/en/manual/dexguard/stable/gradle/dexguard-plugin.html#firebaseCrashlytics)
> First off, the Crashlytics plugin should be applied before the DexGuard plugin.
```
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'dexguard'
```
But steal the problem doesn't resolve, the app version is not published in the firebase console :'(

**Comment by omesquita** [comment]
Here the crashlytics plugin is applied before dexguard plugin, but even so i have the same problems. The crashes aren't sended to console.

**Comment by pablopatarca** [comment]
@omesquita which plugin version are you testing with? 

I'm trying with `2.3.0` for crashlytics and `8.5.06` for dexguard

**Comment by omesquita** [comment]
> @omesquita which plugin version are you testing with?
> 
> I'm trying with `2.3.0` for crashlytics and `8.5.06` for dexguard

here i'm using `2.2.1` for crashlytics plugin and `8.6.09` for dexguard.

**Comment by Bersh** [comment]
In case you are still struggling with it try to add this you your dexguard/proguard config file: 
```
-keepresourcexmlelements manifest/application/service/meta-data@value=cct
```

**Comment by pablopatarca** [comment]
Ok guys, I've solved the problem,
The solution requires two part:

**1- Check the plugins order:**
Your gradle.properties should look like this:
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'dexguard'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
...
```
**2- Downgrade the firebase-crashlytics version to 17.1.0**
`implementation 'com.google.firebase:firebase-crashlytics:17.1.0'`

And that's it!

I hope this helps you.

**Comment by GauravP123** [comment]
17.2.0 with DexGuard version to 8.6.X  is working? @pablopatarca

**Comment by omesquita** [comment]
> In case you are still struggling with it try to add this you your dexguard/proguard config file:
> 
> ```
> -keepresourcexmlelements manifest/application/service/meta-data@value=cct
> ```

It worked for me. Thanks for the help.

**Comment by pablopatarca** [comment]
> 17.2.0 with DexGuard version to 8.6.X is working? @pablopatarca
Sorry @GauravP123, with version DexGuard 8.7.06 and Crashlytics 17.2.1 works!
