### ISSUE TITLE
Firebase Crashlytics now logging fatal when using custom Uncaught Exception Handler

### ISSUE THREAD

**Issue by mwshubham** [firebase/firebase-android-sdk#2001]
Is this related to using   Thread.setDefaultUncaughtExceptionHandler(exceptionHandler);

https://github.com/firebase/firebase-android-sdk/issues/1278#issuecomment-606481792

Removing the code was not the solution, IMO.

I am having the same issue. On using Custom Uncaught Exception Handler,  fatal exceptions are not logging.

_Originally posted by @mwshubham in https://github.com/firebase/firebase-android-sdk/issues/1952#issuecomment-697225524_

**Comment by snehabhegade** [comment]
I am facing the same issue.

**Comment by dev071089** [comment]
I am also facing the same issue. Has anybody found some solution on this.

**Comment by mwshubham** [comment]
We have removed the custom Uncaught Exception Handler for now.

**Comment by mrwillis21** [comment]
Hi @mwshubham @dev071089 @snehabhegade - I've written up an example of how to use a custom exception handler over here: https://github.com/firebase/firebase-android-sdk/issues/1952#issuecomment-713094146 - please let me know if that helps! :)
