### ISSUE TITLE
FirebaseInstallations.registerFidWithServer crashes on Moto Z (2) Force (Android 7.1.1)

### ISSUE THREAD

**Issue by l-barbosa** [firebase/firebase-android-sdk#2011]
### Environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics, Analytics, Config, Messaging
  * Component version: `firebase-core:17.5.0`, `firebase-crashlytics:17.2.1`, `firebase-analytics:17.5.0`, `firebase-config:19.2.0`, `firebase-messaging:20.2.4`

### Describe the problem

36 crash reports coming in of a crash with `FirebaseInstallations.registerFidWithServer`
Crashlytics reports the same device in all cases: `Moto Z (2) Force`, running `Android 7.1.1`

I suspect that this may be the same user/device as the crashes occurred on the same day and the device being the same and rather old is unusual. It is reported by Crashlytics as 36 crashes affecting 30 users but I'm hoping that the same user may have tried to reinstall multiple times. Would these be counted as different users?

Anyway, found #1787, but the app is running Crashlytics 17.2.1 which the issue says contains the fix.

#### Steps to reproduce:

Not able to reproduce it but couldn't try it on the same device/OS version

#### Stack trace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doGetId$1(FirebaseInstallations.java)
       at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(FirebaseInstallations.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by Olegkodysh** [comment]
App reinstalls count as new installs and are given new unique ID's, so they would be counted as new users. In regards to the specific error, I don't have context on it, but I will surface it to some Crashlytics engineers.

**Comment by mrwillis21** [comment]
Hi @l-barbosa, can you try updating to the latest version of Crashlytics, 17.3.1? Also, can you run `./gradlew app:dependencies` and see what version of Firebase Installations is actually being pulled into your app? Thanks!

**Comment by l-barbosa** [comment]
Hi @mrwillis21,

Several updates of the app have been made since (including updating the libraries to the latest version) and the error has not resurfaced. I can't say for sure which was the version of the Firebase Installations being used as it wasn't directly included as a dependency. Maybe you can infer that information from the other dependencies?

In any case, from my end at least, this is not an issue anymore.

Thanks for looking into it though!

**Comment by mrwillis21** [comment]
Good news! Thanks @l-barbosa! :)
