### ISSUE TITLE
getToken(senderId, scope) throw IOException: INVALID_TARGET_VERSION.

### ISSUE THREAD

**Issue by vikey89** [firebase/firebase-android-sdk#2030]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _4.0.1 Build #AI-193.6911.18.40.6626763, built on June 25, 2020_
  * Firebase Component: _Firebase Cloud Messaging_
  * Component version: _20.3.0_

#### Steps to reproduce:

When I compile my app with target 30 (Android 11) the method 
`FirebaseInstanceId.getInstance().getToken(senderId, scope)` throw out the exception java.io.IOException: INVALID_TARGET_VERSION.
If I compile the app for Android Q instead, it works fine.

There is nowhere in the documentation that the method doesn't work with Android 11.

How can I set multi-senderID with an app with target 30?

#### Relevant Code:
Other Firebase Dependencies:

```
    implementation "com.google.firebase:firebase-perf:19.0.9"
    implementation "com.google.firebase:firebase-core:17.5.0"
    implementation "com.google.firebase:firebase-messaging:20.3.0"
    implementation "com.google.firebase:firebase-config:19.2.0"
    implementation "com.google.firebase:firebase-analytics:17.5.0"
```

**Comment by ciarand** [comment]
Hi Vincenzo! What scope are you using in the `getToken` call?

**Comment by vikey89** [comment]
Hello, thank you very much for your attention. 

I use FirebaseMessaging.INSTANCE_ID_SCOPE

**Comment by vikey89** [comment]
Hi, I got an official response from the Firebase team, It is no longer possible to use the `getToken(senderId, scope) `method passing multiple senderIDs, but we must make a request for each senderID.

I write it here maybe it can be useful to someone 😄
