### ISSUE TITLE
[Question] Dynamic Linking open an App in Intune Portal instead of Google Play Store?

### ISSUE THREAD

**Issue by raisarijasa** [firebase/firebase-android-sdk#2044]
I wonder whether is there any possibility for Firebase Dynamic Linking to open an application in Intune Portal instead of Google Play Store?
I want to create a Dynamic linking with pre-populate data, of the app is not installed yet an application page will be opened in Intune Portal and when user install it the apps form will filled by pre-populate data. Or if the app has been installed it will directly open the app and filled the form with pre-populate data.
If it is possible, is there any preference for the Dynamic Linking format/setting to make it happen?

**Comment by eldhosembabu** [comment]
hi @raisarijasa ,

You can configure the firebase dynamic link to take the user to apple appstore if the link is clicked on iOS device and similarly to android playstore if the link is clicked on an Android device when the app is not installed. So basically from where you clicked the link (Android or iOS) determines where you would be taken if the application is not installed.

To answer your second question: Yes, you can achieve the same with an firebase dynamic link with code changes in your app.

1. Create the firebase dynamic link with deeplink url having query params to populate the forms data.
2. Set up your client iOS or Android app to parse this data when they are deeplinked to populate the forum.
3. In the case of iOS, if this link is clicked and 
- If the app is installed, then the app will be universal linked and you can parse the forms data from the deeplink to populate the form.
- If the app is not installed, the user will be taken to appstore to install the app and one the user installs the app and opens the app by himself, the Firebase Dynamic Links SDK will try to retrieve the deeplink previously clicked and you can parse the link to populate the forms data.
- For Android, You can do it the same way.

Refer to [Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links) for more info.

**Comment by argzdev** [comment]
Hi, since this question has been answered and no follow ups has been made. I'll be closing the ticket now. Feel free to ask any other questions by opening a new ticket. Thank you!
