### ISSUE TITLE
Firebase crashlytics doesn't shows error reports when number of custom keys goes over 64

### ISSUE THREAD

**Issue by mashahbazi** [firebase/firebase-android-sdk#2047]
* Android Studio version: 4.0.0
  * Firebase Component: Crashlytics
  * Component version: 17.1.0

#### Steps to reproduce:
When adding custom keys to crashlytics and numbers goes more that 64 it wont ignore new value except in console shows `Error loading your session`. This error shows for all tabs including stack trace, keys, data, log. When amount of keys is less than 64 is works without problem. Same issue when length of one value goes more than 1024kB.

**Comment by cvaghela** [comment]
Crashlytics supports a maximum of 64 key/value pairs. After you reach this threshold, additional values are not saved. Each key/value pair can be up to 1 kB in size.
[Reference](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios)

**Comment by mashahbazi** [comment]
@cvaghela I know about the limitation and if you read issue well you will see that I say it shows `Error loading your session. Docs says is wont save that is means it will shows old keys but it doesn't.

**Comment by mrwillis21** [comment]
Hi @mashahbazi - is this still a problem for you? We've recently made upgrades to our web console to fix some issues causing errors when loading sessions.
