### ISSUE TITLE
Version 17.2.1 showing as Lint error

### ISSUE THREAD

**Issue by dan-0** [firebase/firebase-android-sdk#2049]
* Android Studio version: 4.0.1
  * Firebase Component: Crashlytics (Database, Firestore, Storage, Functions, etc)
  * Component version: 17.2.1

The Crashlytics SDK requires version 17.0.0 to work after November 15, 2020. We updated a few months ago because of this, but now we're getting lint errors with the updated version `com.google.firebase:firebase-crashlytics:17.2.1`. It seems like a bug that `17.2.1` is being reported as an error while the current version is `17.2.2`

Lint Error:

```
  Errors found:
  
  ...app/build.gradle:304: Error: This version is deprecated. Details: The Firebase Crashlytics beta SDK is now deprecated and will continue reporting your app's crashes only until November 15, 2020. To continue getting crash reports in the Firebase console, make sure you upgrade to the generally available Firebase Crashlytics SDK version 17.0.0+.
  For more information, visit https://firebase.google.com/docs/crashlytics/get-started. Consider switching to recommended version 17.2.2. [OutdatedLibrary]
      implementation 'com.google.firebase:firebase-crashlytics:17.2.1'
```

#### Steps to reproduce:

1. Use version `17.2.1` of Android Crashlytics SDK
2. Run `./gradlew lint`
3. Task fails due to version

Example project:
[CrashlyticsBug.zip](https://github.com/firebase/firebase-android-sdk/files/5341318/CrashlyticsBug.zip)

#### Relevant Code:

```
implementation 'com.google.firebase:firebase-crashlytics:17.2.1'
```

**Comment by dan-0** [comment]
Thanks @mrwillis21  

To note, this started happening today, without any code changes, lint checks on the same branches were passing yesterday.

**Comment by mrwillis21** [comment]
Hi @dan-0 - we've rolled out a fix for this and it should be resolved now. There is a local cache, though - if you're on a Mac it should be resolved with a clean build. If not, let me know and I'll send along further instructions. :)
