### ISSUE TITLE
firebase-crashlytics-gradle uploadCrashlyticsMappingFileXxxRelease task failed.

### ISSUE THREAD

**Issue by wurensen** [firebase/firebase-android-sdk#2057]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: firebase-crashlytics-gradle
  * Component version: 2.3.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

The 'uploadCrashlyticsMappingFileXxxRelease' task doesn't declared it's depending relationship, which causing the task 'assembleRelease' error because mapping file did not create:

```
* What went wrong:	
Execution failed for task ':makeup:uploadCrashlyticsMappingFileSetupRelease'.	
> java.io.FileNotFoundException: /var/workspace/workspace/CI-MakeupPlus/release-5.5.0-11-59-pipeline/makeup/build/outputs/mapping/setup/release/mapping.txt (No such file or directory)	
* Try:	
Run with --info or --debug option to get more log output. Run with --scan to get full insights.	
* Exception is:	
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':makeup:uploadCrashlyticsMappingFileSetupRelease'.
```
here is my workaround in my app-level build.gradle file:
```
afterEvaluate {
    def appExtension = extensions.findByName("android")
    appExtension.applicationVariants.each { variant ->
        Task uploadCrashlyticsTask = tasks.findByName("uploadCrashlyticsMappingFile${variant.name.capitalize()}")
        Task packageTask = tasks.findByName("package${variant.name.capitalize()}")
        Task packageBundleTask = tasks.findByName("package${variant.name.capitalize()}Bundle")
        if (uploadCrashlyticsTask != null && packageTask!= null) {
            println packageTask.name
            uploadCrashlyticsTask.mustRunAfter(packageTask)
        }
        if (uploadCrashlyticsTask != null && packageBundleTask != null) {
            println packageBundleTask.name
            uploadCrashlyticsTask.mustRunAfter(packageBundleTask)
        }
    }
}
```

**Comment by gurappa** [comment]
Could you solve it @wurensen ? Any clues ?

**Comment by wurensen** [comment]
> Could you solve it @wurensen ? Any clues ?
> We are facing the same problem after upgrading to latest sdk.

@gurappa Here is the workaround: https://github.com/firebase/firebase-android-sdk/issues/2057#issue-718586498 
It's work for me.

**Comment by charleston10** [comment]
https://github.com/firebase/firebase-android-sdk/issues/1987

**Comment by mrwillis21** [comment]
Hi @wurensen is this still an issue for you? If so, can you give us a little more info about how you're setting up Proguard/R8 in your `build.gradle`?
