### ISSUE TITLE
sendEmailVerification() with ActionCodeSettings doesn't send email

### ISSUE THREAD

**Issue by baole** [firebase/firebase-android-sdk#206]
We are using Firebase Email login and try to send an email verification in which after a user clicks on  the verification link, they will be redirected to the Android app.

Here is our sample Kotlin code

```
val settings = ActionCodeSettings.newBuilder()
                    .setHandleCodeInApp(false)
                    .setUrl("<our url>")
                    .setDynamicLinkDomain("<our dynamic domain>.page.link")
                    .build()
FirebaseUser.sendEmailVerification(settings)
```

Additional details:
- "our url" is based on an Authorized domains
- "our dynamic domain" is created in Dynamic Links
- We use default email template

We didn't receive any verification email. However, if we called 
`FirebaseUser.sendEmailVerification()`
without ActionCodeSettings, we always received a verification email

What's wrong?

**Comment by baole** [comment]
Any update on this issue?

**Comment by samtstern** [comment]
cc @malcolmdeck

**Comment by baole** [comment]
Any update on this issue?
