### ISSUE TITLE
java.lang.ClassNotFoundException: java.util.concurrent.Flow$Publisher

### ISSUE THREAD

**Issue by csi111** [firebase/firebase-android-sdk#2065]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: 19.0.9 (Perf)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?

When I updated retrofit version from 2.6.1 to 2.9.0, FirebasePerf Task is warned with some exceptions while application is building.

#### Relevant Code:

```
> Task :app:transformClassesWithFirebasePerformancePluginForCbtRelease
java.lang.ClassNotFoundException: java.util.concurrent.Flow$Publisher
java.lang.ClassNotFoundException: java.util.concurrent.Flow$Publisher
java.lang.ClassNotFoundException: java.util.concurrent.Flow$Processor
java.lang.ClassNotFoundException: java.util.concurrent.Flow$Processor
java.lang.ClassNotFoundException: java.util.concurrent.Flow$Subscriber
java.lang.ClassNotFoundException: java.util.concurrent.Flow$Subscriber
```

**Comment by alikn** [comment]
@csi111, thanks for reporting this issue. I tried reproducing it on a blank app but could not. Was wondering if you mind sharing some info in order to help me reproduce?
Here are some of the things which could be helpful. Feel free to skip any of them which you cannot share.

1. Other dependencies of the app (maybe the gradle file)
2. Fireperf gradle plugin version
3. A sample app on which the error could be reproduced
