### ISSUE TITLE
FirebaseAuth, Microsoft Azure AD token expiry and refresh

### ISSUE THREAD

**Issue by Jakebreen** [firebase/firebase-android-sdk#2101]
Hello,

_Platform: Android_

I've noticed when logging in with an OAuthProvider for Microsoft the method `FirebaseAuth::startActivityForSignInWithProvider` the AuthResult returned contains the credential with access token for the Microsoft Graph. However, this token should expire and then how can I refresh that token to continue requests to the Microsoft Graph without asking the user to re-authenticate manually or re-calling that previous method.

I've noticed the method `FirebaseUser::startActivityForReauthenticateWithProvider` but _this is not discreet_.

Can I achieve this with Firebase Authentication? Or is the expectation that this should be handled externally to FirebaseAuth?I

Cheers.

**Comment by samhorlbeck** [comment]
Hi, thanks for reaching out.

Your understanding is correct---Firebase Auth does not pass through the refresh token ([more details in this StackOverflow response](https://stackoverflow.com/questions/57031125/firebase-auth-with-microsoft-graph-accesstoken)).

The standard response for many OAuth providers is to handle login manually with the provider, then call `signInWithCredential`. Unfortunately it looks like that's [not an option for Microsoft](https://firebase.google.com/docs/auth/android/microsoft-oauth#expandable-1).

I'm sorry I don't have a better answer for you on this one.
