### ISSUE TITLE
Duplicate class when using BoM

### ISSUE THREAD

**Issue by gwoodhouse** [firebase/firebase-android-sdk#2103]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component:  25.12.0 BoM
  * Component version: 24.1.0

#### Steps to reproduce:

Create a blank project with a simple blank activity, which only contains the following two implementations, and try and build the app in Android Studio.

Results in duplicate class errors such as this:
```
Duplicate class com.google.android.gms.internal.vision.zze found in modules jetified-play-services-vision-20.0.0-runtime (com.google.android.gms:play-services-vision:20.0.0) and jetified-play-services-vision-common-19.1.0-runtime (com.google.android.gms:play-services-vision-common:19.1.0)
```

(jetifier to false makes no difference `android.enableJetifier=false`)
#### Relevant Code:

```
dependencies {
    implementation platform('com.google.firebase:firebase-bom:25.12.0')
    implementation "com.google.firebase:firebase-ml-vision"
}
```

Full example in this SO post - https://stackoverflow.com/questions/64502154/duplicate-class-in-firebase-common-and-jetified-firebase-components-with-library - Includes debugging information

**Comment by eduwhaaat** [comment]
I got the same error? Trying to fix it since yesterday ... Any solutions?

**Comment by yifanyang** [comment]
Here is a [workaround](https://firebase.google.com/support/release-notes/android#mlkit-self-serve-fixes) from Firebase doc. Does it work for you?

**Comment by TomStoffen** [comment]
I have the same issue. Tried the workaround and many other potential solutions - nothing seems to fix it.

**Comment by davidmotson** [comment]
Thank you for reporting this error. It should be fixed in the newer version of the BoM. Feel free to reopen this if it updating doesn't solve your prolem.
