### ISSUE TITLE
No signature of method: build_*.android() is applicable for argument types

### ISSUE THREAD

**Issue by aliyazdi75** [firebase/firebase-android-sdk#2118]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: Crashlytics
  * Component version: Bom-26.0.0

#### Steps to reproduce:

I am using Flutter and NDK supported.
My project works property with the Kotlin Plugin version.
I used the following codes from https://firebase.google.com/docs/crashlytics/ndk-reports
```
android {

    ndkVersion '21.3.6528147'

    buildTypes {
        release {
            signingConfig signingConfigs.release
            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
            firebaseCrashlytics {
                // Enable processing and uploading of native symbols to Crashlytics servers.
                // By default, this is disabled to improve build speeds.
                // This flag must be enabled to see properly-symbolicated native
                // stack traces in the Crashlytics dashboard.
                nativeSymbolUploadEnabled true
            }
        }
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:26.0.0')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ndk'
}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
```
but it goes to this Gradle error when I run Gradle on step 3:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_d8x6vzm4zppddwswq012dxidd.android() is applicable for argument types: (build_d8x6vzm4zppddwswq012dxidd$_run_closure2) values: [build_d8x6vzm4zppddwswq012dxidd$_run_closure2@20ed0a07]
```
When I remove `firebaseCrashlytics` bloc it will be ok.

**Comment by yberstad** [comment]
I'm having the exact same issue in my React Native app. @aliyazdi75 did you find any solution?

I'm running: 
- Android Studio 4.1
- RN 63.3
- classpath 'com.android.tools.build:gradle:4.1.0' (android/app/build.gradle)
- distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-all.zip (android/gradle/wrapper/gradle-wrapper.properties)
- "@react-native-firebase/crashlytics": "^8.4.12" (package.json)

**Comment by aliyazdi75** [comment]
@yberstad 
Just remove firebaseCrashlytics bloc for temporary solution.

**Comment by yberstad** [comment]
@aliyazdi75, thanks for getting back to me. 

I noticed the same, but then I will not get any _"properly-symbolicated native stack traces in the Crashlytics dashboard"_. 
Then again, that's maybe a minor issue?

**Comment by aliyazdi75** [comment]
@yberstad 
Yes, we didn't really implement native stack traces in Crashlytics.
We have to implement as it says after this issue got fixed I think.

**Comment by nikhilbpatil222** [comment]
I Also Got Same Error After Searching So Much In Code i Found Problem in Version Code of my app it was in DECIMAL that's why i got the error after rounding it to integer my error was solved .
HOPE YOU GOT THE RIGHT ANSWER  THANK YOU.

**Comment by vkryachko** [comment]
I assume you've applied the crashlytics plugin to your app's build.gradle?

**Comment by aliyazdi75** [comment]
@vkryachko 
Yes, Sorry for that. I updated it.

**Comment by pasmat** [comment]
For met his was fixed by removing

`
    crashlytics {
        instantAppSupport true
    }`

Not sure yet if crashlytics work on instant apps now or not - can't find any info on this

**Comment by androideveloper** [comment]
For me similar issue was related to kotlin android extensions plugin. After updating Kotlin and removing the plugin, forgot to also remove this 
```
    androidExtensions {
        experimental = true
    }
```

**Comment by mrichards** [comment]
Hey folks, I apologize for this ticket getting so stale, as it didn't get assigned properly. Based on the error message, I believe the resolution is simply to make sure the Crashlytics plugin is applied before the `android` block in the app-level Gradle file. Typically it is applied immediately after the Android Gradle plugin and Google Services plugins are applied, as show in [Step 2.2 of the Getting Started instructions](https://firebase.google.com/docs/crashlytics/get-started?platform=android#add-sdk).

Please reopen the ticket if you are still experiencing problems!

**Comment by aliyazdi75** [comment]
@mrichards
Thanks, it works for me, but I remember the order wasn't like that, but anyway, this is my final gradle:
```gradle
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

dependencies {
    implementation platform('com.google.firebase:firebase-bom:26.7.0')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ndk'
}

android {
    compileSdkVersion 30
    ndkVersion '21.3.6528147'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.matemachine.mate_machine_app"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
            firebaseCrashlytics {
                // Enable processing and uploading of native symbols to Crashlytics servers.
                // By default, this is disabled to improve build speeds.
                // This flag must be enabled to see properly-symbolicated native
                // stack traces in the Crashlytics dashboard.
                nativeSymbolUploadEnabled true
                strippedNativeLibsDir 'build/intermediates/stripped_native_libs/release/out/lib'
                unstrippedNativeLibsDir 'build/intermediates/merged_native_libs/release/out/lib'
            }
        }
    }
}
```

**Comment by mrichards** [comment]
Glad you got it working @aliyazdi75!

Note that you should remove the `strippedNativeLibsDir` property as it is no longer used by the plugin and will be removed at a later date. You will still need the `unstrippedNativeLibsDir` property if you are continuing to override the default unstripped libs location.
