### ISSUE TITLE
FirebaseFunctions OkHttpClient timeout too short

### ISSUE THREAD

**Issue by retNull** [firebase/firebase-android-sdk#212]
## The Problem

The default OkHttpClient timeout of 10 seconds is too short when cold-booting functions. This becomes more evident when using Flutter where shoddy mobile connections are abundant.

## What feature would you like to see?

Either set a default timeout of something greater than 10 seconds (30 seconds?), or, provide a way for users to edit these values:

client.setConnectTimeout(timeout, TimeUnit.SECONDS);
client.setReadTimeout(timeout, TimeUnit.SECONDS);

## How would you use it?

We would be able to use this feature in our Flutter apps, instead of rolling our own http calls.

**Comment by samtstern** [comment]
@retNull thanks for filing this!  We are already tracking this issue internally and there's an API proposal in progress to make it configurable.

No set timeline for release.

**Comment by ahaverty** [comment]
@samtstern this has become a major issue for our Android customers.
The fact that functions are even taking this long is the real issue, but having this increased in Android would at least prevent a lot of our current Android errors and complaints.

**Comment by ahaverty** [comment]
@retNull It looks like this was merged a while back https://github.com/firebase/firebase-android-sdk/pull/224
@samtstern @bklimt am I right in saying that PR fixes this issue?

**Comment by samtstern** [comment]
@ahaverty whoops thanks for pointing that out.  Yes it does.
