### ISSUE TITLE
Dynamic link not working when sharing on facebook in React Native Firebase .

### ISSUE THREAD

**Issue by ravi123saxena** [firebase/firebase-android-sdk#2122]
Dynamic link not working when sharing on facebook in React Native Firebase . when  dynamic link sharing to facebook it shows me "invalid dynamic link." but twitter working fine.

**Comment by christibbs** [comment]
Internal bug number 174063606.

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
