### ISSUE TITLE
Data is not writing on cloud firestore

### ISSUE THREAD

**Issue by jayeshghare** [firebase/firebase-android-sdk#2123]
I write valid code to send data to cloud firestore, android studio doesn't even giving any error even application working fine. i also checked my android device network connection it is fine still firestore not receiving any data.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: Firestore
  * Component version: 22.0.0

#### Relevant Code:
MainActivity.java
```
package com.example.firebasefirestore;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.HashMap;
import java.util.Map;

public class MainActivity extends AppCompatActivity {

    private Button submit;
    private EditText title;
    private EditText thought;
    private TextView textView;
    FirebaseFirestore db = FirebaseFirestore.getInstance();
    public static final String KEY_TITLE="title";
public static final String KEY_THOUGHT="thought";
public static final String TAG="TAG";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        submit=findViewById(R.id.submit);
        title=findViewById(R.id.title);
        thought=findViewById(R.id.thought);
        textView=findViewById(R.id.textview);
        submit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String titlestring=title.getText().toString().trim();
                String thoughtstring=thought.getText().toString().trim();

                Map<String,Object> data=new HashMap<>();
                data.put(KEY_TITLE,titlestring);
                data.put(KEY_THOUGHT,thoughtstring);

               db.collection("Journal")
                        .document("First Thought")
                       .set(data)
                        .addOnSuccessListener(new OnSuccessListener<Void>() {
                            @Override
                            public void onSuccess(Void aVoid) {
                                textView.setText("Success");
                                Toast.makeText(MainActivity.this,"Success"
                                ,Toast.LENGTH_LONG).show();
                            }
                        })
                        .addOnFailureListener(new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {
                                textView.setText("Failure");
                                Toast.makeText(MainActivity.this,"Failure"
                                        ,Toast.LENGTH_LONG).show();
                            }
                        });





            }
        });



    }
}
```
Build.gradle
`
plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}
apply plugin: 'com.google.gms.google-services'  // Google Services plugin

android {
    compileSdkVersion 29
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.example.firebasefirestore"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.3'
    implementation 'com.google.firebase:firebase-firestore:22.0.0'
    implementation 'com.google.firebase:firebase-core:18.0.0'
    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

`

**Comment by rlazo** [comment]
Hi @jayeshghare sorry for the long delay. Since it's been a while since you reported it, are you still having this issue?
