### ISSUE TITLE
Firebase Storage Realtime Database not opening

### ISSUE THREAD

**Issue by nitin2905** [firebase/firebase-android-sdk#2127]
Trying to open Realtime Database in Firebase storage using Chrome browser. The same is not getting opened and rest others can be accessed.

**Comment by schmidt-sebastian** [comment]
@nitin2905 It sounds like you may be using the firebase-js-sdk. Would you mind filing an issue in https://github.com/firebase/firebase-js-sdk? Please note that we will likely need debug logs or a reproduction and the version of the SDKs you are using.
