### ISSUE TITLE
Crashreports don't appear in Crashlytics console but seemed to be reported from the logs...

### ISSUE THREAD

**Issue by kabamvjudys** [firebase/firebase-android-sdk#2136]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics
  * Component version: com.google.firebase:firebase-crashlytics-ndk:17.2.2

### [REQUIRED] Step 3: Describe the problem

I am trying to make my Android crashes to appear in my app Firebase console.
Here is the attached log that is produced when an app starts up after the crash.
[crashlytics_log3.txt](https://github.com/firebase/firebase-android-sdk/files/5484626/crashlytics_log3.txt)

It seems to me that the request is made and status code 200 indicates that it was successful, but when I go to Crashlytics dashboard for my app, I only see the spinning circle, which I was explained means that the console awaits the data to be processed.

Not sure if that exception is important for this case, this is actually the first time I have seen in, my previous logs did not have it.

**Comment by kabamvjudys** [comment]
I have recently updated my code hoping to resolve the issue on my end. I had run a couple tests with crashing the app and restarting on Monday and here is the log of it attached.
[crashlytics_log4.txt](https://github.com/firebase/firebase-android-sdk/files/5518145/crashlytics_log4.txt)
Today, I was hoping to see some meaningful crash information on Crashlytics dashboard, but I only see the charts showing activity, but no crash details. See attached images.
![Crashlytics_Dashboard 2](https://user-images.githubusercontent.com/48963849/98691667-e360ac80-2333-11eb-9fd5-f71068ce404b.png)
![Crashlytics_Spinning 2](https://user-images.githubusercontent.com/48963849/98691685-e8bdf700-2333-11eb-968e-abcdd41f556e.png)
I don't know what else could be done on my end to have the crash details to appear in the console.

**Comment by mrwillis21** [comment]
@kabamvjudys Thanks for posting your logs! I think everything here looks like it's behaving properly on the device side. I'm going to take a look and see if there are any issues with the reports being sent once they get to our backend. Also, what device are you testing this on?

**Comment by kabamvjudys** [comment]
@mrwillis21 
Thank you for response.
I am using Samsung Galaxy S9+, model # SM-G965F/DS, Android OS v 10.

**Comment by kabamvjudys** [comment]
@mrwillis21 Are there any news on that? Is there anything I can do on my end to get the crash report details visible in my console?

**Comment by mrwillis21** [comment]
@kabamvjudys Hi there! Your logs indicate that you're testing out an NDK crash. We just released version 17.3.0 of the Crashlytics NDK SDK (release notes: https://firebase.google.com/support/release-notes/android#crashlytics-ndk_v17-3-0) which includes some major updates to how our native crash reporting works. Can you give that version a shot (along with the updated Crashlytics Gradle plugin version 2.4.1) and let me know if it solves your problem? Thanks!

**Comment by kabamvjudys** [comment]
Thank you @mrwillis21.
I had just updated Gradle plugin to 2.4.1. We use BOM for packages, so it should be pulling the latest Crashlytics NDK SDK already, am I right?
I had made a build and crashed my app a few times. So far I don't see the crash reports appearing in the console, but I know it can take time, so I'll wait until morning and check again.

**Comment by kabamvjudys** [comment]
@mrwillis21 
I have checked my console and see 1 report from 11/20, and it is not on the release that I am trying to track. 
None of the reports from my release appeared.
Interestingly, that I was not testing a Shipping configuration of my App, but the reported crashes came from the build we did separately, but in Shipping configuration. Could that be a reason?

**Comment by kabamvjudys** [comment]
I see some reports coming from our previous and current builds. None of the reports have call stacks in them, but I believe that we are building and submitting the symbols. How can I double check that the symbols are properly submitted and that Crashlytics service got them all right?

**Comment by mrwillis21** [comment]
@kabamvjudys If you're using Firebase BOM 26.1.0, it will bring in the correct version of the Crashlytics NDK SDK. I would check that first, because if you're not on the right version, then that could be the problem.

That said, if you could submit a case using https://firebase.google.com/support/troubleshooter/contact and send us a link to some crashes that are appearing in your dashboard (even if they're missing stacks), we can dig in further on our end to help determine what might be amiss, and see whether your symbols have been submitted correctly. :)

In the future, if you run your symbol upload with debugging enabled, you can see whether symbols are being uploaded properly: `./gradlew crashlyticsUploadSymbolFileRelease --debug | grep "\[com.google.firebase.crashlytics\]"`
