### ISSUE TITLE
[dynamiclinks] Please handle custom parameter and fragment from shortlink

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-android-sdk#2138]
## What feature would you like to see?

Using shortlink url is easy and obvious method to open the app. However it seem like in android, there was some process that remove query parameter and fragment from shortlink before redirection. Rendering this feature to be very limited usage

So I would like to propose that, firebase dynamiclinks system should always pass every non firebase specific parameters to open android app. (I have heard that this behavior is not occur in IOS) or at least has some mechanism to construct forwarded link with query and fragment of the shortlink url

One possibility is to have forwarded url can define injected parameter

Suppose we create url as `example.page.link/user`
that would forwarded to `www.myexample.com/user?uid={{id}}&code={{#}}#{{page}}` (specify this link in firebase console link creation)

If we then construct a link like this > `example.page.link/user?id=123456&page=about#ABCDEFG`
Then it would become link forwarded to `www.myexample.com/user?uid=123456&code=ABCDEFG#about` into the app

## How would you use it?

As you can see, we can reuse shortlink to open the same page but can handle parameter. Such as open another user info page for social. Or request custom action at the app

Is it already possible or we have any other workaround though? Because creating custom manual long link is tedious and unsafe and it's not a link that could be shared easily

**Comment by joshsharrad** [comment]
I would LOVE this feature. Would be useful to use with Google App Script.

It would allow us to shorten the Google App Script link and still pass through the parameters.

Currently we have to change our Google App Script link in multiple places when we release a new version, being able to pass through parameters means we could change it in firebase dynamic links and it would change everywhere!

**Comment by build3r** [comment]
This will be very useful feature. 
Currently we create a single dynamic link for our partners, but due to query parameter being dropped during redirection the partner can't share simple data via the URL.
A simple query parameter forwarding feature or at-least passing the original URL clicked would be very helpful.

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
