### ISSUE TITLE
Firebase Crashlytics: failed for task ':news:uploadCrashlyticsMappingFileRelease'

### ISSUE THREAD

**Issue by leotyndale** [firebase/firebase-android-sdk#2145]
![image](https://user-images.githubusercontent.com/13491298/98211496-19d9a880-1f7d-11eb-83b7-5251363f6dce.png)

Hello, our team has been unable to perform local packaging after using Firebase Crashlytics. Every time we start packaging, we will receive a prompt that Firebase failed to upload the mapping file, but our mapping file has not been generated yet, which causes this problem. It’s because FireBase uploads the mapping file too early. What should I do?

**Comment by leotyndale** [comment]
firebase Crashlytics Plugin Version :'2.1.1',
firebase Crashlytics Version : '17.0.1'

**Comment by KalaiSelvanG** [comment]
Any update on this issue? 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':APP:uploadCrashlyticsMappingFileRelease'.
> Crashlytics could not find the resource file generated by Google Services. You may need to execute the :process<Variant>GoogleServices Task. Please check your Firebase project configuration (https://firebase.google.com/docs/android/setup).

**Comment by leotyndale** [comment]
Hello, is there any progress on this question?

**Comment by KalaiSelvanG** [comment]
@leotyndale try add this on app gradle

gradle.taskGraph.whenReady {
    tasks.each { task ->
        if (task.name.contains("uploadCrashlyticsMappingFile")) {
            task.enabled = false
        }
    }
}

**Comment by leotyndale** [comment]
> @leotyndale try add this on app gradle
> 
> gradle.taskGraph.whenReady {
> tasks.each { task ->
> if (task.name.contains("uploadCrashlyticsMappingFile")) {
> task.enabled = false
> }
> }
> }

@KalaiSelvanG Thank you for your suggestion, but this may cause Firbase Crashlytics to fail to parse out the correct number of code lines and class name.

**Comment by KalaiSelvanG** [comment]
@leotyndale not sure about that will fail or not. As of now this is the one helps to me to assemble the release and I can able to reports with appropriate line numbers and class names

**Comment by leotyndale** [comment]
@KalaiSelvanG 
Thank you, your code is very helpful and can solve my problem. 
At the same time, I saw another idea from other developers. #2057 

I changed a part of the code and plan to try again.

`afterEvaluate {
    Task uploadMappingTask = tasks.findByName("uploadCrashlyticsMappingFileRelease")
    if (uploadMappingTask != null) {
        println "find uploadMappingTask"
        Task packageTask = tasks.findByName("packageRelease")
        if (packageTask != null) {
            println "find packageTask"
            uploadMappingTask.mustRunAfter(packageTask)
        }

        Task packageBundleTask = tasks.findByName("packageReleaseBundle")
        if (packageBundleTask != null) {
            println "find packageBundleTask"
            uploadMappingTask.mustRunAfter(packageBundleTask)
        }
    }
}`

**Comment by KalaiSelvanG** [comment]
@leotyndale did that worked?

**Comment by leotyndale** [comment]
> @leotyndale did that worked?

@KalaiSelvanG Sorry I just saw, It's ok so far.

**Comment by harry248** [comment]
We get the same error since yesterday. Is this related to the Google Outage?

`Execution failed for task ':app:uploadCrashlyticsMappingFileDevelopmentRelease'.
> java.io.IOException: Unknown error while sending file, check network [/Users/runner/work/1/s/app/build/crashlytics/DevelopmentRelease/mappings/6793dea943b640f9a460764e5d01ea54.gz; response: 500 HTTP/1.1 500 Internal Server Error]`

**Comment by fallGamlet** [comment]
It's error may be when in Firebase Crashlytics not enabled for the project yet

**Comment by fallGamlet** [comment]
> It's error may be when in Firebase Crashlytics not enabled for the project yet

![изображение](https://user-images.githubusercontent.com/7059877/102213089-e6286180-3ede-11eb-998f-ca9696a21635.png)

After enable Crashlytics in Firebase project It's error is gone

**Comment by harry248** [comment]
> It's error may be when in Firebase Crashlytics not enabled for the project yet

Nope. We didn't change anything at all and our builds are failing now. Other users are reporting the same issue (see https://github.com/firebase/firebase-android-sdk/issues/2234#issuecomment-745245491)

**Comment by fallGamlet** [comment]
> > It's error may be when in Firebase Crashlytics not enabled for the project yet
> 
> Nope. We didn't change anything at all and our builds are failing now. Other users are reporting the same issue (see [#2234 (comment)](https://github.com/firebase/firebase-android-sdk/issues/2234#issuecomment-745245491))

Just check the flag enabled on Crashlytics settings in Firebase project. For my case in my project app has been added long time ago, but Gradle build start throw error only from today

**Comment by k-farhan** [comment]
> > > It's error may be when in Firebase Crashlytics not enabled for the project yet
> > 
> > 
> > Nope. We didn't change anything at all and our builds are failing now. Other users are reporting the same issue (see [#2234 (comment)](https://github.com/firebase/firebase-android-sdk/issues/2234#issuecomment-745245491))
> 
> Just check the flag enabled on Crashlytics settings in Firebase project. For my case in my project app has been added long time ago, but Gradle build start throw error only from today

Same here, the Crashlytics was enabled at least 2 years ago and we can see non-fatal crashes every after few days, so this assumption is not valid about Firebase Crashlytics being disabled.

**Comment by harry248** [comment]
> > > It's error may be when in Firebase Crashlytics not enabled for the project yet
> > 
> > 
> > Nope. We didn't change anything at all and our builds are failing now. Other users are reporting the same issue (see [#2234 (comment)](https://github.com/firebase/firebase-android-sdk/issues/2234#issuecomment-745245491))
> 
> Just check the flag enabled on Crashlytics settings in Firebase project. For my case in my project app has been added long time ago, but Gradle build start throw error only from today

You're right - we use flavor specific firebase projects and for that specific project Crashlytics indeed wasn't activated yet. That wasn't a problem until yesterday so maybe they just made it more verbose on their side.

**Comment by k-farhan** [comment]
> > > > It's error may be when in Firebase Crashlytics not enabled for the project yet
> > > 
> > > 
> > > Nope. We didn't change anything at all and our builds are failing now. Other users are reporting the same issue (see [#2234 (comment)](https://github.com/firebase/firebase-android-sdk/issues/2234#issuecomment-745245491))
> > 
> > 
> > Just check the flag enabled on Crashlytics settings in Firebase project. For my case in my project app has been added long time ago, but Gradle build start throw error only from today
> 
> You're right - we use flavor specific firebase projects and for that specific project Crashlytics indeed wasn't activated yet. That wasn't a problem until yesterday so maybe they just made it more verbose on their side.

yeah, just checked. Apologies.

**Comment by Cge001** [comment]
gradle.taskGraph.whenReady {
    tasks.each {
        task ->
            if (task.name.contains("uploadCrashlyticsMappingFile")) {
                task.enabled = false
            }
    }
}

watch out the 'tasks'.each, not 'task.each'...

**Comment by mrichards** [comment]
@ leotyndale & @Cge001 We've recently changed how the Crashlytics task dependencies are defined, which may have helped this issue. Are you still seeing the build failure with the latest version of the Crashlytics Gradle plugin (2.6.1)? If so, please provide the debug logging output from the Crashlytics plugin, using a command like this:

`> ./gradlew  app:assembleRelease --debug | grep "\[com.google.firebase.crashlytics\]"

**Comment by leotyndale** [comment]
> @ leotyndale＆@ Cge001我们最近更改了Crashlytics任务依赖项的定义方式，这可能有助于解决此问题。您是否仍在使用最新版本的Crashlytics Gradle插件（2.6.1）看到构建失败？如果是这样，请使用以下命令提供Crashlytics插件的调试日志记录输出：
> 
> `> ./gradlew app:assembleRelease --debug | grep "\[com.google.firebase.crashlytics\]" `

Sorry, the time is too far away. This problem appeared in the code of my last company. I have resigned from the last company this year and cannot debug the code. Thank you for your help.

**Comment by mrdishant** [comment]
Error: "Crashlytics could not find Google Services plugin task: processReleaseGoogleServices. Make sure com.google.gms.google-services is applied BEFORE com.google.firebase.crashlytics. If you are not using the Google Services plugin, you must explicitly declare `googleServicesResourceRoot` inputs for Crashlytics upload tasks."

I had something like this in build.gradle

apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'


changed it to this and voila! it works:

apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
