### ISSUE TITLE
Bug: "GaiException: android_getaddrinfo failed:...." , claiming my app doesn't have Internet permission

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [firebase/firebase-android-sdk#2152]
### [READ] Step 1: Are you in the right place?
I was told via Firebase team to write here, so I hope I am :)

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____
    implementation 'com.google.firebase:firebase-crashlytics-ktx:17.2.2'
    implementation 'com.google.firebase:firebase-analytics-ktx:18.0.0'

### [REQUIRED] Step 3: Describe the problem
Here:
https://www.reddit.com/r/android_devs/comments/jp1s3i/recently_i_keep_getting_firebase_crashes_of/

#### Steps to reproduce:
This is a crash report from users, but according to the logs, they probably just install the app, and for some reason the OS claims the app misses Internet connection.

#### Relevant Code:
Nothing special about Firebase. Haven't changed anything recently about it. Maybe updated the dependencies.

If you wish to check the crash, here:
https://console.firebase.google.com/u/0/project/app-manager-cdf2c/crashlytics/app/android:com.lb.app_manager/issues/5479dbe91f2814f74a8fe70fdcc4e983?time=last-seven-days&sessionEventKey=5FA46DBE019C00011FFEF04C4A81A1B7_1470199596377614575

Attached video too:
[WpulmjP2H5.zip](https://github.com/firebase/firebase-android-sdk/files/5500936/WpulmjP2H5.zip)

And full logs from one of the sessions:

[logs.zip](https://github.com/firebase/firebase-android-sdk/files/5500935/logs.zip)

**Comment by AndroidDeveloperLB** [comment]
@google-oss-bot What's "triage" mean here? Marking of urgency ?

**Comment by mrwillis21** [comment]
Hi @AndroidDeveloperLB sorry for the radio silence! This looks like it might be an issue with OkHttp - a dependency we recently [removed](https://firebase.google.com/support/release-notes/android#crashlytics_v17-3-1). Can you try updating to Crashlytics 17.3.1 and see if that helps? Thanks!

**Comment by AndroidDeveloperLB** [comment]
@mrwillis21 I'm using this since the date of 2021-2-6, which is on v5.4 (version code 440) of my app ([here](https://play.google.com/store/apps/details?id=com.lb.app_manager)), and I still see this GaiException.

Play Console ([here](https://play.google.com/console/u/0/developers/7235900666503041581/app/4975755565900227263/vitals/crashes/b5737f59/details?days=30&versionCode=440)) :
![image](https://user-images.githubusercontent.com/5357526/107700975-ebc4dc80-6cc0-11eb-8779-0003508c8b82.png)

See video about it:
[n1VLwAodA9.zip](https://github.com/firebase/firebase-android-sdk/files/5968623/n1VLwAodA9.zip)


I don't see it on Firebase Crashlytics though for some reason.

**Comment by mrichards** [comment]
Hi @AndroidDeveloperLB if this is still occurring with the latest Crashlytics SDK, can you re-post the logcat here with `VERBOSE` debugging for the `FirebaseCrashlytics` tag? We have improved our debugging logging since you originally posted the issue, which may help us find a resolution (assuming it wasn't the OkHttp fix previously mentioned).

**Comment by AndroidDeveloperLB** [comment]
@mrichards Well, not the exact crash link, but something that seems identical :
https://console.firebase.google.com/u/0/project/app-manager-cdf2c/crashlytics/app/android:com.lb.app_manager/issues/d8fd2edef6b0b0ab333bd39b7ee1286d?time=last-ninety-days&sessionEventKey=60D9B99E00FB000170837D5E4145E3E8_1557258789430129345

As for logs, just like before, it's a Crashlytics log that I've reported. Meaning it's from real users.

See attached instead

[info.zip](https://github.com/firebase/firebase-android-sdk/files/6851472/info.zip)

There are also some crashes I've found of GMS (related to "DynamiteModule") . Can you please tell if it's ok to report those here?

**Comment by HungTDO** [comment]
I had the same bugs. Are there any updates?

**Comment by yccheok** [comment]
I think they might be the same issue - https://github.com/firebase/firebase-android-sdk/issues/2233

**Comment by mrober** [comment]
As far as we know this is not happening on the current version of the SDK. Given the narrow scope of the initial bug, we're going to close the issue. Please file a new issue if this persists on the latest SDK.

**Comment by AndroidDeveloperLB** [comment]
@mrober Thank you.
I hope that indeed it got fixed.
Do you know by any chance where should I write about crashes that are due to GMS and/or Admob ?
