### ISSUE TITLE
SERVICE_UNAVAILABLE for users on WearOS connected to an iPhone

### ISSUE THREAD

**Issue by littleariel** [firebase/firebase-android-sdk#2155]
### Describe your environment

                firebase_analytics: "17.6.0",
                firebase_ads: "19.4.0",
                firebase_perf: "19.0.9",
                firebase_messaging: "20.3.0",
                firebase_crashlytics: "17.2.2",
                firebase_plugins: "1.1.5",
                firebase_inappmessaging: "19.1.1",
                firebase_config: "19.2.0",
                firebase_appindexing: "19.1.0",

### Describe the problem

Hi,

We are getting user reports that Firebase.getInstanceId() is failing on WearOS devices connected to iPhones with error code SERVICE_UNAVAILABLE. The WearOS update causing the error was identified as the one below:

Wear OS: 2.19
Home App 2.39.0.3390011383 (update appears to have been released on oct 29th)
Google Play Services: 20.39.15

This issue is NOT present with Home App 2.39.0.3335555561.

#### Steps to reproduce:

To reproduce the issue, just set up a WearOS device with the versions indicated in this bug report, pair it to an iPhone device, then call Firebase.getInstanceId() and notice the error.

This is critical as it prevents the use of most Firebase services on this device combo.

**Comment by rlazo** [comment]
HI @littleariel do you still see this issue when using HomeApp 2.41?

**Comment by littleariel** [comment]
Hi @rlazo 2.41 did partially fix the issue and resolved the SERVICE_UNAVAILABLE but Firebase push notifications remained broken until iOS Wear OS app v.3.29.52 and Home v2.43.0.344410213, though do note it required users to uninstall and re-install the app. This issue was resolved directly with Google (feel free to reach out to me privately if you need more info!).

This issue can be closed now.

**Comment by rlazo** [comment]
Thanks for the update @littleariel !
