### ISSUE TITLE
[firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ Chain validation failed ]

### ISSUE THREAD

**Issue by Aklamzeeerrrr** [firebase/firebase-android-sdk#2157]
Hello dear all,
I have a firebase authentication error and I don't really know the cause.
Can you please help me?
Here is the message: [firebase_auth/unknown] com.google.firebase.firebaseException: An internal error has occurred. [ Chain validation failed ]
![Capture d’écran (186)](https://user-images.githubusercontent.com/54205051/98444933-951d9480-210c-11eb-99f0-917050857fe0.png)

**Comment by malcolmdeck** [comment]
Huh, this appears to be because of an X509 certificate chain validation failure. Can you please tell me under what circumstances you were able to get this error to appear?
