### ISSUE TITLE
Open source code for firebase analytics (com.google.firebase:firebase-analytics)

### ISSUE THREAD

**Issue by AbhishekTaparia** [firebase/firebase-android-sdk#2159]
## What feature would you like to see?

I want to know if the source code of firebase-analytics is open or not. I couldn't find it in this repo or any where else.

## How would you use it?

I wanted to know the working and flow of the api's available in the firebase-analytics. It's just weird that all the codes are available except analytics.

**Comment by raphael-anydo** [comment]
me++

**Comment by riccardo91** [comment]
up

**Comment by Scino** [comment]
Same here

**Comment by davidmotson** [comment]
The source code for analytics is not currently open source. That may change in the future, and if it does, it will be announced.
