### ISSUE TITLE
[firebase-auth] AuthStateListener not called when upgrading from anonymous user to real user with linkWithCredential method

### ISSUE THREAD

**Issue by NitroG42** [firebase/firebase-android-sdk#2160]
### Step 2: Describe your environment

  * Android Studio version: 4.2-canary16
  * Firebase Component: Authentication
  * Component version: 20.0.0

### Step 3: Describe the problem

From https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.AuthStateListener
We can read that the listener should be called when:

> When the current user changes

On our project, we make an anonymous user ```firebaseAuth.signInAnonymously()```, and then upgrade it to a real user using:
```firebaseAuth.linkWithCredential(EmailAuthProvider.getCredential(email, password))```.
I agree that the user doesn't change completly, but one thing did change: [currentUser.isAnonymous()](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#isAnonymous()) now returns false ! 

#### Steps to reproduce:

- Register an authlistener
- Make an anonymous User (listener should be called)
- Upgrade the user to a real one
-> Listener not called

**Comment by malcolmdeck** [comment]
This is working as intended - linking a user does not change its UID, so it does not trigger the AuthStateListener. 

If you're interested in checking for the completion of the upgrade, use the `#onCompleteListener()` of the linking operation. You can also take a look at [IdTokenListener](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.IdTokenListener), which will trigger when your linking operation happens, but will also trigger whenever the token is refreshed.
