### ISSUE TITLE
Fatal Crashes are not appearing in dashboard on Release build

### ISSUE THREAD

**Issue by Smbat888** [firebase/firebase-android-sdk#2163]
###  I've migrated from Fabric to Firebase Crashlytics new SDK and fatal crashes are not appearing in dashboard on release build.

  * I have followed to the official documentation to migrate from Fabric to Firebase Crashlutics. 
  * I haven't used Manifest collectionEnabled meta-data.
  * I have not any Thread.setDefaultUncaughtExceptionHandler in the code.
  * I have uploaded the latest google-services.json.
  * I have used the following in the app level build.gradle file but no effect.
           firebaseCrashlytics {
                mappingFile("build/outputs/mapping/release/mapping.txt")
                mappingFileUploadEnabled true
            }
   * I've added the following on the Proguard config file:
          # Firebase
         -keepattributes *Annotation*
         -keepattributes SourceFile,LineNumberTable
         -keep public class * extends java.lang.Exception
         -keep class com.crashlytics.** { *; }
         -dontwarn com.crashlytics.**
         -keep class com.google.firebase.** { *; }
         -dontwarn com.google.firebase.**

### The versions.

  * Android Studio version: _____ 4.0
  * Firebase Analytics version: _____ 'com.google.firebase:firebase-analytics:18.0.0'
  * Firebase Crashlytics version: _____ 'com.google.firebase:firebase-crashlytics:17.2.2'
  * Firebase plugin version: _____ 'com.google.firebase:firebase-crashlytics-gradle:2.3.0' 

### Problem Description.

I'm seeing the non-fatal issues are correctly reporting in the Firebase console but the fatals/runtime exceptions aren't!
Can you please help to figure out on this?
I've tried different steps... even downgrading the version but it doesn't help.. maybe I'm missing something.

**Comment by mrwillis21** [comment]
Hi @Smbat888, can you please try the instructions [here](https://github.com/firebase/firebase-android-sdk/issues/1944#issuecomment-706385711) and post your logs? Thanks!

**Comment by Smbat888** [comment]
hi, Thanks for the response, I really need help :)

I'm seeing these logs when recordException method is called, and I can confirm that I see the logs on the Firebase console...
the main issue is: I see only non-fatal issues, but can't see fatal issues (runtime crashes). For example when my app crashes on a null pointer exception I expect that that fatal issue will be reported on the Firebase console, as Fabric did, but can't see it (also can't see it in the logcat)

2020-11-10 13:18:04.670 2213-2263/com.mmm.trebelmusic D/TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
2020-11-10 13:18:04.685 2213-2263/com.mmm.trebelmusic D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-1210830453 in 1000ms(Backend next call timestamp 1604998167571). Attempt 1
2020-11-10 13:18:07.803 2213-2263/com.mmm.trebelmusic D/TransportRuntime.CctTransportBackend: Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
2020-11-10 13:18:10.159 2213-2263/com.mmm.trebelmusic I/TransportRuntime.CctTransportBackend: Status Code: 200
2020-11-10 13:18:10.159 2213-2263/com.mmm.trebelmusic I/TransportRuntime.CctTransportBackend: Content-Type: application/json; charset=UTF-8
2020-11-10 13:18:10.159 2213-2263/com.mmm.trebelmusic I/TransportRuntime.CctTransportBackend: Content-Encoding: gzip

**Comment by mrwillis21** [comment]
Hi @Smbat888 looks like your crash was uploaded, but I need to see more of your logs to be able to track it down - can you also post the logs from the `FirebaseCrashlytics` tag during this crash, or potentially try again?

**Comment by Smbat888** [comment]
@mrwillis21 ,
Please note, that for non-fatals I see the crashes in the console, but for fatal crashes (for example null pointer exception) I don't see the logs on the logcat and in the firebase console.

I'm seeing only this line of log when I fillter logcat with FirebaseCrashlytics


2020-11-10 19:05:25.430 8664-8664/com.mmm.trebelmusic I/FirebaseCrashlytics: Initializing Crashlytics 17.2.2

**Comment by mrwillis21** [comment]
@Smbat888 Ah, my apologies! I thought it was mentioned in the comment that I linked to, but it looks like it wasn't - you'll need to run `adb shell setprop log.tag.FirebaseCrashlytics DEBUG` to enable debug logging.

**Comment by Smbat888** [comment]
[firebase_crashlytics_log.txt](https://github.com/firebase/firebase-android-sdk/files/5520421/firebase_crashlytics_log.txt)

@mrwillis21 , here is the logs:

I've crashed the app by null pointer, then restarted the app :)

**Comment by Smbat888** [comment]
@mrwillis21 
I've noticed this line in the logs... maybe I'm missing something.. 

Send to Reports Endpoint disabled. Removing Reports Endpoint report.

How can I fix this?

**Comment by Smbat888** [comment]
[firebase_crashlytics_log.txt](https://github.com/firebase/firebase-android-sdk/files/5520515/firebase_crashlytics_log.txt)

@mrwillis21 here is the log file.

Thanks in advance :)

**Comment by Smbat888** [comment]
@mrwillis21 when I'm recording exception by myself, I'm seeing a lot of other logs..
here is the example log file:

[firebase_crashlytics_log_1.txt](https://github.com/firebase/firebase-android-sdk/files/5520517/firebase_crashlytics_log_1.txt)

reporting, sending, etc..

**Comment by Smbat888** [comment]
hi @mrwillis21 , did you have a chance to look at the logs? any idea?

**Comment by KalaiSelvanG** [comment]
@Smbat888 even i had undergone this issue, try following steps
1. Invalidate cache and restart. 
2. Place the json file in right place.
3. Try with some other device.(when I tried to run it on other device, I started getting crash for this device)

**Comment by mrwillis21** [comment]
Hi @Smbat888 - The crash report you submitted in https://github.com/firebase/firebase-android-sdk/issues/2163#issuecomment-725001425 appears to have processed properly - do you see it in your dashboard?

**Comment by Smbat888** [comment]
hi @mrwillis21 , for the #2163 (comment) yes, I'm seeing.. it's standard non-fatal
but for the other one I'm not seeing (when app crashes for example on the null pointer exception, it's a fatal issue and I'm not seeing that one)
Again:  I can confirm that I'm seeing non-fatals on the dashboard, but I'm not seeing the fatals there!

**Comment by Smbat888** [comment]
> @Smbat888 Even I had undergone this issue, try following steps
> 
> 1. Try with firebasecrashlytics 17.2.1 version
> 2. Invalidate cache and restart.
> 3. Place the Json file in right place.
> 4. Try with some other device.(when I tried to run it on other device, I started getting crash for this device)

thanks for the response,
I've tried all these steps. and still not working for fatals (for non-fatals it's working correctly)

**Comment by mrwillis21** [comment]
@Smbat888 I took a look at your logs in https://github.com/firebase/firebase-android-sdk/issues/2163#issuecomment-725000669, and didn't see a crash. For that one, did you crash and restart the app?

**Comment by mrwillis21** [comment]
Hi @Smbat888 I took a look at your log in https://github.com/firebase/firebase-android-sdk/issues/2163#issuecomment-725000669 and didn't see a crash at all - can you post the full log of an app launch/crash/restart so I can see the context?

**Comment by mrwillis21** [comment]
Also @Smbat888 can you try `com.google.firebase:firebase-crashlytics:17.1.1` and see if you see the same behavior? We've had a few scattered reports of this that suggest using that version might help.

**Comment by cvaghela** [comment]
Hey @Smbat888, would you mind reaching to support@fabric.io with a link to this Github issue? We'd like to set up a quick call to understand what's going on here.
