### ISSUE TITLE
Does Firebase Capture repeated Crash 

### ISSUE THREAD

**Issue by rahuljain88** [firebase/firebase-android-sdk#2169]
In Android some time crash occur in loop , until user terminate the app . At that time does Firebase capture every time that Crash or only one time in one session somethings ?

Also , in day i open app 10 times and app gets crash 10 times with same reasons , does it capture 10 times ?

**Comment by mrwillis21** [comment]
Hi @rahuljain88 - when the app crashes, the process is terminated, so I'm not entirely sure what you mean by crashing in a loop. 

Are you referring to crashes that happen on app startup? For example, the user starts the app, it crashes, the user reopens it, and it crashes again? Or something else?

**Comment by rahuljain88** [comment]
Yes , you are right .
I would like to know that how many times Firebase capture that crash .

For example - App open it gets Crash , Again App open it gets Crash , both crash have same reasons . In this case Firebase Capture Crash two times or one times or n number of time whenever i open app .

**Comment by mrwillis21** [comment]
It should capture the crash as many times as it happens. :) Are you seeing different behavior?

**Comment by davidmotson** [comment]
Closing as stale, feel free to re-open if you have further questions.
