### ISSUE TITLE
Firestore - security rules error handling

### ISSUE THREAD

**Issue by drusak** [firebase/firebase-android-sdk#2178]
## What feature would you like to see?

Assume We have several restrictions for curtain users to write some data (Android or iOS app). E.g. chat app - user cannot write messages 
 - if banned, 
 - if already wrote N messages per day,
 - if some other logic...
Currently We have to add same logic on client side in order to check before sending message (check if user banned, or sent too many messages) and show informative Popup about error. If We add more restrictions on Security Rules We'll have to release update of the app in order to add same logic so user can see informative message, but old versions of the app don't know about new rule. So it is not quite useful, because old clients will get general WRITE PERMISSION error from Firestore while sending message with violation of new rule and display some general message (non-informative one).

It would be nice to have an option to return error from security rule back to the clients. Or to allow write error to some other document which will be observed by client. In this case We'll have general solution for error handling when new security rule is added

## How would you use it?

Get specific Error in Callbacks of Firestore while performing add/update/delete of documents (ideally set in security rules). 
If it is not possible We can have some sort of Error document of last command for every user and if security rules violated - update it with custom error code and message.

**Comment by thebrianchen** [comment]
Assigning to Firebase Access on call since this is a feature request for security rules.

**Comment by yuchenshi** [comment]
Thanks for the feature request! Unfortunately, this is not the right avenue for feature requests in Firebase Security Rules. Please head over to https://firebase.google.com/support/troubleshooter/report/features and file a feature request with Firebase Support.
