### ISSUE TITLE
Analytics: significant decline in some Automatic Collected Events 

### ISSUE THREAD

**Issue by raphael-anydo** [firebase/firebase-android-sdk#2179]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: Analytics
  * Component version: firebase-bom:25.12.0, firebase-analytics-ktx

### [REQUIRED] Step 3: Describe the problem

We recently, since mid/end October 2020, have noticed a significant decline in some automatic collected events. Example event: `app_store_subscription_convert `. The number of events has gone from ~150 per day to ~20 per day. We think these events are either not tracked anymore or not correctly counted when viewed in the console.

Some other automatic collected events have not declined such as `screen_view`

*Extra Note:* The firebase project and google play app are correctly linked. 
#### Steps to reproduce:

In the Firebase console, navigate to Analytics Events, select the automatic collected event `app_store_subscription_convert` in the range of the last 90 days. Notice the decline. Select another automatic collected event: `screen_view`. Notice no decline.

**Comment by bobsmits** [comment]
Could this be the same or related to the issue I'm facing?  https://github.com/firebase/firebase-android-sdk/issues/2182 ?

**Comment by raphael-anydo** [comment]
> Could this be the same or related to the issue I'm facing? #2182 ?

@bobsmits  could be, those are also automatic collected events. although in that thread it says that in bom 25.12.0 it works, while on my side that's the version I'm currently using, so not sure it's the same issue but could be related.

**Comment by catman-19** [comment]
Hi @raphael-anydo, sorry for the delay here. 

Upon checking, there was an issue with reporting app_store_subscription_convert events around the same time this issue was filed (internal only: b/172550032). It seems to have been fixed already though. Could you please confirm if you're still seeing any issues with your reports?
