### ISSUE TITLE
Dynamic link default events no longer work.

### ISSUE THREAD

**Issue by bobsmits** [firebase/firebase-android-sdk#2182]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: n.v.t. (using react native)
  * Firebase Component: Dynamic Links + Analytics
  * Component version: Bom 26.0.0.

### [REQUIRED] Step 3: Describe the problem

Firebase Dynamic links no longer sends dynamic_link_app_open and dynamic_link_first_open events. This is what i found in the debug logs:

_11-18 10:20:36.002 E/FA      (17361): Name is reserved. Type, name: event, dynamic_link_app_open
11-18 10:20:36.002 E/FA      (17361): Invalid event name. Event will not be logged (FE): dynamic_link_app_open(dynamic_link_app_open)_

I saw in the firebase android changelog that in Analytics version 18.0.0 reserved names where added. Maybe the fault is introduced there? On bom 25.12.0 it still works, on 26.0.0 it breaks. Edit:  26.1.0 still broken.

#### Steps to reproduce:

Open a dynamic link
Check adb debug logs or the firebase debug vieuw

#### Relevant Code:

I'm using the rn-firebase implementation https://github.com/invertase/react-native-firebase. Their implementation can be found here: https://github.com/invertase/react-native-firebase/blob/master/packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java . 

#### Quick note

I'm using the rn-firebase implementation but the issue is not comming from there. I checked the implementation and they just call the android firebase dynamic links sdk as in the examples. With regard to https://github.com/firebase/firebase-android-sdk/issues/2179 this seems to be a bigger issue.

**Comment by stereodenis** [comment]
Same problem for me

**Comment by stereodenis** [comment]
@bobsmits do you find a way how to make this work on bom 25.12.0 in RN? Cause it blocks us with android

**Comment by bobsmits** [comment]
> @bobsmits do you find a way how to make this work on bom 25.12.0 in RN? Cause it blocks us with android

@stereodenis Hidden because its a bit offtopic:
<details><summary>Unfold</summary>
The following set of packages is working for me:

"@react-native-firebase/analytics": "7.6.8",
"@react-native-firebase/app": "8.4.6",
"@react-native-firebase/crashlytics": "8.4.11",
"@react-native-firebase/dynamic-links": "7.5.10",
"@react-native-firebase/perf": "7.4.9",

The next versions wil bump it to bom 26.0.0 and the dynamic link attribution will break.
</details>

Side node: Even with the downgrated version, where the events are send and received in Firebase with the campaign attribution. I could confirm this with BigQuery. The campaign attribution does not show up in Firebase -> Analytics -> Conversions and Google Analytics. I filed seperate bug for this to Firebase / Analytics.

**Comment by mikehardy** [comment]
@stereodenis hey there, react-native-firebase maintainer here, you'll have to stay on older versions of RNFB in order to use the older BoM because we just added support for the auth emulator which requires APIs that are only present in BoM 26+ on android. If you downgrade react-native-firebase to the versions immediately prior to v10 of react-native-firebase you should be able to use BoM 25.12.0. With apologies I'm not sure exactly which versions they were but the last one before v10 on npmjs.com for each is the one that should work

**Comment by christibbs** [comment]
Internal bug number 174063089.

**Comment by argzdev** [comment]
Upon checking the internal bug link, this is already resolved. Closing as fixed.
