### ISSUE TITLE
Password changes upon phoneauth mobile number update

### ISSUE THREAD

**Issue by ninoM** [firebase/firebase-android-sdk#219]
### [READ] Step 1: Are you in the right place?

Yeap

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.2.1
  * Firebase Component: Firebase Authentication (Database, Firestore, Storage, Functions, etc)
  * Component version: 16.1.0

#### Steps to reproduce:

assuming user has email/password provider ONLY
1. call updatePhoneNumber on user
2. log out
3. log in with same email password
4. firebase auth says wrong password

**Comment by samtstern** [comment]
@ninoM sorry for the really slow response but I tried to reproduce this and was not able:
https://jsfiddle.net/gLx63jc8/2/

I did the following:
  * Sign in as an email user
  * Update that account with a phone number
  * Try to sign in as the same email user

It worked.  Did I miss something?

**Comment by ninoM** [comment]
This might have been fixed already. I can't test this on the original codebase as it was in my previous job so I'm closing this issue.

**Comment by samtstern** [comment]
Thanks @ninoM for the response!
