### ISSUE TITLE
Firebase functions: How to get raw json from the response without internal deserialization by the library?

### ISSUE THREAD

**Issue by Zeliret** [firebase/firebase-android-sdk#2193]
Hello, the question is, how can I call a function and get a raw json response? 
I see that the library returns List or Map with already deserialized values. But I want to deserialize the response with help of kotlin json deserialized into my classes not into Map or List.

**Comment by rlazo** [comment]
Hi @Zeliret, as you mentioned the library returns either a list or a map, and relevant code is this:

https://github.com/firebase/firebase-android-sdk/blob/4f3ffc57bb80d28a622e84cfb348d6b4dba79537/firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java#L366

which calls the `Serializer` to process the raw data

https://github.com/firebase/firebase-android-sdk/blob/4f3ffc57bb80d28a622e84cfb348d6b4dba79537/firebase-functions/src/main/java/com/google/firebase/functions/Serializer.java#L137

before returning it to the client. Currently, there's no way of getting the raw json from the response.
