### ISSUE TITLE
Problem with query param "efr"

### ISSUE THREAD

**Issue by ezefire** [firebase/firebase-android-sdk#2205]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Dynamic Links
  * Component version: 19.1.0

#### Steps to reproduce:

When creating a DynamicLink using 'setForcedRedirectEnabled' and sharing it with Google Calendar, Google Calendar cannot recognise the entirely url to display as a link because the parameter 'efr' (when used in the url as "&efr") is replaced with an 'e' because the code '&efr' is the representation of a special character 'e'.  (INFO: https://www.compart.com/fr/unicode/U+1D508)

For example: https://myapp.page.link/?apn=my.apn&efr=1&ibi=my.ibi&isi=1238674449&link=https://www.mysite.com
is shown as: https://myapp.page.link/?apn=my.apne=1&ibi=my.ibi&isi=1238674449&link=https://www.mysite.com

As we can see te text '&efr' was replaced with 'e'

#### Relevant Code:

```
     DynamicLink dynamicLink = FirebaseDynamicLinks.getInstance().createDynamicLink()
                .setLink(uriBuilder.build())
                .setDomainUriPrefix(FIREBASE_DYNAMIC_LINK_PREFIX)
                // Open links on Android
                .setAndroidParameters(
                        new DynamicLink.AndroidParameters.Builder(MainApplication.getAppContext().getPackageName())
                                .build())
                // Open links on iOS
                .setIosParameters(
                        new DynamicLink.IosParameters.Builder(Const.IOS_BUNDLE_ID)
                                .setAppStoreId(Const.IOS_APP_STORE_ID)
                                .build())
                // Force redirect to store if app not installed
                .setNavigationInfoParameters(
                        new DynamicLink.NavigationInfoParameters.Builder()
                                .setForcedRedirectEnabled(true)
                                .build())
                .buildDynamicLink();
```

**Comment by rlazo** [comment]
Thanks for your report @ezefire `&efr` shouldn't be parsed as `E` since it's not an html entity, as it lacks the closing  semicolon `;` https://developer.mozilla.org/en-US/docs/Glossary/Entity 

For example, https://anothertestprojectrlazo.web.app/?something=else&efr=val works and prints `val`

at which point does it gets converted to `e`?

**Comment by ezefire** [comment]
Hi thanks for your response. I was testing on different devices and as a can see the problem is not in firebase as in different versions of Google Calendar the behavior is different, on newer version it works perfectly. 
Sorry about this issue. I close it.
