### ISSUE TITLE
Crashlytics custom keys are not deleted after sending a non-fatal exception

### ISSUE THREAD

**Issue by romanandreyvich** [firebase/firebase-android-sdk#2210]
### Step 1: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: crashlytics, messaging
  * Component version: Crashlytics v17.2.1 | messaging v17.6.0 

### Step 2: Describe the problem

Crashlytics custom keys are not deleted after sending a non-fatal exception

#### Steps to reproduce:

1. I log some non-fatal exception with additional info (as described here: https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#log-excepts). Here is the function:

```
fun logNonFatalException(e: Exception) {
   if (e is MyCustomException) {
      FirebaseCrashlytics.getInstance().setCustomKey(e.key, e.value)
   }
  
   FirebaseCrashlytics.getInstance().recordException(e)
}
```

Then if any exception else happened, I will see next Crashlytics reports with all of the custom keys I added before.

**Comment by rlazo** [comment]
Hi @romanandreyvich This is WAI. When you set a value, it remains set and it's associated with any subsequent fatal and non-fatal events([ref docs](https://firebase.google.com/docs/reference/android/com/google/firebase/crashlytics/FirebaseCrashlytics#setCustomKey(java.lang.String,%20long))). Since custom keys reflect the state of your app at any given time, you can update them after the non-fatal crash to match the new state.

**Comment by romanandreyvich** [comment]
@rlazo Thanks for the explanation, but how can I remove a custom key? As I can see, there is no api to do that.

**Comment by rlazo** [comment]
You're right, there's no API for that. Setting your key to empty string is the closest we have to it.

**Comment by romanandreyvich** [comment]
Got it, thanks again.

**Comment by romanandreyvich** [comment]
Still doesn't work. Added keys -> record exception -> deleted keys. No keys in Crashlytics because recordException method happens to be async.
@rlazo Docs suggest to use custom keys to add an info about exception. You said that custom keys reflect the state of an app at any given time. But I just need to add custom info about my exception, not set state of my application. Overall I feel custom keys shouldn't be used to transfer additional info about exceptions.

**Comment by rlazo** [comment]
Hi @romanandreyvich my explanation was confusing, sorry about that.  What I meant by _"reflect state of your app at any given time"_ is that custom keys values only change when your code explicitly changes them, there are no automatic processes modifying them.  

I'll get back to you about the issue with keys missing after reporting the exception.

**Comment by rlazo** [comment]
@romanandreyvich Please confirm if I understood correctly: the issue you're facing right now is that when reporting a non-fatal crash, the value of the custom keys at the time of the report is **not** being preserved. Am I right? If so, please create a new issue so we can track it.

Thanks!

**Comment by romanandreyvich** [comment]
My major problem is that I want to attach custom info to a particular exception and I have no idea how to do that in Crashlytics. Docs suggest to use custom keys so I tried to follow the advice and ended up with that issue: before recording the exception I add custom info using keys. After recording the exception I remove the keys. Since exception recording is async the keys are removed BEFORE the recording happens. I'm not sure I understand what issue should I create exactly? That I can't attach custom info to an exception or that custom keys API doesn't handle that case?
