### ISSUE TITLE
IllegalStateException "expected a file to resume from" when downloading from Firebase Storage

### ISSUE THREAD

**Issue by pflammertsma** [firebase/firebase-android-sdk#2211]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:
Android Studio 4.2 Canary 16
Build #AI-202.7660.26.42.6939830, built on October 29, 2020
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2560M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.thoughtworks.gauge, org.jetbrains.kotlin, org.intellij.plugins.markdown
  * Firebase Components:
    implementation 'com.google.firebase:firebase-core:17.5.0'
    implementation 'com.google.firebase:firebase-storage-ktx:19.2.0'

#### Steps to reproduce:

1. Download a file from Firebase Storage.

#### Expected results:

2. File downloads successfully, or an error is returned.

#### Observed results:

2. On a small number of devices, an IllegalStateException is thrown from within a thread owned by Firebase, which cannot be caught and causes the application to crash:
```
Fatal Exception: java.lang.IllegalStateException: expected a file to resume from.
       at com.google.firebase.storage.FileDownloadTask.processResponse(FileDownloadTask.java:134)
       at com.google.firebase.storage.FileDownloadTask.run(FileDownloadTask.java:227)
       at com.google.firebase.storage.StorageTask.lambda$getRunnable$7(StorageTask.java:1072)
       at com.google.firebase.storage.StorageTask$$Lambda$12.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

#### Relevant Code:

```
val task = Firebase.storage.reference.child(remotePath)
    .getFile(tmpFile)
val result = Tasks.await(task)
```

The exception is thrown from here:  
https://github.com/firebase/firebase-android-sdk/blob/b33927b0bc49914fc136213eb498957dfa7f8eca/firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java#L133

Observe that this exception type is not trapped by the invoker:  
https://github.com/firebase/firebase-android-sdk/blob/b33927b0bc49914fc136213eb498957dfa7f8eca/firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java#L228

**Comment by schmidt-sebastian** [comment]
Thanks for this report. We should probably throw an IOException in this case. I will get this fixed tomorrow.
