### ISSUE TITLE
[Crashlytics NDK] When calling crashlytics C++ function, FirebaseCrashlytics (java) class not found 

### ISSUE THREAD

**Issue by tellypresence** [firebase/firebase-android-sdk#2245]
Background: android project with significant ndk/c++ content originally with fabric crashlytics support, now migrated to firebase crashlytics.

As instructed on page:
https://firebase.google.com/docs/crashlytics/ndk-reports

included C++ header file:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/external/crashlytics.h

in android project, and modified C++ file to add a crashlytics log e.g.
```
using namespace firebase;

void myProj::doSomething(MyCustomObj myCustomObj ) {
    const std::string logMsg = "doSomething(): " + myCustomObj.someStringValue();
    crashlytics::Log(logMsg.c_str());
    ...
```

But shortly after (debug, no proguard etc obsfucation) app launch get crash with error:
```
java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.crashlytics.FirebaseCrashlytics" 
on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/product/lib64, 
/system/lib64, /system/product/lib64]]
```

This meta-error, complete with above error message, ends up being reported to firebase crashlytics dashboard.

Anyway this is a strange error, because apk inspector shows crashlytics .so libs in the apk; not sure why it can't locate the java class.  For legacy fabric crashlytics I was explicitly initializing crashlytics in the Application file; IIUC there is no explicit init required for firebase crashlytics after looking at the upgrade guide.

[Updated to note that this applies to debug build]

**Comment by kmandrika** [comment]
Hi @tellypresence,

Are you using Proguard or Dexguard? The native API mechanism uses reflection to find certain classes; this fails if those classes are obfuscated in any way.

**Comment by ts-stevem** [comment]
No obfuscation -- this is a debug build

**Comment by tellypresence** [comment]
No obfuscation -- this is a debug build (crawl-before-walk etc :sweat_smile:)

**Comment by kmandrika** [comment]
What does the resulting APK's libs/ folder look like? Do you build for all architectures?

**Comment by tellypresence** [comment]
I build for all 4 supported ABIs (`x86`, `x86_64`, `armeabi-v7a`, `arm64-v8a`) but since it's a debug build, only library for attached device is built:
![firebase_crashlytics_issue_apk_contents_anonymized](https://user-images.githubusercontent.com/26958898/101856770-536b8800-3ba9-11eb-9d10-7bc8ae679d39.png)

Logcat output isn't especially instructive; it executes until it hits the crashlytics log call in C++ then aborts with the above error

**Comment by tellypresence** [comment]
Here's the event as it appears after upload to firebase crashlytics dashboard:
![firebase_crashlytics_issue_dashboard_trace](https://user-images.githubusercontent.com/26958898/101862952-94b66480-3bb6-11eb-9c81-5e746f1dc5c7.png)

**Comment by tellypresence** [comment]
More detail with relevant sections expanded
<img width="1285" alt="firebase_crashlytics_ndk_dashboard_expanded_obfuscated" src="https://user-images.githubusercontent.com/26958898/101870584-48265580-3bc5-11eb-9916-b70c767fc124.png">

**Comment by kmandrika** [comment]
@tellypresence what does your build.gradle look like? Specifically, it'd be helpful to see the Firebase-relevant sections.
