### ISSUE TITLE
Getting error for ConfigFetchHttpClient.java:339

### ISSUE THREAD

**Issue by alicancelik** [firebase/firebase-android-sdk#2253]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: RemoteConfig
  * Component version: Firebase version is 17.0.0

#### Steps to reproduce:

My proje written with react-native-cli, it has firebase crashlytics to handling erros. Suddenly i got error which is about ConfigFetchHttpClient and from only one user and user got this error %100 background mode. User's device is  Galaxy XCover4. I put an image to this issue for you. Thank you for your answers
<img width="1224" alt="Screen Shot 2020-12-14 at 12 01 00" src="https://user-images.githubusercontent.com/26031105/102061128-21099700-3e04-11eb-8dfa-affcddafd7a8.png">

**Comment by danasilver** [comment]
Can you paste in your app-level `build.gradle` with the Firebase SDK versions you're using? Seems like there might be a compatibility issue between classes or SDKs leading to the missing method.
