### ISSUE TITLE
I don't see crashes on Firebase Crashlytics dashboard after update SDK to 17.0.0+ version

### ISSUE THREAD

**Issue by Sergey-Kulyk** [firebase/firebase-android-sdk#2265]
## Firebase Crashlytics SDK
2 weeks ago I updated Firebase Crashlytics SDK to the 17.0.0+ version. I am using SDK version 17.3.0. After that, I couldn't see crashes on the Crashlytics dashboard. Instead of I see the red boxed message
> As of November 16, we are only processing crashes from the Firebase Crashlytics Android SDK 17.0.0+. As a result, you will not see new crashes in your dashboard. Learn More

![Screenshot 2020-12-16 at 10 38 47](https://user-images.githubusercontent.com/55493560/102330406-27c61480-3f92-11eb-8da0-990156113fb5.png)

I used [Firebase Crashlytics SDK](https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android&authuser=4) doc for SDK migration. 
I also used **BOM** instead of directly SDK link, but it didn't help me.

Pay attention to my [StackOverflow question](https://stackoverflow.com/questions/65320083/i-dont-see-crashes-on-firebase-crashlytics-dashboard-after-update-sdk-to-17-0-0). 

**Please, help me asap, because it's very important for my project and my future release.**

**Comment by anilkumar416** [comment]
I was able to solve this by simply upgrading my crashlytics library also changed JSON file 
followed the link as you shared
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android&authuser=4

also, make sure to add a crash/bug to see the changes on the firebase console 
 throw RuntimeException("Test Crash") // Force a crash
https://firebase.google.com/docs/crashlytics/test-implementation?authuser=4&platform=android#kotlin+ktx

**Comment by mrwillis21** [comment]
Hi @Sergey-Kulyk - if you're able to force a crash in development, can you please run `adb shell setprop log.tag.FirebaseCrashlytics DEBUG` to enable debug logging in Crashlytics? Then, run `adb logcat -s FirebaseCrashlytics TransportRuntime.SQLiteEventStore TransportRuntime.JobInfoScheduler TransportRuntime.CctTransportBackend TransportRuntime.DefaultScheduler` to show all logs, and then open, crash, and reopen your app? Posting those logs here will help us determine what might be going on.
