### ISSUE TITLE
Firebase is not throwing exceptions when signing in with Facebook button

### ISSUE THREAD

**Issue by Darbmind** [firebase/firebase-android-sdk#227]
Describe your environment

  * Android Studio version:

Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 24, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

  * Firebase Component: Authentication

### [REQUIRED] Step 3: Describe the problem

Currently I'm working on the scenario where a user had already registered an email and password manually and signing in with password provider. After that, signing out and then pressing the Facebook Login button so I expected Firebase to throw the exception of "ERROR_EMAIL_ALREADY_IN_USE" or something like that.

But  mAuth.signInWithCredential(credential).addOnCompleteListener(... never gets called, it just finishes the handleFacebookAccessToken(AccessToken token) method and nothing happens, there is no result anywhere and the user never logs in to Firebase nor throws any exeption. I think that it just keep on waiting for the answer.

I've checked the resultCode in public void onActivityResult(int requestCode, int resultCode, Intent data) method but its "-1" (log in success) since it DOES log me into facebook but it never tries to log in to Firebase.

I've already posted this question in https://stackoverflow.com/questions/54432230/firebase-is-not-throwing-exceptions-when-signing-in-with-facebook-button

But I have no answer yet.

#### Steps to reproduce:

Step 1: Create a user in firebase using email and password.
Step 2: Log out
Step 3: Try to Log in with Facebook button
Step 4: Nothing happens

#### Relevant Code:

    loginButton = view.findViewById(R.id.login_button);
    loginButton.setReadPermissions("email", "public_profile");
    loginButton.setFragment(this);
    loginButton.registerCallback(mCallbackManager, new FacebookCallback<LoginResult>() {
            @Override
            public void onSuccess(LoginResult loginResult) {
                Log.d("DAN", "facebook:onSuccess1111:" + loginResult);
                handleFacebookAccessToken(TOKEN);
            }        
        });

    private void handleFacebookAccessToken(AccessToken token) {

        AuthCredential credential = FacebookAuthProvider.getCredential(token.getToken());
        signInWithFacebook(credential);
    }

    private void signInWithFacebook(AuthCredential credential){

    //IT JUST JUMPS THIS addOnCompleteListener

    mAuth.signInWithCredential(credential)
    .addOnCompleteListener(getActivity(), new OnCompleteListener<AuthResult>() {
    @Override
    public void onComplete(@NonNull Task<AuthResult> task) {
    if (task.isSuccessful()) {
    // Sign in success, update UI with the signed-in user's information
    } else {
    //I WAS GOING TO HANDLE THE ERROR HERE
    // THIS IS NOT WORKING
    }
    }
    });
    }
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // Pass the activity result back to the Facebook SDK
        mCallbackManager.onActivityResult(requestCode, resultCode, data);
    }

**Comment by lsirac** [comment]
Thanks for bringing this to our attention. It should be fixed now.

Can you please confirm that everything is working properly?

**Comment by aguatno** [comment]
Since there haven't been any recent updates here, I am going to close this issue.

@Darbmind   if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.
