### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: lu@afd33d3

### ISSUE THREAD

**Issue by muhammed-amein** [firebase/firebase-android-sdk#2284]
Hello there
I am creating an UBER clone project in flutter using these dependencies 

  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_database: ^4.4.0
  fluttertoast: ^7.1.6
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.13
  http: ^0.12.2
  provider: ^4.3.2+2
  flutter_polyline_points: ^0.2.4
  font_awesome_flutter: ^8.10.0
  animated_text_kit: ^2.5.4
  pinput: ^0.2.6
  toggle_switch: ^0.1.8
  flutter_geofire: ^1.0.3
  firebase_messaging: ^7.0.3
  assets_audio_player: ^2.0.13+1

and while working on the FCM notification when ever I send a notification from my postman if the app is running in the background am hearing the notification alert  with the popup in my notification center but when I am inside the app a wanted to showDialog and it is showing me this logs

I/flutter (24893): this is rideRequestId ::
I/flutter (24893): -MPKdvRwtFAEfon7r1bf
W/ConnectionTracker(24893): Exception thrown while unbinding
W/ConnectionTracker(24893): java.lang.IllegalArgumentException: Service not registered: lu@afd33d3
W/ConnectionTracker(24893): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1484)
W/ConnectionTracker(24893): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1639)
W/ConnectionTracker(24893): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:703)
W/ConnectionTracker(24893): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516127@20.45.16 (110304-0):1)
W/ConnectionTracker(24893): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516127@20.45.16 (110304-0):2)
W/ConnectionTracker(24893): 	at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516127@20.45.16 (110304-0):9)
W/ConnectionTracker(24893): 	at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516127@20.45.16 (110304-0):3)
W/ConnectionTracker(24893): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516127@20.45.16 (110304-0):3)
W/ConnectionTracker(24893): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
W/ConnectionTracker(24893): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(24893): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516127@20.45.16 (110304-0):5)

and this is my notificaton.dart page code

import 'dart:async';
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:taxi/Driver/notifications/notificationDialogue.dart';
import 'package:taxi/config.dart';
import 'package:taxi/main.dart';
import 'dart:io' show Platform;
import 'package:taxi/riders/model/rideDetails.dart';
class PushNotificationService {
final FirebaseMessaging firebaseMessaging = FirebaseMessaging();
  Future initialize(context) async {
  firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        retrieveRideRequestInfo(getRideRequestId(message), context);
//        getRideRequestId(message);     
      },
      onLaunch: (Map<String, dynamic> message) async {
       retrieveRideRequestInfo(getRideRequestId(message), context);
//        getRideRequestId(message);
      },
      onResume: (Map<String, dynamic> message) async {
       retrieveRideRequestInfo(getRideRequestId(message), context);
//        getRideRequestId(message);
      },
    );
  }
  Future<String> getToken() async {
    String token = await firebaseMessaging.getToken();
    print("this is token ::");
    print(token);
    driverRef.child(currentfirebaseUser.uid).child("token").set(token);
    firebaseMessaging.subscribeToTopic("alldrivers");
    firebaseMessaging.subscribeToTopic("allusers");
  }
  String getRideRequestId(Map<String, dynamic> message){
    String rideRequestId = " ";
    if(Platform.isAndroid){
        print("this is rideRequestId ::");
       rideRequestId = message['data']['ride_request_id'];
        print(rideRequestId);
    }
    else
    {
       print("this is rideRequestId ::");
       rideRequestId = message['ride_request_id'];
       print(rideRequestId);
    }
    return rideRequestId;
  }
  void retrieveRideRequestInfo(String rideRequestId, BuildContext context){
    newRequestsRef.child(rideRequestId).once().then((DataSnapshot dataSnapShot){
      if (dataSnapShot.value != null ){
        assetsAudioPlayer.open(Audio("sounds/alert.mp3"));
        assetsAudioPlayer.play();
        double pickUpLocationLng = double.parse(dataSnapShot.value['pickup']['logitude'].toString());
        double pickUpLocationLat = double.parse(dataSnapShot.value['pickup']['latitude'].toString());
        String pickUpAddress = dataSnapShot.value['pickup_address'].toString();
        double dropOffLocationLat = double.parse(dataSnapShot.value['dropoff']['latitude'].toString());
        double dropOffLocationLng = double.parse(dataSnapShot.value['dropoff']['logitude'].toString());
        String dropOffAddress = dataSnapShot.value['dropoff_address'].toString();
        String paymentMethod = dataSnapShot.value['payment_method'].toString();

        RideDetails rideDetails = RideDetails();
        rideDetails.payment_method = paymentMethod;
        rideDetails.pickup_address = pickUpAddress;
        rideDetails.dropoff_address = dropOffAddress;
        rideDetails.ride_request_id = rideRequestId;
        rideDetails.pickup = LatLng(pickUpLocationLat, pickUpLocationLng);
        rideDetails.dropoff = LatLng(dropOffLocationLat, dropOffLocationLng);
        print("information :::");
        print(rideDetails.pickup);
        print(rideDetails.pickup);
         showDialog(context: context,
         barrierDismissible: false,
         builder: (BuildContext context) => NotificationDialogue(rideDetails: rideDetails,),
         );
      }
    });
  }
}

**Comment by muhammed-amein** [comment]
Guys i need help

**Comment by flutteresbolivia** [comment]
> Guys i need help

there are many with the same problem, I include myself, when that error happens, flutter crashes me and Hot Reload and Restart does not work

**Comment by aguatno** [comment]
Hi @muhammed-amein It seems the error logs are more of Flutter SDK  implementation rather than Firebase itself. If you're still having this issue, we suggest filing here https://github.com/FirebaseExtended/flutterfire/issues.

If you're able to reproduce the issue using our native Firebase SDK (Web, Android, or iOS), please let me know so that I can continue to investigate the issue.
