### ISSUE TITLE
Firebase Remote Config doesn't work with live versions on Google Play

### ISSUE THREAD

**Issue by mwaked** [firebase/firebase-android-sdk#2287]
I integrated Firebase remote config and it's working fine when i run debug, release or APK from bundle any build from Android studio work fine and return remote config data also when i install the app which uploaded to Huawei or Samsung Store it is working fine also, Only the app from Google Play doesn't return any remote config data so something is very strange!!

**Any one faced the same problem before?**

**Maybe the problem in the bundle which uploaded to Google Play?**

Gradle:

` implementation 'com.google.firebase:firebase-config-ktx:20.0.2'`

BaseApplication:

```
 override fun onCreate() {
        super.onCreate()
        initRemoteConfig()
 }

  private fun initRemoteConfig() {
    val mFirebaseRemoteConfig = FirebaseRemoteConfig.getInstance()

    mFirebaseRemoteConfig.setConfigSettingsAsync(
            FirebaseRemoteConfigSettings.Builder().setMinimumFetchIntervalInSeconds(3600L)
                    .build()
    )
    mFirebaseRemoteConfig.setDefaultsAsync(R.xml.remote_config_defaults)
    var cacheExpiration: Long = 720
    if (BuildConfig.DEBUG) {
        cacheExpiration = 0
    }
    mFirebaseRemoteConfig.fetch(cacheExpiration)
            .addOnCompleteListener { task: Task<Void?> ->
                if (!task.isSuccessful) return@addOnCompleteListener
                mFirebaseRemoteConfig.activate()
                // Get remote config data
            }

}
```

**Comment by danasilver** [comment]
A few things to help debug the issue:

- Make sure you wait for the [`activate()`](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#activate()) task to complete before getting the fetched values.
- If you set `minimumFetchIntervalInSeconds` in the call to [`fetch(long minimumFetchIntervalInSeconds)`](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#public-taskvoid-fetch-long-minimumfetchintervalinseconds) that'll override the same setting from `setConfigSettingsAsync` (it's likely that task hasn't completed before `fetch` is called in this case, too).
- You may want to check on your conditions in the Remote Config dashboard within the Firebase console to make sure there isn't a condition that prevents the live apps from receiving the values you expect - or conversely a condition that only delivers them to the local/debug versions.
