### ISSUE TITLE
Firebase Remote Config setMinimumFetchIntervalInSeconds has no effect

### ISSUE THREAD

**Issue by shumidub** [firebase/firebase-android-sdk#2289]
Firebase Remote Config version 19.2.0

I'm trying to use 3600 seconds as minimum fetch interval : 
```
 val settings = FirebaseRemoteConfigSettings.Builder()
                .setMinimumFetchIntervalInSeconds(3600L)
                .build()

FirebaseRemoteConfig.getInstance().setConfigSettingsAsync(settings)
```
```
FirebaseRemoteConfig.getInstance().fetch(3600L).addOnCompleteListener { task ->
            if (task.isSuccessful) FirebaseRemoteConfig.getInstance()
}          
```
when reload app one time and after two hours - remote config not fetched. Only after 12 hours

**Comment by danasilver** [comment]
A couple questions that could help solve this issue:
- Are you waiting for the `setConfigSettingsAsync` task to complete before calling `fetch`?
- Where are you calling [`activate()`](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#activate())? That's how the newly fetched values would become "active" and get returned when you `get` the value with [`getString`](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#getString(java.lang.String)) or another similar method.

**Comment by shumidub** [comment]
I call setConfigSettingsAsync and not wait in a current session.
But I expected that on the next time when app will be started the previous settings were already applied. 

I use fetchAndActivate() method. And wait while task will be completed. And print to log task.getResult() and also get feature toggle method by getString

**Comment by gmacdev** [comment]
@shumidub if you're calling activate or fetchAndActivate() inside your application class (or similar) then it will only activate when the app process is killed or removed from memory and the application class is started again. 

In order for the code to execute every time, make sure to move the code to a class that is called every time you open the application. Example: inside SplashActivty of your android app.

**Comment by argzdev** [comment]
Hi @shumidub, just bumping this thread. Are you still encountering this issue on the latest version? Thanks.
