### ISSUE TITLE
[Firebase Crashlytics] Missing User ID on dashboard

### ISSUE THREAD

**Issue by danhyltoftlund** [firebase/firebase-android-sdk#2293]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics (Database, Firestore, Storage, Functions, etc)
  * Component version: 17.4.4

#### Steps to reproduce:

We are setting userid in our android app to uniquely identify users. However previously I have seen userID present in the Firebase Crashlytics console view. However, the problem list view still show the "users" column, when I open a specific crash report, i cannot find the userID.

Seems to be a duplicate of this issue https://github.com/firebase/firebase-android-sdk/issues/1909, which is already closed.

#### Relevant Code:

```
FirebaseCrashlytics.getInstance().setUserId(UserID);
```

**Comment by rlazo** [comment]
Hi @danhyltoftlund thanks for your report. Just to be sure, you were able to see the userId in the report of a specific crash, and you are no longer able to do so? Does this happen consistently?

**Comment by danhyltoftlund** [comment]
Hi @rlazo, Thank you for responding, When I checked today, I observed that the UserID is back. As a result I will close this issue.
