### ISSUE TITLE
Firebase crashlytic plugin should use Task Configuration Avoidance

### ISSUE THREAD

**Issue by stephanenicolas** [firebase/firebase-android-sdk#230]
The issue : https://github.com/firebase/firebase-android-sdk/issues/198 is related to this but this one generalizes the issue. 

With the release of gradle 4.9+ and AGP 3.3, it's now possible to avoid configuring tasks during builds.
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

This feature is important has it can dramatically decrease build times and especially sync times in Android Studio. Knowing that the Firebase plugin is probably used by most apps in their apk module, using Firebase plugin will actually create a lot of tasks in all modules and break what AGP 3.3 is trying to accomplish.

In gradle 5 and probably soon in AGP, it will not be possible anymore to create/configure tasks the old way. This feature is a blocker for future upgrades. 

The migration is not very difficult, a bit long, but relatively simple. Please prioritize this, we are very close to the point where the firebase plugin is the only non compliant plugin in our app.

To make sure all old api calls have been removed, you can use  `-Pandroid.debug.obsoleteApi=true` in your example apps and make sure they don't call obsolete APIs.

An issue has been open in android issue tracker too: https://issuetracker.google.com/issues/123851263

**Comment by samtstern** [comment]
@stephanenicolas thanks for filing this!  If you're talking about the Firebase Perf plugin, we can leave the issue here.

If you're talking about the `google-services` plugin you may want to move the issue to here:
https://github.com/google/play-services-plugins

**Comment by stephanenicolas** [comment]
I am not sure exactly. To be totally transparent, we are still using crashlytics and we realize that we need to migrate to firebase, not only because crashlytics is outdated and soon gonna be killed, but also because the plugin is obsolete, and not updated. 

So, in other words, we don't use the firebase plugin yet but want to switch to it. With this ticket I was preparing our migration so that it would also provide us Task Configuration Avoidance when we switch. 
I don't understand your question precisely. Sorry about this.

**Comment by samtstern** [comment]
@stephanenicolas no worries it sounds like you're in the right place for Crashlytics.

**Comment by stephanenicolas** [comment]
@samtstern I could read a bit more about the migration. I updated the title to be more precise.
So, I am guessing that we are both talking here about the artifact `com.crashlytics.sdk.android:crashlytics`, right ?

There is something I don't understand yet: we should still keep the fabrics plugin in our build after the migration ?
According to [the doc to setup firebase crashlytics](https://firebase.google.com/docs/crashlytics/get-started#android), the plugin `io.fabric.tools:gradle` is still needed ?

**Comment by davidmotson** [comment]
This should be done now. Feel free to re-open if this is still an issue.
