### ISSUE TITLE
Reduce friction in native symbol uploading by integrating with AGP 4.1

### ISSUE THREAD

**Issue by rciovati** [firebase/firebase-android-sdk#2303]
## What feature would you like to see?

Currently, uploading native symbols is more complicated than (I think) it could be and this leads to people (considering the issues in this repo I don't think I'm the only one) struggling with getting the right configuration. 

The Android Gradle Plugin 4.1 [introduced a feature](https://developer.android.com/studio/build/shrink-code#android_gradle_plugin_version_41_or_later) that allows debug symbols to be bundled directly in the `.aab` so that the Google Play console can automatically de-obfuscate native crashes. With this option enabled, the debug  symbols are also compressed in a `.zip` file that you can find in the `build/outputs/native-debug-symbols/...` directory. 

It would be really convenient for developers if the Crashlytics plugin was integrated with this new feature so that no extra configuration for uploading native symbols is required.

## How would you use it?

I would use it so that I don't have to spend time trying to configure the native symbols upload manually.

**Comment by mrober** [comment]
@rciovati we have a prerelease of the next major version of the Crashlytics Gradle plugin, you can find it in #5733.

One of the improvements here is better support for native builds. It will automatically find the merged native libs output by AGP 8.1+, and process them. This is different than what you described in AGP 4.1, but will still make uploading native symbols much less complicated. All you need to do is set `nativeSymbolUploadEnabled` and it will happen automatically.
