### ISSUE TITLE
Crashlytics - Crash reporting from intranet

### ISSUE THREAD

**Issue by hare989** [firebase/firebase-android-sdk#2304]
Hi,

Not sure if this is supported so i will not set this issue as request feature. Just need info.

Is it possible to set up Firebase Crashlytics to send crash reports from intranet using proxy? ...or any other way?

Crashlytics would be integrated in applications that are in closed network but crash reporting to Firebase should work as expected. 
How this is achievable?

Thanks in advance.

**Comment by rlazo** [comment]
Hi @hare989 it's not possible to send crashes from crashlytics under the scenario you mentioned.
