### ISSUE TITLE
Firebase Messaging License

### ISSUE THREAD

**Issue by vanniktech** [firebase/firebase-android-sdk#2312]
Is it correct that in the POM file Firebase Crashlytics has the normal apache 2 and firebase messaging has:

```
 <name>firebase-messaging</name>
 <licenses>
   <license>
     <name>Android Software Development Kit License</name>
     <url>https://developer.android.com/studio/terms.html</url>
     <distribution>repo</distribution>
   </license>
 </licenses>
</project>
```

I'd expect Firebase Messaging to also have a normal Apache 2 license.

**Comment by rlazo** [comment]
Hi @vanniktech yes, it's correct. Firebase Cloud Messaging is being released right now using the Android Software Development Kit License. Thanks!
