### ISSUE TITLE
How to handle user creations by testing bots?

### ISSUE THREAD

**Issue by GuanacoDevs** [firebase/firebase-android-sdk#232]
Anybody knows how to avoid unnecessary user creation by testing bots?
I have disabled Pre-Launch report from my Play Console, because each time I upload an update I get 8 new user accounts from the testing bots. Still with Pre-Launch report disabled testing bots still create users. 
I have noticed that after testing 2 of them uninstall the app, which is good because I already handle that case when an user uninstall the app, I remove the account. 
But I still want/need to remove the other accounts, and my app is under Internal release.
I have reached Firebase and Play console support, but no avail. I even found a bit of code to recognize when using Test-Lab but not from the testing bots from Play Console. 
By the time I go Production I won't have any idea who is a bot or a "real" user.

Any ideas? 
Best Regards

**Comment by krharsh17** [comment]
I'm in a dire need of a solution for this. In the beginning, when the apps have a very low number of users, it becomes really difficult to tell the bots from the real guys. Any help on this, please?

**Comment by GuanacoDevs** [comment]
What I'm doing at the moment is that I set on my users data node the version of the app(`BuildConfig.VERSION_NAME`)for android, when the app creates an user anonymously.
I have re-enabled Pre-Launch report in my console, because the test were already running anyway. I will always deploy to "Internal Test" first, then promote to "Alfa", from there to Production.
Then I'll wait for the testings to be complete(usually less than an hour) and before I promote to Production I'll run a small javascript script that query users with that version of the app in their RTDB `user_data` node and then remove them from my project.

```
const admin = require('firebase-admin');
const serviceAccount = require('path/to/my/service/account.json');
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: 'https://my-project.firebaseio.com'
});
const database = admin.database();

function getBots(appVersion) {
    const events_ref = database.ref('user_data');
    return events_ref.orderByChild('app_version').equalTo(appVersion).once('value')
        .then(query => {
            const promisesArray = [];
            console.log(query.numChildren());
            query.forEach(snap => {
                promisesArray.push(admin.auth().deleteUser(snap.key));
            });
            return Promise.all(promisesArray);
        })
        .then(() => process.exit())
        .catch(reason => {
            console.log(reason.message);
            return process.exit();
        });
}
getBots("version_to_cleanup_from_bots");
```

I think that even after promotions, there might be a couple of bots, but no more than 2, but is the best approach I have found so far, to avoid testing bots pollution.

**Comment by argzdev** [comment]
Hi, this looks like more of a solution needed on the Google Play console side. At the same time, since an alternative solution has been provided, I'll be closing this issue.
