### ISSUE TITLE
Crashlytics is stuck in infinite loop. How to troubleshoot the root cause?

### ISSUE THREAD

**Issue by ezrover** [firebase/firebase-android-sdk#2338]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _4.1.1____
  * Firebase Component: _Crashlytics____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _bom:26.3.0
![Screen Shot 2021-01-18 at 10 55 12 AM](https://user-images.githubusercontent.com/1473932/104953782-edc6a480-597b-11eb-865b-e41b6cad4342.png)
____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rlazo** [comment]
Hi @ezrover thanks for your report. Could you provide more details on what's the problem, if it's something that can be reproduced consistently? Add any relevant log/console output. Thanks!

**Comment by ezrover** [comment]
Hi @rlazo , I tried to enable Crashylitics from the Console and it went into an infinite loop. I have deleted and recreated the app multiple times both from console as well as Android Studio's Firebase menu and still cant get passed the infinite spinner!  The performance tab seems to be working fine as it does show the app start time. I had only enabled these two features so am not sure if the other features are working fine. The google-services.xml has been copied to the Android Studio App folder as instructed, The App build.gradle is as follows:

`apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'

android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.ezrover"
        minSdkVersion 24
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        // Enables Jetpack Compose for this module
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation fileTree(dir: 'third_party/autobanh/lib', include: ['autobanh.jar'])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.core:core-ktx:1.5.0-alpha05'
    // implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation "androidx.preference:preference-ktx:1.1.1"

    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:26.3.0')
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-perf-ktx'

    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation project(path: ':webrtclib')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    // https://github.com/BeppiMenozzi/BalloonPopup
    // https://github.com/BeppiMenozzi/Knob
    implementation 'com.github.BeppiMenozzi:Knob:1.9.0'
    implementation 'com.github.BeppiMenozzi:BalloonPopup:0.2.8'

    // https://github.com/anastr/SpeedView
    implementation 'com.github.anastr:speedviewlib:1.5.3'

    // sample: implementation 'com.github.Jay-Goo:RangeSeekBar:v3.0.0'
    implementation 'com.github.Jay-Goo:RangeSeekBar:v3.0.0'
}
repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}
`


and project build.gradle is:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.4.30-M1'

    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        // classpath 'com.android.tools.build:gradle:3.6.2'
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
        classpath 'com.google.firebase:perf-plugin:1.3.4'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

The App's main package is "package com.ezrover"

and Manifest is:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="com.ezrover"
          android:versionCode="1"
          android:versionName="1.0">

    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-feature android:glEsVersion="0x00020000" android:required="true" />

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    
    <application
                android:label="@string/app_name"
                 android:icon="@drawable/ic_launcher"
                 android:allowBackup="false"
                 android:debuggable="true"
                 android:supportsRtl="true"
                tools:replace="android:allowBackup"
                tools:ignore="HardcodedDebugMode">

        <activity android:name="com.ezrover.activity.ConnectActivity"
                  android:label="@string/app_name"
                  android:windowSoftInputMode="adjustPan"
                    android:screenOrientation="portrait"
                  android:theme="@style/AppTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="https" android:host="appr.tc"/>
                <data android:scheme="http" android:host="appr.tc"/>
            </intent-filter>
        </activity>

        <activity android:name="com.ezrover.activity.SettingsActivity"
                  android:label="@string/settings_name"
            android:screenOrientation="portrait"
                  android:theme="@style/AppTheme">
        </activity>

        <activity android:name="com.ezrover.activity.CallActivity"
                  android:label="@string/app_name"
                  android:screenOrientation="landscape"
                  android:configChanges="orientation|smallestScreenSize|screenSize|screenLayout"
                  android:theme="@style/CallActivityTheme">
        </activity>
    </application>
</manifest>
`

**Comment by mrwillis21** [comment]
Hi @ezrover - have you tried crashing your app? Once our backend detects a crash from your app, you should be able to see the Crashlytics dashboard.
