### ISSUE TITLE
Firebase Apple login for Android, another webview is opened when login succeeds

### ISSUE THREAD

**Issue by GZaccaroni** [firebase/firebase-android-sdk#2343]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: Authentication
  * Component version: 26.2.0

#### Steps to reproduce:
After login succeeds on Apple website another login webview opens asking me for credentials in an endless loop.

**Comment by malcolmdeck** [comment]
Can you share the code in the activity that you have set up that reproduces this issue? I can't reproduce this myself.
