### ISSUE TITLE
Provide a way to deactivate the auth request limit for testing purposes

### ISSUE THREAD

**Issue by mscherer82** [firebase/firebase-android-sdk#2358]
Implementing SMS code authentication, change phone number features or working on a bug (like this one https://github.com/FirebaseExtended/flutterfire/issues/4651) is difficult because after only a few (5?) login attmeps firebase is blocking the phone number for a certain time. 

It seems this kind of limitation is **not** listed here: https://firebase.google.com/docs/auth/limits

Google "firebase auth too many requests" show a lot of result where develops are struggling with this issue.

**Comment by samhorlbeck** [comment]
Hi, thanks for reaching out

You are correct, the service will start to limit requests after a certain point. To get around this problem, during debugging or integration testing, we have [FirebaseAuthSettings#setAppVerificationDisabledForTesting](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthSettings#setAppVerificationDisabledForTesting(boolean)). This will bypass app verification checks and will skip sending an actual text message; instead you'll enter the code you pre-set in the Firebase Console. Just remember to turn this off before deploying :)
