### ISSUE TITLE
Crashlytics is not being updated real time.

### ISSUE THREAD

**Issue by tank777** [firebase/firebase-android-sdk#2389]
It is taking too much time to get the crash report after the application build version code and build name change. 
```
    implementation platform('com.google.firebase:firebase-bom:26.4.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
```

**Comment by rlazo** [comment]
Hi @tank777 when you say "too much time", what do you mean (hours/days)? Did it use to work and it no longer does? Please provide us more details on how did you find the issue to help triaging it better. Thanks!

**Comment by tank777** [comment]
I have an observer that it has taken one day for 2 times and it has taken 6h for one time. Is it possible that in the firebase console it is displaying the `need to investigation` label on every new build version?

**Comment by mrwillis21** [comment]
Hi @tank777 - when you update your build version, is it a test crash that's taking too long to get through?

**Comment by tank777** [comment]
@mrwillis21  No, It was the same for both cases.

**Comment by mrwillis21** [comment]
Hi @tank777, can you please run `adb shell setprop log.tag.FirebaseCrashlytics VERBOSE` and then paste the logging output here from `adb logcat -s FirebaseCrashlytics`?

**Comment by tank777** [comment]
We have used the other crashlytics in our application. What we have noticed that firebase is not able to capture the ANR crash.

**Comment by tank777** [comment]
02-13 10:05:08.358 12808 12808 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by global Firebase setting.
02-13 10:05:08.359 12808 12808 D FirebaseCrashlytics: Firebase Analytics is available.
02-13 10:05:08.363 12808 12808 D FirebaseCrashlytics: Firebase Analytics listener registered successfully.
02-13 10:05:08.383 12808 12808 D FirebaseCrashlytics: Reading cached settings...
02-13 10:05:08.384 12808 12808 D FirebaseCrashlytics: No cached settings found.
02-13 10:05:08.385 12808 12808 D FirebaseCrashlytics: No cached settings data found.
02-13 10:05:08.388 12808 12808 D FirebaseCrashlytics: Mapping file ID is: 00000000000000000000000000000000
02-13 10:05:08.390 12808 12808 I FirebaseCrashlytics: Initializing Crashlytics 17.3.0
02-13 10:05:08.393 12808 12808 D FirebaseCrashlytics: Installer package name is: null
02-13 10:05:08.447 12808 12808 D FirebaseCrashlytics: Exception handling initialization successful
02-13 10:05:08.493 12808 12847 D FirebaseCrashlytics: No cached FID; legacy id is null
02-13 10:05:08.495 12808 12847 D FirebaseCrashlytics: Created new Crashlytics IID: 2dc91b6824714d509e81a9e35666477a
02-13 10:05:08.502 12808 12847 D FirebaseCrashlytics: Opening a new session with ID 602756FC01BC-0001-3208-037EE7D98DFC
02-13 10:05:08.569 12808 12847 D FirebaseCrashlytics: Initialization marker file created.
02-13 10:05:08.569 12808 12847 D FirebaseCrashlytics: Registered Firebase Analytics event receiver for breadcrumbs
02-13 10:05:08.571 12808 12847 D FirebaseCrashlytics: Finalizing previously open sessions.
02-13 10:05:08.577 12808 12847 D FirebaseCrashlytics: No open sessions to be closed.
02-13 10:05:08.578 12808 12847 D FirebaseCrashlytics: Closed all previously open sessions
02-13 10:05:08.581 12808 12847 D FirebaseCrashlytics: No reports are available.
02-13 10:05:08.585 12808 12847 D FirebaseCrashlytics: Initialization marker file removed: true
02-13 10:05:08.977 12808 12850 D FirebaseCrashlytics: Requesting settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:281590339709:android:f68634b1db55613185f914/settings
02-13 10:05:08.979 12808 12850 D FirebaseCrashlytics: Settings query params were: {instance=f456077a986a33ea3dc3fa20e772cd11f6cdb291, build_version=27, display_version=0.27, source=1}
02-13 10:05:09.098 12808 12858 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[mParcelledData.dataSize=64], name=_s, timestampInMillis=1613190908902}]
02-13 10:05:09.257 12808 12858 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[mParcelledData.dataSize=112], name=_vs, timestampInMillis=1613190909182}]
02-13 10:05:09.365 12808 12858 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[mParcelledData.dataSize=176], name=_vs, timestampInMillis=1613190909292}]
02-13 10:05:11.458 12808 12858 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[mParcelledData.dataSize=36], name=_ab, timestampInMillis=1613190909382}]
02-13 10:05:11.673 12808 12850 D FirebaseCrashlytics: Settings request ID: null
02-13 10:05:11.673 12808 12850 D FirebaseCrashlytics: Settings result was: 404
02-13 10:05:11.674 12808 12850 E FirebaseCrashlytics: Failed to retrieve settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:281590339709:android:f68634b1db55613185f914/settings
02-13 10:05:13.322 12808 12858 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[mParcelledData.dataSize=176], name=_vs, timestampInMillis=1613190913126}]
02-13 10:05:14.395 12808 12858 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[mParcelledData.dataSize=136], name=_e, timestampInMillis=1613190914158}]
02-13 10:05:14.976 12808 12858 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[mParcelledData.dataSize=184], name=_vs, timestampInMillis=1613190914880}]

**Comment by argzdev** [comment]
Hi @tank777, just bumping this thread. May I ask if you still encounter this on the latest SDK version? Thanks.

**Comment by tank777** [comment]
No note anymore with the new version.
