### ISSUE TITLE
Firebase performance plugin: duplicate jar entry [com/google/android/exoplayer2/R.class]

### ISSUE THREAD

**Issue by rhonyabdullah** [firebase/firebase-android-sdk#2396]
> 
> 
> ### [READ] Step 1: Are you in the right place?
> 
> Issues filed here should be about bugs in __the code in this repository__. 
> If you have a general question, need help debugging, or fall into some
> other category use one of these other channels:
> 
>   * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
>     with the firebase tag.
>   * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
>     google group.
>   * For help troubleshooting your application that does not fall under one
>     of the above categories, reach out to the personalized
>     [Firebase support channel](https://firebase.google.com/support/).
> 
> ### [REQUIRED] Step 2: Describe your environment
> 
>   * Android Studio version: _____
>   * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
>   * Component version: _____
> 
> ### [REQUIRED] Step 3: Describe the problem
> 
> #### Steps to reproduce:
> 
> What happened? How can we make the problem occur?
> This could be a description, log/console output, etc.
> 
> #### Relevant Code:
> 
> ```
> // TODO(you): code here to reproduce the problem
> ```

- firebase performance: 19.1.0
- exoplayer2: 2.12.3
- android studio: 4.1.2

I'm just following this [issue](https://github.com/firebase/firebase-android-sdk/issues/1476) but still not working when using R8. So i turning off R8 and build release again, after put exoplayer2 dependencies into my android.library module, building with proguard remains error with duplicated R class, please read this log for complete information.
- gradle [build-scan](https://scans.gradle.com/s/gxx5vz7hknlgw/console-log?anchor=8760)

**Comment by ramanpreetSinghKhinda** [comment]
Adding current oncaller @yalunqin to take a look.

**Comment by yalunqin** [comment]
Hi Rhony,

Would you mind providing a sample app that reproduces this issue? Also would be great if you could also provide specific instructions on how you build ExoPlayer and the app.
