### ISSUE TITLE
Don't leak `com.google.android.datatransport:transport-runtime` onto classpath

### ISSUE THREAD

**Issue by ursusursus** [firebase/firebase-android-sdk#2440]
Hi, I'm a dagger multibinding user and have been burned by you leaking your transitive dependency onto app's classpath

```
+--- com.google.firebase:firebase-crashlytics:17.3.0
|    +--- com.google.android.datatransport:transport-api:2.2.1
|    |    \--- androidx.annotation:annotation:1.1.0
|    +--- com.google.android.datatransport:transport-backend-cct:2.3.2
|    |    +--- androidx.annotation:annotation:1.1.0
|    |    +--- com.google.android.datatransport:transport-api:2.2.1 (*)
|    |    +--- com.google.android.datatransport:transport-runtime:2.2.5
|    |    |    +--- androidx.annotation:annotation:1.1.0
|    |    |    +--- com.google.android.datatransport:transport-api:2.2.1 (*)
|    |    |    \--- javax.inject:javax.inject:1
|    |    +--- com.google.firebase:firebase-encoders:16.0.0
|    |    |    \--- androidx.annotation:annotation:1.1.0
|    |    \--- com.google.firebase:firebase-encoders-json:17.0.0
|    |         +--- androidx.annotation:annotation:1.1.0
|    |         \--- com.google.firebase:firebase-encoders:16.0.0 (*)

```

given that artifact contains `@IntoSet` as well (`import com.google.android.datatransport.runtime.dagger.multibindings.IntoSet`), bug was that the incorrect import was chosen.

There is no reason for `com.google.android.datatransport` to be visible in the app. Remove the footgun please

**Comment by ursusursus** [comment]
I noticed this https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/firebase-crashlytics.gradle

looks fine. So maybe maven setup is bad?

**Comment by mrichards** [comment]
I believe this issue is obsolete based on changes made to the Firebase build configuration some time ago. If updating to the latest Firebase BoM does not resolve the issue, please re-open and provide a minimally reproduceable example.
