### ISSUE TITLE
uploadCrashlyticsSymbolFile gradle task missing when using build.gradle.kts

### ISSUE THREAD

**Issue by kmadsen** [firebase/firebase-android-sdk#2444]
## What feature would you like to see?

Similar to this issue: https://github.com/firebase/firebase-android-sdk/issues/1298

But the `CrashlyticsExtension` does not include `uploadCrashlyticsSymbolFile` gradle tasks when using build.gradle.kts. The work around, is to use the groovy compiler.

``` kotlin
withGroovyBuilder {
    "firebaseCrashlytics" {
        "nativeSymbolUploadEnabled"(true)
        "unstrippedNativeLibsDir"(NativeDownloadTask.UNSTRIPPED_NATIVE_LIBS_PATH)
    }
}
```

## How would you use it?

Similar to the documentation but with build.gradle.kts https://firebase.google.com/docs/crashlytics/ndk-reports#upload-external-dependencies
``` kotlin
configure<CrashlyticsExtension> {
    nativeSymbolUploadEnabled = true
    unstrippedNativeLibsDir = NativeDownloadTask.UNSTRIPPED_NATIVE_LIBS_PATH
}
```

**Comment by kuFEAR** [comment]
after updating firebase gradle plugin from 2.4.1 to 2.6.0-2.6.1 firebaseCrashlytics accessor disappeared from generated extensions in kts build configurations

**Comment by vhoy** [comment]
I'm experiencing the same issue: Gradle tasks GenerateCrashlyticsSymbolFile{build_variant} and  UploadCrashlyticsSymbolFile{build_variant} disappear from the list when using  plugin 2.6.x. Everything works fine with 2.5.2.

**Comment by mrichards** [comment]
[This comment](https://github.com/firebase/firebase-android-sdk/issues/2665#issuecomment-849897741) describes the current state of Crashlytics plugin support for the Kotlin DSL, and provides sample code demonstrating the use of `configure<>`, usable in version 2.6.0+ of the plugin.
