### ISSUE TITLE
NullPointerException on Firebase Performance Dependency

### ISSUE THREAD

**Issue by therealshabi** [firebase/firebase-android-sdk#2462]
Describe your environment

  * Android Studio version: Android Studio 4.2 Beta 4
  * Firebase Component: Performance
  * Component version: 19.0.2

Describe the problem

We've just included the Firebase Performance Library with dependency version `19.0.2`
`implementation 'com.google.firebase:firebase-perf:19.0.2'`

and Firebase Performace Gradle Plugin Version 1.3.4
`classpath 'com.google.firebase:perf-plugin:1.3.4'`

Rest no manual code is written at our end for the Firebase Performance library, still, we're getting
an NPE on our Crashlytics, the stack trace for which I've added below.

99% of these events occurred on Background, 96% for Xiaomi devices and 91% on Android 9 devices.
There are a lot of instances reported for this crash.

#### Steps to reproduce:

We haven't added anything explicitly for the Firebase Performance library in our code, hence there are no concrete steps to reproduce, here's the stack trace of Crashlutics though

```Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
       at com.google.firebase.perf.internal.zzv.zzh(zzv.java:65)
       at com.google.firebase.perf.internal.zzv.<init>(zzv.java:2)
       at com.google.firebase.perf.internal.zzf.zzam(zzf.java:47)
       at com.google.firebase.perf.internal.zzf.zzc(zzf.java:194)
       at com.google.firebase.perf.internal.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)```

**Comment by therealshabi** [comment]
Sure, I'll try to update the dependency to the latest version. But, I checked the changelogs and I found no such issue/bug fixed in that. Anyways, will check by updating the version

**Comment by jposuna** [comment]
Hi @therealshabi, were you able to verify whether this is still happening with version `19.1.1`?

**Comment by therealshabi** [comment]
Hi @jposuna, we've propagated our release, will get back to you in a couple of days with concrete inference

**Comment by therealshabi** [comment]
Hi @jposuna...Thanks for your help...Updating the `com.google.firebase:firebase-perf` to `19.1.1` removed that crash.
This is fixed now
