### ISSUE TITLE
OnVerificationStateChangedCallbacks not respond even OTP code is received 

### ISSUE THREAD

**Issue by LongJakeparker** [firebase/firebase-android-sdk#2475]
I implementing Firebase Phone Authenticate feature and I got problem on production release.
Sometime when user send request to get OTP code by PhoneAuthProvider.verifyPhoneNumber(options), PhoneAuthProvider.OnVerificationStateChangedCallbacks was never fired even the sms was sent successful. I couldn't reproduce this case but my client from Japan reported this issue with the video below. 
I'm looking forward to your help to know the reason why this happens and the solution for this issue. Thank you!

https://user-images.githubusercontent.com/24937411/109588483-643df100-7b3b-11eb-8c74-8f7a65599544.mp4

device：Pixel3
OS：Android10
I had to make a timeout countdown to stop the loading progress.

<img width="870" alt="Screen Shot 2021-03-02 at 09 28 25" src="https://user-images.githubusercontent.com/24937411/109588584-90f20880-7b3b-11eb-9b8e-4adef7a49cc4.png">

And here is my code

**Comment by yuchenshi** [comment]
Based on the symptoms, it is very likely an network issue where the request has reached the server but the response never came back to the Android SDK. Does any other callbacks fire then? https://developers.google.com/android/reference/com/google/firebase/auth/PhoneAuthProvider.OnVerificationStateChangedCallbacks#public-method-summary make sure to check all four -- `onVerificationCompleted`, `	
onVerificationFailed`, `onCodeSent` and `onCodeAutoRetrievalTimeOut` (the last one seems missing from the code snippet in your screenshot). If you can get a reliable reproduction where none of them fires, please let us know and we can look further into this.
