### ISSUE TITLE
ANR  executing service com.google.firebase.auth.api.fallback.service.FirebaseAuthFallbackService

### ISSUE THREAD

**Issue by axkza** [firebase/firebase-android-sdk#2478]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: __4.1.2___
  * Firebase Component: __firebase-bom___ (Database, Firestore, Storage, Functions, etc)
  * Component version: __26.1.0___

### [REQUIRED] Step 3: Describe the problem
Our app has a lot of ANRS about FirebaseAuthFallbackService，more than 50%！！！
![image](https://user-images.githubusercontent.com/6112524/109778748-270f5700-7c40-11eb-8f62-845a5d181b7b.png)

**Comment by yuchenshi** [comment]
Please reach out to the personalized [Firebase support channel](https://firebase.google.com/support/) instead and we can help you troubleshoot over there.

**Comment by flxwu** [comment]
Hi, is there an update on this? Or a solution? This is blocking us from releasing our app...
