### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host "HOST"  No address associated with hostname (wifi turned on/off) 

### ISSUE THREAD

**Issue by andreicosminborta** [firebase/firebase-android-sdk#2479]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: Functions
  * Component version: com.google.firebase:firebase-functions-ktx
  * Device: TFM tablet

#### Steps to reproduce:
Can't call callable cloud functions, when wifi is turned on/off. In the google cloud logs viewer, there is no entry about the call or the internal error 
Cloud function message response:  INTERNAL
stackTrace: 
 * com.google.firebase.functions.FirebaseFunctions$2.onFailure(FirebaseFunctions.java:325)
 * okhttp3.RealCall$AsyncCall.execute(RealCall.java:215)
 * okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
 * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 * java.lang.Thread.run(Thread.java:764)
 
Cause:
 java.net.UnknownHostException: Unable to resolve host "BASE_URL": No address associated with hostname

#### Relevant Code:

        firebaseFunctions
            .getHttpsCallable("functionName")
            .call(endRideFunction)
            .addOnFailureListener {

                callback(false, it)
            }
            .addOnSuccessListener {
                callback(true, null)
            }

**Comment by argzdev** [comment]
Hi @andreicosminborta, just bumping this thread. Since this has been a while, may I ask if you're still encountering this issue on the latest SDK?
