### ISSUE TITLE
Misleading documentation in Dynamic links and steps

### ISSUE THREAD

**Issue by debopriyosanyal** [firebase/firebase-android-sdk#2488]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Device independent but mostly devices which can run apps built using 
  * Firebase Component: Dynamic links 
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Documentation issue or misleading documentation in dynamic links
#### Steps to reproduce:
Follow the steps provided here https://firebase.google.com/docs/auth/android/firebaseui
What happened? How can we make the problem occur?
To make the problem occur you need to have a website running a lamp and your goal should to build a new app on firebase and you should have a existing working domain.
Now for your new android app with firebase database you are adding a firebase signin option as mentioned in the link below:
https://firebase.google.com/docs/auth/android/firebaseui
Follow the steps in the link till you reach step 3 under Set-up sign-in methods which says the following

You will also have to enable Firebase Dynamic Links to use email-link sign in. In the Firebase console, click on Dynamic Links under Engage in the navigation bar. Click on Getting started and add a domain. The domain you choose here will be reflected in the email links sent to your users.

Now if you do as above in the dynamic links section it gives you an 2 IP address links which needs to be added as A records and AAAA records under dns settings with your domain name provider and it asks to remove the existing A record

If you do that your existing lamp website would go offline. This is misleading. I think the writer of the steps or the designer of the firebase dynamic links assumes the user would have their entire setup on firebase.In my opinion this assumption is wrong. I think a warning message needs to put up which says that if you remove your existing A records any live deployment not on firebase would go offline.
Follow the steps

This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @debopriyosanyal thanks for the feedback. I agree that there should be a warning on the Firebase Console to avoid unwanted downtime. As an action item, I filed an internal feature request so that our engineers will be able to look into this more.. I don't have any timelines for this, but I would suggest to please keep an eye out on our [release notes](https://firebase.google.com/support/releases).
