### ISSUE TITLE
 CommonUtils.isRooted(context) will get wrong result

### ISSUE THREAD

**Issue by tobecrazy** [firebase/firebase-android-sdk#2495]
### [READ] Step 1: Are you in the right place?

Please refer to: https://stackoverflow.com/questions/1101380/determine-if-running-on-a-rooted-device 

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  4.1.2
  * Firebase Component: Crashlytics(Database, Firestore, Storage, Functions, etc)
  * Component version: V17.3.0

### [REQUIRED] Step 3: Describe the problem
We I try my emulator isRooted , expected result false, but get a true value

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by mrichards** [comment]
Hi, thanks for letting us know! The root check is "best effort" and not guaranteed to be accurate. However, false positives should be very rare for physical devices. It looks like the root check for emulators may need to be updated. Can you let us know if you see false negatives on physical devices?
