### ISSUE TITLE
Duplicate class com.google.protobuf.AbstractMessageLite

### ISSUE THREAD

**Issue by SunilGoCars** [firebase/firebase-android-sdk#2499]
I am trying to use firebase **BOM 26.6.0** with firebase-perf. I have also included **protobuf-lite** to support proto file generation in my android app. I am getting duplicate class error. I tried excluding **protobuf-javalite** and ran the application then it started giving me **No static method com/google/protobuf/GeneratedMessageLite#registerDefaultInstance**.

I am attaching my build.gradle, dependencies tree and solution tried.

[app_build_gradle.txt](https://github.com/firebase/firebase-android-sdk/files/6121160/app_build_gradle.txt)
[dependencies.txt](https://github.com/firebase/firebase-android-sdk/files/6121174/dependencies.txt)
[app_build_gradle_after_exclude.txt](https://github.com/firebase/firebase-android-sdk/files/6121195/app_build_gradle_after_exclude.txt)

**Comment by SunilGoCars** [comment]
Could you @aguatno please update on it. It's been 20 days.

**Comment by aguatno** [comment]
The issue that you are facing is related to this GitHub issue #1152. In order to solve it, you need to update [all the Firebase SDKs ](https://github.com/firebase/firebase-android-sdk/issues/1152#issuecomment-654171170)affected by this change together, otherwise the old SDKs will pull the wrong dependency into your app.

**Comment by SunilGoCars** [comment]
I am upgrading all firebase dependencies together only. But we are using protobuf in our android app which is giving conflicts with firebase. **implementation "com.google.protobuf:protobuf-lite:3.0.1"**

Please check the app gradle file attached with issue.

**Comment by vkryachko** [comment]
Looks like you depend on `com.google.protobuf:protobuf-lite:3.0.1`, which is an old deprecated library, while firebase-perf depends on the new `com.google.protobuf:protobuf-javalite:3.14.0`, try removing your dependency on protobuf-lite, it should resolve the issue. And you should be able to use the new protobuf-javalite for your purposes without any code changes.
