### ISSUE TITLE
NullPointerException on ConnectionTracker bindService

### ISSUE THREAD

**Issue by TorrentsAlex** [firebase/firebase-android-sdk#250]
### Step 2: Describe your environment

  * Android Studio version: 3.3.1
  * Firebase Component: Core or Messaging
  * Component version: 16.0.4, 17.3.3 

#### Steps to reproduce:

I got this crash report on play console, is a variety of devices, some of them Galaxy a7 2018, Huawei Y9 2019, P20 and the android versions are 8.0, 8.1 and 9.0.

#### Relevant Code:
The crashlog.
```
java.lang.NullPointerException: 
  at com.google.android.gms.common.stats.ConnectionTracker.bindService (ConnectionTracker.java)
  at com.google.firebase.iid.zzad.a (zzad.java:82)
  at com.google.firebase.iid.zzab.a (zzab.java:48)
  at com.google.firebase.iid.zzat.a (zzat.java:26)
  at com.google.firebase.iid.zzs.run (zzs.java:8)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)

```

**Comment by aviashiet** [comment]
I am facing same issue

**Comment by ddx** [comment]
Having the same issue with the same crash log and similar affected OS versions and devices. 75% of our app seem to affect Android 9.0

**Comment by ckpark486** [comment]
I am also facing same issue

**Comment by TorrentsAlex** [comment]
Hi all!

We tested various solutions and the best was initialize manually. Remove the FirebaseInitProvider and call FirebaseApp.initializeApp(), in the next blog they are calling with the builder, but if you have the google-services.json file in your app you can call with the context only. 
This worked for us so i wish this work for all of you! Good luck!!

https://firebase.googleblog.com/2017/03/take-control-of-your-firebase-init-on.html

Yeah i know this is not the best to post this problem but i didn't found anything better.

**Comment by heyangJob** [comment]
Is this problem solved now

**Comment by aguatno** [comment]
Hi @TorrentsAlex Sorry for the delay in our reply. It looks like you found a workaround. I'd like to confirm if you are still having this issue until now? Could you try to update it to the latest version and see if the issue persists?

Thanks
