### ISSUE TITLE
FirebaseInstallations#getId never completes with aeroplane mode enabled

### ISSUE THREAD

**Issue by Michael-MF** [firebase/firebase-android-sdk#2500]
### Describe your environment

  * Android Studio version: `4.1.2`
  * Firebase Component: `FirebaseInstallations`
  * Component version: Tested using `v16.3.5` of `firebase-installations` in isolation, and by using `v26.6.0` of the BoM (both ktx & non-ktx versions)
  * Device: Tested on an Android Emulator (API30) & a physical Samsung A41 (API29)

#### Steps to reproduce:

If aeroplane mode is enabled on the device, `getId` never completes or cancels.

#### Relevant Code:

```kotlin
FirebaseInstallations.getInstance().id
    .addOnFailureListener {
        // Never called
    }
    .addOnCanceledListener {
        // Never called
    }
    .addOnSuccessListener {
        // Never called
    }
    .addOnCompleteListener {
        // Never called
    }
```

Alternative method using `.await()`

```kotlin
try {
    FirebaseInstallations.getInstance().id.await()
    // Never gets here
} catch (e: Exception) {
    // Never called
}
```

**Comment by aguatno** [comment]
Hi @Michael-MF Thanks for reporting. I run a test on Physical Device and Emulator with API30 and was able to call OnComplete and OnSuccessListener in Airplane mode (see image below). Can you try to update your SDK to the latest one and see if that would fix the issue?

![image](https://user-images.githubusercontent.com/56451054/113918755-63247180-9815-11eb-84ce-592a48363956.png)

**Comment by Michael-MF** [comment]
Just bumped from Firebase BoM `v26.6.0` -> `v26.8.0` and this is now working for me, thanks!
