### ISSUE TITLE
Receiving ERROR_INVALID_CERT_HASH even after registering the debug keystore in Firebase console

### ISSUE THREAD

**Issue by Manu-Jindal** [firebase/firebase-android-sdk#2506]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: Authentication (Database, Firestore, Storage, Functions, etc)
  * Component version: 17.0.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I have added authentication via Microsoft in Firebase Auth. I have added the SHA1 and SHA256 identity of the keystore (both debug and App signing key) in the Firebase console, however, I am still receiving the error while using it -> **ERROR_INVALID_CERT_HASH** - _There was an error while trying to get your package certificate hash._
#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
                OAuthProvider.Builder provider = OAuthProvider.newBuilder("microsoft.com");
                provider.addCustomParameter("tenant", "");
                Task<AuthResult> pendingResultTask = FirebaseAuth.getInstance().getPendingAuthResult();
                if (pendingResultTask != null) {
                    // There's something already here! Finish the sign-in for your user.
                    pendingResultTask
                            .addOnSuccessListener(
                                    new OnSuccessListener<AuthResult>() {
                                        @Override
                                        public void onSuccess(AuthResult authResult) {
                                            loginUser(authResult);
                                        }
                                    })
                            .addOnFailureListener(
                                    new OnFailureListener() {
                                        @Override
                                        public void onFailure(@NonNull Exception e) {
                                            AppUtil.showToast(Login.this, e.getMessage(), Toast.LENGTH_LONG);
                                        }
                                    });
                } else {
                    FirebaseAuth.getInstance()
                            .startActivityForSignInWithProvider(/* activity= */ Login.this, provider.build())
                            .addOnSuccessListener(
                                    new OnSuccessListener<AuthResult>() {
                                        @Override
                                        public void onSuccess(AuthResult authResult) {
                                            loginUser(authResult);
                                        }
                                    })
                            .addOnFailureListener(
                                    new OnFailureListener() {
                                        @Override
                                        public void onFailure(@NonNull Exception e) {
                                            AppUtil.showToast(Login.this, e.getMessage(), Toast.LENGTH_LONG);
                                        }
                                    });
                }

```

**Comment by yuchenshi** [comment]
In order to help, we'd need access to your project settings (including the hash config), so please reach out to the personalized [Firebase support channel](https://firebase.google.com/support/) instead.

**Comment by romellfudi** [comment]
@yuchenshi i had the same issue, Is it possible to replicate the solution?
