### ISSUE TITLE
onNewToken() sometimes gets unusable token.

### ISSUE THREAD

**Issue by u-shunya** [firebase/firebase-android-sdk#253]
I changed MyApp's implementing push notification service from GCM to FCM.
I am using the code below to generate FCM Registration token and send it to my server.
```
@Override
public void onNewToken(String token) {
    super.onNewToken(token);
    sendTokenToMyServer(token);
}
```
I noticed that the new token may not be in the same format.
In many cases, the token is 152 characters and it is valid in notifications. However, in rare cases, a token of 140 characters is acquired. This could not be used for notifications.
My experience is very similar to the following posts.
https://stackoverflow.com/questions/39195216/firebaseinstanceid-getinstance-gettoken-is-generating-two-different-types-of

Please tell me the cause and measures.

I use `com.google.firebase:firebase-messaging:17.3.4`.

**Comment by samtstern** [comment]
@u-shunya there's one answer in that SO question that seems relevant:
https://stackoverflow.com/a/39246387/324977

Do you have any old GCM code hanging around?  It seems like that may be causing the "old format" token.

**Comment by u-shunya** [comment]
@samtstern thank you for your comment.
but I already deleted the GCM receiver and the class overriding GCMIntentService.
Now I can not find the GCM code in my project, so I'm not able to think of anything else to do.

**Comment by aguatno** [comment]
Hi @u-shunya sorry for the late in response. I would like to check if you are still having issues? Have you tried the latest SDK version to see if the issue persists? Thanks
