### ISSUE TITLE
A sign-in error occurred. (Phone Auth)

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#2538]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio version: Android Studio Arctic Fox | 2020.3.1 Canary 4
  * Firebase Component: Firebase Auth (PhoneAuth) using Firebase UI (Database, Firestore, Storage, Functions, etc)
  * Component version: 20.0.3/7.1.1(FirebaseUI)

### [REQUIRED] Step 3: Describe the problem

Phone Auth has error on a new added app on the same Firebase project.

#### Steps to reproduce:

What happened? How can we make the problem occur?

Tried to add another app on the same Firebase project since both app are related to each other, now we have two app in one Firebase project with different package name but same keystore was used so the release SHA1 and SHA256 is the same as well.
Enabled Android Device Verification in Cloud Console.
Add both app package name and SHA1 to Credentials.
Launch the second newly added app then test a Phone Auth.
Received an unknown error with Firebase UI.

#### Relevant Code:

```
2021-03-23 23:48:12.109 9350-9350/com.new.added.app E/g0: SafetyNet Attestation has advice: 
    LOCK_BOOTLOADER
2021-03-23 23:48:12.642 9350-10676/com.new.added.app E/FirebaseAuth: [GetAuthDomainTask] Error getting project config. Failed with INVALID_CERT_HASH 400
2021-03-23 23:48:12.745 9350-9350/com.new.added.app E/r0: Failed to get reCAPTCHA token with error [There was an error while trying to get your package certificate hash.]- calling backend without app verification
2021-03-23 23:48:13.179 9350-9453/com.new.added.app E/FirebaseAuth: [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17093 null
2021-03-23 23:48:13.192 9350-9350/com.new.added.app E/AuthUI: A sign-in error occurred.
    com.google.firebase.auth.p: This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.
        at c.c.a.d.f.h.tk.a(com.google.firebase:firebase-auth@@20.0.3:26)
        at c.c.a.d.f.h.yl.a(com.google.firebase:firebase-auth@@20.0.3:1)
        at c.c.a.d.f.h.zl.run(com.google.firebase:firebase-auth@@20.0.3:3)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

PS: Another confusion was it works when I run the debug apk but with release apk this problem occurs.

Btw what are these error code and where could I see its documentation?

`status code: 17093`

**Comment by ArcherEmiya05** [comment]
I noticed that this happened on selected device, I tried to run the release apk on Xiaomi Redmi note 2 SDK 21 (without SIM) and Mi 90T Pro SDK 29 (with SIM) it works but this error occurred with Redmi 5A (without SIM). I think it has to do with how `SafetyNet`, if someone can explain it will be very appreciated and helpful. TIA

**Comment by ArcherEmiya05** [comment]
I discover that if the device `bootloader` was `unlocked` even not rooted, the Firebase Auth fails to work.

Reference:
https://forum.xda-developers.com/t/just-unlocking-the-bootloader-breakes-safety-net-and-make-device-unverified.4146761/
https://xiaomi.eu/community/threads/unlock-bootloader-and-banking-apps.56312/

Is there any work around for this since some user may not be aware of this?

**Comment by aguatno** [comment]
Hi @ArcherEmiya05 thanks for reporting. It appears neither SafetyNet checks nor reCAPTCHA checks didn't push through. 

To provide an insight, the version 20.0.0 of the Firebase Authentication Android SDK no longer depends on Google Play services. This change requires phone authentication to verify that phone number sign-in requests are coming from your app. If SafetyNet is enabled, Firebase Auth will try to verify via SafetyNet. In the event that SafetyNet cannot be used (for example, on devices without Google Play services, or the SafetyNet API is not enabled), Firebase will use reCAPTCHA verification to complete the phone sign-in flow.

If the device has Google Play services and the issue persists, could you please provide the following information? We'd love to dig more into this if we have a sample app.

- Minimal repro that I can run locally. Only include the necessary code that reproduces the issue and remove all third party integrations
- Steps to replicate the issue
- How often have you seen this crash?

**Comment by malcolmdeck** [comment]
The "INVALID_CERT_HASH 400" implies that you're application's SHA-1 is not registered in the console. You'll need both the SHA-1 and SHA-256 registered in the console to support both the reCAPTCHA and SafetyNet flows for Phone Auth, respectively.
