### ISSUE TITLE
W/zze: Application name is not set. Call Builder#setApplicationName.

### ISSUE THREAD

**Issue by shadowsheep1** [firebase/firebase-android-sdk#254]
What's this warning for?

`W/zze: Application name is not set. Call Builder#setApplicationName.`

I get it while calling

`FirebaseRemoteConfig remoteConfig = FirebaseRemoteConfig.getInstance();`

These my Firebase lib versions

```
implementation 'com.google.firebase:firebase-core:16.0.7'
implementation 'com.google.firebase:firebase-messaging:17.3.4'
implementation 'com.google.firebase:firebase-config:16.3.0'
```
There is also a SO question [here](https://stackoverflow.com/questions/54766725/android-firebase-remote-config-application-name-is-not-set-call-buildersetapp).

**Comment by dirkam** [comment]
Same happens when using the new 16.4.0 version.

**Comment by samtstern** [comment]
This warning comes from `AbstractGoogleClient` in the Google APIs Java library but I don't see why Remote Config would be using that...

**Comment by dirkam** [comment]
@samtstern 
16.3.0 switched to REST API, can it be the reason?

> The Firebase Remote Config SDK requires the Firebase Remote Config REST API. For Firebase projects created before March 7, 2018, you must manually enable the REST API. For more information, see our Remote Config REST API user guide.

**Comment by rinlv** [comment]
Does anyone have a solution? @shadowsheep1 @dirkam @samtstern

**Comment by shadowsheep1** [comment]
@rinlv Nope, no solution. But apart from the warning all works fine on my side.

**Comment by sixpi** [comment]
I'm still seeing this in version 17.0.0, its cluttering up our log messages so a solution would be great. I can't find any function named `setApplicationName` in the firebase SDK for Android.

**Comment by sixpi** [comment]
Any updates?

**Comment by matzesoft** [comment]
I'm also passing the exact same issue with @Flutter . Have anyone worked out a solution?

**Comment by leorachit** [comment]
Any solution for this?

**Comment by bubbleguuum** [comment]
Same here although it does not seem to have any side effect.

**Comment by gongelosP** [comment]
Any news on this issue ?

**Comment by Fernandomr88** [comment]
up

**Comment by sceee** [comment]
Also started for me popping up once FirebaseRemoteConfig was added.

**Comment by yjaquinas** [comment]
no solution yet :(

**Comment by bhanuka96** [comment]
this is working for me.

this is `Dart` language

adding  ` await remoteConfig.fetch(expiration: const Duration(seconds: 0));` and `await remoteConfig.activateFetched();`

```
  void _adminValidate() async {
    try{
      final RemoteConfig remoteConfig = await RemoteConfig.instance;
      await remoteConfig.fetch(expiration: const Duration(seconds: 0));
      await remoteConfig.activateFetched();
      print(remoteConfig.getString('admin'));
    }catch (e){
      print(e);
    }
  }
```

**Comment by bubbleguuum** [comment]
This benign warning has disappeared since upgrading to firebase-config 19.0.2

**Comment by shadowsheep1** [comment]
@bubbleguuum You're right! It seems so.
