### ISSUE TITLE
[Crashlytics NDK] When calling crashlytics C++ function, FirebaseCrashlytics (java) class not found

### ISSUE THREAD

**Issue by tellypresence** [firebase/firebase-android-sdk#2540]
Apologies, unable to comment on closed ("locked and limited") issue https://github.com/firebase/firebase-android-sdk/issues/2245 so raising new one for commenting purposes

Currently same issue happening after updating to recent rev 794d8f540125bd308caa1f3afa827ec56a3b35a7 

Anecodotally another report of the same error
https://stackoverflow.com/questions/66579256/didnt-find-class-firebasecrashlytics-on-path-dexpathlistdirectory-nat

**Comment by aguatno** [comment]
Hi @tellypresence thanks for reporting. Questions, how often is this error showing up? Are you able to provide code that we can run locally or steps that you took that led to this error?
