### ISSUE TITLE
How can I use Crashlytics to report a crash in multi-process?

### ISSUE THREAD

**Issue by linguokun1** [firebase/firebase-android-sdk#2549]
According to url:https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp#initializeApp(android.content.Context,%20com.google.firebase.FirebaseOptions)

Since "Any FirebaseApp initialization must occur only in the main process of the app. Use of Firebase in processes other than the main process is not supported and will likely cause problems related to resource contention", how can I use Crashlytics in multi-process?  If I have not use firebasedatabase and filestore and storage, if will occur similar "resource contention"?

**Comment by aguatno** [comment]
Hi @linguokun1 thanks for the question. It seems this is a feature request to support multi process see issue #1545. Note, that we have a great set of community members who are happy to help). These types of questions are best asked [over here](https://stackoverflow.com/questions/tagged/firebase) (questions on usage/etc).

You may also file on [Firebase Support ](https://firebase.google.com/support)page to better assist you with questions regarding this.
