### ISSUE TITLE
ClassNotFoundException: OpenSSLRSAPrivateCrtKey

### ISSUE THREAD

**Issue by MarceloMaia2** [firebase/firebase-android-sdk#2554]
**Environment**
Android Studio version: 4.1.3
Firebase Component: inappmessaging
Plugin version: com.google.firebase:firebase-inappmessaging-display:19.1.5

**The problem**
java.lang.ClassNotFoundException: com.google.android.gms.org.conscrypt.OpenSSLRSAPrivateCrtKey
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:453)
at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1615)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1776)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2002)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1926)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1803)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)

When I add firebase-inappmessaging-display to my project, it breaks another flow of my application.

**Comment by MarceloMaia2** [comment]
The issue happens when I'm going to deserialize an byte array, that returns an KeyPair object, throwing this exception. This only happen when I add InApp Messaging SDK to my project.

**Comment by aguatno** [comment]
Hi @MarceloMaia2. I’m finding it quite difficult replicating your issue without an [mcve](https://stackoverflow.com/help/minimal-reproducible-example), could you able to provide a minimal runnable repro of your app so I can also test this one locally? Thanks

**Comment by gsakakihara** [comment]
Are you serializing the KeyPair object in the app that you are adding firebase-inappmessaging-display to? Also, the deserializing is not related to InApp Messaging, right? It's just that adding the firebase-inappmessaging-display dependency to your project causes this completely separate part to throw an exception?

**Comment by gsakakihara** [comment]
This could be happening if one of firebase-inappmessaging-display's dependencies is installing the Google Play services RSA provider (probably com.google.android.gms:play-services-basement). The Google Play services provider would return that Key class that is not visible to your app's ClassLoader, so it would fail to deserialize it.

One suggestion I have seen to work around this would be to convert the Key to an instance of a different provider before serializing it. Something like:

KeyFactory.getInstance("RSA", "AndroidOpenSSL").translateKey(key);

http://developer.android.com/reference/java/security/KeyFactory.html#translateKey(java.security.Key)

**Comment by MarceloMaia2** [comment]
> KeyFactory.getInstance("RSA", "AndroidOpenSSL").translateKey(key);

My object is a KeyPair.

  ```
      KeyPairGenerator keyGen = null;
        KeyPair keyPair = null;
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                keyGen = KeyPairGenerator.getInstance("RSA");
            } else {
                keyGen = KeyPairGenerator.getInstance("RSA", "BC");
            }
            keyGen.initialize(1024);
            keyPair = keyGen.genKeyPair();
        } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
            e.printStackTrace();
        }
```

**Comment by MarceloMaia2** [comment]
> Hi @MarceloMaia2. I’m finding it quite difficult replicating your issue without an [mcve](https://stackoverflow.com/help/minimal-reproducible-example), could you able to provide a minimal runnable repro of your app so I can also test this one locally? Thanks

To generate RSA:
public static KeyPair generateRSAKeyPair() {
        KeyPairGenerator keyGen = null;
        KeyPair keyPair = null;
        try {
            keyGen = KeyPairGenerator.getInstance("RSA");
            keyGen.initialize(1024);
            keyPair = keyGen.genKeyPair();
        } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
            e.printStackTrace();
        }
        return keyPair;
    }

To serialize:
public static byte[] serializeClientKeyPair(KeyPair clientKeyPair) {
        ByteArrayOutputStream b = new ByteArrayOutputStream();
        ObjectOutputStream o;
        try {
            o = new ObjectOutputStream(b);
            o.writeObject(clientKeyPair);
        } catch (IOException e) {
            e.printStackTrace();
        }
        byte[] res = b.toByteArray();
        return res;
    }

And to deserialize:
public static KeyPair deserializeKeyPair(byte[] serializedKeyPair) {
        ByteArrayInputStream bi = new ByteArrayInputStream(serializedKeyPair);
        ObjectInputStream oi;
        Object obj = null;
        try {
            oi = new ObjectInputStream(bi);
            obj = oi.readObject();
            L.d(TAG, ((KeyPair) obj).toString());
        } catch (StreamCorruptedException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return ((KeyPair) obj);
    }
Exception is thrown at obj = oi.readObject(); when doing the steps:
KeyPair keyPair = generateRSAKeyPair();
                byte[] serialized = serializeClientKeyPair(keyPair);
                KeyPair deserializeKeyPair = deserializeKeyPair(serialized);

**Comment by MarceloMaia2** [comment]
Hi @aguatno , using com.google.firebase:firebase-inappmessaging-display:19.1.5 and with this code provided, you should be able to reproduce the error. Thanks in advance.

> > Hi @MarceloMaia2. I’m finding it quite difficult replicating your issue without an [mcve](https://stackoverflow.com/help/minimal-reproducible-example), could you able to provide a minimal runnable repro of your app so I can also test this one locally? Thanks
> 
> To generate RSA:
> 
> ```
> public static KeyPair generateRSAKeyPair() {
>         KeyPairGenerator keyGen = null;
>         KeyPair keyPair = null;
>         try {
>             keyGen = KeyPairGenerator.getInstance("RSA");
>             keyGen.initialize(1024);
>             keyPair = keyGen.genKeyPair();
>         } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
>             e.printStackTrace();
>         }
>         return keyPair;
>     }
> ```
> 
> To serialize:
> 
> ```
> public static byte[] serializeClientKeyPair(KeyPair clientKeyPair) {
>         ByteArrayOutputStream b = new ByteArrayOutputStream();
>         ObjectOutputStream o;
>         try {
>             o = new ObjectOutputStream(b);
>             o.writeObject(clientKeyPair);
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>         byte[] res = b.toByteArray();
>         return res;
>     }
> ```
> 
> And to deserialize:
> 
> ```
> public static KeyPair deserializeKeyPair(byte[] serializedKeyPair) {
>         ByteArrayInputStream bi = new ByteArrayInputStream(serializedKeyPair);
>         ObjectInputStream oi;
>         Object obj = null;
>         try {
>             oi = new ObjectInputStream(bi);
>             obj = oi.readObject();
>         } catch (StreamCorruptedException e) {
>             e.printStackTrace();
>         } catch (IOException e) {
>             e.printStackTrace();
>         } catch (ClassNotFoundException e) {
>             e.printStackTrace();
>         }
>         return ((KeyPair) obj);
>     }
> ```
> 
> When including FIAM SDK to the project, with an Android >=9, exception is thrown at `obj = oi.readObject();` when doing the steps:
> 
> ```
> KeyPair keyPair = generateRSAKeyPair();
>                 byte[] serialized = serializeClientKeyPair(keyPair);
>                 KeyPair deserializeKeyPair = deserializeKeyPair(serialized);```
> ```

**Comment by aguatno** [comment]
Hi @MarceloMaia2 Sorry for waiting. I wasn't able to see the class exception on the latest SDK, have you tried updating to the latest and let me know if the issue persists? Thanks.

**Comment by aguatno** [comment]
Hi @MarceloMaia2 Thanks. Our engineers are currently looking into that issue. To avoid duplicate efforts, let me know if we can tag this as duplicate thanks.

**Comment by MarceloMaia2** [comment]
Hello @aguatno , thanks for the info! Yes, you can tag this as duplicate.

**Comment by aguatno** [comment]
Thanks :)
