### ISSUE TITLE
Only updated documents & cache size and limitations

### ISSUE THREAD

**Issue by SergejSachs** [firebase/firebase-android-sdk#2557]
I have for example portfolios. On every app start all portfolios will be fetched from the server.
This will sum up pretty fast.

What if I call first a method only to get the documents from Firestore with a greater timestamp compared to the latest timestamp from my cached items.

```
Future _updateCache(AppUser user) async {
    var cachedSnapshot = await _getCachedPortfolios(user);
    var lastUpdatedCached = _getLastUpdatedCached(cachedSnapshot);

    await _firestore
        .collection('portfolios')
        .where('uid', isEqualTo: user.id)
        .where('updatedAt', isGreaterThan: lastUpdatedCached)
        .get();
  } 
```

After that I could just get all items from cache

```
var cachedsnapshot = await _firestore
        .collection('portfolios')
        .where('uid', isEqualTo: user.id)
        .orderBy('updatedAt', descending: true)
        .get(GetOptions(source: Source.cache));
    return cachedsnapshot;
```

This works but im not sure if this would break at some point if the cache gets to big or can't cleared because everything "is in use" whatever this means for firebase

**Comment by aguatno** [comment]
Hi @SergejSachs thanks for the feedback. For Flutter+Firebase please file feature request here
https://github.com/FirebaseExtended/flutterfire.

**Comment by thebrianchen** [comment]
Thanks for writing in @SergejSachs!

The query you're running can be garbage collected if the cache gets too large, but you can disable garbage collection by specifying [CACHE_SIZE_UNLIMITED](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreSettings#CACHE_SIZE_UNLIMITED) with `setCacheSizeBytes()`. I'm going to mark this issue as closed, but feel free to ask any followup questions you may have!

**Comment by SergejSachs** [comment]
Thanks for your fast reply! 

I went another approach with less caching, more like paged caching.
There should be less issues like this but I will take a look how the cache will play out then on bigger data sizes and report here again. 

Thx for your help.
