### ISSUE TITLE
Searching substring among fields of type string. Similar feature to LIKE keyword in MySQL

### ISSUE THREAD

**Issue by donik1998** [firebase/firebase-android-sdk#2558]
## What feature would you like to see?

Hi, I am so excited to use Firebase in my projects. We are working on the second app that uses all the juice of this wonderful peice of tech. We wonder if you could add the feature, which could allow us to search a substring in documents of Firestore.

## How would you use it?

We are going to implement search by first name of the user in Firestore collection, but all we can do is searching by prefix. Considering that names in our country is written in such way that surname comes first. This is why we can't use search by prefix to filter people with the same first names.

P.S. I didnt't find Firebase Flutter/Dart SDK, so I decided to request a feature here

Best wishes, 
Doniyor Murodkulov pattionate Flutter developer and student at INHA University in Tashkent

**Comment by aguatno** [comment]
Hi @donik1998 this seems to be a feature request for Flutter. If so, for Flutter+Firebase please file feature request here
https://github.com/FirebaseExtended/flutterfire.
