### ISSUE TITLE
Null object reference on MethodChannelFirebaseAuth.verifyPhoneNumber 

### ISSUE THREAD

**Issue by dcresnitzky** [firebase/firebase-android-sdk#2560]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.0
  * Firebase Component: Auth
  * Component version: 1.0.1
  *
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
[√] Connected device (3 available)

• No issues found!
```

#### Steps to reproduce:

When verifyPhoneNumber is called on <s>emulator and</s> samsung s20 plus got following error
```
[ +772 ms] E/flutter ( 4570): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [firebase_auth/unknown] Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
[        ] E/flutter ( 4570): #0      MethodChannelFirebaseAuth.verifyPhoneNumber (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:623:7)
[        ] E/flutter ( 4570): <asynchronous suspension>
```

```
#android/app/build.gralde
...
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.firebase:firebase-messaging:21.0.1'
    implementation 'com.google.firebase:firebase-analytics:18.0.2'
    implementation "androidx.fragment:fragment:1.3.2"
    implementation "androidx.browser:browser:1.3.0"
}
```

#### Relevant Code:

In login screen:
```
  void _validateAndSubmit() async {
    final form = _formKey.currentState;
    FocusScope.of(context).unfocus();

    if (form.validate()) {
      form.save();
      setLoading(true);
      await _authenticationProvider.getUserInfo(_email, _password);
      await FirebaseAuth.instance.verifyPhoneNumber(
          phoneNumber: _authenticationProvider.phone,
          timeout: const Duration(seconds: 60),
          verificationCompleted: (PhoneAuthCredential credential) async {
            await FirebaseAuth.instance.signInWithCredential(credential);
          },
          verificationFailed: (FirebaseAuthException e) {
            if (e.code == 'invalid-phone-number') {
              print('The provided phone number is not valid.');
            }
          },
          codeSent: (String verificationId, int resendToken) async {
            setLoading(false);
            Navigator.of(context).push(CupertinoPageRoute(builder: (BuildContext context) => PhoneAuthVerify()));
          },
          codeAutoRetrievalTimeout: (String verificationId) {
            // Auto-resolution timed out...
          });
  }

```

**Comment by aguatno** [comment]
Hi @dcresnitzky as I observe in the log you have a null object reference, this happens when a variable or object is not declared or initialised properly. Could you try bumping the Firebase Auth product you are using to the latest versions?

Also, please try replicating the issue in our [quickstart app](https://github.com/firebase/quickstart-android/tree/master/auth) as this uses the latest version of the SDK. This could also help us pinpoint what's the real cause of your issue.

**Comment by malcolmdeck** [comment]
This issue appears to be with the Flutter implementation - that class exists in Dart, not Android. I think you'll need to reroute the issue to here:
https://github.com/FirebaseExtended/flutterfire/issues

**Comment by aguatno** [comment]
Hi @dcresnitzky Given that this issue is more of Flutter implementation rather than Firebase itself. We suggest filing an issue here https://github.com/FirebaseExtended/flutterfire/issues.

I'll be closing this for now. However, if you are able to replicate the mentioned issue only with native tools we can take a look and try to find a solution.
