### ISSUE TITLE
Firebase messaging does not work when initialized in a separate Android process

### ISSUE THREAD

**Issue by abhinavchdhry** [firebase/firebase-android-sdk#2561]
I've been trying to offload Firebase messaging in our app to a separate Android process and I've had no luck so far. 

Using Firebase-messaging:18.0.0

The first thing I tried was to make sure the `FirebaseListenerService` (our subclass of `FirebaseMessagingService`) runs in a separate process. Because of our application design, we use a `CustomFirebaseInitProvider` and override the default `FirebaseInitProvider`. This `CustomFirebaseInitProvider` also initializes Firebase app in the auxiliary process.

```
<application>
    <service
        android:name=".push.fcm.FirebaseListenerService"
        android:process="com.xxx.yyy.someprocess"
        android:enabled="true"
        android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>

    <!-- Disable default FirebaseInitProvider -->
    <provider android:name="com.google.firebase.provider.FirebaseInitProvider"
        tools:node="remove" />

    <provider android:authorities="${applicationId}.firebaseinitprovider"
        android:name=".push.fcm.provider.CustomFirebaseInitProvider"
        android:process="com.xxx.yyy.someprocess"
        android:exported="false"
        android:initOrder="100">
    </provider>
  </application>
```

This has the effect of creating the `FirebaseListenerService` in a separate process upon receiving the `MESSAGING_EVENT` intent. I am also able to verify that the FirebaseApp instance was instantiated in the auxiliary process.

However, on sending notifications, the `onMessageReceived` handler in `FirebaseListenerService` never gets called. Although a `MESSAGING_EVENT` intent is always sent to create the `FirebaseListenerService` everytime.

After some investigation I realized the `com.google.android.c2dm.intent.RECEIVE` intent ([which causes message delivery to FirebaseMessagingService and thus to onMessageReceived](https://github.com/firebase/firebase-android-sdk/blob/e65f4876ff61b5791986c249b21cb094c37bd29e/firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java#L197)) was being received only in the main process, but not in the auxiliary process. This is because the Firebase SDK internally adds the `FirebaseInstanceIdReceiver` to the app manifest and it comes up in the main process.

```
<receiver
        android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
        android:permission="com.google.android.c2dm.permission.SEND"
        android:enabled="false"
        android:exported="true">
      <intent-filter>
        <action
            android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </receiver>
```

So I also override this to be brought up in the auxliary process. Also realized it might be necessary to bring up the `ComponentDiscoveryService` in the auxiliary process too:

```
<receiver
        android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
        android:process="com.xxx.yyy.someprocess"
        android:permission="com.google.android.c2dm.permission.SEND"
        android:enabled="false"
        android:exported="true"
        tools:node="merge">
      <intent-filter>
        <action
            android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </receiver>

<service
        android:name="com.google.firebase.components.ComponentDiscoveryService"
        android:process="com.xxx.yyy.someprocess"
        android:exported="false"
        android:directBootAware="true"
        tools:node="merge">

      <meta-data
          android:name="com.google.firebase.components:com.google.firebase.dynamicloading.DynamicLoadingRegistrar"
          android:value="com.google.firebase.components.ComponentRegistrar" />

      <meta-data
          android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
          android:value="com.google.firebase.components.ComponentRegistrar" />
    </service>
```

After this change, the auxiliary process never comes up and I do not see any `com.google.android.c2dm.intent.RECEIVE` intents being received on notification send. I would have expected this to  initialize `FirebaseInstanceIdReceiver` on notification send, but maybe my limited understanding of the Firebase SDK is totally off. Any pointers on how to initialize Firebase on a separate process?

**Comment by gsakakihara** [comment]
Can you tell if FirebaseInstanceIdReceiver is receiving the message broadcast? From the manifest snippet that you have posted, I noticed that you have set android:enabled="false" in the merged receiver.

**Comment by abhinavchdhry** [comment]
The `android:enabled="false"` is auto-added to the manifest by the SDK, it's not my change. Either way, I changed that to `android:enabled="true"` and that does not solve the issue.

> Can you tell if FirebaseInstanceIdReceiver is receiving the message broadcast?

I'm not sure how this can be checked since the auxiliary process (where `FirebaseInstanceIdReceiver` is supposed to be initialized) never comes up at all. I could check this with some logging but the `firebase-iid` module is closed source from what I gather

**Comment by abhinavchdhry** [comment]
Also curious what system component sends out the `com.google.android.c2dm.intent.RECEIVE` when notifications are received?

**Comment by gsakakihara** [comment]
I assumed that:

`<receiver
        android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
        android:process="com.xxx.yyy.someprocess"
        android:permission="com.google.android.c2dm.permission.SEND"
        android:enabled="false"
        android:exported="true"
        tools:node="merge">
      <intent-filter>
        <action
            android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </receiver>`

was the part that you added to the manifest. Can you check the manifest of the apk you're testing and see how the FirebaseInstanceIdReceiver is being declared there?

https://firebase.google.com/support/troubleshooter/fcm/delivery/diagnose/android

If you're able to view the FCM Diagnostics, you should be able to see from the logs whether the broadcast was delivered to the app.

Messages are sent from Google Play services.
