### ISSUE TITLE
185090180: Dynamic Links - Mismatch in app clicks and re-opens

### ISSUE THREAD

**Issue by chongwyb** [firebase/firebase-android-sdk#2565]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.3
  * Firebase Component: Dynamic Links
  * Component version: BoM 26.1.0

### [REQUIRED] Step 3: Describe the problem

We are using dynamic links to monitor users' Clicks and Re-opens, however we noticed that the behaviour is inconsistent.

#### Steps to reproduce:

Approach 1
Tap on dynamic link to open the installed app

- Clicks is recorded
- Re-opens is not recorded

Approach 2
Paste dynamic link on chrome app to open the installed app

- Clicks is recorded
- Re-opens is recorded

#### Relevant Code:

As dynamic_link_app_open is an automatically collected event, no additional code was implemented.

**Comment by mikehardy** [comment]
Cross-linking with react-native-firebase initiating issue https://github.com/invertase/react-native-firebase/issues/5110

**Comment by aguatno** [comment]
Hi @chong-shao Dynamic Links are intended to be clicked upon to avoid opening behavior issues. You could try troubleshooting using the [DebugView](https://firebase.google.com/docs/analytics/debugview#ios) to verify that the dynamic_links_* events are being logged. Additionally, make sure that you're using the latest Firebase SDK version.

If the issue persists, can you share a sample runnable app and complete steps to reproduce the issue? This will help us further investigate the issue on the discrepancy between the app re-open and clicks.

**Comment by chong-shao** [comment]
Hi I think the last comment tagged the wrong person. Should be @chongwyb

**Comment by chongwyb** [comment]
Hi @aguatno, the issue still persist where the Re-opens count is not being recorded.

Tested on both BoM 26.1.0 and 26.8.0 (latest).
DebugView is able to log the dynamic_links_app_open event consistently.
From Firebase console, Clicks not equal to Re-opens.

Here is a [minimal repository](https://github.com/jiansheng-gt/quickstart-android/tree/master/dynamiclinks) that I have tested on. 
Step 1 : Tap on a given dynamic link which directly opens the installed app

**Comment by aguatno** [comment]
Hi @chongwyb thanks for the MCVE. Question, could you verify if there’s a discrepancy ( app reopens vs clicks ) using the [REST API](https://firebase.google.com/docs/dynamic-links/analytics#rest_api)? You can get event counts using this API regardless whether the Dynamic Link is created via the console or programmatically. This will help us determine if the issue is isolated to the Dynamic Links dashboard.

Thanks.

**Comment by chongwyb** [comment]
Hi @aguatno , I have tested with the REST API and I am getting the same result as the Dynamic Links dashboard.

**Comment by aguatno** [comment]
Hi @chongwyb Sorry for the wait. Per checking, it seems this is a known issue to the SDK, and currently being worked on by the engineers (Reference Bug#185090180). I'll let you know if there's any update.

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
