### ISSUE TITLE
The Firebase Crashlytics mappingFile parameter is incompatible with the Android Gradle Plugin 4.1+ 

### ISSUE THREAD

**Issue by timrijckaert** [firebase/firebase-android-sdk#2567]
* Android Studio version:  4.1.3
* Firebase Component:  Crashlytics
* Firebase Crashlytics  Gradle Plugin: 2.5.2
* Android Gradle Plugin: 4.1.3

We are trying to upload our `mapping.txt` generated from Dexguard to Firebase Crashlytics using the Firebase Crashlytics Gradle plugin.  
We followed the instructions found [here](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=android).
This is our Crashlytics configuration

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "com.google.gms.google-services"
    id "com.google.firebase.crashlytics"
    id "dexguard"
}

productFlavors {
    brand1 {
        dimension "brand"

        firebaseCrashlytics {
            mappingFile "${project.buildDir}/outputs/apk/brand1/release/mapping.txt"
            mappingFileUploadEnabled true
        }
    }

    brand2 {
        dimension "brand"

        firebaseCrashlytics {
            mappingFile "${project.buildDir}/outputs/apk/brand2/release/mapping.txt"
            mappingFileUploadEnabled true
        }
    }
 }
```

This was working fine in  Android Gradle plugin from `4.0.2`.
However when we upgraded to `4.1.3` we get the following stacktrace in our build log.  

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > org.gradle.api.GradleException: The Firebase Crashlytics mappingFile parameter is incompatible with the Android Gradle Plugin 4.1+
     and will be removed in future versions of the Firebase Crashlytics Gradle plugin.
     Please contact https://firebase.google.com/support/troubleshooter/contact if you have additional questions.
```

We only found this particular error message in the release notes of the [Crashlytics Gradle Plugin](https://firebase.google.com/support/release-notes/android#crashlytics_gradle_plugin_v2-0-0-beta04).
No upgrade guide was found so that we can still use the `mappingFile` option since we obfuscate with Dexguard.  
In fact the documentation doesn't even state the `mappingFile` option all together we had to figure this one out by looking in to other projects....... 

For now we are either stuck using AGP `4.0.3` or we use a script to de-obfuscate the stacktraces ourselves, but is tedious as you can imagine.

Where is the missing documentation about uploading a custom `mappingfile`?

Thanks in advance

**Comment by mrichards** [comment]
If you have the latest versions of both the DexGuard and Crashlytics plugins, the Crashlytics plugin should now be able to find the mapping file automatically! If you remove the `mappingFile` extension option, you should get deobfuscated stack traces.

I'm going to close this issue, though please reopen if that does not work for you. In that case, please attach the Crashlytics-specific debug output from the plugin. Example:

`> ./gradlew app:assemble<VARIANT> --debug | grep "\[com.google.firebase.crashlytics\]"
