### ISSUE TITLE
Linking accounts from Anonymous user to authorized leads to data loss (!)

### ISSUE THREAD

**Issue by RohovDmytro** [firebase/firebase-android-sdk#2579]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: I'm using `react-native-firebase` (see https://github.com/invertase/react-native-firebase/issues/4911)
  * Firebase Component: auth
  * Component version: latest as of April 11 2021

### [REQUIRED] Step 3: Describe the problem

1. Authorize with Google Account. Log out.
2. Authorize with anonymous user. Link account.
3. It does the linking not yielding error that it is NOT possible to link Anonymous account to the existing one.

By doing the following actions all data created by anonymous user is lost. But it was clear that I needed account linking.

**Comment by aguatno** [comment]
Hi @RohovDmytro, 

I'm getting this "The email address is already in use by another account" error when linking my Google account on Step#2. Could you be able to reproduce the issue using [quickstart](https://github.com/firebase/quickstart-android)? it would be helpful if we had a reproduction case. Can you show me a minimal, verifiable example that triggers this?

Thanks
