### ISSUE TITLE
Firebase-analytics adds Ad dependecy

### ISSUE THREAD

**Issue by shumidub** [firebase/firebase-android-sdk#2582]
When I'm using com.google.firebase:firebase-analytics:18.0.2 package com.google.android.gms.ads.identifier.AdvertisingIdClient appears into my apk. And Play Console show warning "Ad SDK found"

![изображение](https://user-images.githubusercontent.com/28213564/114422487-ff0bff80-9bbe-11eb-86ea-3fc297936641.png)

I want to have a way to use firebase analytics without AD SDK.

Similar issue https://github.com/invertase/react-native-firebase/issues/3617

**Comment by aguatno** [comment]
Hi @shumidub  thanks for reaching out. Per this [help center article](https://support.google.com/firebase/answer/6318039): "_By default, the Firebase SDK collects identifiers for mobile devices (for example, Android Advertising ID and Advertising Identifier for iOS) ..._"

This is done to enable attribution, as well as reporting on demographics and interests. If you'd like to continue reporting Ad ID, Google Play now requires publishers that collect Ad ID to submit a privacy policy. Otherwise If the developer doesn't want to collect Ad ID, they can [disable collection](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#disable_advertising_id_collection) instead.

**Comment by shumidub** [comment]
But after add meta-data to Manifest Ads classes also is in apk 
![изображение](https://user-images.githubusercontent.com/28213564/114707166-92197680-9d32-11eb-810e-43322c51e449.png)


And Google Play show warning
![изображение](https://user-images.githubusercontent.com/28213564/114707222-a3fb1980-9d32-11eb-82db-d7cebaf16263.png)

**Comment by mobilase** [comment]
I have same error on Google Play (And I havn't this error month ago):
![Безымянный](https://user-images.githubusercontent.com/1146694/115035460-4521d580-9ed5-11eb-9205-2cc758721bb2.png)
But in my project havn't AdMob, only Firebase:
![AndroidStudio](https://user-images.githubusercontent.com/1146694/115036026-cda07600-9ed5-11eb-97ea-04e162393d30.png)
```    
// Firebase
    implementation platform('com.google.firebase:firebase-bom:26.6.0')
    implementation 'com.google.firebase:firebase-core'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
```

**Comment by mobilase** [comment]
How I can delete AdMob SDK from App without deleting Firebase?

**Comment by mobilase** [comment]
Thanks [https://github.com/invertase/react-native-firebase/issues/3617](https://github.com/invertase/react-native-firebase/issues/3617).
The problem with AdMob SDK  is in `com.google.android.gms:play-services-ads-identifier` that is inside `com.google.firebase:firebase-core` and `com.google.firebase:firebase-analytics`

For fixing I change my dependencing like this:

```
    // Firebase
    implementation platform('com.google.firebase:firebase-bom:26.6.0')
    implementation ('com.google.firebase:firebase-core') {
        exclude group: 'com.google.android.gms', module : 'play-services-ads-identifier'
    }
    implementation ('com.google.firebase:firebase-messaging') {
        exclude group: 'com.google.android.gms', module : 'play-services-ads-identifier'
    }
    implementation ('com.google.firebase:firebase-crashlytics') {
        exclude group: 'com.google.android.gms', module : 'play-services-ads-identifier'
    }
    implementation ('com.google.firebase:firebase-analytics') {
        exclude group: 'com.google.android.gms', module : 'play-services-ads-identifier'
    }
```

And now my Firebase working and Google Play don't show warnings:
![GooglePlay](https://user-images.githubusercontent.com/1146694/115235610-0d0fd200-a123-11eb-80fb-ebb9e3a86dc1.png)

**Comment by mobilase** [comment]
Unfortunately this error came again, and my fixing don't working :(
May be it becouse Google AdMob test needs time to update information.
![AdMob](https://user-images.githubusercontent.com/1146694/117189792-42851280-ade7-11eb-808f-0bf37cc54ce7.png)

Perhaps this fix will help. I'll write about the results later.

```
configurations.all {
    exclude group: 'com.google.android.gms', module : 'play-services-ads'
    exclude group: 'com.google.android.gms', module : 'play-services-ads-identifier'
    exclude group: 'com.google.android.gms', module : 'play-services-ads-lite'
}

dependencies {
// ...
    // Firebase
    implementation platform('com.google.firebase:firebase-bom:26.6.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
// ...
}
```

**Comment by mobilase** [comment]
Unfortunatelly my fix not working :(
Does anybody knows how to fix it?

**Comment by shumidub** [comment]
Analytics use: The advertising identifier may only be connected to personally-identifiable information or associated with any persistent device identifier (for example: SSAID, MAC address, IMEI, etc.) with the explicit consent of the user

https://support.google.com/googleplay/android-developer/answer/10808976?hl=en

**Comment by shumidub** [comment]
I want to disable collecting ads id from my application for my peace of mind

**Comment by shumidub** [comment]
And I want to remove com.google.android.gms:play-services-ads-identifier dependency from my app to hide "Ads warning" in the Play Console

**Comment by mobilase** [comment]
> Hi all, Sorry for getting back late. To disable id collection, please follow our guide [here](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#disable_advertising_id_collection) and I've submitted a request to fix the Ads warning in Google Play. I'll keep you posted.

I add to AndroidManifest.xml:
<meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />

But after publish to GooglePlay I get subject "SDK AdMob" again. And [this](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#disable_advertising_id_collection) not fixed the problem.

**Comment by mobilase** [comment]
> Analytics use: The advertising identifier may only be connected to personally-identifiable information or associated with any persistent device identifier (for example: SSAID, MAC address, IMEI, etc.) with the explicit consent of the user
> 
> https://support.google.com/googleplay/android-developer/answer/10808976?hl=en

Sorry, this page can't be found.

**Comment by mobilase** [comment]
Dear developers of Firebase. Can you connect to developers of GooglePlay? You have been working for the same company Google. Please fix this bug with developers of GooglePlay. May be this bug in GooglePlay?

**Comment by mericgerceker** [comment]
Hello. Are there any new developments for issue?

**Comment by lordcodes** [comment]
You can just add to the AndroidManifest to remove the 'AD_ID' permission and then also tell the Firebase Analytics SDK not to collect it.

The documentation for the class included by the play-services-ads-identifier, explains how the AD ID is used and how to avoid any transitive dependencies from adding the permission.

https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient.Info#getId()

AndroidManifest.xml
```
<uses-permission
        android:name="com.google.android.gms.permission.AD_ID"
        tools:node="remove" />

<meta-data
            android:name="google_analytics_adid_collection_enabled"
            android:value="false" />
```

**Comment by Bardiamist** [comment]
Faced with same issue

![image](https://user-images.githubusercontent.com/22082342/181493275-d5497024-d880-4b42-826d-732756037d0d.png)

Will `firebase.json`
```
{
  "react-native": {
    "google_analytics_adid_collection_enabled": false
  }
}
```
work instead of
```
<uses-permission
    android:name="com.google.android.gms.permission.AD_ID"
    tools:node="remove" />
```
?

Of course with
```
<uses-permission
    android:name="com.google.android.gms.permission.AD_ID"
    tools:node="remove" />
```

**Comment by EverGreeff** [comment]
> D

This not work with a android studio Firebase project, the permission is not on the merged manifest anymore, but google still showing the erro message

**Comment by deepak786** [comment]
![Screen Shot 2022-07-27 at 1 32 59 PM](https://user-images.githubusercontent.com/14223997/181604314-f269859f-40bb-4e04-9461-a5600887eb79.png)

I just selected yes in the Play Console.

**Comment by M001T** [comment]
> ![Screen Shot 2022-07-27 at 1 32 59 PM](https://user-images.githubusercontent.com/14223997/181604314-f269859f-40bb-4e04-9461-a5600887eb79.png)
> 
> I just selected yes in the Play Console.

you just selected yes and worked ?

**Comment by deepak786** [comment]
@M001T Yes.

**Comment by kunwar295** [comment]
I have Contacted to Google Play support they replied that if you use analytics, you need to choose **YES** on The AD_ID permission for analytics use case on **Advertising ID section**.

You should not remove permission manually or remove analytics sub-modules which contains AD_ID permission since it can break things...

So just need to choose YES even if the app is not using Ads
All you have to do is:
Go to Google play console **App Content** -> **Advertising ID** section -> Choose **Yes** and mark the **Analytics** option and check Turn off release errors check box

![Ktc60](https://user-images.githubusercontent.com/64700617/183359780-f1d38b35-8db2-414e-9ce5-25cba31cba9b.png)
.

**Comment by M001T** [comment]
ok, i selected "analytics and yes"

i have <uses-permission android:name="com.google.android.gms.permission.AD_ID" /> on my manifest, the only lib with data collect i have is firebase_analytics

but the app still on "review"

**Comment by FauziAmth** [comment]
> I have Contacted to Google Play support they replied that if you use analytics, you need to choose **YES** on The AD_ID permission for analytics use case on **Advertising ID section**.
> 
> You should not remove permission manually or remove analytics sub-modules which contains AD_ID permission since it can break things...
> 
> So just need to choose YES even if the app is not using Ads All you have to do is: Go to Google play console **App Content** -> **Advertising ID** section -> Choose **Yes** and mark the **Analytics** option and check Turn off release errors check box
> 
> ![Ktc60](https://user-images.githubusercontent.com/64700617/183359780-f1d38b35-8db2-414e-9ce5-25cba31cba9b.png) .

Why would they need to ask if they force it anyway?

IMO App functionality, Analytics & Developer Communications should be seperated from "advertising ID"

**Comment by danielesegato** [comment]
@aguatno please this is become urgent. Google Play now block apps from releasing

![Screenshot from 2022-09-26 17-22-27](https://user-images.githubusercontent.com/469948/192343237-7933b2da-a53d-4391-be04-20ab2076803f.png)

My app doesn't have ads. Just Firebase Analytics

Even doing all this the google play still complains:

in the manifest
```
<uses-permission
        android:name="com.google.android.gms.permission.AD_ID"
        tools:node="remove" />
```

inside application tag
```
<meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
```

and dependency:

```
    implementation(platform("com.google.firebase:firebase-bom:30.4.1")
    implementation("com.google.firebase:firebase-analytics-ktx") {
        exclude(module = "play-services-ads-identifier")
    }
```

Nothing, the Google Play still complains with that error when trying to create a new release

**Comment by argzdev** [comment]
Hi @danielesegato, could you try removing the code you've altered, and add the [solution](https://github.com/firebase/firebase-android-sdk/issues/2582#issuecomment-1207751116) provided by kunwar295? If I'm not mistaken, declaring that Advertising ID is being used in Analytics should remove the error.

I don't think there's any more issue here since this should be working after proper declaration in Google Play Console. Let me know if this works.

**Comment by moertel** [comment]
@danielesegato and others - for some reason adding `<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove" />` is what **caused** the permission to appear in my merged manifest. As soon as I removed this line, everything was fine.

## Firebase services I use
My app includes no ads whatsoever. All I want is crashlytics, performance monitoring and analytics:
```
dependencies {
    implementation platform('com.google.firebase:firebase-bom:29.1.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-perf'
    implementation 'com.google.firebase:firebase-firestore'
}
```

## Configuration that worked for me
With the configuration as below I was able to get rid of the warning in GooglePlay console:
`app/build.gradle`
```
configurations.all {
    exclude group: 'com.google.android.gms', module : 'play-services-ads'
    exclude group: 'com.google.android.gms', module : 'play-services-ads-identifier'
    exclude group: 'com.google.android.gms', module : 'play-services-ads-lite'
}
```
`app/src/main/AndroidManifest.xml`
```
    <meta-data android:name="google_analytics_adid_collection_enabled" android:value="false" />
    <meta-data android:name="google_analytics_default_allow_ad_personalization_signals" android:value="false" />
```

Again, if you have the following line in your AndroidManifest, ⚠️**try removing it**.
```
<!-- remove this -->
<uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove" />
```

**Comment by jeiea** [comment]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/4188984/193052626-b7f74cf1-0e51-4fb9-868c-dc9b8fdfdea9.png">
I'm seeing this even if I remove all app bundles in the release.

I want explicit documentation for requiring Ad ID usage declaration for analytics dependency. Is it play store bug or requirements? I can't know.

**Comment by argzdev** [comment]
Hi @jeiea, you could check out the [documentation](https://support.google.com/analytics/answer/11593727?hl=en) which contains the explanation for requiring Ad ID, under the section of _**Identifiers for mobile devices**_.

> The Google Analytics for Firebase SDK automatically generates and assigns an app-instance identifier to each instance of your app. Analytics uses the ID to identify unique installations of your app and compute user metrics. Learn more about [the app-instance ID](https://support.google.com/analytics/answer/9268042#app-instance-id).

> By default, the SDK collects identifiers for mobile devices (for example, Android Advertising ID and Advertising Identifier for iOS) and uses technologies similar to cookies.

As for the issue, I assume this is a bug where even if you remove all your app bundle, the most recent app bundle is still retained (you would notice this when you try to upload the same app bundle again, an error would come out), but I could be wrong though. That said, I think it would be best to reach out to the [Play Console help](https://support.google.com/googleplay/android-developer/gethelp) support. Alternatively, updating your declaration will remove the error.

**Comment by mobilase** [comment]
Solution of **kunwar295** is not for me. Because I need to control that Advertising ID not used in my app.

Solution of **moertel** interested and I test it when I get back to development of Android app with Firebase.
But I test similar [solution](https://github.com/firebase/firebase-android-sdk/issues/2582#issuecomment-822424745) and this is not working (see my next [comment](https://github.com/firebase/firebase-android-sdk/issues/2582#issuecomment-839607846))

**Comment by argzdev** [comment]
Got it, let me know if [moertel's](https://github.com/firebase/firebase-android-sdk/issues/2582#issuecomment-1261875254) solution works.

**Comment by danielesegato** [comment]
> Hi @danielesegato, could you try removing the code you've altered, and add the [solution](https://github.com/firebase/firebase-android-sdk/issues/2582#issuecomment-1207751116) provided by kunwar295? If I'm not mistaken, there's no extra code setup needed. All that's needed is the declaration that an Advertising ID is being used in third party library (Firebase Analytics). This can be done through your **Google Play Console**, and that should be sufficient enough to remove the error.
> 
> I don't think there should be any more issue here since this should be working after proper declaration in Google Play Console. I'll close this issue for now. If this is still not working, let me know and I'll reopen the issue. Thanks!

@argzdev I as you suggested: I declared my app uses AD ID for analytics by third party.

I was afraid this would make my app show as "Contain Ads" or something like that but it didn't. I still find it a bit odd that something about "AD" is needed for analytics but I'm OK with this.

It is not straight forward tho' and I think you should definitely get in touch with your Google Play colleagues to improve a bit the communication around this, at least in the Google Play side :)

Thanks for your time!
