### ISSUE TITLE
How to generate fake NDK crash to test Crashlytics integration?

### ISSUE THREAD

**Issue by anticafe** [firebase/firebase-android-sdk#2594]
## What feature would you like to see?

Generate fake NDK crash.

## How would you use it?

When integrating NDK Crashlytics, I want to test it. But since it's hard to make a fake NDK crash, I'm not sure if the integration is successful or not.

**Comment by mrober** [comment]
You could write some native code to force a crash. For example:

```
    int *d = NULL;
    *d = 4;
```
