### ISSUE TITLE
Remove/clear custom key of previous event recordException before adding new event

### ISSUE THREAD

**Issue by namtran-cc** [firebase/firebase-android-sdk#2596]
### Environment

  * Android Studio version: 4.1.2
  * Firebase Component: com.google.firebase:firebase-crashlytics
  * Component version: 17.3.1

### Describe the problem

I want to remove/clear custom key of event before add other custom key to other event. I don't find function to support remove custom key.

#### Steps to reproduce:

- I create project demo and tried track event **recordException** (non-fatal exceptions) with name **error1** has custom key (key1= "demo1") and after that continue track event **recordException**  with name **error2** has custom key (key2="demo2").

- Go to Firebase crashlytic and check report **non-fatal** then event **error1** has key1="demo" and event **error2** has key1="demo1" , key2="demo2".

My expectation: on firebase console:

- **error1** has key1="demo1"

- **error2** has key2 = "demo2"

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
`private fun onErrorEvent1() {
        val firebaseAnalytics = FirebaseCrashlytics.getInstance()
        firebaseAnalytics.setCustomKey("key1", "demo1")

        firebaseAnalytics.recordException(Exception("error1"))
    }`

`private fun onErrorEvent2() {
       val firebaseAnalytics = FirebaseCrashlytics.getInstance()
        firebaseAnalytics.setCustomKey("key2", "demo2")

        firebaseAnalytics.recordException(Exception("error2"))
    }`

`onErrorEvent1()
 onErrorEvent2()`
```

**Comment by mrober** [comment]
This is currently working as intended. You can imagine the custom key is session scoped, not event scoped. I understand why you would want it to behave like this. We have considered changing this behaviour, and might do it at some point in the future. But for now, FirebaseCrashlytics.getInstance.log(String) might behave closer to what you are expecting.
