### ISSUE TITLE
Boom 27.1.0

### ISSUE THREAD

**Issue by mariofelesdossantosjunior** [firebase/firebase-android-sdk#2625]
I upgrade firebase boom this 27.1.0 but return bug

* What went wrong:
Execution failed for task ':presentationLayer:lintDebug'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  ...: Error: Unknown issue id "IncompatibleIidVersion", found in... [LintError]

**Comment by aguatno** [comment]
Hi @mariofelesdossantosjunior It seems that your inquiry doesn't follow the template. With this, I'll be closing this ticket for now.

In order for me to get a better understanding of this issue, you may file another ticket that uses the issue template.

Thanks
