### ISSUE TITLE
Always crash when Firestore client is offline

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-android-sdk#2631]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.3
  * Firebase Component: Firestore
  * Component version: Firebase BOM 26.6.0

### [REQUIRED] Step 3: Describe the problem
I'm using Kotlin coroutines and `await()` from `org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.1.1`. Whenever the client is offline, Firestore will throw `FirebaseFirestoreException` which will cause the app to crash. This require programmers to surround every `get()` call with `try..catch` block, which is not very clean.

My first proposed solution is to return null by default if the client is offline (I think that makes more sense).
Second is to create `awaitOrNull()` that return null if exception is happened.

#### Steps to reproduce:

`com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.`

#### Relevant Code:

```
database.collection(COLLECTION_USERS)
            .document(userId)
            .get()
            .await()
```

**Comment by var-const** [comment]
It's the behavior of Kotlin coroutines to throw if the task finished with an exception. If you'd like a different behavior, you should be able to write your own extension function that wraps `Task.await` in a try-catch block and handles the offline exception in a way that is appropriate for your app.
