### ISSUE TITLE
InApp Messaging addImpressionListener, setMessageDisplayComponent not working

### ISSUE THREAD

**Issue by bhavnathacker** [firebase/firebase-android-sdk#2635]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _4.1.2____
  * Firebase Component: _____ InApp Messaging
  * Component version: _____ implementation 'com.google.firebase:firebase-inappmessaging-display:19.1.5'

#### Steps to reproduce:
I am able to fetch InApp messages in App at trigger event but requirement is to save InApp Messages for which I need to add a listener (need callback either for ImpressionListener OR setMessageDisplayComponent), however all listeners except dismiss one are not getting fired.

#### Relevant Code:
This is what I am trying in onCreate of activity

FirebaseInAppMessaging.getInstance().addImpressionListener(inAppMessage -> {
            Log.d("InAPPImpress", inAppMessage.toString());
        });
FirebaseInAppMessaging.getInstance().addClickListener((inAppMessage, action) -> {
            Log.d("InAPPClick", inAppMessage.toString());
        });

FirebaseInAppMessaging.getInstance().addDismissListener(inAppMessage -> {
            Log.d("InAPPDismiss", inAppMessage.toString());
        });

FirebaseInAppMessaging.getInstance().setMessageDisplayComponent((inAppMessage, firebaseInAppMessagingDisplayCallbacks) -> {
            Log.d("InAPPDisplay", inAppMessage.toString());
        });

FirebaseInAppMessaging.getInstance().setAutomaticDataCollectionEnabled(true);
        FirebaseInAppMessaging.getInstance().triggerEvent(eventName);

**Comment by ciarand** [comment]
Hi bhavnathacker@, thanks for your report. This seems like it might have something to do with the ordering of the lifecycle callbacks. If you move the calls that add listeners to your Application#onCreate hook, does that work better? Can you share a little more detail on the structure of your code?

**Comment by bhavnathacker** [comment]
Hi,

This issue is resolved. Basically these listeners worked when I put them in onResume of activity along with including dependency for "inppmessaging" apart from "inppmessaging-display".

However, in official docs for integration, there is no mention of above points, and I had to spend hours to debug and solve the same.

Request to please update docs.

**Comment by bhavnathacker** [comment]
you may close the issue now, thanks for support!
