### ISSUE TITLE
firebase-messaging-ktx-21.1.0 is missing

### ISSUE THREAD

**Issue by sewar** [firebase/firebase-android-sdk#2649]
* Android Studio version: 4.2
  * Firebase Component: Cloud Messaging
  * Component version: 21.1.0

`com.google.firebase.firebase-messaging-21.1.0` was released on April 08, 2021
`com.google.firebase.firebase-messaging-ktx-21.1.0` is not published yet, even though it was 
[announced](https://firebase.google.com/support/release-notes/android#messaging-ktx_v21-1-0)

https://maven.google.com/web/index.html?q=messaging#com.google.firebase:firebase-messaging
https://maven.google.com/web/index.html?q=messaging#com.google.firebase:firebase-messaging-ktx

**Comment by aguatno** [comment]
Hi @sewar good observation. Let me check this team and see what we can do with it. Thanks

**Comment by aguatno** [comment]
Hi @sewar there's a new released version (22.0.0) which includes [updated firebase-messaging for Kotlin](https://firebase.google.com/support/release-notes/android#messaging_v22-0-0). Please let me know if you have any concerns.
