### ISSUE TITLE
[Performance][UIBlocking] AppStateMonitor Collect Activity Frame Data Prob

### ISSUE THREAD

**Issue by ethanhua** [firebase/firebase-android-sdk#2672]
![截屏2021-05-18 下午3 02 31](https://user-images.githubusercontent.com/22186185/118606503-148dce00-b7ea-11eb-815b-9586445bf304.png)

FirebasePerformance Log show that our slowFrame&frozenFrame data for each page is added on top of the data for all previous pages，maybe need to call `FrameMetricsAggregator.reset` method at activity stop lifecycle to solve this problems

![截屏2021-05-18 下午3 06 39](https://user-images.githubusercontent.com/22186185/118606997-a7c70380-b7ea-11eb-875e-73e043b26610.png)

Every time the `FrameMetricsAggregator.remove method` is called, it returns the same `mMetrics` instance that was not cleared at the stop time, resulting in all pages using the same data

![截屏2021-05-18 下午3 09 33](https://user-images.githubusercontent.com/22186185/118607361-10ae7b80-b7eb-11eb-832b-430a8777eccc.png)

**Comment by aguatno** [comment]
Hi @ethanhua thanks for reporting. May we know what version of the SDK version you are using? Also, would you be able to create a project in GitHub that I could clone to reproduce? I'd like to make sure I'm using the same setup as your environment.

**Comment by ethanhua** [comment]
@aguatno hello, my project sdk version: 
![截屏2021-05-21 上午10 57 27](https://user-images.githubusercontent.com/22186185/119075446-5786b600-ba23-11eb-864f-499336e7041a.png)
![截屏2021-05-21 上午10 57 52](https://user-images.githubusercontent.com/22186185/119075476-666d6880-ba23-11eb-99a3-142a20473b93.png)

i check the logic in source code of firebase perf module, this probs may exist in lasted version

**Comment by yalunqin** [comment]
Thank you ethanhua, just FYI we are actively investigating this issue now. We will keep you posted.

**Comment by jeremyjiang-dev** [comment]
PR #2736 is submitted to fix this issue. 
@ethanhua Thank you for reporting the issue and suggesting the fixes!
