### ISSUE TITLE
Functions always use POST request, even if there's no body data

### ISSUE THREAD

**Issue by touficbatache** [firebase/firebase-android-sdk#2685]
### Describe your environment

  * Android Studio version: 4.2
  * Firebase Component: Functions (Database, Firestore, Storage, Functions, etc)
  * Component version: firebase-bom:26.1.1

#### Steps to reproduce:

Call a Functions GET endpoint without body data. The library always uses
```
Request.Builder().url(url).post(requestBody)
```
even if there's no body.

It should rather use
```
Request.Builder().url(url).get()
```
when there's nothing to send.

This is interfering with my API.

#### Relevant Code:

```
Firebase.functions
    getHttpsCallable(ENDPOINT)
    .call()
```

**Comment by aguatno** [comment]
Hi @touficbatache thanks for reporting. Are you able to provide a small repro for this (this would be the fastest way for us to figure out what's up)? Thanks

**Comment by touficbatache** [comment]
Hey @aguatno, yes sure!

I'm using `express.js` in my Cloud Functions. The code in `index.ts` looks like:
```
admin.initializeApp()

const app = express()
app.use(bodyParser.json())
app.use(cors({origin: true}))

routesConfig(app)

export const api = functions.https.onRequest(app)
```

and I have something that looks like so in other files:
```
export function routesConfig(app: Application) {
    /**
     * Create product
     */
    app.post('/products', [
        ...,
        create
    ]);
    /**
     * List all products
     */
    app.get('/products', [
        ...,
        all
    ]);
    /**
     * Update product by ID
     */
    app.patch('/products/:id', [
        ...,
        patch
    ]);
    /**
     * Delete product by ID
     */
    app.delete('/products/:id', [
        ...,
        remove
    ]);
}
```

This allows me to call `.../api/products/` using POST when I want to create a new product and using GET when I want to get all of them. It's much cleaner and is supported by Cloud Functions. The Android SDK calls the endpoints using a POST request and there's no way to change that.

Preferably, there should also be support for other methods such as `GET` `PUT` `PATCH` `DELETE`.

It would be as simple as replacing `new Request.Builder().url(url).post(requestBody)` in `FirebaseFunctions.java` by other methods like so:
`new Request.Builder().url(url).get()`
`new Request.Builder().url(url).put(requestBody)`
`new Request.Builder().url(url).patch(requestBody)`
`new Request.Builder().url(url).delete(requestBody)`

**Comment by vkryachko** [comment]
It looks like this change would violate the functions spec described in : https://firebase.google.com/docs/functions/callable-reference
