### ISSUE TITLE
Kotlin dls

### ISSUE THREAD

**Issue by rhatami7495** [firebase/firebase-android-sdk#2687]
when sync project, this error:
Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '1.2.6'] was not found

**Comment by aguatno** [comment]
Hi @rhatami7495 It seems that your inquiry doesn't follow the template. With this, I'll be closing this ticket for now.

In order for me to get a better understanding of this issue, you may file another ticket that uses the issue template.

Thanks
