### ISSUE TITLE
Not able to catch errors while trying to connect

### ISSUE THREAD

**Issue by Whisper40** [firebase/firebase-android-sdk#2689]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 30.0.3
  * Firebase Component:Firebase Auth
  * Component version: _____
```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [version 10.0.19042.985], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code (version 1.56.2)
```
#### Steps to reproduce:

I have a user that is created, i would like to connect to my app with this user.
I set the good email and a wrong password.
In this case i would that an error message is thrown.
But actually it is throwing a `throw convertPlatformException(e);` in method `signInWithEmailAndPassword` in file `method_channel_firebase_auth.dart`

#### Relevant Code:
Create an app(i'm using flutter) with login process, enter a good email and a wrong password.
It will throw exception, but cannot catch it..
```

static String loginFirebase(context, String email, String password) {
    String errorMessage = "";
    try {
      LoginPageService.auth.signInWithEmailAndPassword(email: email, password: password).then((_) {
        Navigator.of(context).pushReplacement(MaterialPageRoute(
            builder: (context) => DrawerMenu(
                  pageName: 'Name',
                )));
      });
    } on FirebaseAuthException catch (e) {
      if (e.code == 'invalid-email') {
        errorMessage = "Aucun utilisateur n'existe avec cet email";
      } else if (e.code == 'user-disabled') {
        errorMessage = "Cet utilisateur est désactivé";
      } else if (e.code == 'user-not-found') {
        errorMessage = "L'utilisateur n'a pas été trouvé";
      } else if (e.code == 'wrong-password') {
        errorMessage = "Le mot de passe est incorrect";
      } else {
        errorMessage = "Une erreur non gérée est survenue...";
      }
    } catch (err) {
      errorMessage = "Une erreur non gérée est survenue...";
    }
    return errorMessage;
  }
```

Some logs
```
W/System  ( 3123): Ignoring header X-Firebase-Locale because its value was null.
E/flutter ( 3123): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: [firebase_auth/too-many-requests] We have blocked all requests from this device due to unusual activity. Try again later.
E/flutter ( 3123): #0      MethodChannelFirebaseAuth.signInWithEmailAndPassword
package:firebase_auth_platform_interface/…/method_channel/method_channel_firebase_auth.dart:454
E/flutter ( 3123): <asynchronous suspension>
E/flutter ( 3123): #1      FirebaseAuth.signInWithEmailAndPassword
package:firebase_auth/src/firebase_auth.dart:505
E/flutter ( 3123): <asynchronous suspension>

```

**Comment by aguatno** [comment]
Hi @Whisper40 I noticed this error "We have blocked all requests..". to give context this is caused when sending too many Auth requests from a device (or IP) for a given period of time, just to protect the project against abusive behavior (the limit amount of attempts may vary depending on the usage). This type of condition/block is typically cleared after some time, with the exact interval depending on how overly frequent your requests were. Consider testing with fictional phone numbers to prevent such problems.

You may also try to catch this error using [FirebaseTooManyRequestsException](https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseTooManyRequestsException) so you can customize the error message.

**Comment by Whisper40** [comment]
@aguatno I would like to catch errors by using `FirebaseAuthException` as i did in the code above.
The actual problem is that it throws an exception. I don't want to throw an exception, I want to catch it to display it properly..
![image](https://user-images.githubusercontent.com/30440458/120212124-ec628e00-c231-11eb-99ce-c0de69b5de43.png)
