### ISSUE TITLE
 A certain model of device cannot parse the payload of the data message.

### ISSUE THREAD

**Issue by RoyDeng** [firebase/firebase-android-sdk#2699]
* Android Studio version: 4.1.3
  * Firebase Component: Cloud Messaging
  * Component version: 21.1.0

Most models can work normally, but a user’s device crashed because it could not parse the payload of the data message.

This is the code.

```
class MyFirebaseMessagingService : FirebaseMessagingService() {
    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        if (remoteMessage.data.isNotEmpty()) {
            val notificationType = remoteMessage.data.getValue("notification_type").toInt()
        }
    }
}
```

This is the payload when I pass the parameters to https://fcm.googleapis.com/fcm/send.

```json
{
   "data":{
      "notification_type":1
   },
   "to":"xxxxxxxxxxx"
}
```

I get the report from Crashlytics.

![report](https://user-images.githubusercontent.com/29953421/119921471-a2af4480-bfa0-11eb-8d9d-e2a775f56fd8.png)

**Comment by RoyDeng** [comment]
Sorry, did I miss any required information?

**Comment by aguatno** [comment]
Hi @RoyDeng thanks for reporting. 

We tried reproducing the issue with the latest version Messaging and we are not able to reproduce this.  Are you able to provide a small repro for this? I'd like to make sure I'm using the same setup as your environment.

Also this issue states that it happens on a specific device. We need some information to see if we can debug this further.

- Have you been able to reproduce this issue? If so, are you seeing this on Emulator or Device or both? 
- What is the volume of this crash you are seeing? Do you see any other patterns of issue occurring on particular devices/particular versions more often than other?

**Comment by RoyDeng** [comment]
My 

```
{"data":{"notification_type":1,"subscription_id":"627","subscription_title":"侯友宜","ref":"ae56de687328d21cc42b168a637c66ff","is_collected":false,"title":"[討論] 真的覺得陳其邁對防疫觀念很有s...","summary":"乃至於現在嚴格稽查『傳統市場』\n\n都很認真\n\n然後在施打疫苗方面\n\n陳其邁在『三...","content":"現在這樣看下來\n\n各地方首長之間互相比較一下\n\n陳其邁真的算...","src":"PTT","ch":"政黑板","author":"chungrew","url":"https://www.ptt.cc/bbs/HatePolitics/M.1622515747.A.044.html","senti":"負面","pt":"主文","stype":"BBS","cc":0,"lc":0,"dc":0,"sc":0,"time":"2021-06-01 10:49","is_sound_opened":true},"to":"dlrWy3Xc0i7TOlPxDiAVYq:APA91bGUxu4N7Dc6fDpsjRSBQNCUTHJWo7oVFPoFEJcK7pnlkX50loUUnpcVEE5syF6kIARjiuGjG9XMM04pfYk0HdEKqhbc7fZKucFDMcChJ5yQ92Sz1T9qSLYLoXyIFRnsM6ACUL5K"}

Here is the code in onMessageReceived.

```
class MyFirebaseMessagingService : FirebaseMessagingService() {
    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        if (remoteMessage.data.isNotEmpty()) {
            val notificationType = remoteMessage.data.getValue("notification_type").toInt()

            when (notificationType) {
                0 -> {
                    val isSoundOpened = remoteMessage.data.getValue("is_sound_opened").toBoolean()
                    showNotificationForSummary(remoteMessage, isSoundOpened)
                }
                1 -> {
                    val isSoundOpened = remoteMessage.data.getValue("is_sound_opened").toBoolean()
                    showNotificationForArticle(remoteMessage, isSoundOpened)
                }
                2 -> {
                    val isSoundOpened = remoteMessage.data.getValue("is_sound_opened").toBoolean()
                    showNotificationForAnnouncement(remoteMessage, isSoundOpened)
                }
                3 -> {
                    val isSoundOpened = remoteMessage.data.getValue("is_sound_opened").toBoolean()
                    showNotificationForPrivateNotification(remoteMessage, isSoundOpened)
                }
            }
        }
    }
}
```


```
Fatal Exception: java.util.NoSuchElementException: Key notification_type is missing in the map.
       at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
       at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:344)
       at tw.keypo.app.fcm. MyFirebaseMessagingService.onMessageReceived(KEYPOFirebaseMessagingService.kt:20)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.1.0:13)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.1.0:8)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.1.0:3)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.1.0:3)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@21.1.0:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.3.0:6)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by chliangGoogle** [comment]
@RoyDeng Does this payload missing "notification_type" key only happens to production users? You are not able to reproduce locally on your simulator or device?

**Comment by RoyDeng** [comment]
@chliangGoogle Yes, this problem currently only happens to users who own this model of device, so I cannot reproduce it on the simulator or other models of devices.

**Comment by chliangGoogle** [comment]
@RoyDeng It's unlikely FCM will send out different payloads based on different device, do you happen to target that particular device or android version with different payloads?
Also "notification_type" is a user customized key, so another thing we can do here is to guard at the client to not crash if the key does not exist.

**Comment by RoyDeng** [comment]
@chliangGoogle I found that I did not receive the same crash from the same device in the past two days. Thank you.
