### ISSUE TITLE
[Question] Known issues with Android 12?

### ISSUE THREAD

**Issue by Nyankoo** [firebase/firebase-android-sdk#2713]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: None (see below)
  * Firebase Component: Unknown (see below)
  * Component version: 7.2.0 (see below)

#### Steps to reproduce:

We're using Firebase for Unity, but I was redirected to this git as it is a question directly related to Android. You can see the original report here:
https://github.com/firebase/quickstart-unity/issues/1066#issue-909813373

Are there any known issues with the latest Firebase SDKs and Android 12? We're getting user reports that our app is not loading on our splash screen, which is where we're initializing Firebase components and loading our Firestore database.

We don't have any real Android 12 devices to test this ourselves, and we sadly can't get the logcat from these users, as their devices are not rooted.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @Nyankoo thanks for reporting. I checked our system and found no similar issue reported. Are you able to reproduce this with the sample [quickstart app](https://github.com/firebase/quickstart-android) and the most recent version of Firebase? If so,  please provide a sample project where the issue is reproducible so we can help with debugging and fixing it.

**Comment by Nyankoo** [comment]
Hi @aguatno, like I mentioned above, we sadly don't have any real Android devices that can run Android 12, so we can't test this on our end. I will check if we can reproduce this on an emulator.
