### ISSUE TITLE
Can Firebase console push notification if apps is closed? (User swipe away with the long click menu)

### ISSUE THREAD

**Issue by TiavinaRakotobe** [firebase/firebase-android-sdk#2720]

**Comment by gsakakihara** [comment]
Are you asking about Android and/or iOS? For Android, yes, in general FCM messages should be delivered to apps that are not running. However, some devices force stop apps that are swiped away by the user and FCM messages are not delivered to force stopped apps.

**Comment by TiavinaRakotobe** [comment]
> Are you asking about Android and/or iOS? For Android, yes, in general FCM messages should be delivered to apps that are not running. However, some devices force stop apps that are swiped away by the user and FCM messages are not delivered to force stopped apps.

it's about Android, yea I tested it and it's worked fine on Pixel 3 but not on Huawei.... there is no native code that can handle that behavior ?

**Comment by gsakakihara** [comment]
We have been looking into this issue to see how it can be improved, but for now, the expected behavior is that FCM messages will not be delivered to force stopped apps.
