### ISSUE TITLE
Separate FirebaseInstanceIdReceivers for each process in a multi-process Android app

### ISSUE THREAD

**Issue by abhinavchdhry** [firebase/firebase-android-sdk#2724]
This is a follow-up inquiry to #2561 which was marked as closed.

We have multiple processes within the same Android application, which need to receive Firebase messages independent of each other. I understand that an application can only have a single instance of `FirebaseInstanceIdReceiver` singleton, which is responsible for receiving the FCM messages and delivering them to the FirebaseMessagingService instance

We're currently receiving messages in one process (which is where the `FirebaseInstanceIdReceiver` runs) and deliver messages to other processes by explicit intents. But we want to remove this dependency between the processes. Is there any way to run separate instances of `FirebaseInstanceIdReceiver` on each process so they can receive FCM messages independently?

**Comment by gsakakihara** [comment]
No, that isn't supported. Receiving the message in your FirebaseMessagingService and forwarding it to whatever you want to handle it with (in a different process, if desired), similar to what you are describing, would be the recommended solution.
