### ISSUE TITLE
Remote Config not working when app deployed in Firebase Test Lab

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#2738]
I was able to run the app locally and the SHA are all correct and registered in both Firebase project and Cloud Console Credentials but the Remote Config seems failing to fetch when the app is deployed for Robo test in Test Lab on both Physical and Virtual devices.

This is the original SO link: https://stackoverflow.com/q/68013390/12204620

**Comment by aguatno** [comment]
Hi @ArcherEmiya05 thanks for reporting this. Did you get the same error when running it on an actual physical local device? If this only happens on Firebase Test Lab (Physical or Virtual) then there might be something else going on with the device. If that is the case I would suggest filling a  [support ticket ](https://firebase.google.com/support/troubleshooter/contact) so they can check it directly. Also, they might ask you for some information like APK and sample Test Lab result. Thanks

**Comment by ArcherEmiya05** [comment]
> 
> 
> Hi @ArcherEmiya05 thanks for reporting this. Did you get the same error when running it on an actual physical local device? If this only happens on Firebase Test Lab (Physical or Virtual) then there might be something else going on with the device. If that is the case I would suggest filling a [support ticket ](https://firebase.google.com/support/troubleshooter/contact) so they can check it directly. Also, they might ask you for some information like APK and sample Test Lab result. Thanks

Already tested it many times on physical and emulator and it works properly.
I already tried about 7 different devices (most of the physical and some virtual) on Test Lab it seems all of them shares the same problem.
Today I filed a report hope it get fixed sooner.
