### ISSUE TITLE
better documentation how works deferred deep-link for Android App installation

### ISSUE THREAD

**Issue by antoineherzog** [firebase/firebase-android-sdk#2743]
## What feature would you like to see?

on iOS, FDL uses a combination of pasteboard API + fingerprinting to pass the data of the dynamic link to the app just after the installation. We were wondering which techniques do you use when  the user wants to install the app on Android? It is not really explained anywhere.

Thanks!

## How would you use it?

Tell us how you'd use this feature in your app.

**Comment by ciarand** [comment]
Hi @antoineherzog, FDL on Android relies on some components in Google Play services to maintain the referral state before and after an app install.

**Comment by antoineherzog** [comment]
https://developer.android.com/google/play/installreferrer is that correct?

**Comment by antoineherzog** [comment]
thank for your information!

**Comment by ciarand** [comment]
yeah that's a core part of it, the rest of the state is managed in the relevant components in google play services
