### ISSUE TITLE
Firebase Storage: Emulator fails to download file from URL

### ISSUE THREAD

**Issue by patedit** [firebase/firebase-android-sdk#2755]
* Android Studio version: 4.2.1
  * Firebase Component: Storage
  * Component version: 20.0.0

Thanks for adding emulator support!
While files can be uploaded properly, they can't be retrieved given a URL since the SDK fails to normalize the URL.

Steps to repro:
- Use emulator support
```
FirebaseStorage.getInstance().useEmulator("10.0.2.2", PORT);
```
- Get a reference from url:
```
FirebaseStorage.getInstance().getReferenceFromUrl(downloadUrl);
```

An error will be thrown:
`java.lang.IllegalArgumentException: Firebase Storage URLs must point to an object in your Storage Bucket. Please obtain a URL using the Firebase Console or getDownloadUrl().`

It seems that the base url that is used is [always the production one](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-storage/src/main/java/com/google/firebase/storage/internal/Util.java#L91) so the check will always fail since it doesn't use the emulator settings here.

**Comment by aguatno** [comment]
Hi @patedit Thank you for the provided details. I haven't been able to reproduce it on my end yet. A sample project where the issue can be reproduced will significantly help the investigation.
