### ISSUE TITLE
Firebase logs does not work, bug!

### ISSUE THREAD

**Issue by ccc-sseylani** [firebase/firebase-android-sdk#2780]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2.1
  * Firebase Component: crashlytics
  * Component version: 18.1.0

### [REQUIRED] Step 3: Describe the problem

Custom logs does not work, and I can not see them in the website.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

            var numberOfPhotoDownload = 0
            var didAllPhotosDownloadSuccessfully = true
            if (photosToDownloadChunks.size > 0) {
                FirebaseCrashlytics.getInstance().recordException(Exception("API : Get Photos"))
                FirebaseCrashlytics.getInstance().log("API : Get Photos")
                for (chunck in photosToDownloadChunks){
                    for (photo in chunck){
                        numberOfPhotoDownload++
                    }
                }
                FirebaseCrashlytics.getInstance().log("Number of photos to download: $numberOfPhotoDownload")
                var count = 1
                for (chunck in photosToDownloadChunks){
                    for (photo in chunck){
                        FirebaseCrashlytics.getInstance().log("Photo number #${count} " + "Photo_filename: ${photo.fileName}")
                        count++
                    }
                }
            }

```
// TODO(you): code here to reproduce the problem
```

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/75082292/124037306-53a86500-d9cd-11eb-9c8b-99381903f392.png">

**Comment by aguatno** [comment]
Hi @ccc-sseylani Thanks for reporting. Are you able to provide a small repro for this (this would be the fastest way for us to figure out what's up)? Thanks
