### ISSUE TITLE
"No properties to serialize found on class" error when creating new document with custom class

### ISSUE THREAD

**Issue by TomislavHorvat1** [firebase/firebase-android-sdk#2810]
* Android Studio version:4.2.2
  * Firebase Component: Firestore
  * Component version: firebase-bom:28.2.0

When trying to write a custom object to the Firestore the error occurs. When trying to write it as a `HashMap` the request is successful. Using the example from the [tutorial](https://firebase.google.com/docs/firestore/manage-data/add-data?authuser=1#custom_objects)

#### Steps to reproduce:

1. define a custom `data class`
2. initialize the object and add a new document to the Firestore `firestore.collections("test").add(user)`

#### Relevant Code:

Custom class
```
data class User(
    val firstName: String? = null,
    val lastName: String? = null,
    val email: String? = null
){
    fun toMap(): HashMap<String, Any?>{
        return hashMapOf(
            "FirstName" to  firstName,
            "LastName" to  lastName,
            "Email" to email
        )
    }
}
```

Creating an object
```
val user = User(
            "John",
            "Doe",
            "john.doe@email.com",
        )
        ds.createUser(user)
```
This fails
```
fun createUser(user: User) {
        Log.v(TAG, "createUser")

        firestore.collection("test").add(user)
            .addOnSuccessListener {
                Log.v(TAG, "Writing to database successfull")
            }
            .addOnFailureListener { e ->
                Log.w(TAG, "ERROR: ", e)
            }
    }
```
This succeeds
```
fun createUser(user: User) {
        Log.v(TAG, "createUser")

        firestore.collection("test").add(user.toMap())
            .addOnSuccessListener {
                Log.v(TAG, "Writing to database successfull")
            }
            .addOnFailureListener { e ->
                Log.w(TAG, "ERROR: ", e)
            }
    }
```

**Comment by rafikhan** [comment]
@TomislavHorvat1 There's no obvious reason why this shouldn't be working. Can you create a github repo or gist that reproduces the issue that we can examine and clone?

**Comment by TomislavHorvat1** [comment]
@rafikhan here is the gist
https://gist.github.com/TomislavHorvat1/7d0a99c3c885f7e95bf795d1fa89df1f

**Comment by schmidt-sebastian** [comment]
I am not able to reproduce this with your sample and was able to verify via the debugger that the properties are detected. See the following:

```
2021-07-14 20:30:34.528 27957-28798/com.example.myapplication I/Firestore: (23.0.1) [WriteStream]: (2c1a2e9) Stream sending: # com.google.firestore.v1.WriteRequest@e8c96ca9
    stream_token: "\031\020hB\002\201\364\265\265"
    writes {
      update {
        fields {
          key: "firstName"
          value {
            integer_value: 0
            string_value: "John"
          }
        }
        fields {
          key: "lastName"
          value {
            integer_value: 0
            string_value: "Doe"
          }
        }
        fields {
          key: "email"
          value {
            integer_value: 0
            string_value: "john.doe@email.com"
          }
        }
        name: "projects/XXX/databases/(default)/documents/test/b6aAgtC6SxSGxEd3xyGG"
      }
    }
```

If you want to debug this yourself. you can set a breakpoint here: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java#L638 
This code detects the properties in your data class.
