### ISSUE TITLE
Campaign using custom trigger detects old (cached) campaign's impression

### ISSUE THREAD

**Issue by matthew-niemann** [firebase/firebase-android-sdk#2817]
### Environment

  * Android Studio version: 4.2.2
  * Firebase Component: In-App Messaging
  * Component version: BOM 28.2.0

### Description

When creating a new campaign scheduled with [only] a custom trigger that was also used on a previous campaign, the message does not show -- if the previous campaign was already impressed on the device.

From debugging, it seems as though the SDK is looking in the cache for _any_ already-impressed campaign that matches a particular event trigger. In this case, it finds one (that being of a previous campaign), and assumes that the **new** campaign is therefore also impressed -- leading to no display of the new campaign's message.

##### Phase 1: The Setup

1. In the Firebase Console, create a new In-App Messaging campaign (let's call this Campaign A)
2. In Scheduling, remove the default triggers, and add your own (let's call this `"my_trigger"`)
3. Publish the campaign
4. In your app, invoke the In-App Message by logging `"my_trigger"` to Analytics, or In-App Messaging directly
5. Notice it displays just fine, and the impression is logged (and therefore the message will not display on re-trigger, etc.)

At this point, the SDK state is set to reproduce the bug.

##### Phase 2: The Bug

1. In the Firebase Console, delete Campaign A
2. Create a new campaign (let's call this Campaign B)
3. In Scheduling, remove the default triggers, and add `"my_trigger"` again (as we did in Campaign A)
4. Publish the campaign
5. In your app, attempt to invoke the In-App Message by logging `"my_trigger"` to Analytics, or In-App Messaging directly
6. Observe that the message does not display, and the Logcat output shows `I/FIAM.Headless: Already impressed campaign Campaign A ? : true`

### Conclusions

So my assumption based on this behaviour, together with the info log mentioning the previous (now-deleted) campaign, is that the SDK is not fully aware that the triggering event can be used in multiple campaigns going forward, and assumes it must not show the message. I also assume that it is valid to reuse triggering events for consecutive campaigns, and therefore this is unexpected behaviour.

Note that this behaviour does not occur if the campaign is configured with the `on_foreground` event. After inspecting the code, my assumption here is that this event is always exempt from [inspecting the cache](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java#L161), and therefore avoids the flow leading to the bug.

#### Relevant Code:

This section is non-applicable in my opinion, as the only "coding" required in the app itself is the line to log the event trigger.

**Comment by matthew-niemann** [comment]
@aguatno I think you may have labelled this incorrectly. Should it not be `inappmessaging`?

**Comment by JasonAHeron** [comment]
Thanks for the really detailed bug here, I think what you might be experiencing is something else which could also be a bug. We filter impressions [based on campaign IDs](https://cs.opensource.google/firebase-sdk/firebase-android-sdk/+/master:firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ImpressionStorageClient.java;l=90;drc=4273e0ddde8c844b3276dac735f2032bd9b5a048), however the SDK does log all the campaigns that it has impressions for, so I think the logs are confusing here.

you might actually not be fetching the new campaign yet, we do 5 fetches when an app is first installed (to check for test device mode) and then we fetch once per day. If you reinstall your app and then send it a test message you will put it into "test mode" which fetches new campaigns every time the app is on foreground. I'm guessing that will solve your problem.

You can also view a high level of debug logging which might be helpful

```adb shell setprop log.tag.FIAM.Headless DEBUG```
