### ISSUE TITLE
FirebaseRemoteConfig does not support multiple projects

### ISSUE THREAD

**Issue by daniellemariani** [firebase/firebase-android-sdk#282]
When supporting [multiple projects](https://firebase.google.com/docs/projects/multiprojects) (environments), **FirebaseDatabase** and **FirebaseAuth** provide a function `getInstance(app)` that allows to switch environment, but **FirebaseRemoteConfig** does not provide that function, it only provides a `getInstance()`.

Version: 16.3.0

Is there a way to switch projects?
Is it consider to support  getInstance(app) in FirebaseRemoteConfig?

**Comment by kroikie** [comment]
@daniellemariani thanks for the feedback on this. This is a know issue on the Remote Config team and they are working to address it and bring it in line with the other SDKs.

**Comment by daniellemariani** [comment]
Thanks for the heads up. 

Do you know what version this feature will be added? 
@kroikie @samtstern

**Comment by samtstern** [comment]
@daniellemariani sorry we can't share specific timelines, but it will be included along with some other improvements in an upcoming version.

**Comment by vkryachko** [comment]
The recent releases of remote config support multiple apps via `FirebaseRemoteConfig#getInstance(FirebaseApp)`
