### ISSUE TITLE
Native crashes backtrace uploaded at dashboard in non-readable format(native symbol not uploaded/not seen).

### ISSUE THREAD

**Issue by ajayjuneja1997** [firebase/firebase-android-sdk#2847]
### [REQUIRED] Step 2: Describe your environment
  * Firebase Component:  Crashlytics + Crashlytics NDK
  * Component version: om.google.firebase:firebase-bom:28.2.0

### [REQUIRED] Step 3: Describe the problem
Native crashes backtrace uploaded at dashboard in non-readable format(native symbol not uploaded/not seen).

#### Steps to reproduce:
Integrated Crashlytics and Crashlytics NDK in code.
Result:
Firebase crashlytics NDK reports the crashes but does not display the stack traces properly, it only shows as (missing).
The crashes from the Java  are reported and working properly, issue is only with the native crashes.
We did a force native haxe crash in our app but backtrace is coming incomplete as backtrace uploaded at dashboard in non-readable format(native symbol not uploaded/not seen)readable format

#### Relevant Code:

App level build.gradle.
    
    apply plugin: 'com.google.firebase.crashlytics'
    apply plugin: 'com.google.gms.google-services'
    
    android {
        
        defaultConfig {
          ndk {
               abiFilters 'armeabi-v7a'
            }
        }
    
     buildTypes {
         debug {
                firebaseCrashlytics {
                    nativeSymbolUploadEnabled true
                    unstrippedNativeLibsDir "build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a"
                    strippedNativeLibsDir "build/intermediates/transforms/stripDebugSymbol/debug/0/lib/armeabi-v7a"
				    // On version firebase-crashlytics-gradle:2.7.1 and 2.6.0 we have uncommented strippedNativeLibsDir as per instruction.
                }
            }
        }
    
    afterEvaluate {
        android.applicationVariants.all { variant ->
            def variantName = variant.name.capitalize()
            println("symbols will be added on variant ${variantName}")
            def task = tasks.findByName("assemble${variantName}")
            def uploader = "uploadCrashlyticsSymbolFile${variantName}"
            task?.finalizedBy(uploader)
        }
    }

Project-level Build.gradle
    
    dependencies {
        implementation platform('com.google.firebase:firebase-bom:28.2.0')
        implementation 'com.google.firebase:firebase-analytics'
        implementation 'com.google.firebase:firebase-crashlytics-ndk'
        implementation "com.google.firebase:firebase-iid"
    }

Added log file(bun3.txt) and screenshots of dashboard showing incomplete backtrace.
Added the log file and screenshot be dashboard shown non-readable backtrace results.

[bun3.txt](https://github.com/firebase/firebase-android-sdk/files/6861471/bun3.txt)
![native-crash-dashboard](https://user-images.githubusercontent.com/59354421/126622482-076e7629-e9b9-4b49-8443-746eb5cded6c.png)
![native-crash-dashboard-extended](https://user-images.githubusercontent.com/59354421/126622488-99c7a8cb-f96d-43fa-aebe-1cb71915103e.png)
![native-crash-dashboard-txt](https://user-images.githubusercontent.com/59354421/126622496-4b2f5b04-0c36-4f8a-8f04-144b4c5242c0.png)

**Comment by kmandrika** [comment]
Hi @ajayjuneja1997 ,

Could you trying using the Breakpad symbol file (https://firebase.google.com/docs/crashlytics/ndk-reports#breakpad-symbol-file) and see if this helps with your stacks?

**Comment by ajayjuneja1997** [comment]
We have tried this also and we are still facing same issue.

**Comment by kmandrika** [comment]
In order for the Breakpad symbol file to work, you'll need to use the latest version of the Crashlytics NDK SDK and Gradle plugin. If you're already on the latest version, could you post the output of running `./gradlew uploadCrashlyticsSymbolFile{Vriant} --debug`

**Comment by ajayjuneja1997** [comment]
We are using this code in our build.gradle at app level:
```
afterEvaluate {
    android.applicationVariants.all { variant ->
        def variantName = variant.name.capitalize()
        println("symbols will be added on variant ${variantName}")
        def task = tasks.findByName("assemble${variantName}")
        def uploader = "uploadCrashlyticsSymbolFile${variantName}"
        task?.finalizedBy(uploader)    
    }
}

```
Sample Output of build:

> Task :deps:extension-api:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
> Task :deps:extension-api:extractDebugAnnotations UP-TO-DATE
> Task :deps:extension-api:mergeDebugGeneratedProguardFiles UP-TO-DATE
> Task :deps:extension-api:mergeDebugConsumerProguardFiles UP-TO-DATE
> Task :deps:extension-api:prepareLintJarForPublish UP-TO-DATE
> Task :deps:extension-api:mergeDebugJavaResource UP-TO-DATE
> Task :deps:extension-api:syncDebugLibJars UP-TO-DATE
> Task :deps:extension-api:bundleDebugAar UP-TO-DATE
> Task :deps:extension-api:compileDebugSources UP-TO-DATE
> Task :deps:extension-api:assembleDebug UP-TO-DATE
> Task :deps:openfl:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
> Task :deps:openfl:extractDebugAnnotations UP-TO-DATE
> Task :deps:openfl:mergeDebugGeneratedProguardFiles UP-TO-DATE
> Task :deps:openfl:mergeDebugConsumerProguardFiles UP-TO-DATE
> Task :deps:openfl:prepareLintJarForPublish UP-TO-DATE
> Task :deps:openfl:mergeDebugJavaResource UP-TO-DATE
> Task :deps:openfl:syncDebugLibJars UP-TO-DATE
> Task :deps:openfl:bundleDebugAar UP-TO-DATE
> Task :deps:openfl:compileDebugSources UP-TO-DATE
> Task :deps:openfl:assembleDebug UP-TO-DATE
> Task :app:mergeDebugNativeLibs
> Task :app:stripDebugDebugSymbols
> Task :app:packageDebug
> Task :app:assembleDebug
> Task :app:generateCrashlyticsSymbolFileDebug
> Task :app:uploadCrashlyticsSymbolFileDebug

**Comment by igor-korotenko** [comment]
@kmandrika any updates on this?

**Comment by mrober** [comment]
With the latest version of the gradle plugin, you shouldn't need to specify unstrippedNativeLibsDir unless your symbols are in an unusual place. Try with the latest version of the plugin, and without overriding unstrippedNativeLibsDir. If the problem persists, please reopen this issue.
