### ISSUE TITLE
Firebase in-app messagins only shows latest campaing

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-android-sdk#285]
### [READ] Step 1: Are you in the right place?

yes

 
### [REQUIRED] Step 2: Describe your environment

 Android Studio version: 3.2
Firebase Component: In-App Messaging
Component version: 17.1.0

### [REQUIRED] Step 3: Describe the problem

Firebase in-app messaging only shows the latest campaing to the users (i'm only using android clients so i dont know if this issue happens to other clients)

#### Steps to reproduce:

Create Campaing A on firebase dashboard and assing it to all users event on_foreground
Create campaing B on firebase dashboard and assing it to all users event on_foreground

users will stop seing campaing A as soon as Campaign B is online
I read firebase documentation and states that the campaigns are loaded only once per day... and even if you want to assure users will not be flooded with anounces and show the messages once per day.... as soon as the next day arrives users should start to see other campaigns

You can even determine if oldest campaign will be shown first or last but the users shall see all... 
otherwise is pointless to be able to create several campaigns

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by MeghaB** [comment]
Hi @bolds07! The most recently created campaign has the highest priority, and so it is the case that for new installations, the end user should see: Day1 (Campaign B) and Day2 (CampaignA). However, if the installation has already seen CampaignA, it will not display again. 

If you're running into an issue where you have multiple campaigns defined, and a fresh install (ie: no campaigns have been seen by that device), and you aren't getting the subsequent campaigns the next day, please file a support ticket with more details about your project and we can dig in to your particular case, or provide an example to reproduce.

Thanks!
