### ISSUE TITLE
FirebaseInstallations.registerFidWithServer Throwing java.lang.NullPointerException

### ISSUE THREAD

**Issue by radityagumay** [firebase/firebase-android-sdk#2859]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](https://stackoverflow.com/questions/68539000/firebaseinstallations-registerfidwithserver-throwing-java-lang-nullpointerexcept)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: **Android Studio Arctic Fox | 2020.3.1 RC 1**
  * Firebase Component: **FirebaseInstallations**
  * Component version: Please check at [here](https://stackoverflow.com/questions/68539000/firebaseinstallations-registerfidwithserver-throwing-java-lang-nullpointerexcept)

#### Steps to reproduce:

We're not able to reproduce on our end.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @radityagumay As I observe in the log you have a null object reference, this happens when a variable or object is not declared or initialised properly. Could you try bumping the Firebase Installation product you are using to the latest versions?

**Comment by radityagumay** [comment]
@aguatno sure will give a try bumping to the latest version. meanwhile, we can close this issue.
