### ISSUE TITLE
How we can get sms auto verify in firebase auth ui in Android App

### ISSUE THREAD

**Issue by dfg-1310** [firebase/firebase-android-sdk#2866]
## What feature would you like to see?

How we can get SMS auto-verify in firebase auth UI in Android App
## How would you use it?

I am using the firebase auth UI for mobile verification. It's working fine when the user manually enters the SMS on OTP Screen. 

I want an SMS auto-read feature in firebase auth UI. We are not showing any UI and firebase takes care of UI. My Question is what code I have to add so the SMS auto-read feature can work.

Please provide the solution.

**Comment by aguatno** [comment]
Hi @dfg-1310 thanks for feedback. Based on our [documentation](https://firebase.google.com/docs/auth/android/phone-auth#send-a-verification-code-to-the-users-phone) the Instant Verification should have no extra codes to implement and in some cases the phone number can be instantly verified without needing to send or enter a verification code. Should you have any feedback regarding Firebase Auth UI, you may try to file an FR [here](https://github.com/firebase/FirebaseUI-Android/issues). Thanks
