### ISSUE TITLE
Firebase using insecure application permission

### ISSUE THREAD

**Issue by KaviIDPal** [firebase/firebase-android-sdk#2867]
Our app went for penetration test, the pen testers have mentioned the firabase permissions is vulnerable.

﻿﻿**Permission:**
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE

Based on the ticket it was mentioned it was closed in Analytics v18.0.0(https://github.com/firebase/firebase-android-sdk/issues/1573). but i still see that the install referrer broadcast is present.
package="com.google.firebase.measurement_impl"
package="com.google.firebase.measurement"

I'm using the below versions
 'com.google.firebase:firebase-messaging:22.0.0'
 'com.google.firebase:firebase-analytics:19.0.0

Could you please let us know which version of firebase SDK should be used if this has been fixed. If not is there any plan to fix this issue?

**Comment by vkryachko** [comment]
Hi, this permission is required by FirebaseAnalytics to function, see this [issue](https://issuetracker.google.com/issues/78380811#comment22) for details
