### ISSUE TITLE
How does the uploadCrashlyticsMappingFile<Variant> task bind to apk building?

### ISSUE THREAD

**Issue by sboishtyan** [firebase/firebase-android-sdk#2899]
We use the AGP 4.2.2 and we have the custom sign Gradle task. This task binds to APK via

```onVariants { variant: ApplicationVariant -> 
variant.artifacts.use(customSignTask)
                        .wiredWithDirectories(
                            taskInput = SignApkTask::unsignedDirProperty,
                            taskOutput = SignApkTask::signedDirProperty
                        )
                        .toTransform(ArtifactType.APK)
}
```
Now when we execute our customSignTask it triggers `packageRelease` task. But `uploadCrashlyticsMappingFile` binds only with `assemble` task if I understand correctly.

So how could we trigger the `uploadCrashlyticsMappingFile` task when building and singing APK?

**Comment by aguatno** [comment]
Hi @sboishtyan If minifyEnabled is set to false then the code won't be obfuscated and the corresponding mapping file won't be generated which is needed for the uploadCrashlyticsMappingFile{Varian} gradle task. When setting minifyEnabled true, the project is built without issues. You may also visit our documentation [page](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=android) on how to get deobfuscated crash reports.

**Comment by sboishtyan** [comment]
Thank you for the answer but in our app, we'd already enabled the minifying.
Now I ad-hoc the problem calling `uploadCrashlyticsMappingFileRelease` manually.
The problem is that we don't execute `assemble` but bind our task as I describe in issue

**Comment by mrichards** [comment]
Doing a sweep of old tickets and saw this one...you should be able to invoke the `uploadCrashlyticsMappingFile` task manually and it will automatically be registered and configured to execute after the ProGuard/R8 obfuscation task.

Please create a new github issue if you continue to have issues uploading mapping files using the latest version of the Crashlytics Gradle plugin.
