### ISSUE TITLE
Upload to realtime database and storage wont push through

### ISSUE THREAD

**Issue by makoysof** [firebase/firebase-android-sdk#2902]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2.1
  * Firebase Component: Storage, Database(Database, Firestore, Storage, Functions, etc)
  * Component version: 19.3.1(Database) 19.1.1(Storage

### [REQUIRED] Step 3: Describe the problem
When uploading to database and storage, upload won't push through.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
W/NetworkRequest: error sending network request POST https://firebasestorage.googleapis.com/v0/b/project-name.appspot.com/o
W/ExponenentialBackoff: network unavailable, sleeping.
W/StorageUtil: no auth token for request
W/NetworkRequest: no auth token for request

#### Relevant Code:
Storage rules:
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}

realtime db rules:
"rules": {
    ".read": true,
    ".write": true
  }
}
```
```

**Comment by aguatno** [comment]
Hi @makoysof Based on the error message and the code, the issue might be related to the Cloud Storage rules and permissions. It is necessary to use an authenticated user to make requests over the Cloud Storage service. You can also check this entry in [Stackoverflow](https://stackoverflow.com/a/37802427) about a similar issue. Also, a good option is to check the [Firebase Android quickstart](https://github.com/firebase/quickstart-android/tree/master/storage), there is an example on how to implement the service. This project has been already tested and you can use it on your own implementation.
