### ISSUE TITLE
DynamicLinks getDynamicLink sometimes not resolving long links correctly

### ISSUE THREAD

**Issue by mikehardy** [firebase/firebase-android-sdk#2909]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 7.0.0
  * Firebase Component: dynamic-links (Database, Firestore, Storage, Functions, etc)
  * Component version: BoM 28.3.1 (most current stable as of this typing)

### [REQUIRED] Step 3: Describe the problem

:wave:  Hi there, I help maintain https://github.com/invertase/react-native-firebase/ and I'm seeing flaky behavior on this API call, I was hoping you could help me out.

The specific test case is here: 

https://github.com/invertase/react-native-firebase/blob/3002caf4672e1df039a089b9109e444f8d8caf00/packages/dynamic-links/e2e/dynamicLinks.e2e.js#L69-L74

Which exercises this chunk of Java, with a long link:

https://github.com/invertase/react-native-firebase/blob/3002caf4672e1df039a089b9109e444f8d8caf00/packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java#L205-L234

#### Steps to reproduce:

Feed a long link into the `getDynamicLink` method, and sometimes you get the target URI back as a return value, sometimes you get the long link back unchanged

#### Relevant Code:

```java
// feed it this
private String TEST_LINK2 = `https://reactnativefirebase.page.link/?link=https://invertase.io/hire-us&apn=com.invertase.testingutm_source=github`;

// expect this
private String TEST_LINK2_TARGET = 'https://invertase.io/hire-us';


  public void resolveLink(String link) {
    try {
      FirebaseDynamicLinks.getInstance()
          .getDynamicLink(Uri.parse(link))
          .addOnCompleteListener(
              task -> {
                if (task.isSuccessful()) {
                  PendingDynamicLinkData linkData = task.getResult();
                  // Note: link == null if link invalid, isSuccessful is only false on processing
                  // error
                  if (linkData != null
                      && linkData.getLink() != null
                      && linkData.getLink().toString() != null) {
                    String linkUrl = linkData.getLink().toString();
                    int linkMinimumVersion = linkData.getMinimumAppVersion();
                    Bundle linkUtmParameters = linkData.getUtmParameters();
                    System.out.println("resolved to: " + linkUrl);
                  } else {
                    System.err.println("Dynamic link not found");
                  }
                } else {
                  System.err.println("resolve-link-error");
                }
              });
    } catch (Exception e) {
      // This would be very unexpected, but crashing is even less expected
     System.err.println("Unknown resolve failure");
    }
  }
```

**Comment by mikehardy** [comment]
Note this may be an interaction with a later part of our test suite where we attempt to open the app on the same link and it fails, then on another run it resolves the long link here - it appears that there is some state outside the app that is sticky between test runs and can return stale results. It's pretty odd but there's something not right going on here even if it's a bit hard to reproduce

**Comment by aguatno** [comment]
Hi @mikehardy We are looking into this issue. We have not been able to reproduce yet. 
We'll likely need a repro or more specific details about a Firebase issue to help more. Moreover, try reproducing with our quickstart. This will help us isolate the issue and discard conflicts with other third party libraries being used. Please let me know if you have questions about this.

**Comment by mikehardy** [comment]
That's fair - I haven't been able to come up with a reliable reproduction. This may only happen in far-fetched testing scenarios :shrug:
