### ISSUE TITLE
Crashes not being uploaded to firebase dashboard for Instant Apps

### ISSUE THREAD

**Issue by gauravbansal-cpi** [firebase/firebase-android-sdk#2912]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____4.2.1
  * Firebase Component: _Crashlytics____ (Database, Firestore, Storage, Functions, etc)
  * Component version: ____17.2.1_

### [REQUIRED] Step 3: Describe the problem
I am facing an issue with crash log uploads on firebase with our Instant apps. Crash uploads works fine with full version of the app. Also I have noticed that with Instant apps firebase sdk still saves the crash logs but doesn't upload them. Once we upgrade from instant apps to full version it uploads the crash logs which were saved earlier for instant app.
As per my understanding for uploading crash logs firebase crashlytics sdk uses JobSchedulers and as per https://issuetracker.google.com/issues/124267857#comment6 job schedulers don't work with Instant apps. Is this the reason crash logs are not getting uploaded for instant apps?

#### Steps to reproduce:

For your reference PFB logs for adb logcat -s FirebaseCrashlytics TransportRuntime.SQLiteEventStore TransportRuntime.JobInfoScheduler TransportRuntime.CctTransportBackend TransportRuntime.DefaultScheduler

`08-12 20:23:33.514 8676 9766 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{_o=auto, _et=1242518, _sc=MapActivity, _si=-6399843971024424288}], name=_e, timestampInMillis=1628780013008}]

08-12 20:26:34.036 9848 9848 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by global Firebase setting.
08-12 20:26:34.043 9848 9848 D FirebaseCrashlytics: Firebase Analytics is available.
08-12 20:26:34.048 9848 9848 D FirebaseCrashlytics: Firebase Analytics listener registered successfully.
08-12 20:26:34.073 9848 9848 D FirebaseCrashlytics: Reading cached settings...
08-12 20:26:34.074 9848 9848 D FirebaseCrashlytics: No cached settings found.
08-12 20:26:34.075 9848 9848 D FirebaseCrashlytics: No cached settings data found.
08-12 20:26:34.079 9848 9848 D FirebaseCrashlytics: Mapping file ID is: 00000000000000000000000000000000
08-12 20:26:34.079 9848 9848 I FirebaseCrashlytics: Initializing Crashlytics 17.2.1
08-12 20:26:34.081 9848 9848 D FirebaseCrashlytics: Installer package name is: null
08-12 20:26:34.126 9848 9848 D FirebaseCrashlytics: Exception handling initialization successful
08-12 20:26:34.134 9848 9887 D FirebaseCrashlytics: No cached FID; legacy id is null
08-12 20:26:34.134 9848 9887 D FirebaseCrashlytics: Created new Crashlytics IID: 2196d372ed83412ab56602013cff2675
08-12 20:26:34.135 9848 9887 D FirebaseCrashlytics: Opening a new session with ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:34.183 9848 9887 D FirebaseCrashlytics: Initialization marker file created.
08-12 20:26:34.184 9848 9887 D FirebaseCrashlytics: Registered Firebase Analytics event receiver for breadcrumbs
08-12 20:26:34.184 9848 9887 D FirebaseCrashlytics: Finalizing previously open sessions.
08-12 20:26:34.188 9848 9887 D FirebaseCrashlytics: No open sessions to be closed.
08-12 20:26:34.188 9848 9887 D FirebaseCrashlytics: Closed all previously open sessions
08-12 20:26:34.191 9848 9887 D FirebaseCrashlytics: No reports are available.
08-12 20:26:34.191 9848 9887 D FirebaseCrashlytics: Initialization marker file removed: true
08-12 20:26:34.300 9848 9848 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
08-12 20:26:34.614 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{_o=auto, _sid=1628780194}], name=_s, timestampInMillis=1628780194505}]
08-12 20:26:35.644 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{Analytics_Reporting_App=ChargePointInstant, _o=app, Maintenance_Mode=false, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Cached=false, Launch_Source=Google Play}], name=Global_Config_Fetch, timestampInMillis=1628780195574}]
08-12 20:26:35.774 9848 9890 D FirebaseCrashlytics: Requesting settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:53103838140:android:43d04b9beb9c48eb/settings
08-12 20:26:35.775 9848 9890 D FirebaseCrashlytics: Settings query params were: {instance=878f334b3911482b79887416dd7ff9b3dc9ef4fc, build_version=513, display_version=1.0.0-InstantCP-513-0.debug_20210812_18:09, source=1}
08-12 20:26:35.790 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{_o=auto, _sc=MapActivity, _si=1315616320171567843}], name=_vs, timestampInMillis=1628780195750}]
08-12 20:26:36.605 9848 9890 D FirebaseCrashlytics: Settings request ID: null
08-12 20:26:36.605 9848 9890 D FirebaseCrashlytics: Settings result was: 200
08-12 20:26:36.607 9848 9890 D FirebaseCrashlytics: Writing settings to cache file...
08-12 20:26:36.608 9848 9890 D FirebaseCrashlytics: Loaded settings: {"settings_version":3,"cache_duration":86400,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false,"collect_anrs":false},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"54e6b5d34dd4468000000328","bundle_id":"com.coulombtech.debug"},"expires_at":1628866596607}
08-12 20:26:37.430 9848 9848 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
08-12 20:26:37.505 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1794.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=1315616320171567843, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_Get_Global_Config, timestampInMillis=1628780197373}]
08-12 20:26:39.066 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1180.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=1315616320171567843, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_View_Station_Detail, timestampInMillis=1628780199008}]
08-12 20:26:39.497 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1467.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=1315616320171567843, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_Retrieve_Map_Data, timestampInMillis=1628780199395}]
08-12 20:26:40.950 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1164.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=1315616320171567843, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_Station_List, timestampInMillis=1628780200794}]
08-12 20:26:43.050 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1252.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=1315616320171567843, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_Station_List, timestampInMillis=1628780202844}]

08-12 20:26:50.594 9848 9848 D FirebaseCrashlytics: Crashlytics is handling uncaught exception "java.lang.RuntimeException: Test Crash" from thread main
08-12 20:26:50.722 9848 9887 D FirebaseCrashlytics: Closing open sessions.
08-12 20:26:50.722 9848 9887 D FirebaseCrashlytics: Closing session: 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.722 9848 9887 D FirebaseCrashlytics: Collecting session parts for ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.722 9848 9887 D FirebaseCrashlytics: Session 611536A2007F-0001-2678-4433F083327D has fatal exception: true
08-12 20:26:50.722 9848 9887 D FirebaseCrashlytics: Session 611536A2007F-0001-2678-4433F083327D has non-fatal exceptions: false
08-12 20:26:50.725 9848 9887 D FirebaseCrashlytics: Collecting SessionStart data for session ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.726 9848 9887 D FirebaseCrashlytics: Collecting SessionUser data for session ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.726 9848 9887 D FirebaseCrashlytics: Collecting SessionApp data for session ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.726 9848 9887 D FirebaseCrashlytics: Collecting SessionOS data for session ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.727 9848 9887 D FirebaseCrashlytics: Collecting SessionDevice data for session ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.729 9848 9887 D FirebaseCrashlytics: Removing session part files for ID 611536A2007F-0001-2678-4433F083327D
08-12 20:26:50.779 9848 9887 D FirebaseCrashlytics: Opening a new session with ID 611536B2030B-0002-2678-4433F083327D
08-12 20:26:50.782 9848 9887 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
08-12 20:26:50.788 9848 10007 D FirebaseCrashlytics: Logging Crashlytics event to Firebase
08-12 20:26:50.789 9848 10007 D FirebaseCrashlytics: Awaiting app exception callback from FA...
08-12 20:26:50.827 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{_o=clx, _r=1, _et=15052, _sc=MapActivity, _si=1315616320171567843, timestamp=1628780210594, fatal=1}], name=_ae, timestampInMillis=1628780210788}]
08-12 20:26:50.828 9848 10007 D FirebaseCrashlytics: App exception callback received from FA listener.
08-12 20:26:50.840 9848 9880 D TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
08-12 20:26:50.851 9848 9880 D TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=511521345 in 1000ms(Backend next call timestamp 0). Attempt 1
08-12 20:26:50.853 9848 9888 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{_o=auto, _et=15086, _fr=1, _sc=MapActivity, _si=1315616320171567843}], name=_e, timestampInMillis=1628780210830}]
08-12 20:26:50.869 9848 9887 D FirebaseCrashlytics: Crashlytics report successfully enqueued to DataTransport: 611536A2007F000126784433F083327D
08-12 20:26:50.870 9848 9848 D FirebaseCrashlytics: Crashlytics completed exception processing. Invoking default exception handler.
08-12 20:26:50.872 9848 9887 D FirebaseCrashlytics: Attempting to send crash report at time of crash...
08-12 20:26:50.872 9848 9887 D FirebaseCrashlytics: Send to Reports Endpoint disabled. Removing Reports Endpoint report.
08-12 20:26:50.872 9848 9887 D FirebaseCrashlytics: Removing report at /data/user/0/com.coulombtech.debug/files/.com.google.firebase.crashlytics/fatal-sessions/611536A2007F-0001-2678-4433F083327D.cls

08-12 20:27:53.051 10019 10019 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
08-12 20:27:53.057 10019 10019 D FirebaseCrashlytics: Firebase Analytics is available.
08-12 20:27:53.060 10019 10051 D TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=511521345 in 1000ms(Backend next call timestamp 0). Attempt 1
08-12 20:27:53.062 10019 10019 D FirebaseCrashlytics: Firebase Analytics listener registered successfully.
08-12 20:27:53.085 10019 10019 D FirebaseCrashlytics: Reading cached settings...
08-12 20:27:53.096 10019 10019 D FirebaseCrashlytics: Loaded cached settings: {"settings_version":3,"cache_duration":86400,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false,"collect_anrs":false},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"54e6b5d34dd4468000000328","bundle_id":"com.coulombtech.debug"},"expires_at":1628866596607}
08-12 20:27:53.097 10019 10019 D FirebaseCrashlytics: Returning cached settings.
08-12 20:27:53.100 10019 10019 D FirebaseCrashlytics: Mapping file ID is: 00000000000000000000000000000000
08-12 20:27:53.100 10019 10019 I FirebaseCrashlytics: Initializing Crashlytics 17.2.1
08-12 20:27:53.101 10019 10019 D FirebaseCrashlytics: Installer package name is: null
08-12 20:27:53.143 10019 10055 D FirebaseCrashlytics: Found previous crash marker.
08-12 20:27:53.146 10019 10019 D FirebaseCrashlytics: Exception handling initialization successful
08-12 20:27:53.158 10019 10055 D FirebaseCrashlytics: Found matching FID, using Crashlytics IID: 2196d372ed83412ab56602013cff2675
08-12 20:27:53.160 10019 10055 D FirebaseCrashlytics: Opening a new session with ID 611536F10092-0001-2723-4433F083327D
08-12 20:27:53.200 10019 10055 D FirebaseCrashlytics: Initialization marker file created.
08-12 20:27:53.201 10019 10055 D FirebaseCrashlytics: Registered Firebase Analytics event receiver for breadcrumbs
08-12 20:27:53.201 10019 10055 D FirebaseCrashlytics: Finalizing previously open sessions.
08-12 20:27:53.209 10019 10055 D FirebaseCrashlytics: Closing open sessions.
08-12 20:27:53.209 10019 10055 D FirebaseCrashlytics: Closing session: 611536B2030B-0002-2678-4433F083327D
08-12 20:27:53.209 10019 10055 D FirebaseCrashlytics: Collecting session parts for ID 611536B2030B-0002-2678-4433F083327D
08-12 20:27:53.209 10019 10055 D FirebaseCrashlytics: Session 611536B2030B-0002-2678-4433F083327D has fatal exception: false
08-12 20:27:53.209 10019 10055 D FirebaseCrashlytics: Session 611536B2030B-0002-2678-4433F083327D has non-fatal exceptions: false
08-12 20:27:53.209 10019 10055 D FirebaseCrashlytics: No events present for session ID 611536B2030B-0002-2678-4433F083327D
08-12 20:27:53.210 10019 10055 D FirebaseCrashlytics: Removing session part files for ID 611536B2030B-0002-2678-4433F083327D
08-12 20:27:53.211 10019 10055 D FirebaseCrashlytics: Closed all previously open sessions
08-12 20:27:53.212 10019 10055 D FirebaseCrashlytics: No reports are available.
08-12 20:27:53.213 10019 10055 D FirebaseCrashlytics: Initialization marker file removed: true
08-12 20:27:53.308 10019 10019 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
08-12 20:27:54.744 10019 10057 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{_o=auto, _sc=MapActivity, _si=2944307044656855024}], name=_vs, timestampInMillis=1628780274705}]
08-12 20:27:56.545 10019 10057 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1212.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=2944307044656855024, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_View_Station_Detail, timestampInMillis=1628780276487}]
08-12 20:27:56.676 10019 10057 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1232.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=2944307044656855024, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_Retrieve_Map_Data, timestampInMillis=1628780276587}]
08-12 20:27:58.322 10019 10057 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1311.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=2944307044656855024, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_Station_List, timestampInMillis=1628780278217}]
08-12 20:28:00.389 10019 10057 D FirebaseCrashlytics: Received Analytics message: 3 Bundle[{params=Bundle[{User_Type=InstantAppUser, Duration=1213.0, Status=SUCCESS, HTTP_Status_Code=200, Analytics_Reporting_App=ChargePointInstant, _o=app, _sc=MapActivity, _si=2944307044656855024, Global_Config_Region=NA-US, Analytics_Reporting_Version=15, Launch_Source=Google Play}], name=API_Station_List, timestampInMillis=1628780280160}]

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @gauravbansal-cpi thanks for reporting. We're looking into this and will get back to you with updates. Thanks

**Comment by mrichards** [comment]
It is correct that the JobScheduler-based uploader is incompatible with Instant Apps. We continue to track better support for Instant Apps as a feature request, but have no timetable for implementation. 

[Internal tracking ref: b/170120721]
