### ISSUE TITLE
Vulnernabilities Identified in com.google.firebase:firebase:firebase-perf-ktx 20.0.2 with OWASP Dependency Check

### ISSUE THREAD

**Issue by limyeewee** [firebase/firebase-android-sdk#2913]
After including com.google.firebase:firebase:firebase-perf-ktx 20.0.2 in our Kotlin project, the OWASP Dependency Check flags a number of vulnerabilities in the project. If com.google.firebase:firebase:firebase-perf-ktx 20.0.2 is removed, no vulnerabilities are identify. Please remove the vulnerabilities in com.google.firebase:firebase:firebase-perf-ktx 20.0.2.

Reference to OWASP Dependency Check can be found here - https://owasp.org/www-project-dependency-check/.

**Comment by raymondlam** [comment]
Hi @limyeewee. I've tried creating 2 empty projects (one with firebase performance and one without), and both are showing the same vulnerabilities.

Do you have the report with the specific violations that OWASP is showing so I can take a closer look?
