### ISSUE TITLE
No signature of method: build_...

### ISSUE THREAD

**Issue by graviaDaemon** [firebase/firebase-android-sdk#2915]
I've been looking all over github, stackoverflow, reddit, discord-servers, the whole shebang. I've recently implemented firebase into a project I'm doing for a udemy.com course. (Flash Chat app..)
Obviously the work they're doing is outdated, so I've been looking around to find the latest versions and the lot. 
Though when everything is imported and should work, I get this error:

**ERROR Message**
`No signature of method: build_eeszr0gcr6lj33p64zor43zf6.android() is applicable for argument types: (build_eeszr0gcr6lj33p64zor43zf6$_run_closure2) values: [build_eeszr0gcr6lj33p64zor43zf6$_run_closure2@35f07b5d]`

All of the forums I'm looking at tell me to remove `experimental true` somewhere, but nowhere can I find this in my build.gradle files.

Here are the "relevant" files:

**android/app/build.gradle**

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
    localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
    
android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }  

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.DaemonDev.application"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnables true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    } 
}
    
flutter {
    source '../..'
}

 dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:28.3.1')
     implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
    implementation "com.android.support:multidex:$multidex_version"
}
```

**android/build.gradle**

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**gradle.properties**

```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
android.enableDexingArtifactTransform=false
```

**local.properties**
```
sdk.dir=C:\\Users\\Usr\\AppData\\Local\\Android\\sdk
flutter.sdk=C:\\flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
```

**android/gradle/gradle-wrapper.properties**
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
```

I've imported the firebase **core, auth and cloud-firestore ONLY**

All the related issues have resolutions that seem not applicable, please halp!

Edit: The error message didn't copy entirely, so I fixed the error message shown in this post.

**Comment by aguatno** [comment]
Hi @graviaDaemon thanks for reporting. The error logs seem like an issue with the project itself. We'll likely need a repro or more specific details about a Firebase issue to help more. 

Moreover, try reproducing with our [quickstart](https://github.com/firebase/quickstart-android). This will help us isolate the issue and discard conflicts with other third party libraries being used. Please let me know if you have questions about this.

**Comment by graviaDaemon** [comment]
Hey @aguatno thanks for your reply
https://gitlab.com/Daemonium/chat_app
That's my repo, and I did start out using the quickstart. Which resulted in version errors for gradle, and gradlebuild. Which started this entire rabithole untill I ended up here. If I can't fix the error, I might start the entire project over

**Comment by graviaDaemon** [comment]
Edit:
I've restarted the project, and tried these following steps:

1. Go to Firestore console, and locate the app.
2. Download the google-services.json file and place it in the `<project>/android/app` folder
3. add the following lines in the following files:
in the **<project>/android/build.gradle** file
```
buildscript {
    // ...
    repositories {
        google() // had to add this line, but it was already there.
        // ...
    }
    
    dependencies {
        classpath 'com.google.gms:google-services:4.3.10' // added this line
        // ...
    }
}

allprojects {
    repositories {
        google() // had to add this line, but was already there
        // ...
    }
}
```

and in my **<project>/android/app/build.gradle**
```
// ...
apply plugin: 'com.google.gms.google-services' // add this line just above android{}
// ...

android {
    // ...
    defaultConfig {
    applicationId "com.DaemonDev.application" // had to change this from com.android.application
    // ...
    multiDexEnables true // had to add this line because of Dex Errors I received
    }
}

// ...

dependencies {
    implementation platform('com.google.firebase:firebase-bom:28.3.1') // Added line for firebase BoM
    implementation 'com.google.firebase:firebase-auth' // I'm using authentication, so added this line according to google
    implementation 'com.google.firebase:firebase-firestore' // using this for Cloud
    implementation "com.android.support:multidex:$multidex_version" // added this for multidexenables for the dex error
    // ...
}
```
when I started the project, once again I got this error:
`No signature of method: build_c50ksk4sqmgoxnny758kxl7ou.android() is applicable for argument types: (build_c50ksk4sqmgoxnny758kxl7ou$_run_closure2) values: [build_c50ksk4sqmgoxnny758kxl7ou$_run_closure2@43999258]`


From here I went to the [quickstart](https://github.com/firebase/quickstart-android/blob/master/auth/README.md) you sent me, and no success at all @aguatno

**Comment by aguatno** [comment]
@graviaDaemon Sorry for getting back late. I got the same error following the steps and it happens exactly when adding "multiDexEnables true". Could you try to change it to "multiDexEnabled true" and let me know if the issue persists? Thanks
