### ISSUE TITLE
FR: Add support for Kotlin @Serializable within Firestore

### ISSUE THREAD

**Issue by EthanLozano** [firebase/firebase-android-sdk#2916]
Please add support for `kotlinx.serialization` within `firebase-firestore-ktx` (or a similar library) for serializing documents to Firestore and deserializing documents from Firestore. The existing POJO serialization API is appreciated, but this API has several limitations (more details below).

### API Suggestion

More specifically, I would like to be able to define a Serializable object (using multiple `kotlinx.serialization` annotations):
```
@Serializable
data class MySerializableObject<T>(
    val id: String,
    @Serializable(with = MyEnum.Companion::class)
    val state: MyEnum
    @SerialName("in")
    val inner: T,
)
```

Then, I would like to serialize the object to Firestore:
```
firestore.collection("myCollection").add(serializable = mySerializableObj)
```

Also, I would like to deserialize the object from Firestore:
```
doc.addSnapshotListener { snapshot, _ ->
    ...
    val data = snapshot.toObject(serializer = MySerializableObject.serializer(InnerObject.serializer()))
    ...
}
```

### POJO serialization API limitations
1. Kotlin and Java Bean interfaces do not work too well together. Specifically, Kotlin automatically generates getters and setters. However, if the data class implements an interface, then the "override" keyword apparently generates conflicting getters that breaks POJO serialization.
2. Does not handle generics, or at least it's unclear how to handle generics.
3. Requires objects with a zero-argument constructor. 
4. Requires mutable state (Java Bean setters).
5. Requires importing an Android Library (AAR) in order to gain access to the various annotations (`@PropertyName`, `@IgnoreExtraProperties`, etc.). This makes it heavy weight for libraries that could be reused for other types of serialization in other parts of the application (file storage, network transfer, etc.)

I got around the limitations by duplicating all of my application's data classes as mutable objects with default parameter values, without inheritance, and without generics. Then, each of these objects have a `convert()` function which converts the mutable state into the canonical immutable object. Kotlin data classes are really succinct, so this wasn't too hard to do; however, I would have appreciated if I could avoid this code duplication.

**Comment by wu-hui** [comment]
Sorry for getting back late.

This is certainly a nice feature to have. Unfortunately we cannot work on this right away because we have other work planned. I can add this to our back log, will update here when things change.

**Comment by ywmei-brt1** [comment]
```
Does not handle generics, or at least it's unclear how to handle generics.
```
For the current Java POJO Bean Mapper, please refer to this test to handle gentric:

https://github.com/firebase/firebase-android-sdk/blob/0fe063e3bd4dff4d92f0991dc70f2e818d6f4c30/firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java#L1962-L1985
