### ISSUE TITLE
In app messaging crashes

### ISSUE THREAD

**Issue by macinlabs** [firebase/firebase-android-sdk#2919]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

    implementation platform('com.google.firebase:firebase-bom:25.12.0')
  
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-inappmessaging-display'

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
![Screenshot 2021-08-20 at 8 00 14 AM](https://user-images.githubusercontent.com/56329353/130169909-8369b8c2-6399-42b8-9d50-b7b7685c0a23.png)

**Comment by aguatno** [comment]
@macinlabs Sorry to hear you're running into this. It's not clear to me if this is caused by the Firebase SDK, and I’m finding it quite difficult to replicate your issue without an MCVE. It will be great if you can also share the steps to reproduce this so we can help you better. Thanks
