### ISSUE TITLE
com.google.mlkit.common.MlKitException: Failed to load deprecated vision dynamite module.

### ISSUE THREAD

**Issue by faldujaldeep** [firebase/firebase-android-sdk#2923]
Hi,
I am using firebase barcode & OCR scan SDK in my project and am able to see deprecated vision dynamite module error. Below SDK version i am using.

implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:16.1.5'
implementation 'com.google.android.gms:play-services-mlkit-text-recognition:16.2.0'

Can someone please check and advise for the solution?

**Comment by aguatno** [comment]
Hi @faldujaldeep thanks for reporting. The behavior you reported seems odd as I'm unable to reproduce this issue locally.  Try using the [latest SDK version](https://firebase.google.com/docs/android/setup) to see if we can fix it. It's probably worth trying to run our [quickstart](https://github.com/firebase/quickstart-android) project to see if the issue persists. Could you try replicating this behavior in the quickstart? If it works without issues, you could use it as a guide to compare it with your setup.

**Comment by faldujaldeep** [comment]
Hi, @aguatno This issue I found from the live users google analytics exception report and it will not reproducible on all the devices.

**Comment by aguatno** [comment]
Hi @faldujaldeep I just noticed that you're using the [Google version of ML Kit](https://developers.google.com/ml-kit). Currently we can help you in troubleshooting or debugging problems related to integrations between Firebase.

You may try different channels like [ML Kit Community ](https://developers.google.com/ml-kit/community) where you may find better help and options to troubleshoot the issue.

If the issue persists using our [libraries](https://firebase.google.com/docs/android/setup#available-libraries), please share with me screenshots of errors and the code that generates the issue, so I could check what's going on. Thanks
