### ISSUE TITLE
com.google.mlkit.common.MlKitException: Error initializing the legacy barcode scanner.

### ISSUE THREAD

**Issue by faldujaldeep** [firebase/firebase-android-sdk#2924]
Hi,
I am using firebase barcode scan SDK in my project and am able to see "Error initializing the legacy barcode scanner." this error. And below SDK version i am using in the project.

implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:16.1.5'

Can someone please check and advise on this issue?

**Comment by aguatno** [comment]
Hi @faldujaldeep It seems this is somehow related to #2923. We haven't received similar reports on this, as our [services](https://status.firebase.google.com/) are currently healthy. Try using the latest SDK version to see if we can fix it. Also, It's probably worth trying to run our quickstart project to see if the issue persists.

**Comment by faldujaldeep** [comment]
@aguatno This issue is an exceptional case and not able to reproduce on all the devices. And the above exception is happening inside ML Kit SDK only.

**Comment by aguatno** [comment]
Hi @faldujaldeep sorry to hear you're running to this issue. I tried checking our system, but there are no similar entries. You may try our quickstart to discard a problem with the service, the [quickstart](https://github.com/firebase/quickstart-android) its a good tool to compare your code/environment to see if something is missing. You may also try to replicate the error you are getting.

If the issue persists, please share with me a sample runnable app that can reproduce the issue. This will bring us a better understanding of what is happening. Thanks

**Comment by aguatno** [comment]
Hi @faldujaldeep I just noticed that you're using the [Google version of ML Kit](https://developers.google.com/ml-kit). Currently we can help you in troubleshooting or debugging problems related to integrations between Firebase.

You may try different channels like [ML Kit Community ](https://developers.google.com/ml-kit/community) where you may find better help and options to troubleshoot the issue.

If the issue persists using our [libraries](https://firebase.google.com/docs/android/setup#available-libraries), please share with me screenshots of errors and the code that generates the issue, so I could check what's going on. Thanks
