### ISSUE TITLE
Unable to run gradle tasks

### ISSUE THREAD

**Issue by sumitkp18** [firebase/firebase-android-sdk#2947]
### Discussed in https://github.com/firebase/firebase-android-sdk/discussions/2946

<div type='discussions-op-text'>

<sup>Originally posted by **sumitkp18** September  1, 2021</sup>
On running the following command: `$ ./gradlew :firebase-config:googleJavaFormat`
I am getting this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 823ms
```

Tried to upgrade gradle version, but it seems to be having some issue with kotlin dsl version and gives the following error:

```
Unable to find method ''void org.gradle.kotlin.dsl.support.EmbeddedKotlinProvider.addRepositoryTo(org.gradle.api.artifacts.dsl.RepositoryHandler)''
'void org.gradle.kotlin.dsl.support.EmbeddedKotlinProvider.addRepositoryTo(org.gradle.api.artifacts.dsl.RepositoryHandler)'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.


```
</div>

**Comment by aguatno** [comment]
Hi @sumitkp18 Based on the error logs it seems to be an issue with Gradle's dependency. You may try our [quickstart](https://github.com/firebase/quickstart-android) to discard a problem with the service, the quickstart it's a good tool to compare your code/environment to see if something is missing. You may also try to replicate the error you are getting.

If you're still experiencing this problem and want to continue the discussion, please share with me a sample runnable app that can reproduce the issue. This will bring us a better understanding of what is happening. Thanks
