### ISSUE TITLE
IllegalStateException in AppMeasurementService (starting AppMeasurementReceiver)

### ISSUE THREAD

**Issue by wp529** [firebase/firebase-android-sdk#295]
### I use the version is 11.4.2
this is the log:
```java.lang.RuntimeException:Unable to start receiver com.google.android.gms.measurement.AppMeasurementReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.gms.measurement.UPLOAD cmp=/com.google.android.gms.measurement.AppMeasurementService (has extras) }: app is in background uid UidRecord{81230bc u0a190 TRNB bg:+2m52s798ms idle change:uncached procs:1 seq(51,51,51)}```

I checked the firebase-analytics source code and found that there is a paragraph code in the AppMeasurementReceiver directly context.startService() as follows:
```
public static ComponentName startWakefulService(Context context, Intent intent) {
        synchronized (sActiveWakeLocks) {
            int id = mNextId;
            mNextId++;
            if (mNextId <= 0) {
                mNextId = 1;
            }

            intent.putExtra(EXTRA_WAKE_LOCK_ID, id);
            ComponentName comp = context.startService(intent);
            if (comp == null) {
                return null;
            }

            PowerManager pm = (PowerManager)context.getSystemService(Context.POWER_SERVICE);
            PowerManager.WakeLock wl = pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,
                    "wake:" + comp.flattenToShortString());
            wl.setReferenceCounted(false);
            wl.acquire(60 * 1000);
            sActiveWakeLocks.put(id, wl);
            return comp;
        }
    }
```
But I went to check the latest version of firebase and found that this code has not been modified, so how is it caused? How to deal with it?

**Comment by Zweihui** [comment]
My version is 11.8.0.I have the same issue.

**Comment by aguatno** [comment]
Hi @wp529 sorry for the late in response. I would like to check if you are still having issues? Have you tried the latest SDK version to see if the issue persists? Thanks
