### ISSUE TITLE
Get Extension of type 'CrashlyticsExtension' does not exist error for crashlytics  

### ISSUE THREAD

**Issue by tobecrazy** [firebase/firebase-android-sdk#2952]
### [READ] Step 1: Are you in the right place?

  **Extension of type 'CrashlyticsExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaPluginExtension, JavaInstallationRegistry, JavaToolchainService, NamedDomainObjectContainer<BaseVariantOutput>, BaseAppModuleExtension, KotlinAndroidProjectExtension, KotlinTestsRegistry, AndroidExtensionsExtension, KaptExtension, LintConfigExtension, JacocoPluginExtension, RealmPluginExtension]**
 

I already search both stackoverflow and https://github.com/firebase/firebase-android-sdk/issues/2665 , all the solutions doesn't work.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 2Build #AI-203.7717.56.2031.7678000 

  * Firebase Component:  crashlytics
  * Component version:  com.google.firebase:firebase-crashlytics:18.0.0  and com.google.firebase:firebase-crashlytics-gradle:2.7.1
  

### [REQUIRED] Step 3: Describe the problem
We wanna disable upload mapping file when build release APKs , since gradle file convert to KTS , the gradle config doesn't work.  always no firebaseCrashlytics .

#### Steps to reproduce:

config : build.gradle.kts file
import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension
**Solution 1** 
`the<CrashlyticsExtension>().mappingFileUploadEnabled = false`
**Solution 2**
`     configure<CrashlyticsExtension> {
        this.mappingFileUploadEnabled = false
      }`

**Solution 3**
```
  withGroovyBuilder {
    "FirebaseCrashlytics" {
      invokeMethod("setInstrumentationEnabled", false)
    }
  }
```
All of them doesn't work. 
#### Relevant Code:

```
 buildTypes {
    getByName("debug") {
        ...

        firebaseCrashlytics {
            mappingFileUploadEnabled = false
        }
    }
    
	...
}
```

**Comment by tobecrazy** [comment]
Hi Firebase team,

Any update for this ?

**Comment by aguatno** [comment]
Hi @tobecrazy thanks for reporting. Could you please try using the latest version firebase-crashlytics:18.2.1? This is to make sure that you have the latest updates and bug fixes. Also if the solution [here](https://github.com/firebase/firebase-android-sdk/issues/2665#issuecomment-849897741) doesn't work.

**Comment by varis-m** [comment]
having the same problem.

**Comment by KarenkovID** [comment]
Same for me with latest BOM and firebase-crashlitics-gradle. Works fine on 2.5.2
