### ISSUE TITLE
A way to record custom errors like the iOS SDKs recordExceptionModel

### ISSUE THREAD

**Issue by Olof-IL** [firebase/firebase-android-sdk#2967]
## What feature would you like to see?

I'd like to see a way to record custom errors, without involving Java Exceptions, like I can do in the iOS SDK with recordExceptionModel

## How would you use it?

In our game, we have a custom javascript engine running in native code integrated with C++, and would like to record any errors that happen when we execute our scripts. On iOS we have the option to easily create fully custom errors with custom callstacks and record them using recordExceptionModel, no matter how the error occurs or is handled. We would like to do the same in our Android version.

There does not seem to be anything similar in the Android SDK, only the option to record Java Exceptions, but our code does not throw Java Exceptions.

Particularly the part with errors with custom callstack would be useful to us.

**Comment by argzdev** [comment]
Hi @Olof-IL, we have documentations where we allow developers to create customize reports. Could you check this  [link](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android) and see if this fits your use case? For the custom callstack, are you pertaining to this [section](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios#customize-stack-traces)? If not, could you show me a reference or documentation of the custom callstacks, so we can understand this better?

**Comment by Olof-IL** [comment]
Hi @argzdev  

Thanks for getting back on this issue. We've since figured out that we can just create our own exceptions and set a custom stacktrace/callstack with Throwable.setStackTrace(StackTraceElement[] stackTrace) and send it to crashlytics.

This is exactly what we need, so there i no need for any new APIs and you can close this feature request. I understand this is standard Java, but it would be nice with a note/tip about this in the documentation.

The Android documentation (your first link) currently only mentions custom keys&logs and nothing about fully customizing your stacktrace as the iOS documentation does. (your second link)

**Comment by argzdev** [comment]
Hi @Olof-IL, this is very insightful. Thanks for sharing, we really appreciate the feedback. I'll ask our engineers if we can include this in our documentation, though I can't provide any specific timeline as to when this will be available. With that said, I'll be closing this ticket for now.
