### ISSUE TITLE
Firebase signin with email/password not working on android over wifi

### ISSUE THREAD

**Issue by arseneHuot** [firebase/firebase-android-sdk#2975]
### Environment

  * Android Studio version: 4.2.1
  * Firebase Component: Authentication
  * Component version: 21.0.1

### The problem

Firebase signin with email/password not working on android with some wifi. It works if the user try with a vpn. 
We have a lot of users reporting this problem, I have met the same problem myself on my wifi but without wifi or with a vpn it was working fine.

1. A confirmation that the issue happens from different devices.
=> Yes different device because it happens on differents network (not working in my wifi's home but working at my wifi's office)
=> when it is working using a VPN, I'm still on my Wifi ! So the problem is more about a network problem, maybe some of your CDN or anything else don't like some IP address.
=> not working on my wifi => working on my wifi BUT using a VPN => working also without wifi using mobile connection in 4G

2. Which are the errors you are getting while making these unsuccessful connections, it would be so helpful if you can share exactly what the errors say.
=> I have investigate with my own problem at my home. The problem is on this function of firebase SDK : FirebaseAuth.getInstance().signInWithEmailAndPassword(email, password)
addOnSuccessListener or addOnFailureListener is never called so the app is loading until a timeout

3. Did it work for you before or is it the first time that you have tried it?
Yes was working fine 

4. If it was working before, Did you make some changes before the issue started?
No change, happened 12 September at 9pm (Paris timezone), no app update and no backend update at this time

#### Relevant Code:

```
fun signin(
    email: String,
    password: String,
    showError: Boolean = true,
    callback: ((user: User?) -> Unit)
  ) {
    firebaseToken = ""
    FirebaseAuth.getInstance().signInWithEmailAndPassword(email, password)
      .addOnSuccessListener { task ->
      //.....
      }.addOnFailureListener { exception ->
      }
  }
```

**Comment by aguatno** [comment]
Hi @arseneHuot thanks for reporting. I tried logging in using email/pass over Wifi network and it seems to be working properly. If you are able to connect to Firebase services from your mobile data, this issue could be happening by ISP's restrictions, rather than Firebase services/SDK.

I suggest checking out if your router does not have any kind of firewall or restrictions to connect. If you feel this is an issue with the SDK, please provide a sample mcve and error logs so we can analyze it better.

**Comment by aguatno** [comment]
In addition, try reaching out to Firebase Support. They might have tools and resources to trace if this is really caused by network/ ISP's restrictions.
