### ISSUE TITLE
Firestore - Failed to get documents from server

### ISSUE THREAD

**Issue by Monabr** [firebase/firebase-android-sdk#2976]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 1
  * Firebase Component: Firestore
  * Component version: 23.0.3

#### Steps to reproduce:

What happened? How can we make the problem occur?

The problem is that if l leave the smartphone just lying and not using the application for about 20 minutes or more, then when I try to make a request, I will receive: `com.google.firebase.firestore.FirebaseFirestoreException: Failed to get documents from server. (However, these documents may exist in the local cache. Run again without setting source to SERVER to retrieve the cached documents.)`
At the same time, the Internet is available, moreover, attempts to repeat the request do not lead to success for about half a minute of attempts. That is, it looks like this: error-repeat-error-repeat-error-repeat-worked

I tried to use 
```
val settings = firestoreSettings {
            isPersistenceEnabled = false
        }
Firebase.firestore.firestoreSettings = settings
```
to fix the problem but it didn't work

#### Relevant Code:

```
query.limit(loadLimit).get(source)
            .addOnSuccessListener {
                coroutine.resume(it)
            }
            .addOnFailureListener {
                coroutine.resumeWithException(it)
            }
```

**Comment by aguatno** [comment]
Hi @Monabr thanks for reporting. I found a similar discussion [here](https://github.com/firebase/firebase-android-sdk/issues/2575#issuecomment-817923593), please try the suggested workarounds and let me know it resolves the issue. 

In addition, the exception log is of type FirebaseFirestoreException. Try extracting the error [code](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreException.Code.html) type and see if this could provide insights where the issue is coming from.

**Comment by thebrianchen** [comment]
@Monabr Can you also enable logging and share the stack trace of the error and its subsequent attempts to reconnect?

You can enable Firestore [debug logging](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#setLoggingEnabled(boolean)) by calling `FirebaseFirestore.setLoggingEnabled(true)`  prior to reproducing the error.
