### ISSUE TITLE
Multiple blocking issues for native crash debugging.

### ISSUE THREAD

**Issue by jlennox** [firebase/firebase-android-sdk#2989]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2.1
  * Firebase Component: Crashlytics
  * Component version: 2.4.1

### [REQUIRED] Step 3: Describe the problem

Hi. At Discord we use Crashlytics for monitoring our Android crashes and we've been blocked on diagnosing many issues that have native entries in the call stack.

#### External library's do not have symbols.

This one is absolutely crushing. It entirely blocks the ability to diagnose many issues.

![image](https://user-images.githubusercontent.com/836194/134080869-03360143-2896-40b7-8ab5-f9b917eac647.png)

#### Does not give libc abort messages.

This is another show stopper. Many system libraries report invalid state using `abort`. Crashlytics groups every `abort` (actually, every _libc_) crash together, as well as does not capture the abort message!!!! The abort message is of utmost importance. It's the only way to debug these issues. The above pasted stack is an example of what an abort crash looks like.

#### No thread names.

The pictured example is likely from a crash that featured a thread bomb, and crashlytics provides no assistance in debugging this. We're not able to explain where these extra threads are coming from but if we had thread names we would know.

Crashlytics also appears to silent drop threads past the 300th. Is this correct?

![image](https://user-images.githubusercontent.com/836194/134081385-33b6c43f-cdf4-46d6-a2d4-f4189fe78f67.png)

#### At times, has no cause of crash (SIGSEGV?)

![image](https://user-images.githubusercontent.com/836194/134081552-7a1665c4-40d5-404f-ad57-8bdf2eb484c7.png)

#### At times, has no indication of which thread crashed

See above screen shot.

#### No "expand all" for threads.

I'm often searching for a non-crashing thread that is doing something related. This means I can need to click on up to 300 threads so I can use control+f.

**Comment by aguatno** [comment]
Hi @jlennox It seems this may be a problem better suited for Firebase [support](https://firebase.google.com/support), since it seems to affect a specific set of projects and may require that you provide info not suitable for sharing publicly on GitHub.

Please file tickets with specific projects/apps that this affects and we'll be able to help you better.

**Comment by jlennox** [comment]
> We are sorry, but you do not have access to Google Developers. 

@aguatno I do not know what access, why it's needed, who's side that's on, etc. Are you able to open a bug report in my name?
