### ISSUE TITLE
Crashlytics web panel

### ISSUE THREAD

**Issue by iamskullking** [firebase/firebase-android-sdk#2998]
## What feature would you like to see?
The question in the web panel shows where the exception occurred. I want to know if it can be modified to display the exception type?
![image](https://user-images.githubusercontent.com/37255783/134506485-3ce34539-5383-4749-adba-347036ef241d.png)

## How would you use it?
I don’t know if this issue should be reported here, or you can tell me where to report this issue.

**Comment by aguatno** [comment]
Hi @iamskullking thanks for reporting. It seems you can filter the issue or try to use the search feature. In case you need a more granular way for searching exceptions I'd suggest filling a feature through the Firebase Support [channel](https://firebase.google.com/support/troubleshooter/contact). Thanks

**Comment by iamskullking** [comment]
OK， thank you very much
