### ISSUE TITLE
Microsoft OAuth Problems

### ISSUE THREAD

**Issue by fabricio-godoi** [firebase/firebase-android-sdk#3013]
Greetings!

I'm having two issues with the Microsoft OAuth sign-in flow in the Android SDK *only*. I've tried the same steps on iOS devices and in the Web Platform, and was not able to reproduce it.

## First problem:

When I try to sign-in in the Microsoft provider with the `startActivityForSignInWithProvider`, it results with "Failed to generate/retrieve public encryption key for Generic IDP flow." for some devices (like the Samsung Galaxy S20 FE with Android 11).  When the `startActivityForSignInWithProvider` is called, it immediately returns the error without opening any web view. If the user tries to login, with the same account, on other devices, it works without any issue. But for some unknown reason, it keeps happening consistently with some devices.

I don't know how to track it more precisely, but here is the information that I have gathered:

Device: Samsung Galaxy S20 FE with Android 11;
Browser: Google Chrome or Samsung Web Browser as the default browser;
Microsoft Users configured to login only with 2FA (SMS, Phone call, or MFA apps like Microsoft Authenticator);

Here is the stack that I was able to fetch from Crashlytics:

```
firebase_screen_class:GenericIdpActivity

PlatformException(FirebaseAuthError, An internal error has occurred. [ Failed to generate/retrieve public encryption key for Generic IDP flow. ], com.google.firebase.j: An internal error has occurred. [ Failed to generate/retrieve public encryption key for Generic IDP flow. ] at c.d.a.b.e.e.il.a(Unknown Source:151) at com.google.firebase.auth.internal.w.onReceive(Unknown Source:163) at b.l.a.a.a(Unknown Source:59) at b.l.a.a$a.handleMessage(Unknown Source:11) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8587) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) , null) 
```

Also in Crashlytics, not completely sure that is related to the bug, I found the following bugs in some devices.

Xiaomi, Redmi Note 8, Android 10.
Samsung, Galaxy A8(2018), Android 9.

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {br.com.bancobmg.superapp/com.google.firebase.auth.internal.GenericIdpActivity}: java.lang.NullPointerException: null reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4272)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4304)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7564)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)

Caused by java.lang.NullPointerException: null reference
       at com.google.android.gms.common.internal.Preconditions.a(Preconditions.java:7)
       at com.google.android.gms.internal.firebase-auth-api.zzxq.<init>(zzxq.java:3)
       at com.google.firebase.auth.internal.GenericIdpActivity.onResume(GenericIdpActivity.java:122)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
       at android.app.Activity.performResume(Activity.java:8073)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4262)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4304)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7564)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

## Second Problem:

Also, I've got login issues using the Firefox browser consistently. I was not able to perform any login with OAuth for Microsoft with Firefox. The intent starts, and I'm able to finish the Microsoft login process, but at the end, when redirected back to the Firebase, the process indicates that are missing data in the session storage.

![image](https://user-images.githubusercontent.com/7767910/135326424-0509320e-214b-48f2-b800-af0c4256d920.png)

## Some project information:

Currently, the project is written in Flutter using the [firebase_auth_oauth](https://pub.dev/packages/firebase_auth_oauth) 1.0.3 library. The source code can be checked on the [GitHub](https://github.com/amrfarid140/firebase_auth_oauth) page.

These issues have been notified in the firebase_auth_oauth with some speculation:
https://github.com/amrfarid140/firebase_auth_oauth/issues/63
https://github.com/amrfarid140/firebase_auth_oauth/issues/65
https://github.com/amrfarid140/firebase_auth_oauth/issues/68
https://ru.stackoverflow.com/questions/1331961/firebase-auth-oauth-failed-to-generate-retrieve-public-encryption-key-for-gener

Since the authentication process is a black box, I could not retrieve any other process information that could help solve such issues.

I hope that the Firebase team could help us out with these issues.

Best regards.

---

# Edit 1:

Issue update about  `An internal error has occurred. [ Failed to generate/retrieve public encryption key for Generic IDP flow. ]`. It appears to be a static cache in the Android phones that are not being cleared even with deleting and installing the application again. It appears to work again if the user goes to the phone settings and clears all application cache. I don't really understand why the data is not erased even when the application is deleted in the Android, but it seems to be a cache problem.

**Comment by fabricio-godoi** [comment]
Guys, we have any update on this issue?

Thank you!

**Comment by sam-gc** [comment]
Hi @fabricio-godoi, we have no updates at this time. As for the second issue, the web handler expects certain state to be set in session storage. It's likely some combination of settings in the web browser is causing `sessionStorage` to clear itself (or be unavailable) between the start of the login flow and the end.

**Comment by fabricio-godoi** [comment]
@sam-gc Thank you for the reply. I test the Firefox issue with the Android emulator and real device, both with the same behavior. I don't think that is a personal configuration, and just the implementation that have some issue with the way Firefox handles the session storage.

Nevertheless, if you have any update, it would be appreciated.

Best regards.

**Comment by yoyomyo** [comment]
@fabricio-godoi Were you able to reproduce the bug in other browsers on Android emulator? For example, Chrome.

**Comment by yoyomyo** [comment]
Because problem one is resolved and problem two is a bug in Firebase, I am closing this bug for now. @fabricio-godoi Please feel free to re-open if there are evidences showing otherwise.

**Comment by fabricio-godoi** [comment]
@yoyomyo 
Can you provide in which version the patch to fix the first problem will be available? I mentioned that it was possible to clear the cache and proceed with the authentication, but I think that the issue should be addressed by the SDK itself, instead realizing on the developer to know how to clear the cache.

About the second issue, in which project should we expect to have updates to fix this behavior? I thought that it was some issue related to the Android SDK. Can you point the proper way to me?

Thank you!

**Comment by yoyomyo** [comment]
@fabricio-godoi, sorry I had a typo in my previous comment s/Firebase/Firefox.
For the first problem, is it feasible to clear cache programmatically in the application code? Let me know.
For the second problem, it is a bug in Firefox and there is nothing we could do at the moment.

**Comment by fabricio-godoi** [comment]
@yoyomyo 
About the first problem:
I didn't have time to implement a way to clear the cache programmatically, the only thing that I was able to do so far is to speak with each user with this issue to manually clear the app cache in the Android settings, which seams to make the authentication works again.
This issue seams to appear more frequently when the user updates the application, which seems not to work with the previous cache, but for now I have no real evidence of this effect.

About the second problem:
Thank you for the clarification. Can you explain to us what is the issue with the Firefox browser that is leading to the issue in the Firebase? Maybe the community could find a way to help fix the issue or even some kind of workaround.

Thank you for your efforts!

**Comment by yoyomyo** [comment]
Hi @fabricio-godoi, thank you for the more detailed feedback!
For the first problem, from your description, it looks like clearing cache upon app upgrade could help? This logic would belong to the application code.
For the second problem, please refer to the previous comment https://github.com/firebase/firebase-android-sdk/issues/3013#issuecomment-987306499. I am not the most qualified to answer web related questions. However I can probably find an expert to redirect to if you have any further questions.
