### ISSUE TITLE
Authentication with Microsoft

### ISSUE THREAD

**Issue by g-sahu** [firebase/firebase-android-sdk#302]
Currently Firebase authentication does not support Microsoft/Outlook authentication. Is this on the roadmap?

**Comment by samtstern** [comment]
Yes! See https://github.com/firebase/quickstart-android/pull/820

This is happening soon, I will merge that PR once the backend makes some final changes.

**Comment by g-sahu** [comment]
Thanks! Eagerly waiting for this to be rolled out. :)
