### ISSUE TITLE
Firebase storage timeout doesn't work

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-android-sdk#3021]
#### Steps to reproduce:

I've a very simple code:
 
```
    FirebaseStorage.getInstance().setMaxUploadRetryTimeMillis(1000);
            FirebaseStorage.getInstance().setMaxOperationRetryTimeMillis(1000);
            FirebaseStorage.getInstance().setMaxDownloadRetryTimeMillis(1000);
            FirebaseStorage.getInstance().getReference("a_real_file").getFile(new File(getCacheDir(), "file")).addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {
                    System.out.println("ERROR");
                }
            }).addOnCanceledListener(() -> {
                System.out.println("canceled");
            }).addOnCompleteListener(task -> {
                System.out.println("complete");
            });
```

The files are valid and storage access is fine.

if i run this code with data ON, it works fine and "complete" is printed after a few seconds.  
however if DATA IS OFF, or any connection issue is happening, nothing shows up... none of the configurations above does affect the real Connection Timeout for firebase storage...

s

is there any way to solve this?

**Comment by aguatno** [comment]
Hi @bolds07 thanks for reporting. May I ask what version of the SDK are you using? Thanks.
