### ISSUE TITLE
OTP reaching the application after a long time. Sometimes not receiving at all

### ISSUE THREAD

**Issue by ashique-perumbavoor** [firebase/firebase-android-sdk#3049]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 
Android Studio Arctic Fox | 2020.3.1 RC 1
Build #AI-203.7717.56.2031.7557721, built on July 17, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Statistic, google-java-format, name.kropp.intellij.makefile, com.thoughtworks.gauge, org.jetbrains.kotlin, org.intellij.plugins.markdown

  * Firebase Component:
```
    implementation platform('com.google.firebase:firebase-bom:28.3.1')
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-database'
```

  * Component version: 28.3.1

### [REQUIRED] Step 3: Describe the problem

OTP is not reaching the mobile phone randomly(Some users are reporting to get the OTP after a lot of time after closing the application). It's not happening to my test phones but a lot of users are reporting the issue. Any help is appreciated.

#### Steps to reproduce:

I don't know how to reproduce the issue. It's happening randomly to some users.

#### Relevant Code:

```
fun sendOTP(mobileNumber: String) {
        val options = PhoneAuthOptions.newBuilder(auth)
            .setPhoneNumber(mobileNumber)
            .setTimeout(60L, TimeUnit.SECONDS)
            .setActivity(context)
            .setCallbacks(callBacks)
            .build()
        PhoneAuthProvider.verifyPhoneNumber(options)
    }
```

**Comment by aguatno** [comment]
Hi @ashique-perumbavoor thanks for reporting. I understand how hard it is to debug from your end. If the SDK was able sent the OTP but no OTP sent to the device. It could be an issue with the carrier so I suggest filling a Firebase support [ticket](https://firebase.google.com/support). They have tools to check if there's something wrong with the carrier. Please note that you'll have to provide some affected phone numbers from them to verify the issue. Thanks.
