### ISSUE TITLE
Custom fetchTimeout for Remote Config is ignored

### ISSUE THREAD

**Issue by adam2603** [firebase/firebase-android-sdk#3067]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 3
  * Firebase Component: Remote Config
  * Component version: 21.0.1

### [REQUIRED] Step 3: Describe the problem

I set firebase remote config fetch timeout to 5 seconds, but it is ignored and default one (60 seconds) is used.
To test this I setup charles proxy with following throttling configuration:
<img width="554" alt="Screenshot 2021-10-20 at 12 29 08" src="https://user-images.githubusercontent.com/25059578/138128159-9fd7f2df-318d-42aa-ad4c-dfdea22497d1.png">

#### Steps to reproduce:

1. Setup proxy to delay all communication for 100 seconds
2. Run app with timeout set to 5 seconds
3. FirebaseRemoteConfig.fetch blocks for around 60 seconds

#### Relevant Code:

```kotlin
val firebaseRemoteConfig = FirebaseRemoteConfig.getInstance()
firebaseRemoteConfig.setConfigSettingsAsync(
    FirebaseRemoteConfigSettings.Builder()
        .setFetchTimeoutInSeconds(5)
        .build()
).await()
firebaseRemoteConfig.fetch(remoteConfigFetchInterval).await()
firebaseRemoteConfig.activate().await()

private fun <T> Task<T>.await() = Tasks.await(this)
```

**Comment by argzdev** [comment]
Hi @adam2603, just bumping this thread. I was able to replicate the issue, I'll try to notify an engineer and see what we can do here.

**Comment by RomeuG** [comment]
Any news about this?

**Comment by MatthiasDh** [comment]
Encountering same issue.

**Comment by argzdev** [comment]
Hi all, upon testing this code snippet on the latest version `21.0.2` it seems to work properly. Could you verify if you're still experiencing this issue @adam2603.

@MatthiasDh, could you add more details such as steps to repro or minimal repro of your issue?

**Comment by adam2603** [comment]
@argzdev I'm still experiencing this issue after upgrade to version `21.0.2`

**Comment by abdulkadirgun** [comment]
Hi, is there any solution?

**Comment by andrew-just14** [comment]
Also experiencing this issue - any solution?

**Comment by danasilver** [comment]
Thanks for the reports @abdulkadirgun @andrew-just14 @adam2603. I'm wondering if you're seeing the timeout ignored outside of using Charles to increase the latency?

We control the timeout using URLConnection's [setConnectTimeout](https://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#setConnectTimeout(int)) and [setReadTimeout](https://docs.oracle.com/javase/7/docs/api/java/net/URLConnection.html#setReadTimeout(int)), so it's possible something is returned that satisfies those "connection opened" and "started to read" requirements, but the round trip latency causes the connect to still hang open beyond those two limits.

**Comment by DanielNovak** [comment]
This is still happening - at least on `21.2.0`. Sometimes (very very rarely) each `fetchAndActivate()` takes 20 seconds on my Pixel 4a. No amount of process restarts will fix it. It just takes 20 seconds every time. Setting `setFetchTimeoutInSeconds()` to for example 5 seconds doesn't help at all. It seems that the Firebase service is somehow "stuck", maybe the connection works as expected but some other parts of the Firebase Config code now cause a large delay.
Rebooting my device has fixed the huge 20+ second delays. So this confirms that it's a Firebase service issue on the device (since uninstalls or process restarts didn't fix it, only device reboot).
