### ISSUE TITLE
🐛 [realtime_database] Increment doesn't work properly when Internet Goes Down

### ISSUE THREAD

**Issue by dlondonog** [firebase/firebase-android-sdk#3068]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.2. VS Code v 1.61.1
  * Firebase Component: Firebase Realtime Database
  * Component version: firebase_database: ^8.0.0
                                        firebase_database_platform_interface 0.1.0 

### [REQUIRED] Step 3: Describe the problem

**ServerValue.Increment() works wrong when the connection goes from Online to Offline**

The addition of `ServerValue.increment()` was a great news as it allows field values ​​to be increased atomically in Firebase RTDB.

I have an application that keeps inventories and this function has been key because it allows updating the inventory regardless of whether the user is offline at times. However, I started to notice that sometimes the function is executed twice, which completely misstates the inventory in the wrong way.

To isolate the problem I decided to do the following test, which shows that ServerValue.Increment() works wrong when Internet Goes Down (the connection goes from Online to Offline)...

#### Steps to reproduce:

1. Make a `for loop function` from 1 to 200:

```
for (var i = 1; i <= 200; i++) {
  testBloc.incrementTest(i);
  print('Pos: $i');
}
```

2. The function `incrementTest(i)` must increment two variables: `position` (count from 1 in 1 up to 200) and `sum` (add 1 + 2 + 3, ..., + 200 which should result in 20,100)

```
    Future<bool> incrementTest(int value) async {    
     try {    

       db.child('test/position')
         .set(ServerValue.increment(1));     

       db.child('test/sum')
         .set(ServerValue.increment(value));     

     } catch (e) {
       print(e);
     }  


      return true;
 }
```
Note that db refers to the Firebase instance (`FirebaseDatabase.instance.reference()`)

3. You can see an error / incorrect behavior when you goes from Online to Offline (Airplane mode) during the loop and later you recover the Internet Connection. You can use a physical device to simulate the Online - Offline - Online Connection behavior.

**Expected Behavior:**

What I hope happens is that the variables get to the correct value in Firebase after the loop and once the Internet connection is recovered, like this:

position: 200 (Incrementing 1 from 1 to 200)
sum: 20100 (Incrementing i from 1 to 200... 1+2+3+...+200 = 20100)

There are the tests:

**Test 1: 100% Online. PASSED**
The function works properly, reaching the two variables to the correct result (in the Firebase console):

position: 200
sum: 20100

**Test 2: 100% Offline. PASSED**
To do this I used a physical device in airplane mode, then I executed the for loop function, and when the function finished executing I deactivated airplane mode and checked the result in the firebase console, which was satisfactory:

position: 200
sum: 20100

### **Test 3: Start Online and then go to Offline. FAILED**

It is a typical operating scenario **when the Internet Connection goes down**. Even worse when when you are traveling on a subway, the connections are intermittent, or you are in a low coverage site for which Firebase Offline Persistence is a key feature. To simulate it, what I did was run the for loop function in online mode, and before it finished, I put the physical device in airplane mode. Later I went Online to finish the test and see the results on the Firebase console. The results obtained are incorrect in all cases. Here are three of the results:

position: 210
sum: 21123

position: 218
sum: 22053

position: 209
sum: 21295

As you can see, the Increment was erroneously repeated 10, 18 and 9 times more.

#### Relevant Code:

The project is very simple to reproduce following the **Steps to Reproduce**. What you need is:
1. A for loop function (may be linked to a button)
2. A function to use `ServerValue.Increment()` as described in Steps to Reproduce (I used BLoC Pattern, you can use a different one).
3. A Physical device to emulate Internet goes down (Airplane Mode)
4. Your Firebase Console to verify the final data

**Additional context:**
The problem may be related to the ServerValue.Increment() function strategy to determine if the increment has already been executed or not
I tried to report as an Issue in [FlutterFire](https://github.com/FirebaseExtended/flutterfire/issues/7211), and they advised me that the correct place to report the problem is the Official Firebase SDK Repository.

**Comment by argzdev** [comment]
Hi @dlondonog, thanks for reporting. We don't generally have much experience with Flutter apps. With that said, if you could provide us an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that would help us alot. In the meantime, I'll try to replicate this on Android and see what I can find.

**Comment by dlondonog** [comment]
Hi @argzdev. I don't have a MCVE in Flutter, but I think that you will identify the same error when you replicate it on Android. Only a for loop and connection to the Firebase database is required. Thank you.

**Comment by argzdev** [comment]
Hi @dlondonog, thanks for your findings. However, I was unable to replicate the issue after testing it synchronously and asynchronously for Android. I tried all 3 scenarios; and for the final scenario, Firebase Realtime Database took quite some time to reconnect, but the data returned after the reconnection is still correct. Perhaps this issue is only present in Flutter? I suggest you continue your bug report in https://github.com/FirebaseExtended/flutterfire. Thanks.

For code snippets:
1. Synchronously
```
for(int i = 0; i <= 200; i++){
  try {
      Thread.sleep(400);
  } catch (InterruptedException e) {
      e.printStackTrace();
  }
  FirebaseDatabase database = FirebaseDatabase.getInstance();
  DatabaseReference db = database.getReference("test/position");
  db.setValue(ServerValue.increment(i));
}
```

2. Asynchronously
```
Observable.range(0, 201)
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .concatMap(i -> Observable.just(incrementValue(i)).delay(400, TimeUnit.MILLISECONDS))
    .subscribe(new Observer<Integer>() {
        @Override
        public void onSubscribe(@NonNull Disposable d) {
            display.postValue("Start");
        }
        @Override
        public void onNext(@NonNull Integer integer) {
            display.postValue("" + integer);
        }
        @Override
        public void onError(@NonNull Throwable e) {}
        @Override
        public void onComplete() {
            display.postValue("End");
        }
    });
```
