### ISSUE TITLE
Firestore snapshot listener is not reliable

### ISSUE THREAD

**Issue by MarkoHup** [firebase/firebase-android-sdk#3076]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 2 Build #AI-203.7717.56.2031.7678000, built on August 26, 2021
  * Firebase Component: Firestore
  * Component version: firebase-firestore:23.0.0

### [REQUIRED] Step 3: Describe the problem
The Firestore snapshot listener is not reliable. The Firestore connection will not recover after multiple WiFi access point handovers.
#### Steps to reproduce:

Try this scenario:
-     Connect your device to WiFi SSID_A
-     Start a Firestore snapshot listener
-     Start walking until you are out of range of WiFi SSID_A
-     The Firestore snapshot listener will lose its connection
-     Keep on walking until you are in range of WiFi SSID_B
-     Your device will connected to WiFi SSID_B
-     The Firestore snapshot listener should recover but the Firestore recovery process occasionally fails, it is not reliable!

After repeating this scenario 10 times the Firestore connection recovers only 9 times.

Logging:

W Firestore: (23.0.0) [s0]: (28b1652) Stream closed with status: c1{code=UNAVAILABLE, description=Channel shutdownNow invoked, cause=null}.

10-07 17:07:54.493 23279 10618 W Firestore: (23.0.0) [WatchStream]: (5ed9157) Stream closed with status: Status{code=UNAVAILABLE, description=null, cause=javax.net.ssl.SSLException: Write error: ssl=0xb400007112705cc8: I/O error during system call, Broken pipe 

10-07 17:07:54.493 23279 10618 W Firestore: at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_write(Native Method) 10-07 

17:07:54.493 23279 10618 W Firestore: at com.google.android.gms.org.conscrypt.NativeSsl.write(:com.google.android.gms@213614046@21.36.14 (150400-395708125):3) 

10-07 17:07:54.493 23279 10618 W Firestore: at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(:com.google.android.gms@213614046@21.36.14 (150400-395708125):5) 

10-07 17:07:54.493 23279 10618 W Firestore: at okio.Okio$1.write(Okio.java:79) 

10-07 17:07:54.493 23279 10618 W Firestore: at okio.AsyncTimeout$1.write(AsyncTimeout.java:180) 

10-07 17:07:54.493 23279 10618 W Firestore: at io.grpc.okhttp.AsyncSink$2.doRun(AsyncSink.java:140) 

10-07 17:07:54.493 23279 10618 W Firestore: at io.grpc.okhttp.AsyncSink$WriteRunnable.run(AsyncSink.java:192) 

10-07 17:07:54.493 23279 10618 W Firestore: at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) 

10-07 17:07:54.493 23279 10618 W Firestore: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 

10-07 17:07:54.493 23279 10618 W Firestore: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 

10-07 17:07:54.493 23279 10618 W Firestore: at java.lang.Thread.run(Thread.java:923) 10-07 17:07:54.493 23279 10618 W Firestore: }.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
val settings = FirebaseFirestoreSettings.Builder()
        .setPersistenceEnabled(false)
        .build()

val firestore = FirebaseFirestore.getInstance()
firestore.firestoreSettings = settings

messagesListener = firestore.collection("team/${settings.teamId}/messages")
                .whereEqualTo(MessageDocument::archivedAt.name, null)
                .orderBy(MessageDocument::createdAt.name, Query.Direction.DESCENDING)
                .addSnapshotListener { snapshot, exception -> handleFetchMessagesResponse(snapshot, exception) }

**Comment by thebrianchen** [comment]
@MarkoHup At the moment, we do not expose an API for connectivity changes since the SDK cannot precisely determine connectivity state and will close the streaming connection if no reads/writes have been made for some time.

One way to detect Firestore's connectivity state is to listen to the `isFromCache` metadata events on snapshot's [metadata](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/SnapshotMetadata). If Firestore is offline, you will not get the snapshot with `isFromCache` equal to false. I'm going to mark this issue as closed, but feel free to ask any other questions you may have!
