### ISSUE TITLE
[cloud_firestore] Flutter communication to Firebase over static IP address

### ISSUE THREAD

**Issue by pulstar** [firebase/firebase-android-sdk#3080]
### [READ] Step 1: Are you in the right place?

I can't say for sure, but I think the problem is with the Firestore SDK for Android.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Arctic Fox | 2020.3.1 Patch 3, Build #AI-203.7717.56.2031.7784292
  * Firebase Component: Firestore, FCM notifications
  * Component version: no idea

### [REQUIRED] Step 3: Describe the problem

I needed to configure a cell phone's wifi network as static IP so that it can be accessed over a local network from an Arduino device. Everything works except the Flutter app's communication with Firebase. Notifications do not reach their destination and collections are not updated. After returning to DHCP mode, everything works normally. 

#### Steps to reproduce:

1. Set Wifi connection setting to static IP in an Android device.
2. Try to run a Flutter App to update a Firestore collection and send FCM notifications.

**Comment by pulstar** [comment]
@dconeybe There is nothing special about the app, it is just a Flutter app with Firebase plugin connecting over a static IP address. I noticed that the device this problema occurred is running Android 7.1. Maybe this issue is already fixed in newer OS versions.

**Comment by dconeybe** [comment]
@pulstar The maintainers of this repository do not have Flutter knowledge or experience. We're happy to investigate but we need some help along the way. Personally, I think you'd be better off logging the issue against the flutterfire repository (linked to in a previous comment) where the Flutter experts can investigate. Otherwise, could you try to reproduce with this Android SDK directly? For example, see if you can reproduce using the Android quickstart: https://github.com/firebase/quickstart-android. If you can reproduce with the quickstart then we can do some investigation.

**Comment by pulstar** [comment]
@dconeybe The FlutterFire repository was my first choice, so I opened an issue there, but they said their plugin is just a wrapper around the Android SDK and they can't help me with that. So I opened the issue here. Sorry, but I have no knowledge about Android SDK. I'm going to ask the Flutter experts again. Thank you!

**Comment by dconeybe** [comment]
If you could provide a GitHub repository with a Flutter app that you use to reproduce then that would help a lot. It's just enormously helpful to see the code that is problematic for you. Are you able to write a basic app for this purpose? Then I can clone it and reproduce for myself and bridge the gap between my lack of Flutter knowledge and your lack of Android knowledge.

**Comment by dconeybe** [comment]
Also, could you provide the link of the issue you logged against Flutter?

**Comment by pulstar** [comment]
@dconeybe I am a bit busy right now, so give me a few days to do that. The link is here:

https://github.com/FirebaseExtended/flutterfire/issues/7246#issuecomment-952755635

**Comment by dconeybe** [comment]
Thanks for the link. Take your time with the reproduction app. I'll look into it when it's ready.

**Comment by pulstar** [comment]
@dconeybe After several tests I found that the problem was a bad configuration of the local network, it wasn't with the cell phone connected. Sorry for the inconvenience and thanks again for your attention.
