### ISSUE TITLE
validate firebase-installation authToken

### ISSUE THREAD

**Issue by chaitanya4288** [firebase/firebase-android-sdk#3089]
I have a use case where I am supposed to authorise requests originating from my android app. So for this I was relying on the Firebase InstanceId Tokens and validate them on the server side. So far I was using this API [validate-instanceId-api](https://developers.google.com/instance-id/reference/server#get_information_about_app_instances)

But It seems that Firebase Instance ID has been replaced with FirebaseInstallations for app instance identifiers. Now, there is something called FIS authToken as per this [documentation](https://firebase.google.com/docs/projects/manage-installations#retrieve-fis-token),

But I don't understand how do I validate these tokens on the server side. Seems the documentation doesn't point anything about validation on the server side.

**Comment by vkryachko** [comment]
> authorise requests originating from my android app

[Firebase App Check](https://firebase.google.com/docs/app-check/android/safetynet-provider) is the recommended way to do it as it provides much stronger security. I don't believe fis provides validation API.
