### ISSUE TITLE
Firestore is not working after WebRTC disconnection

### ISSUE THREAD

**Issue by Sonumohammad** [firebase/firebase-android-sdk#3091]
### Describe the problem
I am using WebRTC in webview, using simple-peer.js library.
After calling peer.destroy() (javascript), Firestore (android) is not working properly.
Snapshot listener is not firing new document changes, but I can see changes in the console.

**Comment by argzdev** [comment]
Hi @Sonumohammad, could you create another issue following our template? This is so that the necessary information is present for us to conduct an initial investigation. I'll be closing this ticket for now.
