### ISSUE TITLE
PRINT FirebaseCrashlytics.getInstance().log("MESSAGE") TO ANDROID STUDIO CONSOLE

### ISSUE THREAD

**Issue by bolds07** [firebase/firebase-android-sdk#3108]
What feature would you like to see?
I would like messages logged with FirebaseCrashlytics.getInstance().log("message"); and FirebaseCrashlytics.getInstance().recordException(new RuntimeException("exception")); GET PRINTED IN ANDROID STUDIO CONSOLE

How would you use it?
The most important objective of logging (not to say the only) is to identify and debug errors... Crashlytics is the best library I know for that, but in the current state the lib makes unnecessarily difficult to **debug in development environment.**

but as current state of firebase crashlytics it is impossible to do this in development environment.

Prior to google buy Crashlytics it was possible using the fabric api. But now seems these methods were removed.

The whole problem is, if I'm in the **development environment and want to follow the code execution (by watching the log messages)** Crashlytics wont show them... I need to intentionally cause an crash, then wait a time for it be uploaded to dashboard them start hunting for the registers among maybe thousands of others...

All other firebase libraries allow us to enable debug features which will print thousands of messages straight to console, but ironically the library made for debug doesn't allow it...

it is time to rethink this guys

**Comment by argzdev** [comment]
Hi @bolds07, since this ticket already exists, I'll mark this one as duplicate and reopen the previous one. Thanks!

**Comment by argzdev** [comment]
Duplicate of #3005
