### ISSUE TITLE
Publish Gradle Plugin marker artifacts for all Gradle Plugins to maven.google.com

### ISSUE THREAD

**Issue by gildor** [firebase/firebase-android-sdk#3125]
## What feature would you like to see?

Firebase Gradle Plugins should be published together with [Gradle plugin marker](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers). 
See [the same issue request for Android Gradle Plugin](https://issuetracker.google.com/issues/64551265) (which was fixed)

## How would you use it?

It will simplify usage of [Gradle Plugins DSL
](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block), which [became the default way to use plugins for Android project templates](https://developer.android.com/studio/preview/features?utm_source=android-studio-2021-1-1&utm_medium=studio-assistant-preview#settings-gradle)

Currently, it is required to do mapping manually for Firebase plugins (we don't have any other plugin without marker artifacts)

```
   pluginManagement {
        resolutionStrategy {
            eachPlugin {
                if (requested.id.id == "com.google.firebase.appdistribution") {
                    useModule("f:$requested.version")
                } else if (requested.id.id == "com.google.firebase.crashlytics") {
                    useModule("com.google.firebase:firebase-crashlytics-gradle:$requested.version")
                } else if ...
            }
        }
    }
```

**Comment by argzdev** [comment]
HI @gildor, thanks for the input. I'll mark this as a feature request, so that our engineers can have a look and discuss this further for future plans.

**Comment by davidmotson** [comment]
We discovered this recently and are working on a fix. Expect it to be released late next week!

I will post back here when its out.

**Comment by davidmotson** [comment]
These should be out now

**Comment by gildor** [comment]
@davidmotson Could you please specify for which version it will be available?

**Comment by davidmotson** [comment]
It is available for at least the latest version of each plugin, some plugins (like crashlytics) released a new version to implement this. 

If there is a version/artifact pair for which you need this, and cannot upgrade for some reason, let me know.
