### ISSUE TITLE
Save bandwidth when fetching firestore documents using cache

### ISSUE THREAD

**Issue by Sonumohammad** [firebase/firebase-android-sdk#3140]
## What feature would you like to see?
After reading documents for a query and getting metadata, the client-side SDK checks if any of the documents exist and are up to date, if up to date those documents will not be fetched.

Describe the feature you would like to add, ideally proposing a specific API.
1. Query and get documents metadata.
2. Check if any of the documents are up to date in the cache.
3. If up to date, don't fetch those documents from the server.

## How would you use it?
1. where documents in a list don't change frequently but require up-to-date data to be shown.

2. When the user applies a filter for a list in the app and most of the required documents will be available in the cache.
Fetching the documents again is redundant.

3. When refreshing a list, most of the documents will be available in the cache.

Another feature, It will be very useful if the client SDK has a method to get only metadata (list of document ids and modification time) for a query instead of document data.
So later client can decide if it is necessary to fetch documents.

It saves a lot of bandwidth (network egress from GCP)
Still, it costs document reads and a little bandwidth, but it's not a problem.

**Comment by argzdev** [comment]
Hi @Sonumohammad, thanks for filing. Just to clarify, this is a feature you'd like to see for Cloud Firestore or Realtime Database?

**Comment by Sonumohammad** [comment]
I am requesting for Cloud Firestore.

**Comment by argzdev** [comment]
Noted, I'll mark this as a feature request, so that our engineers can have a look and discuss this further for future plans.

**Comment by wu-hui** [comment]
Hey @Sonumohammad 

This is already implemented, to some extent: if the document/query is issued within half hour from when they are last read, backend will only send you the diff, which means backend will not send an update if the results are up-to-date.

What you proposed is hard to implement, with current backend protocol. If bandwidth is a big concern, there are some ways you can try:

* Read from cache only most of the time, and read from backend periodically (every 2~3 minutes for example).  
* Check if [Firestore Data Bundles](https://firebase.googleblog.com/2021/04/firestore-supports-data-bundles.html) apply to the data you are reading.

All in all, I do not see this feature being added to current backend protocol easily, I'd like to close this issue for now. We can revisit it in the future.
