### ISSUE TITLE
A problem was found with the configuration of task ':app:uploadCrashlyticsSymbolFileRelease' (type 'UploadSymbolFileTask'). - Type 'UploadSymbolFileTask' property 'googleServicesResourceRoot' doesn't have a configured value in dynamic feature module

### ISSUE THREAD

**Issue by WIPPayal** [firebase/firebase-android-sdk#3141]
```
A problem was found with the configuration of task ':app:uploadCrashlyticsSymbolFileRelease' (type 'UploadSymbolFileTask').
  - Type 'UploadSymbolFileTask' property 'googleServicesResourceRoot' doesn't have a configured value.

* What went wrong:
A problem was found with the configuration of task ':app:uploadCrashlyticsSymbolFileRelease' (type 'UploadSymbolFileTask').
  - Type 'UploadSymbolFileTask' property 'googleServicesResourceRoot' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'googleServicesResourceRoot'.
      2. Mark property 'googleServicesResourceRoot' as optional.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#value_not_set for more details about this problem.
```
    
Android Studio Version: 4.2.2
Crashlytics version: 2.8.0
Note: Symbol file uploading is working for app module but not for dynamic feature module
We have similar [issue ]( https://github.com/firebase/firebase-android-sdk/issues/2721) raised also

**Comment by WIPPayal** [comment]
> I found a few problems with this issue:
> 
> * I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
> * This issue does not seem to follow the issue template. Make sure you provide all the required information.

This issue is related to already closed [one](https://github.com/firebase/firebase-android-sdk/issues/2721)

**Comment by argzdev** [comment]
Hi @WIPPayal, thanks for reporting. May I ask what steps did you take to reproduce the issue? Also did trying the solution provided in the closed issue helped? It would be helpful if you could provide us a sample project with the issue. Thanks!

**Comment by WIPPayal** [comment]
@google-oss-bot  I am still facing this issue. I will not able to provide you source code.
I have integrated firebase [crashlytics ndk](https://firebase.google.com/docs/crashlytics/ndk-reports) support for dynamic feature module . While uploading symbols i am getting above error
:app:uploadCrashlyticsSymbolFileRelease.
Notes:
In my project i have dynamic feature module along with base module. For base module symbol file uploading is working for dynamic feature module it is giving issue
