### ISSUE TITLE
Firebase crashlytics stack info obfuscated

### ISSUE THREAD

**Issue by ethanhua** [firebase/firebase-android-sdk#3159]
### Version:

firebase-boom version: 26.1.0
firebase-crashlytic  version:17.3.0
com.google.firebase:firebase-crashlytics-gradle:2.4.1
dexguard version : 9.2.3

### Problem:

some crash stack on firebase console is obfuscated, like this: 

<img width="810" alt="截屏2021-11-22 下午2 36 26" src="https://user-images.githubusercontent.com/22186185/142814439-1bf4e2b1-a04b-450b-9351-fde58c8956e5.png">

some class still show the obfuscated name and the source line num also isn't correct.

i asked dexguard engineer，they said maybe this caused by firebase crashlytics deobfuscated rule, the rule don't know how to deobfuscated this,

<img width="852" alt="截屏2021-11-22 下午2 40 45" src="https://user-images.githubusercontent.com/22186185/142815670-4f0a3f62-5c2f-41ca-bd42-fcba2d8bd938.png">

how to solve it?

**Comment by argzdev** [comment]
Hi @ethanhua, thanks for reporting. Could you try using our latest version of BoM (29.0.0) and see if you still encounter the issue? We usually advise this to avoid issues that have been resolved in the previous versions.

**Comment by argzdev** [comment]
Upon checking, this issue seems more suitable for our backend team to investigate. Could you file a ticket in our [support channel](https://firebase.google.com/support) instead, so they can conduct a deeper investigation on this. With that said, I'll be closing this ticket now, thanks!
