### ISSUE TITLE
distinguish  between automatically collected exceptions and actively reported exceptions

### ISSUE THREAD

**Issue by iamskullking** [firebase/firebase-android-sdk#3162]
## What feature would you like to see?

version in our project:
firebase-boom version: 26.1.0
firebase-crashlytic  version:17.3.0

We have the need to actively report some exceptions. I would like to ask if there is an API to add filter conditions, or if there is a way to distinguish between automatically collected exceptions and actively reported exceptions.

![image](https://user-images.githubusercontent.com/37255783/142969550-95b18881-2506-4f6b-92b1-44a30cd6f26f.png)

## How would you use it?

We will take the initiative to distinguish some crashes.

**Comment by argzdev** [comment]
Hi @iamskullking, thanks for your input. AFAIK, there is no API for filtering conditions. With that said, I'll mark this as a feature request, so our engineers can have a look and discuss this for future plans.

May I ask though, just to clarify when you're pertaining to "automatically collected exceptions and actively reported exceptions." 
Do you mean by automatically collected exceptions = Crashlytics automatically logging exceptions during crashes? And actively reported exceptions = sending and using customized crash reports?

**Comment by iamskullking** [comment]
> Hi @iamskullking, thanks for your input. AFAIK, there is no API for filtering conditions. With that said, I'll mark this as a feature request, so our engineers can have a look and discuss this for future plans.
> 
> May I ask though, just to clarify when you're pertaining to "automatically collected exceptions and actively reported exceptions." Do you mean by automatically collected exceptions = Crashlytics automatically logging exceptions during crashes? And actively reported exceptions = sending and using customized crash reports?

Thanks for your answer. @argzdev , We will actively report some exceptions through recordException() in try catch and these exceptions = actively reported exceptions, automatically collected exceptions = Crashlytics automatically logging exceptions during crashes

**Comment by argzdev** [comment]
Hi @iamskullking, well said. Thank you for the clarification. Let's leave this ticket open until sometime that it is picked up by our engineers.

**Comment by iamskullking** [comment]
> Hi @iamskullking, well said. Thank you for the clarification. Let's leave this ticket open until sometime that it is picked up by our engineers.

Thank you very very much for your help～ @argzdev
