### ISSUE TITLE
What Data Type the Firebase SDK require?

### ISSUE THREAD

**Issue by 3bdev** [firebase/firebase-android-sdk#3170]
Today we filled the new Data Safety form in Play Console and received a refusal with this reason:

Data sent off device undeclared in Data safety form: **App Activity Data Type - Installed Apps**

Does Fireabase/Crashlytics need this data type? Or we should check for other SDK like DFP/AdManager? Cause on our side we don't access that data type.

Thanks. A list of the required access by Firebase could be useful in order to comply with the Data Safety stuff.

**Comment by 3bdev** [comment]
Sorry. Closing the issue.
I noticed it was related to a version without Firebase.

**Comment by argzdev** [comment]
Hi @3bdev, sure that's alright. Thanks for clearing up the confusion.
