### ISSUE TITLE
Firestore QuerySnapshot is empty in first launch or run

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#3203]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2020.3.1
  * Firebase Component: Firestore, Storage
  * Component version: 24.0.0

### [REQUIRED] Step 3: Describe the problem

Had a simple query with Firestore inside `ViewModel`, everything is okay except it does not go inside the `for` statement and never triggers and this usually happens on first launch or install of the project. 

Note: This is the first page (Fragment) of `ViewPager` while the second page which just have an identical approach on getting documents works fine.

    fun fetchAssignments(){
    
            fireStore.collection(appContext.getString(R.string.assignment))
                .whereEqualTo(appContext.getString(R.string.type), GlobalConfig.userData.shift)
                .orderBy(appContext.getString(R.string.time), Query.Direction.DESCENDING)
                .get()
                .addOnSuccessListener {
    
                    val assList = mutableListOf<AssignmentData>()
    
                    for (item in it){
    
                        val assignment = item.toObject(AssignmentData::class.java)
                        assignment.documentId = item.id
                        assList.add(assignment)
    
                    }
    
                    assignmentList.value = assList
    
                }
                .addOnFailureListener {
    
                    assignmentList.value = listOf()
    
                }
    
        }

But on my second run the `for` statement is working, maybe the cache helps as well

This must be a bug because why such query works on the second fragment with almost same query and not with the first fragment, and why when I call the function again via retry button it works as intended?

#### Steps to reproduce:

Here, I install the app directly and the snapshots is empty. Then just press back in the navigation to close the app and reopen/launch it and now it works as expected. The `QuerySnapshot` is no longer empty.

https://user-images.githubusercontent.com/38008900/144735457-80749371-d434-4144-bbaa-693db3779d49.mp4

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hi @ArcherEmiya05, thanks for reporting. I'll try to repro the issue and see what I can find.

**Comment by dconeybe** [comment]
@ArcherEmiya05 Could you also reproduce the issue with debug logging enabled and attach the resulting logs? Reproduce it both when the query results are unexpectedly 0 and when the expected set of documents is returned. To enable debug logging, call [`FirebaseFirestore.setLoggingEnabled(true)`](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#setLoggingEnabled(boolean)) before making any other calls to Firestore.
