### ISSUE TITLE
Getting error if setting android:exported="true" and tools:node="replace" in Manifest application tag

### ISSUE THREAD

**Issue by hamzaahmedkhan** [firebase/firebase-android-sdk#3204]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 3
  * Firebase Component: 
```
    implementation "com.google.firebase:firebase-core:20.0.0"
    implementation "com.google.firebase:firebase-crashlytics:18.2.4"
    implementation 'com.google.firebase:firebase-config-ktx:21.0.1'
    implementation "com.google.firebase:firebase-analytics-ktx:20.0.0"
    implementation 'com.google.firebase:firebase-firestore-ktx:24.0.0'
```
    
### [REQUIRED] Step 3: Describe the problem

After switching the app to CompileSdk and targetSdk version 31, it required exported flag for each activity, including projects and dependency activity.
so I set following code in Manifest application tag to set exported true for all.
```
android:exported="true"
tools:replace="android:exported"
tools:node="replace"
```
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Just set following code in Manifest application tag
android:exported="true"
tools:replace="android:exported"
tools:node="replace"

**Comment by argzdev** [comment]
Hi @hamzaahmedkhan, thanks for providing steps and details. May I ask what's the problem you're experiencing, is it a crash or bug when using Firebase? I tried to use the code snippet you provided on a fresh project and I don't seem to experience any crashing or bugs.

**Comment by hamzaahmedkhan** [comment]
Hi @argzdev, I am facing a NullPointerException when using firestore db `FirebaseFirestore.getInstance()`

`java.lang.RuntimeException: Unable to create application com.tech.bazaar.shipper.AppApplication: java.lang.NullPointerException: Firestore component is not present.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by hamzaahmedkhan** [comment]
@vkryachko thanks for the explanation, well it's not just about Firebase activities. After using compileSDK and targetSDK version 31, now it is required to explicitly defined `android:exported` flag for all the components. Including all the 3rd party dependencies. and so many 3rd party dependencies doesn't have exported flag defined in their manifest So I was trying to add this flag for all the components of my application.

For that case I added ` tools:node="replace"` in application tag and set exported="false" during manifest merging
But after your explanation, it seems like we can't use 'tools:node="replace"' as it does not preserve metadata values for ComponentDiscoveryService.

What I did now is I removed tools:node="replace" and manually added all these components in my app manifest class.

```
        <activity
            android:name="com.readystatesoftware.chuck.internal.ui.MainActivity"
            android:label="@string/chuck_name"
            android:launchMode="singleTask"
            android:taskAffinity="com.readystatesoftware.chuck.task"
            android:theme="@style/Chuck.Theme" />
        <activity
            android:name="com.readystatesoftware.chuck.internal.ui.TransactionActivity"
            android:parentActivityName="com.readystatesoftware.chuck.internal.ui.MainActivity"
            android:theme="@style/Chuck.Theme"
            android:exported="true"/>

        <activity
            android:name="com.mazenrashed.printooth.ui.ScanningActivity"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"
            android:exported="true">
            <intent-filter>
                <action android:name="com.mazenrashed.universalbluethootprinter.ui.ScanningActivity.LAUNCH" />
            </intent-filter>
        </activity>
        <activity android:name="com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity"
            android:exported="true">
        </activity>
        <receiver android:name="com.mixpanel.android.mpmetrics.MixpanelPushNotificationDismissedReceiver"
            android:exported="true">
        </receiver>
```

**Comment by vkryachko** [comment]
Just to clarify, you should be able to keep using 

```
android:exported="true"
tools:replace="android:exported"
```

without tools:replace on components that don't specify the exported attribute. But you don't need to do this for firebase since we do explicitly specify it in our declarations
