### ISSUE TITLE
https://www.google.com/httpservice/web/CardApiService/GetRenderedCardsStreaming?safe=on&client=ms-android-rogers-ca-revc&hl=en&output=search&ie=UTF-8&q=Apps+google+play+link+:+https://play.google.com/store/apps/details?id%3Dequalizer.bassbooster.musicplayer.theme.pro&spell=1

### ISSUE THREAD

**Issue by davin67** [firebase/firebase-android-sdk#3220]
https://www.google.com/httpservice/web/CardApiService/GetRenderedCardsStreaming?safe=on&client=ms-android-rogers-ca-revc&hl=en&output=search&ie=UTF-8&q=Apps+google+play+link+:+https://play.google.com/store/apps/details?id%3Dequalizer.bassbooster.musicplayer.theme.pro&spell=1

**Comment by argzdev** [comment]
Seems like spam, closing this ticket.
