### ISSUE TITLE
An ANR issue occurred after upgrading Firebase to BoM 29.0.0.

### ISSUE THREAD

**Issue by yuki7wang** [firebase/firebase-android-sdk#3239]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Arctic Fox | 2020.3.1 patch 1
  * Firebase Component: Firebase BoM
     * com.google.firebase:firebase-analytics
     * com.google.firebase:firebase-perf
     * com.google.firebase:firebase-appindexing
     * com.google.firebase:firebase-dynamic-links
     * com.google.firebase:firebase-crashlytics
     * com.google.firebase:firebase-crashlytics-ndk
  * Component version: 29.0.0

### [REQUIRED] Step 3: Describe the problem

The ANR:
executing service [My package name]/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService 
com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService

And there's no "Stack trace" info for this ANR.
The attached images are all the info we have.

#### Steps to reproduce:

We cannot reproduce. 

Actually, we doubted about WorkManager in the beginning. So we tried to change the version of 
"androidx.work:work-runtime" from 2.5.0 to 2.7.0, but still got the same ANR in the Play Console.

#### Relevant Code:

```
Old firebase versions:
    firebaseCoreVersion = '18.0.3'
    firebasePerfVersion = '19.0.9'
    firebaseConfigVersion = '19.2.0'
    firebaseAdsVersion = '18.2.0'
    firebaseAppindexingVersion = '19.1.0'
    firebaseMessagingVersion = '20.3.0'
    firebaseDynamicLinkVersion = '19.1.0'

Current firebase: BoM 29.0.0
```
![anr](https://user-images.githubusercontent.com/55964336/145948027-0779b6b2-ea51-498f-9167-3b25666f3f3f.png)
![anr2](https://user-images.githubusercontent.com/55964336/145948769-26be3791-99cd-49ff-97ac-d3f4d8ca8d5f.PNG)

**Comment by argzdev** [comment]
Hi @yuki7wang, thanks for reporting. I'll try to investigate and see what I can find.

**Comment by clevertrevor** [comment]
I have the same exact issue using BoM v28.0.0. I will upgrade to the latest `29.0.3` to release early in January.

**Comment by argzdev** [comment]
Hi all, since there's no update on this. I'll be closing this issue for now. Please open a new ticket if you still encounter this issue.

**Comment by PranavMalayil** [comment]
Hi all, getting the same error after using firebase analytics
