### ISSUE TITLE
After updated to "com.google.gms:google-services:4.3.10" Cannot resolve symbol 'default_web_client_id'

### ISSUE THREAD

**Issue by maliqhammad** [firebase/firebase-android-sdk#3242]
**1. Cannot resolve symbol 'default_web_client_id'
2. ApiException: 10**

W: com.google.android.gms.common.api.ApiException: 10: 
W:     at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.5.0:4)
W:     at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@19.2.0:3)
W:     at com.azex.rentole.activity.LoginAndRegister.ActivityLoginWithSocial.onActivityResult(ActivityLoginWithSocial.java:294)
W:     at android.app.Activity.dispatchActivityResult(Activity.java:7466)
W:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4496)
W:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4545)
W:     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
W:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
W:     at android.os.Handler.dispatchMessage(Handler.java:106)
W:     at android.os.Looper.loop(Looper.java:193)
W:     at android.app.ActivityThread.main(ActivityThread.java:6814)
W:     at java.lang.reflect.Method.invoke(Native Method)
W:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by argzdev** [comment]
Hi @maliqhammad, thanks for reporting. However, we would like to ask you to kindly file a new issue following our template, this is so that we can gather the basic necessary information to conduct an investigation. With that said, I'll be closing this ticket.
