### ISSUE TITLE
Remote config crash on startup

### ISSUE THREAD

**Issue by vlazdra** [firebase/firebase-android-sdk#3245]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment
  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 4
  Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
  Runtime version: 11.0.10+0-b96-7281165 x86_64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  macOS 12.0.1
  GC: G1 Young Generation, G1 Old Generation
  Memory: 4096M
  Cores: 12
  Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
  Non-Bundled Plugins: com.dengzii.plugin.adb, Dart, org.jetbrains.kotlin, io.flutter, com.developerphil.adbidea, com.intellij.lang.jsgraphql

  * Firebase Component: Remote Config
  * Component version: BOM 29.0.2

### [REQUIRED] Step 3: Describe the problem

Once updated from 28.4.2 to 29.0.2 the Firebase remote config SDK won't instantiate. It produces a crash as shown bellow.
Note: The Google services library version used is: "com.google.gms:google-services:4.3.10"

#### Steps to reproduce:

In my case I just updated the BOM from 20.4.2 to 29.0.2

These are all the libraries used with the BOM
- "com.google.firebase:firebase-analytics-ktx"
- "com.google.firebase:firebase-messaging"
- "com.google.firebase:firebase-perf"
- "com.google.firebase:firebase-config"
- "com.google.firebase:firebase-crashlytics-ktx"
- "com.google.firebase:firebase-iid"

#### Relevant Code:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.e247.radio538.dev.debug, PID: 28806
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
        at redacted.doWork$lambda-2$lambda-0(Unknown Source:7)
        at redacted.$r8$lambda$DINMtVKWpN8cLcreI8VVAfa1BvI(Unknown Source:0)
        at redacted$$ExternalSyntheticLambda1.onSuccess(Unknown Source:4)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.0:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by argzdev** [comment]
Hi @vlazdra, thanks for reporting. May I ask was there any steps or code necessary to produce the crash? If you can provide us with an MCVE, that'll greatly help our investigation as well.

**Comment by vlazdra** [comment]
Hi @argzdev I just updated the BOM version. The same default remote config was used locally and nothing was changed in the meantim on the dashboard.

Although, not sure if it's of any value, there are some values defined inside the remote config dashboard but not locally inside the default XML.
There is no default value set for those values in the dashboardz so that might be an issue?

Note: I did try defining those values inside the default XML but the crash was still occuring.


Unfortunately I can't share the entire project where it is reproducible.

**Comment by argzdev** [comment]
Hi @vlazdra, thanks for the details. I'll try to investigate this and see what I can find.

**Comment by vlazdra** [comment]
Hey @argzdev if it's off any value, I tried the same scenario of just running the app on two devices Pixel 5 (Android 12) and Galaxy Note 9 (Android 11), they both have the same crash.

Also tried changing the Kotlin version in the project the same crash happens with 1.5.31 and 1.6.0

**Comment by vlazdra** [comment]
Hey @argzdev I think that I identified the library that is crashing.

So if you update Firebase BOM from 28.4.2 to 29.0.2 it will pull in `"com.google.android.gms:play-services-tasks:18.0.0@aar"` and that library is the culprit of why the Remote Config can't instantiate properly.

The same happened if I update the Cast SDK from 20.0.0 to 21.0.0 (BOM was 28.4.2 in this case)
`"com.google.android.gms:play-services-cast-framework:20.0.0"` this also pulls in the  `"com.google.android.gms:play-services-tasks:18.0.0@aar"`

What do you think? Is the Tasks library the culprit here?

**Comment by argzdev** [comment]
Hi @vlazdra, thanks for providing more details about this case. I tried creating a clean project while adding the same dependencies you have, and trying to mix & match remote config values with or without default values, but I still can't seem to reproduce this type of behavior even with the said versions.

I can't say for sure which exactly is the culprit since I'm unable to reproduce the issue, however your point is a plausible one. 
May I ask if this is reproducible on all devices? If it's possible for you to provide us a minimal reproducible example of this issue, I'll be able to investigate this further.

**Comment by vlazdra** [comment]
@argzdev Hi, thanks for checking the issue.

I will try to provide you the minimal reproducible example ASAP.

**Comment by argzdev** [comment]
Sure, I'll wait for the repo. Thanks!
