### ISSUE TITLE
Crashed by Receiver not registered: com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver@aa2bc7f

### ISSUE THREAD

**Issue by zhouweidong** [firebase/firebase-android-sdk#3271]
com.google.firebase:firebase-messaging:23.0.0

I received some crash from firebase by Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver@aa2bc7f

please help me!

Caused by java.lang.IllegalArgumentException
Receiver not registered: com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver@aa2bc7f
android.app.LoadedApk.forgetReceiverDispatcher (LoadedApk.java:1523)
android.app.ContextImpl.unregisterReceiver (ContextImpl.java:1712)
android.content.ContextWrapper.unregisterReceiver (ContextWrapper.java:733)
com.google.firebase.messaging.SyncTask$ConnectivityChangeReceiver.onReceive (com.google.firebase:firebase-messaging@@23.0.0:5)
android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args (LoadedApk.java:1666)
android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run (-.java:2)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8633)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by argzdev** [comment]
Hi @zhouweidong, please use our template when filing a report so we can retrieve the basic necessary information before conducting an initial investigation. With that said, I'll be closing this ticket.
