### ISSUE TITLE
Firebase Performance: Crash - Caused by java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by esyuleyman** [firebase/firebase-android-sdk#3296]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.2
  * Firebase Component: Performance Monitoring library  - com.google.firebase:firebase-perf
  * Component version: 20.0.0

### [REQUIRED] Step 3: Describe the problem
The app is crashing when use HttpClient communication:
Stack trace:
```
Caused by java.lang.IncompatibleClassChangeError
Class 'org.apache.http.message.BufferedHeader' does not implement interface 'org.apache.http.NameValuePair' 
in call to 'java.lang.String org.apache.http.NameValuePair.getValue()' 
(declaration of 'com.google.firebase.perf.network.h' appears in base.apk!classes3.dex)

com.google.firebase.perf.network.NetworkRequestMetricBuilderUtil.getApacheHttpMessageContentLength (NetworkRequestMetricBuilderUtil.java:45)
com.google.firebase.perf.network.FirebasePerfHttpClient.execute (FirebasePerfHttpClient.java:195)
com.google.firebase.perf.network.FirebasePerfHttpClient.execute (FirebasePerfHttpClient.java:48)

```
#### Steps to reproduce:
Add  to use the following http client in your code:
'org.apache.httpcomponents » httpclient'
When use some requests, for example PUT Request.
On response it is crashing with the stack described above.
Regarding the crash log and the sources in the Git repository - it is in the parsing Response content length.

#### Relevant Code:

```
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPut;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.DefaultHttpClient;

public class SampleCodeClass {
. . . . . . 

    public void checkPutRequest() {
              HttpClient httpClient = new DefaultHttpClient();
               HttpPut request = new HttpPut(<url>);
               StringEntity se = new StringEntity( "{ \"key\": \"value\"}", ContentType.APPLICATION_JSON);
                se.setChunked(false);
                request.setEntity(se);
                request.setHeader("Authorization", <authorization_token>);
                request.setHeader("Content-Type", ContentType.APPLICATION_JSON.toString());
                /////////////////////////////////////////////////////////////////////////////////////////
                // Crashing in the next line
                HttpResponse response = httpClient.execute(request);
                /////////////////////////////////////////////////////////////////////////////////////////
       . . . . . . 
    }
}
```

**Comment by argzdev** [comment]
Hi @esyuleyman, thanks for reporting. We'll try to investigate and see what we do about this. In the meantime, any chance that you could provide us a [minimal reproducible example ](https://stackoverflow.com/help/minimal-reproducible-example)of this issue? It'll help speed up our investigation. Thanks!

**Comment by esyuleyman** [comment]
I have updated the issue description with sample (function). 
You can use the checkPutRequest() method in your test code (for example in: https://github.com/firebase/quickstart-android/tree/master/perf) with replacing the <url> with correct real existing server address and json body with "{}"

**Comment by argzdev** [comment]
Thanks for the extra details, @esyuleyman. May I ask what version of `org.apache.http` are you using? I'm having problems finding the correct library version that contains both `ContentType` and `HttpClient`. Also I noticed that this is a deprecated version for SDK version 23 and above. Have you tried using the latest httpcomponent on this [link](https://search.maven.org/artifact/org.apache.httpcomponents.client5/httpclient5/5.2-alpha1/jar), and see if you still experience the issue on that version?
