### ISSUE TITLE
auto collection of android_id is not compliance with privacy policy

### ISSUE THREAD

**Issue by nuyunhai** [firebase/firebase-android-sdk#3319]
when i set firebase_crashlytics_collection_enabled  false in menifest.xml,android_id is still collected。so,how to disable it,
?I  predict to collect  data  when i agree it manually。follow is my code in  AndroidMenifest.xml.

`<meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="false"
            tools:replace="android:value"/>
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false"
            tools:replace="android:value"/>
        <meta-data
            android:name="firebase_performance_collection_enabled"
            android:value="false"
            tools:replace="android:value"/>
        <meta-data
            android:name="google_analytics_ssaid_collection_enabled"
            android:value="false" />`

**Comment by argzdev** [comment]
Hi @nuyunhai, could you open a new issue using our template? We always ask this so that we can gain the basic necessary information to conduct an initial investigation of your issue. With that said, I'll be closing this case now.
