### ISSUE TITLE
auto collection of android_id is not compliance with privacy policy

### ISSUE THREAD

**Issue by nuyunhai** [firebase/firebase-android-sdk#3320]
## What feature would you like to see?

when i set firebase_crashlytics_collection_enabled  false in menifest.xml,android_id is still collected。so,how to disable it,
?I  predict to collect  data  when i agree it manually。Of course,I'm not sure whether this issue  is a feature  request or  a bug  report.
follow is my code in  AndroidMenifest.xml
`<meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="false"
            tools:replace="android:value"/>
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false"
            tools:replace="android:value"/>
        <meta-data
            android:name="firebase_performance_collection_enabled"
            android:value="false"
            tools:replace="android:value"/>
        <meta-data
            android:name="google_analytics_ssaid_collection_enabled"
            android:value="false" />`

## How would you use it?

I  will  disable  all   data  collection  before  users  agree my  privacy  policy,and  enable  it   when  them authorize it.

**Comment by argzdev** [comment]
Hi @nuyunhai, thanks for filing a new report. Could you help me answer a few questions to help us narrow down the issue:

1. Where is the `android_id` being collected and shown? Is this in the Crashlytics dashboard?
2. What version of Firebase `Crashlytics` are you using?
3. Are the other meta-data not collecting `android_id`? (e.g. analytics, performance, google_analytics_ssaid)

Thanks!

**Comment by mrichards** [comment]
The only place the `android_id` is used currently in the Crashlytics SDK is in the `isEmulator` heuristic, so the value is not reported to our backend. (Also, we don't make any network calls if data collection is disabled.)

We're taking a look to see if we can reimplement `isEmulator` to avoid that query, or get rid of that function entirely. We'll keep this issue open while we investigate.

**Comment by nuyunhai** [comment]
Thanks! I know that the&nbsp; collection&nbsp; of&nbsp; android_id will not report,but the verification of privacy polilcy will be&nbsp; failed&nbsp; just&nbsp; because androud_id was got when my app is launching.so thanks for you trying to avoid it!



---Original---
From: "Marc ***@***.***&gt;
Date: Mon, Jan 24, 2022 23:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [firebase/firebase-android-sdk] auto collection of android_id isnot compliance with privacy policy (Issue #3320)




 
The only place the android_id is used currently in the Crashlytics SDK is in the isEmulator heuristic, so the value is not reported to our backend. (Also, we don't make any network calls if data collection is disabled.)
 
We're taking a look to see if we can reimplement isEmulator to avoid that query, or get rid of that function entirely. We'll keep this issue open while we investigate.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by argzdev** [comment]
Hi @nuyunhai, while this is being investigated, since mrichards mentioned that no network calls are being made when data collection is disabled, may I ask if you've used any Crashlytics specific code in your app? Perhaps this triggered a network call sending `android_id`?
