### ISSUE TITLE
firebase-perf plugin marker for 1.4.1 doesn't seem to have been uploaded

### ISSUE THREAD

**Issue by smetz** [firebase/firebase-android-sdk#3337]
### [READ] Step 1: Are you in the right place?

I believe so, this is an issue with the firebase-perf plugin

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Bumblebee 2021.1.1 RC 1
  * Firebase Component: `firebase-perf` gradle plugin
  * Component version: 1.4.1

### [REQUIRED] Step 3: Describe the problem
The marker for version 1.4.1 of the firebase-perf plugin doesn't seem to have been uploaded.
We're getting the following build error when trying to use 1.4.1

```
FAILURE: Build failed with an exception.

* Where:
Build file '/opt/workspace/build.gradle.kts' line: 6

* What went wrong:
Plugin [id: 'com.google.firebase.firebase-perf', version: '1.4.1', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.google.firebase.firebase-perf:com.google.firebase.firebase-perf.gradle.plugin:1.4.1')
  Searched in the following repositories:
    MavenRepo
    Google
    Gradle Central Plugin Repository
```

1.4.1 of the underlying plugin artifact exists: https://dl.google.com/android/maven2/com/google/firebase/perf-plugin/1.4.1/perf-plugin-1.4.1.pom
as does the plugin marker for 1.4.0: https://dl.google.com/android/maven2/com/google/firebase/firebase-perf/com.google.firebase.firebase-perf.gradle.plugin/1.4.0/com.google.firebase.firebase-perf.gradle.plugin-1.4.0.pom
but not the plugin marker for 1.4.1: https://dl.google.com/android/maven2/com/google/firebase/firebase-perf/com.google.firebase.firebase-perf.gradle.plugin/1.4.1/com.google.firebase.firebase-perf.gradle.plugin-1.4.1.pom

#### Steps to reproduce:
Reference the plugin in the build.gradle.kts as follows
```
plugins {
    id("com.google.firebase.firebase-perf") version "1.4.1"
}
```

#### Relevant Code:

We're currently able to work around this issue using the following code in `settings.gradle.kts`:
```
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.google.firebase.firebase-perf") {
                useModule("com.google.firebase:perf-plugin:${requested.version}")
            }
        }
    }
```

**Comment by davidmotson** [comment]
The artifact should be live now. Thank you so much for alerting us to this, and let me know if you run into further issues.
