### ISSUE TITLE
Unresolved reference: "appDistributionProperties"

### ISSUE THREAD

**Issue by ribafish** [firebase/firebase-android-sdk#3369]
### [READ] Step 1: Are you in the right place?
Issues filed here should be about bugs in the code in this repository.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

For general technical questions, post a question on StackOverflow
with the firebase tag.
For general Firebase discussion, use the firebase-talk
google group.
For help troubleshooting your application that does not fall under one
of the above categories, reach out to the personalized
Firebase support channel.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Bumblebee 2021.1.1 RC 1
  * Gradle: 7.3.3
  * Android Gradle Plugin: 7.0.3
  * Firebase Component: App Distribution Gradle Plugin (Database, Firestore, Storage, Functions, etc)
  * Component version: 3.0.0

```
Android Studio Bumblebee | 2021.1.1 RC 1
Build #AI-211.7628.21.2111.8005941, built on December 16, 2021
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.toml.lang (0.2.155.4114-211), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40)
```

###  [REQUIRED] Step 3: Describe the problem

After updating the `com.google.firebase.appdistribution` plugin from `2.2.0` to `3.0.0`, to get the gradle configuration cache fixes, we're getting `Unresolved reference: "appDistributionProperties"` error when syncing in AS, or trying to build from commandline with `../gradle assemble*`. 

#### Steps to reproduce:

We have an app with multiple flavors and multiple flavor dimensions. For most of them we can have a common `firebaseAppDistribution` configuration, applied via `AppDistributionExtension`, but for some we want to specify special configs. Until now, we did it via the code pasted below (example), for which we want access to the `Property<AppDistributionProperties>`, which was available for use in `UploadDistributionTask` until `2.2.0`. 

How can we achieve the same effect with version `3.0.0`, or is this a bug?

#### Relevant Code:

We have this in the main app module `build.gradle.kts` file, to configure one of the builds differently:
```
project.afterEvaluate {
    tasks.withType(com.google.firebase.appdistribution.gradle.UploadDistributionTask::class){
        val distributionProperties = appDistributionProperties.get()
        val applicationVariant = distributionProperties.variant as ApplicationVariant
        if (applicationVariant.name == "someVariantName") {
            distributionProperties.groups = "qa"
            distributionProperties.serviceCredentialsFile = project.findProperty("serviceCredentialsFile") as String?
        }
    }
}
```

**Comment by tagboola** [comment]
Hey @ribafish. To support configuration cache, we had to make a breaking change and update the fields in our task. Specifically, we removed the `appDistributionProperties` field and instead added all inputs as fields of type `Property` on the task. This is why your code isn't working.  Here is an updated snippet that _should_ work.

```
project.afterEvaluate {
  var variant = "someVariantName"
  tasks.getByName("appDistributionUpload$variant") {
    if (this is com.google.firebase.appdistribution.gradle.UploadDistributionTask) {
      this.groups.set("qa")
      this.serviceCredentialsFile.set(project.findProperty("serviceCredentialsFile").toString())
    }
  }
}
```

Please let me know if this fixes your issue. Also, just an FYI the API for the task is not publicly documented, and can technically change anytime, so it's not guaranteed that custom scripts like these will work in between releases.

**Comment by ribafish** [comment]
@tagboola Yeah, that makes sense. I know this is not publicly documented, but it's the easiest way to achieve what we want (since we have some conditional variants that are configured on some build flags we need to pass in). Thank you for the speedy support, this (with a few minor modifications) works as expected.
