### ISSUE TITLE
java.lang.Exception: Client is offline

### ISSUE THREAD

**Issue by zoltish** [firebase/firebase-android-sdk#3380]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1
  * Firebase Component: RTDB
  * Component version: 29.0.0

#### Steps to reproduce:

Since publishing a beta release w/ Firebase RTDB, Ive seen a few stack traces like this. I saw another similar bug report, but the generic nature of the stack traces leaves me clueless to where the problem actually lies. 

Im using a bunch of different API:s, and I have `setPersistenceEnabled(true)`. From my understanding, the issue can be a result of trying to read a value when offline, and no cached value being available; but I also saw mentions of (something similar to) D) causing the crash (in another bug report). 

Im basically wondering if I need to wrap all my firebase calls in `try catch`; or if theres a subset that I can work with? A clearer stack trace would be infinitely helpful, but I understand why thats a hard thing to do given the async nature of it.

A)
```
reference.get()
            .await()
```

B) 
```
 reference.updateChildren(map)
            .await()
```

C)
```
   reference.removeValue()
            .await()
```

D)
```
callbackFlow {
            val observer = FirebaseObserver { notification ->
                trySend(notification).getOrThrow()
            }

            reference.addChildEventListener(observer)

            awaitClose {
                reference.removeEventListener(observer)
            }
        }.buffer(UNLIMITED)
```

#### Relevant Code:

```
Fatal Exception: java.lang.Exception: Client is offline
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$get$1(PersistentConnectionImpl.java:441)
       at com.google.firebase.database.connection.PersistentConnectionImpl.$r8$lambda$DHovbqW2nxPacSd_wNZBtpYapws(PersistentConnectionImpl.java)
       at com.google.firebase.database.connection.PersistentConnectionImpl$$InternalSyntheticLambda$0$52bf7d7d868f9879d27ad3cf2834b3947f2289fd1666388cdb330423e612114c$1.run(PersistentConnectionImpl.java:8)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by argzdev** [comment]
Hi @zoltish, thanks for the report! Unfortunately, without a way of reproducing this issue, it'll be difficult to investigate. However, I did get a feedback from our engineer regarding your question.

I'm paraphrasing here:
What you can do is throw an exception in this case by invoking an error callback on a listener, you should handle this for all listeners. Any listener for uncached data should get the same error, on the other hand, if there is data in the cache, then the client returns data even when offline. Note that the new .get() API would return a rejected Task as it does not use callbacks

**Comment by zoltish** [comment]
Hey again, @argzdev! 

> Note that the new .get() API would return a rejected Task as it does not use callbacks

I believe this is what causes the reported crash. I looked through the [source code](https://github.com/firebase/firebase-android-sdk/blob/ad37944ac1969fd8a3398a350702ef0f9d0168ae/firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java#L441) and it sure does look like it. Ive reworked my implementation to handle this case and the error hasnt come up since, so feel free to close this issue. 

Feedback-wise, it would probably help others if the documentation for the `.get().await()` call mentioned it crashing if there is no locally cached value available!

**Comment by argzdev** [comment]
Hello again, @zoltish. I'm glad that helped resolve your issue, I've filed an internal bug for our docs to be updated b/217670553. With that said, I'll close this issue now. Thanks!
