### ISSUE TITLE
slow / jank frames in 120 fps devices

### ISSUE THREAD

**Issue by jeethu-johnson** [firebase/firebase-android-sdk#3386]
## What feature would you like to see?

I think the firebase SDK currently categorises and reports slow / jank frames that takes 16ms and above. But in devices that are rendered with 120 fps this number doesn't hold true. 

## How would you use it?

This will help me identify and fix slow / jank frames in devices running 120 fps and above.

**Comment by jeethu-johnson** [comment]
Currently slow frames are tracked in performance SDK not Crashlytics. So this would be an add-on to that I suppose.

**Comment by argzdev** [comment]
Well noted, thanks @jeethu-johnson! Our engineers will take a look at this once they have the time.

**Comment by raymondlam** [comment]
Hi @jeethu-johnson 

Thanks for the feature request!

Some background, we are targeting 16ms to align with [Android Vitals’ definition of slow rendering](https://developer.android.com/topic/performance/vitals/render). This is to make sure that we are showing values consistent with Android. The article also has a link for the rationale on [why 60FPS is being used](https://www.youtube.com/watch?v=CaMTIgxCSqU).

 But, as more higher FPS devices come into the market, it’s definitely important for developers to want to ensure that their app is performant for higher refresh screens. I’ve surfaced this to our team to see when we can prioritize measuring slow/jank frames for different refresh rates and display it in our dashboard.
