### ISSUE TITLE
com.google.firebase.database.tubesock.WebSocketException: unknown host

### ISSUE THREAD

**Issue by Tom3652** [firebase/firebase-android-sdk#3390]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.1.1
  * Firebase Component: Database 
  * Component version: latest version of [firebase_database](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database) in flutter.

### [REQUIRED] Step 3: Describe the problem

I am using flutter and i believe that the Firebase Android SDK must be close to the latest version in the flutter plugin but i can't find where it is declared.

Sometimes when my app start i am having this error in logs which delay the first query i am making to my database.  
This was using ```FirebaseDatabase.instance``` so there is no error for a shard URL or anything, i don't even know this hostname :

```
D/PersistentConnection(29777): pc_0 - Trying to fetch auth token
D/PersistentConnection(29777): pc_0 - Trying to fetch app check token
D/PersistentConnection(29777): pc_0 - Successfully fetched token, opening connection
D/Connection(29777): conn_38 - Opening a connection
D/WebSocket(29777): ws_38 - WebSocket error.
D/WebSocket(29777): com.google.firebase.database.tubesock.WebSocketException: unknown host: s-euw1b-nss-206.europe-west1.firebasedatabase.app
D/WebSocket(29777): 	at com.google.firebase.database.tubesock.WebSocket.createSocket(WebSocket.java:332)
D/WebSocket(29777): 	at com.google.firebase.database.tubesock.WebSocket.runReader(WebSocket.java:360)
D/WebSocket(29777): 	at com.google.firebase.database.tubesock.WebSocket.access$000(WebSocket.java:47)
D/WebSocket(29777): 	at com.google.firebase.database.tubesock.WebSocket$2.run(WebSocket.java:143)
D/WebSocket(29777): 	at java.lang.Thread.run(Thread.java:923)
D/WebSocket(29777): Caused by: java.net.UnknownHostException: Unable to resolve host "s-euw1b-nss-206.europe-west1.firebasedatabase.app": No address associated with hostname
D/WebSocket(29777): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
D/WebSocket(29777): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
D/WebSocket(29777): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
D/WebSocket(29777): 	at java.net.Socket.<init>(Socket.java:218)
D/WebSocket(29777): 	at javax.net.ssl.SSLSocket.<init>(SSLSocket.java:931)
D/WebSocket(29777): 	at com.android.org.conscrypt.AbstractConscryptSocket.<init>(AbstractConscryptSocket.java:97)
D/WebSocket(29777): 	at com.android.org.conscrypt.OpenSSLSocketImpl.<init>(OpenSSLSocketImpl.java:41)
D/WebSocket(29777): 	at com.android.org.conscrypt.ConscryptEngineSocket.<init>(ConscryptEngineSocket.java:77)
D/WebSocket(29777): 	at com.android.org.conscrypt.Java8EngineSocket.<init>(Java8EngineSocket.java:42)
D/WebSocket(29777): 	at com.android.org.conscrypt.Platform.createEngineSocket(Platform.java:302)
D/WebSocket(29777): 	at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:108)
D/WebSocket(29777): 	at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:598)
D/WebSocket(29777): 	at com.google.firebase.database.tubesock.WebSocket.createSocket(WebSocket.java:320)
D/WebSocket(29777): 	... 4 more
D/WebSocket(29777): ws_38 - closing itself
D/Connection(29777): conn_38 - Realtime connection failed
D/Connection(29777): conn_38 - closing realtime connection
D/PersistentConnection(29777): pc_0 - Got on disconnect due to OTHER
D/PersistentConnection(29777): pc_0 - Scheduling connection attempt
D/ConnectionRetryHelper(29777): Scheduling retry in 688ms
D/WebSocket(29777): ws_38 - closed
```

Fortunately, there is an automatic retry that performs the connection again later and make queries but my UI stays black for nothing when this happens.
I have made an [issue](https://github.com/FirebaseExtended/flutterfire/issues/7990) in the FlutterFire repo and they told me it was an SDK one.  
They also told me to follow up on #1258 but i am not sure that this is related and the thread was locked anyway.

#### Steps to reproduce:

Sorry I have no idea how to reproduce it, sometimes it simply happens in my logs (no bad connection or anything).  
I also believe this why my beta test users are telling me "sometimes it's very long to load".

**Comment by Tom3652** [comment]
Hi @argzdev, no problem i understand !

I have setup a local database to avoid bad user experience during long time queries if this happens or a bad connection.  

This is not critical in my opinion as there is an automatic retry to connect, but i can't reproduce this by turning off wifi / mobile data for example so i wondered where it could come from :)

**Comment by the-thirteenth-fox** [comment]
I have the same problem. It is look likes a Firestore problem that solves by method `FirebaseFirestore.instance.disableNetwork()` when turning off wifi / mobile.
But in this case `FirebaseDatabase.instance.goOffline()` solves the problem with some bugs.
The bug is that the methods of reading, writing and the like stop working.

**Comment by Tom3652** [comment]
I am sorry but how this is a solution ? I don't want my database to be shut down or offline... 

Besides, the SDK behaves actually pretty well meaning that it auto reconnects when the network comes back, that's the wanted behavior by users. 

Also, when i turn off internet connection, i see other kind of errors that the database lost connection etc.. but it's not this one and it's not impacting users, it's the "usual" error in that case.

I simply wanted to point out this log because it's different from the "usual" error when the database is offline and it seemed to me it was a bug, but again this is not preventing me from using RTDB :)

**Comment by argzdev** [comment]
It might be related to the grpc issue #3469, Firestore was also experiencing network issues related to that. The update might fix this issue as well.

**Comment by the-thirteenth-fox** [comment]
> I am sorry but how this is a solution ? I don't want my database to be shut down or offline...
> 
> Besides, the SDK behaves actually pretty well meaning that it auto reconnects when the network comes back, that's the wanted behavior by users.
> 
> Also, when i turn off internet connection, i see other kind of errors that the database lost connection etc.. but it's not this one and it's not impacting users, it's the "usual" error in that case.
> 
> I simply wanted to point out this log because it's different from the "usual" error when the database is offline and it seemed to me it was a bug, but again this is not preventing me from using RTDB :)

As I know, a similar problem with Firestore has not yet been solved, so at least such a temporary solution will avoid errors related to network disconnection, hopefully everything will be fixed in the future.

**Comment by argzdev** [comment]
Hi, just bumping this issue. Are you still experiencing this issue, @Tom3652?

**Comment by Tom3652** [comment]
Hi @argzdev, no i have not come across this in newest releases. Thanks !

**Comment by argzdev** [comment]
Awesome, I'm glad it's working. I'll close this issue now.
