### ISSUE TITLE
Some Crashlytics stack traces still obfuscated  

### ISSUE THREAD

**Issue by mitchell-ibarra** [firebase/firebase-android-sdk#3392]
### Environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 3
  * Firebase Component: Crashlytics
  * Component version: 
     * firebase-bom version: 28.4.2
     * Crashlytics Gradle plugin version: 2.7.1

### Problem

Some stack traces in Crashlytics still show up as obfuscated, such as below:
![Screen Shot 2022-02-02 at 12 27 46 PM](https://user-images.githubusercontent.com/73446624/152222992-782a504c-6e76-4ac3-aa52-66beb3699034.png) 

From looking at the Crashlytics console, this seems to only occur with the production release of our app and only with some of the stack traces. Our debug project on Firebase shows that all of those stack traces are de-obfuscated correctly. Our debug and production builds use the same proguard-rules file, and I can see from the FirebaseCrashlytics logs that the mapping file does seem to get created correctly. 

If I take the obfuscated stack trace from Firebase and use our generated mapping.txt file with the retrace.sh script, I can see the stack trace be correctly de-obfuscated as well.

#### Relevant Code:
This is from the app's build.gradle file and is the same for both our 'release' and 'debug' build types: 

```
minifyEnabled = true
shrinkResources = true
proguardFiles(getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro")
```
Please let me know what other information you may need. Thank you!

**Comment by mrichards** [comment]
Hi @mitchell-ibarra, are you seeing that identical stack traces are sometimes deobfuscated and sometimes not? That is, for a specific issue, are you seeing obfuscated and deobfuscated traces on the Crashlytics console? Or is a given stacktrace *always* being deobfuscated or *always* staying obfuscated? Knowing this will help us narrow down the root cause.

**Comment by mitchell-ibarra** [comment]
Hi @mrichards, thank you for reaching out.
 
For specific issues we are seeing that the stack traces always obfuscated and sometimes they are more obfuscated than other times.
For example: 
![Screen Shot 2022-02-07 at 11 53 23 AM](https://user-images.githubusercontent.com/73446624/152852878-dad53e6b-4ca3-4cfa-ab16-f43c69bf5e3e.png)
At times this issue shows up like this, and other times it shows up with some of the package names deobfuscated while some of the names are not.

It also seems like most of these obfuscated stack traces occur within Coroutines as the stack traces will mention "invokeSuspend" followed by the "resumeWith" as shown above.

**Comment by mattbusuu** [comment]
I am seeing the same on bom version 29.1.0.
I can de-obfuscate using the mapper file generated at build time and everything looks fine (for multiple different crashes), but Firebase does not show the full error.
My gradle looks like:
```
 release {
            minifyEnabled true
            firebaseCrashlytics {
                mappingFileUploadEnabled true
            }
            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                "proguard-rules.pro",
                "proguard-project.txt"
                .........
```

**Comment by mitchell-ibarra** [comment]
@mrichards Hello, wondering if there have been any updates on this. Thank you!

**Comment by mrichards** [comment]
@mitchell-ibarra @mattbusuu Sorry I lost track of this issue! Can you both make sure you are on the latest versions of the Crashlytics SDK (18.2.9) and the latest Crashlytics Gradle plugin (2.8.1). The Firebase App Distribution plugin version should not matter for deobfuscation.

Once on the latest versions, if the issue persists, please provide the debugging output from your Gradle build.  You can filter to just the Crashlytics-specific output like this:
`> ./gradlew app:assembleRelease --debug | grep "\[com.google.firebase.crashlytics\]"`

(Replace `app:assembleRelease` above with the appropriate task name.)

If you are not running the default `assemble` or `bundle` Android Gradle plugin tasks, it is possible that the Crashlytics mapping file upload task is not being automatically scheduled by our plugin. If that's the case, you can try explicitly running the module's `uploadCrashlyticsMappingFile<VARIANT>` task from the command line. If that seems to work but you're seeing incorrect stack traces, we may need to do a little more work to configure the task dependencies correctly.


If you are not comfortable sharing your Gradle output or more details about your build config publicly, please feel free to email Firebase support and reference this issue.
