### ISSUE TITLE
Obfuscation problem

### ISSUE THREAD

**Issue by alex9153** [firebase/firebase-android-sdk#3395]
I receive crash in unreadable format (R8 obfuscation). How to fix it?  
<img width="517" alt="Снимок экрана 2022-02-03 в 12 14 23" src="https://user-images.githubusercontent.com/353832/152314055-7f880908-11e0-4fec-a225-d7c693d3be12.png">

**Comment by argzdev** [comment]
Hi @alex9153, thanks for filing a report. For issues like these, it would be better if you file them to our [Firebase support](https://firebase.google.com/support/troubleshooter/contact) instead. With that said, I'll be closing this now. Thanks!

**Comment by argzdev** [comment]
You may also try reaching out to the Flutter team at https://github.com/FirebaseExtended/flutterfire, since this is a flutter issue.
