### ISSUE TITLE
Android 10 Firebase analytics-> Debug view shows sign_up event twice

### ISSUE THREAD

**Issue by morevishal06** [firebase/firebase-android-sdk#3424]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Arctic Fox 2020.3.1 Patch 3
  * Firebase Component: Firestore analytics
  * Component version: 20.0.2

#### Steps to reproduce:

Firebase custom event is showing only once when triggered. But when we trigger "sign_up" event then it shows twice in debug view

#### Relevant Code:
                FirebaseAnalytics mFirebaseAnalytics = FirebaseAnalytics.getInstance(mContext);
                mFirebaseAnalytics.setUserId(getMainUserId());
                Bundle bundle = new Bundle();
                bundle.putString(FirebaseAnalytics.Param.METHOD, "Email");
                bundle.putString("email",getLoginUserEmailID());
                bundle.putString("name",getMainUserFName()+" "+getMainUserLName());
                bundle.putString("user_id",getMainUserId());
                mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SIGN_UP, bundle);

**Comment by morevishal06** [comment]
![two_signup](https://user-images.githubusercontent.com/95213747/153407132-cb6c083b-38c6-481e-8c9e-f41457104d49.PNG)
This is how it looks on debug view. dfc_sign_up is custom event showing only once & sign_up is showing twice.

**Comment by argzdev** [comment]
Thank you for the extra details. Perhaps, there's somewhere in your code which is triggering `sign_up` event twice. 

What you can do is create a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of this issue on a clean project. If you're able to repro the issue, please share it with us. If not, then you can use that to cross reference and debug the code implementation in your project.

**Comment by argzdev** [comment]
Hi @morevishal06, unfortunately, I cannot answer your question. 

Since our engineers currently have a lot on their plates, if you could provide us an [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of your issue, then I can probably justify an engineer’s time to dig into it with that much evidence. 

You could try what I previously said:
> What you can do is create a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of this issue on a clean project. If you're able to repro the issue, please share it with us. If not, then you can use that to cross reference and debug the code implementation in your project.

This may help you debug your app.

**Comment by argzdev** [comment]
Since this issue is stale, I'll be closing it for now.
