### ISSUE TITLE
A/B Testing bug

### ISSUE THREAD

**Issue by bill-121** [firebase/firebase-android-sdk#3428]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____2020.3.1
  * Firebase Component: _____firebase-config:20.0.0  firebase-analytics:18.0.3  firebase-crashlytics:17.2.2  firebase-auth:20.0.0  firebase-messaging:21.0.0
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Hi, i'm using A/B Testing, i create 3 variant(base variant, variant A, variant B), after running some days, variant B is the best, so i published variant B, but i still fetched variant A on my device even uninstall/reinstall my app, i don't understand why this happened, i think all device will fetch variant B after i published variant B, that's right?

**Comment by argzdev** [comment]
Hi @bill-121, thanks for your report. This doesn't seem to be a direct issue with the SDK, but rather a process/implementation issue. That being said, could you reach out to our [Firebase support](https://firebase.google.com/support), they can better assist you and help you with your issue. 

I'll be closing this ticket for now. Thanks!
