### ISSUE TITLE
Allow to access short link / dynamic link

### ISSUE THREAD

**Issue by build3r** [firebase/firebase-android-sdk#3445]
## What feature would you like to see?

Allow the app to access the original short link/ dynamic link. 

## How would you use it?

We have use case where we want to track the short link and share it our custom analytics setup. The Firebase dynamic link sdk only exposes the deeplink. But the dynamic link is there but is marked as private field. It would be good if we can access it directly without having to go through reflection.
The [line](https://github.com/firebase/firebase-android-sdk/blob/c374dbe186e20a756f5da156c5b09481508f5bc9/firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/PendingDynamicLinkData.java#L35)
```
public class PendingDynamicLinkData {

  @Nullable private final DynamicLinkUTMParams dynamicLinkUTMParams;
  @Nullable private final DynamicLinkData dynamicLinkData;
```

**Comment by argzdev** [comment]
Hi @build3r, thanks for the request. I've marked this as a feature request so that our engineers can take a look at this when they have the time. Thanks!

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
