### ISSUE TITLE
Crashlytics fails to track app startup crashes

### ISSUE THREAD

**Issue by vibin** [firebase/firebase-android-sdk#3467]
### Describe your environment

  * Android Studio version: 2020.3.1 patch 4
  * Firebase Component: Crashlytics
  * Component version: 17.4.1

### Describe the problem

Crashlytics' uncaught exception handler is printing TimeoutException when tracking crashes that happen in Application.onCreate().

```
FirebaseCrashlytics  E  Error handling uncaught exception
FirebaseCrashlytics  E  java.util.concurrent.TimeoutException
FirebaseCrashlytics  E      at t8.h0.a(Utils.java:11)
FirebaseCrashlytics  E      at t8.j.G(CrashlyticsController.java:6)
FirebaseCrashlytics  E      at t8.j$b.a(CrashlyticsController.java:1)
FirebaseCrashlytics  E      at t8.p.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:4)
FirebaseCrashlytics  E      at io.sentry.UncaughtExceptionHandlerIntegration.uncaughtException(UncaughtExceptionHandlerIntegration.java:19)
FirebaseCrashlytics  E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
FirebaseCrashlytics  E      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
FirebaseCrashlytics  E      at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
```

#### Steps to reproduce:

1. Integrate Firebase Crashlytics with auto initialisation.
2. Create a custom Application class and throw an exception from there.

Expected: Crashlytics should track crashes that happen in Application class
Actual: Crashlytics fails to track crashes that happen in Application class and [logs a TimeoutException](https://github.com/firebase/firebase-android-sdk/blob/9dec703a90767e1646466d2786ddda2b25201d84/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java#L234) in that process

Other information: We also use Sentry for crash reporting and it seems to track these crashes just fine

**Comment by argzdev** [comment]
Thanks for the report, @vibin. Upon reproducing, I also did not receive a crash report on Crashlytics dashboard when the exception happens in the Application class. A minor difference with that, I did not receive a `TimeoutException`, rather a `RuntimeException`.

Relevant Code:
```
public class CustomApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        throw new RuntimeException("Test Crash");
    }
}
```

With that said, I'll notify an engineer and see if what we can do here.

**Comment by tommyjackson** [comment]
Any updates on this one?

**Comment by mrichards** [comment]
We believe this was fixed in Crashlytics [v18.2.3](https://firebase.google.com/support/release-notes/android#crashlytics_v18-2-3). Anyone experiencing this issue should update to the latest SDK version using the [Firebase BoM](https://firebase.google.com/docs/android/learn-more#bom) (currently BoM v30.4.0). If the problem persists, please open a new GitHub issue. Thanks!

**Comment by vibin** [comment]
@mrichards I tried the scenario (an unconditional `throw RuntimeException()`) in my Application class with Crashlytics v18.2.8 and it doesn't track these crashes.

If the startup crash happens conditionally, then Crashlytics is successfully able to send the previous crash the next time App inits without crash.

Is this the expected behaviour? Is there no way for Crashlytics to track unconditional startup crashes, like Play Console?

**Comment by mrichards** [comment]
@vibin Yes, it seems that the 18.2.3 updated helped but didn't ensure launch-time crashes got sent in all cases. The next release (18.3.0, due out soon), will resolve this by sending the crash reports immediately at crash time, without restarting the app in the background. As long as the device has connectivity, all early launch crashes will get sent to our servers.
