### ISSUE TITLE
Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=com.pkg.abc/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) }

### ISSUE THREAD

**Issue by zainriaz** [firebase/firebase-android-sdk#3468]
A huge number of ANRs use firebase FCM. 

  ` implementation platform('com.google.firebase:firebase-bom:29.0.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-config:21.0.1'
    implementation 'com.google.firebase:firebase-messaging'`
 
Also tried the old version of firebase messaging
 `implementation 'com.google.firebase:firebase-messaging:20.0.0'`
 but the ANR still exist.

The ANRs report on play console, I test the application with test notification on actual devices listed on play console but I didn't see any ANR in the log.

**Comment by argzdev** [comment]
Thanks for the report, @zainriaz. Thanks for trying version 20.0.0, could I ask you to try version 19.0.1 and see if that also reports ANR? This'll help our engineering team pinpoint what version the issue started occurring and possibly come up with a fix.

**Comment by vivchar** [comment]
We a lot of the same issues on PROD, looks like it happens when a user receive a FCM in background (or when app is not launched)
```
	firebaseAnalyticsVersion = '19.0.1'
	firebaseCrashlyticsVersion = '17.3.0'
	firebaseAppIndexingVersion = '19.1.0'
	firebaseDynamicLinksVersion = '19.1.0'
	firebaseConfigVersion = '19.1.4'
	firebaseMessagingVersion = '20.2.4'
	firebaseInAppMessagingVersion = '19.0.7'
	firebaseInAppMessagingGuava = '27.0.1-android'
	firebaseAuthVersion = '20.0.3'
```

**Comment by argzdev** [comment]
Hi @vivchar, could you try downgrading to version 19.0.1, to see if that resolves the issue? This is so that we can determine in which version did the ANR began happening.

**Comment by fanfanxiaozu** [comment]
![image](https://user-images.githubusercontent.com/3436091/156761707-e1dbf5a3-7bb0-4518-b402-1d2f6e103702.png)
I think the order broadcast leads to the anr problem , why not change it to unOrder broadcast? If this, there will be no anr.

**Comment by argzdev** [comment]
Hi @fanfanxiaozu, may I ask why do you think `sendOrderedBroadcast` is causing ANR? And why `UnorderedBroadcast` will work?

**Comment by fanfanxiaozu** [comment]
> Hi @fanfanxiaozu, may I ask why do you think `sendOrderedBroadcast` is causing ANR? And why `UnorderedBroadcast` will work?
The reason for anr is very complicated and very hard to find,  it may not be the reason on the app side.  But the Android framework code will only monitor the anr timeout of the ordered broadcast receiver.

**Comment by argzdev** [comment]
I see, thanks for the extra details @fanfanxiaozu. For now, let's keep this ticket open in case our engineers might have an idea what the issue is. Feel free to add any questions or extra information. Thanks!

**Comment by 1008k** [comment]
Same for me, also happening with Firebase BOM 29.2.1.
