### ISSUE TITLE
Update grpc-java to 1.44.1

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-android-sdk#3469]
There's a fix to, what we consider a critical issue, with network detection on Android devices in `1.44.1`. The PR and explanation can be found here: https://github.com/grpc/grpc-java/pull/8855

Pretty sure this will fix several longstanding issues upstream in Flutterfire: https://github.com/FirebaseExtended/flutterfire/issues/6749#issuecomment-1024228063

I've been pestering your support department about this, and they assured me that you're aware of the issue. Well the fix is now here.

I'm hoping this isn't a dependency that is too difficult to update, and we can get this out of the door fairly quickly.

Thanks

**Comment by argzdev** [comment]
Thanks for the update, @larssn. I've made the change as needed, but I'll ask an engineer to take a closer look at it, if whether it's clear for merging or needs update.

**Comment by argzdev** [comment]
I've closed the previous PR to avoid redundancy. Please track the update of grpc version on PR #3473 instead. Thanks!

**Comment by wu-hui** [comment]
https://github.com/firebase/firebase-android-sdk/pull/3473 is merged.

It might take couple weeks for the next version to release..you can try getting a snapshot version or build from source directly if you want to use it.

**Comment by larssn** [comment]
@wu-hui Thank you so much!

It shouldn't be a problem to compile the source. Just not source how to include the built aar's in flutterfire as they reference the BoM in their gradle files. If you have any tips for doing that I'd appreciate it.

Closed in https://github.com/firebase/firebase-android-sdk/pull/3473

**Comment by larssn** [comment]
@wu-hui Any idea when the next BoM will be released?

**Comment by dconeybe** [comment]
We expect a release in the next week. Sorry that I can't give you a firmer date.

**Comment by larssn** [comment]
Thanks, that's perfect 👍
