### ISSUE TITLE
[RTDB] High memory usage when observing large datasets

### ISSUE THREAD

**Issue by zoltish** [firebase/firebase-android-sdk#3503]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Canary 4
  * Firebase Component: Database
  * Component version: 29.0.4 (BOM)

### [REQUIRED] Step 3: Describe the problem

At the root, the problem is that whenever Im signed into Firebase RTDB, my app stutters at times. Its clearly noticeable, and after running the memory profiler (in a release build) Ive noticed that the memory usage grows a lot whenever the firebase integration is active - and remains high until the app is closed / you sign out. 

To compare, normally my app uses about 40 mb of memory, and when signed in that number grows to 90 mb for a completely new & empty account, and if theres a lot of data stored, it sits at about 160 mb, or 4x the normal usage.

I dont know if its fair/correct to compare it with Google Fit considering how different they are, but I will say that Fit behaves "correctly" per my perspective - the memory does grow by about 30-40 mb, but as it grows towards 40 it always drops back down to 30, whereas firebase just continiously grows and grows, and then never drops.

Im observing 6 different references for as long as the app is active (and youre signed in), each reference resides under path/uid/, so "exercises/my_id/..list". The list in my code is 2200 elements long, and Im observing the whole thing as Id like to download updates to any of the elements as soon as it happens. Every element stored in firebase has a version field associated with it, which I compare with locally to find out if the "downloaded" data is actually newer than whats already stored locally. 

My hope in posting this is that its a bug in firebase. That something keeps things around in memory for much longer than needed. At the worst, Ive made some mistakes in my implementation - Im open to that too!

#### Steps to reproduce:

Sign in, and add `ChildEventListener` to 6 different references. 

#### Relevant Code:

For each reference in firebase, this code runs.

```
val reference = database
            .getReference(branch.path()) // "exercises"
            .child(token.userId()) // "uid"

// Scope = IO + SupervisorJob()
scope.launch {
        observe().collect{ 
        // Even if the collect is empty, memory usage remains the same 
    }
}

  private  fun observe(): Flow<SyncNotification> {
        return callbackFlow {
            val observer = SyncObserver(this)

            reference.addChildEventListener(observer)

            awaitClose {
                reference.removeEventListener(observer)
            }
        }.buffer(UNLIMITED)
    }
```

`SyncNotification` contains the DataSnapshot and a token that describes whether the notification is UPDATE/DELETE.

The SyncObserver just emits values everytime `onChild..` is called.

**Comment by argzdev** [comment]
Hi @zoltish, thanks for reporting. You mentioned that the memory grows when you sign it. Do you mean when signing in using Firebase Auth? As it happens, there's a memory leak issue in Firebase Auth #2387. This might've something to do with that. 

A fix is currently on its way, however, it is still in BoM testing and the release process can take some time.

**Comment by zoltish** [comment]
Hey @argzdev! It seems that would affect the memory usage just by using `AuthStateListener`? I do use it, but it doesnt bother the app unless youre explicitly signed in. Does that make sense? Which version of the bom could I opt to rely on until the fix is out?

**Comment by argzdev** [comment]
Thanks for the update, @zoltish. Unfortunately, the leak can exist even without using AuthStateListener. I've encountered a similar case in #3236. Can you confirm that the issue of memory usage only grows when the user is signed in? Or when using Firebase Auth?

I'm assuming this memory leak issue might be due to Auth.
The fix is already on the way, however, I'm unable to provide a timeline when this could be released.

According to one of our engineers.
> The only way we know for sure to fix this right now would be to rewrite a very large section of our library to not use that internal library (which may not fix the issue, but at least would make it easier to debug). We don't really have the resources right now to do that, so we're trying to see if we can figure out how to fix it without having to rewrite everything.

As a result, the testing phase will take a long time before it can be released.

As for the app stuttering, it may be possibly due to the memory leak but I can't say for sure. You could probably try to test your app without Firebase Auth and see if the app still stutters.

**Comment by zoltish** [comment]
@argzdev Just signing in or being signed in does not affect memory usage, pretty much at all (<1 mb). 

If Im signed in and add a `ChildEventListener` to a small reference (~300 entries) the memory usage is still pretty much unaffected (<2 mb), **but** if I add the same type of listener to a large reference (~2000 entries) the memory usage grows a lot (~60 mb). I just tested this to verify and those are the exact numbers Im seeing. 

It doesnt sound like the same issue as the auth leak? Im practically using AuthStateListener regardless if the user is signed in, and memory usage is stellar up to the point when I add the listener to the large reference. 

The app stuttering is pretty much exactly linked to its high memory usage, e.g. if the user isnt signed in at all, the app is super-smooth, if youre signed in, you can notice stutters (especially in animations); and even if you sign out in the same session the memory usage will remain high until the app is effectively restarted. Before signing in, memory usage sits at 57 mb, after close + swipe away from recents, its back at exactly 57 mb.

Fwiw, the ChildEventListeners are exactly identical for all my references. The data stored there is different though, Ill link them below in case it helps; data complexity is way higher for the large references, I dont know if that makes any difference?

```
~300 entries: 
(ExerciseWrapper)
    val id: String,
    val name: String,
    val instructions: String?,
    val muscles: List<MuscleType>,
    val equipment: EquipmentType,
    val category: Category,
    val status: Status,
    val version: Long

~2000 entries:
(WorkoutWrapper)
    val id: String,
    val name: String?,
    val description: String?,
    val movements: List<MovementWrapper>,
    val version: Long

(MovementWrapper):
    val id: String,
    val exerciseId: String,
    val groupId: String?,
    val trainingMax: WeightWrapper?,
    val note: String?,
    val plans: List<PlanWrapper>

(PlanWrapper)
    val id: String,
    val rpe: Int?,
    val maxPercent: Float?,
    val rest: Long?,
    val distance: DistanceWrapper?,
    val duration: Long?,
    val calories: Int?,
    val repetitionRange: RepetitionRangeWrapper?,
    val mark: Mark?
```

**Comment by argzdev** [comment]
Hi @zoltish, our engineer have confirmed that this is working as intended. 
>Currently, all data is being kept in memory until the listener is removed. 

With that said, you might need to change your implementation for this use case to avoid increase in memory usage, however I don't have an advice on what's the best approach for this.

**Comment by zoltish** [comment]
Thanks for checking @argzdev, it helps knowing that this is intentional - Ill see what I can do on my end of things to reduce the query size. 

Im rather curious about how the memory usage can grow so much by 4000 entities, e.g. even if things are kept in memory intentionally, isnt 60 mb a bit too much for such a query? 

Obviously I dont know the internals of firebase, the only thing Im comparing with is how much work Id have to do to acheive a 60 mb usage myself. Ive tried using boundless caches that practically hold all the data in my app in memory at all times, including their json structures - still almost nothing (this is probably not a fair comparison as I dont understand the internals of firebase, but still - 60 mb _is_ a lot). 

Do what you will with this information, Ill look into reducing query sizes regardless - hopefully it helps!

**Comment by argzdev** [comment]
Hi @zoltish, I understand your pain point, that is a valid reasoning. 60 mb is indeed huge for these types of queries. 

What I can do is raise this as a concern with our engineers, so they can discuss this further. However, since this is currently working as intended, the change won't be anytime soon. 

I'll post comment back here, once I get an update. Thanks!

**Comment by argzdev** [comment]
Hi @zoltish, I've consulted with our engineers regarding this.

> The memory usage in the (Android) SDK really depends on the data structure, not just the size of it. For example if the 300 child nodes are each a single string, that's quite different then when the 2,000 child nodes are all a bunch of boolean/numeric properties. We don't have any docs clarifying how the memory usage changes between the formats, but in general: more complex data structures will use more memory.

Given that this is the case, there isn't any plan of changing this in the future since this may require a huge change in how RTDB works. That being said, thank you for bringing this up, maybe this can be revisited in the future, but for now, I'll close this case.

**Comment by zoltish** [comment]
Hi @argzdev! 

Thanks for the update; fitting as I was just experimenting further in an attempt to reduce the query size, and in turn hopefully the memory overhead as well.. 

Im seeing some (seemingly) strange results though. Even if I use something like `reference.limitToLast(20)`, effectively taking the query result-set down to 20 from 2000, the memory overhead is exactly the same. 

This sort of brings me to the conclusion that none of the query methods actually have an impact on memory usage, the same data is potentially kept in memory - but the data I see in my app just differs to match the query filters. 

Is this also intended? If it is, I dont see any other way to reduce the memory consumption (beyond changing the data structure, of course).

**Comment by zoltish** [comment]
Ive started seeing quite a few OOM errors as a result of the above. As I mentioned in my last comment, using queries didnt have any effect - and these OOM errors are happening while using queries even (_limitToLast_). I also follow the best practices and have flattened "tables" similar to those that are included in the samples. 

Honestly not sure what else I should try at this point; the only pattern I can see on my end of things is that the crashes are exclusively happening on Android 12 devices. 

```
         java.lang.RuntimeException: Firebase Database encountered an OutOfMemoryError. You may need to reduce the amount of data you are syncing to the client (e.g. by using queries or syncing a deeper path). See https://firebase.google.com/docs/database/ios/structure-data#best_practices_for_data_structure and https://firebase.google.com/docs/database/android/retrieve-data#filtering_data
                 	at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7839)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                 Caused by: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 1312280 free bytes and 1281KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC.
                 	at java.util.HashMap.resize(HashMap.java:703)
                 	at java.util.HashMap.putVal(HashMap.java:662)
                 	at java.util.HashMap.put(HashMap.java:611)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJson(JsonMapper.java:125)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJson(JsonMapper.java:125)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJson(JsonMapper.java:125)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJson(JsonMapper.java:125)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJson(JsonMapper.java:125)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJson(JsonMapper.java:125)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJson(JsonMapper.java:125)
                 	at com.google.firebase.database.util.JsonMapper.unwrapJsonObject(JsonMapper.java:110)
                 	at com.google.firebase.database.util.JsonMapper.parseJson(JsonMapper.java:91)
                 	at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:256)
                 	at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:302)
                 	at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:34)
                 	at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:86)
                 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:920)

```

**Comment by argzdev** [comment]
Hi @zoltish, thanks for providing more information and sorry for the delayed response. 

It looks like there's a lot of details to discuss here, unfortunately I haven't gone through or tested these yet. For now, I'll reopen this issue and get back to you once I'm able to investigate the issues you've mentioned. In the meantime, if you could provide a minimal repro of this it'll help us out a lot and I can immediately notify an engineer about this.

**Comment by zoltish** [comment]
Hey @argzdev!

Im pretty sure that [this](https://github.com/firebase/firebase-android-sdk/issues/3503#issuecomment-1064158684);

> Hi @zoltish, thanks for clarifying with extra details. You're right, it looks like the issue isn't with Auth. I tried reproducing the issue by adding `ChildEventListener` to a reference of 4000 entries, and the memory usage also grew by ~60 mb. That being said, I'll try to notify our engineers to see what can be done here.

In combination with `reference.limitToLast(20)` will provide you with the exact same thing Im seeing - the memory usage will still grow by ~60 mb, even though youre now listening to 20 entries instead of 4000.

**Comment by argzdev** [comment]
Hi @zoltish,

I tried adding this to my query, but it only added around ~3 mb in memory usage. I have a dataset of 4000 workouts. Am I missing anything?

```
    fun getData(database: DatabaseReference){
        database.child("workout").limitToLast(20).get().addOnSuccessListener {
            Log.d(TAG, "getChild: ")
            var workout = (it.children.elementAt(Random().nextInt(it.childrenCount.toInt()))).getValue(Workout::class.java)
            Log.d(TAG, "getChild: ${workout?.id}")
        }
    }
```

**Comment by zoltish** [comment]
Hi again @argzdev! The only key difference is that Im adding a ChildEventListener, could you please try doing that instead of the `.get().addOnSuccessListener`?

**Comment by argzdev** [comment]
Hi @zoltish, thanks for the extra details. I was able to reproduce the same issue. It looks like there is a 30 ~ 40mb overhead when a ChildEventListener is added.

Using the profiler I tried testing with the following:
1. starting memory at 86.4, after adding listener it increased to 116.3 (limitToLast 20) ~30 mb overhead
2. starting memory at 70.4, after adding listener it increased to 109.4 (no limit) ~30 mb overhead
3. starting memory at 73, after adding listener it increased to 108 mb (limitToLast 10) ~30 mb overhead
4. starting memory at 74.4, after adding listener it increased to 110.5 mb (limitToLast 1) ~30 mb overhead

Relevant code:
```
fun addChildEventListener(database: DatabaseReference){
        Log.d(TAG, "addChildEventListener: ")
        childEventListener = object : ChildEventListener {
            override fun onChildAdded(snapshot: DataSnapshot, previousChildName: String?) {
                Log.d(TAG, "onChildAdded:" + snapshot.key!!)
            }

            override fun onChildChanged(snapshot: DataSnapshot, previousChildName: String?) {
                Log.d(TAG, "onChildChanged: ${snapshot.key}")
            }

            override fun onChildRemoved(snapshot: DataSnapshot) {
                Log.d(TAG, "onChildRemoved:" + snapshot.key!!)
            }

            override fun onChildMoved(snapshot: DataSnapshot, previousChildName: String?) {
                Log.d(TAG, "onChildMoved:" + snapshot.key!!)
            }

            override fun onCancelled(error: DatabaseError) {
                Log.w(TAG, "postComments:onCancelled", error.toException())
            }
        }
//        database.child("workout").limitToLast(1).addChildEventListener(childEventListener)
        database.child("workout").addChildEventListener(childEventListener)
        Log.d(TAG, "addChildEventListener: ")
```

I'll try to consult with an engineer and see what can be done here.

**Comment by zoltish** [comment]
Thank you for checking, @argzdev. Im glad were seeing the same thing at least, even if its a bad bad thing. Please keep me posted on the progress! This issue absolutely destroys my use-case to the point that its almost unusable, but I do love firebase and Id really like to be able to continue using it!

**Comment by argzdev** [comment]
Hi @zoltish, sorry for the delayed response. One of our engineers have investigated this and have found the issue.

1. The listener is being added to `/workout` and not `/workout/workout`. So the limit is being applied in the wrong place: it always needs to be applied at the path right above the auto-id list (`/workouts/workouts/<auto-id>/<item>`). 

2. The rtdb server doesn't filter un-indexed locations on the server side. Even if you do 
```
Firebase.database.reference.child("workout/workout").limitToLast(1).addChildEventListener(childEventListener)
```
RTDB is going to send all 4000 items at `/workout/workout`. In order to get your expected server-side filtering behavior, you need to add an index via rules:
```
{
  "rules": {
      ".read": true,
      ".write": true,
    "workout": {
      "workout": {
        ".indexOn": "id"
      }
    }
  }
}
```
And then use: 
```
Firebase.database.reference.child("workout/workout").orderByChild("id").limitToLast(1).addChildEventListener(childEventListener)
```

I hope this helps with your issue. Let me know if this works for you!

**Comment by zoltish** [comment]
Hey @argzdev! Thanks for getting back to me :) 

I dont understand what you mean by /workout/workout. Could you please elaborate? 

My data is structured like; `/workouts/<userId>/<workoutId>/<item>`. Im guessing that Im doing something wrong seeings how the memory usage is unaffected by limit, but Im seeing the expected behavior when using it - I receive the last N workouts rather than all of them. And for clarity, Im adding the limit and listener to `/workouts/<userId>`.

Ill add indexes and test things out as well. I never noticed this in the documentation, is it in there? If not, Im sure others will find it useful too!

**Comment by argzdev** [comment]
Hi @zoltish. You can ignore that step. This was due to the structure of my minimal repro I submitted to the engineering team to investigate this issue. Probably, the important take away from number 1 is that the listener always needs to be applied at the path right above the auto-id list.

Upon checking, the indexes is actually within the documentations, however this is placed under [Security & Rules](https://firebase.google.com/docs/database/security/indexing-data), so I understand why this is being overlooked.

Other than that, let me know if the indexes works for you.

**Comment by zoltish** [comment]
Gotcha, @argzdev! Ill focus my efforts on the indexing then :) I totally missed that in the docs, good to know that its there. Ill get back to you when Ive tried the indexes, it will likely take a few days as Im in the middle of some tech challenges!

**Comment by zoltish** [comment]
After adding `.indexOn`, I can see that the memory consumption drops by ~150 mb. For sanity I also tried removing the `indexOn` afterwards, and can immediately see that the memory consumption increases by the same amount it was lowered by previously.

I still need some more time to experiment with this, as it changes how I interact with the database, but Ill close this issue for now and report back if anything else comes up. 

**Im very very thankful for all your help. Thank you!**

**Comment by argzdev** [comment]
Awesome @zoltish, I'm glad that helped.
