### ISSUE TITLE
google-services:4.3.10 breaks on Dolphin Canary 5

### ISSUE THREAD

**Issue by sjmueller** [firebase/firebase-android-sdk#3517]
Using  `com.google.gms:google-services:4.3.10` results in this compile time error on Android Studio Dolphin Canary 5 using gradle 7.4.1:

![image](https://user-images.githubusercontent.com/29085/157608285-a1d005bf-02be-48d7-9987-8c8184c8bac7.png)

Reverting back to `com.google.gms:google-services:4.3.8` allows the project to build successfully.

**Comment by argzdev** [comment]
Thanks for reporting, @sjmueller. I was able to reproduce the issue, I'll notify our engineers to see what we can do here.

**Comment by argzdev** [comment]
Hi @sjmueller, it looks like the issue isn't exactly with our Firebase SDK. Could you open a new issue in https://github.com/google/play-services-plugins? That being said, I'll be closing this now. Thanks!
