### ISSUE TITLE
Android 12 Firebase Messaging Crash

### ISSUE THREAD

**Issue by jklitzke** [firebase/firebase-android-sdk#3523]
* Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 2
  * Firebase Component: Messaging
  * Component version: 23.0.0

Following up on issue originally [reported here](https://github.com/firebase/firebase-android-sdk/issues/3115) where latest firebase messaging library available causing app crashes due to android 12 changes. We are experiencing the exact same issue and although the defect was fixed I am not able to locate a newer version of the firebase messaging SDK which should(?) include the bug fix described. 

When I check the [Google Maven Repo firebase messaging](https://maven.google.com/web/index.html?q=firebase-messag#com.google.firebase:firebase-messaging:23.0.0) is still at 23.0. Has this fix been published for general use yet? Please advice.

Thanks

#### Steps to reproduce:

See original issue above.

Set `compileSdkVersion` to `31` in build.gradle file
Use latest firebase messaging library available (23.0.0)
Try to send a push notification/message to a device w/registered FCM token.

Expected result would be user receives push but actual result is push does not appear and app seems to crash in background

**Comment by argzdev** [comment]
Hi @jklitzke, thanks for reporting. I've recently confirmed with the engineer that the fix was released in version 21.1.0 (see #3423 for details). Can you confirm if the developer is experiencing the issue on FCM version 23.0.0? If this is the case, the issue might be due to something else. Could you provide error logs so we can investigate this further? Thanks!

**Comment by jklitzke** [comment]
Thanks for confirming.  I did some more checking around and found an internal issue that was causing similar behavior for my app and we were able to fix it. So the issue was something on our end but we got a bit confused w/the timing of how that the android 12 changes were deployed in the [other ticket](https://github.com/firebase/firebase-android-sdk/issues/3115). Thanks for your time.
