### ISSUE TITLE
[cloud_firestore] Snapshot lost all attributes data after offline updates

### ISSUE THREAD

**Issue by lukber** [firebase/firebase-android-sdk#3528]
* Android Studio version: 2020.3.1. Patch 3
  * Firebase Component: Firestore
  * Component version: firebase-bom:29.2.0

### Describe the problem

When is Android client offline and I add a new document to firestore and then I call update data on this document then snapshot contain only updated attribute.

#### Steps to reproduce:

1. My phone is in flight mode
2. I register the snapshots listener
3. I create new _movie_ document. DocumentSnapshot.getData() contain all document data (Snapshot: {name=Star wars (episode 1), likes=0}, ID: X07AxnfSg6bU2lAx5MAP)
4. I update _movie_ document. DocumentSnapshot.getData() contain only likes value (Snapshot: {likes=1}, ID: 07AxnfSg6bU2lAx5MAP). I would expect it to contain the entire document therefore Snapshot: {name=Star wars (episode 1), likes=1}, ID:  07AxnfSg6bU2lAx5MAP 

#### Create new document

```
Map<String, Object> user = new HashMap<>();
user.put("name", "Star wars (episode " + (episode++) + ")");
user.put("likes", 0);

// Add a new document with a generated ID

db.collection("movies")
	.add(user)
	.addOnSuccessListener(documentReference -> Log.d(TAG, "Movie added with ID: " + documentReference.getId()))
	.addOnFailureListener(e -> Log.w(TAG, "Error adding movie", e));
```

#### Snapshot listener

```
db.collection("movies")
.addSnapshotListener((snapshots, e) -> {
	if (e != null) {
		Log.w(TAG, "listen:error", e);
		return;
	}

	for (DocumentSnapshot dc : snapshots.getDocuments()) {
		Log.d(TAG, "Snapshot: " + dc.getData() + ", ID: " + dc.getId());
	}
});
```

#### Update document

```
db.collection("movies")
	.document(documentId)
	.update("likes", lastLikes++);
```

#### Log

```
Create new document
2022-03-14 10:27:46.712 24467-24467/cz.datasys.firebaseissue D/Firebase: Snapshot: {name=Star wars (episode 1), likes=0}, ID: X07AxnfSg6bU2lAx5MAP

After update
2022-03-14 10:28:11.426 24467-24467/cz.datasys.firebaseissue D/Firebase: Snapshot: {likes=1}, ID: X07AxnfSg6bU2lAx5MAP
```

**Comment by dconeybe** [comment]
@lukber I'll take a look into this.

**Comment by lukber** [comment]
I create logcat output with debug logging. Snapshot data has _APP_LOG_ tag.
[logcat_output.txt](https://github.com/firebase/firebase-android-sdk/files/8250759/logcat_output.txt)

**Comment by lukber** [comment]
[https://github.com/lukber/FirebaseIssue](Here) is a test application. You must put google-services.json yourself.

1. Start app with no internet connection
2. Click to _ADD NEW MOVIE_ button. It is important to try this on document witch isn't synchronized with server.
3. Click to movie list item to update likes. First update is OK. Second update is fail (movie name = null).

**Comment by dconeybe** [comment]
Thank you for the reproduction app. I've been able to reproduce and there is indeed a bug in Firestore. I still have to investigate further, but for now a workaround would be to downgrade `com.google.firebase:firebase-bom` to 29.0.3 or lower. This bug appears to have been introduced in 29.0.4.
