### ISSUE TITLE
AppCheck Custom Token refreshed in infinite loop

### ISSUE THREAD

**Issue by TomBAMU** [firebase/firebase-android-sdk#3561]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Chipmunk Beta 4
  * Firebase Component: Firebase AppCheck (Beta)
  * Component version:16.0.0-beta04

### [REQUIRED] Step 3: Describe the problem
We have implemented a cloud function with a custom appcheck token provider in NodeJS. This JWT token we are exposing our android devices. The JWT token produces a claim with seconds value. The firebase android sdk retrieves the expiration time from the token itself and interprets it as milliseconds. The SDK now thinks the token already expired
#### Steps to reproduce:
1. Implement a custom token provider with NodeJS or generate a  JWT token with seconds in the claim "exp" and "iat" in seconds. 
2.  Return this token in your AppCheckProvider wtth the signature  `fun getToken(): Task<AppCheckToken>` and add a log statement
3.  Register the AppCheckProviderFactory
4. Start app and observe the log - it will contain many lines of the log statement of step2 since the sdk thinks the token is expired and the token needs to  be refreshed

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
My analysis of the refresh mechanism leads to the following Insight. The problem is actually the function `public void maybeScheduleTokenRefresh(@NonNull AppCheckToken token)` in TokenRefreshManager. It ignores the getExpireTimeMillis() in the AppCheckToken and calls instead `public static DefaultAppCheckToken constructFromRawToken(@NonNull String token)`
```
class MyAppCheckToken(
    private val token: String,
    private val expiration: Long
) : AppCheckToken() {
    override fun getToken(): String {
        return token
    }

    override fun getExpireTimeMillis(): Long {
        return expiration
    }
}

class MyCheckProvider(private val firebaseApp: FirebaseApp) : AppCheckProvider {
    override fun getToken(): Task<AppCheckToken> {
        val taskCompletionSource = TaskCompletionSource<AppCheckToken>()
        /
        try {
            // call to myService to get token from NodeJS Cloudfunction via Admin SDK
            val token = getJwtFromNodeJsAdminSdk()
            // Log Statement
            Timber.d("token recieved")
            taskCompletionSource.setResult(token)
        } catch (e: IOException) {
            taskCompletionSource.setException(e)
        }
        return taskCompletionSource.task
    }
}

class MyAppCheckProviderFactory private constructor() : AppCheckProviderFactory {
    @NonNull
    override fun create(@NonNull firebaseApp: FirebaseApp): AppCheckProvider {
        return MyAppCheckProvider(firebaseApp)
    }

    companion object {
        private var INSTANCE: MyAppCheckProviderFactory? = null
        val instance: MyAppCheckProviderFactory?
            @JvmStatic
            @NonNull
            get() {
                if (INSTANCE == null) {
                    INSTANCE = MyAppCheckProviderFactory()
                }
                return INSTANCE
            }
    }
}

```

**Comment by TomBAMU** [comment]
Additional Information - The JWT Specification actually states that the claims exp are in seconds, as far as I understand the following information

> NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [[POSIX.1](https://www.rfc-editor.org/rfc/rfc7519#ref-POSIX.1)] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339)
      [[RFC3339](https://www.rfc-editor.org/rfc/rfc3339)] for details regarding date/times in general and UTC in
      particular.

https://www.rfc-editor.org/rfc/rfc7519#section-2
This means the assumption in the function "constructFromRawToken()" in DefaultAppCheckToken is not valid.
```
 @NonNull
  public static DefaultAppCheckToken constructFromRawToken(@NonNull String token) {
    checkNotNull(token);
    Map<String, Object> claimsMap = TokenParser.parseTokenClaims(token);
    long iat = getLongFromClaimsSafely(claimsMap, ISSUED_AT_KEY);
    long exp = getLongFromClaimsSafely(claimsMap, EXPIRATION_TIME_KEY);
    long expiresInMillis = exp - iat;
    // We use iat for receivedAtTimestamp as an approximation since we have to guess for raw JWTs
    // that we recovered from storage
    return new DefaultAppCheckToken(token, expiresInMillis, iat);
  }
```
should be in understanding somehow like this
```
 @NonNull
  public static DefaultAppCheckToken constructFromRawToken(@NonNull String token) {
    checkNotNull(token);
    Map<String, Object> claimsMap = TokenParser.parseTokenClaims(token);
    long iat = getLongFromClaimsSafely(claimsMap, ISSUED_AT_KEY);
    long exp = getLongFromClaimsSafely(claimsMap, EXPIRATION_TIME_KEY);
    long expiresInSeconds = exp - iat;
    long expiresInMillis = expiresInSeconds * 1000;
    // We use iat for receivedAtTimestamp as an approximation since we have to guess for raw JWTs
    // that we recovered from storage
    return new DefaultAppCheckToken(token, expiresInMillis, iat);
  }
```

**Comment by argzdev** [comment]
Hi @TomBAMU, thanks for the detailed report. We'll try to investigate this, in the meantime, if you could provide us with an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), it'll greatly speed up our investigation. Thanks!

**Comment by argzdev** [comment]
Hi @TomBAMU, thanks for reporting, we'll investigate this. In the meantime, if you could provide us a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of the issue, it'll greatly help us in our investigation. Thanks!

**Comment by TomBAMU** [comment]
Hi @argzdev. Thank you for your reply. I would like to provide MCVE, however, I can't offer you a backend producing a JWT Token though. Would it be sufficient for you to fill a placeholder with a valid JWT Token or do you have any other ideas?

**Comment by argzdev** [comment]
Hi @TomBAMU, I was able to repro the issue, and I can confirm that with the code snippet you've provided this, it fixes the issue.

Thanks for the PR, @rosalyntan.

**Comment by argzdev** [comment]
Hi @TomBAMU, the target release date would around early to mid April 2022

**Comment by TomBAMU** [comment]
@argzdev thank you for your reply.
There is a new release with 16.0.0-beta05 for appcheck. But it seems this fix is not in there. I'm sorry for bothering you with this question, though is there a changelog or something equivalent to see what changes a release contains?

**Comment by argzdev** [comment]
@TomBAMU, no worries! Usually when there's a release that fixes some GitHub issues, it would contain a description and link to that issue. You can check this [Cloud Firestore release](https://firebase.google.com/support/release-notes/android#firestore_v24-1-0) as an example where an issue is linked to the release notes.
