### ISSUE TITLE
157239010: Firebase dynamic link issue related to google play service cache

### ISSUE THREAD

**Issue by bravono3** [firebase/firebase-android-sdk#357]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: __3.3.1___
  * Firebase Component: Firebase Dynamic link
  * Component version: 16.1.7

### [REQUIRED] Step 3: Describe the problem
I want to implement data transfer between apps using Firebase dynamic linking.
It usually works normally.
But sometimes the sender changed the parameter value, but the recipient received the previous parameter value.
In this case, I removed the Google Play services cache from my device. After that, I could see that it worked again.
#

For example:

**1. Sender**

          String url = "https://nyr9b.app.goo.gl/?efr=1&ius=example&apn=com.example.com&ibi=com.example.com&isi=12345656&link=";
                String link = "https://www.example.com/?sc=aaabb&no=12345&text=abce";

                try {
                    url += URLEncoder.encode(link, "utf-8");
                } catch (UnsupportedEncodingException e) {
                    e.printStackTrace();
                }

                Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
                startActivity(intent);

**2. Receiver**

 
     FirebaseDynamicLinks.getInstance()
                .getDynamicLink(getIntent())
                .addOnSuccessListener(this, new OnSuccessListener<PendingDynamicLinkData>(){
                    @Override
                    public void onSuccess(PendingDynamicLinkData pendingDynamicLinkData) {
                        // Get deep link from result (may be null if no link is found)
                        Uri deepLink = null;
                        if (pendingDynamicLinkData != null) {
                            deepLink = pendingDynamicLinkData.getLink();

                            //For Tphone
                            if(deepLink.toString().contains("aaabb"){

                                String tDynamicLink ="";
                                try {
                                    tDynamicLink = URLDecoder.decode((deepLink.toString()).replaceAll("#%","%23%25"),"UTF-8");
                                } catch (IllegalArgumentException e){
                                    tDynamicLink = deepLink.toString();
                                } catch (UnsupportedEncodingException e) {
                                    tDynamicLink = deepLink.toString();
                                }

 
                                Uri url = Uri.parse(tDynamicLink);
                                String no = url.getQueryParameter("no");
                               String text = url.getQueryParameter("text").replaceAll("[^0-9|a-z|A-Z|ㄱ-ㅎ|가-힣ㅏ-ㅣ]", "");

                })
                .addOnFailureListener(this, new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.w(TAG, "getDynamicLink:onFailure", e);
                    }
                });

**Comment by shangxinbo** [comment]
I got the same thing.  And i catch the redirect like this:
intent://deeplink.startimes.me/PVDE#Intent;package=com.google.android.gms;action=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK;scheme=https;S.browser_fallback_url=http://qa.upms.startimestv.com/hybrid/account/deeplink%3Fvcode%3D029KQKS1&signature%3DQtL5pEdcgz/pM4ouxamkHr3hOjb/ca46bl4JTmBeNMtm8WEsqtUlbuteoQXY%2BrS/o54q/k4ziEmwE37g/so8QF2SfbO3c9A8qtESUABYS9ZuB7BTtGs0oN2l4Zsqsr7Az34HS3k3nh2W0mqpxJA0G2pjyO/v4m/AGKhYY1Npu1w%253D;end;

I think the dynamiclinks will be solved in com.google.android.gms first and then fallback to the reallinks, why ?

**Comment by ornolisvt** [comment]
I have the same issue. I'm testing with an app published on internal test. The app installed from Play Store don´t handle the link when install first time

**Comment by CristianMG** [comment]
We have the same issue it does not work the first time. We are waiting for updates
