### ISSUE TITLE
Numeric Transforms are not included in Firestore KTX

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/firebase-android-sdk#360]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.3.0
  * Firebase Component: Firestore
  * Component version: 18.2.0

### [REQUIRED] Step 3: Describe the problem
After replacing the `firebase-firestore` depedency with `firebase-firestore-ktx` on my `build.gradle` file, I noticed the class `com.google.firebase.firestore.FieldValue` is missing its `increment()` method (the other methods are there, so I'm sure I'm calling the public class and not the one under the `model` package). 

I understand this might be happening because the ktx gradle distribution started before the numeric transforms distribution (although the commit history shows otherwise) but it would be nice to have this fixed ASAP.

#### Steps to reproduce:

Simply replace the `firebase-firestore` depedency with `firebase-firestore-ktx` and try to call `FieldValue.increment()`.

#### Relevant Code:

If it helps, here's what I'm trying:
```kotlin
FirebaseFirestore.getInstance().collection("users").document(uid).update("views", FieldValue.increment(1))
```

**Comment by schmidt-sebastian** [comment]
@rosariopfernandes Thanks for letting us know about this and sorry for your troubles! The current release of `firebase-firestore-ktx` depends on an outdated version of Firestore. I will see if we can publish a new version.

**Comment by rosariopfernandes** [comment]
Thanks for your reply @schmidt-sebastian 

I'm closing this since a new version of the firestore sdk (19.0.0) has been released.
