### ISSUE TITLE
FCM doesn't receive notifications when I swiped app from Recent Apps

### ISSUE THREAD

**Issue by gmyrzamuratov** [firebase/firebase-android-sdk#3601]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 2
  * Firebase Component: Cloud Messaging
  * Component version: 23.0.2

### [REQUIRED] Step 3: Describe the problem
Hi, Firebase Cloud Messaging doesn't receive notification when I swiping my app from Recent Apps in Xiaomi Redmi 4
Android version: 6.0.1

#### Steps to reproduce:
Case #1
1. I launched app
2. I took my FCM token
3. Sent notification from Firebase console to this token
4. I received notification

Case #2
1. I launched app
2. I clicked back button, to close app
3. I sent notification from Firebase console to this token again
4. I received notification again

Case #3
1. I swiped app from Recent Apps tray
2. I sent notification from Firebase console to this token again
3. I didn't receive notification
4. After some time I launched app again
5. Only after this I received notification again

#### Relevant Code:

**This is my App Gradle:**
`plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 31

    defaultConfig {
        applicationId "gm.Kazakh_Olenderi"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 265
        versionName "18.0.07"
        multiDexEnabled true
    }
    buildTypes {

        release {
            //minifyEnabled true
            //shrinkResources true
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            zipAlignEnabled true
            lintOptions {
                disable 'MissingTranslation'
            }
        }

    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    buildToolsVersion = '30.0.3'
}
repositories {
    mavenCentral()
    //maven { url "https://artifact.bytedance.com/repository/pangle" }
    //maven { url "https://android-sdk.is.com" }
    //maven { url "https://sdk.tapjoy.com/" }
    google()
    jcenter()
}
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    testImplementation 'junit:junit:4.12'
    implementation 'androidx.multidex:multidex:2.0.1'
    //implementation 'com.google.android.gms:play-services-analytics:16.0.8'
    // Firebase
    implementation platform('com.google.firebase:firebase-bom:29.3.0')

    //implementation 'com.google.firebase:firebase-crash'
    implementation 'com.google.firebase:firebase-core'
    implementation 'com.google.firebase:firebase-appindexing'
    implementation 'com.google.firebase:firebase-messaging:23.0.2'
    implementation 'com.google.firebase:firebase-dynamic-links'
    implementation 'com.google.firebase:firebase-analytics'
    // Firebase

    implementation 'com.facebook.android:facebook-login:5.15.3'
    implementation 'com.github.bumptech.glide:glide:4.10.0'
    implementation files('libs/commons-io-2.4.jar')
    implementation files('libs/nineoldandroids-2.4.0.jar')
    implementation 'com.google.android.gms:play-services-auth:19.0.0'
    implementation 'androidx.browser:browser:1.3.0'
    implementation 'androidx.vectordrawable:vectordrawable-animated:1.1.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.media:media:1.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.aurelhubert:ahbottomnavigation:2.2.0'
    implementation 'com.vk:androidsdk:1.6.7'
    implementation 'com.miguelcatalan:materialsearchview:1.4.0'
    implementation 'com.squareup.okhttp3:okhttp:3.12.2'

    implementation 'com.google.android.exoplayer:exoplayer-core:2.9.2'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.9.2'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.2'

    // adfox
    //implementation ('com.yandex.android:mobileads:4.4.0') {
    //    exclude group: 'com.google.android.exoplayer', module:'exoplayer-core'
    //}
    //implementation 'com.yandex.android:mobmetricalib:3.20.1'

    //implementation 'com.yandex.ads.mediation:mobileads-unityads:1.5.0'
    //implementation 'com.yandex.ads.mediation:mobileads-mytarget:1.13.0'

    // adfox

    // admob
    implementation 'com.google.android.gms:play-services-ads:20.6.0'
    // admob

    // admob mediation
    implementation 'com.unity3d.ads:unity-ads:4.0.1'
    implementation 'com.google.ads.mediation:unity:4.0.1.0'
    // admob mediation

    //implementation 'com.unity3d.ads:unity-ads:3.6.0'
    //implementation 'com.my.target:mytarget-sdk:5.12.3'

    implementation 'dnsjava:dnsjava:2.1.9'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    implementation 'info.androidhive:fontawesome:0.0.5'

    implementation "com.android.billingclient:billing:4.0.0"
}

apply plugin: 'com.google.gms.google-services'`

This is my project Gradle:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**This is my Project AndroidManifest.xml:**
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="gm.Kazakh_Olenderi"
    android:installLocation="auto"
    android:versionCode="34"
    android:versionName="3.9">
    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="28"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:name=".GoogleAnalyticsApp"
        android:networkSecurityConfig="@xml/network_security_config"
        >
        <activity android:name=".ui.activity.Splash"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity
            android:name=".ui.activity.MyActivity"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:theme="@style/AppTheme.NoActionBar"
            android:exported="true">
            <intent-filter>
                <data android:mimeType="application/mp3"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data
                    android:host="sazalem.com"
                    android:scheme="https"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data
                    android:host="sazalem.page.link"
                    android:scheme="https"/>
            </intent-filter>
        </activity>
        <activity android:name=".ui.activity.activity_singers_songs_list"
            android:configChanges="keyboardHidden|orientation|screenSize">
        </activity>
        <activity android:name=".ui.activity.activity_playlist_songs"
            android:configChanges="keyboardHidden|orientation|screenSize">
        </activity>
        <activity android:name=".ui.activity.activity_playlist_details"
            android:configChanges="keyboardHidden|orientation|screenSize">
        </activity>
        <activity android:name=".ui.activity.activity_download_page"
            android:configChanges="keyboardHidden|orientation|screenSize">
        </activity>
        <activity android:name=".ui.activity.activity_song_page"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </activity>
        <activity android:name=".ui.activity.activity_new_player"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </activity>
        <activity android:name=".ui.activity.activity_billing">
        </activity>
        <activity android:name=".ui.activity.activity_new_songs">
        </activity>
        <activity android:name=".ui.activity.activity_genre_new_songs">
        </activity>
        <activity android:name=".ui.activity.activity_edit_song_page">
        </activity>
        <activity android:name=".ui.activity.activity_news">
        </activity>
        <activity android:name=".ui.activity.activity_news_page">
        </activity>
        <activity android:name=".ui.dialog.LoginDialog">
        </activity>
        <activity android:name=".ui.activity.activity_search"
            android:theme="@style/AppTheme.NoActionBar">
        </activity>

        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-7813891820290008~9437502574"/>
        

        
        <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
        
        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        <meta-data android:name="com.google.android.gms.analytics.globalConfigResource"
            android:resource="@xml/global_tracker" />
        
        
        
        
        <service android:name=".services.MusicService"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
                <action android:name="android.media.AUDIO_BECOMING_NOISY" />
                <action android:name="android.media.browse.MediaBrowserService" />
            </intent-filter>
        </service>
        <service android:name=".services.HLSDownloadService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.exoplayer.downloadService.action.INIT"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
        </service>
        <service android:name="com.google.android.exoplayer2.scheduler.PlatformScheduler$PlatformSchedulerService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="true"/>
        
        <service
            android:name=".fcm.MyFirebaseMessagingService"
            android:stopWithTask="true"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        

        <activity android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>
        <receiver android:name="androidx.media.session.MediaButtonReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
                <action android:name="android.media.AUDIO_BECOMING_NOISY" />
            </intent-filter>
        </receiver>

        
        
    </application>
</manifest>`

**This is my FCM service:**
`package gm.Kazakh_Olenderi.fcm;

import android.accounts.Account;
import android.accounts.AccountManager;
import android.annotation.SuppressLint;
import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.media.RingtoneManager;
import android.os.AsyncTask;
import android.os.Build;
import androidx.core.app.NotificationCompat;

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import gm.Kazakh_Olenderi.R;
import gm.Kazakh_Olenderi.api.api_function;
import gm.Kazakh_Olenderi.api.authorization_module;
import gm.Kazakh_Olenderi.ui.activity.MyActivity;
import gm.Kazakh_Olenderi.util.Constants;

public class MyFirebaseMessagingService extends FirebaseMessagingService {

   public static final String PROPERTY_REG_ID = "registration_id";
   private static final String PROPERTY_APP_VERSION = "appVersion";

   @Override
   public void onMessageReceived(RemoteMessage remoteMessage) {
      super.onMessageReceived(remoteMessage);
      // TODO(developer): Handle FCM messages here.
      // If the application is in the foreground handle both data and notification messages here.
      // Also if you intend on generating your own notifications as a result of a received FCM
      // message, here is where that should be initiated. See sendNotification method below.
      RemoteMessage.Notification notification = remoteMessage.getNotification();

      if (remoteMessage.getData().size() > 0) {
         Map<String, String> data = remoteMessage.getData();
         sendNotification(notification, data);
      }

   }

   @Override
   public void onNewToken(String token) {

      // If you want to send messages to this application instance or
      // manage this apps subscriptions on the server side, send the
      // Instance ID token to your app server.
      RegistrationInBackground(token);
      storeRegistrationId(this, token);
   }

   @SuppressLint("WrongConstant")
   private void sendNotification(RemoteMessage.Notification notification, Map<String, String> data) {

      Bitmap icon = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);

      Intent intent = new Intent(this, MyActivity.class);
      intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

      String SongTitle  = "";
      String SongAuthor = "";
      NotificationCompat.Builder notificationBuilder = null;
      if (data.containsKey("song")) {
         String jsonArray = data.get("song");
         try {

            JSONObject json = new JSONObject(jsonArray);

            SongTitle = json.getString("song_title");
            SongAuthor = json.getString("song_author");

         } catch (JSONException e1) {
            e1.printStackTrace();
         }

         String push_msg = SongAuthor + "-" + SongTitle;

         intent.putExtra("message", jsonArray);
         PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, intent, PendingIntent.FLAG_CANCEL_CURRENT);

         notificationBuilder = new NotificationCompat.Builder(this, Constants.channelForNotification)
                 .setContentTitle(getResources().getString(R.string.push_title))
                 .setContentText(push_msg)
                 .setAutoCancel(true)
                 .setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
                 .setContentIntent(pendingIntent)
                 .setContentInfo(getResources().getString(R.string.push_title))
                 .setLargeIcon(icon)
                 .setColor(Color.RED)
                 .setLights(Color.RED, 1000, 300)
                 .setDefaults(Notification.DEFAULT_VIBRATE)
                 .setSmallIcon(R.mipmap.ic_launcher);
      } else {

         PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, intent, PendingIntent.FLAG_ONE_SHOT);

         notificationBuilder = new NotificationCompat.Builder(this, Constants.channelForNotification)
                 .setContentTitle(notification.getTitle())
                 .setContentText(notification.getBody())
                 .setAutoCancel(true)
                 .setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
                 .setContentIntent(pendingIntent)
                 .setContentInfo(notification.getTitle())
                 .setLargeIcon(icon)
                 .setColor(Color.RED)
                 .setLights(Color.RED, 1000, 300)
                 .setDefaults(Notification.DEFAULT_VIBRATE)
                 .setSmallIcon(R.mipmap.ic_launcher);

         try {
            String picture_url = data.get("picture_url");
            if (picture_url != null && !"".equals(picture_url)) {
               URL url = new URL(picture_url);
               Bitmap bigPicture = BitmapFactory.decodeStream(url.openConnection().getInputStream());
               notificationBuilder.setStyle(
                       new NotificationCompat.BigPictureStyle().bigPicture(bigPicture).setSummaryText(notification.getBody())
               );
            }
         } catch (IOException e) {
            e.printStackTrace();
         }

      }

      NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

      // Notification Channel is required for Android O and above
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
         NotificationChannel channel = new NotificationChannel(
                 "channel_id", "channel_name", NotificationManager.IMPORTANCE_DEFAULT
         );
         channel.setDescription("channel description");
         channel.setShowBadge(true);
         channel.canShowBadge();
         channel.enableLights(true);
         channel.setLightColor(Color.RED);
         channel.enableVibration(true);
         channel.setVibrationPattern(new long[]{100, 200, 300, 400, 500});
         notificationManager.createNotificationChannel(channel);
      }

      notificationManager.notify(2, notificationBuilder.build());
   }

   public void RegistrationInBackground(String Token) {

      new sendRegistrationToServer().execute(Token);

   }

   private static int getAppVersion(Context context) {
      try {
         PackageInfo packageInfo = context.getPackageManager()
                 .getPackageInfo(context.getPackageName(), 0);
         return packageInfo.versionCode;
      } catch (PackageManager.NameNotFoundException e) {
         // should never happen
         throw new RuntimeException("Could not get package name: " + e);
      }
   }

   private void storeRegistrationId(Context context, String regId) {

      //final SharedPreferences prefs = getGCMPreferences(context);
      //int appVersion = getAppVersion(context);
      //SharedPreferences.Editor editor = prefs.edit();
      //editor.putString(PROPERTY_REG_ID, regId);
      //editor.putInt(PROPERTY_APP_VERSION, appVersion);
      //editor.commit();

      authorization_module amd = new authorization_module();
      amd.setFCM_ID(regId, context);

   }

   // ---------------------------------------------------------------------------------------------
   // SendRegIdToServer()
   //
   //
   public class sendRegistrationToServer extends AsyncTask<String, Void, JSONArray> {

      @Override
      protected JSONArray doInBackground(String... params) {

         try {

            //String gmail_user_email = getUserParam();
            //String[] parts = gmail_user_email.split("@");

            //String gmail_user_name = "-";
            //if (parts.length > 1) {
            //    gmail_user_name = parts[0];
            //}

            String FCM_ID = params[0];
            String urlParameters = //"name=" + URLEncoder.encode(gmail_user_name, "UTF-8") +
                    //"&email=" + URLEncoder.encode(gmail_user_email, "UTF-8") +
                    "regid=" + URLEncoder.encode(FCM_ID, "UTF-8") +
                            "&country=1&type=fcm&app_version="+getAppVersion(getApplicationContext());

            String api = "https://sazalem.com/register";

            api_function af = new api_function();
            String resultString = af.request(api, urlParameters);

            System.out.print("FCM TOKEN - <" + FCM_ID + ">");
            System.out.print("Result");
            System.out.print(resultString);

            // parsing data
            return new JSONArray();

         } catch (Exception e) {
            e.printStackTrace();
            return null;
         }

      }

      @Override
      protected void onPostExecute(JSONArray result) {

         String str = "";

      }

   } // SendRegIdToServer()

}`

I tried data and notifications, I didn't receive both messages

**Comment by argzdev** [comment]
Closing due to stale. Feel free to reopen once you can provide more details, thanks!
