### ISSUE TITLE
[messaging] Please publicly expose the functionality of DisplayNotification.java

### ISSUE THREAD

**Issue by sfuqua** [firebase/firebase-android-sdk#3610]
## What feature would you like to see?

This class, DisplayNotification:
https://github.com/firebase/firebase-android-sdk/blob/6ee7bdf1bff4c9054204e2230d5ded9050274481/firebase-messaging/src/main/java/com/google/firebase/messaging/DisplayNotification.java#L45

is responsible for the "automagical" behavior of Android Firebase Cloud Messaging, wherein the SDK will automatically display an Android notification if a message is received while the app is _in the background_.

This automatic behavior is [a point of contention](https://github.com/firebase/firebase-android-sdk/issues/2639) in the developer community since there is no current way to customize or [opt-out](https://github.com/firebase/firebase-android-sdk/pull/3492) of the display notification, but as long as the SDK is opinionated about doing this, I would like a way to _mimic_ the SDK's behavior while the app is foregrounded.

So I would appreciate it if a public variant of `DisplayNotification` could be exposed by the SDK, ideally taking a `RemoteMessage` instance in a constructor, that would allow me to generate and display an Android Notification _in the same style as created by the SDK_.

This would allow consistent presentation by an app regardless of whether the message is received in the foreground or background.

## How would you use it?

Today, if I specify "image" in my FCM payload, the SDK will automatically download and display the image in a Notification using `BigPictureStyle`, which is convenient - but it only does this when the app is backgrounded.

When the app is foregrounded I have to recreate this Notification myself, manually, and for consistency I find myself basically copying the same styling the SDK uses. It'd be great if the SDK just exposed its helpers to me so I could literally display the same Notification that it automatically creates. This also applies to the logic the SDK uses for icons, strings, etc.

**Comment by sfuqua** [comment]
Possible duplicate of https://github.com/firebase/firebase-android-sdk/issues/1663

**Comment by argzdev** [comment]
Hi @sfuqua, thanks for the request! 

To avoid duplicates of feature requests, I'll be closing this now. However, what I did was add a comment to issue 1663, so that this can be visible to whomever is checking the request.

That being said, can you give the issue 1663 a thumbs up? This is so that we can track the requests of our developers, and prioritize accordingly. Thanks again!
