### ISSUE TITLE
FirebaseMessaging is using "src/main/proto" for encoding its big query analytics payload, while only "json" and "proto" are supported

### ISSUE THREAD

**Issue by hnljp** [firebase/firebase-android-sdk#3628]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: wu.seal.tool.jsontokotlin (3.7.2), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.6.20-release-275-AS7442.40), org.intellij.plugins.markdown (211.7142.37)
  * Firebase Component: Messaging ( com.google.firebase:firebase-messaging )
  * Component version: 23.0.2

### [REQUIRED] Step 3: Describe the problem

Receiving this warning, when receiving a notificiation (data notification in this case):

`2022-04-08 06:52:40.327 31221-17504/? W/FirebaseMessaging: Failed to send big query analytics payload.
    java.lang.IllegalArgumentException: Encoding{name="src/main/proto"} is not supported byt this factory. Supported encodings are: [Encoding{name="json"}, Encoding{name="proto"}].
        at p4.p.a(TransportFactoryImpl.java:4)
        at com.google.firebase.messaging.MessagingAnalytics.logToFirelog(MessagingAnalytics.java:5)
        at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(MessagingAnalytics.java:6)
        at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:8)
        at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:3)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:6)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0(EnhancedIntentService.java:1)
        at com.google.firebase.messaging.EnhancedIntentService.b(Unknown Source:0)
        at com.google.firebase.messaging.b.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at b8.a.run(com.google.android.gms:play-services-basement@@18.0.0:2)
        at java.lang.Thread.run(Thread.java:920)`

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Thanks for reporting, @hnljp. I'm unable to reproduce this using our [quickstart project](https://github.com/firebase/quickstart-android). Could you answer a few questions below:
1. What Android version did you experience this issue?
2. Are you able to reproduce this issue? Is it consistently reproducible? 
3. Was the app in the background, foreground, or closed when the notification was clicked?

Any chance you could provide a minimal repro of this issue? It'll help us a lot in our investigation. Thanks!

**Comment by hnljp** [comment]
1. I see this on both Pixel 5 with Android 12 (S3B1.220218.004) and Pixel 5 with Android 12 (S3B1.220318.003)
2. Happens every time when receiving a notification (I have both tried with data notifications and now also using the firebase console)
3. I have just tried and it happening every time I receive a notification, no matter if it is in the background running or not or if it is in the foreground.

I will try to see if I can find the time later this weekend.
One thing that could make a difference, is that we always add a custom data payload to the notifications.

Source of the unsupported argument ("src/main/proto") : https://github.com/firebase/firebase-android-sdk/blob/26c905be56b14cb5dee745cd446020db2451e0b4/firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java#L344

Source of the "byt" spelling mistake:
https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportFactoryImpl.java#L52

Most likely the source of "proto" and "json"
https://github.com/firebase/firebase-android-sdk/blob/26c905be56b14cb5dee745cd446020db2451e0b4/transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CCTDestination.java#L43

Again, this is just a warning, but as it is telling that it is not sending the analytics data, so I guess this could be important.

**Comment by argzdev** [comment]
Thanks for the detailed analysis, @hnljp. I'm still unable to reproduce this issue, however I've notified an engineer to see what we can do here. I'll wait for the minimal repro too, thanks!

**Comment by thatfiredev** [comment]
I believe this has been address in #3636 ?
But I'll wait for someone from the engineering team to confirm once it gets released.

**Comment by hnljp** [comment]
> I believe this has been address in #3636 ? But I'll wait for someone from the engineering team to confirm once it gets released.

Looking good. And as it has already been merged, am I closing it now.
