### ISSUE TITLE
Usage of raw query 

### ISSUE THREAD

**Issue by gstephin** [firebase/firebase-android-sdk#3666]
We have used firebase in our android project and everything is working fine. But when I had to submit my .apk for VAPT(Pen Testing), I had to face a critical issue that was raised because of the use of rawQuery. On further analysis I came to know that it could be the code from the SchemaManager class line 159 as shown here https://github.com/firebase/firebase-android-sdk/blob/master/transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java. The VAPT team is not going forward with closing the issues unless until this issue is solved. Is there anything I can do about it so that the issue is resolved?

**Comment by argzdev** [comment]
Hi @gstephin, thanks for reporting. 

In this case, unfortunately, we can only ask our engineers to investigate this if there is an actual vulnerability impact since this may require further discussions. If you could provide more details why this is a "critical" issue, then I can probably justify an engineer’s time to dig into it with that much evidence. 

Also just to ask, would your tooling flag `execSql()` as an issue as well?

**Comment by gstephin** [comment]
Hi @argzdev, Thanks for reaching out. The app is yet to publish and we are doing a penetration testing for the application and the testing team reported this issue regarding the code quality. Their comment is - "One of the most common vulnerabilities in both web applications and mobile applications are the injection-based vulnerabilities. SQLite also suffers from an injection vulnerability if the input given by the user is used as it is or with little but insuffic ient protection in a dynamic SQL query. The rawQuery method will, in fact, simply execute whatever SQL query is passed to it. " . Can you please confirm if this issue will cause any threat to the app ?. The tooling flag didn't flag  execSql()  as an issue.

**Comment by argzdev** [comment]
Thanks for explaining, @gstephin. Currently, `db.rawQuery` is only being used internally for tests, PRAGMA, and a few SELECT statements for storing events in Analytics. All `db.rawQuery` used do not accept inputs in anyway or form from external sources e.g. user inputs. We can be sure that this will not cause any vulnerabilities to your app. 

However, if this is unsatisfactory, what you can do is clone a copy of the repository, search for all the usage of `db.rawQuery`, check which ones you think may have SQL injection vulnerability potential. Then we can further discuss what can be done on those statements. (There are around 23 instances of the rawQuery including tests and excluding comments).

**Comment by argzdev** [comment]
Hi, since this question has been answered, I'll be closing this issue now. Thanks!

**Comment by gstephin** [comment]
@argzdev Sorry for the delay. You can close this issue.
