### ISSUE TITLE
Automatic monitoring of HTTP/S network requests from Firebase Performance is flooding Firebase Crashlytics

### ISSUE THREAD

**Issue by ppamorim** [firebase/firebase-android-sdk#3679]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1
  * Firebase Component: Crashlytics & Performance
  * Component version: crashlytics-ktx:17.3.1 & perf-ktx:19.1.1

### [REQUIRED] Step 3: Describe the problem

Our Firebase Crashlytics is getting flooded with non-fatal error reports of users trying to use our app without internet connection. This should not be reported at all, our user base is well known for having very unstable internet connection and our application already ignores this exception from the system. Firebase Performance for OkHttp seems to not ignore that.

The exception present is:

```
Non-fatal Exception: java.net.UnknownHostException
Unable to resolve host "$https_address_here": No address associated with hostname
```

#### Steps to reproduce:

 - Create an app with Firebase Crashlytics + Firebase Performance and OkHttp 3.x. 
 - Turn off the internet of your device and try to do Http requests.

What happened? How can we make the problem occur?

 - You should start receiving the same exception from the screenshot below. To reproduce do what is described on the last step above.

Note the line `com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute (FirebasePerfOkHttpClient.java:43)`

![Screenshot 2022-04-26 at 12 16 42](https://user-images.githubusercontent.com/5521682/165289117-5e39a282-831b-4ad4-a38b-50e127ee16bc.png)

**Comment by argzdev** [comment]
Since this is currently stale, I'll be closing this now. Feel free to reopen once there are new details that can be provided.
