### ISSUE TITLE
Add an IsRunningInTestLab method to detect if app is running in test lab/Google Play pre-launch test environment

### ISSUE THREAD

**Issue by mikequ-taggysoft** [firebase/firebase-android-sdk#3690]
## What feature would you like to see?

I believe the React Native Firebase SDK has an `.isRunningInTestLab` method that can be used to detect if the app is running in a test lab or Google Play Console pre-launch test env.

I can't seem to find an equivalent in the Xamarin SDK. It would be great if such a helper method can be made available.

## How would you use it?

It can be quite handy to have this check available so that we can filter out some unnecessary/unwanted actions that can be triggered in these test environments.

**Comment by argzdev** [comment]
Hi @mikequ-taggysoft, thanks for reporting. However, this is the Firebase Android repository. Afaik we don't have an officially supported open source Firebase Xamarin SDK. That being said, I'll be closing this issue now. Thanks!

**Comment by mikequ-taggysoft** [comment]
Sorry, accidentally posted in wrong repo.
