### ISSUE TITLE
flutter

### ISSUE THREAD

**Issue by robertspaculus** [firebase/firebase-android-sdk#3695]
Type mismatch: inferred type is Map<String, Int>? but Map<String, Int> was expected
FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 3s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

**Comment by argzdev** [comment]
Hi @robertspaculus, please file Flutter issues in their [repository](https://github.com/firebase/flutterfire/issues), so they can assist you better. That being said, I'll close this now. Thanks
