### ISSUE TITLE
Internal error in Cloud Firestore (24.0.1).

### ISSUE THREAD

**Issue by cxMax** [firebase/firebase-android-sdk#3702]
* blow is my dependencies. 

implementation 'com.google.firebase:firebase-bom:29.2.1'  

implementation 'com.google.firebase:firebase-analytics:19.0.0'  

implementation 'com.google.firebase:firebase-crashlytics:18.0.1'  

implementation 'com.google.firebase:firebase-firestore:24.0.1'

* java stack:

Fatal Exception: java.lang.RuntimeException
Internal error in Cloud Firestore (24.0.1).
com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3 (AsyncQueue.java:539)
com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$cG4e8FKiBI1uHuEBYC-bY9JR88Y.run (-.java:2)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:236)
android.app.ActivityThread.main (ActivityThread.java:8073)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:620)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1011)

Caused by com.google.android.gms.tasks.RuntimeExecutionException
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
com.google.android.gms.tasks.zzu.getResult (zzu.java:15)
com.google.firebase.firestore.remote.FirestoreChannel.lambda$runBidiStreamingRpc$0 (FirestoreChannel.java:115)
com.google.firebase.firestore.remote.-$$Lambda$FirestoreChannel$0Ae0OZVH5uV1moEedILJLfrbyWY.onComplete (-.java:6)
com.google.android.gms.tasks.zzj.run (zzj.java:4)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:462)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run (AsyncQueue.java:234)
java.lang.Thread.run (Thread.java:923)

Caused by io.grpc.ManagedChannelProvider$ProviderNotFoundException
No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
io.grpc.ManagedChannelProvider.provider (ManagedChannelProvider.java:43)
io.grpc.ManagedChannelBuilder.forTarget (ManagedChannelBuilder.java:76)
com.google.firebase.firestore.remote.GrpcCallProvider.initChannel (GrpcCallProvider.java:113)
com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6 (GrpcCallProvider.java:256)
com.google.firebase.firestore.remote.-$$Lambda$GrpcCallProvider$-4U_AcdJVCEeG6NOrpg3tM4Nfcc.call (-.java:2)
com.google.android.gms.tasks.zzv.run (zzv.java:2)
com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0 (ThrottledForwardingExecutor.java:54)
com.google.firebase.firestore.util.-$$Lambda$ThrottledForwardingExecutor$LidNF-W_9-SVM15Diteen_5-PO8.run (-.java:4)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)`

* how can i slove this problem ?
need help , thx

**Comment by cherylEnkidu** [comment]
Hi,
Thanks for reporting this. Could you please share with us the minimum code and steps to reproduce this issue?

**Comment by cxMax** [comment]
* I sampely use firestore as the tutorial guide say
* Whether need I initialize FireStore during application onCreate?
* below is my usage

FirebaseFirestore.getInstance()  
.collection("feedback")    
.document("RLISPq6dD1H53XRUsx0k")  
.collection(SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(System.currentTimeMillis()) + "_" + UUID.randomUUID())  
.add(mapOf("extra" to getExtraParams()))

**Comment by cxMax** [comment]
## summery
I track the code `FirebaseFirestore.getInstance().collection()`, then I found how this crash happend
## process
1. First Time, `FirebaseFirestore.ensureClientConfigured()` will create a new FirestoreClient Object
<img width="826" alt="image" src="https://user-images.githubusercontent.com/17964075/167250414-5a182ff7-408b-462c-a51e-7ac645ec6370.png">
2. `FirestoreClient.initialize(Context context, User user, FirebaseFirestoreSettings settings)` will create a new Datastore object
<img width="888" alt="image" src="https://user-images.githubusercontent.com/17964075/167250463-9085bfbf-0edf-445d-98f9-6f82e77ccf1d.png">
3. create a new FirestoreChannel object
<img width="867" alt="image" src="https://user-images.githubusercontent.com/17964075/167250520-72cdea81-d801-4946-b374-bf9718e8a271.png">
4. create a new GrpcCallProvider object
<img width="903" alt="image" src="https://user-images.githubusercontent.com/17964075/167250551-ca83b325-fbfa-4309-9cf8-764b25332215.png">
5. `GrpcCallProvider.initChannelTask()` -> `GrpcCallProvider#initChannel(Context context, DatabaseInfo databaseInfo)` -> ManagedChannelBuilder.forTarget(databaseInfo.getHost())
<img width="888" alt="image" src="https://user-images.githubusercontent.com/17964075/167250665-8ce890f0-4945-4dde-86d9-fabd82fc55d7.png">
6. `ManagedChannelProvider.provider().builderForTarget(target)` -> `ManagedChannelProvider.provider()`
<img width="704" alt="image" src="https://user-images.githubusercontent.com/17964075/167250722-9f8e602c-ba13-43b7-a9ae-ee79e5bdced9.png">
7. finally, the crash happen
<img width="877" alt="image" src="https://user-images.githubusercontent.com/17964075/167250745-c0085712-7a26-4aed-97cd-a729cf856f9e.png">

## question
what cause `ManagedChannelRegistry.getDefaultRegistry().provider()` get null?
Does it depends on the environment of the user's android mobile phone? such as Network environment?

**Comment by cxMax** [comment]
I seem to find out how it cause the crash, look at this
> https://github.com/grpc/grpc-java/issues/9152

I don't know whether it works, if it works, I'll be back and update the final conclusion

**Comment by RushitaBacancy** [comment]
Same issue I'm facing
<img width="1346" alt="Screenshot 2022-05-18 at 11 25 04 AM" src="https://user-images.githubusercontent.com/91242522/168967258-414db973-1385-4d33-a361-b8488037f3e9.png">
.

**Comment by argzdev** [comment]
Hi @RushitaBacancy, looking at your logs snippet you've provided, it seems like a different issue compared to @cxMax. That being said, could you file a new issue following our template? Also if possible please provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of your issue. It'll greatly help us alot. Thanks!
