### ISSUE TITLE
How to enable ANR collection to Crashlytics?

### ISSUE THREAD

**Issue by LazyBonesLZ** [firebase/firebase-android-sdk#3705]
Integrated Firebase Crashlytics SDK v18.2.9, collected the crash data correctly, but no ANR data .
Device info:
Samsung SM-P610, Android 12.

How to enable ANR collection to Crashlytics? Need some additional code?

**Comment by argzdev** [comment]
Hi @LazyBonesLZ, there's no need for any additional code to receive ANR from Crashlytics. However, there's a few thing to take note of:
1. ANR collection starts only on Crashlytics SDK version 18.2.4 (you're already doing this)
2. ANR collection only works for devices with Android version 11+. For ANRs from older Android versions, you may get check that from Google Play console Android vitals.

If you have further questions or issues on the implementation, feel free to reach out to our [Firebase Support](https://firebase.google.com/support). You may share your project configuration with them, and they'll be able to give you a more personalized help. That being said, I'll be closing this issue now. Thanks!
