### ISSUE TITLE
No signature of method: build_d2d0kup0ase29ffduk40eouuj.android()

### ISSUE THREAD

**Issue by venkatesh123-tec** [firebase/firebase-android-sdk#3733]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\user\Downloads\eFood_v7.2\eFood_v7.2\Efood Orugallufresh\android\app\build.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_d2d0kup0ase29ffduk40eouuj.android() is applicable for argument types: (build_d2d0kup0ase29ffduk40eouuj$_run_closure2) values: [buil
d_d2d0kup0ase29ffduk40eouuj$_run_closure2@1cf9c10f]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Running Gradle task 'assembleRelease'...                           41.7s
Gradle task assembleRelease failed with exit code 1

PS C:\Users\user\Downloads\eFood_v7.2\eFood_v7.2\Efood Orugallufresh> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.67.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
PS C:\Users\user\Downloads\eFood_v7.2\eFood_v7.2\Efood Orugallufresh>

**Comment by argzdev** [comment]
Hi @venkatesh123-tec, thanks for filing. I don't see any indicator that your issue is related to Firebase, also it looks like you're using Flutter. Could you file an issue to the [Flutter repo](https://github.com/flutter/flutter) or to [FlutterFire repo](https://github.com/firebase/flutterfire/issues) if you're having issues implementing Firebase. That being said, I'll close this issue now. Thanks!
