### ISSUE TITLE
Reauthenticating with wrong credentials creates a new user

### ISSUE THREAD

**Issue by linas77** [firebase/firebase-android-sdk#3755]
#### Environment
  * Android Studio version: Chipmunk 2021.2.1
  * Firebase Component: Authentication
  * Component version: 21.0.1

#### Steps to reproduce:

When using login providers to retrieve credentials for reauthentication, if the user reauthenticates with the wrong Facebook/Google account, the reauthentication fails, however a new account is created on the server with the wrong credentials.

#### Relevant Code:

For Facebook we pass the retrieved credentials to reauthenticate
```
    suspend fun reAuthenticateUser(credentials: AuthCredential) {
        firebaseAuth.currentUser!!.reauthenticate(credentials).await()
    }
```

For Google we let the function handle the reauthentication
```
    suspend fun reAuthenticateUserGoogle(activity: Activity) {
        val provider = OAuthProvider.newBuilder(AUTH_PROVIDER_GOOGLE)

        firebaseAuth.currentUser!!.startActivityForReauthenticateWithProvider(activity, provider.build()).await()
    }
```

**Comment by lisajian** [comment]
Hi, thanks for filing this issue! We are unable to promise any timeline for this, but if others also have this issue, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: [b/234154236](https://b.corp.google.com/issues/234154236))

**Comment by rosalyntan** [comment]
Hi @linas77, thanks for filing this issue!

At the present moment, this is the intended behavior -- reauthenticating essentially behaves the same as a sign-in, with an additional check on the client to verify that the user is the same as before.
