### ISSUE TITLE
Firebase performance events have not been reported to the dashboard

### ISSUE THREAD

**Issue by javaboboApp** [firebase/firebase-android-sdk#3786]
Hello I am using Firebase performance to report custom metrics and those are not appearing in the dashboard. 

I am installing an app using emulator and I have followed recommended steps on: 
https://firebase.google.com/docs/perf-mon/troubleshooting?platform=android 

to found and solve issues. 

I have activated logs and I can see: 

06-06 10:04:24.708  6392  6865 I FirebasePerformance: Logging network request trace: https://mobile-collector.newrelic.com/mobile/v3/data (responseCode: 200, responseTime: 165.536ms)
06-06 10:05:24.723  6392  6871 I FirebasePerformance: Logging network request trace: https://mobile-collector.newrelic.com/mobile/v3/data (responseCode: 200, responseTime: 179.016ms)

 But dashboard reminds  empty. 
 
I have troubles to test crashanalitycs too when events are being reported after a long time. 

Is there any way to speed up this reporting? So when we are testing, could see event's performance in real time?

**Comment by jposuna** [comment]
Hi @javaboboApp, we need some more information to help you, and some of it may contain PII that we wouldn't want to have publicly on this issue. To help you troubleshoot, can you contact Firebase support through https://firebase.google.com/support/troubleshooter/contact?

**Comment by javaboboApp** [comment]
Issue was in the library dependencies:

I was using **com.google.firebase:firebase-config** rather than **com.google.firebase:firebase-config-ktx** strange that I was not getting any error message in the logs.

**Comment by jposuna** [comment]
Thanks for the information - I'm glad you were able to resolve the issue.
