### ISSUE TITLE
unit test for `buildSrc` does not run [both on Linux and Windows].

### ISSUE THREAD

**Issue by ywmei-brt1** [firebase/firebase-android-sdk#3820]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.1.1 Patch3
  * Firebase Component: buildSrc
  * Component version: NA
  
#### Steps to reproduce:

What happened? How can we make the problem occur?
run the unit test for `buildSrc`, the build success, but the test is skipped.
Can not manually run the unit test neither. Will show `0 pass`.
See this PR: https://github.com/firebase/firebase-android-sdk/pull/3801#issuecomment-1158117475

#### Relevant Code:

```
ywmei@ywmei:~/Workspace/SDK/firebase-android-sdk/buildSrc$ ../gradlew test --scan
Starting a Gradle Daemon, 3 busy Daemons could not be reused, use --status for details
> Task :compileKotlin UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :pluginDescriptors UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestKotlin UP-TO-DATE
> Task :pluginUnderTestMetadata UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test SKIPPED

BUILD SUCCESSFUL in 8s
6 actionable tasks: 6 up-to-date
```

**Comment by rlazo** [comment]
Tests for plugins are disabled by default. See https://github.com/firebase/firebase-android-sdk/blob/master/buildSrc/build.gradle#L116
