### ISSUE TITLE
 firebase app check is not working in android OS 10 .its working fine in android OS 9 

### ISSUE THREAD

**Issue by Nabeelyousaf** [firebase/firebase-android-sdk#3821]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment
 Flutter 2.10.1

  * Android Studio version: ____9_
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
Describe the bug
I m trying to implement the Firebase app check-in flutter but its package is not helpfull for me i tried to implemet in native in app I follow the firebase app check documentation. its working fine in android OS 9. but I face issues in Android OS 10 the issue is related to Firebase

Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation

#### Steps to reproduce:
I follow the Firebase app check documentation

### Sample project
override fun onCreate(savedInstanceState: Bundle?) {
        FirebaseApp.initializeApp(/*context=*/this)
        val firebaseAppCheck = FirebaseAppCheck.getInstance()
//        DebugAppCheckProviderFactory.getInstance()
        firebaseAppCheck.installAppCheckProviderFactory(
                SafetyNetAppCheckProviderFactory.getInstance()
        )
        super.onCreate(savedInstanceState)
    }

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Thanks for reporting, @Nabeelyousaf. I'm unable to reproduce your issue. I tried using the sample code snippet provided in our [guide](https://firebase.google.com/docs/firestore/quickstart#add_data), and this seems to work both on Android versions 10, & 9. Here is my relevant code:

```
class CustomApplication : Application() {
    override fun onCreate() {
        val firebaseAppCheck = FirebaseAppCheck.getInstance()
        firebaseAppCheck.installAppCheckProviderFactory(
            SafetyNetAppCheckProviderFactory.getInstance()
        )
        super.onCreate()
    }
}

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val db = Firebase.firestore

        findViewById<Button>(R.id.btn_add).setOnClickListener {
            val user = hashMapOf(
                "first" to "Ada",
                "last" to "Lovelace",
                "born" to 1815
            )

            db.collection("users")
                .add(user)
                .addOnSuccessListener { documentReference ->
                    Log.d(TAG, "DocumentSnapshot added with ID: ${documentReference.id}")
                }
                .addOnFailureListener { e ->
                    Log.w(TAG, "Error adding document", e)
                }
        }
```

Have you added your CustomApplication in your manifest file? e.g. `android:name=".CustomApplication"`?
Can you provide more details so I can investigate this further?

**Comment by cvs85** [comment]
Hi, We have almost the same issue.

Firebase SMS authentication works fine in all os version, but once we upload in-store and is live, the SMS authentication stop working for 10-10+ os versions. We don't understand where is exactly the issue.

Any insight, or support is appreciated.

Thank you,

**Comment by argzdev** [comment]
Hi @cvs85, could you open a new issue with the details from our template? This is so we can gain the necessary details to help you better. Thanks!
