### ISSUE TITLE
Please add prefix on res/raw/keep.xml file

### ISSUE THREAD

**Issue by ganadist** [firebase/firebase-android-sdk#3836]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment
  * Android Studio version: Any
  * Firebase Component: firebase-common
  * Component version: 20.1.1

### [REQUIRED] Step 3: Describe the problem

After update firebase-common 20.1.1, app build was failed with following log.

```
> Task :app:packageDebugBundle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebugBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.PackageBundleTask$BundleToolWorkAction
   > Modules 'base' and 'feature1' contain entry 'res/raw/keep.xml' with different content.

```

My app has [dynamic feature modules](https://developer.android.com/guide/playcore/feature-delivery), and a 3rd party library which is included on a dynamic feature has also `res/raw/keep.xml` 

But firebase-common has [same resource name with different content](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-common/src/main/res/raw/keep.xml), and AGP cannot merge them.

It seems that the resource name does not have to be `keep.xml`,
https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-main/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/res/shrinker/usages/ToolsAttributeUsageRecorder.kt#51

But it is introduced as keep.xml in [the guideline documentation](https://developer.android.com/studio/build/shrink-code#keep-resources).
So, many library are providing their rules as `keep.xml` including `firebase-common`

To avoid merge conflict `keep.xml`, please rename it with prefix.

**Comment by argzdev** [comment]
Hi, @ganadist. Thank you for reporting and creating a pull request for this! I'll let our engineers know if there's changes needed to be done or if it's clear to merge.
