### ISSUE TITLE
dynamic_link_first_open not tracked anymore after bom:29.1.0

### ISSUE THREAD

**Issue by SteveBurkert** [firebase/firebase-android-sdk#3848]
### [READ] Step 1: Are you in the right place?

The event is part of the analytics sdk, so I guess.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Cipmunk 2021.2.1 Patch 1
  * Firebase Component: Analytics
  * Component version: 21.0.0 with bom: 30.1.0

#### Steps to reproduce:

We updated the bom from 29.1.0 to 30.1.0 and released a new version.
Since then we did not receive `dynamic_link_first_open` events anymore.

After downgrading the bom back to 29.1.0 for the next release,
the event is being tracked again.

#### Relevant Code:

There is not really relevant code, besides the deps. 

```
            platform     : 'com.google.firebase:firebase-bom:29.1.0', // Updated to 30.1.0
            analytics    : 'com.google.firebase:firebase-analytics',
            analytics_ktx: 'com.google.firebase:firebase-analytics-ktx',
``` 

Analytics before update: `20.1.0`
After update: `21.0.0`

As of doc: 

> The following Analytics events are automatically logged when you open a short or long Dynamic Link in your app.

We still get new users. We still use dynamic links a lot. But the event is missing.

**Comment by argzdev** [comment]
Good day @SteveBurkert, I've tried testing this with Firebase BoM versions `30.1.0` & `29.1.0`, which equates to com.google.firebase:firebase-analytics versions `21.0.0` & `20.1.0`, respectively. However, I'm able to receive the `dynamic_link_first_open` event properly in both tests. Could you provide a [minimal](https://stackoverflow.com/help/minimal-reproducible-example) repro of your issue? So we can investigate this further? Thanks!

**Comment by SteveBurkert** [comment]
> Good day @SteveBurkert, I've tried testing this with Firebase BoM versions `30.1.0` & `29.1.0`, which equates to com.google.firebase:firebase-analytics versions `21.0.0` & `20.1.0`, respectively. However, I'm able to receive the `dynamic_link_first_open` event properly in both tests. Could you provide a [minimal](https://stackoverflow.com/help/minimal-reproducible-example) repro of your issue? So we can investigate this further? Thanks!

I will, I just need some time. Currently we are facing multiple problems with firebase. Of which tracking is less important. 
I need to create some minimal repos for them, too. Next to my usual tasks. But I will add a small repo in the near future.

**Comment by argzdev** [comment]
Sure thing, @SteveBurkert. I'll wait for the repro. Thanks!

**Comment by SteveBurkert** [comment]
Hey! Sorry for the late response.
So I created a minimal repo and tried to reproduce the issue.
For whatever reason I had a hard time to get `bla` even on the old bom. 

`First Open` events are tracked, but not `dynamic_link_first_open`. Instead `dynamic_link_app_open` is being tracked.

Since this is an example repo, I did not push the app to PlayStore and was not able to test the flow with 
a dynamic link leading to an install. Instead I installed the apk, without launching it.
Then opening the dynamic link and watched the verbose FA log.

repo: [firebase-dynamic-link-issue-example](https://github.com/SteveBurkert/firebase-dynamic-link-issue-example)

![Screenshot from 2022-07-26 17-23-51](https://user-images.githubusercontent.com/5735305/181048762-3d793c6f-3a9d-4ea2-b384-ffc1c85505a1.png)

**Comment by argzdev** [comment]
Hi @SteveBurkert, thanks for the minimal repro. I was able to receive the `dynamic_link_first_open` parameter with the repo. The only change I did was use my own dynamic link which I created via Firebase Console, and changed my app package name so I can upload this to Play Store.

What you can do to test the flow is by uploading the app to Play Store internal testing.
1. Create app in Play Store, upload through internal testing (Testing > Internal testing)
2. Allow anyone to download you shared the link with  (Setup > Internal app sharing > Manage Testers)
3. Create a tester mailing list (Testing > Internal testing > Testers)
4. Allow testers to join (Testing > Internal testing > Testers > How testers join your test > Copy link then follow steps)
5. Once all the setup is complete, you should be able to open your app from your generated dynamic link.
6. The logcat will be able to detect the logs coming from your app. E.g. `2022-07-28 18:51:13.670 11480-6906/? V/FA-SVC: Logging event: origin=fdl,name=dynamic_link_first_open,params=Bundle[{medium=dynamic_link, dynamic_link_accept_time=1659005464405, source=firebase, campaign=youtube, ga_event_origin(_o)=fdl, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=1035661436052574254, dynamic_link_link_name=youtube, dynamic_link_link_id=https://issue3842.page.link/3848}]`

Upon investigating, it looks like if you simply install the apk without opening it, the `dynamic_link_first_open` won't trigger even if you open the app at a latter time. The correct process should be that your app needs to be downloaded from the Play Store and then the "open" button is clicked in order for to receive `dynamic_link_first_open`.
