### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by kabeer-uber** [firebase/firebase-android-sdk#3864]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: **Any**
  * Firebase Component: firebase-ml-modeldownloader
  * Component version: 24.0.2

#### Steps to reproduce:
Note this is an edge case the requirement to hit this edge case are as below:

Be in the process of migrating from [FirebaseModelManager](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/common/modeldownload/FirebaseModelManager) (old version) to [FirebaseModelDownloader](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader) (open source).

Why because they store the same model in the exact same destination. Path (/data/user/0/\<app package name\>/no_backup/com.google.firebase.ml.custom.models/\<firebase persistent key\>/\<model name\>) verified by checking the file paths via both the downloaders. But they store model details in different locations, i.e details in the SharedPreferences cache are in different namespaces. (Open source firebase model downloader stores it in [com.google.firebase.ml.modelDownloader](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java#L40)  and likely old FirebaseModelManager stores it here com.google.firebase.ml.common.modeldownload) 

Two models need to be triggered for download at the same time (It leads to partial information present in the SharedPreferences cache) and with the larger model already downloaded on the device. Smaller model download = faster download time relative to larger model download.

Why because when the smaller model completes downloading and the larger model is in progress when we look to [clean up files](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L65) post smaller model download, we find the [larger model folder](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L70) but do not find the larger model file path in the [SharedPreferences cache ](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L74)(although the file is on the device). Thus we get an [empty file path](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L215) for the larger model resulting in the below stack trace.

```
java.lang.NumberFormatException: For input string: ""
java.lang.Integer.parseInt(Integer.java:627)
java.lang.Integer.parseInt(Integer.java:650)
com.google.firebase.ml.modeldownloader.internal.ModelFileManager.deleteOldModels(ModelFileManager.java:222)
com.google.firebase.ml.modeldownloader.internal.ModelFileManager.deleteNonLatestCustomModels(ModelFileManager.java:82)
com.google.firebase.ml.modeldownloader.internal.ModelFileDownloadService.maybeCleanUpOldModels(ModelFileDownloadService.java:463)
com.google.firebase.ml.modeldownloader.internal.ModelFileDownloadService.loadNewlyDownloadedModelFile(ModelFileDownloadService.java:436)
com.google.firebase.ml.modeldownloader.FirebaseModelDownloader.finishModelDownload(FirebaseModelDownloader.java:432)
com.google.firebase.ml.modeldownloader.FirebaseModelDownloader.lambda$getCustomModelTask$2$FirebaseModelDownloader(FirebaseModelDownloader.java:361)
com.google.firebase.ml.modeldownloader.-$$Lambda$FirebaseModelDownloader$GcaMffATH6wSK_VJ7z2TtucDhnk.then(Unknown Source:6)
com.google.android.gms.tasks.zzg.run(com.google.android.gms:play-services-tasks@@17.0.2:2)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:920) 

```

We would not see this issue:

- If we had simultaneous downloads and the larger model was not already present on the device (via [FirebaseModelManager](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/common/modeldownload/FirebaseModelManager) (old version)), we would not try to iterate through the [larger model folder](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L70), and thus not try to fetch details about this model from the [SharedPreferences cache](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L74).
- If we had sequential downloads, we would fill up our preferences cache sequentially, and with complete information one at a time. Even if we triggered smaller model download first although we would still iterate through the [larger model folder](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L70) we would not find any information in the [SharedPreferences cache](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L74) (instead of partial information that we find in simultaneous downloads). Thus leading to model = null condition as shown [here](https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java#L75) and avoid the crash.

#### Relevant Code:

```
val remotedModel = FirebaseCustomRemoteModel.Builder(largeModelName).build();

//note this is a different version of model downloader the ones below, it is firebaseModelManager
firebaseModelManager
        .download(remoteModel, conditions)
        .addSuccessListener{}
        .addFailureListener{}
        
//restart app and simultaneously trigger
firebaseModelDownloader
                  .getModel(largeModelName, DownloadType.LOCAL_MODEL, conditions)
                  .addSuccessListener{}
                  .addFailureListener{}

firebaseModelDownloader
                  .getModel(smallerModelName, DownloadType.LOCAL_MODEL, conditions)
                  .addSuccessListener{}
                  .addFailureListener{}

//The smallerModelName will result in a failure with the above stack trace.
```

**Comment by argzdev** [comment]
Hi @kabeer-uber, thanks for reporting and creating a pull request! I'll let our engineers check and see if it's clear to merge or if changes have to be made.
