### ISSUE TITLE
Firebase Auth Web - Google sign in - not presenting pick account dialog on android

### ISSUE THREAD

**Issue by dvird** [firebase/firebase-android-sdk#3884]
Hi when im using firebase auth and with google sign in, im not getting this dialog as the picture.

When im going to google.com from the browser and click sign in so im getting this dialog.

is it possible to make firebase auth to present it as well?
![WhatsApp Image 2022-07-10 at 11 21 05 AM](https://user-images.githubusercontent.com/42498461/178151117-7841f678-9f17-4ae2-b1a1-e54e95c10391.jpeg)

**Comment by argzdev** [comment]
Hey @dvird, thanks for reporting. What dialog or pop up are you receiving when logging in via google sign in? Is it similar to the one below? 
<img width="377" alt="Screen Shot 2022-07-12 at 5 51 48 PM" src="https://user-images.githubusercontent.com/93124282/178463638-a42ff8ec-640c-4920-a31b-b1d7b1d9d728.png">

This is the default behavior for the login. However, this may differ based on the android version of your device.

**Comment by argzdev** [comment]
Thanks for clarifying, @dvird. For web issues, could you file an issue on our [JS repo](https://github.com/firebase/firebase-js-sdk/issues/) instead? They'll be able to assist you better. 

That being said, I'll close this issue now. Thanks!
