### ISSUE TITLE
FirebaseMessaging getToken() api callback is not working.

### ISSUE THREAD

**Issue by CyborgRahil** [firebase/firebase-android-sdk#3897]
### Describe your environment

  * Android Studio version: Android studio Chipmunk
  * Firebase Component: FCM
  * Component version: Firebase BOM version - 29.3.1

###  Describe the problem
Migrating getToken() api from firebase-iid to firebase-messaging because firebase-iid is deprecated. 
Once we call getToken() of firebase messaging we are not get any callback from firebase library inside OnCompleteListener()/onSuccessListener().

We face this issue in integration build where we are using Dexguard on debug build it is working fine.

**Did not observe this token or callback issue with firebase instance IID on integration build.**

**Dexguard version:**  9.1.12

Added keep rules with FirebaseMessage api but nothing works:

```
-keep class com.google.firebase.** { *; }
-keep interface com.google.firebase.** { *; }
-keepresourcexmlelements manifest/application/**
```
Did not observe any crash/ANR.

#### Steps to reproduce:
Not working in integration build :(

#### Relevant Code:
```
FirebaseMessaging.getInstance().token.addOnCompleteListener(OnCompleteListener { task ->
    if (!task.isSuccessful) {
        Log.w(TAG, "Fetching FCM registration token failed", task.exception)
        return@OnCompleteListener
    }

    // Get new FCM registration token
    val token = task.result

    // Log and toast
    val msg = getString(R.string.msg_token_fmt, token)
    Log.d(TAG, msg)
    Toast.makeText(baseContext, msg, Toast.LENGTH_SHORT).show()
})
```

**Comment by argzdev** [comment]
Thanks for reporting, @CyborgRahil. I'm also unable to reproduce this in the debug build. Can you provide stack trace of the error in your integration build? Maybe that will provide clues for us to investigate.

**Comment by argzdev** [comment]
I think this issue might be related to #3898, in which retrieving of token fails for Android 12+. Could you confirm if this is the case for you, @CyborgRahil?

**Comment by CyborgRahil** [comment]
@argzdev 
No our case is different we can reproduce this on API level 30 as well. We did not observe any crash, issue is app did not get any callback from firebase sdk inside OnCompleteListener()/onSuccessListener(). There is no any stack-trace.

**Comment by argzdev** [comment]
Correct me if I'm wrong, I'm guessing that the integration test is being run on an emulator? It would seem that the retrieving of token fails when being run on emulators or devices with API 30 that does not have Google APIs. However, this works normal on a physical device. Perhaps there's a way for you to run this on an emulator with Google Play Store or Google APIs.

Could you provide more details what are you using for your integration build? Perhaps I can simulate this on my end.

**Comment by CyborgRahil** [comment]
Hi @argzdev,
Is there any update on this tracker?

**Comment by argzdev** [comment]
Hi @CyborgRahil, sorry for the delayed response. 

We're still investigating this. We'll get back to you here once we have updates. Thanks!

**Comment by gsakakihara** [comment]
Since this works without Dexguard but doesn't when using Dexguard, it appears likely this is a Dexguard issue and not an FCM one. Unfortunately Firebase doesn't support Dexguard, so there's not much we can do about that. Dexguard may be removing or obfuscating some classes that the SDK needs to function, so you could look into that and see if there is a way to prevent it.
