### ISSUE TITLE
AppCheck can not activate DebugAppCheckProviderFactory in Android 6 API 

### ISSUE THREAD

**Issue by manakuro** [firebase/firebase-android-sdk#3916]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: `2021.2.1 Patch1`
  * Firebase Component: `AppCheck` (Database, Firestore, Storage, Functions, etc)
  * Component version: `16.0.0` with bom `30.1.0`

### [REQUIRED] Step 3: Describe the problem
The AppCheck activate throws an error when enabling DebugAppCheckProviderFactory in Android 6 API like so.

```
java.lang.IllegalAccessException: Class java.lang.Class<io.invertase.firebase.appcheck.ReactNativeFirebaseAppCheckModule> cannot access  method void com.google.firebase.appcheck.debug.DebugAppCheckProviderFactory.<init>(java.lang.String) of class java.lang.Class<com.google.firebase.appcheck.debug.DebugAppCheckProviderFactory>
```

This happens when using `DebugAppCheckProviderFactory`  in `react-native-firebase`
https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java#L59-L74

Android 12 is working fine, but Android 7 and Android 8 do not seem to be working as well.

Is there a minimum supported version when using the SDK?

#### Steps to reproduce:
Enable `DebugAppCheckProviderFactory` in Android6.

#### Relevant Code:

```.java
          FirebaseAppCheck firebaseAppCheck = FirebaseAppCheck.getInstance();
          
          Class<DebugAppCheckProviderFactory> debugACFactoryClass =
              DebugAppCheckProviderFactory.class;

          // Get the (undocumented) constructor accepting a debug token as string
          Class<?>[] argType = {String.class};
          Constructor c = debugACFactoryClass.getDeclaredConstructor(argType);

          // Create a object containing the constructor arguments
          // and initialize a new instance.
          Object[] cArgs = {BuildConfig.FIREBASE_APP_CHECK_DEBUG_TOKEN};
          firebaseAppCheck.installAppCheckProviderFactory(
              (AppCheckProviderFactory) c.newInstance(cArgs));
```

#### Relevant issue:
https://github.com/invertase/react-native-firebase/issues/6384

**Comment by argzdev** [comment]
Thanks for reporting, @manakuro. I was able to reproduce the same behavior. I'll notify our engineers and see what we can do here. Thanks!

**Comment by rosalyntan** [comment]
Hi @manakuro, thanks for reporting this issue!

This is working as intended; the [`DebugAppCheckProviderFactory` constructor](https://github.com/firebase/firebase-android-sdk/blob/381bf87833cec3456e5bce75506b8e88a5657481/appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/DebugAppCheckProviderFactory.java#L36-L43) that accepts a `String` is package-private, and not intended to be called outside our `firebase-appcheck-debug-testing` SDK.

Please see our [docs](https://firebase.google.com/docs/app-check/android/debug-provider#emulator) for the intended usage of `DebugAppCheckProvider` in Android.

**Comment by manakuro** [comment]
Thanks for investigating it!  @rosalyntan 

I appreciate your suggestion, but is there any way to configure DebugAppCheckProvider with `APP_CHECK_DEBUG_TOKEN_FROM_CI` to inject a debug token? In the docs, it is intended to be used only for unit testing, but in some cases, I want to be able to use the same debug token and test it with devices or emulators, instead of registering it in the [Manage debug tokens](https://firebase.google.com/docs/app-check/android/debug-provider#emulator) every time.

In iOS, it can be accomplished by simply setting a debug token to `FIRAAppCheckDebugToken`.
https://firebase.google.com/docs/app-check/ios/debug-provider#ci

**Comment by rosalyntan** [comment]
Hi @manakuro -- you shouldn't need to re-register a debug token across application runs. Once you run the app with the `DebugAppCheckProvider` installed, the debug secret is saved in `SharedPreferences` and used for future runs. I believe on [Android 6 and up, `SharedPreferences` are also saved across app re-installs](https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup).

If this still does not work for your use-case, you may be able to use [`DebugAppCheckProviderFactoryHelper`](https://github.com/firebase/firebase-android-sdk/blob/master/appcheck/firebase-appcheck-debug-testing/src/main/java/com/google/firebase/appcheck/debug/DebugAppCheckProviderFactoryHelper.java) to achieve what you want. However, this is not the intended use of this class, and as such, is an undocumented class.

**Comment by manakuro** [comment]
@rosalyntan 
Thanks for your explanation! I'm going to try it out.
