### ISSUE TITLE
 No engagement_time_msec in the screen_view event

### ISSUE THREAD

**Issue by xingchenfengn** [firebase/firebase-android-sdk#3933]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ ( Analytics)
  * Component version: _____18.0.3

#### Steps to reproduce:

I want to know the calculation logic of the parameter engagement_time_msec in the screen_view event, which is not explained in the official documentation. 
I don't see engagement_time_msec in the console either

#### Relevant Code:

```
07-22 11:25:39.816 V/FA-SVC  (23546): Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{ga_event_origin(_o)=auto, ga_screen_class(_sc)=MainActivity, ga_screen_id(_si)=-994169611236223976}]
```

**Comment by argzdev** [comment]
Hi @xingchenfengn, thanks for reporting. This does seem odd. Upon checking the [documentations](https://support.google.com/firebase/answer/9234069?hl=en). It looks like `engagement_time_msec` should be tracked from these 4 events within the app:
1. app_exception
2. first_open
3. screen_view
4. user_engagement

I tried simulating this, and I'm also unable to track `engagement_time_msec` from `screen_view`. `first_open` and `user_engagement` works fine. That being said, I'll notify our engineers to check and see what we can do here.

**Comment by argzdev** [comment]
Hi @xingchenfengn, I got a response from our engineer.

To explain, the `engagement_time_msec` is our best calculation for how long the user has been looking at that particular screen. In general, it goes from the time the screen was displayed to the time it stopped being displayed, based on activity lifecycle events. An example would be when you open your app, and press home button. You would see a `user_engagement` event logged that includes the `engagement_time_msec` that logs a duration of how long the app was in foreground before it went to the background.

As for the `screen_view` event, this doesn't always contain the `engagement_time_msec`. We sometimes move `engagement_time_msec` event with other events such as screen view events to avoid logging a redundant engagement event. As a result your `screen_view` event sometimes might have an `engagement_time_msec`, but not always.

I hope this answers your questions, I'll close this issue for now. Feel free to ask this to be reopened if it's unclear or open a new thread if you have a new question. Thanks!
