### ISSUE TITLE
OkHttp v2 has been deprecated since 2016 (6+ years now)

### ISSUE THREAD

**Issue by valeriyo** [firebase/firebase-android-sdk#3942]
Latest Firestore directly depends on OkHttp v2 (see https://github.com/firebase/firebase-android-sdk/search?q=com.squareup.okhttp%3Aokhttp)

```
com.google.firebase:firebase-firestore -> 24.2.1
+--- com.squareup.okhttp:okhttp:2.7.5
```

Since the release of OkHttp v3 (https://square.github.io/okhttp/changelogs/changelog_3x/#version-300-rc1) the v2 has been deprecated - and that happened in January of 2016, over 6 years ago.

Are you guys asleep at the wheel?

<img width="736" alt="image" src="https://user-images.githubusercontent.com/7052801/180889181-eb516be9-5195-4faa-b01b-4fd379897b63.png">

**Comment by argzdev** [comment]
Hi @valeriyo, thanks for reporting this. I did some checking, and it looks like this might have something to do with the conflict on [grpc](https://github.com/grpc/grpc-java/issues/6119). But I'll let our engineers know and see what we can do here.

**Comment by tom-andersen** [comment]
I am looking to remove this dependency, and update gRPC to a newer version.

**Comment by tom-andersen** [comment]
I have updated the OkHttp dependencies, and this should be available in an upcoming release. I think I just missed the window for current release.

**Comment by thatfiredev** [comment]
okhttp has been removed from firestore in this week's release ([24.3.1](https://firebase.google.com/support/release-notes/android#firestore_v24-3-1))
