### ISSUE TITLE
Firebase Admin Java SDK should bypass App Check for RTDB operations

### ISSUE THREAD

**Issue by lahirumaramba** [firebase/firebase-android-sdk#3952]
It appears that `java.com.google.firebase.database` currently does not send the auth token for admin clients, and as a result RTDB operations performed through the Admin SDK are unable to bypass App Check.

I think we need to update the [`WebsocketConnection`](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-database/src/main/java/com/google/firebase/database/connection/WebsocketConnection.java) class with a [similar fix](https://github.com/firebase/firebase-js-sdk/commit/99414a51ca5cd25f69a96e4c9949ad5b84e3f64e#diff-ddbaa9e762a6010e5a0aa0c8048d48deea15594f14caa3d51e68b283f36e489fR170) done in the Node.js `firebase/database` package to bypass App Check for Admin SDK requests.

**Comment by lahirumaramba** [comment]
CC: @jsdt

**Comment by maneesht** [comment]
@lahirumaramba I work on RTDB SDKs now, so I can take a look.

**Comment by maneesht** [comment]
@lahirumaramba it seems like the issue is related to the Firebase Java Admin SDK, not the Android Client SDK.

**Comment by lahirumaramba** [comment]
Thank you, @maneesht !
Moving to the [firebase/firebase-admin-java](https://github.com/firebase/firebase-admin-java/issues/704) repo.

https://github.com/firebase/firebase-admin-java/issues/704
