### ISSUE TITLE
Android Timestamp Showing- 26-Jan-1970 in Some Android Device

### ISSUE THREAD

**Issue by Akilramki** [firebase/firebase-android-sdk#3957]
If we Trigger the Multiple Schedule Notification from Firebase.We getting wrong TimeStamp from Some Android Device (26-1-1970)
Currently Noted Devices: Samsung Galaxy’s , Nokia 4.1 , One Plus

Output :

{"collapseKey": "com.firebasetest", "data": {}, "from": "606529", "messageId": "0:16588086484686%3c41be66e66", "notification": {"android": [Object], "body": "HURRY!", "title": "Flat off"}, "sentTime": 2147483647, "ttl": 2419200}

sentTime": 2147483647

console.log(moment(2147483647).format('DD-MMM-YYYY')); // "26-Jan-1970"

**Comment by argzdev** [comment]
Hi @Akilramki, thanks for reporting. Could you answer some questions below:
1. Could you provide more details how to reproduce this issue, such as how many schedule d notifications to trigger before experiencing this behavior? 
2. How are you retrieving the timestamp in your android devices?
3. Also any chance you could share code snippets or [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? It'll greatly help us investigating this further. 

Thanks!

**Comment by Akilramki** [comment]
Hi @argzdev ,thanks for supporting 

1.Could you provide more details how to reproduce this issue, such as how many scheduled notifications to trigger before experiencing this behavior?
we trigger 3 schedule notifications to all devices, it’s scheduled on 1 ,2 and 3 PM, 
   1 o clock notification received to all device, 2 o clock schedule notification received to samsung device at 2.56 o clock, but we getting wrong sendTime  timestamp (26-Jan-1970 02.01.23) from firebase.

2.How are you retrieving the timestamp in your android devices? 
{
"image":"https://www.verywellmind.com/thmb/utB197ZQ8ZtUvjdNwB7B6x5dyRM=/1000x1000/smart/filters:no_upscale()/BestOnlineTherapyServices_V7-9d78415a9c5b4663a6b542acae6d5c61.jpg",
   "title":"Best Offer",
   "body":"HURRY UP",
   "sentTime":2147483647,
   "data":{
      "message":"Test",
      "title":"Test"
   }
}

3.code snippets

App.js

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React, { useEffect, useState } from 'react';
import type {Node} from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
  Alert,
  TouchableOpacity,
} from 'react-native';

import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';
import Notification from './Notification';
import messaging from '@react-native-firebase/messaging';
import moment from 'moment';
import AsyncStorage from '@react-native-async-storage/async-storage';
const Section = ({children, title}): Node => {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
};

const App: () => Node = () => {
  const isDarkMode = useColorScheme() === 'dark';
  const [notification,setNotification] = useState([])
  const [notification1,setNotification1] = useState([])
  const [StoreNotification,setStoreNotification] = useState([])
  const [getStoreNotification,setgetStoreNotification] = useState(null)
  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

   const  requestUserPermission = async() =>  {
    await messaging().registerDeviceForRemoteMessages();
    const token = await messaging().getToken();
    //console.log(token)
    const authStatus = await messaging().requestPermission();
    const enabled =
      authStatus === messaging.AuthorizationStatus.AUTHORIZED ||
      authStatus === messaging.AuthorizationStatus.PROVISIONAL;
  
    if (enabled) {
      //console.log('Authorization status:', authStatus);
    }
  }

  useEffect(() => {
    requestUserPermission()
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
      //console.log(JSON.stringify(remoteMessage))
      storeData(remoteMessage)
      setNotification([...notification,remoteMessage])
      setNotification1(notification1.push(remoteMessage))
    });

    // Register background handler
    messaging().setBackgroundMessageHandler(async remoteMessage => {
      //console.log('Message handled in the background!', remoteMessage);
      storeData(remoteMessage)
      setNotification([...notification,remoteMessage])
      setNotification1(notification1.push(remoteMessage))
    });

    messaging().onNotificationOpenedApp(remoteMessage => {
      // console.log(
      //   'Notification caused app to open from background state:',
      //   remoteMessage.notification,
      // );
      storeData(remoteMessage)
      setNotification([...notification,remoteMessage])
      setNotification1(notification1.push(remoteMessage))
    });

    // Check whether an initial notification is available
    messaging()
      .getInitialNotification()
      .then(remoteMessage => {
        if (remoteMessage) {
          // console.log(
          //   'Notification caused app to open from quit state:',
          //   remoteMessage.notification,
          // );
          storeData(remoteMessage)
          setNotification([...notification,remoteMessage])
          setNotification1(notification1.push(remoteMessage))
        }
      });


    return unsubscribe;
  }, []);

  useEffect(()=>{
   //console.log("notification:",notification,moment(notification.sentTime).format("MMM Do YY"))
   AsyncStorage.setItem('StoreItem',JSON.stringify(notification))
   .then((data)=>{
    //console.log("AsyncStorage::",data)
   })
   .catch((err)=>console.log(err))
  },[notification])

  useEffect(()=>{
    //AsyncStorage.setItem('StoreItem',JSON.stringify(notification1))
   },[notification1])

   useEffect(()=>{
    // AsyncStorage.getItem('StoreItem')
    // .then((data)=>{
    //   console.log(JSON.parse(data))
    //   setStoreNotification(JSON.parse(data))
    // }).
    // catch((err)=>console.log(JSON.parse(err)))
   },[])

   const getData = async()=>{
   await AsyncStorage.getItem('StoreItem')
    .then((data)=>{
      if(data!=null && data!=undefined){
        console.log("AsyncStorage1::",data)
        // console.log(JSON.parse(data),data)
        setStoreNotification(JSON.parse(data))
      }
    }).
    catch((err)=>console.log(JSON.parse(err)))
   }

  const getDateDiff = sentDate => {
    const dateFrom = moment().subtract(14, 'd').format('DD-MMM-YYYY');
    var a = moment(sentDate, 'DD-MMM-YYYY');
    var b = moment(dateFrom, 'DD-MMM-YYYY');
    return a.diff(b, 'days');
  };

  const storeData = async (value) => {
    try {
      const jsonValue = JSON.stringify(value)
      await AsyncStorage.setItem('@storage_Key', jsonValue)
    } catch (e) {
      // saving error
    }
  }


const getStoreData = async () => {
  try {
    const jsonValue = await AsyncStorage.getItem('@storage_Key')
    setgetStoreNotification(jsonValue != null ? JSON.parse(jsonValue) : null);
    console.log(jsonValue)
  } catch(e) {
    // error reading value
  }
}

useEffect(()=>{
  //console.log(getStoreNotification,getStoreNotification?.data?.sentTime,moment(parseInt(getStoreNotification?.data?.sentTime)).format('DD-MM-YYYY hh:mm:ss'))
},[getStoreNotification])


  return (
    <SafeAreaView style={backgroundStyle}>
      <Notification/>
      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        style={backgroundStyle}>
        <Header />
        <View
          style={{
            backgroundColor: isDarkMode ? Colors.black : Colors.white,
          }}>
         {
          notification.map((data,index)=>{
            return(
            <Section key={index} title="Learn More">
           <Text style={{marginVertical:2}}>{data?.notification?.body}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>{data?.notification?.title}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>{data?.sentTime}{'\n'}Length: {String(data?.sentTime).length}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>unix: {moment.unix(data?.sentTime).format('DD-MMM-YYYY hh:mm:ss')}{'\n'}</Text>
           <Text style={{marginVertical:2}}>{ moment(data?.sentTime).format('DD-MMM-YYYY hh:mm:ss')}{'\n'}</Text>
           <Text style={{marginVertical:2,backgroundColor:'#FF0000'}}>{ parseInt(data?.data?.sentTime)!=undefined ? moment(parseInt(data?.data?.sentTime)).format('DD-MMM-YYYY hh:mm:ss'):""}{'\n'}</Text>
           <Text style={{marginVertical:2}}> {getDateDiff(moment(data?.sentTime).format('DD-MMM-YYYY'))}{'\n'} </Text>
           <Text style={{marginVertical:2}}> {getDateDiff(moment(data?.sentTime).format('DD-MMM-YYYY')) <= 14} {'\n'}</Text>
           <Text style={{marginVertical:2}}>{data?.ttl}{'\n'}</Text> 
          </Section>
            )
          })
         }
         <View style={{flexDirection:'row'}}>
         <TouchableOpacity style={{width:'50%',height:50,backgroundColor:'#ccc',justifyContent:'center',alignItems:'center'}} onPress={getData}>
          <Text>Store Data</Text>
         </TouchableOpacity>
         <TouchableOpacity style={{width:'50%',height:50,backgroundColor:'#ccc',justifyContent:'center',alignItems:'center'}} onPress={getStoreData}>
          <Text>AsyncStorage Data</Text>
         </TouchableOpacity>
         </View>

         {
          StoreNotification!=undefined && StoreNotification.map((data,index)=>{
            return(
            <Section key={index} title="Learn More">
           <Text style={{marginVertical:2}}>{data?.notification?.body}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>{data?.notification?.title}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>{data?.sentTime}{'\n'}Length: {String(data?.sentTime).length}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>unix: {moment.unix(data?.sentTime).format('DD-MMM-YYYY hh:mm:ss')}{'\n'}</Text>
           <Text style={{marginVertical:2}}>{ moment(data?.sentTime).format('DD-MMM-YYYY hh:mm:ss')}{'\n'}</Text>
           <Text style={{marginVertical:2,backgroundColor:'#FF0000'}}>{ parseInt(data?.data?.sentTime)!=undefined ? moment(parseInt(data?.data?.sentTime)).format('DD-MMM-YYYY hh:mm:ss'):""}{'\n'}</Text>
           <Text style={{marginVertical:2}}> {getDateDiff(moment(data?.sentTime).format('DD-MMM-YYYY'))}{'\n'} </Text>
           <Text style={{marginVertical:2}}> {getDateDiff(moment(data?.sentTime).format('DD-MMM-YYYY')) <= 14} {'\n'}</Text>
           <Text style={{marginVertical:2}}>{data?.ttl}{'\n'}</Text> 
          </Section>
            )
          })
         }

       {
          getStoreNotification!=undefined && getStoreNotification!=null &&
            <Section title="AsyncStorage">
           <Text style={{marginVertical:2}}>{getStoreNotification?.notification?.body}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>{getStoreNotification?.notification?.title}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>{getStoreNotification?.sentTime}{'\n'}Length: {String(getStoreNotification?.sentTime).length}{'\n'}</Text> 
           <Text style={{marginVertical:2}}>unix: {moment.unix(getStoreNotification?.sentTime).format('DD-MMM-YYYY hh:mm:ss')}{'\n'}</Text>
           <Text style={{marginVertical:2}}>{ moment(getStoreNotification?.sentTime).format('DD-MMM-YYYY hh:mm:ss')}{'\n'}</Text>
           <Text style={{marginVertical:2,backgroundColor:'#FF0000'}}>{ moment(parseInt(getStoreNotification?.data?.sentTime)).format('DD-MMM-YYYY hh:mm:ss')}{'\n'}</Text>
           <Text style={{marginVertical:2}}> {getDateDiff(moment(getStoreNotification?.sentTime).format('DD-MMM-YYYY'))}{'\n'} </Text>
           <Text style={{marginVertical:2}}> {getDateDiff(moment(getStoreNotification?.sentTime).format('DD-MMM-YYYY')) <= 14} {'\n'}</Text>
           <Text style={{marginVertical:2}}>{getStoreNotification?.ttl}{'\n'}</Text> 
          </Section>
         }
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
`

Notification.js
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React, { useEffect } from 'react';
import PushNotificationIOS from "@react-native-community/push-notification-ios";
import PushNotification from "react-native-push-notification";
const Notification: () => Node = () => {
useEffect(()=>{
// Must be outside of any component LifeCycle (such as `componentDidMount`).
PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)
  onRegister: function (token) {
    console.log("TOKEN:", token);
  },

  // (required) Called when a remote is received or opened, or local notification is opened
  onNotification: function (notification) {
    console.log("NOTIFICATION:", notification);

    // process the notification

    // (required) Called when a remote is received or opened, or local notification is opened
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },

  // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
  onAction: function (notification) {
    console.log("ACTION:", notification.action);
    console.log("NOTIFICATION:", notification);

    // process the action
  },

  // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
  onRegistrationError: function(err) {
    console.error(err.message, err);
  },

  // IOS ONLY (optional): default: all - Permissions to register.
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },

  // Should the initial notification be popped automatically
  // default: true
  popInitialNotification: true,

  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   * - if you are not using remote notification or do not have Firebase installed, use this:
   *     requestPermissions: Platform.OS === 'ios'
   */
  requestPermissions: true,
});
   },[])
  return (<></>);
};

export default Notification;
`

**Comment by argzdev** [comment]
Hi @Akilramki, thanks for the extra details. Can you share code snippet of how you're sending the `sentTime` timestamp? So I can try reproducing the error on my side?

**Comment by argzdev** [comment]
Thanks for the extra details, @Akilramki. Is this issue 100% consistent on these devices (Samsung Galaxy’s , Nokia 4.1 , One Plus)? Are you able to reproduce this issue on emulators? Is there a specific Android version this issue is present on?
