### ISSUE TITLE
Offline failure to access a database shows isSuccess in the onComplete event.

### ISSUE THREAD

**Issue by nohe427** [firebase/firebase-android-sdk#3958]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.2.1 Patch 1
  * Firebase Component: Firestore
  * Component version: bom:30.2.0

### [REQUIRED] Step 3: Describe the problem

When running a firestore query with cache disabled and your device on airplane mode, the query returns that is was completed successfully even though it could not access the network and not find resources on the network.
```
        query.get()
            .addOnCompleteListener{
                if (it.isSuccessful) {
                    Log.e("EX", "SUCCESS")
                }
                else {
                    Log.e("EX", it.exception!!.message!!)
                }
            }
            .addOnFailureListener{
                ex -> Log.e("EX", ex.message!!)
            }
            .addOnSuccessListener { qs ->
                Log.e("EX", "SUCCESS")
            }
```

#### Steps to reproduce:

Start an emulator or device in airplane mode. Disable firestore cache
```
val settings = FirebaseFirestoreSettings.Builder()
            .setPersistenceEnabled(false)
            .build()
        firestore.firestoreSettings = settings
```

call query.get() against your firestore database

#### Relevant Code:

See above for snippets. Can reproduce on emulator that is in airplane mode.

```
// TODO(you): code here to reproduce the problem
```

StackOverflow post: https://stackoverflow.com/questions/73199211/android-cloud-firestore-tasks-return-successfully-when-there-is-no-internet-con/73199546

**Comment by MarkDuckworth** [comment]
Hi @nohe427, thanks for reporting this issue. Just to clarify, you are expecting the failure listener to be called when the device is offline and cached is disabled? Let me dig in and see if I can understand when the failure listener should be called and if this is an expected case.

**Comment by nohe427** [comment]
Correct. I assume with no network and cache enabled it would succeed, but with no network and no cache I would expect a failure

**Comment by MarkDuckworth** [comment]
The SDK is behaving as expected. Documentation related to this behavior is at https://firebase.google.com/docs/firestore/manage-data/enable-offline#get_offline_data.

Regarding @nohe427's expectation of what happens with no network and persistence disabled, an in-memory cache is used in that case. This is different from the persistence layer that is enabled or disabled with `setPersistenceEnabled(boolean)`.

I believe the documentation regarding in-memory cache and this scenario (query with no network and no persistence) could be improved, so I have created an internal ticket to improve the docs. (b/241146470)

Since the SDK is behaving as expected, I'm going to go ahead and close this issue. Please follow up with any additional questions or concerns.

**Comment by nohe427** [comment]
Ok, so it comes down to when querying for a specific document with no cache and no network, it would fail, but not for a collection of documents. It will return successfully. Is that the correct understanding?
