### ISSUE TITLE
Remote config: ga4 ab test experiments bug after clearing the app data(app_clear_data)

### ISSUE THREAD

**Issue by Spoof1511** [firebase/firebase-android-sdk#3963]
### Enviroment

  * Android Studio version: Chipmunk 2021.2.1
  * Firebase Component: Firebase Remote Config, Firebase Analytics
  * Component version: firebase_config = '20.0.4',  firebase_analytics = '20.1.0'

### Describe the problem

In ga 4, we see the wrong experiment group after clearing the application data. Before the cleanup, the user was in one ab test group, and after that he became in another, but the old value of experiment group remained in ga 4.

#### Steps to reproduce:

1) Start ab test with 2 groups.
2) Run app and fetch data from remote config.
3) Firebase will split us in first group
4) In ga4 events we see that the user is in the first group
4) Clear app data
5) Run app and fetch data from remote config.
6) Firebase will split us in second group
7) IIn ga4 events we see that the user is in the first group (SHOULD BE IN SECOND)

**Comment by argzdev** [comment]
Hi @Spoof1511, thanks for reporting. This sounds like server side issue. Could you reach out to our [Firebase support](https://firebase.google.com/support/troubleshooter/contact), they'll be able to assist you better.

I'll be closing this for now. Feel free to reopen if you think this is an SDK issue. Thanks
