### ISSUE TITLE
com.google.firebase:firebase-bom:30.3.1 causing "There's been an error processing your app because of an archiving issue."

### ISSUE THREAD

**Issue by ColtonIdle** [firebase/firebase-android-sdk#3966]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: AS chipmunk patch 2
  * Firebase Component: BOM
  * Component version: 30.3.1

#### Steps to reproduce:

I updated firebase BOM today from 

  implementation(platform("com.google.firebase:firebase-bom:30.2.0"))
to
  implementation(platform("com.google.firebase:firebase-bom:30.3.1"))
and now when i try to upload to firebase app dist I get this error:

```
Error: failed to upload release. There's been an error processing your app because of an archiving issue. Use zipalign in your build process and try again. Learn more at https://developer.android.com/studio/command-line/zipalign If this problem continues, contact Firebase support.
Additional information about this error:
APK is not zip aligned.
```

**Comment by argzdev** [comment]
Hi @ColtonIdle, thanks for reporting. Are you uploading via the Firebase Console or via gradle, or fastlane? Any chance you could share us a code snippet or [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? Also steps to reproduce this issue would be very helpful. Thanks in advance!

**Comment by ColtonIdle** [comment]
I'm uploading my app via https://github.com/guness/bitrise-step-firebase-app-distribution
If I revert from 30.3.1 to 30.2.0 then everything works again. I wonder if firebase updated any transitive dependencies.

**Comment by ColtonIdle** [comment]
Here's the command that is actually run on the CI machine:

```
firebase appdistribution:distribute "/bitrise/deploy/internal-release.apk" --app "[REDACTED]" --token "[REDACTED]" --release-notes "Version testing-1" --groups "android"
```

**Comment by argzdev** [comment]
Thanks for the extra details, @ColtonIdle. I tried simulating this via cmd cli and it works fine, I'm assuming this might depend on the Firebase products under BoM being uploaded which is causing the issue. I've only tested this with:
```
implementation platform('com.google.firebase:firebase-bom:30.3.1')
implementation 'com.google.firebase:firebase-analytics'
```
May I know what Firebase products under BoM are you using?

**Comment by ColtonIdle** [comment]
Whoops. Sorry about that. 🤦 

implementation(platform("com.google.firebase:firebase-bom:30.2.0"))
  implementation("com.google.firebase:firebase-analytics")
  implementation("com.google.firebase:firebase-messaging")
  implementation("com.google.firebase:firebase-crashlytics-ktx")
  implementation("com.google.firebase:firebase-perf")

In my root build.gradle I also have

classpath("com.google.firebase:firebase-crashlytics-gradle:2.9.1")
    classpath("com.google.firebase:perf-plugin:1.4.1")

Thank you for the quick response!

**Comment by ColtonIdle** [comment]
I've updated similar projects and they seem to work fine, but they dont use analytics, messaging, or perf. So I wonder if it has to do with 1 of those 3 deps.

**Comment by argzdev** [comment]
Interestingly, I'm unable to reproduce the issue. There might be a configuration in your build.gradle that I don't have. Could you share a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) with the issue?

**Comment by ColtonIdle** [comment]
Thanks for checking. I will try to create a minimal sample. I also just tried to update a bunch of other dependencies and they worked fine. But I came across another one that causes the upload issue.
  implementation("androidx.core:core-splashscreen:1.0.0-rc01")
to
  implementation("androidx.core:core-splashscreen:1.0.0")

```
Error: failed to upload release. There's been an error processing your app because of an archiving issue. Use zipalign in your build process and try again. Learn more at https://developer.android.com/studio/command-line/zipalign If this problem continues, contact Firebase support.
Additional information about this error:
APK is not zip aligned.
```
Very weird indeed.

**Comment by ColtonIdle** [comment]
If I skip the automated upload and do it manually I get the same error. So that takes the cli upload out of the questions.

<img width="957" alt="2022-08-04 at 15 30 02" src="https://user-images.githubusercontent.com/31751141/182937665-476fb424-f5cb-4995-8c47-33a7c3e279d7.png">

**Comment by ColtonIdle** [comment]
I thought maybe it was related to r8/proguard, but I removed that and same issue... working on a minimal repro build.gradle.kts I can share.

**Comment by ColtonIdle** [comment]
I tried making a minimal repro, but the problem went away. So I'm a bit stuck here for now. I really dont understand how a simple dep update could bring up an archiving issue (unless the firebase upload error message is incorrect?) I'm going to see if I can upload to google play. If google play gives a signing issue, then I suppose the issue is legit.

**Comment by ColtonIdle** [comment]
Uploaded to the play store without a problem. I'm starting to think that maybe this is a false error on the firebase app dist upload side of things.

**Comment by ColtonIdle** [comment]
As you can see — only a 5B difference between the two apks. 
<img width="1036" alt="2022-08-04 at 19 12 10" src="https://user-images.githubusercontent.com/31751141/182970509-d1b3f6ea-5aab-4778-837a-f45182b53971.png">

**Comment by ColtonIdle** [comment]
<img width="1030" alt="2022-08-04 at 19 27 04" src="https://user-images.githubusercontent.com/31751141/182971900-bf9dedb4-cdd6-4a0f-a991-6b221cfb9f06.png">
<img width="1019" alt="2022-08-04 at 19 26 52" src="https://user-images.githubusercontent.com/31751141/182971904-013399ad-2e26-4ddf-b514-9ac50967f14b.png">

looks like the only difference is the name? 🤯 
completely lost. but i think this is an error with app distribution

**Comment by vcaen** [comment]
It is indeed the only difference between rc01 and stable. Did you try to completely remove the lib and see if it fails?

**Comment by ColtonIdle** [comment]
I can try to remove the splash lib. Just need a small tweak to my manifest, theme, and mainactivity. gimme 1 sec to test. 😄

**Comment by ColtonIdle** [comment]
OOOH. Unexpected results IMO. 
removed the library. and now the error is there. so its almost like removing the library and upgrading the library have the same result. i guess its clear that its not a splash screen issue (thanks @vcaen ) and its very much likely that its either some app bundling issue or a firebase app dist issue.

**Comment by ColtonIdle** [comment]
I downgraded agp from alpha09 to beta05 and now everything works. So either an issue with firebase app dist not being able to handle something in the newest alpha09 agp (because the play store upload does NOT complain) or it's something actually with agp. I'll file a bug with the agp team as well.

**Comment by ColtonIdle** [comment]
Filed: https://issuetracker.google.com/issues/241469653
I think it might make sense to see if AGP team and firebase app dist team can try to see if they can figure out what changed here.

**Comment by ColtonIdle** [comment]
Marking as closed. It seems to be AGP related. There's a workaround in the issuetracker above.

Thank you @argzdev and @vcaen
