### ISSUE TITLE
[MFA] getEnrollmentTimestamp is returning 0

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-android-sdk#4001]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.2.1 Patch 2
  * Firebase Component: Auth
  * Component version: 30.3.0

### [REQUIRED] Step 3: Describe the problem

When running `getEnrollmentTimestamp()`, the SDK is returning 0.
When running the equivalent code on iOS the correct Timestamp is returned.

#### Steps to reproduce:
Run `multiFactor.getEnrolledFactors();` and go through the results

#### Relevant Code:
```
if (info instanceof PhoneMultiFactorInfo) {
  final long a =  info.getEnrollmentTimestamp();
```

`a` should not be 0 

Related issue
https://github.com/firebase/flutterfire/issues/9354

**Comment by argzdev** [comment]
Hi @Lyokone, thanks for reporting. I was able to reproduce the same behavior. I'll notify our engineers and see what we can do here.
