### ISSUE TITLE
Caused by java.lang.RuntimeException: Failed to gain exclusive lock to the Cloud Firestore client's offline persistence

### ISSUE THREAD

**Issue by KissloveDewangan** [firebase/firebase-android-sdk#4034]
While using cloud firestore android SDK, getting below error:
`Caused by java.lang.RuntimeException: java.lang.RuntimeException: Failed to gain exclusive lock to the Cloud Firestore client's offline persistence. This generally means you are using Cloud Firestore from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing Cloud Firestore in your Application class. If you are intentionally using Cloud Firestore from multiple processes, you can only enable offline persistence (that is, call setPersistenceEnabled(true)) in one of them.
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
       at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$SynchronizedShutdownAwareExecutor$oFTIvhhx7tqTG4gmyuURvt31K0g.run(-.java:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:234)
       at java.lang.Thread.run(Thread.java:923)`
       
 Although in our Android app, we create two separate processes but we are using initializing and using firestore only in the main process but still we are getting this above issue log.
 And also we tried to disable the offline persistence but this issue is still persists.

 Please look into this issue. Any help would be appreciated. Thanks!

**Comment by argzdev** [comment]
Hi @KissloveDewangan, thanks for reporting. Can you answer a few questions below:
1. What Firestore version are you currently using? Have you tried using the latest version?
2. Could you share snippets of your code or a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? 
3. Can you share steps how to reproduce this issue?

These information will greatly help us in our investigation. Thanks in advance!

**Comment by KissloveDewangan** [comment]
Hi @argzdev, Please find the details below:
1. Firebase BOM ver 30.3.1
2. Code snippets below
`private suspend fun Context.deleteDuplicateEntries(xyz: String, pqr: String) {

    if (this.checkForSecondaryProcess()) {
        return
    }

    try {
        val document = Firebase.firestore.collection("XXXX").whereEqualTo("XXXX", xyz).get()
            .await().documents
        document.forEach { doc ->
            if (doc.get("XXXXX") != pqr) {
                doc.reference.delete()
            }
        }
    } catch (exception: Exception) {
        track("FireStoreEventFail", "method" to "deleteDuplicateEntries", "exception" to exception)
        FirebaseCrashlytics.getInstance().recordException(Exception("FireStoreEventFail deleteDuplicateEntries -- $exception"))
    }
}`
`fun Context.addUserIdToFireStore(xyz: String? = null, retryCount: Int = 0) {

    if (this.checkForSecondaryProcess()) {
        return
    }

    MainScope().launch(Dispatchers.IO) {

        try {
            val eventProps = hashMapOf<String, String>()
            val uid = checkAndSignIn()
            if (uid.isNullOrEmpty()) return@launch

            eventProps["XXXX"] = uid
            if (!userId.isNullOrEmpty()) {
                eventProps["YYYY"] = xyz
            }

            val userDoc = Firebase.firestore.collection("WWWW").document(uid).get().await()
            if (!userDoc.exists()) {
                Firebase.firestore.collection("WWWW").document(uid).set(eventProps).await()
                if (!xyz.isNullOrEmpty()) {
                    deleteDuplicateEntries(xyz, uid)
                }
            } else {
                if (userDoc.data?.get("WWWW") == null) {
                    Firebase.firestore.collection("WWWW").document(uid).update("WWWW", xyz).await()
                    if (!xyz.isNullOrEmpty()) {
                        deleteDuplicateEntries(xyz, uid)
                    }
                }
            }

        } catch (exception: Exception) {
            track("FireStoreEventFail", "method" to "addUserIdToFireStore", "exception" to exception, "retryCount" to retryCount)
            FirebaseCrashlytics.getInstance().recordException(Exception("FireStoreEventFail addUserIdToFireStore -- $exception"))
            if (retryCount < 2 && exception is FirebaseFirestoreException) {
                delay(1000)
                addUserIdToFireStore(xyz, retryCount+1)
            }
        }
    }
}`
Here function `addUserIdToFireStore`can be called from multiple places at a time.

3. Currently, we don't have the steps to reproduce, even we are still debugging this issue. But this issue we are facing at the Production scale i.e. around 55K DAUs and we are getting around > 150 crashes instances daily for these much amount of users traffic

**Comment by argzdev** [comment]
Thanks for the extra details, @KissloveDewangan. Upon investigation, it looks like this code shouldn't be reachable if offline persistence is disabled.

https://github.com/firebase/firebase-android-sdk/blob/befe421de2a359ac1861a57825ad1a5a91367288/firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java#L139-L149

Could you share a code snippet where you initialize Firestore and where you disable offline persistence? Perhaps that will give us a clue of the issue. Also if there's any chance you could provide a minimal reproducible example, that'll greatly help us. Thanks in advance!
