### ISSUE TITLE
Ability to linkWithCredential with Apple Sign In

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-android-sdk#4064]
## What feature would you like to see?

Ability to linkWithCredential with Apple Sign In. Currently, the only way to get an Apple Token is to use signInWithCredential. But since it will logout the current Anonymous user, we have no way to link the Anonymous user.
 
## How would you use it?

Being able to link a current anonymous user to an Apple Sign In

**Comment by argzdev** [comment]
Thanks for filing, @Lyokone. I've marked this as a feature request, so our engineers can take a look when they have the time. I can't promise any timeline for this. If others find this feature useful, adding an emoji thumbs up on the main post can help our engineers prioritize adding this to the roadmap.

**Comment by rosalyntan** [comment]
Hi @Lyokone, this feature already exists. The relevant method can be found [here](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#startActivityForLinkWithProvider(android.app.Activity,%20com.google.firebase.auth.FederatedAuthProvider)).

**Comment by Lyokone** [comment]
Thanks a lot for your help, totally missed it
