### ISSUE TITLE
[auth] Dynamic Link Path Prefixes are not kept when using Sign In Link 

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-android-sdk#4079]
as reported in the FlutterFire repo: https://github.com/firebase/flutterfire/issues/5051

### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: Auth

#### Steps to reproduce:

When trying to setup [Sign in With Link with a path prefix](https://firebase.google.com/docs/auth/android/email-link-auth#completing_sign-in_in_an_android_app) (previously setup in Dynamic Link), the path prefix is not kept.

#### Relevant Code:

```
ActionCodeSettings actionCodeSettings =
        ActionCodeSettings.newBuilder()
                // URL you want to redirect back to. The domain (www.example.com) for this
                // URL must be whitelisted in the Firebase Console.
                .setUrl("https://custom.domain/dl/signIn")
                // This must be true
                .setHandleCodeInApp(true)
                .setIOSBundleId("com.example.ios")
                .setDynamicLinkDomain("custom.domain")
                .setAndroidPackageName(
                        "com.example.android",
                        true, /* installIfNotAvailable */
                        "12"    /* minimumVersion */)
                .build();

FirebaseAuth auth = FirebaseAuth.getInstance();
auth.sendSignInLinkToEmail(email, actionCodeSettings)
        .addOnCompleteListener(new OnCompleteListener<Void>() {
            @Override
            public void onComplete(@NonNull Task<Void> task) {
                if (task.isSuccessful()) {
                    Log.d(TAG, "Email sent.");
                }
            }
        });

```

#### Expected behavior
The generated sign in link should be using the custom domain and the path prefix.

**Comment by rosalyntan** [comment]
Hi @Lyokone, thanks for filing this issue!

In the [docs](https://firebase.google.com/docs/auth/android/email-link-auth#completing_sign-in_in_an_android_app), we have this section, which I believe may be relevant to your use case:

"When creating your dynamic link domain you may have also created a short URL link. This short URL will not be passed; do not configure your intent filter to catch it with an android:pathPrefix attribute. This means that you will not be able to catch different dynamic links in different parts of your application. However, you can check the mode query parameter in the link to see what operation is attempting to be performed, or use SDK methods such as isSignInWithEmailLink to see if a link that your app has received does what you want."

Does the workaround listed here work for your case?

**Comment by Lyokone** [comment]
I think I'll close this, the issue in FlutterFire seems to have a resolution. Thanks :)
