### ISSUE TITLE
Thanks for the dependency info! Could you also please include your `build.gradle`? I've seen another instance of this issue when the configuration includes:

### ISSUE THREAD

**Issue by Ukandu147** [firebase/firebase-android-sdk#4094]
Thanks for the dependency info! Could you also please include your `build.gradle`? I've seen another instance of this issue when the configuration includes: 

```configurations { all { exclude(group = "com.google.protobuf", module = "protobuf-javalite") } }```

which effectively removes code in the `com.google.protobuf` package, which the `registerDefaultInstance` is part of. So that's my current hunch.

About whether it's required: yes, it is. We use it to encode the data when it's transferred from the device to the service.

_Originally posted by @rlazo in https://github.com/firebase/firebase-android-sdk/issues/1907#issuecomment-680981365_

**Comment by argzdev** [comment]
Hi @Ukandu147, thanks for reporting. It looks like #1907 has been resolved, could you share details of the issue you're experiencing?
