### ISSUE TITLE
Crash NoClassDefFoundError in "firebase-installations-executor-1"

### ISSUE THREAD

**Issue by rupiapps** [firebase/firebase-android-sdk#4097]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.2.1
  * Firebase Component: analytics (Database, Firestore, Storage, Functions, etc)
  * Component version: 21.1.1

### [REQUIRED] Step 3: Describe the problem
Since last saturday (10th sept.) I see lots of crashs in crashlytics.
The crahes happen directly at start of the app. Most of them happen on android 12 devices.
Not all of them happen at the latest version of my app and it did not happen before Saturday.
So the problem is probably not inside my app.
the stacktrace looks like this: firebase-installations-executor-1
jdk.internal.misc.Unsafe.park (Unsafe.java)
java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:234)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2123)
java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:458)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1062)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1123)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
java.lang.Thread.run (Thread.java:1012)

#### Steps to reproduce:
I don't know how to reproduce. it happens on some android 12 devices and it happens directly at start of the app.

**Comment by argzdev** [comment]
Thanks for reporting, @rupiapps. Could you answer the following questions?
1. May I know what Firebase products are you using? 
2. Could you add a full stacktrace of your issue? You can format it by adding 3 single quotes as the first line and last line of your stacktrace, like this:
<img width="246" alt="Screen Shot 2022-09-15 at 9 22 03 PM" src="https://user-images.githubusercontent.com/93124282/190414821-aba960a5-0826-4992-a521-179671dbac59.png">


And will result into this:
```
Hello, this is a multiline stacktrace
Another line.
```
3. Any code snippets you could share regarding your issue?

Thanks in advance!

**Comment by argzdev** [comment]
Sorry @rupiapps! I meant back quotes (`) not single quotes('). While I investigate this, did you happen to update your Firebase versions before this issue started? If so, could you share me the previous versions you were using?

**Comment by rupiapps** [comment]
I did update analytics from 21.0.0 to 21.1.1 and firebase-perf from 20.1.0 to 20.1.1
but it also happens on older versions of the app.
I'm not even sure if it related to firebase. 
I think it is a device related issue regarding native methos.

**Comment by rupiapps** [comment]
hi,
I was now able to reproduce the issue on one of my devices. 
The issue is NOT related to firebase.
it happens when calling class.getDeclaredMethods()
