### ISSUE TITLE
[auth] Inconsistence between documentation and SDK

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-android-sdk#4118]
Related to FlutterFire: https://github.com/firebase/flutterfire/issues/9566

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Latest
  * Firebase Component: Auth
  * Component version: 30.5.0

#### Steps to reproduce:

[In the documentation](https://firebase.google.com/docs/auth/android/microsoft-oauth#handle_the_sign-in_flow_with_the_firebase_sdk) there is a mention of `authResult.getCredential().getAccessToken()` but I cannot seem to access it on the AuthCredential object.

#### Relevant Code:

```
  AuthResult authResult =
      Tasks.await(
          firebaseAuth.startActivityForSignInWithProvider(
              /* activity= */ activity, provider.build()));
authResult.getCredential().getAccessToken();
```

**Comment by argzdev** [comment]
Thanks for reporting, @Lyokone. It looks like you need to cast the `getCredentials()` as `OAuthCredential`. So retrieving the access token would be something like this `((OAuthCredential) authResult.getCredential()).getAccessToken()`. That said, I'll let our engineers know and update our documentations accordingly. 

I'll close this issue now. If the solution doesn't work, feel free to ask this to be reopened.
