### ISSUE TITLE
Gradle and AGP versions to compile the project are unclear

### ISSUE THREAD

**Issue by shamilovtim** [firebase/firebase-android-sdk#4119]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.2.1 Patch 2
  * Firebase Component: Perf
  * Component version: Latest

#### Steps to reproduce:

For local development contributions, the project docs do not specify Gradle or AGP versions to compile the project with. The project doesn't specify AGP version in local gradle files either. Users who wish to compile this project must search the repo for issues and PRs to see what Gradle versions the project calls for.

#### Relevant Code:

Propose adding to the docs:
under: CONTRIBUTING

```
This project should be compiled with:
Android Gradle Plugin: 4.2.2
Gradle: 6.5.1
```

**Comment by argzdev** [comment]
Hi @shamilovtim, thanks for reporting. I'll let our engineering team know about this.

**Comment by argzdev** [comment]
I've consulted with our engineer, and it looks like Firebase-Performance works with the latest stable AGP and Gradle version. I'll try and check if we can include this in our README.md. That being said, I'll close this issue for now.

Feel free to ask this to be reopened if you think this is a mistake, or if you think further action needs to be done. Thanks!

**Comment by shamilovtim** [comment]
> I've consulted with our engineer, and it looks like Firebase-Performance works with the latest stable AGP and Gradle version. I'll try and check if we can include this in our README.md. That being said, I'll close this issue for now.
> 
> Feel free to ask this to be reopened if you think this is a mistake, or if you think further action needs to be done. Thanks!

Hey, yeah that's not the case. To be clear I'm referring to compiling **this project** not bringing Firebase Perf into a project as an end user.

**Comment by argzdev** [comment]
Thanks for the update, @shamilovtim. I have AGP `7.2.2` and Gradle version `7.3.3` and tried to compile and assembled `firebase-android-sdk` via `gradle firebase-perf:assemble`, this seems to work fine. Is there any specific error you're encountering when compiling the project?

**Comment by shamilovtim** [comment]
> Thanks for the update, @shamilovtim. I have AGP `7.2.2` and Gradle version `7.3.3`. I tried to compile and assemble `firebase-android-sdk` via `gradle firebase-perf:assemble`, this seems to work fine. Is there any specific error you're encountering when compiling the project with the latest stable version of AGP and Gradle? I might be missing something.

Awesome let me try those. I followed the docs with latest AGP/Gradle was trying latest and getting Gradle errors.

**Comment by thatfiredev** [comment]
@shamilovtim We are using:

- AGP 7.2.2:
    https://github.com/firebase/firebase-android-sdk/blob/4f24be3d2ac6481cb5c3995b4abcf5361894b1c7/buildSrc/build.gradle.kts#L59
- Gradle 7.3.3:
    https://github.com/firebase/firebase-android-sdk/blob/4f24be3d2ac6481cb5c3995b4abcf5361894b1c7/gradle/wrapper/gradle-wrapper.properties#L3

Also note that you'll need Java 11:
https://github.com/firebase/firebase-android-sdk/blob/4f24be3d2ac6481cb5c3995b4abcf5361894b1c7/build.gradle#L72-L74

I'll check if we can get this documented in the repo itself as you suggested.

**Comment by shamilovtim** [comment]
Thank you guys for responding. I think I just had a weird hiccup in Android Studio because after re-importing the project all over again, all of the Gradle versions inferred automatically and nothing manual was actually needed out of me.
