### ISSUE TITLE
INTERNAL ASSERTION FAILED: A transaction object cannot be used after its update callback has been invoked.

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-android-sdk#4147]
### [READ] Step 1: Are you in the right place?

Hopefully

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: N/A
  * Firebase Component: Firestore
  * Component version: 30.5.0

### [REQUIRED] Step 3: Describe the problem

The error in the title has been showing up in our error reporting service immediately after updating from 30.3.2 to 30.5.0 (in Flutterfire).
It **periodically** hard crashes when running a transaction.

I can't reproduce it myself, only our customers can, as it usually goes. 😆

Here's an obfuscated stack trace that I'm sure is extremely useful:
```
x1.b in a at line 6
x1.b in d at line 3
q1.g1 in f at line 9
q1.g1 in j at line 1
com.google.firebase.firestore.t0 in d at line 2
com.google.firebase.firestore.t0 in c at line 2
i4.t in U at line 5
i4.t in k
i4.m in run at line 6
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1167
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 641
java.lang.Thread in run at line 920
```

#### Steps to reproduce:

Sadly I don't know.
Has any changes been made to the transaction logic lately?

#### Relevant Code:

None

**Comment by ehsannas** [comment]
Can you please provide the code snippet that you're running?

**Comment by larssn** [comment]
Sure, it's Dart code though, but it's nothing fancy.

```dart
Future<String> _getReferenceNumber() {
    return _db.runTransaction((trx) async {
      final ref = _db.doc('organizations/${_organization.id}');
      final snap = await trx.get(ref);
      final org = Organization.fromSnapshot(snap);
      final split = org.lastReferenceNumber.split('-');
      final time = DateTime.now().format('yyMMdd');

      String newTime;
      if (split[0] == time) {
        final n = num.parse(split[1]);
        newTime = '${split[0]}-${n + 1}';
      } else {
        newTime = '$time-1';
      }

      trx.update(ref, {
        'lastReferenceNumber': newTime,
      });

      return newTime;
    }, timeout: const Duration(seconds: 5));
  }
```

**Comment by larssn** [comment]
Hm, we're also getting crashes in 30.3.2 now, which is making me think that the issue is a side effect to another issue we're seeing atm: We're getting `cloud_firestore/deadline-exceeded` errors on documents that are no where near 1 write per second (which is the above `ref`).

We're moving the above function into Cloud Functions, and then access it via a REST endpoint as a workaround for now.

Not sure what is going on...

**Comment by ehsannas** [comment]
Thanks for the update. I can't see anything wrong with this code snippet per se; perhaps it's the way this function (`_getReferenceNumber`) is being used in the rest of your codebase.

Please create a minimal standalone reproduction app and file an issue against https://github.com/firebase/flutterfire to get the investigation started there. Thanks!
