### ISSUE TITLE
ML Model Downloader is giving wrong exception

### ISSUE THREAD

**Issue by sandeep5193** [firebase/firebase-android-sdk#4157]
### Step 2: Describe your environment

  * Android Studio version: Dolphin, 2021.3.1
  * Firebase Component: firebase-ml-modeldownloader
  * Component version: 24.0.5

### Step 3: Describe the problem
In 2 situations, model download is failing.
1) for some reason, it has started to fail on my WiFi connection, while on mobile data it works. this has started recently.
2) when model name passed is empty string.

while there can be a problem with the network, and of course in point no 2 it should fail, but error message it is giving is misleading.

Error message for Empty model name:
`Permission error while fetching model (): HTTP response from Firebase Download Service: [401 - Unauthorized: API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication]`

And yes, I have restricted my API key with debug/release keys.

#### Steps to reproduce:

restrict API key with android app's debug/release key, send modelName as empty string to `getModel()` method.

#### Relevant Code:

```
FirebaseModelDownloader.getInstance(FirebaseApp.getInstance())
                .getModel("", DownloadType.LOCAL_MODEL, conditions)
```

**Comment by argzdev** [comment]
Thanks for reporting, @sandeep5193. Just to clarify so I don't get it wrong, how did you "restrict API key with android app's debug/release key"? Can you walk me through the steps? 

Also I wonder, does passing an empty string to the `getModel()` work if the API is not restricted?

Thanks!

**Comment by sandeep5193** [comment]
I have restricted the API used for this project with [these](https://cloud.google.com/docs/authentication/api-keys?hl=en_US#android) steps.

I have not tried passing an empty string to that method when API is not restricted, this is a prod setup, I cannot test that.

**Comment by argzdev** [comment]
Thanks for the extra details, @sandeep5193. I was able to reproduce the same behavior. It seems that passing an incorrect string to the `getModel()` will result to this error behavior, including passing an empty string. That said, I'll notify our engineer and see what we can do here. Thanks!

**Comment by Sankyuubigan** [comment]
i updated fierbase libs and now i have this error. very bad. have you any workaround temporary case ?

**Comment by argzdev** [comment]
Hi @Sankyuubigan, can you explain what issue are you experiencing? Is it the internet connection issue? Also can you share what previous version were you using?

**Comment by argzdev** [comment]
Hi @sandeep5193, we've added a new exception handler for empty strings. The fix would be available in the next upcoming release. That said, I'll close this issue now.
