### ISSUE TITLE
Got Token FCM but the onMessageReceived is never called... 

### ISSUE THREAD

**Issue by exaland** [firebase/firebase-android-sdk#4175]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.1.1 Patch 3
  * Firebase Component: Messaging
  * Component version: Via firebase-bom:28.2.1

#### Steps to reproduce:

What happened? How can we make the problem occur?
In MyFirebaseMessagingService declared in Manifest  i receive the Token in function "onNewToken" but never i receive any log in "onMessageReceived" and never i receive any Notification

#### Relevant Code:

```
// TODO(you):

FirebaseMessaging.getInstance().getToken()
              .addOnCompleteListener(task -> {
                  if (!task.isSuccessful()) {
                      Log.w("FCM registration token", "Fetching FCM registration token failed", task.getException());
                      return;
                  }

                  // Get new FCM registration token
                  String token = task.getResult();

                  // Log and toast
                  Log.d("FCM registration token", token);
                  userInfoHandler.setFcmRegistrationId(token);
              });
```

**Comment by argzdev** [comment]
Thanks for reporting, @exaland. It looks like you're using an old version of the SDK. Could you try using our latest version in Firebase BoM (30.5.0) and see if this resolves the issue?

Just to give some insights, you do not receive any notification when receiving a new token on `onNewToken`. That said, have you tried sending a notification to the new token you've registered? If not, you can use our documentations [here](https://firebase.google.com/docs/cloud-messaging/android/first-message#send_a_test_notification_message) for the steps.

Let me know if this works. Thanks

**Comment by thatfiredev** [comment]
@exaland what device are you testing on?
And can you also share your `onMessageReceived` code snippet?

**Comment by argzdev** [comment]
Thanks for the extra details, @exaland. I tried a clean project with your setup. However, I'm unable to reproduce the issue.
Code snippet:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.argz.issue4175">

    <application
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.Issue4175"
        tools:targetApi="31">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service
            android:name=".MyFirebaseMessagingService"
            android:enabled="true"
            android:permission="com.google.android.c2dm.permission.SEND"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <service
            android:name="com.google.firebase.components.ComponentDiscoveryService"
            android:directBootAware="true"
            android:exported="true"
            tools:replace="android:exported">

            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />

            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
        </service>

    </application>

</manifest>
```


```
class MyFirebaseMessagingService : FirebaseMessagingService() {

    override fun onMessageReceived(remoteMessage: RemoteMessage) {
        Log.d(TAG, "From: ${remoteMessage.from}")

        if (remoteMessage.data.isNotEmpty()) {
            Log.d(TAG, "Message data payload: ${remoteMessage.data}")
        }

        remoteMessage.notification?.let {
            Log.d(TAG, "Message Notification Body: ${it.body}")
        }
    }

    override fun onNewToken(token: String) {
        Log.d(TAG, "Refreshed token: $token")
    }

    companion object {
        private const val TAG = "MyFirebaseMsgService"
    }
}
```

```
private const val TAG = "MainActivity"
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        Firebase.messaging.getToken().addOnCompleteListener(OnCompleteListener { task ->
            if (!task.isSuccessful) {
                Log.w(TAG, "Fetching FCM registration token failed", task.exception)
                return@OnCompleteListener
            }

            val token = task.result
            Log.d(TAG, token)
            Toast.makeText(baseContext, token, Toast.LENGTH_SHORT).show()
        })
    }
}
```


Log results:
```
2022-10-06 20:34:49.503 28717-28802/com.argz.issue4175 D/MyFirebaseMsgService: From: 1059489949573
2022-10-06 20:34:49.503 28717-28802/com.argz.issue4175 D/MyFirebaseMsgService: Message data payload: {body=test, test=data}
2022-10-06 20:34:49.504 28717-28802/com.argz.issue4175 D/MyFirebaseMsgService: Message Notification Body: body
```

I would recommend first trying out our [quickstart sample](https://github.com/firebase/quickstart-android) for Firebase Messaging and initially make that work to receive notifications then slowly transfer snippets of your code to the quickstart to see what made it "not" work. I think that'll help you find your issue a lot faster.


If that doesn't work/help, could you provide me a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of your issue, so we can investigate this further?

**Comment by exaland** [comment]
I want add an precision , the problem appears with the API 31 update and with **tools:node="replace"** added in AndroidManifest.xml file

When i remove this attribute **tools:node="replace"** i have Android 12 merge problem attribute

**Comment by exaland** [comment]
Fixed with removed this attribute in AndroidManifest.xml  **tools:node="replace"** Thanks @argzdev and @thatfiredev for your Help
