### ISSUE TITLE
Using Firestore on a watch consumes a lot of power. Is there an optimization solution?

### ISSUE THREAD

**Issue by zhanlv** [firebase/firebase-android-sdk#4196]
![image](https://user-images.githubusercontent.com/26138453/195229443-aa093dc6-1945-48d3-b7f3-4ad7f25bffc1.png)
![image](https://user-images.githubusercontent.com/26138453/195229632-c9737a1c-9126-47cd-87f3-dd313f0b3195.png)
use addSnapshotListener

**Comment by MarkDuckworth** [comment]
@zhanlv, there are no optimizations that I'm aware of. You could see if poling the backend using `getDocs()` uses less power, but this has other tradeoffs.

Can you please explain the first screenshot? What in that screenshot it indicating that a watch uses lots of power?

**Comment by zhanlv** [comment]
![image](https://user-images.githubusercontent.com/26138453/195476256-40686a5b-c25a-48a7-b31b-14971c9ef915.png)


> @zhanlv, there are no optimizations that I'm aware of. You could see if poling the backend using `getDocs()` uses less power, but this has other tradeoffs.
> 
> Can you please explain the first screenshot? What in that screenshot it indicating that a watch uses lots of power?

![image](https://user-images.githubusercontent.com/26138453/195476293-0145f8d3-48f4-416c-9236-1bb57882116b.png)

**Comment by zhanlv** [comment]
> @zhanlv, there are no optimizations that I'm aware of. You could see if poling the backend using `getDocs()` uses less power, but this has other tradeoffs.
> 
> Can you please explain the first screenshot? What in that screenshot it indicating that a watch uses lots of power?

![image](https://user-images.githubusercontent.com/26138453/195476364-3810a551-b4d6-4711-b524-6ed1bad5e280.png)
@MarkDuckworth

**Comment by MarkDuckworth** [comment]
@zhanlv, a few things.

1. A watch requires an open connection with the server, even if data is not actively sent. You could play with polling using getDocs() or potentially disable the network during certain times using [disableNetwork()](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#disableNetwork()). But those may affect the viability of your solution.
2. We can't move forward with the screenshot of steady current. It's not specific enough to indicate any issue with Firestore. If you believe there is an issue here, perhaps it would be better to profile your application and show that Firestore is indeed consuming significant CPU on your machine.
