### ISSUE TITLE
FirebaseAuthInvalidUserException

### ISSUE THREAD

**Issue by jvojacek** [firebase/firebase-android-sdk#4197]
Hello,
in our project we use Firebase Auth. When I try to get idToken, reload user or anything else I get FirebaseAuthInvalidUserException from time to time with some unrecommended message like Account can be disabled, deleted or credentials could change. 
But in the last few days I received a FirebaseAuthInvalidUserException with the message This user's credential isn't valid for this project. This can happen if the user's token has been tampered with, or if the user isn't for the project associated with this API key.

What does it mean? How can we fix this?

When I catch this exception I log the user out, but after that the user can log back in normally and everything works fine. (So obviously the credentials are valid for this project :D )

Thank you in advance for your reply.

**Comment by argzdev** [comment]
Hi @jvojacek, thanks for reporting. Are you able to reproduce this issue on your end? Could you share code snippets or a minimal reproducible example of your issue? That'll greatly help us investigate this further. Thanks!

**Comment by jvojacek** [comment]
Hello,
we've found that the affected users are using Google Provider in Auth. 
In the network availability listener I got this exception -> if a user came from offline to online, I try to reload it via currentUser.reload() and in the onFailure callback I get this exception.

**Comment by argzdev** [comment]
Hi @jvojacek, I can't really say what the issue might be. I think it's best if you could share code snippets or [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), so I can try and reproduce the same issue on my end. That way , itll allow us to understand your issue more.
