### ISSUE TITLE
[Firebase-Pref] lib is getting issue in CIDE pipeline when sourceCompatibility version is 11

### ISSUE THREAD

**Issue by KrunalStrategyX** [firebase/firebase-android-sdk#4229]
java.lang.UnsupportedClassVersionError: com/google/firebase/perf/plugin/FirebasePerfPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> com/google/firebase/perf/plugin/FirebasePerfPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by KrunalStrategyX** [comment]
I have resolve this issue.
it happen when i was start my CICD pipeline in release in build. i was change build variants release to debug and it work properly.

**Comment by argzdev** [comment]
I'm glad it's working now. Thanks for confirming @KrunalStrategyX. I'll close this issue now since this has been resolved.
