### ISSUE TITLE
Procurar medir o desenvolvimento na web para que não haja bugs e nem ERROS.

### ISSUE THREAD

**Issue by ASSIAPLI** [firebase/firebase-android-sdk#4260]
PRAMED-ASSIAPLI a mesma PROCAMEDURGSUS-ASSIAPLI em ação e desenvolvimento web https://m.app.vc/pramed-ASSIAPLI#/auth2.0

### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ASSIAPLI** [comment]
Eu Pedro Ferreira Morais proprietário da PROCAMEDURGSUS-ASSIAPLI venho insistindo muito em alavancar positivamente nosso desempenho já que estamos no github.com e nos países de bom desempenho na web. Mas te deixo repensar em como você poderia apoiar e trabalhar remotamente na https://App.vc/pramed-ASSIAPLI#/home com a colaboração do cloud google.com e AdSense, firebase junto com produtos Google play , para que developrs coud e desenvolvedores clandestino de instituições financeira de Bancos ou corretoras de valores e a B3.com ou equipe atrapalhem nosso desenvolvimento na web e que a PROCAMEDURGSUS-ASSIAPLI tenha seus devidos recursos internacionais pra usar em benefício do nosso bom desenvolvimento e desempenho financeiro próprio doados em pró da carismática atenção ao novos developrs e programadores a ser contratados.
![IMG_20171130_002943272](https://user-images.githubusercontent.com/47190460/198848578-0f4b6525-2ddd-4474-883f-180091ddfcd8.jpg)
![IMG_20171130_003010838](https://user-images.githubusercontent.com/47190460/198848580-f182f4bd-22b5-4bec-9386-f8feb42a7120.jpg)

**Comment by argzdev** [comment]
Using google translate:
> I Pedro Ferreira Morais, owner of PROCAMEDURGSUS-ASSIAPLI, have been insisting a lot on positively leveraging our performance since we are on github.com and in countries with good performance on the web. But I let you rethink how you could support and work remotely at https://App.vc/pramed-ASSIAPLI#/home with the collaboration of cloud google.com and AdSense, firebase together with Google play products, so that developrs coud and clandestine developers of financial institutions of banks or stockbrokers and B3.com or team hinder our web development and that PROCAMEDURGSUS-ASSIAPLI has its due international resources to use for the benefit of our good development and own financial performance donated in favor of charismatic attention to new developers and programmers to be hired.

This seems more like an advertisement/spam. I'll close this issue now.

**Comment by ASSIAPLI** [comment]
Eu Pedro Ferreira Morais da ASSIAPLIg quero fazer card bônus de valor $25dolares e vender 7 vezes o valor para 7pessoas,  descontando 10% para os meus investimentos, mais 3% de desconto de imposto que dá igual a 13% descontado em cima do valor $175 dólares total. Mas atenção dos valores a combinar com clientes de $25 a$50 Dólares cada clientes.  Esse meu projeto de cash negócio investimento para com o cidadão que aderir ao projeto pagando o valor com as taxas e imposto mencionado. Pegando o plano desenvolvimento 5 em 6+1 para não sair totalmente gratuito eu desenvolvedor 2 card cash do desenvolvimentoEconomicoIndividual.
![‪+55 21 98110-4812‬ 20170810_181716](https://user-images.githubusercontent.com/47190460/203850250-349d8fa0-8f81-4226-b00c-b387a1d8a3f5.jpg)
PROCAMEDURGSUS-ASSIAPLI em ação e desenvolvimento web.[https://m.app.vc/procamedurgsus-assiapli#/auth2.0](https://m.app.vc/pramed-ASSIAPLI#/home)

**Comment by ASSIAPLI** [comment]
Muito investimento e criatividade para quem quer ganhar algumas porções de dólares. Qual quer dúvida é só enviar e-mail para meu endereço MSM ou e-mail mesmo.
