### ISSUE TITLE
HTTPS://M.APP.VC/PRAMED-ASSIAPLI#/AUTH2.0

### ISSUE THREAD

**Issue by ASSIAPLI** [firebase/firebase-android-sdk#4261]
Iniciação de um desenvolvimento https://pwa.app.vc/pramed-ASSIAPLI#/auth 2.0 procurar medir o desenvolvimento na web e analisar o pôr quê dos ERRO. 
![‪+55 21 98110-4812‬ 20170810_181716](https://user-images.githubusercontent.com/47190460/198849201-ebe3b47d-f193-4361-b175-1bb8275ca98e.jpg)

### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Good day, I'm not sure what the issue here is. Could you file a new issue with the details on the template so we can assist you further? Thanks!
