### ISSUE TITLE
Exception java.lang.IllegalArgumentException: com.companyname.*: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by anji22** [firebase/firebase-android-sdk#4263]
Hi ,

We have upgraded the Android API Level 30 to API Level 31 to support the Android 12 Version in Xamarin Project.
SDK Versions:
Xamarin Forms:5.0.0.2401
Xamarin.Firebase.Messaging:71.1740
Xamarin.Android SDK-13.0.0

In the production we are getting the below issue even we add the Mutable FLAG'S.

Exception java.lang.IllegalArgumentException: com.companyname.*: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
  at android.app.PendingIntent.checkFlags (PendingIntent.java:375)
  at android.app.PendingIntent.getActivityAsUser (PendingIntent.java:464)
  at android.app.PendingIntent.getActivity (PendingIntent.java:444)
  at android.app.PendingIntent.getActivity (PendingIntent.java:408)
  at com.google.firebase.messaging.zza.zzh
  at com.google.firebase.messaging.FirebaseMessagingService.zzd
  at com.google.firebase.iid.zzg.run
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at com.google.android.gms.common.util.concurrent.zza.run (com.google.android.gms:play-services-basement@@17.6.0:2)
  at java.lang.Thread.run (Thread.java:1012)

we added the FLAG_IMMUTABLE for our PendingIntents see below
if (Build.VERSION.SdkInt >= BuildVersionCodes.S)
                {
                    
                    pendingIntent = PendingIntent.GetActivity(CrossCurrentActivity.Current.AppContext,
                                                             FormsActivity.NOTIFICATION_INTENT_ID,
                                                             intent,
                                                             PendingIntentFlags.Immutable);
                }
                else
                {
                  
                    pendingIntent = PendingIntent.GetActivity(CrossCurrentActivity.Current.AppContext,
                                                             FormsActivity.NOTIFICATION_INTENT_ID,
                                                             intent,
                                                             PendingIntentFlags.OneShot);
                }

Could you please help us to resolve this issue in ASAP.

**Comment by argzdev** [comment]
Hi @anji22, thanks for reporting. I noticed two things: It seems that the version you're using is old. Looking at NuGet, the current stable version is [Xamarin.Firebase.Messaging v123.0.8](https://www.nuget.org/packages/Xamarin.Firebase.Messaging/). Also could you file the issue in the official [xamarin/GooglePlayServicesComponents/](https://github.com/xamarin/GooglePlayServicesComponents/issues) repo? They'll be able to assist you better with xamarin related issues.

That said, I'll close this issue now.
