### ISSUE TITLE
[Crashlytics] Exception message masking API

### ISSUE THREAD

**Issue by mkeeda** [firebase/firebase-android-sdk#4264]
## What feature would you like to see?
I need a safe crash report excluded user data for privacy.

Crashlytics collects thrown exceptions and stack traces. We can check messages in exceptions on Firebase console.
Exceptions include any data and we can not predict in advance what the message. If exception messages include sensitive user data (ex. password), we can currently get the data although we don't intend it.
Thrid perty library codes sholud be especially careful because there includes codes that we don't check. For example, when a crash happen by a network connection library and the library dumps sending payload to a error object, then Crashlytics send this payload to Firebase backend server. If the payload has user password of sign in, we know the password as a result.

So, Crashlytics should have a exception message masking feature to exclude senditive user data for privacy before send backend servers.

## How would you use it?
The app developer provides an exception message masking strategy for the Crashlytics SDK.
If you want to mask all messages, you can write using `AllMaskStrategy` below the code,

```kotlin
// Java
FirebaseCrashlytics.getInstance().setMaskingStrategy(new AllMaskStrategy());

// Kotlin
Firebase.crashlytics.setMaskingStrategy(AllMaskStrategy())

throw RuntimeException("message!")
```

Crash report in Firebase console
```
Fatal Exception: java.lang.RuntimeException: ********
       at com.example.crashlyticstest.ComposableSingletons$MainActivityKt$lambda-2$1$1.invoke(MainActivity.kt:36)
       at com.example.crashlyticstest.ComposableSingletons$MainActivityKt$lambda-2$1$1.invoke(MainActivity.kt:34)
       at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
       at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
```

Also, app developers can provide a custom masking rule for exception message using a lambda or `ThrowableMessageMaskingStrategy` interface.
For example,

```kotlin
// Java
FirebaseCrashlytics.getInstance().setMaskingStrategy(originalMessage -> {
    if (originalMessage != null) {
        return originalMessage.replaceAll("[0-9]{4}-[0-9]{4}", "xxxx-xxxx");
    } else {
        return null;
    }
});

// Kotlin
Firebase.crashlytics.setMaskingStrategy { originalMessage ->
    originalMessage?.replace(
        regex = "[0-9]{4}-[0-9]{4}".toRegex(),
        replacement = "xxxx-xxxx"
    )
}

// or
class PhoneNumberMaskStrategy : ThrowableMessageMaskingStrategy {
    override fun getMaskedMessage(originalMessage: String?): String? {
        return originalMessage?.replace(
            regex = "[0-9]{4}-[0-9]{4}".toRegex(),
            replacement = "xxxx-xxxx"
        )
    }
}
Firebase.crashlytics.setMaskingStrategy(PhoneNumberMaskStrategy())

throw RuntimeException("Phone number: 1234-1234")
```

Crash report in Firebase console
```
Fatal Exception: java.lang.RuntimeException: Phone number: xxxx-xxxx
       at com.example.crashlyticstest.ComposableSingletons$MainActivityKt$lambda-2$1$1.invoke(MainActivity.kt:36)
       at com.example.crashlyticstest.ComposableSingletons$MainActivityKt$lambda-2$1$1.invoke(MainActivity.kt:34)
       at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
       at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
```

`NoMaskStrategy` by default.

```java
public class NoMaskStrategy implements ThrowableMessageMaskingStrategy {
    @Nullable
    @Override
    public String getMaskedMessage(@Nullable String originalMessage) {
        return originalMessage;
    }
}
```

## Implementation
I have implemented this feature.
PR https://github.com/firebase/firebase-android-sdk/pull/4211

**Comment by argzdev** [comment]
Hi @mkeeda, thank you for taking the time and effort for filing this feature request, this sounds like a well thought out idea. I'll inform our engineers and see what they think about this.

**Comment by mkeeda** [comment]
@argzdev 
Thank you for reply.
Do you have any questions or opinions about this issue?
Is there anything I should do to get firease team to review my PR #4211 ?

**Comment by mrober** [comment]
Hi @mkeeda thanks for this! I really like this idea! Let me bring it to our PM and I will get back to you.

**Comment by mrober** [comment]
@mkeeda I brought it to our PM and he agrees. I would like to move forward with this. Because this would be an API change, it requires some internal process for us to go through first. We also need to keep the iOS SDK in sync. So let me get that process started, and I will review your PR. Thanks!

**Comment by mkeeda** [comment]
@mrober 
Thank you, I'm so happy to approve my request!

**Comment by mrober** [comment]
We have this feature request logged internally.
