### ISSUE TITLE
Firebase App Distribution Gradle Plugin is unfriendly to extension through custom plugins

### ISSUE THREAD

**Issue by sampengilly** [firebase/firebase-android-sdk#4265]
I currently use the Firebase App Distribution gradle plugin to publish internal builds for a collection of apps to Firebase App Distribution. There are some challenges that I have in our environment. The main one is that the FAD gradle plugin requires service credentials to be provided as a File. Whereas the CI infrastructure that my apps run on make it difficult to store secret files, we can store secret strings easily.

Because of this, I have written a gradle plugin of my own with a task that takes the service credentials secret string and writes it to the temp build files. By configuring each `UploadDistributionTask.serviceCredentialsFile` with the output of my task, it ensures that my task is run before `UploadDistributionTask` and the credentials are available. Creating this plugin means each of my apps can apply it and get common configuration for App Distribution.

Version 3.1.0 of the App Distribution gradle plugin has just made `UploadDistributionTask` package-private. Which means I can no longer configure it with my written credentials filepath. The task was also not properly honouring Gradle lifecycle previously, if you simply wired the `serviceCredentialsFile` property up to another gradle property inside `configureEach {}` without doing so in an `afterEvaluate` block the App Distribution gradle plugin would later overwrite that.

The source code for the App Distribution gradle plugin has not been made available so I can't check the specifics of what's going on. Could I ask that the plugin be updated to better make use of Gradle's lazy configuration APIs and to be more friendly to extension from other plugins. 

If `UploadDistributionTask` is going to remain package-private, could the `AppDistributionExtension` interface be updated to take Gradle `Property` types rather than primitives? That way custom plugin developers can wire that configuration up to the output of a task and Gradle will handle the ordering. Could the app distribution plugin also be made open source like the rest of Firebase's SDKs?

**Comment by argzdev** [comment]
Thank you for taking the time and effort in writing this, @sampengilly. This does sound like a very reasonable use case. I'll notify our engineers and see what we can do here.

**Comment by argzdev** [comment]
Hi @sampengilly, our engineers will be shipping a new version that will make the task public again. Meanwhile, please use a previous version of the plugin. Also thank you very much for the suggestions, we will consider looking into the open source option in the future.

**Comment by kaibolay** [comment]
[Version 3.1.1 of the App Distribution Gradle plugin](https://maven.google.com/web/index.html#com.google.firebase:firebase-appdistribution-gradle:3.1.1) (which makes `UploadDistributionTask` public again) has been released. Sorry for the inconvenience.

We're working on making the plugin open-source.
