### ISSUE TITLE
FA Issue with "screen_view" event  manual / automatic

### ISSUE THREAD

**Issue by migcol** [firebase/firebase-android-sdk#4276]
Hi, we are experimenting some issues with Event SCREEN_VIEW

1.    compileSdkVersion 33 and updated firebase bom to 31.0.2    analytics  21.2.0    tagmanager:18.0.2

2. My code didnt change : 
```
if (mFirebaseAnalytics == null) {
    mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);
}
Bundle bundle = new Bundle();
bundle.putString(FirebaseAnalytics.Param.SCREEN_NAME, "Loading");   
bundle.putString(FirebaseAnalytics.Param.SCREEN_CLASS, "LoadingActivity"); 
mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
![image](https://user-images.githubusercontent.com/25180960/199751320-b06c4ca0-636f-428c-883f-860cf7120e62.png)
```

**We are getting a infinite loop for : 
```
Logging screen view with name, class: null, LoadingActivity
Screen exposed for less than 1000 ms. Event not sent. time: 427**
```

3. Our issue is with automatic / manual  screen_view  event

Thanks

**Comment by argzdev** [comment]
Thanks for reporting, @migcol. I'm unable to replicate the same behavior you're experiencing with a clean project. Could you share the steps to reproduce this behavior? Also does this issue happen on prior versions?

Any chance you could share a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? That'll greatly help us investigating your issue. Thanks!
