### ISSUE TITLE
PendingIntent.checkFlags: com.google.firebase:firebase-messaging@@20.1.6

### ISSUE THREAD

**Issue by rudy8530** [firebase/firebase-android-sdk#4296]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1 Patch 2
  * Firebase Component: Firestore,  Analytics, Messaging, Dynamic-Links, Storage, UIStorage, CrashLethics
  * Component version: firebase-messaging(20.1.6), firebase-analytics-ktx(17.5.0), firebase-dynamic-links-ktx(20.1.1), firebase-storage-ktx(19.1.1), firebase-analytics(17.2.3), firebase-crashlytics(17.2.2), firebase-ui-storage(6.2.0)
  * Versions: compileSdkVersion = 31, minSdkVersion = 21, targetSdkVersion = 31 
 
#### Steps to reproduce:

- Create an application with the compile, min and target sdk versions, below.
- Implement the firebasse-messaging library (20.1.6)
- App your app on a Samsung devices (Galaxy A41, Galaxy A13, Galaxy S20 FE, Galaxy A71, Galaxy S22, Galaxy S10, Galaxy A32 5G, Galaxy A42 5G, Galaxy S20 FE, Galaxy S10e, Galaxy A12, Galaxy A21s, Galaxy Note10, Galaxy A32)
- The app crash randomly on these users devices

#### Tried and tested solution
- Used firebase Bom and messaging-ktx (KO)
- Update firebase-messaging version to 23.1.0 (KO)
For this two solutions I have an error message:
```
Type com.google.firebase.iid.FirebaseInstanceIdReceiver is defined multiple times
```

#### Relevant Code:
MainActivity.kt
```
FirebaseInstanceId.getInstance().instanceId
                .addOnCompleteListener(OnCompleteListener { task ->
                    if (!task.isSuccessful) {
                        Timber.w("getInstanceId failed")
                        return@OnCompleteListener
                    }

                    // Get new Instance ID token
                    val token = task.result.token
                    token.let {
                        userViewModel.token = token
                        userViewModel.updateFirestoreUser(hashMapOf("token" to token))
                    }
                })
```
<img width="946" alt="Capture d’écran 2022-11-09 083817" src="https://user-images.githubusercontent.com/23360861/200792961-c37b218b-9e52-4b5d-b496-fb4fa7142395.png">
<img width="952" alt="Capture d’écran 2022-11-09 083838" src="https://user-images.githubusercontent.com/23360861/200792966-846d0e7b-f638-4b65-b139-b264ab15cfd5.png">

**Comment by gsakakihara** [comment]
This happens if you're using an older version of the firebase-iid library along with a more recent version of firebase-messaging. We recommend that you upgrade to using the FirebaseMessaging APIs as FirebaseInstanceId is deprecated, but if that's not possible, you may be able to fix this by adding an explicit dependency on the most recent version of firebase-iid (21.1.0).

**Comment by rudy8530** [comment]
Thanks @gsakakihara. 
I increase the firebase messaging and added firebase-iid. I not even see anymore this issue on crashlethics dashboard.
Thanks :)

**Comment by argzdev** [comment]
Hi @rudy8530, thanks for confirming the fix. That said, I'll close this issue now.
