### ISSUE TITLE
`FirebaseVisionImage` cannot handle bitmaps when configuration is `HARDWARE`

### ISSUE THREAD

**Issue by funct7** [firebase/firebase-android-sdk#430]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4
  * Firebase Component: ML Kit (Database, Firestore, Storage, Functions, etc)
  * Component version: 19.0.3

#### Steps to reproduce:

The library will fail when a `Bitmap` instance with configuration `Bitmap.Config.HARDWARE` is used to create a `FirebaseVisionImage` instance, with the factory method `FirebaseVisionImage.fromBitmap(Bitmap)`.

The error:
`A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xc919d000 in tid 11059 (FirebaseMLHandl), pid 10959 (...)`

#### Relevant Code:

```kotlin
// This fails
val image = FirebaseVisionImage.fromBitmap(bitmap)
// This is fine
//val image = FirebaseVisionImage.fromFilePath(context, uri)

FirebaseVision.getInstance().visionBarcodeDetector.detectInImage(image)
    .addOnSuccessListener { Log.d(TAG, "$it") }
    .addOnFailureListener { Log.d(TAG, "$it") }
```

As in the code above, when using `FirebaseVisionImage.fromBitmap(Bitmap)` the error occurs.

In order to get a bitmap with `Bitmap.Config.HARDWARE`:  
```kotlin
val source = ImageDecoder.createSource(context.contentResolver, uri)
ImageDecoder.decodeBitmap(source)
```

**Comment by Shirane85** [comment]
i'm  facing the same issue when user is picking an image for his device. I saw a solution on SOF suggesting to convert the bitmap to Bitmap.Config.ARGB_888. Is this the correct solution, does this can affect image quality and then ML processing quality as well?

**Comment by funct7** [comment]
Setting `allocator` to `ImageDecoder.ALLOCATOR_SOFTWARE` helped in my case

**Comment by Bild78** [comment]
I was wondering how through KB93341 I received info then saw where yall
talked about that link was not good how would you have it and how did a
text I sent at 615pm Monday and up in the info your creativeting she's my
fiance were about to call it quits if she's got anything g to do with this
can you explain anything about this event.

**Comment by vitrol4** [comment]
I fix this bug changing class YuvToRgbConverter to another code.

**Comment by Gnzlt** [comment]
> I fix this bug changing class `YuvToRgbConverter` to another code.

I face the same issue, which code you mean?

**Comment by vitrol4** [comment]
@Gnzlt try it --> https://github.com/android/camera-samples/commit/35396a9d2df42fa796db7592f333cd29c6358c4c#diff-d61c12f7809dd0b2acf6a56999eb9b7d93664f9332a30ed3022534ed68b57651
else i paste my code here.

**Comment by vkryachko** [comment]
Moved issue to https://github.com/googlesamples/mlkit/issues/226
