### ISSUE TITLE
I can't receive FCM push messages when my phone locks the screen for more than 30 minutes

### ISSUE THREAD

**Issue by warrenToday** [firebase/firebase-android-sdk#4317]
I integrate firebase. When my application is in the foreground, background or directly killed, I can normally receive push messages. When I kill the application, I can also receive push messages within 20 minutes of locking the screen. But 30 minutes after locking the screen, I can no longer receive messages until I unlock the phone screen.

I have three mobile phones, Pixel2, Pixel4 and Galaxy Note 10+. Their systems are Android11 and Android12. These three mobile phones all have the same problem. After the screen is locked for 30 minutes, no push mes

**Comment by argzdev** [comment]
Hi @warrenToday, thanks for reporting. I think the issue you might be experiencing is due to the priority level of the message. Could you try setting it up using our [docs](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message) here, it should be something like this:

```
{
  "message":{
    "topic":"subscriber-updates",
    "notification":{
      "body" : "This week's edition is now available.",
      "title" : "NewsMagazine.com",
    },
    "data" : {
      "volume" : "3.21.15",
      "contents" : "http://www.news-magazine.com/world-week/21659772"
    },
    "android":{
      "priority":"normal"
    },
    "apns":{
      "headers":{
        "apns-priority":"5"
      }
    },
    "webpush": {
      "headers": {
        "Urgency": "high"
      }
    }
  }
}
```

Let me know if this works. Thanks.

**Comment by warrenToday** [comment]
The push data can be received normally after being added to high priority. Thank you for your support

**Comment by warrenToday** [comment]
> Hi @warrenToday, thanks for reporting. I think the issue you might be experiencing is due to the priority level of the message. Could you try setting it up using our [docs](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message) here, it should be something like this:
> 
> ```
> {
>   "message":{
>     "topic":"subscriber-updates",
>     "notification":{
>       "body" : "This week's edition is now available.",
>       "title" : "NewsMagazine.com",
>     },
>     "data" : {
>       "volume" : "3.21.15",
>       "contents" : "http://www.news-magazine.com/world-week/21659772"
>     },
>     "android":{
>       "priority":"normal"
>     },
>     "apns":{
>       "headers":{
>         "apns-priority":"5"
>       }
>     },
>     "webpush": {
>       "headers": {
>         "Urgency": "high"
>       }
>     }
>   }
> }
> ```
> 
> Let me know if this works. Thanks.

The push data can be received normally after being added to high priority. Thank you for your support
