### ISSUE TITLE
Unable to upload file to emulator

### ISSUE THREAD

**Issue by marschwar** [firebase/firebase-android-sdk#4362]
### Environment

  * Android Studio version: 2021.3.1 Patch 1
  * Firebase Component: Storage (20.1.0), Firebase Emulator (11.16.1)

### Problem
Uploading a file to the emulator results in the message `Caused by: java.lang.IllegalStateException: Unable to obtain an upload URL.` 

It seems the UploadTask expects the server to send a `X-Goog-Upload-URL` header but the emulator sends `x-goog-upload-url`. 

The SDK should extract response headers without being case sensitive.

#### Steps to reproduce:

* Start the emulator
* Create a FirebaseStorage instance with useEmulator(host, port)
* put a local file and wait for the result

#### Relevant Code:

```kotlin
val storage = FirebaseStorage.getInstance(bucketUrl).apply { useEmulator("localhost", 9199) }
val fileRef = storage.reference.child(file.name)
fileRef.putFile(.await()
```

**Comment by argzdev** [comment]
Hi @marschwar. Please file issues in our [firebase-tools](https://github.com/firebase/firebase-tools/issues) for emulator related issues. Thanks!
