### ISSUE TITLE
Não a falta de compreensão e discernimento de vândalos maliciosos.

### ISSUE THREAD

**Issue by ASSIAPLI** [firebase/firebase-android-sdk#4367]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Resolvendo o problema para a compreensão e discernimento de vândalos maliciosos. 
![IMG_20171130_002943272](https://user-images.githubusercontent.com/47190460/203851411-331db204-96aa-4e38-80f4-5e2468559d96.jpg)
[Discernimento de compreensão das ações de vândalos maliciosos.](https://m.app.vc/pramed-ASSIAPLI#/home)

**Comment by argzdev** [comment]
This is a spam.
