### ISSUE TITLE
Remove Scope.LIBRARY_GROUP restriction on Blob <-> ByteString methods

### ISSUE THREAD

**Issue by Actine** [firebase/firebase-android-sdk#440]
## What feature would you like to see?

I don’t see why not make methods [Blob#toByteString()](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/Blob.java#L72) and [Blob#fromByteString()](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/Blob.java#L51) truly public API. `ByteString` is a very handy class for manipulating blob data, e.g. joining and splitting byte arrays.

## How would you use it?

One example where I’m using Blob over String is when I want to store encoded data.
I would use
```
Blob.fromByteString(ByteString.copyFrom(iv).concat(ByteString.copyFrom(encoded)))
```
to concatenate the initialization vector and AES-encoded message into one field, and then use
```
ByteString byteString = titleBlob.toByteString();
byte[] iv = byteString.substring(0, 16).toByteArray();
byte[] data = byteString.substring(16).toByteArray();
```
to split it.

**Comment by mikelehen** [comment]
@Actine Thanks for the feedback!

The com.google.protobuf.ByteString methods actually exist as an implementation detail to allow us to convert Blobs into protobuf messages for communicating with the backend.  Although unlikely, it's technically possible that in the future we'd end up using a different protocol with the backend and no longer need / use com.google.protobuf.ByteString. So we didn't want to make it part of the public API.  Additionally, having only a single way to interact with a Blob (fromBytes() and toBytes()) results in a simpler API and avoids developers having to make an extra decision about which method is best for them.

In the meantime, I assume you could do something like:
```
byte[] bytes = titleBlob.toBytes();
byte[] iv = Arrays.copyOfRange(bytes, 0, 16);
byte[] data = Arrays.copyOfRange(bytes, 16, bytes.length);
```

While a bit more typing, hopefully this is a suitable solution?  If we get more feedback we may reconsider exposing ByteString as part of the public API, but for now I think we'd prefer to keep the public surface as minimal as possible.  Thanks for the feedback though. We'll keep an eye out for other people requesting this.

**Comment by Actine** [comment]
Alright, fair enough.

Guess for array concatenation the only way is to do it all manually via `System.arraycopy()`. One could use `ArrayUtils.concatByteArrays(byte[]...)`, from gms.common.util, but the code supporting variable number of arrays looks like unnecessary overhead.

**Comment by wilhuff** [comment]
Alternatively, you're welcome to declare your own dependency on `ByteString` and use it on `Blob.toBytes`. While this would result in an extra copy it does keep our implementation details from getting tangled up in your details.
