### ISSUE TITLE
Outdated firebase-inappmessaging-display

### ISSUE THREAD

**Issue by stari4ek** [firebase/firebase-android-sdk#441]
Looks like open-sourced firebase-inappmessaging-display is left behind released one 17.1.1
```
implementation('com.google.firebase:firebase-inappmessaging:17.0.3') {
    exclude group: 'com.google.firebase', module: 'firebase-common'
  }
```

**Comment by stari4ek** [comment]
There is 17.2.0 already.

**Comment by stari4ek** [comment]
July 12, 2019: 18.0.2 released

still no sources here

**Comment by aguatno** [comment]
Hi @stari4ek sorry for the delay. I checked the previous [pull request](https://github.com/firebase/firebase-android-sdk/pull/784) and it looks like the inappmessaging-display has already been published. Let me know if this is not the case.

I am going to close this issue. If you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.
