### ISSUE TITLE
FirebaseCrashlytics.getInstance().log not showing up in Firebase crashes on Oculus Quest

### ISSUE THREAD

**Issue by BattleAxeVR** [firebase/firebase-android-sdk#4451]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Dolphin, 2021.3.1 Patch 1, built September 29, 2022
  * Firebase Component: FirebaseCrashlytics
  * Component version: (com.google.firebase:firebase-bom:31.1.1)

### [REQUIRED] Step 3: Describe the problem

I followed the instructions here to add custom logs to track what led up to a crash in my Quest VR app (android, standalone), but the logs aren't showing up. I had to create and initialize a FirebaseApp and FirebaseCrashlytics instance  in OnCreate of my Activity.

Everything works except I see no custom logs. When I followed the instructions for sending a test crash via a runtime exception, the string in the exception did show up in the crash logs. But I need all logs that led up to the crash so I can deduce what the client is doing, as mentioned here:

https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#add-logs

#### Steps to reproduce:

I just run my app, then when it crashes, I never see any logs alongside the crash dump, they're just empty.

#### Relevant Code:

in onCreate I added:

 try {
            FirebaseApp.initializeApp(this);
            mFireBaseAppInstance = FirebaseApp.getInstance();
            mFireBaseAnalyticsInstance = FirebaseCrashlytics.getInstance();

            if (mFireBaseAnalyticsInstance != null)
            {
                String userID = getUserID();
                mFireBaseAnalyticsInstance.setUserId(userID);
            }    
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }

This is what I call to try and add custom logs to firebase. No exceptions or errors occur, only the logs are never seen in crashes

   
    public void sendLogToFireBase(String message)
    {
        // https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#add-logs

        try {
            if (mFireBaseAnalyticsInstance != null)
            {
                //Log.v(TAG, "sendLogToFireBase message = " + message);
                mFireBaseAnalyticsInstance.log(message);
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

**Comment by argzdev** [comment]
Thanks for reporting, @BattleAxeVR. Just to confirm, you don't see anything under the Logs tab from the Firebase console, right? I think if you're able to receive crashes on the Firebase console, then Crashlytics should be able to add custom logs as well. I'm just guessing here but perhaps the thread path isn't traversing through the `sendLogToFireBase` before crashing? 

Also were you able to see the `userId` in your Firebase console after setting this from your `mFireBaseAnalyticsInstance.setUserId(userID)`?

<img width="1231" alt="Screen Shot 2022-12-15 at 7 17 09 PM" src="https://user-images.githubusercontent.com/93124282/207846130-8e538784-bb95-455c-ad50-1c02d46f48d1.png">

**Comment by BattleAxeVR** [comment]
Thanks for the response! I put in a test user ID and see it in the data tab:

![image](https://user-images.githubusercontent.com/11604039/207992239-74dc40d3-e404-4872-a8ab-671e193d8709.png)

Here are the logs for that exact bunch of 8 crashes I spawned in my test scenario with this same user ID:

![image](https://user-images.githubusercontent.com/11604039/207992545-ae69f351-1c68-4d7a-bdce-f18bf6989d48.png)

screen_view is showing nothing. I am 100% sure when I originally integrated this app and threw a runtime exception deliberately (to simulate a crash) with "Test Crash" it showed up in these logs.

**Comment by BattleAxeVR** [comment]
Although, I didn't add any keys, are those necessary? Pardon me if I didn't configure this properly.

**Comment by BattleAxeVR** [comment]
I think the problem may be that our users' crashes aren't runtime exceptions, per se, but either Java timeout exceptions or C++ crashes. Actually, I'm not getting C++ side crashes at all unless I manually / deliberately trigger them in my test app, but I need those to work as well (later). 

I can't use the code you provided "as is" as my app is based on NativeActivity and I can't spawn a button or view like this, it won't show up. My app is a VR app based on JNI / C++ / native OpenXR and the java side is only handling the webview creation and drawing, which is rendered to an offscreen hardware buffer backed EGL surface texture. This webview drawing is what's causing timeout exceptions when certain things happen (which I'm not sure of), but debugging it is very hard to do remotely without logs leading up to the crashes. Every example I see here of Firebase logs seems to expect a runtime exception being thrown. I added try / catch blocks around my critical section that's throwing the timeouts but now I'm wondering if I should re-throw a new runtime exception in the catch blocks. I'll try that and work back from something that works until I get it. I'll let you know if this sorts it out.

Ideally, what would be best is a way to automatically just store all Android ADB logs (or above a certain severity, like debug or warning) in Firebase, as this would also catch system errors. The way I'm doing it now is pushing to Firebase the same log strings I'm also pushing to ADB logs, but that won't get me system errors which I would ideally also need. 

Is there a way to simply enable all android logs (or above a severity threshold) in Firebase? If not I guess I can get by with only app-originated logs and forego system errors too, but it's not ideal.

**Comment by argzdev** [comment]
> I'm wondering if I should re-throw a new runtime exception in the catch blocks

You could try recording [non-fatal exceptions](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#log-excepts) instead of re-throw exceptions in the catch blocks.

Relevant code:
```
try {
    methodThatThrows();
} catch (Exception e) {
    FirebaseCrashlytics.getInstance().recordException(e);
    // handle your exception here
}
```

> Is there a way to simply enable all android logs (or above a severity threshold) in Firebase?

Not that I know of.

I appreciate you explaining these details to us. Unfortunately, since Oculus Quest is not officially supported by Firebase as of the moment, we expect this not to work as expected. The maintainers of this repository have little to no Oculus Quest knowledge and cannot assist with this sort of debugging. I'll try and consult our engineers to see what we can do here. I'm sorry that we can't be of more assistance.

**Comment by BattleAxeVR** [comment]
Since my crashes are uploading and I see the dummy test user ID, I think the logs should work, even on Quest since it runs on fairly standard Android (in fact 2D android apps run on it without any issue or code changes required)

**Comment by mrober** [comment]
Sorry I don't have a Quest to try to reproduce your issue on. But I have a hunch: Can you try adding a delay between when you set the custom keys, logs, etc... and the test crash? If that works, please let me know. If it still does not work, I will investigate more.

**Comment by BattleAxeVR** [comment]
Hey just wanted to say, I got it working by starting over clean and using non-fatal exceptions THEN adding the logs. That was a big weird, but I guess it makes sense. Anyway, I'm happy it's sorted out. cheers.
