### ISSUE TITLE
OTP code is received OnVerificationStateChangedCallbacks not respond

### ISSUE THREAD

**Issue by Sotatek-MinhPham** [firebase/firebase-android-sdk#4461]
#### Steps to reproduce:

I implementing Firebase Phone Authenticate feature and I got problem on production release.
Sometime when user send request to get OTP code by PhoneAuthProvider.verifyPhoneNumber(options), PhoneAuthProvider.OnVerificationStateChangedCallbacks was never fired even the sms was sent successful. I couldn't reproduce this case but my client from Japan and Philippines reported this issue.
I'm looking forward to your help to know the reason why this happens and the solution for this issue. Thank you!

#### Relevant Code:

```

callbackVerifyPhoneNumber =
            object : PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                override fun onCodeAutoRetrievalTimeOut(p0: String) {
                    ...
                }

                override fun onVerificationCompleted(credential: PhoneAuthCredential) {
                    ...
                }

                override fun onVerificationFailed(e: FirebaseException) {
                    ...
                }

                override fun onCodeSent(
                    verificationId: String,
                    token: PhoneAuthProvider.ForceResendingToken
                ) {
                    ...
                }
            }

val options = PhoneAuthOptions.newBuilder(Firebase.auth)
            .setPhoneNumber(phoneNumber)
            .setTimeout(1L, TimeUnit.SECONDS)
            .setActivity(activity)
            .setCallbacks(callbackVerifyPhoneNumber)
            .build()
        PhoneAuthProvider.verifyPhoneNumber(options)

```
The old one [2475](https://github.com/firebase/firebase-android-sdk/issues/2475) was ignored so I created a new ticket here

**Comment by argzdev** [comment]
HI @Sotatek-MinhPham, thanks for reporting. I saw one of our engineers replied to #2475.

> Based on the symptoms, it is very likely an network issue where the request has reached the server but the response never came back to the Android SDK. Does any other callbacks fire then? https://developers.google.com/android/reference/com/google/firebase/auth/PhoneAuthProvider.OnVerificationStateChangedCallbacks#public-method-summary make sure to check all four -- `onVerificationCompleted`, `onVerificationFailed`, `onCodeSent` and `onCodeAutoRetrievalTimeOut` (the last one seems missing from the code snippet in your screenshot). If you can get a reliable reproduction where none of them fires, please let us know and we can look further into this.

I believe yuchenshi's advice would be helpful. Perhaps you can use something like [Crashlytics](https://firebase.google.com/docs/crashlytics) to track [non-fatal exceptions](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#log-excepts) to see what's causing these issues in the four mentioned methods. That'll give us a hint where the issue lies. You can add the logs here once you get an update. I'll mark this as `needs-info` for now.
