### ISSUE TITLE
NotificationCompas Not adapted to older keys (custom voice not played)

### ISSUE THREAD

**Issue by wuzhxyl** [firebase/firebase-android-sdk#4485]
@Nullable
  public String getSoundResourceName() {
    String sound = getString(MessageNotificationKeys.SOUND_2);
    if (TextUtils.isEmpty(sound)) {
      sound = getString(MessageNotificationKeys.SOUND);
    }
    return sound;
  }

should be as follows:

public String getSoundResourceName(Bundle bundle) {
		String sound = getString(Constants.MessageNotificationKeys.SOUND_2);
		if (TextUtils.isEmpty(sound)) {
			sound = getString(Constants.MessageNotificationKeys.SOUND);
		}

		if (TextUtils.isEmpty(sound)) {
			sound = getString(keyWithOldPrefix(Constants.MessageNotificationKeys.SOUND_2));
		}

		if (TextUtils.isEmpty(sound)) {
			sound = getString(keyWithOldPrefix(Constants.MessageNotificationKeys.SOUND));
		}

		return sound;
	}

**Comment by argzdev** [comment]
Hi @wuzhxyl, thanks for reporting. It seems like your code doesn't use Firebase, so I'm not sure what the issue is here. Could you file a new issue with our template? The details you provide is essential for an initial investigation. Thanks!
