### ISSUE TITLE
OnChildChanged and onChildRemoved not getting called at app start

### ISSUE THREAD

**Issue by metinvio** [firebase/firebase-android-sdk#4497]
* Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
  * Firebase Component: Firebase Realtime DB
  * Component version: 
implementation platform('com.google.firebase:firebase-bom:29.0.2')
implementation 'com.google.firebase:firebase-database-ktx'

On iOS, if you change or remove data from firebase and start the app, onChildChanged or onChildRemoved are getting called delivering the changed/removed data. On Android the methods are only called when the app is running but not after start. (Why I need this: It's crucial for syncing eg for users using multiple devices). This is my code:

```
transactionsRef.child(depotName).addChildEventListener(object : ChildEventListener {
                    override fun onChildAdded(snapshot: DataSnapshot, previousChildName: String?) {
                        // Handle event here } // Other override methods, such as onChildChanged, onChildRemoved, etc. })
                        println("onChildAdded : ${snapshot.key}}")
                    }

                    override fun onChildChanged(snapshot: DataSnapshot, previousChildName: String?) {
                        //TODO("Not yet implemented")
                        println("onChildChanged : ${snapshot.key}}")

                    }

                    override fun onChildRemoved(snapshot: DataSnapshot) {
                        //TODO("Not yet implemented")
                        println("onChildRemoved : ${snapshot.key}}")

                    }

                    override fun onChildMoved(snapshot: DataSnapshot, previousChildName: String?) {
                        //TODO("Not yet implemented")
                    }

                    override fun onCancelled(error: DatabaseError) {
                        //TODO("Not yet implemented")
                    }
                })```

**Comment by argzdev** [comment]
Hello @metinvio, thanks for reporting.

> the methods are only called when the app is running but not after start.

Just to clarify, do you mean you'd like to receive `onChildChanged` or `onChildRemoved` at the beginning of app start? e.g.:
1. App is closed
2. make changes to the database (add or remove)
3. open app
4. app receives `onChildChanged` or `onChildRemoved`

**Comment by metinvio** [comment]
Hey @argzdev,

that's exactly what I was looking for. But we managed to find the solution. You only have to add below line to your application class or to the very beginning:

`Firebase.database(your_database_url_firebasedatabase.app).setPersistenceEnabled(true)`

**Comment by argzdev** [comment]
Hi @metinvio, I'm glad you were able to find the solution. Thanks for sharing this as well. I'm sure it'll be helpful for other developers that sees this in the future. That said, I'll close this issue now.
