### ISSUE TITLE
 Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds

### ISSUE THREAD

**Issue by Mukesh1133** [firebase/firebase-android-sdk#4517]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:   Android Studio Dolphin
  * Firebase Component:   Firestore
  * Component version:    Firestore:22.0.0

### [REQUIRED] Step 3: Describe the problem
When i switch my network connection from mobile data to wifi, I am unable to load data from firestore and when i checked the log i got the following message(Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds                                                                                               
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.) but when i switched back to mobile data it works fine.

A resource failed to call close. 
Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds                                                                                               
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

#### Steps to reproduce:
Switch the connection from mobile data to wifi.

#### Relevant Code:
The following code is here.

 DocumentReference documentReference = firestore.collection("user").document("tUJJzPXWDqD2KcStzF8s").

        documentReference.get().addOnSuccessListener(new OnSuccessListener<DocumentSnapshot>() {

            ArrayList<UserModel> userModel = new ArrayList<>();

            @Override
            public void onSuccess(DocumentSnapshot documentSnapshot) {

                if (documentSnapshot.exists()) {
                    String name = documentSnapshot.getString("First Name") + " " + documentSnapshot.getString("Last Name");
                    String age = documentSnapshot.getString("Age");
                    String injuryDetails = documentSnapshot.getString("Injury Details");

                    Log.d("TAG", "RESULT" + name);

                    userModel.add(new UserModel(name, age, injuryDetails));

                } else {
                    Toast.makeText(PatientListActivity.this, "Failed", Toast.LENGTH_SHORT).show();
                }

                patientListAdapter = new PatientListAdapter(userModel, PatientListActivity.this);
                binding.rvPatientList.setAdapter(patientListAdapter);

            }
        }).addOnFailureListener(new OnFailureListener() {
            @Override
            public void onFailure(@NonNull Exception e) {
                Toast.makeText(PatientListActivity.this, "Failed", Toast.LENGTH_SHORT).show();
            }
        });
  
[firebase loading issue 2.txt](https://github.com/firebase/firebase-android-sdk/files/10345179/firebase.loading.issue.2.txt)

```

**Comment by wu-hui** [comment]
Thanks for your report!

There are several things you can try:

1. Are you sure your wifi works when you are testing? It could be a wifi issue, or an Android issue when switching networks.
2. Can you try with a newer version of Firestore SDK? Anything 24+. We (or more precisely GRPC) have made some improvements around connectivity in the newer versions. They do not directly target network switch AFAIK, but it might be worth trying it out.
3. If none of the above worked for you, can you try turning debug logs, and send us the logs?

Thanks!
