### ISSUE TITLE
In-app messages not displayed when accepting permission on the second display

### ISSUE THREAD

**Issue by vladislav-t** [firebase/firebase-android-sdk#4575]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
  * Firebase Component: com.google.firebase:firebase-bom:30.4.1
  * Component version: com.google.firebase:firebase-inappmessaging-display

#### Steps to reproduce:

Open app

Tap on X or on the outside of the Notification pop-up

Tap on “Don’t allow“ btn

Meet the conditions for the pop-up to be displayed second time

Re-open the app

Tap on “Good“ btn from the notification pop-up

Tap on “Allow“ btn

Close the app

Send In-app message to this phone from 

Open app

Actual result: In-app message not displayed in the app

https://user-images.githubusercontent.com/13637332/213410763-c900c742-4706-479b-9f36-5d73dea3bd0f.mp4

**Comment by argzdev** [comment]
Hi @vladislav-t, thanks for reporting. There's a few things I noticed:
1. Could you try using the latest version of com.google.firebase:firebase-inappmessaging-display `20.2.0` and see if this is reproducible?
2. Also can you share a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of your issue? Or any code snippets?
3. From testing it seems that notification request whether allowed or not should not affect your app from receiving any inappmessages. Have you checked your logs if you receive messages from the backend? e.g. `Successfully fetched 1 messages from backend`
