### ISSUE TITLE
Firestore Emulator Android: Stream closed with status UNKNOWN

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-android-sdk#4606]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Flamingo | 2022.2.1 Beta 1 Build #AI-222.4459.24.2221.9471578
  * Firebase Component: Firestore, Cloud Functions
  * Component version: BOM 31.1.1

### [REQUIRED] Step 3: Describe the problem
Updating a data through a Cloud Functions emulator works, but it doesn't get updated in the Android app, it gets updated in the Web app though.

#### Steps to reproduce:
1. Connect an Android project with Firebase emulator
2. Create a listener to listen to a Firestore collection
3. Make changes to some data through cloud functions call
4. Data doesn't change at all. Created/inserted data gets displayed in the app, but updated data doesn't change.

Logs
```
Firestore                W  (24.4.1) [WatchStream]: (7552d15) Stream closed with status: Status{code=UNKNOWN, description=null, cause=null}.
Firestore                W  (24.4.1) [WatchStream]: (7552d15) Stream closed with status: Status{code=UNAVAILABLE, description=End of stream or IOException, cause=null}.
Firestore                W  (24.4.1) [WatchStream]: (7552d15) Stream closed with status: Status{code=UNKNOWN, description=null, cause=null}.
chatty                   I  uid=10084(id.co.appname) FirestoreWorker identical 575 lines
Firestore                W  (24.4.1) [WatchStream]: (7552d15) Stream closed with status: Status{code=UNKNOWN, description=null, cause=null}.
Firestore                W  (24.4.1) [WatchStream]: (7552d15) Stream closed with status: Status{code=UNKNOWN, description=null, cause=null}.
```

#### Relevant Code:

This is more of the emulator or SDK issue, so I can't give a code. It's just a normal listener with some queries.
I've tested the same query in Web platform and it works fine.

**Comment by risalfajar** [comment]
UPDATE:
Some people said to downgrade Android Studio Emulator version, tried that several times, doesn't work.
Switching from Android Studio Emulator to GenyMotion Emulator doesn't work, same problem.

**Comment by risalfajar** [comment]
UPDATE (FIXED):
So happy to found the culprit after hours of trying. The error occurs because I'm accidentally calling `order` on the same field twice. 🙇🏻‍♂️

Something like
```kotlin
val query = getQuery()
    .orderBy("created")
    .orderBy("created")
```

This could happen unnoticeably because I am using abstract class. I hope there will be meaningful logs though.

**Comment by argzdev** [comment]
Hi @risalfajar, glad you were able to resolve your issue. Thanks for posting the solution!
