### ISSUE TITLE
Pixel 4: java.io.IOException: e8.b: 17: API: DynamicLinks.API is not available on this device.

### ISSUE THREAD

**Issue by akrulec** [firebase/firebase-android-sdk#4611]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: N/A
  * Firebase Component: Android Firebase SDK
  * Component version: com.google.firebase:firebase-bom:30.5.0

#### Steps to reproduce:
Firebase crashlytics is showing the following error on a user with a Pixel 4:

`Non-fatal Exception: java.io.IOException: e8.b: 17: API: DynamicLinks.API is not available on this device. Connection failed with: b{statusCode=SERVICE_INVALID, resolution=null, message=null}`
 

#### Relevant Code:
firebaseAuth.signInWithEmailLink fails

**Comment by argzdev** [comment]
Thanks for reporting, @akrulec. Could you answer a few details below:

1. Do you have steps how to reproduce this issue?
2. Is this consistently reproducible?

**Comment by akrulec** [comment]
Firebase Crashlytics that is integrated into our application recorded this 7 times for a single user on Jan 29th. Which means that the user was unable to log into our app, so not ideal.

**Comment by argzdev** [comment]
Hi @akrulec, could you answer the questions above? Also can you share with us the Firebase products that you're using?
