### ISSUE TITLE
Firebase Crashlytics does not account for newline characters when calling `log()`

### ISSUE THREAD

**Issue by russellwheatley** [firebase/firebase-android-sdk#4617]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 1  

  * Firebase Component: Crashlytics
  * Component version: 18.3.2

### [REQUIRED] Step 3: Describe the problem

Not something wrong with the API, but the way [logs](https://firebase.google.com/docs/reference/android/com/google/firebase/crashlytics/FirebaseCrashlytics#log(java.lang.String)) are displayed in the Firebase console.

If I log a String with newline characters like so:

```java
FirebaseCrashlytics.getInstance().log("I\n want \n on \n separate\n lines");
```

The display looks like this:
<img width="777" alt="Screenshot 2023-02-01 at 10 20 42" src="https://user-images.githubusercontent.com/16018629/216017800-aecfe817-01e1-4716-a98b-6d4e5d7eaff1.png">

Compare this to how iOS handles newline characters:
<img width="863" alt="Screenshot 2023-02-01 at 10 21 06" src="https://user-images.githubusercontent.com/16018629/216018082-89a1eafc-9425-4e11-a61e-ed1e3e985970.png">

#### Steps to reproduce:

Just call these methods:
```java
FirebaseCrashlytics.getInstance().log("I\n want \n on \n separate\n lines");
FirebaseCrashlytics.getInstance().recordException(new Exception("test-error"));
```

Check the Firebase console for "test-error" and read the logs for the exception.

**Comment by jrothfeder** [comment]
Thank you for reporting this feature request. As this is a Crashlytics service feature, and does not pertain to our SDK, I've moved it to the appropriate service team.
