### ISSUE TITLE
java.lang.IllegalStateException: Could not create Crashlytics-specific directory: /data/user/0/package/files/.com.google.firebase.crashlytics.files.v1 // at android.app.ActivityThread.null installProvider(null)(ActivityThread.java:7192)

### ISSUE THREAD

**Issue by lujun525** [firebase/firebase-android-sdk#4626]
// java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Could not create Crashlytics-specific directory: /data/user/0/package/files/.com.google.firebase.crashlytics.files.v1
// 	at android.app.ActivityThread.null installProvider(null)(ActivityThread.java:7192)
// 	at android.app.ActivityThread.null installContentProviders(null)(ActivityThread.java:6670)
// 	at android.app.ActivityThread.null handleBindApplication(null)(ActivityThread.java:6565)
// 	at android.app.ActivityThread.null access$1400(null)(ActivityThread.java:224)
// 	at android.app.ActivityThread$H.null handleMessage(null)(ActivityThread.java:1887)
// 	at android.os.Handler.null dispatchMessage(null)(Handler.java:107)
// 	at android.os.Looper.null loop(null)(Looper.java:224)
// 	at android.app.ActivityThread.null main(null)(ActivityThread.java:7560)
// 	at java.lang.reflect.Method.null invoke(null)(Method.java)
// 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.null run(null)(RuntimeInit.java:539)
// 	at com.android.internal.os.ZygoteInit.null main(null)(ZygoteInit.java:950)
// Caused by: java.lang.IllegalStateException: Could not create Crashlytics-specific directory: /data/user/0/com.bstar.intl.pogo/files/.com.google.firebase.crashlytics.files.v1
// 	at com.google.firebase.crashlytics.internal.persistence.FileStore.java.io.File prepareBaseDir(java.io.File)(FileStore.java:188)
// 	at com.google.firebase.crashlytics.internal.persistence.FileStore.void (android.content.Context)(FileStore.java:66)
// 	at com.google.firebase.crashlytics.FirebaseCrashlytics.com.google.firebase.crashlytics.FirebaseCrashlytics init(com.google.firebase.FirebaseApp,com.google.firebase.installations.FirebaseInstallationsApi,com.google.firebase.inject.Deferred,com.google.firebase.inject.Deferred)(FirebaseCrashlytics.java:75)
// 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.com.google.firebase.crashlytics.FirebaseCrashlytics buildCrashlytics(com.google.firebase.components.ComponentContainer)(CrashlyticsRegistrar.java:57)
// 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.com.google.firebase.crashlytics.FirebaseCrashlytics $r8$lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(com.google.firebase.crashlytics.CrashlyticsRegistrar,com.google.firebase.components.ComponentContainer)(CrashlyticsRegistrar.java:0)
// 	at com.google.firebase.crashlytics.CrashlyticsRegistrar$$InternalSyntheticLambda$2$db162bb9be36f9206ef3c77773d22791204d3cb6279c7815312c3bc51d3b6568$0.java.lang.Object create(com.google.firebase.components.ComponentContainer)(CrashlyticsRegistrar.java:2)
// 	at com.google.firebase.components.ComponentRuntime.java.lang.Object lambda$discoverComponents$0(com.google.firebase.components.Component)(ComponentRuntime.java:132)
// 	at com.google.firebase.components.ComponentRuntime.java.lang.Object $r8$lambda$4FqOW9eOQsvFYo-HpMfxCOnPQr0(com.google.firebase.components.ComponentRuntime,com.google.firebase.components.Component)(ComponentRuntime.java:0)
// 	at com.google.firebase.components.ComponentRuntime$$InternalSyntheticLambda$1$562ccfbab29457946f69b904d7c620216b88cbd0fd784cee32e00ed2dcd3a60c$0.java.lang.Object get()(ComponentRuntime.java:4)
// 	at com.google.firebase.components.Lazy.java.lang.Object get()(Lazy.java:53)
// 	at com.google.firebase.components.ComponentRuntime.void doInitializeEagerComponents(java.util.Map,boolean)(ComponentRuntime.java:291)
// 	at com.google.firebase.components.ComponentRuntime.void initializeEagerComponents(boolean)(ComponentRuntime.java:281)
// 	at com.google.firebase.FirebaseApp.void initializeAllApis()(FirebaseApp.java:584)
// 	at com.google.firebase.FirebaseApp.com.google.firebase.FirebaseApp initializeApp(android.content.Context,com.google.firebase.FirebaseOptions,java.lang.String)(FirebaseApp.java:303)
// 	at com.google.firebase.FirebaseApp.com.google.firebase.FirebaseApp initializeApp(android.content.Context,com.google.firebase.FirebaseOptions)(FirebaseApp.java:267)
// 	at com.google.firebase.FirebaseApp.com.google.firebase.FirebaseApp initializeApp(android.content.Context)(FirebaseApp.java:252)
// 	at com.google.firebase.provider.FirebaseInitProvider.boolean onCreate()(FirebaseInitProvider.java:51)
// 	at android.content.ContentProvider.null attachInfo(null)(ContentProvider.java:2117)
// 	at android.content.ContentProvider.null attachInfo(null)(ContentProvider.java:2091)
// 	at com.google.firebase.provider.FirebaseInitProvider.void attachInfo(android.content.Context,android.content.pm.ProviderInfo)(FirebaseInitProvider.java:45)
// 	at android.app.ActivityThread.null installProvider(null)(ActivityThread.java:7187)
// 	... 10 more
//

**Comment by argzdev** [comment]
Hi @lujun525, thanks for reporting. With just the given stacktrace, it won't help us investigate this. Please open a new issue with the necessary details provided in our template for us to conduct an initial investigation. I'll close this issue now.

**Comment by argzdev** [comment]
Hi @lujun525, thanks for reporting. With just the given stacktrace, it won't help us investigate this. Please open a new issue with the necessary details provided in our template for us to conduct an initial investigation. I'll close this issue now.
