### ISSUE TITLE
Crashlytics plugin release notes missing

### ISSUE THREAD

**Issue by eygraber** [firebase/firebase-android-sdk#4671]
The release notes for the crashlytics plugin haven't been updated since 2.9.2 - https://firebase.google.com/support/release-notes/android#crashlytics_gradle_plugin_v2-9-2

**Comment by argzdev** [comment]
Hi @eygraber, I'm not sure what you mean. The current latest version for `com.google.firebase:firebase-crashlytics-gradle` is `2.9.2`. Am I missing something?

**Comment by eygraber** [comment]
I'm using https://github.com/ben-manes/gradle-versions-plugin and it's saying that there's an update to 2.9.4

I used that version and everything builds fine.

**Comment by argzdev** [comment]
You're right. I tried checking maven repository, and it also shows a different version `2.9.3`. I'll let our engineers know about this and update accordingly. Thanks!

**Comment by ParticleCore** [comment]
Same thing is happening with `com.google.firebase:firebase-crashlytics-ktx`, it shows 18.3.4 but it is not documented anywhere. Also that specific version (18.3.4) is causing the app to crash.

**Comment by thatfiredev** [comment]
@eygraber Thanks for finding and reporting this. The [release notes](https://firebase.google.com/support/release-notes/android#2023-02-10) are out now. :)

**Comment by argzdev** [comment]
Since the release notes are now out. I'll close this as resolved. Thanks again, all!
