### ISSUE TITLE
Push notification token invalidated after a few minutes

### ISSUE THREAD

**Issue by flavioramos** [firebase/firebase-android-sdk#469]
Our app has been running on ~600 devices, and some of them are getting the push token invalidated after just a few minutes being registered.

The Firebase SDK works as the token is still valid, but when we try to send a message we get a "NotRegistered" error on the backend.

Also, onNewToken method is not being called with a new token as expected. 

Restarting the app or rebooting the device still gets the same token. The only way to get a new one is by cleaning the app data. But after a few minutes, it gets invalidated too.

### Environment

- Android Studio 3.3.1
- Firebase Messaging 17.3.4
- Firebase Core 16.0.5

**Comment by aguatno** [comment]
Hi @flavioramos I wasn’t able to reproduce the issue. Are you still having this issue? If so, we'd be happy to look into this further if you could provide steps to replicate or a [minimal repro.](https://stackoverflow.com/help/minimal-reproducible-example)

Thanks
