### ISSUE TITLE
[firebase-crashlytics-ndk] Breakpad symbol generation failed for prebuilt library built by Go for Android

### ISSUE THREAD

**Issue by sergeiignatov** [firebase/firebase-android-sdk#4699]
### Describe your environment

  * Android Studio version: 2022.1.1 Patch 1
  * Firebase Component: firebase-crashlytics-ndk
  * Component version: 18.3.5

### Describe the problem

We have prebuilt .so library built with Go for Android (go version go1.19.5 linux/amd64). It's not possible to generate crashlytics symbol file. Error is: "Breakpad symbol generation failed (exit=134), see STDERR". Other prebuilt libraries that doesn't use golang are processed fine.

#### Steps to reproduce:

clone https://github.com/sergeiignatov/golangdemo
Run ./gradlew clean assembleRelease generateCrashlyticsSymbolFileRelease
generateCrashlyticsSymbolFileRelease task fails with Breakpad symbol generation failed (exit=134), see STDERR

#### Relevant Code:

https://github.com/sergeiignatov/golangdemo
https://github.com/sergeiignatov/golangdemo/blob/main/app/prebuilt/arm64-v8a/libwebrtc_worker.so

**Comment by argzdev** [comment]
Hi @sergeiignatov, thanks for reporting. I was able to experience the same behavior with your demo project. I'll notify our engineer and see what we can do here.

**Comment by argzdev** [comment]
Hey @sergeiignatov, while this is still being investigated by our engineers. It seems that this is currently a similar issue to #4280. That said, for better tracking purposes I'll close this for now. Feel free to continue your report and check for updates on #4280 instead. Thanks!
