### ISSUE TITLE
com.google.firebase:firebase-crashlytics:18.3.0

### ISSUE THREAD

**Issue by jackteng9725** [firebase/firebase-android-sdk#4703]
"com.google.firebase:firebase-crashlytics:18.3.0
We detected an issue in this version of the Crashlytics Android SDK. We strongly recommend either using v18.2.13 or earlier or upgrading to v18.3.1+."

<img width="487" alt="截屏2023-02-21 下午11 14 02" src="https://user-images.githubusercontent.com/64823103/220383917-f13dd3ae-5fff-4325-9853-d9549be67961.png">
I have upgraded it to version 18.3.2, why I still get the above warning when I publish, it makes me very distressed, can you tell me what else I need to do?

**Comment by argzdev** [comment]
Hi @jackteng9725, there's currently a problem with that version. Please upgrade `com.google.firebase:firebase-crashlytics ` to version `18.3.5`. Thanks!

**Comment by jackteng9725** [comment]
@argzdev Thank you very much for your reply, I will try to upgrade
