### ISSUE TITLE
com.google.firebase:firebase-crashlytics-gradle:2.9.4

### ISSUE THREAD

**Issue by jackteng9725** [firebase/firebase-android-sdk#4707]
**After using com.google.firebase:firebase-crashlytics-gradle:2.9.4, when building, an error will appear**

android/build.gradle
dependencies {
classpath("com.google.firebase:firebase-crashlytics-gradle:2.9.4")
}

====================================================================

android/app/build.gradle
apply plugin: "com.google.firebase.crashlytics"

dependencies {
implementation platform('com.google.firebase:firebase-bom:31.2.2')
implementation 'com.google.firebase:firebase-analytics'
implementation 'com.google.firebase:firebase-crashlytics'
}

====================================================================

The executed command is ./gradlew clean

====================================================================

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/xxx/project/xxxx/android/app/build.gradle' line: 13

* What went wrong:
A problem occurred evaluating project ':app'.
> Receiver class com.google.firebase.crashlytics.buildtools.gradle.ExternalPluginsState does not define or inherit an implementation of the resolved method 'abstract void setProperty(java.lang.String, java.lang.Object)' of interface groovy.lang.GroovyObject.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Can anyone tell me how to solve it, because I use com.google.firebase:firebase-crashlytics-gradle:2.9.2, there will be no error**

**Comment by jackteng9725** [comment]
android/build.gradle
dependencies {
       classpath("com.google.firebase:firebase-crashlytics-gradle:2.9.4")
}

====================================================================

android/app/build.gradle
apply plugin: "com.google.firebase.crashlytics"

dependencies {
    implementation platform('com.google.firebase:firebase-bom:31.2.2')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
}

**Comment by jackteng9725** [comment]
The executed command is ./gradlew clean

**Comment by argzdev** [comment]
HI @jackteng9725, it seems to me that the issue is `Cause: compileSdkVersion is not specified. Please add it to build.gradle`. You can add this in the `build.gradle` file of your module.

```
android {
    namespace "com.argz.issue4707"

    // add the compileSdk below with the version of your choice
    compileSdk 33

    defaultConfig {
        applicationId "com.argz.issue4707"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    ....
}
```

That said, I think this should resolve your issue. If the issue persists give us a reply, and I'll reopen the issue again. Thanks!
