### ISSUE TITLE
firebase-messaging includes unsolicited directBootAware service

### ISSUE THREAD

**Issue by henrik-lindqvist** [firebase/firebase-android-sdk#4712]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1Build #AI-213.7172.25.2113.9014738, built on August 31, 2022
  * Firebase Component: firebase-messaging
  * Component version: 22.0.0

### [REQUIRED] Step 3: Describe the problem
`jetified-firebase-common-20.0.0` adds an unsolicited and undocumented directBootAware service to the `AndroidManifest.xml`:

    <service
        android:name="com.google.firebase.components.ComponentDiscoveryService"
        android:directBootAware="true"
        android:exported="false" >
        ...
    </service>

This will cause an app to crash unless it's specifically designed support it, e.g. if it access `SharedPreference` or other credential protected storage in its `Application.onCreate()`. Even the Firebase [documentation](https://firebase.google.com/docs/cloud-messaging/android/receive#receive_fcm_messages_in_direct_boot_mode) warns of this and correctly require a special dependency, apparently `firebase-common` is not that responsible.

#### Steps to reproduce:

Add the following to your `build.gradle`

    implementation 'com.google.firebase:firebase-messaging:22.0.0'

and the following will be included in the merged `AndroidManifest.xml`

    <service
        android:name="com.google.firebase.components.ComponentDiscoveryService"
        android:directBootAware="true"
        android:exported="false" >
        ...
    </service>

### Update required
Version 22.0.0 needs to be updated since many of us that still support older Android cannot use any newer release due to them requiring `minSkdVersion=19`.

**Comment by argzdev** [comment]
Hi @henrik-lindqvist, thanks for reporting. Good catch, I'll let our engineers know about this.

**Comment by argzdev** [comment]
Upon investigation, adding `android:directBootAware="true"` is a requirement before accessing the device encrypted storage. From my understanding adding this without accessing the device encrypted storage shouldn't cause any issues.

According to the [docs](https://developer.android.com/training/articles/direct-boot):
> Apps must register their components with the system before they can run during Direct Boot mode or access device encrypted storage. Apps register with the system by marking components as encryption aware. To mark your component as encryption aware, set the `android:directBootAware` attribute to true in your manifest.

Could you point me where it requires special dependency? I'm not sure, I might be missing something.

That said, it seems that this was added for #1840.
> * Initialize Firebase in direct boot mode
> Note that even though `FirebaseApp itself initializes, none of the other SDKs get initialized until the user unlocks the devices.
> * Add direct boot logging to FirebaseApp.

I believe this was for the usage of `DataCollectionConfigStorage` class, specifically for:
https://github.com/firebase/firebase-android-sdk/blob/bb62df1b4c1c3337734c6a4bc63534bed6f138f7/firebase-common/src/main/java/com/google/firebase/internal/DataCollectionConfigStorage.java#L55

**Comment by henrik-lindqvist** [comment]
@argzdev I don't know if these questions are directed at me, but here i go. As said, an app can access device encrypted storage in its `Application.onCreate`, `ContentProvider.onCreate` or any other component that's automatically initialized when the app is loaded. Firebase maybe designed for direct boot but other components in the hosting app may not, e.g. see stack trace below.

Special dependency as described in Firebase [documentation](https://firebase.google.com/docs/cloud-messaging/android/receive#receive_fcm_messages_in_direct_boot_mode): 

    implementation 'com.google.firebase:firebase-messaging-directboot:20.2.0'

I thought about this a bit more. I guess there should be no way for `ComponentDiscoveryService` to initialize itself since it's not exported. But i reported this since it has become the primary cause for crashes in my app after upgrading from 17.0.0 to 22.0.0 for `targetSkdVersiom=31`:

```
Caused by java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
  at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:572)
  at android.app.ContextImpl.getSharedPreferences (ContextImpl.java:557)
  at android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:224)
  at u4.j.d
  at com.xxx.yyy.zzz.MyApplication.onCreate
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1267)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6962)
```

**Comment by emilypgoogle** [comment]
Hi @henrik-lindqvist I've looked into the issue you've described and I've been unable to replicate it. Using `firebase-messaging` 22.0.0, nothing abnormal has been added to the `AndroidManifest.xml` and I haven't been able to replicate launches in direct boot mode either. Is it possible something else in your setup is causing this? If possible more context on where you're seeing this issue or a minimum viable reproduceable setup would be appreciated to debug this further.

**Comment by henrik-lindqvist** [comment]
@emilypgoogle I've only seen the issue in production, reported through the Play console. But i've since `tools:remove`d the `android:directBootAware` from `ComponentDiscoveryService` in the merged manifest and the issue no longer occur. It may have been a manufacturer Android issue, so unless you're going to make an separate `firebase-common-directboot` version that includes the `android:directBootAware`, then i guess you can close the issue.

**Comment by argzdev** [comment]
Hi @henrik-lindqvist, I'm glad you're able to resolve your issue. It might be difficult for us to make a decision on the fix unless we're able to replicate the issue and verify that it is the one causing the problem. We'll close this for now and observe this further if the issue arises again. And if there are more developers that are encountering this issue then we can prioritize a deeper investigation and reopen this thread. Thank you very much for the updates you've provided us.
