### ISSUE TITLE
"firebase_messaging_auto_init_enabled" flag does not work

### ISSUE THREAD

**Issue by UserSty** [firebase/firebase-android-sdk#473]
### Step 1: Describe your environment

  * Android device: Samsung S9
  * Android OS version: 8.0.0
  * Google Play Services version: 17.4.55
  * Play Services Base SDK version: 16.1.0
  * Firebase Core version: 16.0.7
  * Firebase Messaging version: 17.4.0
  
### Step 2: Describe the problem:
As mentioned in the docs to prevent auto-initialization of FCM tokens we may add 
```
<meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false"/>
<meta-data android:name="firebase_analytics_collection_enabled" android:value="false" />
```
 in AndroidManifest.xml. Bt this does not seem to work as token is still being generated automatically when the app starts.
This issue (https://github.com/firebase/quickstart-android/issues/467) already exist but it was closed. It strange because it wasn't solved

#### Steps to reproduce:

  1. Add this to manifest.xml
  2. Run the App

#### Observed Results:

  * Token would still generate without even initializing the firebase messaging again at runtime.
  
#### Expected Results:

  * Token wouldn't generate before the call `FirebaseMessaging.getInstance().setAutoInitEnabled(true);`

**Comment by samtstern** [comment]
@vkryachko do we have any tests for things that are specified in end-developer manifests like `firebase_messaging_auto_init_enabled`?

**Comment by vkryachko** [comment]
@samtstern We do for firebase-common for example: https://github.com/firebase/firebase-android-sdk/blob/bdfe418f1a2f908263eb22040af35f021984d5ab/firebase-common/src/test/java/com/google/firebase/DataCollectionDefaultDisabledTest.java#L30

But it's up to each individual SDK to have such tests

**Comment by UserSty** [comment]
What is the news?

**Comment by MiriamCordes** [comment]
Hi @samtstern, Is there an update concerning this issue? A bug-fix seems rather important regarding legal implications of user consent and GDPR... Thank you!

**Comment by MiriamCordes** [comment]
Hi @gsakakihara, 
thanks for your answer! I checked everything, but still I receive a push-message even though I think I should not. 

- I only added the Firebase Messaging SDK to gradle (version 20.0.0)
- In the app's manifest I added 
``` 
      <meta-data
         android:name="firebase_messaging_auto_init_enabled"
         android:value="false" />

      <meta-data
         android:name="firebase_analytics_collection_deactivated"
         android:value="true" />

      <meta-data
         android:name="firebase_analytics_collection_enabled"
         android:value="false" />
 ```
- I have not called a Firebase API that called / generated a Firebase Instance ID token, yet I receive a push message (I tested it on a freshly installed app)

I noticed that right after app start "FirebaseInitProvider: FirebaseApp initialisation successful" is logged. Could it be that we have to prevent this manually? (like it is described [here](https://firebase.googleblog.com/2017/03/take-control-of-your-firebase-init-on.html))

Thank you!

**Comment by gsakakihara** [comment]
FirebaseInitProvider should be fine, as long as you are not seeing a token being generated at startup (onNewToken() not called in FirebaseMessagingService). This is what firebase_messaging_auto_init_enabled is controlling.

How are you sending a message to the app? Specifically, how are you targeting the message to your device when you send it? If you are getting an FCM registration token or are subscribing to a topic, for example, those require a Firebase Instance ID token to function, so one will be generated when making those calls.

**Comment by MiriamCordes** [comment]
Hi @gsakakihara, 
it's working for me now. I discovered that it was not working on the emulator for me but everything worked as expected when I used a real-device to test the code. 
Thanks for your answers and the insights and sorry to have wasted your time!

**Comment by UserSty** [comment]
@MiriamCordes but we have a problem on real devices

**Comment by MiriamCordes** [comment]
Hi @UserSty, 
sorry to hear you're still having a problem. For me it is working now and I just wanted to get back to @gsakakihara, since he helped me finding my mistake.

**Comment by chliangGoogle** [comment]
@UserSty Can you also double check your setup following @gsakakihara's comment at https://github.com/firebase/firebase-android-sdk/issues/473#issuecomment-525399912

**Comment by UserSty** [comment]
> @gsakakihara's comment at [#473 (comment)](https://github.com/firebase/firebase-android-sdk/issues/473#issuecomment-525399912)

@chliangGoogle it didn't help then.

> Hey @UserSty. We need more information to resolve this issue but there hasn't been an update in 5 weekdays. I'm marking the issue as stale and if there are no new updates in the next 5 days I will close it automatically.
> 
> If you have more information that will help us get to the bottom of this, just add a comment!

@google-oss-bot I don't know what is the situation with the latest version of SDK but at the time I used the hack and did the `FirebaseMessaging.getInstance().setAutoInitEnabled(false);` because via the manifest it didn't work.

**Comment by chliangGoogle** [comment]
@UserSty Can you also look into your code and make sure you don't call anything to trigger Messaging to generate token again? Methods like @gsakakihara suggested here:  #473 (comment)

Would be also helpful if you can share with us any messaging or instanceID or Installations API you called in the code.

**Comment by mphill** [comment]
We're seeing a situation where a Pixel 3a, and Galaxy S9 are working, but Galaxy S10e and Galaxy S7 attempt to generate the token immediately upon start.  Same codebase on all 4 devices.

When I hook a debugger up to the S10e, it works - in release it fails - but logging indicates it's trying to generate the token before I set AutoInitEnabled to true.

**Comment by ashwinraghav** [comment]
@UserSty please share relevant portions of your gradle build and possibly the output of `./gradlew :app:dependencies`
