### ISSUE TITLE
Unable to authenticate with Microsoft using Firebase

### ISSUE THREAD

**Issue by g-sahu** [firebase/firebase-android-sdk#478]
I'm trying to implement authentication with Microsoft using Firebase in my app. I followed the steps mentioned in the tutorial https://firebase.google.com/docs/auth/android/microsoft-oauth.

Following are the code snippets from my application -

**MSAuthManager.java**

```
public void loginOutlook(Context context) {
    FirebaseAuth firebaseAuth = FirebaseAuth.getInstance();
    Task<AuthResult> pendingResultTask = firebaseAuth.getPendingAuthResult();

    if (pendingResultTask == null) {
        OAuthProvider.Builder provider = OAuthProvider.newBuilder("microsoft.com");
        provider.setScopes(asList(SCOPES));

        firebaseAuth.startActivityForSignInWithProvider((Activity) context, provider.build())
                    .addOnSuccessListener(this)
                    .addOnFailureListener(this)
                    .addOnCanceledListener(this);
    }
}
```

**AndroidManifest.xml**

```
<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https://**********.firebaseapp.com/__/auth/handler"
                  android:host="auth" />
        </intent-filter>
</activity>
```

**Note - I have already authenticated the user with Google sign-in using Firebase on the Login Screen.**

However, when I start the authentication process, a custom tab launches takes me to the Microsoft login page and then automatically closes and redirects me back to my app with the following error -

`FirebaseAuthWebException: The web operation was canceled by the user.`

Could anyone please tell me what am I missing here?

**Comment by samtstern** [comment]
@malcolmdeck I am concerned to see "FirebaseAuthWebException: The web operation was canceled by the user." pop up again, I thought we got rid of that generic message?

**Comment by g-sahu** [comment]
Hi, 
Is there an update on this issue? I'm kinda blocked here.

**Comment by malcolmdeck** [comment]
We throw that in the event that the user actually cancelled the flow;
otherwise you should get a more descriptive error. I don't know why we'd
still be seeing this - can a bugreport be taken on a device where this is
occurring?

**Comment by g-sahu** [comment]
@malcolmdeck Yes, sure. Please tell me how to submit a bug report.

**Comment by samtstern** [comment]
@g-sahu here's a description of how to capture a bug report:
https://developer.android.com/studio/debug/bug-report

Bug reports contain sensitive information about your device so please don't post it on GitHub.  Email it to me directly (my email is on my GitHub profile) and then I will forward it to @malcolmdeck for analysis.  Thanks!

**Comment by g-sahu** [comment]
@samtstern Dropped you a mail with the bug report.

**Comment by radzish** [comment]
I am having the same issue. I am using com.google.firebase:firebase-auth:17.0.0. First time it works fine, but with error: "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address", which is OK as I am using email, linked to my gmail already. But next time I try to login with different email I am getting: com.google.firebase.auth.FirebaseAuthWebException: The web operation was canceled by the user.

**Comment by SergeyMilewski** [comment]
I have the same problem.

**Comment by radzish** [comment]
So I suggest you upvote ;)

**Comment by jhilal** [comment]
I have the same problems ... I know the origin but dt know the solution..

The probleme is chrome or samsung internet browser, u have a password saved in one of this browser, and this password saved is not the good.

The web operation was canceled by the user : In my case, its means 'wrong password'

I have a proof of this, u just have to clear all data of chrome (cache and data), and retry it works directly

**Comment by SergeyMilewski** [comment]
I've switched to SDK from Microsoft and there is no more issue.

**Comment by jhilal** [comment]
Plz can u send me a tutorial for SDK, i don't undertand your 'switched'?

**Comment by Asad4132** [comment]
@g-sahu Did you find any solution?

**Comment by gitam2869** [comment]
> I have the same problems ... I know the origin but dt know the solution..
> 
> The probleme is chrome or samsung internet browser, u have a password saved in one of this browser, and this password saved is not the good.
> 
> The web operation was canceled by the user : In my case, its means 'wrong password'
> 
> I have a proof of this, u just have to clear all data of chrome (cache and data), and retry it works directly

Yes, problem solve for me. Thank You so much.

**Comment by gitam2869** [comment]
> I have the same problems ... I know the origin but dt know the solution..
> 
> The probleme is chrome or samsung internet browser, u have a password saved in one of this browser, and this password saved is not the good.
> 
> The web operation was canceled by the user : In my case, its means 'wrong password'
> 
> I have a proof of this, u just have to clear all data of chrome (cache and data), and retry it works directly

**Comment by gitam2869** [comment]
Yes, problem-solve for me. Thank you so much.

**Comment by argzdev** [comment]
Hi @g-sahu, just bumping this thread. Since this has been a while, are you still encountering this issue on the latest SDK?
