### ISSUE TITLE
KTX artifact issues

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/firebase-android-sdk#480]
1. It looks like Firestore `19.0.2` was published without its accompanying KTX variant.
1. It would be really awesome if we didn't have to pull in both the normal and ktx artifacts to use a lib. To start the discussion, I've created #479.

**Comment by vkryachko** [comment]
Hey @SUPERCILEX , thanks for filing this

1. We are aware of the issue and will address it in a followup release
2. Not sure what you mean, are you saying that you have to include both e.g. firebase-firestore and firebase-firestore-ktx to be able to use it? That should not be the case as our ktx pom specifies deps as `compile` scoped.

**Comment by SUPERCILEX** [comment]
@vkryachko 
1. Dope!
1. Yeah, that was the issue but I just realized I had an erroneous `transitive = false`. My B. 😊
