### ISSUE TITLE
Support for setting authDomain on Android

### ISSUE THREAD

**Issue by skion** [firebase/firebase-android-sdk#4805]
## What feature would you like to see?

Support for setting `authDomain` on Android, or mobile in general. At the moment it is impossible to authenticate users via a custom domain when signing in on mobile.

## How would you use it?

Usage would be similar to the [web variant](https://cloud.google.com/identity-platform/docs/web/redirect-best-practices#update-authdomain).

**Comment by NhienLam** [comment]
Hi, thanks for reporting!
The best practices in https://cloud.google.com/identity-platform/docs/web/redirect-best-practices need to be applied only for web applications that use the `signInWithRedirect` web SDK API. Hence, no action is needed for mobile apps.

If there are other reasons why you need this feature, could you please describe your use case and why you need this? Thanks!

**Comment by NhienLam** [comment]
@skion Thanks for the update. We currently do not support custom domain on mobile. We have put this feature request on our radar, but we are unable to promise a timeline right now.

**Comment by apgiorgi** [comment]
I have another good reason for using custom auth domains:
A customer had their `firebaseapp.com` and `web.app` hostnames incorrectly included in phishing blacklists (DNSBL), interfering with DNS resolution on "safe/protected" nameservers. The only immediate solution before removing those blacklist entries is to use a custom authentication domain.
Is it so hard to implement this customization option? Are there other alternatives?
