### ISSUE TITLE
Does firebase-crashlytics-ndk/Crashpad catch SIGQUIT?

### ISSUE THREAD

**Issue by bc-lee** [firebase/firebase-android-sdk#4818]
We are using firebase-crashlytics-ndk 18.3.2.

Some crash reports in the Firebase console have a native stack trace, but no signal information such as the signal name (`SIGABRT`, `SIGSEGV`, etc.) and the thread it was fired from. This leaves us with no clue what's going on.

One possibility I'm thinking of is that the SIGQUIT sent by ART is caught by firebase-crashlytics-ndk, but it shows up as a crash, not an ANR.

Is my hypothesis correct? So is this a bug or is it intended? If that's intended, are there any plans to add an option to not catch `SIGQUIT`?

According to the crashspad API firebase-crashlytics-ndk can prevent some signals from being caught by crashpad.

Example: https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:components/crash/core/app/crashpad_android.cc;drc=2450f2f5d0ce0da9b8cf493c533f9528ff17bab6;l=531

**Comment by argzdev** [comment]
Thanks for reporting, @bc-lee. I'll raise your questions to our engineers and reply back here once I get an update. While we wait, any chance you could share with us the native stack trace you're receiving with no signal information? Thanks!

**Comment by bc-lee** [comment]
It is currently being investigated in Firebase support case 10222183.

**Comment by argzdev** [comment]
Hi @bc-lee, thanks for this update. For better tracking, you can continue your report with the mentioned Firebase support case. I'll close this for now.
