### ISSUE TITLE
FirebaseAuthInvalidCredentialsException problem

### ISSUE THREAD

**Issue by michal-chojnacki** [firebase/firebase-android-sdk#4823]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Electric Eel | 2022.1.1 Patch 1
  * Firebase Component: Firebase Auth
  * Component version: bom:31.0.2

### [REQUIRED] Step 3: Describe the problem

In logs I can see that some users of my app are getting exception which looks like this: `FirebaseAuthInvalidCredentialsException: The supplied auth credential is malformed or has expired. [ ID Token issued at 1647450573 is stale to sign-in. ]` when `FirebaseAuth#signInWithCredential` or `FirebaseAuth#linkWithCredential` is called.

Users have correct time set on their devices when this error happens.

I was able to reproduce the state of the app when signing in stopped working only once. I was changing time backward on forward and after that all sign in attempts resulted with `FirebaseAuthInvalidCredentialsException`

I tried to fix this problem with calling `getIdToken` with `forceRefresh` flag set to true, but even though new token was generated with different `expirationTimestamp`  still the same `FirebaseAuthInvalidCredentialsException` was thrown. I also tried to call `FirebaseAuth#signOut` but it didn't help. After signing out when I was asking for `FirebaseUser` `null` was returned but exception during signing in was still being thrown.

How I can fix the state of `FirebaseAuth` when this problem happens? I'd be grateful for help.

#### Steps to reproduce:

I wasn't able to find exact steps to reproduce it. I was able to reproduce the state of the app when signing in stopped working only once. I was changing time backward on forward and after that all sign in attempts resulted with `FirebaseAuthInvalidCredentialsException`.

**Comment by argzdev** [comment]
Thanks for reporting, @michal-chojnacki. Would you happen to know if there's any specific type of authentication when these issues happened? I'm thinking if the issue might be related to timezones.

**Comment by michal-chojnacki** [comment]
I was able to encounter on this issue on the newest sdk version `31.4.0`.

When app was in state when signing in stopped working I was able to see failed request to `https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyAssertion?key=my_key_was_here`:
```
{
  "error": {
    "code": 400,
    "message": "INVALID_IDP_RESPONSE : ID Token issued at 1680190843 is stale to sign-in.",
    "errors": [
      {
        "message": "INVALID_IDP_RESPONSE : ID Token issued at 1680190843 is stale to sign-in.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```
I've decoded token which was sent and it wasn't issued at 1680190843 and dates of issuing and expiration looked ok. Token shouldn't be stale.

Also in my logs I can see that some users have `The supplied auth credential is malformed or has expired. [ Unable to verify the ID Token signature.` in the same use case. Is possible that these problems are related? How can I fix this issue?

**Comment by argzdev** [comment]
Hi @michal-chojnacki, sorry for the radio silence here. It seems to me that we might need to take a closer look into this. That said, could you file an issue to our [Firebase support](https://firebase.google.com/support)? Since they have visibility on your project setup, they'll be able to assist you better. You may also share project details, and other configurations.

I'll close this issue for now. Feel free to come back here if you think this is a mistake or if you have any further information that you can share with us to help investigate the issue further from the SDK side. Thanks!
