### ISSUE TITLE
SafetyNet SDK and Play Integrity on version 21.2.0

### ISSUE THREAD

**Issue by dpedrinha** [firebase/firebase-android-sdk#4836]
>               ### 🎉 Good news, everyone!
> 
> We have just released [Firebase Auth 21.2.0](https://firebase.google.com/support/release-notes/android#auth_v21-2-0) (BoM 31.4.0) which adds support for Play Integrity in phone auth.
> We recommend that you migrate to it as soon as possible (just need to update the version in the Gradle file, no breaking changes in code).
> 
> Firebase phone auth will now attempt a Play Integrity verification and fallback to SafetyNet or reCAPTCHA if that fails. See more details in [the docs][1].
> 
> ---
> 
> #### ⚠️ But I still see the warning in the Play console 😕
> 
> That's because the SafetyNet SDK is still being used as a fallback. We plan to completely remove the SafetyNet SDK in a future release - I will post a new comment to this thread when that happens.
> 
> #### ❓ Do I need to enable the Play Integrity API ? 🤔 
> 
> As explained in our [docs](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification:~:text=The%20Play%20Integrity%20API%20is%20enabled%20on%20a%20Google%2Downed%20project%20by%20Firebase%20Authentication%2C%20not%20on%20your%20project), the Play Integrity API is enabled on a Google-owned project, not on your project. It **does not** contribute to any Play Integrity API quotas on your project.
> 
> ---
> 
> If you're having an issue with the new version, please file a [new issue](https://github.com/firebase/firebase-android-sdk/issues/new/choose) or [contact Firebase support](https://firebase.google.com/support/troubleshooter/auth).
> 
> [1]: https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification
> 
> _Originally posted by @thatfiredev in https://github.com/firebase/firebase-android-sdk/issues/3890#issuecomment-1488368740_
> 
> 
>             

I can't reply to the original issue, so I had to create this new one because I've a few questions about it.

-1 The docs point to a documentation regarding Phone auth, I'm not using phone auth, I'm using Google sign in only and I have the same issue. Is this fix just for phone auth? 

-2 If SafetyNet is deprecated, why does it need to stay as a fallback? I need to test my app without this fallback otherwise I risk my app stop working the day SafetyNet is shut down. And I will have to wait for your fix. In the other hand, if it doesn't work now, I can downgrade the the previous version and report a bug in time for a fix. Am I missing something or does it make sense?

**Comment by thatfiredev** [comment]
@dpedrinha Thanks for bringing this up.

1. Yes, SafetyNet and Play Integrity are only used by Phone Auth. Unfortunately, at the moment the Firebase SDK is bundled with all sign-in providers and there's no easy way to opt out of one of them. (see a workaround below)
2. SafetyNet should still work for developers who have migrated to the PlayIntegrity API, so we kept it as a fallback to ease the transition. (more details in the [deprecation timeline](https://developer.android.com/training/safetynet/deprecation-timeline#safetynet_attestation_deprecation_timeline))



### Temporary workaround (not recommended)
If you're not using phone auth (nor MFA) in your app, you might be able to exclude the safetynet dependency from your build:

```groovy
    implementation (platform('com.google.firebase:firebase-bom:31.4.0')) {
        exclude group: 'com.google.android.gms', module: 'play-services-safetynet'
    }

    implementation ('com.google.firebase:firebase-auth-ktx') {
        exclude group: 'com.google.android.gms', module: 'play-services-safetynet'
    }
```

⚠️  Note that this will break both phone auth and MFA in runtime.

**Comment by argzdev** [comment]
Hi all, since I think the questions regarding SafetyNet and Play Integrity has been answered. I'll go ahead and close this now.
