### ISSUE TITLE
Nice to have - ability to have turn off persistence for specific Firestore write operations

### ISSUE THREAD

**Issue by Jeffreyoboe1** [firebase/firebase-android-sdk#4840]
## What feature would you like to see?

Firebase Firestore SDK - when setting a document reference with a write request, or when deleting/updating, we would have a setOption that allows us to NOT persist the operation in case of internet not working.  For example, with `GetOptions` we have `default` | `server` | `cache`.  For SetOptions, would be nice to have `persistWrite: boolean`.  I understand it is possible to to do this using `Firebase Transactions`.  However, would be more convenient/easier to find this way.  

For example:  
`Firestore().clearPendingWrites()`

## How would you use it?
Would use this by being certain user will only see writes complete at certain point within the app.  

For example, user on screen A.  Goes to screen B, he writes a doc to firestore.  We use `persist = false`.  If an internet problem, the user can be notified there was an error writing to server.  Otherwise, user backs out of screen, out of app, and back into app, then the write will complete at a time unexpected by user.

**Comment by milaGGL** [comment]
Hi @Jeffreyoboe1. Thank you for submitting this ticket. I will take this feature request to our team's discussion and keep you informed of any updates.

**Comment by milaGGL** [comment]
Google internal tracking id: b/169688224
