### ISSUE TITLE
communicate with my own backend service

### ISSUE THREAD

**Issue by scguoi** [firebase/firebase-android-sdk#4846]
As a backend developer of a SaaS service, we have built a backend with capabilities such as configuration management, application analytics, and crash analysis, which overlap significantly with Firebase. I want to use the open-source Firebase SDK but remove its access to Google services and instead have it communicate directly with our backend. Is this feasible?

**Comment by argzdev** [comment]
Hi @scguoi, thanks for reaching out. Just to confirm, when you say "Google services", are you pertaining to usage of `google-services.json` or the Google services inside each Firebase SDK. If it's the latter part, I think this would depend on which Firebase product you would be using. Would you mind sharing what Firebase products do you have in mind?

**Comment by scguoi** [comment]
We have a mid-sized backend development team in our company, which has already built a crash analysis, data analysis, performance monitoring, and remote configuration management platform, similar to Firebase's Crashlytics, Analytics, Performance Monitoring, and Remote Config. However, our SDKs for each platform are not well-developed yet. We have noticed that Firebase's SDKs are open source, and we want to make some adjustments to connect the SDKs to our own crash analysis, data analysis, performance monitoring, and remote configuration management platform. This will improve integration efficiency and ease of use for our platform.

**Comment by argzdev** [comment]
Thanks for the updates, @scguoi. According to our [docs](https://firebase.google.com/docs/android/android-play-services#play-services-required-summary):

Products that Google Play services are **not** required:
- Firebase's Crashlytics
- Performance Monitoring
- Remote Config

Products that Google Play services are required:
- Analytics

You should be able to make these adjustments except for Analytics.

**Comment by argzdev** [comment]
Since I believe this question has been clarified. I'll go ahead and close this. If there are other concerns/questions, feel free to ask if you'd like this to be reopened. Thanks!
