### ISSUE TITLE
i see this every time during login (after crash)

### ISSUE THREAD

**Issue by plakapenka** [firebase/firebase-android-sdk#4865]
last version android studio
last version all firebase module

i see this every time during login (after crash)
![image](https://user-images.githubusercontent.com/10694250/230408330-d2dc49b2-89dc-44bc-a6e0-daf3cab2a10f.png)

I have a line like this, when I close the application through the exit button
`FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(false);`

**Comment by argzdev** [comment]
Hi @plakapenka, thanks for reaching out. Just to confirm when you say "last version all firebase module" are you pertaining to using `com.google.firebase:firebase-bom` version `31.4.0`? Can you share with us a minimal reproducible code example?

**Comment by plakapenka** [comment]
My game sometimes crashes when closed by the user. (too hard to fix. it consists of own cpp library and gta cpp library)
As a temporary solution, I added the code when closing the game:
![image](https://user-images.githubusercontent.com/10694250/230420050-aa1d2694-8af1-4740-ad50-e455aeaff8cc.png)

After doing this 50/50 I get a crash on the next run.

**Comment by argzdev** [comment]
Upon checking:
- `com.google.firebase:firebase-bom` version `31.1.0` have `com.google.firebase:firebase-crashlytics` version `18.3.2`. 
- `com.google.firebase:firebase-bom` version `31.4.0` have `com.google.firebase:firebase-crashlytics` version `18.3.6`.

Can you try using the latest version? There were previously some changes that were made to fix crash issues. Let me know if that helps.

Also it might be difficult for us to investigate this without a reproducible steps or examples

**Comment by argzdev** [comment]
Awesome, thanks for confirming. I'll close this now.
