### ISSUE TITLE
[Crashlytics-ndk] Native crash does not get reported on real device

### ISSUE THREAD

**Issue by Vukooo** [firebase/firebase-android-sdk#4867]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: IntelliJ IDEA 2023.1
  * Firebase Component: Crashlytics/Crashlytics-ndk
  * Component version: com.google.firebase:firebase-bom:31.4.0

#### Steps to reproduce:

I'm currently trying to integrate crashlytics-ndk in our app. We have a simple segfault crash for testing purpose.
```
        int* p = (int*)-1;
        int i = *p;
```
This test crash crashes successfully. When running the test crash in the emulator, crashlytics recognizes the crash on the next app start and uploads it. However, when running on a real device, the crash doesn't get recognized and doesn't get uploaded,
FirebaseCrashlytics.getInstance().didCrashOnPreviousExecution() always returns false.
The logs show on in both cases "Initializing native crash handling successful.". 
Java crashes work fine.
Setting "android:debuggable=true" doesn't change anything (https://github.com/firebase/firebase-android-sdk/issues/1678).

Emulator: Pixel 3a API 33 arm64-v8a
Real device: Samsung Galaxy A40 API 30 arm64-v8a

**Comment by argzdev** [comment]
Thanks for reaching out, @Vukooo. That is odd, can you share some details with us:
1. Have you tried running this on other test devices and see if the same behavior happens? 
2. Is there any debug logs you can share with us?
3. Do you have a minimal reproducible example you could share with us?

**Comment by Vukooo** [comment]
> 1. Have you tried running this on other test devices and see if the same behavior happens?

Not yet, currently I have only one real device at my disposable. However, I'll try to get my hands on a second one.

> 2. Is there any debug logs you can share with us?

The logcat logs I looked through only showed successful initialization. Is there a way, to activate a more verbose crashlytics log, that I could share?

> 3. Do you have a minimal reproducible example you could share with us?

Not yet, I'll try to create one.

**Comment by kim-f** [comment]
Hi @Vukooo, thanks for this information!

I have couple of additional questions –  

1. Do you see `"Crashlytics report successfully enqueued to DataTransport"` in the logs at any point when using a real device?
2. Is it possible that the real device you're using is subject to a firewall that your emulation environment is not?

**Comment by Vukooo** [comment]
Hi,

> 1. Do you see "Crashlytics report successfully enqueued to DataTransport" in the logs at any point when using a real device?

No, I do not.

> 2. Is it possible that the real device you're using is subject to a firewall that your emulation environment is not?

I don't think so. Also, java crashes work and get reported normally. 

Also, in general, "FirebaseCrashlytics.getInstance().didCrashOnPreviousExecution()" always returns false on a native crash on a real device, so it seems not to be a uploading issue, right?

**Comment by kim-f** [comment]
Thanks again. This issue is unusual so a minimal reproducible example would be extremely helpful for our investigation into the problem. 

Please reply with an example when you have a chance, or let us know if you won't be able to put one together.

**Comment by Vukooo** [comment]
I was able to create a minimal reproducer: https://github.com/Vukooo/CrashlyticsNDKBug
The important line is the following:
https://github.com/Vukooo/CrashlyticsNDKBug/blob/55f7e9596060e94767bad538055bb051364ab6c6/app/src/main/java/com/vukooo/crashlyticsndkbug/MainActivity.java#L48
On my emulator, this returns "true" when starting the app after a crash. On my real device it always returns false.

Please note, that the committed credentials are incorrect: https://github.com/Vukooo/CrashlyticsNDKBug/blob/55f7e9596060e94767bad538055bb051364ab6c6/app/src/main/java/com/vukooo/crashlyticsndkbug/MainActivity.java#L32-L36

I hope this reproducer is helpful!

**Comment by kmandrika** [comment]
@Vukooo Could you set this value to true and try again? https://github.com/Vukooo/CrashlyticsNDKBug/blob/55f7e9596060e94767bad538055bb051364ab6c6/app/src/main/java/com/vukooo/crashlyticsndkbug/MainActivity.java#L40

**Comment by Vukooo** [comment]
Yes, I have, the behavior is the same. It still always reports "DETECTED CRASH: false".

**Comment by Vukooo** [comment]
I got around testing it on more real device:
Sony Xperia X with Android 8 - works
Samsung Galaxy A31 with Android 11 - works

So it seems to be something special to my device, I don't know what it is though.

**Comment by argzdev** [comment]
Hi @Vukooo, sorry for the delayed response here. It seems to me that there might be something particularly different with your device. That said, I believe you'll need to share a bit more information which might not be suitable discussing here on GitHub. If you're still experiencing this issue, please file a ticket to our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact). They'll be able to assist you better since you'll be able to share project details and configurations. Thanks!
