### ISSUE TITLE
 java.lang.OutOfMemoryError com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:304)

### ISSUE THREAD

**Issue by ZhangZhizhen** [firebase/firebase-android-sdk#4889]
java.lang.OutOfMemoryError

解析原始
1
java.util.zip.Deflater.init(Native Method)
2
java.util.zip.Deflater.<init>(Deflater.java:187)
3
java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:90)
4
java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:109)
5
com.google.android.datatransport.cct.CctTransportBackend.doSend(CctTransportBackend.java:304)
6
com.google.android.datatransport.cct.CctTransportBackend.lambda$bLAzIpNF4NtapXlUpPVGhzxyNT8(Unknown Source:0)
7
com.google.android.datatransport.cct.-$$Lambda$CctTransportBackend$bLAzIpNF4NtapXlUpPVGhzxyNT8.apply(Unknown Source:4)
8
com.google.android.datatransport.runtime.retries.Retries.retry(Retries.java:54)
9
com.google.android.datatransport.cct.CctTransportBackend.send(CctTransportBackend.java:372)
10
com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:144)
11
com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1$Uploader(Uploader.java:104)
12
com.google.android.datatransport.runtime.scheduling.jobscheduling.-$$Lambda$Uploader$DXUaNZ7S78mHsDrcqc_9ECz1Ymg.run(Unknown Source:8)
13
com.google.android.datatransport.runtime.SafeLoggingExecutor$SafeLoggingRunnable.run(SafeLoggingExecutor.java:47)
14
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
15
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
16
java.lang.Thread.run(Thread.java:923)

**Comment by argzdev** [comment]
Thanks for reaching out, @ZhangZhizhen. There's not much details for us to go by with just the stacktrace. Could you file a new ticket with the details using our template? This is so that we can conduct an initial investigation regarding your issue. That said, I'll be closing this issue now.
