### ISSUE TITLE
Crash due to FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.

### ISSUE THREAD

**Issue by valeriyo** [firebase/firebase-android-sdk#4907]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2022.2.1 RC1
  * Firebase Component: Auth
  * Component version: 21.1.0, 21.2.0, 21.3.0

### [REQUIRED] Step 3: Describe the problem

A significant number of crashes in production, due to this exception:
```
Fatal Exception: com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.
       at com.google.android.gms.internal.firebase-auth-api.zzaaj.zza(com.google.firebase:firebase-auth@@21.2.0:19)
       at com.google.android.gms.internal.firebase-auth-api.zzabi.zza(zzabi.java:28)
       at com.google.android.gms.internal.firebase-auth-api.zzabj.zzl(com.google.firebase:firebase-auth@@21.2.0:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabg.zzh(com.google.firebase:firebase-auth@@21.2.0:25)
       at com.google.android.gms.internal.firebase-auth-api.zzaah.zzh(com.google.firebase:firebase-auth@@21.2.0:1)
       at com.google.android.gms.internal.firebase-auth-api.zzxb.zza(com.google.firebase:firebase-auth@@21.2.0:2)
       at com.google.android.gms.internal.firebase-auth-api.zzabr.zzb(zzabr.java:16)
       at com.google.android.gms.internal.firebase-auth-api.zzaaw.zzf(com.google.firebase:firebase-auth@@21.2.0:4)
       at com.google.android.gms.internal.firebase-auth-api.zzyk.zzp(zzyk.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzaai.zzj(zzaai.java:3)
       at com.google.android.gms.internal.firebase-auth-api.zzyu.zzc(zzyu.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzabk.run(com.google.firebase:firebase-auth@@21.2.0:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

Since it happens outside my app code, there is no obvious way to handle it (or avoid it).

#### Steps to reproduce:

Normal app usage. As far as I can tell, at the time of the crash, the user is signed in. So, it's possible that this crash is occurring when Firebase Auth decided to check / refresh authentication status of the current user.

#### Relevant Code:

None.

**Comment by argzdev** [comment]
HI @valeriyo, thanks for reporting. Could you answer a few questions below for me:

1. Did this happen after upgrading the version of Firebase Auth? If so, could you tell us which version?
2. Did this happen after a recent app deployment? Perhaps there were code changes related to Firebase Auth that could cause this issue? Could you share that with us?
3. One possible reason for this is if Google Play services is not running or the user do not have Google Play services on their device. Can you check Crashlytics to see if those users have device brands that do not have Google Play services? 

These might give us a clue to what's causing the issue. Thanks in advance!

**Comment by valeriyo** [comment]
Answers:

1. We released our app to open testing in Play Store, with `firebase-auth:21.1.0` and crashes have been continuously happening since then.
2. Yes and no, since the app has been publicly out for ~3 months.
3. From the logs looks like user has been signed in already (meaning, they were able to sign in), and crash happens right after upon app launch.

(ignore the line colors - these are different app versions)
<img width="501" alt="image" src="https://user-images.githubusercontent.com/7052801/232769433-d11574f4-d3f4-4b56-9887-dec920904fe0.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/7052801/232770202-0b2c4312-8afc-4aac-99e8-f7ba788acc15.png">

Crashing happens disproportionally more frequently on Android 13:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/7052801/232770394-9a299a98-3329-4672-871c-ff7cee2e19e3.png">

Here is actual Android version distribution - Android 13 is third:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/7052801/232770771-7777bb1b-e09a-456c-911d-f3711808a108.png">

**Comment by valeriyo** [comment]
The crash occurs with `firebase-auth:21.3.0` as well :(

**Comment by argzdev** [comment]
Hi @valeriyo, this is very insightful. Thanks for getting back to us with these details. I hope you don't mind, could you share some code snippets related to Firebase Authentication? I'm wondering which API call from the SDK is causing the issue. Also do you have `minifyEnabled` set as `true`?

**Comment by valeriyo** [comment]
Yes, we enable minification.

We use https://github.com/GitLiveApp/firebase-kotlin-sdk , where `dev.gitlive.firebase.auth.FirebaseAuth` is the wrapper for the underlying `com.google.firebase.auth.FirebaseAuth` object.

Use-cases:

To determine if user is signed in and getting user's properties (name, email):
```
firebaseAuth.currentUser
```

To observe changes of the authenticated state, we subscribe to:
```
firebaseAuth.authStateChanged
```

To sign in:
```
firebaseAuth.signInWithCredential(credential)
```

To sign up:
```
firebaseAuth.createUserWithEmailAndPassword(email, password)
```

To sign out:
```
firebaseAuth.signOut()
```

To refresh auth token:
```
firebaseAuth.currentUser?.getIdToken(forceRefresh = false)
```

Q: You should be able to de-obfuscate the callstack (e.g. `om.google.android.gms.internal.firebase-auth-api.zzaaj.zza`) and figure out what it's doing, right?

**Comment by valeriyo** [comment]
Hey guys - this is the most frequent crash for us right now, can you perhaps suggest a workaround - how to avoid it? Thanks.

**Comment by prameshj** [comment]
> Yes, we enable minification.
> 
> We use https://github.com/GitLiveApp/firebase-kotlin-sdk , where `dev.gitlive.firebase.auth.FirebaseAuth` is the wrapper for the underlying `com.google.firebase.auth.FirebaseAuth` object.
> 
> Use-cases:
> 
> To determine if user is signed in and getting user's properties (name, email):
> 
> ```
> firebaseAuth.currentUser
> ```
> 
> To observe changes of the authenticated state, we subscribe to:
> 
> ```
> firebaseAuth.authStateChanged
> ```
> 
> To sign in:
> 
> ```
> firebaseAuth.signInWithCredential(credential)
> ```
> 
> To sign up:
> 
> ```
> firebaseAuth.createUserWithEmailAndPassword(email, password)
> ```
> 
> To sign out:
> 
> ```
> firebaseAuth.signOut()
> ```
> 
> To refresh auth token:
> 
> ```
> firebaseAuth.currentUser?.getIdToken(forceRefresh = false) // sometimes, with true
> ```
> 
> Q: You should be able to de-obfuscate the callstack (e.g. `om.google.android.gms.internal.firebase-auth-api.zzaaj.zza`) and figure out what it's doing, right?

Thanks for providing this stacktrace. That line points to a network exception which wraps ["UnknownHostException"](https://docs.oracle.com/javase/8/docs/api/java/net/UnknownHostException.html)

There isn't anything in the 21.2.0 version that could trigger this more often. Are you able to repro this with an emulator/under a network proxy?

**Comment by valeriyo** [comment]
I am not able to reproduce it. But it happens 10+ times a day in Production, and is # 1 crash, by number of crashes and affected users.

I added more logging, and I think it occurs after we request `FirebaseUser.getIdToken()`, which we wrap inside `runCatching` -- so it looks like the implementation of this `Task` doesn't propagate exception correctly to the `Task` - instead, it crashes the app.

**Comment by argzdev** [comment]
Thanks for the update, @valeriyo. So when you use `FirebaseUser.getIdToken()` are you using `addOnSuccessListener` or `addOnCompleteListener`? If you're using the latter, this might be the reason for the issue. You could probably catch this with the `addOnFailureListener`. Let me know if this helps. Thanks!

**Comment by valeriyo** [comment]
We use gitlive -- see https://github.com/GitLiveApp/firebase-kotlin-sdk/blob/master/firebase-auth/src/androidMain/kotlin/dev/gitlive/firebase/auth/user.kt#L36 :

```
    actual suspend fun getIdToken(forceRefresh: Boolean): String? = android.getIdToken(forceRefresh).await().token
```

**Comment by valeriyo** [comment]
I think `addOnCompleteListener` should be sufficient, so I think the `await()` is actually correct.

**Comment by argzdev** [comment]
Hi @valeriyo, thanks for clarifying. Yeah, ignore what I said initially said, the implementation for `addOnCompleteListener` is correct. I initially thought you were using `FirebaseUser.getIdToken()` directly e.g.
```
FirebaseUser.getIdToken()
        .addOnSuccessListener {  }
        .addOnFailureListener {  }
```

However, now that you've mentioned you're using await, this shouldn't apply in your case. 

That said, since we now know that the stacktrace error is due to network exception. I don't see any fix we can do on the SDK side, since network issues are very tricky, and it could be caused by simple problems such as intermittent connection. I think the best solution for this, should probably be to catch the error whenever the token being returned is invalid, and refresh. Let me know if this helps or if there's anything else you'd like to be done differently in this case.

**Comment by valeriyo** [comment]
So, the `getIdToken(false)` was causing the crash, because it doesn't just return the token, but rather goes out to the network (despite `forceRefresh = false`) and it's prone to failures and latency (could take several seconds)

That's disgusting, you guys!

We'll have to store the token in our own storage and retrieve it on the app launch, since you've failed to provide a reliable way to fetch this token quickly and reliably.

**Comment by argzdev** [comment]
Hi @valeriyo, I'm really sorry you're having a bad experience with this. I can see how this issue is causing a major impact in your system. 

FWIW, the `getIdToken(false)` will only do a network call if the cached id token is no longer valid. It should return the token immediately if the token is still valid. 

Just a thought, since it was mentioned that the issue is due to `UnknownHostException`. And usually UnKnownHostException is thrown to indicate that the IP address of a host could not be determined. Then perhaps you could try a connectivity conditional check first before triggering `getIdToken(false)`? Let me know if doing so helps. Thanks!

Other than that, if we're able to replicate the same environment and issue that the developers are experiencing then it would give us much more information to investigate and provide a foolproof solution.

**Comment by Biowulf21** [comment]
> 

This is very interesting. I'm using a Samsung device to run my APK and I am getting this error as well.

**Comment by argzdev** [comment]
Hi @Biowulf21, any chance you could share with us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the issue? It'll greatly help us investigate this further.
