### ISSUE TITLE
Native callstack missing in crashlytics for crashes (but works for ANRs)

### ISSUE THREAD

**Issue by Olof-IL** [firebase/firebase-android-sdk#4926]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Electric Eel | 2022.1.1 Patch 1
  * Firebase Component: Crashlytics NDK
  * Component version: 18.3.6 (BoM: 31.3.0)
  * Gradle plugin: 2.9.5
  * Gradle version: 7.5
  * Android Gradle Plugin Version: 7.4.2
  * Google services Gradle Plugin version: 4.3.15

### [REQUIRED] Step 3: Describe the problem

I've followed all steps in the documentation, plugin applied in build.gradle and nativeSymbolUploadEnabled set to true
Running ./gradlew app:uploadCrashlyticsSymbolFileRelease seems to succeed.
I've run it with --debug, and it shows "Crashlytics symbol file uploaded successfully"

What makes me believe there is a firebase issue is that I do get callstacks into my native code for all my ANRs in the same version. Only the callstacks for crashes keep showing "missing buildid".

Here's a snippet of callstack for an ANR I get. Notice it finds the symbols for "36e3bae77e5ad4776dba33dd83b6667400ffe98e" except for one line (#19) where it for some reason shows "missing" also in the ANR:

```
#12 pc 0x139684 libGLESv2_mtk.so (glTexStorage2D + 104) (BuildId: 0e02c8f1e2225ac94e0860c49d05345a)
#13 pc 0x1139620 split_config.arm64_v8a.apk (void gfx::ResourceManager::createAndBind<gfx::TextureGLES3, gfx::ResourceManagerGLES3, gfx::Texture2D>(gfx::ResourceManagerGLES3*, gfx::Texture2D*) + 68) (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#14 pc 0x11540cc split_config.arm64_v8a.apk (gfx::ResourceManager::createTexture2D(gfx::PixelFormat, unsigned int, unsigned int, unsigned int, gfx::TextureUsage, gfx::TextureStorageMode) + 288) (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#15 pc 0x11575d0 split_config.arm64_v8a.apk (gfx::TextureLoader::loadTexture2D(std::__ndk1::shared_ptr<il::fs::Resource> const&, gfx::PixelFormat, bool, gfx::TextureUsage) + 252) (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#16 pc 0x11572c8 split_config.arm64_v8a.apk (gfx::TextureLoader::textureWithContentsOfFile(std::__ndk1::shared_ptr<il::fs::Resource> const&, gfx::PixelFormat, gfx::TextureType, bool, gfx::TextureUsage) + 140) (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#17 pc 0x116b7c4 split_config.arm64_v8a.apk (TextureAtlas::getTexture(gfx::ResourceManager&, gfx::PixelFormat) + 756) (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#18 pc 0xb170a0 split_config.arm64_v8a.apk (bmx2::MainMenuLayer::loadMenuEntries() + 1036) (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#19 pc 0xb21090 split_config.arm64_v8a.apk + 3657728 (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#20 pc 0x1193c74 split_config.arm64_v8a.apk (PanelLayout::resize(float, float, float) + 624) (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
```

Here's a snippet from a crash (they all look pretty much the same):
```
null pointer dereference: SIGSEGV  0x0000000000000000
#00 pc 0xf07780 libbmx2.so (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#01 pc 0xf0492c libbmx2.so (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
#02 pc 0xf0492c libbmx2.so (BuildId: 36e3bae77e5ad4776dba33dd83b6667400ffe98e)
```

Here it fails to find the symbols for "36e3bae77e5ad4776dba33dd83b6667400ffe98e" for each line, even though this build ID is (mostly) available for the ANR...

Possibly relevant is that we use Android Integrity Protection for this release.

#### Steps to reproduce:

Not sure, please advice if there is anything more I can show to help you identify the issue.

#### Relevant Code:

Firebase modules used
```
    implementation platform('com.google.firebase:firebase-bom:31.3.0')

    implementation ('com.google.firebase:firebase-crashlytics-ndk')

    implementation ('com.google.firebase:firebase-analytics')
    implementation ('com.google.firebase:firebase-messaging')
    implementation ('com.google.firebase:firebase-config')
```

**Comment by argzdev** [comment]
Hey @Olof-IL, thanks for reporting. Seems to me that there might be a configuration issue. That said, could you file an issue to our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact)? They'll be able to assist you better since you'll be able to share project setup and details. I'll close this issue for now. You can always come back here if we verify that the SDK is causing issues. Thanks!
