### ISSUE TITLE
Unable to process request due to missing initial state.

### ISSUE THREAD

**Issue by kakueki61** [firebase/firebase-android-sdk#4946]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Electric Eel | 2022.1.1
  * Firebase Component: Firebase Authentication
  * Component version: Firebase Android BoM 31.5.0

#### Steps to reproduce:

When signing in with phone authentication, reCAPTCHA flow is triggered and the web browser is launched.
On the browser, the screen below appear.

<img src="https://user-images.githubusercontent.com/1000470/234809487-5a8d6068-54a0-4d91-b235-12c0c44c520b.jpg" width="300">

Only part of the users encounter this error, but I can't reproduce this.

#### Relevant Code:

```
val phoneWithCountryCode = getPhoneNumberWithCountryCode(phoneNumberText)

val auth = Firebase.auth
val optionsBuilder = PhoneAuthOptions.newBuilder(auth)
    .setPhoneNumber(phoneWithCountryCode)
    .setTimeout(120L, TimeUnit.SECONDS)
    .setCallbacks(object : PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
        override fun onVerificationCompleted(authCredential: PhoneAuthCredential) {
            onVerificationCompleted(authCredential)
        }

        override fun onVerificationFailed(e: FirebaseException) {
            e.printStackTrace()
            onVerificationFailed(e)
        }

        override fun onCodeSent(
            verificationId: String,
            token: PhoneAuthProvider.ForceResendingToken
        ) {
            super.onCodeSent(verificationId, token)
            forceResendingToken = token
            onCodeSent(verificationId, token)
        }

        override fun onCodeAutoRetrievalTimeOut(verificationId: String) {
            super.onCodeAutoRetrievalTimeOut(verificationId)
            onCodeAutoRetrievalTimeOut(verificationId)
        }
    })
    .setActivity(activity)
        
forceResendingToken?.let {
    optionsBuilder.setForceResendingToken(it)
}

val options = optionsBuilder.build()
PhoneAuthProvider.verifyPhoneNumber(options)
```

**Comment by argzdev** [comment]
Thanks for reaching out, @kakueki61. This looks similar to the issue in the [JS repo](https://github.com/firebase/firebase-js-sdk/issues/4256). Looking last update in the [thread](https://github.com/firebase/firebase-js-sdk/issues/4256#issuecomment-1495054934), I wonder if we could look at this on a different angle. Could you help answer the following questions:

1. Where you able to perhaps check if the affected users are only using a specific browser? e.g. Chrome only?
2. Are you able to check if what Chrome version are they using? I'm assuming this is only affecting Chrome users on a specific version.

Other than that, given the nature of the issue. It might be difficult for us to investigate this without a minimal repro. Let me know if you see any others patterns or information you think will help us investigate this further. Thanks!

**Comment by prameshj** [comment]
+1 to @argzdev 's question - we noticed that the flow on Firefox was failing, since it wasn't handling an intent based redirect. Curious what browser this was on.

**Comment by kakueki61** [comment]
@argzdev I could get the answers from one user, 
1. The user is using Chrome as a default browser, but Tor browser and Firefox are installed as well.
2. The version is `112.0.5615.136`

I hope this helps.

**Comment by argzdev** [comment]
Hi @kakueki61, thanks for the extra details. So I tried reproducing this with an emulator of Android 11.0, x86, and with Chrome version you've provided, however I'm unable to get the same behavior.

So from my understanding, the user doesn't have Google Play Store, but have Chrome, which is why reCAPTCHA flow is triggered.

I have a few ideas:
1. This is a farfetched thought, but I wonder if it's due to different different processor (CPU) architecture. Would you be able to check what processor (CPU) architecture is their device running or what brand or model are they using?
2. Is there a specific Android version that are affected? Could you list them down?
3. Are the other browsers (Tor and Firefox) working when used for the reCAPTCHA flow?

**Comment by kakueki61** [comment]
Thank you for your investigation.

1. 2 . I only got answers from 2 affected users.
    ```
    1.
    model: Samsung SM-A515F/DSN
    Android OS: 13

    2.
    model: DOOGEE S40Pro
    Android OS: 10
    ```
    There are other affected users, so there are other affected models and os versions.
    It may not be happening only on a specific OS or device. For example, some users have no problems with the S40Pro.
3. Checking

**Comment by NhienLam** [comment]
Hi @kakueki61, thanks for the extra information. We're still not able to reproduce the same issue on Chrome. 

Would you be able to provide the following information:
1. a screen recording of this issue happening on Chrome
2. a full url where you see the error
3. +1 to 
> Are the other browsers (Tor and Firefox) working when used for the reCAPTCHA flow?

Thanks.
