### ISSUE TITLE
Dependency to play-services-tasks marked as jar

### ISSUE THREAD

**Issue by r-gurzkowski** [firebase/firebase-android-sdk#4958]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: EE
  * Firebase Component: Crashlytics
  * Component version: 18.3.6

### [REQUIRED] Step 3: Describe the problem
In the `firebase-crashlytics:18.3.6` pom file ([link](https://dl.google.com/android/maven2/com/google/firebase/firebase-crashlytics/18.3.6/firebase-crashlytics-18.3.6.pom)) dependency to `com.google.android.gms:play-services-tasks` is defined as `<type>jar</type>`. However on maven.google.com only aar exists. This still works with Gradle but apparently Bazel has a different resolution strategy and it fails with 404.

The problem doesn't affect 18.3.5, because it defines `<type>aar</type>` in it's pom file ([link](https://dl.google.com/android/maven2/com/google/firebase/firebase-crashlytics/18.3.5/firebase-crashlytics-18.3.5.pom))

#### Steps to reproduce:
1. Use any Bazel project (for example: https://github.com/bazelbuild/examples/tree/main/android/jetpack-compose)
2. Add "com.google.firebase:firebase-crashlytics:18.3.6" to `maven_install` (`WORKSPACE` file in the example)
3. Add the dependency to any bazel target
3. Observe the following error:
```
ERROR: workspace/examples/android/jetpack-compose/app/src/main/BUILD.bazel:4:19: //app/src/main:lib_base depends on @maven//:com_google_firebase_firebase_crashlytics in repository @maven which failed to fetch. no such package '@maven//': Error while fetching artifact with coursier: Error fetching artifacts:
https://maven.google.com/com/google/android/gms/play-services-tasks/18.0.2/play-services-tasks-18.0.2.jar: not found: https://maven.google.com/com/google/android/gms/play-services-tasks/18.0.2/play-services-tasks-18.0.2.jar
```

**Comment by mrober** [comment]
Thanks for reporting this. Fixed in #4962 and the next release of Crashlytics won't have this issue.
