### ISSUE TITLE
Firebase Cloud messaging not open app from background when notification data has url like(https://www.google.com).

### ISSUE THREAD

**Issue by sahilXperge** [firebase/firebase-android-sdk#4968]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 
		 

    ```
     Android Studio Flamingo | 2022.2.1 
     Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
     Runtime version: 17.0.6+0-17.0.6b802.4-9586694 aarch64
     VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
     macOS 13.0
     GC: G1 Young Generation, G1 Old Generation
     Memory: 2048M
     Cores: 8
     Metal Rendering is ON
     
     Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    gradle.version.catalogs.dynamic.support=true
    
    Non-Bundled Plugins:
    com.bloc.intellij_generator_plugin (3.4.0)
    Dart (222.4560)
    andrasferenczi.dart-data-plugin (0.2.0)
    io.flutter (73.0.2)
    ```

  * Firebase Component: Firebase Cloud messaging
  * Component version: com.google.firebase:firebase-messaging:23.1.2

### [REQUIRED] Step 3: Describe the problem

When push notification contains link then it not open android application when application is  in background or killed in android. 

It will work fine when app is in foreground. 

#### Steps to reproduce:

1. send payload to token 
	```
		{ notification:
		{ sound: 'default',
		badge: '1',
		title: 'qww',
		 body: 'w'
		  type: 'Link',
		   typeId: '',
		    link: 'https://www.google.com'  },
		    data:{ sound: 'default',
		    badge: '1',
		    title: 'qww',
		     body: 'w',
		       type: 'Link',
		       typeId: '',
		       link: 'https://www.google.com' } }
	```

##### Firebase service in manifest
```
<service android:name=".service.MyFirebaseMessagingService"  
  android:exported="false"  
  android:enabled="true"  
  >  
 <intent-filter> 
 <category android:name="android.intent.category.DEFAULT" />  
 <action android:name="com.google.firebase.MESSAGING_EVENT" />  
 <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />  
 </intent-filter>
 </service>
```
##### Splash activity in manifest
```
<activity  
  android:name=".views.splash.SplashActivity"  
  android:screenOrientation="portrait"  
  android:windowSoftInputMode="stateAlwaysHidden|adjustResize"  
  android:exported="true">  
 <intent-filter>  
 <action android:name="android.intent.action.MAIN" />  
 <action android:name="com.google.firebase.MESSAGING_EVENT"/>  
 <category android:name="android.intent.category.LAUNCHER" />  
 </intent-filter>
 </activity>
```

**Comment by argzdev** [comment]
Hey @sahilXperge, thanks for reporting. Looking through [NotificationMessagePayload](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.notificationmessagepayload.md#properties) - `type`,`typeId`, or `link` are not supported properties. May I ask why are you adding these?

**Comment by sahilXperge** [comment]
Thanks @argzdev for update.
