### ISSUE TITLE
Compiling Firestore with AGP 8.0 cause an R8 issue

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-android-sdk#4974]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2022.2.1
  * Firebase Component: Firestore
  * Component version:  32.0.0

### [REQUIRED] Step 3: Describe the problem
When trying to compile an application using Gradle 8.0 with Firestore I get the following issue:
```
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in PATH/build/app/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class org.kxml2.io.KXmlParser,org.kxml2.io.KXmlSerializer (referenced from: java.lang.Iterable io.grpc.ServiceProviders.getCandidatesViaServiceLoader(java.lang.Class, java.lang.ClassLoader) and 1 other context)
```

#### Steps to reproduce:

Switch to AGP 8.0.

**Comment by dconeybe** [comment]
Hi @Lyokone. I'll take a look at this.

**Comment by dconeybe** [comment]
I just tried a vanilla android project with agp8 and it worked just fine: https://github.com/dconeybe/agp8testapp
Can you try out that application? Just run `./gradlew assembleDebug`

**Comment by Lyokone** [comment]
I've tried on your project and it works as expected in release and debug mode, with `minifyEnabled true` and  `shrinkResources true`
Not sure why it wouldn't work on Flutter but at least I know where the problem is 😅 

Thanks for your help, I think we can close this

**Comment by Lyokone** [comment]
For reference: after some more investigation, it seems that adding the 
```
  integration_test:
    sdk: flutter
```
is what is causing the R8 errors. Till integration_test is not fully updated user should stay on 7.4.2.

**Comment by cuong0993** [comment]
Raised https://github.com/flutter/flutter/issues/127388
