### ISSUE TITLE
Firestore's get(/databases/) call on a sub-collection #firestore assignee: MilaGGL

### ISSUE THREAD

**Issue by mathems-m** [firebase/firebase-android-sdk#4994]
Hi @milaGGL

I am finding an unusual result when calling Firestore's get(/databases/) function for data that is two sub-collections deep.  For some reason, the data that is meant to be read isn't allowed, with Firestore confirming that the caller does not have permission to perform the operation.

To replicate the situation, please arrange Firestore collections with the following arrangement:

 **<img width="1292" alt="Screenshot 2023-04-19 at 12 21 39" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/b98e8096-3e10-46d3-bdfa-ec87c61a7c8c">** 
<img width="1292" alt="Screenshot 2023-04-19 at 12 22 17" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/e5fde943-a043-44a6-b873-c50a73425d28">
<img width="1292" alt="Screenshot 2023-04-19 at 12 23 09" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/887a7299-86da-4dd4-be54-2e823fa87f9a">
<img width="1292" alt="Screenshot 2023-04-19 at 12 24 19" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/223d89f0-5ca6-4994-a12d-bad14d0ba5be">

Please note: collections 'users', 'userA' and 'userB' are empty.

The contents of collections 'signInData', 'otherDetails', 'exclusiveA' and 'exclusiveB' are confirmed in the attached images, and, the 'userA' collection does not have any user-data but collection 'userB' does.

So, the get(/databases/) call is meant to permit the reading of documents in collection 'exclusiveA' if the boolean field-value of 'creditCard' in collection 'exclusiveB' is set to false.  This is where the failure is occurring.

The code querying my security rules is within file: stream_results.txt

The security rules that have been set are within file: testdevelop_security_rules.txt

Please share your feedback on this situation and whether there is a way that this problem can be worked around.  The main thing is the conditional reading of collection 'exclusiveA'.

Thank you for your time and for your assistance.
[stream_results.txt](https://github.com/firebase/firebase-android-sdk/files/11435231/stream_results.txt)
[testdevelop_security_rules.txt](https://github.com/firebase/firebase-android-sdk/files/11435244/testdevelop_security_rules.txt)
<img width="1258" alt="Screenshot 2023-05-08 at 10 27 15" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/456bd82c-7101-481e-8e16-afa6f9ef31ce">
<img width="1258" alt="Screenshot 2023-05-08 at 10 27 34" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/b8026a64-528c-4c77-9d1e-db0a7b07e363">
<img width="1258" alt="Screenshot 2023-05-08 at 10 28 11" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/44dc8799-12d9-448f-9a74-b7e3e64ef85d">
<img width="1258" alt="Screenshot 2023-05-08 at 10 29 02" src="https://github.com/firebase/firebase-android-sdk/assets/106067897/c672714d-30e7-449e-b86b-7dd1c553856b">

**Comment by mathems-m** [comment]
#firestore 

Assignee: MilaGGL

**Comment by mathems-m** [comment]
The flutter doctor -v response is:

m.mathems@Ms-MacBook-Pro developer_testing % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/m.mathems/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (10 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/m.mathems/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/m.mathems/Library/Android/sdk/
    • Java binary at: /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2 EAP)
    • IntelliJ at /Users/m.mathems/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version EAP IU-222.3153.4)
    • IntelliJ at /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.3153.4/IntelliJ IDEA 2022.2 EAP.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Users/m.mathems/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.17/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (7 available)
    • sdk gphone64 x86 64 (mobile)        • emulator-5554                        • android-x64    • Android 12 (API 32) (emulator)
    • iPhone 12 Pro Max (mobile)          • 4BB077E1-56E6-468B-A35A-A8F533ACD849 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPhone SE (3rd generation) (mobile) • E0095356-C638-46CD-9601-C43A14EE4641 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPad Pro (10.5-inch) (mobile)       • 67B76729-B225-4F02-86EE-380A7F0724FC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • iPad mini (5th generation) (mobile) • 2975B3C2-C864-481A-8BBC-6C4B9752441F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


The error message when I am using the iOS emulator is: flutter: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.

The error message when I am using the Android emulator is:  W/Firestore(24205): (24.4.3) [Firestore]: Listen for Query(target=Query(users/l9NzQFjN4iB0JlJaY3AI/userA/2VzSHur3RllcF5PojT61/exclusiveA order by name);limitType=LIMIT_TO_FIRST) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null} D/EGL_emulation(24205): app_time_stats: avg=15753.46ms min=383.96ms max=31122.96ms count=2

**Comment by dconeybe** [comment]
This topic was discussed in several forum posts. I'm closing this ticket because the discussion is regarding security rules and the flutter sdk, and this repository is for the android sdk.

Here are the relevant posts:
- https://groups.google.com/g/google-cloud-firestore-discuss/c/_3B1FTfn0Uo/m/GGYaPB5TAQAJ
- https://groups.google.com/g/google-cloud-firestore-discuss/c/NWnJLCxKuMo/m/4tR-CT6fAQAJ
- https://groups.google.com/g/google-cloud-firestore-discuss/c/a5z_t5-XNfM/m/qfex5NZeAQAJ
