### ISSUE TITLE
[In App Messaging] Ability to override action's default behaviour

### ISSUE THREAD

**Issue by Ethan1983** [firebase/firebase-android-sdk#5003]
## What feature would you like to see?

- Firebase In App Messaging's default behaviour is to always launch the URL payload of the action button. Apps typically use deep link to navigate to a part of an application. However, the intent extras for such deep links just has the URL and doesn't have any specified custom data (key value pairs).

   <img width="510" alt="Screenshot 2023-05-15 at 8 39 50 PM" src="https://github.com/firebase/firebase-android-sdk/assets/1020585/e51eb05a-df37-4de0-87aa-63e1ea159988">

- Support `FirebaseInAppMessagingClickListener::messageClicked` to return a boolean. Apps wanting to disable `FirebaseInAppMessagingDisplay` default behaviour can just return true, false otherwise.

```
new View.OnClickListener() {
              @Override
              public void onClick(View v) {
                if (callbacks != null) {
                  Logging.logi("Calling callback for click action");
                  callbacks.messageClicked(action);
                }
                launchUriIntent(activity, Uri.parse(action.getActionUrl()));
                notifyFiamClick();
                // Ensure that we remove the displayed FIAM, and ensure that on re-load, the message
                // isn't re-displayed
                removeDisplayedFiam(activity);
                inAppMessage = null;
                callbacks = null;
              }
            };
```

## How would you use it?

   This gives app an ability to use custom data in click handler and be able to handle the action url as desired. Currently, it is not possible to get custom data from suggested deep link mechanism.

**Comment by argzdev** [comment]
Thanks for reaching out, @Ethan1983. In a way, this seems similar to #3056. Could you leave a thumbs up emoji on the author's post of #3056? This is so that we can quantify and have better tracking on features that have demand. Feel free to add more information on that thread. That said, I'll go ahead and mark this as a duplicate.
