### ISSUE TITLE
[Admin SDK] Support for Firebase In App Messaging

### ISSUE THREAD

**Issue by Ethan1983** [firebase/firebase-android-sdk#5004]
## What feature would you like to see?

Admin SDK (https://firebase.google.com/docs/admin/setup)  to support Firebase In App Messaging.

## How would you use it?

App would use Firebase Cloud Functions to send Firebase In App Messages programatically based on real time data generated in Cloud Firestore.

**Comment by argzdev** [comment]
Hi there, thanks for reaching out. Could you file this to the [Firebase Admin SDK](https://github.com/firebase/firebase-admin-node) team? Thanks!
