### ISSUE TITLE
Firebase calling firebaseinstallations.googleapis.com despite manifest flag firebase_crashlytics_collection_enabled = false

### ISSUE THREAD

**Issue by iriphon** [firebase/firebase-android-sdk#5025]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Electric Eel | 2022.1.1 Patch 2
  * Firebase Component: Crashlytics via com.google.firebase:firebase-bom:26.7.0
  * Component version: 26.7.0

### [REQUIRED] Step 3: Describe the problem
Despite disabling Crashlytics data collection via the manifest, upon install the app sends a request to firebaseinstallations.googleapis.com. We are asking for the user's consent for crash reporting, and only then enable it in our code. 

The expected behaviour would be for the FirebaseApp initialisation also to only happen once Crashlytics tracking is enabled, not before. That is, no calls to firebaseinstallations.googleapis.com upon install should be made, submitting information such as device model, if data collection is not enabled.

#### Steps to reproduce:

* In Android Manifest under `<application>` add
```
<meta-data
            android:name="firebase_analytics_collection_deactivated"
            android:value="true" />
```
```
<meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="false" />
```
* Add dependency to Crashlytics to buid.gradle files (no other Firebase components have been added as a dependency)
* Make sure there is absolutely no usage of Firebase in the code, other than adding the dependency buid.gradle files
* Set up proxy tool to intercept app requests
* Deploy app to device
* Despite setting the manifest flags to disable data collection, the app sends a request to https://firebaseinstallations.googleapis.com/v1/projects/app-xxxx/installations to register the app installation with Firebase

#### What I tried unsuccessfully:
* Setting above manifest properties, including permanently disabling Crashlytics data collection via `firebase_analytics_collection_deactivated = true`
* Calling FirebaseApp.getInstance().setDataCollectionDefaultEnabled(false) in onCreate() in the MainActivity has no effect.
It seems that the FirebaseInitProvider is called despite this setting or the manifest settings, as it is hooked into the app lifecycle, even before `MainActivity.onCreate()` gets called.

####  Successful workaround:
* Disable FirebaseInitProvider by adding the following to the manifest under `<application>`
```
<provider
            android:name="com.google.firebase.provider.FirebaseInitProvider"
            android:authorities="${applicationId}.firebaseinitprovider"
            tools:node="remove"/>
```
* Call `FirebaseApp.initializeApp(context)` programmatically once user granted tracking consent
* Side-effect: the call to firebaseinstallations.googleapis.com now happens every time the user performs a full re-start of the app, after FirebaseApp has been initialised programmaticaly, as opposed to only once upon a new install

**Comment by iriphon** [comment]
@argzdev ah, amazing, I'd been looking in the docs forever and somehow hadn't seen that flag. Thanks!

**Comment by iriphon** [comment]
@argzdev I have added the following to the manifest:
```
<meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false" />
```
but the problem persists, upon install the app sends the request.

We did not have a dependency to "com.google.firebase:firebase-analytics-ktx", so I added it, and tried again, thinking we may need to add the component explicitly for it to work. Same result, app sends the request upon install.

So this flag also doesn't seem to work.

Additionally, even if the flag *did* work, we did not have a dependency to firebase analytics in our app. I wouldn't expect for the firebase lib to nonetheless do any kind of analytics tracking, unless we explicitly added that dependency. That is rather hidden and unexpected.

Further, I have looked at the docs for Crashlytics setup again, in particular [the section on opt-in](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#enable-reporting) nowhere is it mentioned that the flag you mentioned should be set. I would at least expect to see a clearly visible reference to the [Analytics docs](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#disable_data_collection), making developers aware that adding Crashlytics automartically adds other kinds of tracking than just crash data collection.

**Comment by argzdev** [comment]
Hi @iriphon, thanks for getting back. Please note that `meta-data` data you've provided are distinct with each other, one for `Analytics` and one for `Crashlytics`.

`firebase_analytics_collection_enabled` is only for `Analytics`. This is only needed if you are using Analytics. I've tried testing the behavior you've mentioned with just `Crashlytics` and adding `firebase_crashlytics_collection_enabled` as `false`, and this seems to work as intended (no network requests to firebaseinstallations).

> making developers aware that adding Crashlytics automatically adds other kinds of tracking than just crash data collection.

We do have documentation regarding the network call for FIS. You may check out the documentations [here](https://firebase.google.com/docs/projects/manage-installations).

I'm not sure why you're experiencing a different behavior. Are you using other Firebase products? Also could you provide a minimal reproducible example for us to investigate this further?

**Comment by iriphon** [comment]
Many thanks for the analysis so far. I'm working in creating an example project and will be adding it here, with further information, in the course of today.

**Comment by iriphon** [comment]
@argzdev please see https://github.com/iriphon/crashlytics_call_demo for a demo project where the issue occurs.

note it contains the following dependencies
`    
implementation(platform("com.google.firebase:firebase-bom:26.7.0"))
implementation("com.google.firebase:firebase-crashlytics")
//implementation("com.google.firebase:firebase-analytics-ktx") (= not enabled)
`

and manifest flags
`
<meta-data android:name="firebase_analytics_collection_enabled" android:value="false" />
<meta-data android:name="firebase_crashlytics_collection_enabled" android:value="false" />
`

**Comment by argzdev** [comment]
Hi @iriphon, thanks for the extra details. I've been out of the office for sometime so I couldn't get back to you. Anyway, I've tested the scenario you've provided. From my findings, it looks like this issue does happen with the `firebase-bom:26.7.0`. But testing with the latest version `32.1.0` works just fine. Could you try that and see if it makes any changes?

**Comment by iriphon** [comment]
@argzdev that very latest update v32.1.0 from 26 May does indeed fix the problem. Perfect, thank you 👍 🙂

**Comment by argzdev** [comment]
Awesome, glad to hear that works.
