### ISSUE TITLE
Upgrading to AGP 8.0.1 caused NO logs in issue reports ("No logs found")

### ISSUE THREAD

**Issue by valeriyo** [firebase/firebase-android-sdk#5033]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1 Beta 3
  * Firebase Component: Crashlytics
  * Component version: Firebase BOM 31.5.0 and Crashlytics plugin 2.9.2

### [REQUIRED] Step 3: Describe the problem
Our error/crash reports were working just fine with AGP 7.4.2 -- but the moment we upgraded to AGP 8.0.1 the issues in the Crashlytics web console stopped showing logs -- "No logs found"

#### Steps to reproduce:

Log something:

```
crashlytics.log("testing")
crashlytics.recordException(Error("dummy error"))
```

<img width="1195" alt="NoLogs" src="https://github.com/firebase/firebase-android-sdk/assets/7052801/5b98f5e0-2cbf-4434-b0e8-e2c37f4c52e0">

**Comment by argzdev** [comment]
Hi @valeriyo, let me take a look into this and get back to you in a moment.

**Comment by argzdev** [comment]
Hi @valeriyo, this is odd. I'm able to receive logs from Non-fatals. I used AGP version `8.0.1` and Gradle version `8.0`, this seems to work fine. Are you receiving no logs at all? You might be receiving logs in a delayed manner.

> Crashlytics processes exceptions on a dedicated background thread to minimize the performance impact to your app. To reduce your users’ network traffic, Crashlytics batches logged exceptions together and sends them the next time the app launches.

To test this without the delay, you could throw an exception and see if logs are recorded also in the exception. Let me know if this works. Thanks!

**Comment by mtotschnig** [comment]
I also observe missing logs since upgrading AGP to version 8. recordException works fine but log does not work. Logs are no longer visible in Firebase Console, neither for fatals nor non-fatals.

**Comment by valeriyo** [comment]
Perhaps this is related to R8? We use `isMinifyEnabled = true` but we had to disable `fullMode` because it caused issues...

```
android.enableR8.fullMode=false
```

**Comment by valeriyo** [comment]
So, I tried changing to `isMinifyEnabled = false` and got the logs!

**Comment by mtotschnig** [comment]
After some debugging, I was able to validate that the problem is due to R8, unfortunately it happens independent of the fullMode setting. The problem lies in class QueueFileLogStore, method getLogBytes, variable offsetHolder. R8 seems to corrupt this variable, as reported in https://issuetracker.google.com/issues/281929803. Upgrading R8 as explained in https://issuetracker.google.com/issues/280659987#comment17 solves the problem for me.

**Comment by mtotschnig** [comment]
Upgrading AGP to 8.0.2, which uses R8 8.0.46, should also get rid of the problem.

**Comment by valeriyo** [comment]
Yes, confirmed that updating AGP to 8.0.2 fixes this issue! Thanks @mtotschnig for digging..

**Comment by argzdev** [comment]
Good stuff, @mtotschnig! Thanks @valeriyo for confirming that it works.
