### ISSUE TITLE
[remote_config] User Properties are ignored during first fetch of Remote Config data

### ISSUE THREAD

**Issue by barmaciej** [firebase/firebase-android-sdk#5039]
### Describe your environment

  * Android Studio version: Electric Eel | 2022.1.1 Patch 1
  * Firebase Component: Remote Config
  * Component version: 21.4.0 (BOM 32.0.0)
  * Android OS version: 11

### Describe the problem

Users report random situations when my application uses default-marked values (coming from Remote Config), despite the presence of values coupled with User Properties that are suitable for this particular app.

I tried to reproduce this situation and I found only one way to do it (but it has 100% repro rate). I start with clearing application's data. Then, immediately, I cut the power off the device (the device has no battery supply).

I've done some debugging of Firebase SDK code and I noticed that the part of Remote Config's logic, which is reponsible for preparation of User Prorties that will act as parameter of Remote Config query, returns an empty map (com.google.firebase.remoteconfig.internal.ConfigFetchHandler.getUserProperties()). Then, everything goes well. There is a network request to fetch Remote Config values (com.google.firebase.remoteconfig.internal.ConfigFetchHttpClient.fetch()), but there's no User Properties passed as parameter, so... Remote Config server returns defaults.
Deeper analysis of the part of code responsible of fetching User Prioperties was impossible due to code obfuscation.

To sum up what I've done and what gave no positive effects:
- I'm sure that User Properties has been set before calling Remote Config to fetch data
- I tried to postpone the moment of initialization of Firebase SDK relative to application launch
- I tried different delays between the moment of setting the User Properties and the moment of querying Remote Config
- com.google.firebase.remoteconfig.internal.ConfigFetchHandler.getUserProperties() - connector has always been present. Just the userPropetiesMap has sometimes not been filled.
- each time I've set the returned value of ConfigFetchHandler.getUserProperties() myself (using debugger), the proper (in context of User Properties) Remote Config values have been fetched

#### Steps to reproduce:

- clear application's data
- (immediately!) cut the power off the device
- let the device reboot, open application and check what has been fetched from Remote Config

**Comment by barmaciej** [comment]
Thanks for reply, @paulinon 
I'll prepare a sample that will show this faulty scenario.

**Comment by suhocki** [comment]
Hi @paulinon 

Here is a sample for the requested issue:
[remote-config-sample.zip](https://github.com/firebase/firebase-android-sdk/files/11763406/remote-config-sample.zip)

cc @barmaciej
