### ISSUE TITLE
Sample code to test ANR is actually being recorded by crashlytics

### ISSUE THREAD

**Issue by oddgames-david** [firebase/firebase-android-sdk#5046]
## What feature would you like to see?

Sample code to test ANR are actually being recorded by crashlytics. Currently I cannot see any ANR data being collected even though the play console has plenty for Android 11+ but we receive native crashes to crashlytics etc no problem.

## How would you use it?

Before uploading to google play to make sure crashlytics is actually receiving ANR data

**Comment by mrober** [comment]
I confirmed ANRs are working on the latest Crashlytics for Android 11+. Please file a new issue if you still do not see ANRs in Crashlytics with more details.
