### ISSUE TITLE
First_Open not working properly

### ISSUE THREAD

**Issue by beinghassandar1** [firebase/firebase-android-sdk#5084]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 Canary 8
  * Firebase Component: BOM  32.0.0

### [REQUIRED] Step 3: Describe the problem
We are trying to use `first_open` with Remote Config as a condition. We can see the `first_open` event being logged in realtime analytics. But when we try to apply the condition on Remote config to only get particular value for users who have `first_open` in last 2 days. It does not work. 

#### Steps to reproduce:
Install new app. It would log `first_open` in analytics. Then apply condition to a remote config to only send particular value to new users or first_open time range. It will not work.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hi @beinghassandar1. We might need to look at your configuration to see if this is an issue in the Firebase Console side. Could you reach out to our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact)? They'll be able to assist you further since they have visibility on the backend side, and you'll be able to share project details. Thanks!
