### ISSUE TITLE
Firebase In App Messaging Not Displaying on Specific Screen

### ISSUE THREAD

**Issue by SaketCG** [firebase/firebase-android-sdk#5087]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  Android Studio Electric Eel
  * Firebase Component: firebase-inappmessaging-display
  * Component version: firebase-bom:32.1.1

#### Steps to reproduce:

Please refer the link to this issue and this is the exact same issue I am facing. We have used
FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true) on the Splash screen and 
FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false) on the next screen i.e. the Home Screen but due to this usage of messageSuppressed method on Splash screen the message is not displayed on the Home Screen as well

https://github.com/firebase/firebase-android-sdk/issues/2027

#### Relevant Code:
 FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true/false)
```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hi @SaketCG, have you tried the [suggestion](https://github.com/firebase/firebase-android-sdk/issues/2027#issuecomment-709529887) of eldhosembabu?

So when you create your In-app messaging campaign, add a temporary trigger event say "show_pending" or something you prefer. Then after running `FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)` in your MainActivity, you may also call FirebaseInAppMessaging.getInstance().triggerEvent("show_pending"). This will allow your In-App Message to display immediately. Let me know if this works.

**Comment by SaketCG** [comment]
Hi @argzdev, have tried that as well but still the issue persists.

We have added an event called "home_screen_launched" and I am triggering the same in the Home screen after calling
FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false).

Please find the attached screenshot of the Firebase console In App Message configuration.

<img width="960" alt="Firebase_In_App_Event" src="https://github.com/firebase/firebase-android-sdk/assets/136801702/cf995a4b-7d95-43eb-8c9d-095eb888617f">

**Comment by argzdev** [comment]
There might be something wrong with your configuration. I've tried testing this with the version `32.1.1` and it works alright.

Relevant code:
```
class SplashActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        findViewById<TextView>(R.id.tv).text = "SplashScreen"

        FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true)

        GlobalScope.launch {
            delay(3000)
            runOnUiThread{
                startActivity(Intent(this@SplashActivity, MainActivity::class.java))
            }
        }
    }
}

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        
        FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)
        FirebaseInAppMessaging.getInstance().triggerEvent("show_pending")
    }
}
```
<img width="680" alt="Screenshot 2023-06-21 at 12 27 11 AM" src="https://github.com/firebase/firebase-android-sdk/assets/93124282/22afa94e-2062-426d-bb83-fa314bbe7015">

Could you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so we can investigate your issue further. Thanks.

**Comment by SaketCG** [comment]
Hi @argzdev, Thank you for the help. We are getting the In App Message now as I tested by publishing the campaign on the release APK. Earlier I was testing with Test device and hence it was not getting displayed as for Test devices it will be shown on "app_open" event itself as mentioned on the Firebase console.

**Comment by argzdev** [comment]
Awesome, that's great to hear. Thanks for sharing your findings, I'm sure this'll help future developers if they encounter this. That said, I'll go ahead and close this now. Feel free to let me know if you'd like this to be reopened. Thanks!
