### ISSUE TITLE
FCM topic subscription issue

### ISSUE THREAD

**Issue by ranatalaldev** [firebase/firebase-android-sdk#5153]
When the user unsubscribes to the FCM topic and re subscribes topic then sometimes a push notification work or sometimes not

**Comment by argzdev** [comment]
Hi @ranatalaldev, thanks for reaching out. To understand your problem, could you kindly create a new thread with the details from our template? This is necessary for us to conduct an initial investigation and properly address your issue. If possible please also provide detail how frequent this issue happens. Thanks!
