### ISSUE TITLE
FirebaseApp.delete() does not clean FirebaseSessions callbacks

### ISSUE THREAD

**Issue by carlonzo** [firebase/firebase-android-sdk#5186]
### [REQUIRED] Step 2: Describe your environment
  * Firebase Component: core module (firebase-common)
  * Component version: 20.3.3

### [REQUIRED] Step 3: Describe the problem

Hi, with the introduction of FirebaseSessions (not sure if this was the cause or the issue if more obvious now), we are not able to disable a `FirebaseApp` instance anymore. Before if was possible to do simply call `FirebaseApp.delete()` to remove the instance of the default app, but now I noticed that FirebaseSessions [here](https://github.com/firebase/firebase-android-sdk/blob/965ac2f45964a277046706dba712a7fc859f9d22/firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt#L77) register a listener that will require the initial default app to be alive. also, this listener leaves a leak to the FirebaseApp instance that was supposed to be removed. 

#### Steps to reproduce:

- setup Firebase normally
- make sure that the`FirebaseInitProvider` is enabled and added to the manifest (this is by default, I know)
- in the Application.onCreate call `FirebaseApp.getInstance().delete()`
- this should be crashing as soon as the activity starts (or app in foreground?) and the FirebaseSessions callback is triggered

Side note: It would be nice if Firebase was allowing manual initialization of Firebase. The code is there but I dont find it supported anymore. I am aware we can disable the `FirebaseInitProvider` and manually init Firebase but this is breaking FirebasePerformance that doesnt collect anymore stats if not init by `FirebaseInitProvider`. maybe we could have a separate `FirebasePerfInitProvider` to enable the user to control the init step?

**Comment by argzdev** [comment]
Hi @carlonzo, sorry for the delayed response here. Just to clarify, with your provided steps, you're adding `FirebaseInitProvider` in the AndroidManifest.xml, specifically:
```
<provider
    android:name="com.google.firebase.provider.FirebaseInitProvider"
    android:authorities="${applicationId}.firebaseinitprovider"
    tools:node="remove"/>
```
So you can initialize FirebaseApp programmatically, right? And then once you try to remove `FirebaseApp` with `FirebaseApp.getInstance().delete()` this leaves a memory leak(?) and this happens on the latest version of `firebase-common`.

I've tried testing this and added leakcanary within my app, but I don't see any reports regarding a memory leak. Am I missing anything?
```
implementation platform('com.google.firebase:firebase-bom:32.2.0')
implementation 'com.google.firebase:firebase-perf-ktx'

debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.12'
```

Code snippet:
```
fun deleteBtn(view: View) {
    FirebaseApp.getInstance().delete()
}
fun createBtn(view: View) {
    FirebaseApp.initializeApp(this)
}
```

**Comment by argzdev** [comment]
Got it, thanks for the extra details @carlonzo, I was able to reproduce the same behavior. I'll notify our engineers and see what we can do.

**Comment by mrober** [comment]
This is fixed in the latest versions of Sessions and Crashlytics.

**Comment by carlonzo** [comment]
Thanks @mrober for the fix!
