### ISSUE TITLE
Firebase Realtime Remote Config onUpdate is still triggered when app is in Background

### ISSUE THREAD

**Issue by dhruvkaushal11** [firebase/firebase-android-sdk#5214]
I am using the remote config real-time feature, from the samples when I keep the App in the background (let's say pressing the home button) and then do changes in the Firebase Console dashboard. Then also I can check in logs that onUpdate() is being invoked.

Document says: 

> Although you can manually stop listening for updates, it's often not necessary. Real-time Remote Config automatically stops listening for updates when the app enters the background and restarts when the app is foregrounded.

But the connection remains even when the app is in the background. Can't this lead to battery drain?
I am calling this from my MainActivity OnCreate()
```
FirebaseRemoteConfig.getInstance().addOnConfigUpdateListener(object : ConfigUpdateListener {
            override fun onUpdate(configUpdate : ConfigUpdate) {
                Log.d("MainActivity", "Updated keys: " + configUpdate.updatedKeys);


            }

            override fun onError(error : FirebaseRemoteConfigException) {
                Log.w("MainActivity", "Config update error with code: " + error.code, error)
            }
        })
```

**Comment by argzdev** [comment]
Hi @dhruvkaushal11, I've gotten update from our engineers. So the specifics are, 
> when the app goes into the background the connection isn't immediately severed. Instead it is allowed to timeout, so after a maximum of 5 mins the connection should end.

Since this question has been answered, I'll be closing this issue now. Thanks!
