### ISSUE TITLE
Lack of ability to submit Crashlytics reports immediately and bug in background submission of non-fatal errors on Wear OS

### ISSUE THREAD

**Issue by uripre** [firebase/firebase-android-sdk#5234]
## What feature would you like to see?

After using reportException to report non fatal exceptions, I need the reports to be sent right away. Why? Because the user can just remove the app and never return. Or he/she can return in a day, week, month, who knows. How is it possible for this service to not offer such a rudimentary feature?

P.S calling sendUnsentReports does not help. I'm on Wear OS if that matters.

Edit: Further discussion below discovered non fatal errors would normally be sent in the background on Android devices, but not on Wear OS, due to a bug.

## How would you use it?

To report bugs and actually get the report.

**Comment by uripre** [comment]
Thank you @argzdev for the prompt response.

I have tested this quite extensively by both keeping the app open for an hour, and by closing it and waiting 3 hours+. Nothing seems to trigger the submission besides re-launching the app. I've been trying to provide support to some of my users, and had to explicitly ask them to relaunch the app because the non fatal reports weren't being sent for days.

**Comment by argzdev** [comment]
Sorry you're having a bad experience with our product. I was expecting the background network reports to submit at most in a few hours, not days. I'll try testing this on a wear OS, maybe there's a difference in doze or app standby state of background services of phones vs wear os.

**Comment by uripre** [comment]
@argzdev Thank you for looking into this! I'm quite relieved to hear that's not the expected behavior. Looking forward for a fix 🙏

**Comment by uripre** [comment]
Also related
https://github.com/firebase/flutterfire/discussions/6660

**Comment by uripre** [comment]
Hi @mrober, thank you for the reply.

I fully understand sendUnsentReports doesn't send the reports immediately. However, both I and whoever created the ticket I referenced (and you can find a few other such tickets/inquiries across the web) would like the option to send the reports immediately, and not only when the session is finalized. 

Separately, @argzdev and I discussed a potential problem specific to WearOS. He mentioned that even without relaunching the app, there should be a background network connection that takes care of sending the reports. However, on WearOS, it seems there might be a bug inhibiting this feature. Could you shed some light on whether this is a recognized issue, or is it an inherent design decision that I shouldn't get some of my bug reports?

**Comment by argzdev** [comment]
Hi @uripre, after further discussion, we understand that the behavior is somewhat not the same when comparing Android OS vs WearOS. But the issue falls within the scope that non-fatals will only try to submit the reports via background network connection post-crash, and does not guarantee success until the app is relaunched. 

As of the moment, we can't promise any timeline, or when this would be revisited, or if this is something that would change in the roadmap in the near future. 

That said, I'd like to ask for a favor for anyone else that encounters the same issue to kindly leave a thumbs up on the author's original post. This'll help us prioritize issues based on severity and demand.

**Comment by uripre** [comment]
Hi @argzdev. Thank you for taking it into a discussion.

I'm obviously not so thrilled about the decision. In my view, you offer a feature to report "non-fatal" exceptions (which can still be critical), and you support Wear OS. This bug essentially compromises the service you intend to deliver. Typically, service providers don't judge the significance of such issues merely based on the volume of requests vs other feature requests.

Furthermore, there is also the question of why you don't allow users to trigger an immediate submission (relevant to all platforms), especially since it sounds like a small 3 story-points task for someone who's familiar with the repo.

**Comment by redmanit** [comment]
I created an related issue at https://github.com/firebase/firebase-android-sdk/issues/5896

**Comment by johnglow** [comment]
In the real world apps are complicated. 1000s of lines of code.
Many users never restart their app.

After 8 errors the non fatal exceptions report get deleted.
Non fatal exceptions that we catch are only sent next time there is a fatal error or an app restart.
Calling sendUnsentReports only seems to apply to the previous session.
What this really means is that non fatal exceptions that we catch will never reach our Firebase Crashlytics dashboard. 
If a version of sendUnsentReports applied to the current session, or there was an option to send reports immediately, or we could trust firebase to send unsent reports once an hour, then this wouldn't be as much of an issue.

But currently Firebase Crashlytics seems unfit for purpose with this limitation of only sending on restarts on when encountering a fatal error.

Also software development companies don't always provide front line support for their app users. So suggesting to tell users to turn it off and again in an FAQ, whilst a classic phrase is only a partial solution.

Apologies if I've misunderstood any configuration options (Also we're on .NET Maui)

**Comment by mrober** [comment]
Closing this since the FR is open
