### ISSUE TITLE
Unable to Receive OTP Promptly and Inquiry About IP-Based Delays in Phone Number Authentication

### ISSUE THREAD

**Issue by qasim313** [firebase/firebase-android-sdk#5265]
I'm currently working on an Android app that employs Firebase Phone Authentication for user logins. The app serves as a communication platform between schools, parents, and faculty, facilitating crucial interactions and updates.

While implementing the phone number authentication flow, I've been facing an issue where some users, particularly parents who are assisted by school faculty, are experiencing delays or failures in receiving One-Time Passwords (OTPs) for verification. This inconsistency in OTP delivery is causing inconvenience and hindering the smooth user experience we aim to provide.

I've been trying to understand the root cause of this problem, and I'm curious if the issue might be related to a high volume of OTP requests originating from the same IP address. Since parents often connect to the school's internet to complete the verification process, could it be possible that the Firebase server's handling of multiple requests from the same IP address might lead to delays in OTP delivery?

I would greatly appreciate your insights on this matter. If there's a possibility that IP-based delays are contributing to this issue, I would love to explore potential solutions or best practices that can help mitigate this situation. It's important for us to ensure a seamless experience for our users, especially since this app serves a critical role in school-parent communication.

Thank you for your time and assistance. Your expertise would be invaluable in resolving this challenge and enhancing the effectiveness of our app.

**Comment by argzdev** [comment]
Hi @qasim313, thanks for reaching out. We're glad to hear that you're using our products for the education community. It seems to me that your questions might be more suited for our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact). They'll be able to assist you better since you can share with them your project details and configuration. Thanks!
