### ISSUE TITLE
Add record a fatal exception in FirebaseCrashlytics

### ISSUE THREAD

**Issue by pasmichos** [firebase/firebase-android-sdk#5273]
## What feature would you like to see?

Log a fatal exception from FirebaseCrashlytics like the non-fatal exception
Already Exist FirebaseCrashlytics.getInstance().recordException(e)

It could be
FirebaseCrashlytics.getInstance().recordFatalException(e)

## How would you use it?

I have an Android POS that is unattended in a Kiosk. I would like to create the application restart after the crash. In order to do that, I added the code below
[Code.txt](https://github.com/firebase/firebase-android-sdk/files/12421452/Code.txt)

After the crash the application opens but the crashlytics doesn't capture the crash because of exit system.
To fix I added the recordException before the exit and now I get the trace as Non-fatal but the crash is fatal and I can't change the type.

**Comment by argzdev** [comment]
Hi @pasmichos, thanks for reaching out. With your given code snippet:
```
class MainApplication: Application() {

    override fun onCreate() {
        super.onCreate()

        // Enable crashlytics - disabled by default
        Firebase.crashlytics.setCrashlyticsCollectionEnabled(true)

        // Assign crashlytics's uncaughtExceptionHandler as defaultHandler
        val defaultExceptionHandler = Thread.getDefaultUncaughtExceptionHandler()

        // Set this class as new default uncaughtExceptionHandler
        val newDefaultExceptionHandler = DefaultExceptionHandler(applicationContext, defaultExceptionHandler)
        Thread.setDefaultUncaughtExceptionHandler(newDefaultExceptionHandler)
    }
}


class DefaultExceptionHandler(
    private val context: Context,
    private val defaultExceptionHandler: Thread.UncaughtExceptionHandler?
) : Thread.UncaughtExceptionHandler {

    override fun uncaughtException(t: Thread, e: Throwable) {
        startNewTask(context)
        defaultExceptionHandler?.uncaughtException(t, e)
    }

    private fun startNewTask(context: Context) {
        thread(isDaemon = true, priority = Thread.MAX_PRIORITY) {
            val packageManager = context.packageManager
            val intent = packageManager.getLaunchIntentForPackage(context.packageName)
            val componentName = intent?.component
            val mainIntent = Intent.makeRestartActivityTask(componentName)
            context.startActivity(mainIntent)
            exitProcess(2)
        }
    }
}
```

Crashlytics should still be able to capture the crash. I've tested this with a sample kiosk app, and I'm able to receive crash reports. That said, could you provide a minimal reproducible example of your issue so we can investigate this further? Thanks

**Comment by pasmichos** [comment]
Hi @argzdev
Thanks for the back response.

I tested in 2 devices.
1) Android 7.1.1
[Android 7_1_1.txt](https://github.com/firebase/firebase-android-sdk/files/12453119/Android.7_1_1.txt)
[Android_7_1_1_with_record_exception.txt](https://github.com/firebase/firebase-android-sdk/files/12453122/Android_7_1_1_with_record_exception.txt)


2) Android 8.1.0
[Android_8_1_0.txt](https://github.com/firebase/firebase-android-sdk/files/12453124/Android_8_1_0.txt)
[Android_8_1_0_with_record_exception.txt](https://github.com/firebase/firebase-android-sdk/files/12453125/Android_8_1_0_with_record_exception.txt)

In the logs you will see that the application doesn't upload the fatal exception. Also with record exception it uploads.

Below the demo that I did the tests.

[DemoCrash.zip](https://github.com/firebase/firebase-android-sdk/files/12453132/DemoCrash.zip)

**Comment by pasmichos** [comment]
@argzdev !!! Thanks, it worked!

![image](https://github.com/firebase/firebase-android-sdk/assets/76706269/805b3b0c-9e8b-4f27-b28d-6b49012f8ff0)


Updated demo for the community.
[DemoCrash.zip](https://github.com/firebase/firebase-android-sdk/files/12454651/DemoCrash.zip)
