### ISSUE TITLE
Gradle plugin com.google.firebase.crashlytics Always-Run Tasks

### ISSUE THREAD

**Issue by aaleksievcmc** [firebase/firebase-android-sdk#5287]
### [REQUIRED] Step 2: Describe your environment

AS: Giraffe | 2022.3.1 Patch 1
Kotlin plugin: 223-1.9.0-release-358-AS8836.35.2231.10671973
Android Gradle Plugin: 8.1.1
Gradle: 8.1
Gradle JDK: Eclipse Temurin version 17.0.8
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)

### [REQUIRED] Step 3: Describe the problem

At 08:45, Aug 31, 2023, Android Studio detected the following issue(s) with Gradle plugin com.google.firebase.crashlytics

Always-Run Tasks
This task might be setting its up-to-date check to always return false.

Plugin: com.google.firebase.crashlytics
Task: injectCrashlyticsMappingFileIdDebug
Task type: com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask
Issues for the same task were detected in 1 module(s), total execution time was <0.1s (<0.1%), by module:
  Execution mode: FULL, time: <0.1s (<0.1%), determines build duration: true, on critical path: true, issues: Always-Run Tasks

====Build information:====
Execution date: 31/08/2023, 08:45
Total build duration: 87.1s
Configuration time: 0.3s (0.3%)
Critical path tasks time: 86.7s (99.5%)
Critical path tasks size: 25
AGP versions: 8.1.1
====Platform information:====
AI-223.8836.35.2231.10671973, JRE 17.0.6+0-17.0.6b829.9-10027231x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.4, screens 3840.0x1200.0

**Comment by argzdev** [comment]
Hi @aaleksievcmc, thanks for reaching out. Could you answer a few questions below:

1. What version of Firebase Crashlytics plugin did you encounter this issue? 
2. Can you share steps to reproduce this behavior?
3. Is there any code snippets related to Firebase Crashlytics needed to reproduce this issue?

Thanks!
