### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by tianshenyi** [firebase/firebase-android-sdk#529]
android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1488)
--
 android.app.ContextImpl.unbindService(ContextImpl.java:1638)
 android.content.ContextWrapper.unbindService(ContextWrapper.java:703)
 com.google.android.gms.common.stats.ConnectionTracker.void unbindService(android.content.Context,android.content.ServiceConnection)(Unknown Source:25)
com.google.android.gms.common.internal.zzf.void zzf(java.lang.String)(Unknown Source:41)
 com.google.android.gms.common.internal.zze.boolean handleMessage(android.os.Message)(Unknown Source:45)
 android.os.Handler.dispatchMessage(Handler.java:102)
 com.google.android.gms.internal.common.zze.void dispatchMessage(android.os.Message)(Unknown Source:8)
 android.os.Looper.loop(Looper.java:164)
 android.app.ActivityThread.main(ActivityThread.java:6765)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by NiaNingXue** [comment]
I have the same issue

**Comment by NiaNingXue** [comment]
@tianshenyi  hi, have you solved it?

**Comment by garbirel94** [comment]
the same

**Comment by ashwinraghav** [comment]
@tianshenyi our issue format helps us triage these effectively. Can you fill in the information we need to help you ? Feel free to close this and start a new issue .

**Comment by daidaijie** [comment]
the same too
