### ISSUE TITLE
App Distribution Plugin - serviceCredentialsFile is global

### ISSUE THREAD

**Issue by mandrachek** [firebase/firebase-android-sdk#5291]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Giraffe 2022.3.1 Patch 1
  * Firebase Component: App Distribution Gradle Plugin
  * Component version: 4.0.0
  * Android Gradle Plugin version: 8.1.1
  * Gradle version: 8.0.2

#### Steps to reproduce:

My application is configured to use product flavors, and to configure the firebase app distribution based on the product flavor, like so:

```kotlin
productFlavors {
    create("dev") {
        applicationIdSuffix = ".dev"
        dimension = "default"
        firebaseAppDistribution {
            artifactType = "APK"
            serviceCredentialsFile = "${project.rootDir}/config/keys/firebase-distribution.json"
            groups = "developers"
        }
    }

    create("qa") {
        applicationIdSuffix = ".qa"
        dimension = "default"
        firebaseAppDistribution {
            artifactType = "APK"
            serviceCredentialsFile = "${project.rootDir}/config/keys/firebase-distribution.json"
            groups = "qa"
        }
    }      
}
```

This has worked in a single firebase project, ~~and the right groups invited to the right builds~~.

Recently we decided to break our flavors out into separate firebase projects.  This means we need different serviceCredentialsFile values for each flavor. Thus we have the credential files split and different per product flavor, like so:

```kotlin
productFlavors {
    create("dev") {
        applicationIdSuffix = ".dev"
        dimension = "default"
        firebaseAppDistribution {
            artifactType = "APK"
            serviceCredentialsFile = "${project.rootDir}/config/keys/dev/firebase-distribution.json"
            groups = "developers"
        }
    }

    create("qa") {
        applicationIdSuffix = ".qa"
        dimension = "default"
        firebaseAppDistribution {
            artifactType = "APK"
            serviceCredentialsFile = "${project.rootDir}/config/keys/qa/firebase-distribution.json"
            groups = "qa"
        }
    }      
}
```

Unfortunately the app distribution plugin seems to be broken when it comes to the serviceCredentials file, as it appears to use the last serviceCredentialsFile configured in the build.gradle, rather than one specified for the flavor, so:

`./gradlew :app:appDistributionUploadDevDebug` prints:

`Using service credentials file specified by the serviceCredentialsFile property in your app's build.gradle file: .../config/keys/qa/firebase-distribution.json
`
When the path should be `/dev/`, not `/qa/`

This doesn't appear to be correct or in-line with the documentation.  As one cannot share .json based service credentials across different firebase projects, this is a significant problem.

PS. It would also be nice to have some documentation on how to configure per-variant (type + flavor).

**Comment by mandrachek** [comment]
I've been able to work around this temporarily by copying the individual service credentials file into a common location before running the appDistributionUpload tasks, like so:

```kotlin
// delete the common file
tasks.register("deleteFirebaseJson", Delete::class) {
    delete("${project.rootProject.projectDir}/config/keys/distribution.json")
}

// copy the file from the flavor specific folder to the common location.
tasks.register("devFirebaseJson", Copy::class) {
    dependsOn("deleteFirebaseJson")
    from("${project.rootProject.projectDir}/config/keys/dev")
    into("${project.rootProject.projectDir}/config/keys")
}

tasks.register("qaFirebaseJson", Copy::class) {
    dependsOn("deleteFirebaseJson")
    from("${project.rootProject.projectDir}/config/keys/qa")
    into("${project.rootProject.projectDir}/config/keys")
}

afterEvaluate {
    tasks.findByName("appDistributionUploadDevDebug")?.dependsOn("devFirebaseJson")
    tasks.findByName("appDistributionUploadDevRelease")?.dependsOn("devFirebaseJson")
    tasks.findByName("appDistributionUploadQaDebug")?.dependsOn("qaFirebaseJson")
    tasks.findByName("appDistributionUploadQaRelease")?.dependsOn("qaFirebaseJson")
}
```

But this really shouldn't be necessary.

**Comment by mandrachek** [comment]
Actually, it looks like the groups have the same problem. We just never noticed it before since all our groups were shared on the same project.  It doesn't respect the per-product flavor configuration!!!

**Comment by argzdev** [comment]
Hi @mandrachek, thanks for reaching out. Not sure what I'm missing here, I'm unable to reproduce the same behavior with your provided source code. I used groovy but I don't think that should matter.

Relevant code:
```
    signingConfigs {
        release {
            storeFile file(project.findProperty('release_signing_keystore') ?: "${project.rootProject.projectDir}/config/keys/debug.keystore")
            storePassword project.findProperty('release_signing_store_password') ?: 'android'
            keyAlias project.findProperty('release_signing_key_alias') ?: 'androiddebugkey'
            keyPassword project.findProperty('release_signing_key_password') ?: 'android'
        }
        debug {
            storeFile file("${project.rootProject.projectDir}/config/keys/debug.keystore")
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    flavorDimensions "default"
    productFlavors {
        dev {
            applicationIdSuffix = ".dev"
            dimension = "default"
            firebaseAppDistribution {
                artifactType = "APK"
                serviceCredentialsFile = "${project.rootDir}/config/keys/dev/credential-1.json"
                groups = "developers"
            }
        }
        qa {
            applicationIdSuffix = ".qa"
            dimension = "default"
            firebaseAppDistribution {
                artifactType = "APK"
                serviceCredentialsFile = "${project.rootDir}/config/keys/qa/credential-2.json"
                groups = "qa"
            }
        }
    }
```

<img width="1587" alt="Screenshot 2023-09-06 at 10 47 45 PM" src="https://github.com/firebase/firebase-android-sdk/assets/93124282/5f72c36a-42ac-43f3-87fe-38970ae19302">

<img width="1575" alt="Screenshot 2023-09-07 at 1 41 53 AM" src="https://github.com/firebase/firebase-android-sdk/assets/93124282/e566267b-45bf-42a1-a9f6-39a4ff975306">

Running `appDistributionUploadDevDebug` and then `appDistributionUploadQaDebug` both seems to point to the correct service credential file. I'm wondering if it's due to a configuration setup issue. That said, could you provide a minimal reproducible example so I can investigate this further? Thanks!
