### ISSUE TITLE
Firebase ML Kit Text Recognition Issues

### ISSUE THREAD

**Issue by abhishek084** [firebase/firebase-android-sdk#5302]
### Environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1 Patch 1
  * Firebase Component: Firebase ML Kit
  * Component version: 23.0.0

### Problem Statement
I am developing an Android application for card scanning using Firebase ML Kit with the following dependencies:

```
implementation 'com.google.firebase:firebase-core:16.0.0'
implementation 'com.google.firebase:firebase-ml-vision:23.0.0'

```
However, I am encountering several issues with Firebase ML Kit when scanning cards:

#### Font Compatibility Issue:
Firebase ML Kit fails to work with a specific font on the card called "Farrington 7B." Instead of recognizing digits, it produces unexpected English alphabets in the recognized text.

## Farrington 7B Font:
 ![image](https://github.com/firebase/firebase-android-sdk/assets/129366551/e00c68ae-5de6-4033-835c-334f10b55bb3)

![image](https://github.com/firebase/firebase-android-sdk/assets/129366551/ed49dffb-5427-4029-b07c-6a8345db2104)

#### Digit Misinterpretation: 
During scanning, Firebase ML Kit frequently misinterprets certain digits. For instance, it recognizes "5" as "6," "8" as "3," "7" as "1," and vice versa, leading to incorrect results.

#### Embossed Text Scanning: 
Firebase ML Kit struggles to effectively scan embossed text on most occasions, which is a crucial requirement for card scanning applications.

#### Performance Issues:
 The ML Kit either takes an excessively long time to recognize text or fails to scan text with a dense background, affecting the usability and reliability of the card scanning feature.

These issues pose significant challenges in accurately scanning and recognizing text from cards, and they impact the functionality of my application. I kindly request guidance or solutions to address these challenges with Firebase ML Kit for card scanning. Your assistance in resolving these issues would be greatly appreciated. 
Thank you.

**Comment by argzdev** [comment]
Hi @abhishek084, thanks for reaching out. Just for context, the `firebase-ml-vision` is a old/[deprecated](https://firebase.google.com/docs/ml/android/recognize-text-deprecated) version of the SDK. It is advised to use the more recent/updated version of the SDK. You can either use [Cloud Vision API](https://firebase.google.com/docs/ml/android/recognize-text) where it uses Cloud functions to interpret text from images; or you may also use the on-device text recognition [standalone ML kit library](https://developers.google.com/ml-kit/vision/text-recognition/v2/android). If you choose the latter option, this [quickstart](https://codelabs.developers.google.com/codelabs/mlkit-android#0) will definitely help you get started a lot faster.

That said, I did exhibit the same issue with the on-device text recognition of the standalone ML kit library. Where in my testing:

"1234 5678 9012 3456" 
was interpretted as:
"1234 5b18 9012 345b"

 so "6" was recognized as "b" and "7" was recognized as "1". However, from my understanding the ML kit is trained to a specific font style, and does not have a specific API for recognizing different font styles, as a result this interpretation is intended. I would recommend using a custom ML model that is trained to recognize credit card font style. For this, there are different options, but you may refer to our [documentation](https://firebase.google.com/docs/ml/train-image-labeler) for an in depth explanation of which option would fit your use case. Please note that these options are not on the Spark[free] plan.

That said, I'll be closing this issue now. Feel free to let me know if you want this thread to be reopened or if you have other concerns or questions. Thanks!
