### ISSUE TITLE
setPersistenceEnabled deprecated

### ISSUE THREAD

**Issue by rakshitsoni02** [firebase/firebase-android-sdk#5314]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Iguana | 2023.2.1 Canary 1

  * Firebase Component: 24.6.0

#### Relevant Code:

```
    /**
     * Enables or disables local persistent storage. The default is to use local persistent storage.
     *
     * @return A settings object that uses local persistent storage as specified by the given
     *     <tt>value</tt>.
     * @deprecated Instead, use {@link
     *     FirebaseFirestoreSettings.Builder#setLocalCacheSettings(LocalCacheSettings)} to configure
     *     SDK cache.
     */
    @NonNull
    @Deprecated
    public Builder setPersistenceEnabled(boolean value) {
      if (cacheSettings != null) {
        throw new IllegalStateException(
            "New cache config API setLocalCacheSettings() is already used.");
      }
      this.persistenceEnabled = value;
      this.usedLegacyCacheSettings = true;
      return this;
    }


firestoreSettings {
            setLocalCacheSettings(persistentCacheSettings {  }).build().cacheSettings
        }
```

**Comment by wu-hui** [comment]
You should be able to simply replace `persistentCacheSettings` with `memoryCacheSettings`.

**Comment by rakshitsoni02** [comment]
not sure with that, I need an alternative to the below code:

` val settings = firestoreSettings {
            isPersistenceEnabled = false
        }`

memoryCacheSettings is irrelevant here because I wanted to disable SQL lite persistence. 
Looking at the builder of persistentCacheSettings there is no **boolean** option to set this field however there is a private field `private boolean persistenceEnabled; ` but the builder function to update it is deprecated

**Comment by wu-hui** [comment]
`memoryCacheSettings` *is* how you disable SQLite. Firestore SDK *always* has a cache layer, `isPersistenceEnabled` simply controls whether the cache is from memory or SQLite(persistence).

**Comment by rakshitsoni02** [comment]
related issue & reason to disable persistence: [5001](https://github.com/firebase/firebase-android-sdk/issues/5001)

@wu-hui would you mind adding an example without using deprecated functions?

**Comment by wu-hui** [comment]
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt#L133 is an example to use memory cache (aka disable persistence).
