### ISSUE TITLE
firebase-bom renders no dependency from firebase-firestore-ktx to firebase-firestore-ktx

### ISSUE THREAD

**Issue by drindt** [firebase/firebase-android-sdk#5339]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: #AI-231.9392.1.2311.10779794
  * Firebase Component: Firestore
  * Component version: 24.8.0

#### Steps to reproduce:
I define in my build.gradle.kts the `firebase-firestore-ktx` and the `firebase-bom` where the bom defines version `32.3.0`. This includes then the  `firebase-firestore-ktx` with version `24.8.0`.

#### Relevant Code:
By using this version, this construct no longer work:
```
val firestore = Firebase.firestore
```
You need to declare `firebase-firestore` in the dependencies too. Which was not required before in version `32.2.3`.
This doesn't match to the statement here:
https://firebase.google.com/docs/android/learn-more#ktx

**Comment by argzdev** [comment]
Thanks for reporting, @drindt. I was able to reproduce the same behavior. Let me notify our engineers and see what we can do about this.

**Comment by szykam** [comment]
Problem with new BOM may be broader as I had same issue with `com.google.firebase:firebase-crashlytics-ktx`. With `32.3.0` I had to add `com.google.firebase:firebase-crashlytics` dependency.

**Comment by thatfiredev** [comment]
Sorry that you folks ran into this.
FYI The issue happens with the following libraries:

- `firebase-crashlytics-ktx`
- `firebase-firestore-ktx`
- `firebase-inappmessaging-ktx`
- `firebase-inappmessaging-display-ktx`

A fix has been merged in #5337 and a new version of the BoM should be released soon.

**Comment by thatfiredev** [comment]
Hey all,
This has been fixed in the [Firebase BoM 32.3.1](https://firebase.google.com/support/release-notes/android#bom_v32-3-1)
Thanks for you patience!

**Comment by drindt** [comment]
That was more than quick, thank you guys.
