### ISSUE TITLE
Wrong Remote Config values are being sent to some users/devices.

### ISSUE THREAD

**Issue by SiddhantPanhalkar** [firebase/firebase-android-sdk#5358]
#### Environment

  * Android Studio version: Android Studio Flamingo | 2022.2.1
  * Firebase Component: Remote Config
  * Component version: 21.1.1

#### Problem Statement

We have an app with approximately 100 million users, and we're encountering an issue related to a Firebase Remote Config key. This key contains JSON values that depend on different conditions, such as the app package or platform, for both Android and iOS.

Somehow, Firebase Remote Config is erroneously pushing iOS-specific values to Android devices. In our recent release, we attempted to log the values being sent by Firebase Remote Config for this particular key, and we discovered that the JSON element retrieved from Firebase is tailored for iOS devices, which should only be applicable to iOS users/devices.

This issue predominantly affects users of Pixel, Xiaomi, Vivo, Oppo, Samsung, Realme, and Infinix devices, encompassing various Android versions ranging from Android 6 to 13.

We have also checked the number of fetches happening from the Firebase Remote Config server, and it seems to be significantly lower than our current user base, consistently hovering around 6 million whenever we update the Remote Config values on the dashboard.

#### Steps to reproduce:

We couldn't reproduce this issue on the devices that we have. Consequently, we attempted to address the problem by logging the Firebase Remote Config values in our error monitoring system. Through this logging process, we determined that the values being received are specific to iOS. We also tried changing the conditions from platform to app package specific on the firebase dashboard, but it didn't worked.

#### Relevant Code:

<img width="429" alt="Screenshot 2023-09-26 at 11 38 11 AM" src="https://github.com/firebase/firebase-android-sdk/assets/13965772/5f3bae79-5bd4-4a90-a654-420d64558e9c">

The JSON object displayed in the screenshot originates from an iOS-specific conditional value configured within the Firebase dashboard.

![screenshot_2023-09-22_at_12 31 15_pm~2](https://github.com/firebase/firebase-android-sdk/assets/13965772/759f608b-4f21-49e9-9609-f9fdb2f65b54)

**Comment by argzdev** [comment]
Hi @SiddhantPanhalkar, looks like this might be a backend issue. I would expect the SDK to only act as a receiving end of the config values. The SDK team is very limited to investigating this given that there's no reproducible example or code snippet, and we do not have access to backend resources. That said, could you file an issue to the [Firebase support team](https://firebase.google.com/support/troubleshooter/contact)? You'll be able to share your project details and configuration with them, and they'll be able to assist you better. Thanks!
