### ISSUE TITLE
The injectCrashlyticsBuildIds*** Gradle task depends on the merge***NativeLibs task implicitly

### ISSUE THREAD

**Issue by sergiandreplace** [firebase/firebase-android-sdk#5371]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1 (Runtime version: 17.0.6+0-17.0.6b829.9-10027231 aarch64)
  * Gradle version: 8.3
  * Crashlytics Gradle Plugin version: 2.9.9

#### Steps to reproduce:

Gradle build fails when building an Android project which uses Crashlytics with NDK integration.

```
org.gradle.internal.execution.WorkValidationException: A problem was found with the configuration of task ':app:mergeReleaseNativeLibs' (type 'MergeNativeLibsTask').
  - Gradle detected a problem with the following location: '/Users/sergi/dev/ij/android-ij--app/app/build/intermediates/merged_native_libs/release/out'.
    
    Reason: Task ':app:injectCrashlyticsBuildIdsDebug' uses this output of task ':app:mergeReleaseNativeLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':app:mergeReleaseNativeLibs' as an input of ':app:injectCrashlyticsBuildIdsDebug'.
      2. Declare an explicit dependency on ':app:mergeReleaseNativeLibs' from ':app:injectCrashlyticsBuildIdsDebug' using Task#dependsOn.
      3. Declare an explicit dependency on ':app:mergeReleaseNativeLibs' from ':app:injectCrashlyticsBuildIdsDebug' using Task#mustRunAfter.
 ```

This is a duplicate of issue #5083, it was closed as resolved in 2.9.7, but still fails in 2.9.9 so I'm reopening it as a new issue.

**Comment by argzdev** [comment]
Hi @sergiandreplace, thanks for reaching out. I initially thought there was an issue using Gradle version 8.3, but upon my testing, with Crashlytics Gradle Plugin version `2.9.7` and `2.9.9`, both seems to work alright. I've also tried Android Studio Giraffe, Hedgehog, and Canary, all with the same result. That said, I'm suspecting that there might be a difference in the project configuration. Could you share code snippets of your configuration to see if there's anything that might help us investigate this further. Also if there's any chance you could share us a minimal reproducible example, it'll greatly speed up the investigation. Thanks!

**Comment by sergiandreplace** [comment]
We have a huge configuration with several plugins shared among other projects. Let me do some tests in order to reduce the possiblities and I'll get back to you.

Meanwhile, these are the changes done in order to configure NDK crashes into Crashlytics:

app/build.gradle.kts
```
import com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsExtension

...

  buildTypes {
    named("debug") {
      // other configurations
      configure<CrashlyticsExtension> {
        nativeSymbolUploadEnabled = true
        unstrippedNativeLibsDir = "build/intermediates/merged_native_libs/release/out/lib"
      }
    }

    named("release") {
      // other configurations
      configure<CrashlyticsExtension> {
        nativeSymbolUploadEnabled = true
        unstrippedNativeLibsDir = "build/intermediates/merged_native_libs/release/out/lib"
      }
...
dependencies {
 // other dependencies
  implementation(libs.google.firebase.crashlytics.ndk)
  implementation(libs.google.firebase.analytics.ktx)
}
```

gradle/libs.versions.toml
```
...
google-firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
...
```

**Comment by sergiandreplace** [comment]
Ok, shame moment, after sharing with other apps team they noticed that our debug configuration is using release path for unstrippedNativeLibsDir. I've fixed it and... worked like a charm.

So it was my mistake 😭 . Sorry for it and thanks for the support.

![tenor-265043992](https://github.com/firebase/firebase-android-sdk/assets/541020/51ec7d80-5daa-4119-a558-85b2fe387687)

**Comment by argzdev** [comment]
That's perfectly alright! I'm glad you were able to resolve the issue. I'll close this thread now. Thanks for the updates!
