### ISSUE TITLE
Issue on crachlystics : #00 abs c36711e3 virt 003ae1e3 _kDartIsolateSnapshotInstructions+0x5

### ISSUE THREAD

**Issue by hisham-safade** [firebase/firebase-android-sdk#5379]
I have this issue in Firebase crashlystics and it is repeated many times, but there is no specified line number,
how can I fix it,

#flutter

**Comment by argzdev** [comment]
Hi @hisham-safade, thanks for reaching out. Could you file a report to the [flutter team](https://github.com/firebase/flutterfire)? They'll be able to assist you with your issue. Thanks!
