### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Muhammad-Fazan** [firebase/firebase-android-sdk#5380]
What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-installations:17.1.4.
     Required by:
         project :app > com.google.firebase:firebase-bom:32.2.3
      > Could not resolve com.google.firebase:firebase-installations:17.1.4.
         > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-installations/17.1.4/firebase-installations-17.1.4.pom
            > Content is not allowed in prolog.
      > Could not resolve com.google.firebase:firebase-installations:17.1.4.
         > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-installations/17.1.4/firebase-installations-17.1.4.pom
            > Content is not allowed in prolog.
      > Could not resolve com.google.firebase:firebase-installations:17.1.4.
         > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-installations/17.1.4/firebase-installations-17.1.4.pom
            > Content is not allowed in prolog.
      > Could not resolve com.google.firebase:firebase-installations:17.1.4.

**Comment by argzdev** [comment]
Hi @Muhammad-Fazan, in order for us to conduct a proper initial investigation. We require details from our template. That said, please file a new issue with the necessary details so that we may assist you better. Thanks!
