### ISSUE TITLE
In-app tester feedback feature from Firebase App Distribution unable to take screenshots in Flutter apps

### ISSUE THREAD

**Issue by foxanna** [firebase/firebase-android-sdk#5386]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: `Android Studio Giraffe | 2022.3.1 Patch 2`
  * Firebase Component: `firebase-appdistribution`
  * Component version: `16.0.0-beta10`
  * Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

### [REQUIRED] Step 3: Describe the problem

In-app testers' feedback feature is unable to take a screenshot of the Flutter app. Instead, a black rectangle is shown. Attaching an image from the gallery works as expected.
Here is the video of the problem:

https://github.com/firebase/firebase-android-sdk/assets/1845144/eea6fa29-363b-40de-a7fe-bedbde806fed

The same results are delivered to the Firebase App Distribution dashboard:

<img width="350" alt="Screenshot 2023-10-08 at 15 35 55" src="https://github.com/firebase/firebase-android-sdk/assets/1845144/843c99b0-187e-457b-b351-fb8a7bf63c55">
<img width="350" alt="Screenshot 2023-10-08 at 15 36 07" src="https://github.com/firebase/firebase-android-sdk/assets/1845144/57b479aa-34f1-4fad-aec7-2996c2d6b211">

#### Steps to reproduce & Relevant Code:

I prepared a [repository](https://github.com/foxanna/flutter_app_firebase_feedback_demo) where this problem is reproducible. 
The [README file](https://github.com/foxanna/flutter_app_firebase_feedback_demo#readme) contains all the steps I performed so it's easy to validate if the problem is on the SDK side or in my implementation.

**Comment by argzdev** [comment]
Hi @foxanna, thanks for reaching out. I tested this on our native android with activities/fragments, or with jetpack compose and it's working alright. That said, I think the issue might be due to the flutter wrapping. Please reach out to the https://github.com/firebase/flutterfire. They'll be able to assist you better. Thanks.
