### ISSUE TITLE
DocumentSnapshot.toObject() always returns default boolean value

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/firebase-android-sdk#544]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.1
  * Firebase Component: Firestore
  * Component version: 20.0.0

### [REQUIRED] Step 3: Describe the problem

I have created a Kotlin data class to be written to Cloud Firestore. This class has a `boolean` attribute named `foo` with the default value set to `true`. When I call `DocumentSnapshot.toObject()`, the returned value is always `true`, even if the value stored in firestore is `false`.

#### Steps to reproduce:

1. Create the User data class (see code in section below) with the default values (I've also tried using an empty constructor instead, but the result is the same).
2. Write some data to firestore `[{foo = true, bar=1}, {foo = false, bar=2}]`
3. Read this data using a Query (relevant code below)
4. Check the shown result: `[{foo = true, bar=1}, {foo = true, bar=2}]`

(I've also tried changing the default value to false. Every document then shows `foo=false`)

#### Relevant Code:

User data class:
```kotlin
data class User(val foo: Boolean = true, val bar: Int = 0)
```

Using empty constructor:
```kotlin
data class User(
    val foo: Boolean,
    val bar: Int
) {
    constructor(): this(true, 0)
}
```

Query:
```kotlin
val query = FirebaseFirestore.getInstance().collection("users").orderBy("bar")
query.get().addOnSuccessListener { querySnapshot ->
    for (document in querySnapshot.documents) {
        val user = document.toObject<User>()
        if (user != null) {
            print(user.foo) // Always prints true
        }
    }
}
```

**Comment by var-const** [comment]
Thank you for a detailed report! I will try to reproduce the issue and will post here when I have an update.

**Comment by var-const** [comment]
@vkryachko Vlad, adding you to the thread in case you have any idea on what might be happening here.

**Comment by vkryachko** [comment]
I was unable to repro the issue, the values correctly roundtrip via the `CustomClassMapper` and `DocumentSpanshot` test utils, @var-const could the issue be somewhere in persistence?

**Comment by schmidt-sebastian** [comment]
@rosariopfernandes I just spent some time looking at this. I am definitely not a Kotlin expert, but can you verify your syntax for the code snippet you posted? To make it compile, I had to change it to 

```
document.toObject(User::class.java)
```

If I make this change, the deserialization works as expected.  Can you see if the code snippet in https://firebase.google.com/docs/firestore/query-data/get-data#custom_objects works for you?

If you still encounter this issue, it would help us if you could create a small sample project.

**Comment by rosariopfernandes** [comment]
@schmidt-sebastian  I'm actually using [firestore-ktx](https://github.com/firebase/firebase-android-sdk/tree/master/firebase-firestore/ktx), hence the different syntax. 

Sure, I'll try reproducing the problem on a small project.

**Comment by rosariopfernandes** [comment]
@schmidt-sebastian @var-const @vkryachko I've created a small project to see if I could reproduce the problem. Fortunately or not, I couldn't. I'll investigate what happened in my previous project, where I encountered this issue.

**Comment by schmidt-sebastian** [comment]
Thanks! Feel free to re-open this should this issue surface again.

**Comment by ahmedAlmasri** [comment]
+1
