### ISSUE TITLE
crashlytics is not compliant with market policies 

### ISSUE THREAD

**Issue by ber4444** [firebase/firebase-android-sdk#5490]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: hedgehog
  * Firebase Component: crashlytics
  * Component version: firebase-bom:32.4.0

#### Steps to reproduce:

Similar to https://github.com/firebase/firebase-android-sdk/issues/4045, you have introduced `getRunningAppProcesses()` in this module, which triggers flags from security scans.

Recommendation
Due to its deprecation, do not use the getRunningAppProcesses() method on production builds. If the method is being used for debugging purposes, safely use it on preproduction builds only.

Furthermore, on API level 23 and later, the getRunningAppProcesses method only returns the current App’s process, instead of all the running processes (including processes that belong to other Apps).

As of 2014, Google began classifying Apps that collect the list of Apps on the device as Spyware, as described on page 29 of the [2014 Android Security Report](https://source.android.com/security/reports/Google_Android_Security_2014_Report_Final.pdf):

"Throughout 2014, we have regularly tightened the definition of Spyware, for example in 2014 we began to classify applications that send the list of other applications on the device as Spyware."

Lastly, a list of SDKs that have already been blocked by Google Play because of this issue can be found [here](https://stackoverflow.com/questions/27044517/notification-from-google-play-store).

#### Relevant Code:

As per the finding, the above method is called in `com.google.firebase.crashlytics.internal.common.SessionReportingCoordinator`.

**Comment by mrober** [comment]
Hi @ber4444 thanks for reporting this.

Are you talking about the unreleased change #5445 ? This is not ready for release yet as we still have more testing and validation to do. It is part of an effort to better support multi-process apps in Firebase, specifically to get more reliable session details for multi-process apps to use in statistics like crash free sessions. We will be careful not to violate any privacy or security issues.

Or are you talking about the existing behaviour in previously released versions of Crashlytics? We have been using that API to detect background crashes. That has been in the SDK for a long time and I am unaware of it causing any security policy violations or triggering on security scans, but I will double check with our team.

**Comment by ber4444** [comment]
We have more findings for this in the following:
```
De-Obfuscated class: com.google.firebase.perf.FirebasePerfEarly

This finding was identified within the following SDKs:
Firebase Analytics
FirebaseAnalytics
```
