### ISSUE TITLE
How does the FCM SDK generate a token in Android?

### ISSUE THREAD

**Issue by sankar-gp** [firebase/firebase-android-sdk#5493]
### [READ] How does the FCM SDK generate a token in Android?

Can you please explain how the Firebase Cloud Messaging SDK generates a token in Android Devices.

Is that token generated by the Firebase Cloud Messaging SDK or by the Android OS notification service? Could you kindly explain this?

**Comment by argzdev** [comment]
Hi @sankar-gp, thanks for reaching out. The FCM SDK does not rely on the Android OS notification service to generate a registration token. The SDK makes requests to the server to retrieve a registration token. This is generated using the details of your Firebase project, specifically GCM sender ID, app ID, or project ID. 

You may also be able to check this within our source code:

https://github.com/firebase/firebase-android-sdk/blob/3c7a382f12e306998ec63c63bcb834be25fb9998/firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java#L605-L608

Let me know if this helps with your questions. Thanks!

**Comment by argzdev** [comment]
Closing this question, since I believe no clarification is needed.
