### ISSUE TITLE
Intermittent issue in receiving push notification because the users are unable to retrieve token at their end.

### ISSUE THREAD

**Issue by shakunm1** [firebase/firebase-android-sdk#5496]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: EEL
  * Firebase Component: Messaging & Core.
  * Component version:    
                                     implementation 'com.google.firebase:firebase-core:20.1.0'
                                     implementation "com.google.firebase:firebase-messaging:23.0.0"

### [REQUIRED] Step 3: Describe the problem
We have been receiving complaints from the end users that they are not receiving the push notifications. When we debugged at our end, we found that the token was not generated at the user end. Once the customer clears the cache/ re-install the build he is able to get the notifications and the feature is working as expected.

We would like to know the root cause of this problem as we cannot convey the user to clear cache/re-install the build every time. The same users have been facing the same problem at different interval. Kindly help us on the solving this issue.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
In build.gradle we have added below dependencies:
           implementation 'com.google.firebase:firebase-core:20.1.0'
           implementation "com.google.firebase:firebase-messaging:23.0.0"

We have a Service class which implements the FirebaseMessagingService. In the service class, we are overriding onNewToken method and expecting the token to be generated and it has been sent to our server along with storing at local. We have followed the best practices mentioned in https://firebase.google.com/docs/cloud-messaging/manage-tokens document.

Note : We are updating/refreshing the tokens every 15 days interval.

```
// TODO(you): code here to reproduce the problem
```

Kindly let us know what could be the root cause of this intermittent problem to arrive at the conclusion.

**Comment by argzdev** [comment]
Hey @shakunm1, sorry for the delayed response here. Let's try to narrow down the issue. Could you share code snippets of your usage with Firebase Cloud Messaging, particularly with how you initialize/generate or use the tokens. This will help us investigate if this issue is due to SDK concern or backend related problem. If you're also able to share a [minimal reproducible example](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean), then that'll help speed up our investigation further. 

Also I'm curious about this issue where the same set of users are encountering this problem. Do you notice any similarities between these users, such as android version, device specifications, or any other details that you think might be helpful for us.

Thanks!

**Comment by vknow360** [comment]
I don't have a real device with Nougat so I tested on emulators (having play services) and found that token is not generating there and thus unable to receive notifications.

**Comment by shakunm1** [comment]
@argzdev Thanks for your response. Will share the details shortly. Kindly keep the ticket open.

**Comment by argzdev** [comment]
Hey @shakunm1, I noticed a problem with your code. It seems to me that you're returning `deviceFcmToken` while the retrival of `FirebaseMessaging.getInstance().token` is still running. You could try adding `.await()` to make sure it retrieves a value before returning the token:

```kotlin
FirebaseMessaging.getInstance().token.addOnCompleteListener { task ->
    if(task.isSuccessful) {
        deviceFcmToken = task.result
        //Stores in local.
        //if not logged in, then store locally 
        //or
        //Update the token to server and store locally with timestamp too.(updateFCMTokenToServer)
     } else {
         //We are just logging the exception.
     }
 }.await() // add this
 return deviceFcmToken
```

However you'll need to call this inside a coroutine. Let me know if this helps. Thanks!
