### ISSUE TITLE
Realtime Database connection is lost when app is disconnected from WiFi and reconnected back again

### ISSUE THREAD

**Issue by ablbol** [firebase/firebase-android-sdk#5510]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____(Android SDK version 30.0.3)
  * Firebase Component: _____ (Database)
  * Component version: _____

#### Steps to reproduce:

I have a Flutter app that is running on real Android device with Firebase emulator.  I followed [documentation](https://firebase.google.com/docs/database/flutter/offline-capabilities) to detect user presence.  Here is the code from the docs:

```
final connectedRef = FirebaseDatabase.instance.ref(".info/connected");
connectedRef.onValue.listen((event) {
  final connected = event.snapshot.value as bool? ?? false;
  if (connected) {
    debugPrint("Connected.");
  } else {
    debugPrint("Not connected.");
  }
});
```
The problem starts when I disconnect the app from WiFi then reconnect.  I noticed that I loose the connection to the Realtime Database even though I am connected back to WiFi.  I also noticed that since I no longer have the Realtime Database connection, the document I am interested in has the right data in the app memory but not in the Realtime Database emulator.

This is how I am listening to the document that I am interested in:

```
    FirebaseDatabase.instance.ref('users/$uid').onValue.listen((event) {
      debugPrint('data: ${event.snapshot.value}');
    });

```

I expect that the Realtime Database connection to come back after reconnecting to WiFi.

I also noticed that when I use the following command, the app crash even though the command is executed once.

```
FirebaseDatabase.instance.setPersistenceEnabled(true);
```
#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
See the code above
```

**Comment by argzdev** [comment]
Hey @ablbol, thanks for bringing this up to our attention. I was able to reproduce the same behavior. In my case I used a native android app to test. The problematic behavior is only present when testing locally on Firebase Emulators, it seems to work fine when connected to the remote project. Let me reach out to our engineers to see if this is an issue with the Firebase emulators or with the Firebase Android RTDB SDK.

**Comment by argzdev** [comment]
Hi @ablbol, after further investigations, we've narrowed down that this issue might be more related to our Firebase emulator. That said, could you reach out to our [Firebase tools team](https://github.com/firebase/firebase-tools/issues)? They handle issues related to our Firebase Emulators and CLI. They'll be able to look into this further.

Thanks!
