### ISSUE TITLE
I Added Custom Traces for My App, and While Timings Appear Fine, I'm Observing 0 Sessions for Most of the Traces. Considering My App Is in Production, It's Unlikely That Data Is Less Than 1%

### ISSUE THREAD

**Issue by shrutipatil13798** [firebase/firebase-android-sdk#5519]
All the data related to Firebase is working fine for the app. However, the only issue I'm encountering is related to monitoring custom code in my app. I want to trace sessions by adding code before starting the trace and after stopping the trace. My expectation is that it should trace sessions, at least randomly, for these custom traces.

The problem is that when I check the data for an app that has been in production for over a month, I notice that there are no sessions recorded for most of the custom traces.

Please suggest a solution."

This revised version is grammatically correct and conveys the issue clearly.

Version :
 firebase_crashlytics: ^3.3.3
  firebase_messaging: ^14.6.3
  firebase_auth: ^4.6.3
  firebase_performance: ^0.9.2+3
  firebase_app_check: ^0.2.0+1
  firebase_dynamic_links: ^5.3.3

**Comment by argzdev** [comment]
Hey @shrutipatil13798, thanks for reaching out. It seems to me that the versions you've listed are from flutter. That said, could you reach out to the [flutterfire](https://github.com/firebase/flutterfire) team? They'll be able to assist you better with your concern. Thanks!
