### ISSUE TITLE
Remote config crashes the app on fetch

### ISSUE THREAD

**Issue by hcknl** [firebase/firebase-android-sdk#5540]
* Android Studio Giraffe | 2022.3.1 Patch 2
  * firebase-bom:32.2.0
  * firebase-config-ktx

#### Steps to reproduce:

Remote config fetchAndActivate crashes the application if I access the Task.getResult inside onCompleteListener.

specs: no wifi, no mobile connection is available, clear app cache. (does not crash when you are on airplane mode)

Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.remoteconfig.FirebaseRemoteConfigClientException: The client had an error while calling the backend!
       at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:3)

Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.remoteconfig.FirebaseRemoteConfigClientException: Firebase Installations failed to get installation auth token for fetch.
       at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:3)
       at myclasses.init$lambda$1(MyClassImpl.kt:41)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)

#### Relevant Code:

```
// DOES CRASH
  remoteConfig.fetchAndActivate()
            .addOnCompleteListener {
                if (it.isSuccessful) {
                    Timber.d("FirebaseRemoteConfig - Successful ${it.result}")
                } else {
                    Timber.d("FirebaseRemoteConfig - Failed ${it.result}")
                }.addOnFailureListener {
                Timber.d("FirebaseRemoteConfig - Exception ${it.message}")
            }


// DOES NOT CRASH
  remoteConfig.fetchAndActivate()
            .addOnSuccessListener {
                Timber.d("FirebaseRemoteConfig - Successful")
            }.addOnFailureListener {
                Timber.d("FirebaseRemoteConfig - Exception")
            }
```

**Comment by argzdev** [comment]
Hi @hcknl, thanks for reaching out. From my testing, I'm unable to reproduce this behavior you're encountering. According to your stacktrace, specifically `FirebaseRemoteConfigClientException: The client had an error while calling the backend!
`, this issue is normally due to poor internet connectivity. If however, this is not the case, could you provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? Also is this issue consistently reproducible? Thanks!
