### ISSUE TITLE
Provide more details for SENDER_ID_MISMATCH if I have permission to see across projects

### ISSUE THREAD

**Issue by denkc** [firebase/firebase-android-sdk#5545]
## What feature would you like to see?

As a developer, I'd like to be able to verify an ID token across all projects that I have access to in Firebase.  There is an existing API to do so today but requires specifying a project ID and providing the correct credentials for each project.

https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_the_firebase_admin_sdk

## How would you use it?

During debugging, the SENDER_ID_MISMATCH response tells you that a token is registered against a different project than it's being used for, but does not tell you what project it is.  Since the Firebase portal knows which projects I already have access to, it would be helpful to have this built into the Firebase portal where, if I have access to the project, it can tell me the project it is registered to.  Often, we will have dev/prod Firebase projects and provide the config during build time; this would help us debug the issue if they got mixed up.

**Comment by argzdev** [comment]
Hi @denkc, thanks for reaching out. It seems to me that you might want this feature on the Admin SDK. Could you reach out to our [Firebase Admin SDK](https://github.com/firebase/firebase-admin-node/issues) team and file this feature request? Thanks!
