### ISSUE TITLE
UnstrippedNativeLibsDir no longer supports multiple directories

### ISSUE THREAD

**Issue by eric-klukovich** [firebase/firebase-android-sdk#5559]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1 Patch 1
  * Firebase Component: Crashlytics Gradle Plugin
  * Component version: 
     * Current: `2.9.2`
     * Updating to:`2.9.9`

### [REQUIRED] Step 3: Describe the problem
We are currently on the 2.9.2 version of the Crashlytics Gradle plugin and when attempting to update to version 2.9.9, we are experiencing an error with having multiple directories for the `unstrippedNativeLibsDir` field in our build.gradle. This is the stacktrace after updating:
```
Could not determine the dependencies of task ':app:mergeStandardDebugResources'.
> Could not create task ':app:injectCrashlyticsBuildIdsStandardDebug'.
   > Cannot convert the provided notation to a File or URI: file collection.
     The following types/formats are supported:
       - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
       - A String or CharSequence URI, for example 'file:/usr/include'.
       - A File instance.
       - A Path instance.
       - A Directory instance.
       - A RegularFile instance.
       - A URI or URL instance.
       - A TextResource instance.
```
This is the firebaseCrashlytics block in our build.gradle:
```
firebaseCrashlytics {
    nativeSymbolUploadEnabled true
    unstrippedNativeLibsDir files(
          file("..."),  // Different module
          file("...").  // Directory with third party symbols
    )
}
```
The current documentation [here](https://firebase.google.com/docs/crashlytics/ndk-reports#alternative-options-symbol-uploading) says that the `unstrippedNativeLibsDir` with multiple directories is supported:
```
Multiple directories for a single build flavor by providing a list or FileCollection instance
```

I have tried all versions >2.9.2 and still encountering this issue. The change logs also do not indicate changes around supporting multiple directories.

#### Steps to reproduce:
Use Crashlytics Gradle plugin version 2.9.9 and set the `unstrippedNativeLibsDir` with multiple files.

Happy to provide any additional information!

**Comment by marcelwooga** [comment]
Having the same issue, any news on it?

**Comment by mrober** [comment]
I have a hunch that this broke when we did another change to support multiple flavors building in parallel mode.

We are working on the next major version of the Crashlytics Gradle plugin, and have a prerelease you can find it in #5733. This version has several improvements to support native apps, including a better behaving `unstrippedNativeLibsDir`. It is now accumulative, so you could set some dirs in flavors, some in build types, etc.

I verified that it does support multiple dirs locally by doing something like this:

```kotlin
    create("prod") {
      configure<CrashlyticsExtension> {
        nativeSymbolUploadEnabled = true
        unstrippedNativeLibsDir = arrayOf("a", "b", "c")
      }
    }
```

And I will add a functional test for this use case to prevent another regression.

The `unstrippedNativeLibsDir` field will accept any valid argument to [org.gradle.api.Project.files](https://docs.gradle.org/8.1/javadoc/org/gradle/api/Project.html#files-java.lang.Object...-).

Please let me know if this resolves your issue, or if you have any feedback about the prerelease version.

**Comment by eric-klukovich** [comment]
Thanks for replying @mrober! I will try out the pre-release and let you know how it works for us, hoping to get to this later this week.

**Comment by mrober** [comment]
This has been released.
