### ISSUE TITLE
Get Data problem 

### ISSUE THREAD

**Issue by erkocali1** [firebase/firebase-android-sdk#5561]
Hello, I am trying to get all the data of a collection, but I cannot do it.  in the code I posted, I can do the operation while trying to get all the data of a document in the fun fetchData function. So, while my fun fetchData function is working, my fetchArea() function is not working, can you help me?

class FireBaseSourceImpl @Inject constructor(private val database: FirebaseFirestore) :
    FireBaseSource {

    override suspend fun saveArea(dataModel: DataModel): Result<Unit> {

        return kotlin.runCatching {

            val post = hashMapOf(
                "message" to dataModel.message,
                "title" to dataModel.title,
                "photoUrl" to dataModel.photoUrl,
                "timeStamp" to dataModel.timestamp

            )

            database.collection("Users").document(dataModel.currentUser)
                .collection("construcitonName").document(dataModel.constructionArea).set(post)
                .await()
        }
    }

    override suspend fun fetchData(
        currentUser: String, constructionName: String
    ): Result<List<DataModel>> {
        return kotlin.runCatching {
            val dataModelList = mutableListOf<DataModel>()

            val documentSnapshot =
                database.collection("Users").document(currentUser).collection("construcitonName")
                    .document(constructionName).get().await()

            if (documentSnapshot.exists()) {
                val data = documentSnapshot.data
                val message = data?.get("message") as? String ?: ""
                val title = data?.get("title") as? String ?: ""
                val photoUrl = data?.get("photoUrl") as? String ?: ""
                val timestamp = data?.get("timeStamp") as? Long ?: 0L

                val retrievedDataModel = DataModel(
                    message, title, photoUrl, timestamp, currentUser, constructionName
                )
                dataModelList.add(retrievedDataModel)
            }

            dataModelList.toList()
        }
    }

    override suspend fun fetchArea(): Result<List<ConstructionName>> {
        return kotlin.runCatching {
            val constructionNames = mutableListOf<ConstructionName>()

            val usersSnapshot = database.collection("Users")
                .get().await()

            if (usersSnapshot.isEmpty){
                Log.d("FirebaseDebug", "usersSnapshot is empty")
            }

            for (userDocument in usersSnapshot.documents) {
                val userId = userDocument.id
                val constructionsSnapshot = userDocument.reference.collection("construcitonName").get().await()

                for (constructionDocument in constructionsSnapshot.documents) {
                    val data = constructionDocument.data
                    val message = data?.get("message") as? String ?: ""
                    val title = data?.get("title") as? String ?: ""
                    val photoUrl = data?.get("photoUrl") as? String ?: ""
                    val timestamp = data?.get("timeStamp") as? Number ?: 0

                    val constructionName = ConstructionName(
                        userId,
                        constructionDocument.id,
                        message,
                        title,
                        photoUrl,
                        timestamp.toLong()
                    )
                    constructionNames.add(constructionName)
                }
            }

            constructionNames.toList()
        }
    }

}`

**Comment by erkocali1** [comment]
okay ı i'm waiting.

**Comment by dconeybe** [comment]
Hi @erkocali1. When you say "my fetchArea() function is not working" can you clarify what you mean by "not working"? Is it throwing an exception? Is it getting stuck? Is it returning some unexpected value? Also, please reproduce the problem with debug logging enabled and post the debug logs. These logs may help make sense of what's going on. To enable debug logs, call `FirebaseFirestore.setLoggingEnabled(true)`.

**Comment by erkocali1** [comment]
I solved the problem. I edited my save function as I wrote below. I had to enter information, even if it was empty, into the documents I used when creating the reference. Otherwise I get an error like this "Non-existent ancestor documents."

    override suspend fun saveArea(dataModel: DataModel): Result<Unit> {
        return kotlin.runCatching {
            val post = hashMapOf(
                "message" to dataModel.message,
                "title" to dataModel.title,
                "photoUrl" to dataModel.photoUrl,
                "timeStamp" to dataModel.timestamp
            )

            val currentUserRef = database.collection("Users").document(dataModel.currentUser)
            val constructionSiteRef = currentUserRef.collection("construcitonName").document(dataModel.constructionArea)

            // Üst belgeyi oluşturmak
            currentUserRef.set(hashMapOf("dummyField" to "dummyValue")).await()
            constructionSiteRef.set(hashMapOf("dummyField" to "dummyValue")).await()

            val postsRef = constructionSiteRef.collection("posts").document("20231117")

            postsRef.set(post).await()
        }
    }
https://firebase.google.com/docs/firestore/using-console?authuser=0&_gl=1*11pt0xi*_ga*MjAzNjU4MjAwOS4xNjk0ODY2MDMy*_ga_CW55HF8NVT*MTcwMDIzNTY3Mi44MS4xLjE3MDAyNDIwODAuMzkuMC4w#non-existent_ancestor_documents

**Comment by erkocali1** [comment]
by the way thanks your your attention :)

**Comment by dconeybe** [comment]
I'm glad to hear you've resolved your issue. Thank you for showing the solution. All the best!
