### ISSUE TITLE
getInstanceId keeps throwing SERVICE_NOT_AVAILABLE even after connecting to internet

### ISSUE THREAD

**Issue by DarthVader05** [firebase/firebase-android-sdk#5575]
Describe your environment

  * Android Studio version: Chipmunk | 2021.2.1 Patch 2
  * Firebase Component: Messaging 
  * Component version: 20.1.5

Describe the problem

#### Steps to reproduce:

1. Connect device to a wifi signal with no internet connectivity
2. Try calling FirebaseInstanceId.getInstance().getInstanceId()
3. Throws SERVICE_NOT_AVAILABLE - which is expected
4. We change to a wifi signal with internet connectivity
5. We keep getting SERVICE_NOT_AVAILABLE until we clear the app data

The problem is that even after changing into a wifi signal that does have internet connectivity we keep getting the same error, even if we kill the process, the only solution is to clear the app's data.

This is not a recurrent problem, testers found it with a reproducibility of 1 out of 5 times.

#### Relevant Code:

```
// We retry this code infinitely until we get a successful response
Single.create { emitter ->
            FirebaseInstanceId.getInstance().getInstanceId()
                    .addOnSuccessListener { result ->
                        emitter.onSuccess(result.token)
                    }
                    .addOnFailureListener { exception ->
                        emitter.onError(exception)
                    }
        }
```

**Comment by argzdev** [comment]
Hi @DarthVader05, thanks for reaching out. Just to set some expectations, while we understand that `FirebaseInstanceId` may have issues, `FirebaseInstanceId` is [deprecated](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId) and will not be expected to have support or work correctly.

You may however use the [alternative options](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId):
1. Use `FirebaseInstallations.getInstance().getToken()`
2. With the latest version of FCM `23.3.1` use `FirebaseMessaging.getInstance().getToken()`

That said, could you test if these help? Given with the low reproducibility rate, I'm unable to reproduce the same behavior after testing 7 times for both `FirebaseInstanceId` and the alternative options.
