### ISSUE TITLE
Allow different firestore cache settings per collection 

### ISSUE THREAD

**Issue by eranl** [firebase/firebase-android-sdk#5580]
## What feature would you like to see?

A way to assign memory or persistent cache to specific firestore collections, or to exclude certain collections from the cache.

## How would you use it?

In a given firestore, some collections can benefit from a persistent cache, and others might suffer from it, so I would use different settings accordingly.

**Comment by cherylEnkidu** [comment]
Thank you for your report! This feature request has been added to our internal tracking tools : b/315348516

**Comment by eranl** [comment]
How can I get status updates about this?
