### ISSUE TITLE
Firebase Auth: Deprecated fetchSignInMethodsForEmail

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#5586]
Hi, I don't see any documentation on what is the replacement for `fetchSignInMethodsForEmail`.  The only document related to this method is [this](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#fetchSignInMethodsForEmail(java.lang.String)) however it seems the migration is not happening in Android or iOS SDK and it is not clear what changes should we made for this deprecation.

Using Firebase Auth`22.3.0`

**Comment by argzdev** [comment]
Hi @ArcherEmiya05, thanks for reaching out. I've received feedback from our engineer. This is being deprecated, and there is no replacement for this method. The recommendation is to stop relying on this feature for increased security. Let me know if that answers your question. Thanks!

**Comment by argzdev** [comment]
Since this question has been answered, I'll go ahead and close this now. Thanks!

**Comment by POULASTAAdAS** [comment]
Hi @argzdev you said "there is no replacement for this method" then how should I handle if user don't exists and tries to login..
"com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The supplied auth credential is incorrect, malformed or has expired" is the only execption it returns......... how to segregate incorrect passowrd and  user don't exist. I tried doc didn't find anything (maybe i overlooked :)  )

**Comment by Dark-error-Honor** [comment]
Hi, I found a workaround for this. In my application I want to check if the given e-mail is already used and make an account later in the sign up process. I store the all email addresses along with some other data for each user in the Firestore database. That way I can lookup if there already is a user with this email.
`
QuerySnapshot query = await FirebaseFirestore.instance.collection('users').where("e-mail", isEqualTo: email).get();
`
This returns all documents where the user has the given email so you can simply use:
`
if (query.docs.isNotEmpty) {
      // Email is already used...
    }
`
To check if it returned any documents.
Hope this helps!

**Comment by POULASTAAdAS** [comment]
@Dark-error-Honor thanks this helps :)
