### ISSUE TITLE
FIAM will not be displayed in non-main processes

### ISSUE THREAD

**Issue by imaiya** [firebase/firebase-android-sdk#5595]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1
  * Firebase Component: in-app-message
  * Component version: firebase bom 32.7.0

### [REQUIRED] Step 3: Describe the problem
I am using the latest firebase bom version, my application has multiple processes, I manually initialize firebase in the application.

I configure analytics events as FIMA triggers in the firebase background (my app already has a large number of analytics events), but then events triggered by non-main processes will never display FIMA.
I analyzed the FIMA source code and found that it is related to the AnalyticsEventsManager class, where FiamAnalyticsConnectorListener #onMessageTriggered () will only be called by the analytics component in the main process. but at this time, my main process activity is in the background, not the main process activity. When triggerInAppMessage () is called, fiamDisplay == null, so the FIMA message cannot be displayed.

This issue has blocked my app development, my app is used by 200 million users, please help me, thank you

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Two activities are in different processes, using the analytics event as a trigger, only the activity of the main process can display fima

#### Relevant Code:
Because onMessageTriggered () will only be called in the main process
```
final class FiamAnalyticsConnectorListener implements AnalyticsConnectorListener {
  private FlowableEmitter<String> emitter;

  FiamAnalyticsConnectorListener(FlowableEmitter<String> emitter) {
    this.emitter = emitter;
  }

  @Override
  public void onMessageTriggered(int id, Bundle extras) {
    if (id == AnalyticsConstants.FIAM_ANALYTICS_CONNECTOR_LISTENER_EVENT_ID) {
      emitter.onNext(extras.getString("events"));
    }
  }
}
```

**Comment by argzdev** [comment]
Hey @imaiya, thanks for reaching out. Just for context, the FIAM will not display when the app is in the background, however 
 the FIAM will be displayed once the user returns back to the app:

https://github.com/firebase/firebase-android-sdk/blob/16a90fa48dcdcc4fc91fb0d6bf469a56bab21f50/firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java#L178C11-L178C11

> I analyzed the FIMA source code and found that it is related to the AnalyticsEventsManager class, where FiamAnalyticsConnectorListener #onMessageTriggered () will only be called by the analytics component in the main process. but at this time, my main process activity is in the background, not the main process activity. When triggerInAppMessage () is called, fiamDisplay == null, so the FIMA message cannot be displayed.

I'm not sure if I understand correctly. However, from your explanation, it looks like it is working as intended. We won't show the FIAM unless the app is in the foreground. If there are triggered analytics commands from the background, the app will display the FIAM once the user returns back to the app foreground.

To further investigate this issue, could provide steps to reproduce this behavior and also a minimal reproducible example? Thanks!
