### ISSUE TITLE
Crash After Updating com.google.gms:google-services to 4.4.0

### ISSUE THREAD

**Issue by Suraj820** [firebase/firebase-android-sdk#5612]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Hedgehog | 2023.1.1
  * Firebase Component: Firebase-messaging
  * Component version: 23.4.0

#### Steps to reproduce:

I have recently updated the com.google.gms:google-services:4.4.0 dependency, and after that, it started crashing my app. The cause was listed as 'Initialize the Firebase.' However, when I downgraded the version of com.google.gms:google-services, it works fine. 

#### Relevant Code:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackage.activity/com.mypackage.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.mypackage.activity. Make sure to call FirebaseApp.initializeApp(Context) first. at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3872)                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)                                                                                        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
```

**Comment by Suraj820** [comment]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Hedgehog | 2023.1.1
  * Firebase Component: Firebase-messaging
  * Component version: 23.4.0

### [REQUIRED] Step 3: Describe the problem

#### Steps to reproduce:

I have recently updated the com.google.gms:google-services:4.4.0 dependency, and after that, it started crashing my app. The cause was listed as 'Initialize the Firebase.' However, when I downgraded the version of com.google.gms:google-services, it works fine. 

#### Relevant Code:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackage.activity/com.mypackage.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.mypackage.activity. Make sure to call FirebaseApp.initializeApp(Context) first. at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3872)                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)                                                                                        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
```

**Comment by argzdev** [comment]
Hey @Suraj820, thanks for reaching out. I created a new project with `com.google.gms:google-services:4.4.0` and `com.google.firebase:firebase-messaging:23.4.0` but I'm not encountering the crashing behavior. Is there any additional steps to reproduce this behavior? Could you share code snippets or minimal reproducible example for us to investigate this further? Thanks!

**Comment by Suraj820** [comment]
Hi @argzdev,

I am experiencing a crash in my app, and I believe it is related to the following code snippet in the `onCreate()` method of my MainActivity:

```java
FirebaseMessaging.getInstance().getToken().addOnCompleteListener(task -> {
    if (!task.isSuccessful()) {
        return;
    }
    // Get new FCM registration token
    String token = task.getResult();
});
```

I have already initialized FirebaseApp in my Application class using the following code:

```java
FirebaseApp.initializeApp(this);
```

Could you please help me identify the issue or provide guidance on how to resolve it? Thank you!

**Comment by Suraj820** [comment]
@argzdev  , while troubleshooting, I found this warning log coming from Firebase. This might be helpful for you:

```
2023-12-21 15:15:37.496 27078-27078 W FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your Gradle project.
```

I hope this information proves useful to you.

**Comment by argzdev** [comment]
Hi @Suraj820, you might've missed adding `com.google.gms.google-services` in your **app** module build.gradle. So you need to add both `com.google.gms.google-services` in your project module and app module build.gradle :

project build.gradle
```gradle
plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.kotlinAndroid) apply false
    id("com.google.gms.google-services") version "4.4.0" apply false
}
```
app build.gradle
```gradle
plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
    id("com.google.gms.google-services")
}
```

You should be able to resolve this issue after adding this. Also you don't need to add `FirebaseApp.initializeApp(this);` in your application class.

**Comment by Suraj820** [comment]
hi @argzdev 

i alredy have this  in my  gradle files
project level gradle file

```gradle
buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.2'
        classpath 'com.google.gms:google-services:4.4.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        // Add the Crashlytics Gradle plugin.
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.7.6'
     //   classpath "com.rakuten.sixthsense.mobilemonitoring:SSNetworkPlugin:1.2.0"
    }
}

```

app level gradle file:

`apply plugin: 'com.google.gms.google-services'`
still facing this issue

**Comment by argzdev** [comment]
Not sure what's going on here, there's definitely a configuration issue. Could you share a [MCVE](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean) of your issue so we can investigate this further? Thanks

**Comment by Suraj820** [comment]
Hi @argzdev 

Thank you for your prompt response and valuable suggestion! Upgrading Gradle to the latest version indeed resolved my issue. I appreciate your help!

**Comment by argzdev** [comment]
Awesome, I'm glad to hear it helps!
