### ISSUE TITLE
 Sent Firebase cloud messaging, the photo didn't shown and the words are normal.

### ISSUE THREAD

**Issue by alex-sssun186** [firebase/firebase-android-sdk#5617]
## What feature would you like to see?

Describe the feature you would like to add, ideally proposing a specific API.

## How would you use it?

Tell us how you'd use this feature in your app.

**Comment by argzdev** [comment]
Hi @alex-sssun186, thanks for reaching it. Just to clarify, are you trying to [show an image in the notification payload](https://firebase.google.com/docs/cloud-messaging/android/send-image)? If so, could you answer the questions below so we can investigate further?

1. Could you share what version of Firebase Cloud Messaging are you using?
2. Is this issue consistently reproducible?
3. Do you have any code snippets or [MCVE](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean) you could share?

These information will help us conduct an initial investigation to figure out what's going on.
