### ISSUE TITLE
Surface KDoc only KTX deprecations more visibly with the `@Deprecated` annotation

### ISSUE THREAD

**Issue by EdricChan03** [firebase/firebase-android-sdk#5639]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Jellyfish Canary 4
  * Firebase Component: Firestore, Auth, Messaging
  * Component version: BoM 32.7.0

#### Steps to reproduce:

Use a KTX import (for e.g. `Firebase` and `Firebase.firestore`) in a class:

##### Relevant Code:

```kt
package com.example.myapp.di

import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.ktx.auth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import com.google.firebase.messaging.FirebaseMessaging
import com.google.firebase.messaging.ktx.messaging
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent

@Module
@InstallIn(SingletonComponent::class)
object FirebaseModule {
    @Provides
    fun provideFirebaseAuth(): FirebaseAuth = Firebase.auth

    @Provides
    fun provideFirebaseFirestore(): FirebaseFirestore = Firebase.firestore

    @Provides
    fun provideFirebaseMessaging(): FirebaseMessaging = Firebase.messaging
}
```

Note that the KTX classes/members (`Firebase`, `firestore`, `messaging`, etc) are not striked-through, like what would be expected with a deprecated Kotlin class/member/function:

<img width="840" alt="Screenshot of the provideFirebaseFirestore method from the earlier code snippet with no striked-out Firebase or firestore text" src="https://github.com/firebase/firebase-android-sdk/assets/20047125/e637843f-7332-4d90-9c0f-e53e8544615e">

It appears that these methods are missing their `@Deprecated` annotations, which would then be more visibly surfaced to the end-user compared to a potentially missed documentation note which can only be viewed in the KDoc/sources/Quick Documentation or online:

```kt
/**
 * Accessing this object for Kotlin apps has changed; see the
 * [migration guide](https://firebase.google.com/docs/android/kotlin-migration).
 *
 * Returns the [FirebaseFirestore] instance of the default [FirebaseApp].
 * @deprecated **Deprecation Notice:** The Kotlin extensions (KTX) APIs have been added to their
 * respective main modules, and the Kotlin extension (KTX) APIs in
 * `com.google.firebase.firebase-database-ktx` are now deprecated. As early as April 2024, we'll no
 * longer release KTX modules. For details, see the
 * [FAQ about this initiative.](https://firebase.google.com/docs/android/kotlin-migration)
 */
val Firebase.firestore: FirebaseFirestore
  get() = FirebaseFirestore.getInstance()
```

They should be added, perhaps with a `ReplaceWith` annotation as well to make it easier for developers to easily migrate their source code over to the non-KTX variant without having to manually consult the sources to figure out what the new import would be:

```kt
@Deprecated(
  "The KTX APIs for Firestore have since been added to the main Firestore artifact, and this API is now deprecated, and will be scheduled for removal in April 2024.",
  replaceWith = ReplaceWith(
    "this.firestore",
    "com.google.firebase.firestore.firestore"
  )
)
val Firebase.firestore: FirebaseFirestore
  get() = FirebaseFirestore.getInstance()

```

**Comment by cherylEnkidu** [comment]
Hi @EdricChan03 ,

The reason why this api is not marked with `@deprecated` is it would give the message `Firebase.firestore` is deprecated which could give some people the opinion that firestore is deprecated.

The team is working on improving the Kotlin API which includes the usage of this annotation. 

Thank you for filling the request again!
