### ISSUE TITLE
Does in-app messaging not support measurement protocol events?

### ISSUE THREAD

**Issue by clearflame236** [firebase/firebase-android-sdk#5657]
I checked all the documents and found no relevant information, so I can only ask for help here. I can receive in-app messaging normally using the send event of Android SDK, but the published message is a server event, using measurement protocol events. I have seen that the event is triggered many times in the firebase console, but the in-app messaging 's campaign dashboard keeps showing empty data

**Comment by lehcar09** [comment]
Hi @clearflame236, thank you for reaching out. [Impression](https://support.google.com/analytics/answer/9234069?hl=en&visit_id=638034142619607831-1028025920&rd=2#:~:text=when%20a%20user%20sees%20a%20Firebase%20In%2DApp%20Message) count is based on Google Analytics automatically collected events that are recorded if a user received the In-App campaign in the app and the user sees the In-App campaign. As for the clicks, I suggest [implement an event listener for card interactions](https://firebase.google.com/docs/in-app-messaging/modify-message-behavior?platform=android#implement_an_event_listener_for_card_interactions) to determine if the user fully interacts with your FIAM campaign.

This type of inquiry/issue is best suited to be filed in our [Firebase support channel](https://firebase.google.com/support/) for more personalized assistance as we’d need access to your project details (including projectID, campaign ids), so please reach out to them to check on the issue.

**Comment by lehcar09** [comment]
Hi @clearflame236, thank you for reaching out. Just to give an overview, according to our [documentation](https://firebase.google.com/docs/in-app-messaging/compose-campaign#schedule-your-message),you can add at least one trigger event.
* You can enter default events or [events logged through Firebase Analytics](https://firebase.google.com/docs/analytics/android/events?authuser=0) to trigger your in-app message. These events can be user actions, system events, or errors.
* Your in-app message is triggered when any of your events occur.

In-app messages are shown while the user is actively using the app and is always triggered from within the app. There is no way to trigger it externally. 

To add for data related issues/ inquiry, it would be best to reach out to [Firebase support channel](https://firebase.google.com/support/) for more personalized assistance as we’d need access to your project details (including projectID, campaign ids) to check the issue. 

Let me know if I misunderstood anything.
