### ISSUE TITLE
firebase-bom renders no dependency from firebase-firestore

### ISSUE THREAD

**Issue by dnhyde** [firebase/firebase-android-sdk#5662]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 (Build #AI-231.9392.1.2311.11076708)
  * Firebase Component: Firestore
  * Component version: firebase-bom = "32.7.1"

### [REQUIRED] Step 3: Describe the problem

I have the exact same problem as https://github.com/firebase/firebase-android-sdk/issues/5339 but the thread is locked so I am opening a new issue.

#### Steps to reproduce:

Install firebase-bom (I user gradle version catalog)
```
[versions]
firebase-bom = "32.7.1"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore"}
```

#### Relevant Code:

Reading from [docs](https://firebase.google.com/docs/firestore/quickstart?authuser=0&_gl=1*kjyahk*_ga*MjU1NzYxODEzLjE3MDUwNDgyNzI.*_ga_CW55HF8NVT*MTcwNjIxNjMxMy42LjEuMTcwNjIxNjQ4MC40Ny4wLjA.#initialize) 
```
val db = Firebase.firestore
```
However when I user `Firebase.firestore` or `FirebaseFirestore.getInstance()` I get prompted to add the following dependency:
```
[version]
firebase-firestore-ktx = "24.10.1"

[libraries]
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebase-firestore-ktx" }
```

**Comment by lehcar09** [comment]
Hi @dnhyde , thank you for reaching out. I tried reproducing the issue, however, I wasn't able to encounter the dependency issue you reported. Below is how I've added these in my gradle. 

**libs.versions.toml**
```
[versions]
firebase-bom = "32.7.1"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore"}
```

**app/build.gradle.kts**

```
dependencies {
    //Add
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.firestore)
}
```

However, I seem to experience the issue when I remove the BOM dependency `implementation(platform(libs.firebase.bom))`. Can you confirm that you have declared the BOM dependency? or am I missing something? If you could you provide me an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example), that'll be helpful for me to investigate this issue further. Thanks.

**Comment by dnhyde** [comment]
My bad I realized that I did not include the `bom` in my module. 
I included only 
```
dependencies {
    implementation(libs.firebase.firestore)
}
```
instead of
```
dependencies {
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.firestore)
}
```
Sorry I misread the dependencies of my module 🙏
