### ISSUE TITLE
build_id/mapping_file_id prevents gradle build cache

### ISSUE THREAD

**Issue by lamphamTL** [firebase/firebase-android-sdk#5668]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1
  * Firebase Component: firebase crashlytics gradle plugin
  * Component version: 2.3.0

### [REQUIRED] Step 3: Describe the problem

For every **release** build, a brand new `com.crashlytics.android.build_id` (or `com.google.firebase.crashlytics.mapping_file_id` for the new versions) is generated which changes the inputs of gradle build tasks.
This leads to the fact that build cache is not used while in reality, there is nothing changed in the code.

#### Steps to reproduce:

- Run assembleRelease.
```
./gradlew clean assembleRelease
```
- Run assembleRelease (and `clean` to remove the previously created `build_id`) once again. 
```
./gradlew clean assembleRelease
```
This second assemble is supposed to use build cache but it doesn't.

**Comment by mrober** [comment]
@lamphamTL we have a prerelease of the next major version of the Crashlytics Gradle plugin, you can find it in #5733.

One of the changes in this version of the plugin is a better implementation of the InjectMappingFileIdTask. It will only generate a new mapping file id when the input sources have changed. Please try it and let us know if this resolves your issue.
