### ISSUE TITLE
onDisconnect() not working in Firebase Android

### ISSUE THREAD

**Issue by pahadi777** [firebase/firebase-android-sdk#5671]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 Patch 2
  * Firebase Component: Realtime database
  * Component version: implementation("com.google.firebase:firebase-database:20.3.0")

### [REQUIRED] Step 3: Describe the problem

This is my code below, the `isOnline` value is not changing to false for the user when the device is disconnected. Please fix this !!!!!

```
isDeviceConnectedRef = deviceReference.child("isOnline")
val isConnectedRef = Firebase.database.getReference(".info/connected")
isDeviceConnectedRef.onDisconnect().setValue(false)

isConnectedRef.addValueEventListener(object : ValueEventListener {
    override fun onDataChange(snapshot: DataSnapshot) {
        val connected = snapshot.getValue(Boolean::class.java) ?: false
        if (connected) {
            isDeviceConnectedRef.setValue(true)
        }
    }

    override fun onCancelled(error: DatabaseError) {

    }
})
```

<img width="479" alt="Screenshot 2024-01-30 at 1 35 10 AM" src="https://github.com/firebase/firebase-android-sdk/assets/90754518/54eced91-2335-4897-b05c-485323f139a6">

**Comment by lehcar09** [comment]
Hi @pahadi777 , thank you for reaching out. I've tried replicating this issue but I did not encounter any issue with `onDisconnect()`.  Below is how used them.

```
        databaseRef = Firebase.database
        val myRef = databaseRef.getReference("Devices")
        val isDeviceConnectedRef = myRef.child("myDevice").child("isOnline")
        isDeviceConnectedRef.setValue(true)
        isDeviceConnectedRef.onDisconnect().setValue(false)

        // Read from the database
        val isConnectedRef = Firebase.database.getReference(".info/connected")
        isConnectedRef.addValueEventListener(object : ValueEventListener {
            override fun onDataChange(dataSnapshot: DataSnapshot) {
                // This method is called once with the initial value and again
                // whenever data at this location is updated.
                //val value = dataSnapshot.getValue<Boolean>()

                val connected = dataSnapshot.getValue(Boolean::class.java) ?: false
                Log.d(TAG, "Value is: ${connected.toString()}")
                if (connected) {
                    isDeviceConnectedRef.setValue(true)
                    txt_status.text = "Connected"
                } else {
                    txt_status.text = "Disconnected"
                }
            }
            override fun onCancelled(error: DatabaseError) {
                // Failed to read value
                Log.w(TAG, "Failed to read value.", error.toException())
            }
        })
``` 

Upon running the app some time, I disabled the device network connection and the 'isOnline' value is set to false.  The data synced up after I reconnect to the network

![Screenshot 2024-01-31 at 10 55 30 PM](https://github.com/firebase/firebase-android-sdk/assets/155964350/fdede10d-d6fa-46ad-a4e9-c68bac8f7b71)

Any chance you could provide detailed steps to reproduce the issue?

**Comment by pahadi777** [comment]
@lehcar09 Please try this code in Android 13. It isn't working, status in not changing to false when app is killed or if user disconnects.

**Comment by lehcar09** [comment]
Hi @pahadi777, I tried in Android version 12, 13, and 14 and `onDisconnect` is triggered accordingly when I kill the app and/or disconnect to the network.

I noticed that sometimes, it takes a couple of minutes before it actually makes the update. Not much we can do about the delay, it's up to the Firebase server to make the change once the connection is lost. Might be worth contacting Firebase support to make them aware of the delay.

However, we are still investigating this. We'll keep this open and provide feedback if we figure out something. Feel free to add more details that you think might be helpful. Thanks!

**Comment by lehcar09** [comment]
Hi @pahadi777, I tried in Android version 12, 13, and 14 and `onDisconnect` is triggered accordingly when I kill the app and/or disconnect to the network. I noticed that sometimes, it takes a couple of minutes before it actually makes the update. 

Could you share with me an MCVE that could help us investigate the issue?
