### ISSUE TITLE
157239989: Remove ABT Proto Dependency

### ISSUE THREAD

**Issue by miraziz** [firebase/firebase-android-sdk#568]
The Firebase Remote Config (FRC) SDKs released before I/O 2019 depended on the ABT proto "ExperimentPayload" to enable FRC experiments. To maintain backward compatibility, the newer FRC SDKs have Legacy logic that parses the older proto experiments.

The Legacy logic will be removed in the next major release, at which point both ABT and FRC should be proto-free.

However, FIAM is using the proto version of ABT, so both FRC and FIAM currently depend on the same proto definition. As a short term fix, the ABT SDK can define the proto, and FRC/FIAM can depend on ABT to get the proto definition.

Once FRC's legacy logic is removed, ABT's proto definition should be removed (otherwise the FRC SDK will keep depending on protos because of its hard dependency on ABT). If FIAM is still using protos at that point, then the proto dependency can be moved back from ABT to FIAM.

**Comment by ashwinraghav** [comment]
Seems like this was fixed a while ago

**Comment by allisonbm92** [comment]
No, this hasn't been fixed.

**Comment by ashwinraghav** [comment]
My bad. Misread.

**Comment by clp93** [comment]
@JasonAHeron Do you know why the FIAM SDK needs the ABT proto dep?

**Comment by ashwinraghav** [comment]
Note to our future selves.
When we remove this [proto](https://github.com/firebase/firebase-android-sdk/blob/add8c9b45a5488d368f3fc77f33198e673c3fb17/firebase-abt/src/proto/com/google/protos/developers/mobile/abt/proto/experiment_payload.proto#L32) from ABT and RC, it will have to be vendored into Fiam until they no longer have the dep

**Comment by samtstern** [comment]
(test comment for oss-bot, please ignore)

**Comment by vkryachko** [comment]
This was addressed in the latest abt release `20.0.0`.
