### ISSUE TITLE
Firebase Analytic consent indicators not collected

### ISSUE THREAD

**Issue by JohnFarl** [firebase/firebase-android-sdk#5731]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version:  Hedgehog 1.1.2023
  * com.google.gms:google-services:4.4.1
  * firebase-analytics:21.5.1 
  * ump:user-messaging-platform:2.2.0 
  * com.google.android.gms:play-services-ads:22.6.0

### [REQUIRED] Step 3: Describe the problem
Seems Firebase doesn't receive any consent indicator despite in the App manifest I already have
```
<meta-data android:name="google_analytics_default_allow_analytics_storage" android:value="true" />
<meta-data android:name="google_analytics_default_allow_ad_storage" android:value="true" />
<meta-data android:name="google_analytics_default_allow_ad_user_data" android:value="true" />
<meta-data android:name="google_analytics_default_allow_ad_personalization_signals" android:value="true" />
```

Firebase console show this warning: 

> End users in the European Economic Area (EEA) must provide consent to have their personal data shared with Google for advertising purposes. If data is marked as non-consent, ad personalization and measurement may be affected. Check your Firebase consent settings.

Google Analytics console shows this warning in stream detailss:

> **ACTION REQUIRED** Consent indicators not collected for ad personalization 
To verify that your business is collecting consent from end users in the EEA before submitting personal data to Google for use in ad personalization, implement consent indicators for ad personalization. If personal data is not marked with end-user consent, EEA-based visitors will not be included in audience lists exported to Google Ads and will impact ad personalization. To set up consent indicators, use a consent management platform or the Consensus Mode API. Learn more about consensus indicators You may need to update the Google Analytics for Firebase SDKs for Android and iOS to a version that supports the consent indicators required for EEA-based visitors (Android: 21.5.0, iOS: 10.17.0).

These warnings appeared recently and don't go away, I'm not sure if the bug is client side or server side.

**Comment by lehcar09** [comment]
Hi @JohnFarl, thank you for reaching out. It seems to me that this is more of configuration issue. The console banners you’re seeing means that data from European-based users is available in a linked Google Ads account. It also means that consent signals for ad personalization aren’t being sent with data to Google Analytics. This means you will need to check that you’re using a consent banner on your website. And if you’re already using a consent banner, then you might need to adjust the settings used for the banner. You can check this [documentation](https://support.google.com/analytics/answer/9976101?hl=en&sjid=7678898629498770479-AP) for more information. 

Just to note, you need to wait up to 48 hours once you’re adjusted you’re implementation before you see updates in the ‘Consent Settings’ section then you will see the ‘Ad personalization consent signals active’. You can refer to this [documentation](https://support.google.com/analytics/answer/14275483?hl=en) to verify and update consent settings.

If the issue persists, It would be best to reach out to the [Firebase support channel ](https://firebase.google.com/support/)instead. We'd need access to your project settings (including projectID, SHA-1) to troubleshoot this type of issue.

**Comment by JohnFarl** [comment]
@lehcar09 The point is that isn't a configuration issue unless Google configuration guide is also wrong, because my configuration follows reported indication but recently for some reason I have this warning. I have also contacted Firebase support.

**Comment by kenumir** [comment]
+1

**Comment by lehcar09** [comment]
Hi everyone, our engineers looked into this issue. You can check this #5738 for updates. Just to echo details here, according to the investigation the consents are getting collected and the issue is on the backend. The issue has been resolved. If the issue persists, please reach out to the Firebase support channel [here](https://firebase.google.com/support/troubleshooter/contact)

**Comment by harun119** [comment]
+1
