### ISSUE TITLE
firebase-common-ktx published POM is bogus starting version 20.4.1

### ISSUE THREAD

**Issue by oliviernotteghem** [firebase/firebase-android-sdk#5732]
Repro :
- compare the POM of https://mvnrepository.com/artifact/com.google.firebase/firebase-common-ktx/20.4.0 vs https://mvnrepository.com/artifact/com.google.firebase/firebase-common-ktx/20.4.1

20.4.1 POM is specifying dep  https://maven.google.com/com/google/firebase/firebase-components/17.1.5/firebase-components-17.1.5.jar which does not exist (it should be aar, not jar)

breaks Bazel / jvm_rules_external - see https://github.com/bazelbuild/rules_jvm_external/issues/1057

**Comment by lehcar09** [comment]
Hi @oliviernotteghem, thank you for reaching and reporting the issue. We have confirmed the issue on our side. We will release a new version of firebase-common-ktx with the right dependency in the next release cycle. I'll be closing this ticket now. You can check our [release notes](https://firebase.google.com/support/release-notes/android#latest_sdk_versions) for an update. Thanks.
