### ISSUE TITLE
[storage] Incorrect mime type inferred when not manually setting metadata

### ISSUE THREAD

**Issue by Lyokone** [firebase/firebase-android-sdk#5734]
This issue is related to another issue reported to https://github.com/firebase/flutterfire/issues/12363 
The issue does not appear when running the same logic on iOS.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2022.3.1
  * Firebase Component: Storage
  * Component version: BoM 32.7.2

#### Steps to reproduce:

When uploading a file without any metadata, the metadata are not inferred properly. For instance uploading a jpeg file to the Firebase emulator will give a mime type of "application/octet-stream" instead of "image/jpeg".

#### Relevant Code:

```
reference.putFile("file:///data/user/0/io.flutter.plugins.firebasestorageexample/cache/54cd5d7d-1718-4353-a4ce-a87c8c29b28d/dog-puppy-on-garden-royalty-free-image-1586966191.jpg")
```

**Comment by lehcar09** [comment]
Hi @Lyokone, thank you for reaching out. I tried reproducing the issue with the quickstart app, but I did not encounter the issue. I tried `photoRef.putFile(fileUri)` and `photoRef.putFile(fileUri, storageMetadata {})` and the `contentType` is still intact upon upload.

Just to note, according to our [documentation](https://firebase.google.com/docs/storage/android/upload-files#add_file_metadata),

>The putFile() method automatically infers the MIME type from the File extension, but you can override the auto-detected type by specifying contentType in the metadata. If you do not provide a contentType and Cloud Storage cannot infer a default from the file extension, Cloud Storage uses application/octet-stream.See the [Use File Metadata](https://firebase.google.com/docs/storage/android/file-metadata) section for more information about file metadata.

I suggest try running our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) to help troubleshoot the issue. Let me know if I misunderstood anything.
