### ISSUE TITLE
Firebase Analytic consent indicators not collected

### ISSUE THREAD

**Issue by Monabr** [firebase/firebase-android-sdk#5738]
### [REQUIRED] Step 2: Describe your environment
Android Studio version: Hedgehog 1.1.2023
com.google.gms:google-services:4.4.1
firebase-analytics:21.5.1
ump:user-messaging-platform:2.2.0
com.google.android.gms:play-services-ads:22.6.0

### [REQUIRED] Step 3: Describe the problem
Seems Firebase doesn't receive any consent indicator despite in the App manifest I already have

```
<meta-data android:name="google_analytics_default_allow_analytics_storage" android:value="true" />
<meta-data android:name="google_analytics_default_allow_ad_storage" android:value="true" />
<meta-data android:name="google_analytics_default_allow_ad_user_data" android:value="true" />
<meta-data android:name="google_analytics_default_allow_ad_personalization_signals" android:value="true" />
```
Firebase console show this warning:

> End users in the European Economic Area (EEA) must provide consent to have their personal data shared with Google for advertising purposes. If data is marked as non-consent, ad personalization and measurement may be affected. Check your Firebase consent settings.

Google Analytics console shows this warning in stream detailss:

> ACTION REQUIRED Consent indicators not collected for ad personalization
> To verify that your business is collecting consent from end users in the EEA before submitting personal data to Google for use in ad personalization, implement consent indicators for ad personalization. If personal data is not marked with end-user consent, EEA-based visitors will not be included in audience lists exported to Google Ads and will impact ad personalization. To set up consent indicators, use a consent management platform or the Consensus Mode API. Learn more about consensus indicators You may need to update the Google Analytics for Firebase SDKs for Android and iOS to a version that supports the consent indicators required for EEA-based visitors (Android: 21.5.0, iOS: 10.17.0).

These warnings appeared recently and don't go away, I'm not sure if the bug is client side or server side.

This is a BIG problem. Please pay attention to the problem and do not close the issue until bug is resolved!

**Comment by ahmed-ahsan2001** [comment]
i am also getting the same error in my iOS application

**Comment by lehcar09** [comment]
Hi @Monabr, thank you for reaching out and reporting the issue. We are already investigating the issue that we're internally tracking here at b/327531180. We'll keep you posted for updates.

**Comment by lehcar09** [comment]
Hi @Monabr, according to our engineers' investigation, the consents are collected and the issue is more on the backend side of things. 

However, the issue has been resolved. Could you confirm if you’re still experiencing the issue? If so, it would be best to reach out to the Firebase support channel here. We'd need access to your project settings (including projectID, SHA-1) to troubleshoot this type of issue.
