### ISSUE TITLE
Noob Question: nothing happens after Google consent pops up and I choose an account.

### ISSUE THREAD

**Issue by psymnx** [firebase/firebase-android-sdk#5739]
Looking for some help for a noobie here. Building in android studio, can't sign in with google.
Here's my login code:

`package com.example.lockchain

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.fragment.app.Fragment
import com.example.lockchain.databinding.FragmentLoginBinding
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import androidx.activity.result.contract.ActivityResultContracts
import androidx.navigation.NavOptions
import androidx.navigation.fragment.findNavController
import com.google.android.gms.auth.api.signin.GoogleSignInStatusCodes
import com.google.android.gms.common.api.CommonStatusCodes

class LoginFragment : Fragment() {

    private lateinit var googleSignInClient: GoogleSignInClient
    private var _binding: FragmentLoginBinding? = null
    private val binding get() = _binding!!
    private val firebaseAuth: FirebaseAuth by lazy { FirebaseAuth.getInstance() }

    private val TAG = "LoginFragment"

    private val googleSignInLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
        Log.d(TAG, "Google SignIn ActivityResult - resultCode: ${result.resultCode}")
        if (result.resultCode == androidx.fragment.app.FragmentActivity.RESULT_OK) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
            try {
                val account = task.getResult(ApiException::class.java)!!
                Log.d(TAG, "Google SignIn successful - account: ${account.email}")
                firebaseAuthWithGoogle(account.idToken!!)
            } catch (e: ApiException) {
                val message = when (e.statusCode) {
                    CommonStatusCodes.SIGN_IN_REQUIRED -> "Sign in required."
                    CommonStatusCodes.NETWORK_ERROR -> "Network error. Check your connection."
                    CommonStatusCodes.INVALID_ACCOUNT -> "Invalid account specified."
                    CommonStatusCodes.INTERNAL_ERROR -> "An internal error occurred."
                    GoogleSignInStatusCodes.SIGN_IN_CANCELLED -> "Sign in was cancelled by the user."
                    GoogleSignInStatusCodes.SIGN_IN_CURRENTLY_IN_PROGRESS -> "Sign in currently in progress."
                    GoogleSignInStatusCodes.SIGN_IN_FAILED -> "Sign in failed with the current account."
                    else -> "Unknown error occurred. Error code: ${e.statusCode}"
                }
                Log.e(TAG, "Google SignIn failed: $message", e)
                Toast.makeText(context, "Google Sign-In error: $message", Toast.LENGTH_LONG).show()
            }
        } else {
            Log.d(TAG, "Google SignIn ActivityResult not OK")
            Toast.makeText(context, "Google Sign-In cancelled or failed.", Toast.LENGTH_SHORT).show()
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = FragmentLoginBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupGoogleSignIn()
        setupListeners()
    }

    private fun setupGoogleSignIn() {
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.web_client_id))
            .requestEmail()
            .build()

        googleSignInClient = GoogleSignIn.getClient(requireActivity(), gso)
    }

    private fun setupListeners() {
        binding.btnSignIn.setOnClickListener { performEmailSignIn() }
        binding.btnSignUp.setOnClickListener { performEmailSignUp() }
        binding.googleButton.setOnClickListener {
            Log.d(TAG, "Google SignIn button clicked")
            performGoogleSignIn()
        }
    }

    private fun performGoogleSignIn() {
        val signInIntent = googleSignInClient.signInIntent
        googleSignInLauncher.launch(signInIntent)
    }

    private fun firebaseAuthWithGoogle(idToken: String) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        firebaseAuth.signInWithCredential(credential).addOnCompleteListener(requireActivity()) { task ->
            if (task.isSuccessful) {
                Log.d(TAG, "Firebase Auth with Google successful")
                val navOptions = NavOptions.Builder()
                    .setPopUpTo(R.id.nav_login, true)
                    .build()
                findNavController().navigate(R.id.action_nav_login_to_nav_entrance, null, navOptions)
            } else {
                Log.e(TAG, "Firebase Auth with Google failed: ${task.exception?.message}")
                Toast.makeText(context, "Authentication Failed.", Toast.LENGTH_SHORT).show()
            }
        }
    }

    private fun performEmailSignIn() {
        val email = binding.etEmail.text.toString()
        val password = binding.etPassword.text.toString()
        if (email.isBlank() || password.isBlank()) {
            Toast.makeText(context, "Email and password cannot be empty", Toast.LENGTH_SHORT).show()
            return
        }

        firebaseAuth.signInWithEmailAndPassword(email, password).addOnCompleteListener(requireActivity()) { task ->
            if (task.isSuccessful) {
                //Toast.makeText(context, "Login Successful.", Toast.LENGTH_SHORT).show()
                val navOptions = NavOptions.Builder()
                    .setPopUpTo(R.id.nav_login, true) // Clear the back stack
                    .build()
                findNavController().navigate(R.id.action_nav_login_to_nav_entrance, null, navOptions)
            }
            else {
                Toast.makeText(context, "Incorrect Password or Username", Toast.LENGTH_SHORT).show()
            }
        }
    }

    private fun performEmailSignUp() {
        // Navigate to the Sign Up fragment without attempting to sign up here
        findNavController().navigate(R.id.action_nav_login_to_nav_sign_up)
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
`

My module level build:
`
buildscript {
    // Keep this block for classpath dependencies only
    dependencies {
        classpath("com.android.tools.build:gradle:8.2.2") // Specify your Android Gradle Plugin version here
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22") // Specify your Kotlin Gradle Plugin version here
        classpath("com.google.gms:google-services:4.4.1") // Google Services plugin for Firebase
    }
}

plugins {
    id("com.android.application") version "8.2.0" apply false
    id("org.jetbrains.kotlin.android") version "1.9.10" apply false
    // The google-services plugin is typically applied at the app module level, not here.
}
`

I got the right plugins in my app  level build:
`
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.gms.google-services")
    id("kotlin-kapt")
}
`

and my dependencies:
`
 //noinspection BomWithoutPlatform
    implementation(platform("com.google.firebase:firebase-bom:32.7.2"))
    implementation ("com.google.firebase:firebase-analytics")
    implementation ("com.google.firebase:firebase-firestore-ktx")
    implementation ("com.google.firebase:firebase-auth")

    // Google Sign-In
    implementation ("com.google.android.gms:play-services-auth:21.0.0")
    implementation ("com.google.android.material:material:1.11.0")
    implementation ("com.google.android.material:material:1.11.0")
`

When I click the google account to sign in with on the consent pop up, nothing happens and I get the lgocat message:
2024-02-25 21:12:14.877 24490-24490 LoginFragment                D  Google SignIn ActivityResult - resultCode: 0
2024-02-25 21:12:14.877 24490-24490 LoginFragment                D  Google SignIn ActivityResult not OK

Help a noobie out! What am I missing?
I 100% know the google-json is in the right app level directory, and that the web client id is correct.

**Comment by phamconganh** [comment]
change com.google.gms.google-services 4.4.1 to 4.3.15. I don't know why 4.4.1 can't return the id Token after authentication. So when checking on the server it fails

**Comment by lehcar09** [comment]
Hi @psymnx, thank you for reaching out. I tried reproducing the issue using the code snipped you shared and I was able to sign in with Google successfully. 

![test](https://github.com/firebase/firebase-android-sdk/assets/155964350/683e1f90-813b-46d0-8754-b8171dc4cc13)

build.gradle.kts
```
buildscript {
    dependencies {
        classpath("com.google.gms:google-services:4.4.1")
    }
}
// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id("com.android.application") version "8.2.2" apply false
    id("org.jetbrains.kotlin.android") version "1.9.22" apply false
}
```

app/build.gradle.kts
```
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.gms.google-services")
}

dependencies {
    ...
    implementation("com.google.firebase:firebase-auth:22.3.1")
    implementation("com.google.android.gms:play-services-auth:21.0.0")
```

One thing that could this issue is when the SHA-1 is missing. If you haven't yet specified your app's SHA fingerprint, do so from the [Settings page](https://console.firebase.google.com/project/_/settings/general/) of the Firebase console. Refer to [Authenticating Your Client](https://developers.google.com/android/guides/client-auth) for details on how to get your app's SHA fingerprint. Once done, you need to re-download the updated Firebase config file (google-services.json), which now contains the OAuth client information required for Google sign-in. And, just to be sure that the configuration updates, I suggest invalidating the cache `(File -> Invalidate Caches)`.

Let me know if I misunderstood anything or the issue persists. Thanks.

**Comment by psymnx** [comment]
> change com.google.gms.google-services 4.4.1 to 4.3.15. I don't know why 4.4.1 can't return the id Token after authentication. So when checking on the server it fails

Thank you kindly for that suggestion! Will do.

**Comment by psymnx** [comment]
> Hi @psymnx, thank you for reaching out. I tried reproducing the issue using the code snipped you shared and I was able to sign in with Google successfully.
> 
> ![test](https://private-user-images.githubusercontent.com/155964350/309698650-683e1f90-813b-46d0-8754-b8171dc4cc13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzgyMzQsIm5iZiI6MTcwOTU3NzkzNCwicGF0aCI6Ii8xNTU5NjQzNTAvMzA5Njk4NjUwLTY4M2UxZjkwLTgxM2ItNDZkMC04NzU0LWI4MTcxZGM0Y2MxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxODQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjFlNmJiY2E0MzQ2OWE0NzJjZGQ5ODZmNzYwNDYzMjkxMDY1NjlmMTVkOGFiNmFlODQxNTIwMmQ3OTA3MTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tnynU26SzAqCv55cf5P0XT62-ThpqOkW5VaCa5YazbI)
> 
> build.gradle.kts
> 
> ```
> buildscript {
>     dependencies {
>         classpath("com.google.gms:google-services:4.4.1")
>     }
> }
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> plugins {
>     id("com.android.application") version "8.2.2" apply false
>     id("org.jetbrains.kotlin.android") version "1.9.22" apply false
> }
> ```
> 
> app/build.gradle.kts
> 
> ```
> plugins {
>     id("com.android.application")
>     id("org.jetbrains.kotlin.android")
>     id("com.google.gms.google-services")
> }
> 
> dependencies {
>     ...
>     implementation("com.google.firebase:firebase-auth:22.3.1")
>     implementation("com.google.android.gms:play-services-auth:21.0.0")
> ```
> 
> One thing that could this issue is when the SHA-1 is missing. If you haven't yet specified your app's SHA fingerprint, do so from the [Settings page](https://console.firebase.google.com/project/_/settings/general/) of the Firebase console. Refer to [Authenticating Your Client](https://developers.google.com/android/guides/client-auth) for details on how to get your app's SHA fingerprint. Once done, you need to re-download the updated Firebase config file (google-services.json), which now contains the OAuth client information required for Google sign-in. And, just to be sure that the configuration updates, I suggest invalidating the cache `(File -> Invalidate Caches)`.
> 
> Let me know if I misunderstood anything or the issue persists. Thanks.

Hi @lehcar09, thank you kindly, you indeed understood and did everything correctly. The fault was on my end.
It turns out I did not have my debug keys in firebase, only my release keystore keys. Yikes! Thanks anyway, learning lots from you guys!
