### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.firestore.QueryDocumentSnapshot.getString(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by Sarthak77tiwari** [firebase/firebase-android-sdk#5740]
i am getting this error   when i call the data from database of firestore 
my code 
       

            `public static void  LoadBook(MyCompleteListener completeListener){
                 bookList.clear();
                     g_firestore.collection("BOOKS").get()
                .addOnSuccessListener(new OnSuccessListener<QuerySnapshot>() {
                    @Override
                    public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
                        Map<String, QueryDocumentSnapshot> docList = new ArrayMap<>();
                        for (QueryDocumentSnapshot doc: queryDocumentSnapshots ){
                            docList.put(doc.getId(),doc);

                        }
                        QueryDocumentSnapshot bookListDoc = docList.get("Categories");

                        long bookCount = bookListDoc.getLong("COUNT");
                        for (int i=1; 1 <= bookCount ;i++){
                            String bookID =  bookListDoc.getString("BOOK"+String.valueOf(i)+"_ID");
                            QueryDocumentSnapshot bookDoc = docList.get(bookID);
                            int noOfBook = bookDoc.getLong("NO_OF_BOOK").intValue();
                            String bookName = bookDoc.getString("NAME");
                            String bookType = bookDoc.getString("TYPE");

                            bookList.add(new BookModel( bookID,bookName,bookType,noOfBook));

                        }
                        completeListener.onSuccess();

                    }
                }).addOnFailureListener(new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {

                    }
                });`
my  dependency is 
`     implementation 'com.google.android.gms:play-services-analytics:18.0.4'
    implementation("com.google.firebase:firebase-firestore")
    implementation("com.google.firebase:firebase-auth")
    implementation(platform("com.google.firebase:firebase-bom:32.7.2"))
    implementation 'com.google.firebase:firebase-analytics'`

**Comment by dconeybe** [comment]
@Sarthak77tiwari Could you provide some logs with debug logging enabled for us to take a look at?

Here is how you can do that:
1. Call `FirebaseFirestore.setLoggingEnabled(true)` as early as possible in your application.
2. Reproduce the problem.
3. Capture the Android logcat logs.
4. Post the captured logs to https://gist.github.com/ and add a comment to this issue with a link to the logs.

Thank you.
