### ISSUE TITLE
A closed socket IOException occurs if AutoCloseable is used when upload using InputStream in Firebase Storage.

### ISSUE THREAD

**Issue by choiman1559** [firebase/firebase-android-sdk#5749]
### [REQUIRED] Step 2: Describe your environment
I am testing with the following environment...
 - firebase-storage with firebase-bom:32.7.2
 - Android SDK 34
 - Java Version 11
 - Android Studio Hedgehog | 2023.1.1 Patch 2
 

### [REQUIRED] Step 3: Describe the problem
I don't know if this is the intended behavior, but I get an IOException when I use AutoCloseable like this:

```
StorageReference fileRef = blabla;
try(FileInputStream someStream = new FileInputStream(someFileObj)) {  
   UploadTask uploadTask = fileRef.putStream(someStream);

   blabla....

} catch (IOException e) {
   e.printStackTrace();
}
```

And Stacktrace:
```
Unable to read bytes for uploading
java.io.IOException: socket closed

at android.net.LocalSocketImpl$SocketInputStream.read(LocalSocketImpl.java:104)
at com.google.firebase.storage.internal.AdaptiveStreamBuffer.fill(AdaptiveStreamBuffer.java:105)
at com.google.firebase.storage.UploadTask.uploadChunk(UploadTask.java:465)
at com.google.firebase.storage.UploadTask.run(UploadTask.java:248)
at com.google.firebase.storage.StorageTask.lambda$getRunnable$7$com-google-firebase-storage-StorageTask(StorageTask.java:1077)
at com.google.firebase.storage.StorageTask$$ExternalSyntheticLambda7.run(Unknown Source:2)
at com.google.firebase.concurrent.LimitedConcurrencyExecutor.lambda$decorate$0$com-google-firebase-concurrent-LimitedConcurrencyExecutor(LimitedConcurrencyExecutor.java:65)
at com.google.firebase.concurrent.LimitedConcurrencyExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:1012)
```

**Comment by lehcar09** [comment]
Hi @choiman1559, thank you for reaching out. I tried reproducing the issue, however, I did not experience the exception. Can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?

Here's how I implement the upload.
```
try(FileInputStream someStream = new FileInputStream(String.valueOf(fileUri))) {
          UploadTask uploadTask = photoRef.putStream(someStream);
          uploadTask.addOnFailureListener(new OnFailureListener() {
              @Override
              public void onFailure(@NonNull Exception exception) {
                  Log.w(TAG, "uploadFromUri:onFailure", exception);
              }
          }).addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
              @Override
              public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {
                   Log.d(TAG, "Download URI: " + taskSnapshot.getUploadSessionUri());
              }
          });
 } catch (IOException e) {
          e.printStackTrace();
}
```

**Comment by choiman1559** [comment]
@lehcar09

```
public class TestReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
        Log.d("StreamTest", "Test Receiver Called!");

        FirebaseStorage storage = FirebaseStorage.getInstance();
        StorageReference storageRef = storage.getReferenceFromUrl("gs://blablabla.com");
        StorageReference fileRef = storageRef.child("/document.pdf");
        UploadTask task = null;

        try (FileInputStream stream = new FileInputStream("/storage/emulated/0/Download/document.pdf")) {
            task = fileRef.putStream(stream);
        } catch (Exception e) {
            e.printStackTrace();
        }

        if(task != null) {
            task.addOnSuccessListener(taskSnapshot -> Log.d("StreamTest","UploadTask Successfully Uploaded!!!"));
            task.addOnFailureListener(e -> Log.d("StreamTest","UploadTask Failed!!!"));
        } else {
            Log.d("StreamTest", "UploadTask is null!!!");
        }
    }
}

```

```
try {
```

**Comment by lehcar09** [comment]
That's a great finding. Thank you for sharing that. I was able to reproduce the issue as you mentioned.

However, this is more of an implementation issue. [BroadcastReceivers](https://developer.android.com/develop/background-work/background-tasks/broadcasts#effects-process-state) have a short timeout and are not meant for long-lived tasks. 

> Broadcast receivers should not initiate long-running background threads. The system can stop the process at any moment after onReceive() to reclaim memory, terminating the created thread. To keep the process alive, schedule a [JobService](https://developer.android.com/reference/android/app/job/JobService) from the receiver using the [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) so the system knows the process is still working. [Background Work Overview](https://developer.android.com/guide/background) provides more details.

You can use [BroadcastReceiver#goAsync()](https://developer.android.com/reference/android/content/BroadcastReceiver#goAsync()) method to extend the timeout. Or, use either [service](https://developer.android.com/develop/background-work/services) or [work manager](https://developer.android.com/develop/background-work/background-tasks/persistent/getting-started).

With that, I believe this resolves the issue, so I'll go ahead and close this thread. Let me know if you'd like this to be reopened. Thanks.
