### ISSUE TITLE
Security finding

### ISSUE THREAD

**Issue by ber4444** [firebase/firebase-android-sdk#5767]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: not relevant
  * Firebase Component: Sessions
  * Component version: latest

#### Steps to reproduce:

Your SDK is calling `activityManager?.runningAppProcesses` which has the problems already discussed in #5490

This method was used to determine which other Apps the user run on their device on pre-23 API levels .

As of 2014, Google began classifying Apps that collect the list of Apps on the device as Spyware, as described on page 29 of the [2014 Android Security Report](https://source.android.com/security/reports/Google_Android_Security_2014_Report_Final.pdf):

"Throughout 2014, we have regularly tightened the definition of Spyware, for example in 2014 we began to classify applications that send the list of other applications on the device as Spyware."

Lastly, a list of SDKs that have already been blocked by Google Play because of this issue can be found [here](https://stackoverflow.com/questions/27044517/notification-from-google-play-store).

#### Relevant Code:

https://github.com/firebase/firebase-android-sdk/blob/master/firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt#L37

**Comment by argzdev** [comment]
Hey @ber4444, thanks for bringing this up to our attention. Reading through the thread, from the most recent comment of our engineer, it looks like we are aligned with the usage of the API according to the privacy team. It shouldn't cause any problem.

> I checked with our team and we're comfortable with how we are using getRunningAppProcesses(). We used it to detect [background](https://github.com/firebase/firebase-android-sdk/blob/fe84885ec87d7457926812ab4ecfa70bf8583581/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java#L138) crashes and the latest change is part of ongoing work to better support multi-process apps. We also confirmed we use this [API](https://developer.android.com/reference/android/app/ActivityManager#getRunningAppProcesses()) appropriately as we are a debugging tool. We checked in with our privacy team, and we are aligned with this usage of the API.

However, based on your report, it looks like there's a problem. Was there any recent issue that you've encountered or did you receive an email regarding the violation of Google Play policy?
