### ISSUE TITLE
Branch details for Firebase messaging 23.3.1

### ISSUE THREAD

**Issue by InteractP** [firebase/firebase-android-sdk#5769]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by InteractP** [comment]
Since we have license issue with 23.4.1 we had to downgrade to 23.3.1. We need to share the codebase for firebase-messaging version 23.3.1 with our OSS team to get the approval for using this library. please share the code base for V23.3.1 and not the master branch. Was not able to find the tags

**Comment by argzdev** [comment]
Hey @InteractP, thanks for bringing this up to our attention. Now that you mentioned it, I did notice that our iOS repo have a history of releases and tags. Let me bring this up to our engineers and see what we can do here.

**Comment by argzdev** [comment]
I've received feedback from our engineers. It looks like while we don't necessarily have tags, we do have branches for all succeeding releases after M122. You can find it [here](https://github.com/firebase/firebase-android-sdk/branches/all?query=.release). Firebase Messaging version 23.3.1 is located at M139. You should be able to find it on this [branch](https://github.com/firebase/firebase-android-sdk/tree/releases/m139.release).

That said, I believe this resolves the issue, so I'll go ahead and close this thread. Feel free to let me know if you'd like this to be reopened or if you have suggestions how we can improve our version management. Thanks!

**Comment by InteractP** [comment]
What is the version of https://github.com/firebase/firebase-android-sdk/tree/releases/m139_3.release this branch
