### ISSUE TITLE
Error using com.google.gms: google-services: 4.3.0

### ISSUE THREAD

**Issue by Okami-x-Senpai** [firebase/firebase-android-sdk#577]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.1
  * Firebase Component: com.google.gms:google-services
  * Component version: 4.3.0

#### Steps to reproduce:

Previously I used com.google.gms: google-services: 4.2.0 but Android Studio told me there was a new update, then update to the new version com.google.gms: google-services: 4.3.0 and now I get a warning every time I compile my project, it makes me nervous to see errors when compiling.

> This is the warning message I get:

```
WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app
```

#### Relevant Code:
Before
```
classpath 'com.google.gms:google-services:4.2.0'
```

Now
```
classpath 'com.google.gms:google-services:4.3.0'
```

**Comment by samtstern** [comment]
@Okami-x-Senpai thanks for filing this!  I think this belongs over on the plugin repo, so I will transfer the issue:
https://github.com/google/play-services-plugins

**Comment by Viktoru** [comment]
====This classpath 'com.google.gms:google-services:4.3.0' is not working: my errors after I changed that:====

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.android.utils.FileUtils

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Finished with error: Gradle task assembleDebug failed with exit code 1

====If I keep classpath 'com.google.gms:google-services:4.2.0'
Works but, still the problem: =====

Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
