### ISSUE TITLE
Conflicting documentation regarding initialization in background processes

### ISSUE THREAD

**Issue by chr-stripe** [firebase/firebase-android-sdk#5774]
### [READ] Step 1: Are you in the right place?

I’m trying to square up two seemingly-conflicting messages in the FirebaseApp Android SDK documentation here, specifically in regards to how it works in multi-process apps. At the end of the `FirebaseApp` documentation, it states that initialization should only be done in the main process:

https://github.com/firebase/firebase-android-sdk/blob/b77c2188e5ec7c53c2a955fc4663b301e6c98c83/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L87-L89

However the documentation for the `initializeApp` method states the opposite, that initialization _should_ be done in secondary processes:

https://github.com/firebase/firebase-android-sdk/blob/b77c2188e5ec7c53c2a955fc4663b301e6c98c83/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L223-L224

Which one is correct?

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: N/A
  * Firebase Component: Common
  * Component version: Latest

#### Steps to reproduce:

Reading the `FirebaseApp` documentation.

#### Relevant Code:

See code linked above.

**Comment by lehcar09** [comment]
Hi @chr-stripe, thank you for reaching out. 

For Android apps using Firebase, there is a central [FirebaseApp](https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseApp) object that manages the configuration for all the Firebase APIs. This is initialized automatically by a content provider when your app is launched, and you typically never need to interact with it. 

https://github.com/firebase/firebase-android-sdk/blob/b77c2188e5ec7c53c2a955fc4663b301e6c98c83/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L223-L224

However, when you want to access multiple projects from a single app, any FirebaseApp initialization must occur only in the main process of the app.

https://github.com/firebase/firebase-android-sdk/blob/b77c2188e5ec7c53c2a955fc4663b301e6c98c83/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java#L87-L89

You can check the blog posts below for more detailed explanation.
[How does Firebase initialize on Android?](https://firebase.blog/posts/2016/12/how-does-firebase-initialize-on-android)
[Working with multiple Firebase projects in an Android app](https://firebase.blog/posts/2016/12/working-with-multiple-firebase-projects-in-an-android-app)

Hope that helps. With that, I’ll be closing this case now. Let me know if we need to re-open the issue.

**Comment by chr-stripe** [comment]
Thanks for the response @lehcar09. This isn't a concern about accessing multiple projects from a single app though – this is just about using a single project from a multi-process app.

That first link you sent is helpful and mentions the use case I'm asking about down the page:

> The other thing to know about about ContentProviders is that they are only run in the main process of an app. For a vast majority of apps, this isn’t a problem, as there is only one process by default. But the moment you declare that one of the Android components in your app must run in another process, that process won’t create any ContentProviders, which means your `ContentProvider` onCreate will never get invoked. In this case, the app will have to either avoid calling anything that requires the initialization, or safely initialize another way. Note that this behavior is different than a custom Application subclass, which does get invoked in every process for that app.

In that case it does seem that using Firebase outside of the main process is supposed, so long as an explicit call to `initializeApp()` is made (likely from the Application class). My original question was around the contradictory statement in the `FirebaseApp.java` overview documentation cited above:

> [...] Use of Firebase in processes other than the main process is not supported and will likely cause problems related to resource contention.

This makes it seem like _any_ Firebase usage outside of the main process is unsupported. But based on our experience, it seems like it does indeed work. I might be splitting words here, but maybe it should mention that it's not "officially supported", instead of saying it's unsupported.
