### ISSUE TITLE
Too many threads may created.

### ISSUE THREAD

**Issue by Edison0716** [firebase/firebase-android-sdk#5779]
[REQUIRED] Step 2: Describe your environment
Android Studio version: 2022.3.1 Patch 1
Firebase version: com.google.firebase:firebase-bom:31.1.1
[REQUIRED] Step 3: Describe the problem
2000+ "firebase-iid-executor" threads have been created.

## Problem

![img_v3_028u_d5bbc613-535a-418e-8796-8658f28f7acg](https://github.com/firebase/firebase-android-sdk/assets/8669094/d3d8781c-b958-4c9c-a2bf-e4574f65ff29)

![image](https://github.com/firebase/firebase-android-sdk/assets/8669094/44fede4c-30cd-4b0a-ac0c-a6eaf68bcb05)

When received a push message, then will create a Receiver object. so no matter how, can not create a new thread pool in constructor.

Please check this logic. If i mistake, please tell me.

**Comment by lehcar09** [comment]
Hi @Edison0716, thank you for reaching out. I noticed that you're using the SDK version (v31.1.1), where the fix (#5570) mentioned in #5284 is not yet merged. Could you try if the issue persists in the version [32.7.0](https://firebase.google.com/support/release-notes/android#2023-12-07) and above ([32.7.4](https://firebase.google.com/support/release-notes/android#bom_v32-7-4))?

**Comment by Edison0716** [comment]
![image](https://github.com/firebase/firebase-android-sdk/assets/8669094/742bd4e3-6a68-4d47-ba85-d47e32aa5c02)


my version looks not have any code changed. if my mistake, please tell me.
