### ISSUE TITLE
I have added firebase crashlytics to my react native project and play store reject my app how to fix it?

### ISSUE THREAD

**Issue by Mohamed-Ziyad** [firebase/firebase-android-sdk#5782]
We found an issue in the following area(s):

Version code 28:
SDK: Fabric io.fabric.sdk.android:fabric (consider upgrading to version com.google.firebase:firebase-crashlytics:18.4.0)
To bring your app into compliance, follow these steps:

You may consider upgrading to a policy-compliant version of this SDK, if available from your SDK provider or removing the SDK.
Fabric io.fabric.sdk.android:fabric: Consider upgrading to version com.google.firebase:firebase-crashlytics:18.4.0 of the SDK

app/gradle 

 implementation "com.google.firebase:firebase-crashlytics:18.6.2"
    implementation "com.google.firebase:firebase-analytics:21.5.1" 
    implementation 'com.google.firebase:firebase-messaging:23.4.1'

**Comment by lehcar09** [comment]
Hi @Mohamed-Ziyad, thank you for reaching out. To give an overview, Google has now completely migrated from Fabric to Firebase Crashlytics. React Native has a different migration path. I suggest checking out the [documentation](https://rnfirebase.io/crashlytics/android-setup) for reference on how to setup/ migrate your project. 

If the issue persists, it would be best to reach to the [Investase (React Native)](https://github.com/invertase/react-native-firebase/issues) team.
