### ISSUE TITLE
FR: Provide a synchronous way to get the Instance ID

### ISSUE THREAD

**Issue by dapp** [firebase/firebase-android-sdk#583]
* Operating System version: Android 9
  * Firebase SDK version: 17.0.0
  * Library version: ?
  * Firebase Product: Core

There is no way to synchronously get the FirebaseInstanceId token.  

We use the firebase instance ID as part of our authentication scheme.  When the instance id token changes and the app has not been notified yet (no call to onNewToken), APIs fail, because the instance ID is invalid.  In this case, we want to intercept that failure response, refresh the firebase instance id, and retry.  However, because FirebaseInstanceId.getInstance().getInstanceId() returns a Task *that always and can only callback to the MAIN thread with a result* it makes it needlessly difficult to make this operation atomic.  The SDK should provide a synchronous way to get the token and trust clients to implement this responsibly in their code.

**Comment by ashwinraghav** [comment]
@dapp Does `Tasks.await` not solve your use case ?

https://developers.google.com/android/guides/tasks#blocking

**Comment by dapp** [comment]
Not sure what's going on here guys.  I opened this issue at least a year ago, not sure why it's just been transferred here.  Pretty sure we solved this way back, you can go ahead and close it.
