### ISSUE TITLE
Images getting corrupted on upload to bucket

### ISSUE THREAD

**Issue by pratham-PDots** [firebase/firebase-android-sdk#5843]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Giraffe | 2022.3.1 Patch 2
  * Firebase Component: Storage
  * Component version: 20.2.1

### [REQUIRED] Step 3: Describe the problem
This issue occurs randomly with some uploaded images i.e. it does not occur with every uploaded image so have not been able to reproduce but have faced it in production. 

Have also noticed that the size of all such corrupted images have size as multiple of 256 KB (for example 512 KB, 1536 KB etc.)

#### Steps to reproduce:

General steps : 

1. Upload an image using the provided code.
2. Check the uploaded image file in the Firebase Storage console or download it to a device.

#### Relevant Code:

```kotlin
package com.example.services

import android.app.Service
import android.content.Intent
import android.net.Uri
import android.os.IBinder
import android.util.Log
import com.google.firebase.storage.FirebaseStorage
import com.google.firebase.storage.StorageMetadata
import com.google.firebase.storage.StorageReference
import java.io.File

class MyService : Service() {

    private var storage: FirebaseStorage? = null
    private var storageReference: StorageReference? = null

    override fun onBind(intent: Intent?): IBinder? {
        return null
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        // Initialize Firebase storage
        storage = FirebaseStorage.getInstance()
        storageReference = storage!!.reference

        // Dummy list of image URIs
        val imageList = listOf(
            "uri1",
            "uri2",
            "uri3"
        )

        // Upload images to Firebase
        if (imageList.isNotEmpty()) {
            uploadImages(imageList)
        }

        return START_STICKY
    }

    private fun uploadImages(imageList: List<String>) {
        imageList.forEach { uri ->
            val fileUri: Uri = Uri.parse("file://$uri")

            // Set metadata for the uploaded image
            val metadata = StorageMetadata.Builder()
                .setContentType("image/jpeg")
                // Add custom metadata as needed

            // Upload image to Firebase Storage
            val uploadTask = storageReference?.child(uri)?.putFile(fileUri, metadata.build())

            // Handle upload success, failure, and progress
            uploadTask?.addOnSuccessListener { taskSnapshot ->
                // Handle successful upload
                // You can get the download URL if needed:
                val downloadUrl = taskSnapshot.metadata?.reference?.downloadUrl
                Log.i("MyService", "Image uploaded successfully")

                // Remove the uploaded image from local storage
                removeImageFromLocalStorage(uri)
            }?.addOnFailureListener { exception ->
                // Handle failed upload
                Log.e("MyService", "Image upload failed: ${exception.message}")
            }?.addOnProgressListener { progress ->
                // Handle upload progress
                val progressPercent = 100.0 * progress.bytesTransferred / progress.totalByteCount
                Log.i("MyService", "Upload progress: $progressPercent%")
            }
        }
    }

    private fun removeImageFromLocalStorage(uri: String) {
        val file = File(uri)
        if (file.exists()) {
            val isDeleted = file.delete()
            Log.d("MyService", "Deleted image from local storage: $isDeleted")
        }
    }

    override fun onDestroy() {
        super.onDestroy()
    }
}

**Comment by pratham-PDots** [comment]
Hi @lehcar09 , thankyou for looking into the issue. 

These are received randomly, 1 out of say 100 images comes out as corrupted, as for devices, mostly have observed in **Galaxy A53 5G** (Android 14) but have gotten on some other devices as well.

- Could you tell me why network or resource allocation would be a factor here? And how I could look into that? 

- Also the corrupted images always have a size i.e. a multiple of 256 KB, was thinking if that has something to do with firebase chunk size?

As for reproducing it, I have never been able to reproduce it either, only received corrupted images from users, will look into work manager though, would that help fix the issue you think? 

Attached a corrupted image for reference : 
![c566e0c7-3918-4bf0-88c4-ffa5d2f37980_1](https://github.com/firebase/firebase-android-sdk/assets/145988153/4a7778b6-6f43-4d2f-a428-a626b2415641)

**Comment by pratham-PDots** [comment]
Hi @lehcar09 , could you provide some info on the above questions? Would help debug the issue on my end, thanks!

**Comment by lehcar09** [comment]
I’ll close this thread for now. If you were able to reproduce the issue or details that could help us investigate the issue, let me know so we can re-open the issue. Thanks!
