### ISSUE TITLE
Could not get Response payload size data from firebase perfomance monitoring

### ISSUE THREAD

**Issue by KrunalStrategyX** [firebase/firebase-android-sdk#5847]
**Environment**

  * Android Studio version: Android Studio Iguana | 2023.2.1 Patch 1 (Runtime version: 17.0.9+0--11185874 amd64)
  * Firebase Component And version
     *  Build.gradle(app)
        implementation 'com.google.firebase:firebase-auth-ktx:22.3.1'
        implementation 'com.google.firebase:firebase-analytics-ktx:21.6.1'
        implementation 'com.google.firebase:firebase-messaging-ktx:23.4.1'
        implementation 'com.google.firebase:firebase-database-ktx:20.3.1'
        implementation 'com.google.firebase:firebase-perf-ktx:20.5.2'
        implementation 'com.google.firebase:firebase-crashlytics-ktx:18.6.3'
    *  Build.gradle(project)
       buildscript {
          dependencies{
               classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
               classpath ('com.google.firebase:perf-plugin:1.4.2') {
                       exclude group: 'com.google.guava', module: 'guava-jdk5'
               }
          }
       }
       
       

**Problem**
I have created one custom url pattern for note data of response time, success rate, response payload size, request payload size.
i was get data properly. I was update firebase lib as android studio suggest after that time other data i found but response payload size data is not get.
i was create firebase ticket for this issue 2 time and they taken more than 1.5 year time to resolve this issue but they not resolve this one every time they told more time for resolving but issue is not fix and response payload size data  is not get.

**Steps to reproduce**

I submit all related data as you need to find this issue. please check this one RE: Case 10258948: I could not get Response payload size data from firebase perfomance monitoring because i already reported this issue in firebase support but they close this issue today. so please fix this one ASAP because i already wait more than 1.5 year.

**Comment by lehcar09** [comment]
Hi @KrunalStrategyX, thank you for reaching. I tried reproducing the issue, and somehow I encountered the behavior you're experiencing. Initially, I did not not set the `content-length` key in the response header, and upon checking in the Firebase console, the **Response payload size** is blank. After I defines the `content-length` key in the response header, the **Response payload size** metric is populated. 

Based on our [documentation](https://firebase.google.com/docs/perf-mon/get-started-android#known_issues), 
> Performance Monitoring reports the total payload size for HTTP network requests based on the value set in the HTTP content-length header. This value might not always be accurate.

Did you set the 'content-length' key in the response header from your server?

**Comment by KrunalStrategyX** [comment]
> Hi @KrunalStrategyX, thank you for reaching. I tried reproducing the issue, and somehow I encountered the behavior you're experiencing. Initially, I did not not set the `content-length` key in the response header, and upon checking in the Firebase console, the **Response payload size** is blank. After I defines the `content-length` key in the response header, the **Response payload size** metric is populated.
> 
> Based on our [documentation](https://firebase.google.com/docs/perf-mon/get-started-android#known_issues),
> 
> > Performance Monitoring reports the total payload size for HTTP network requests based on the value set in the HTTP content-length header. This value might not always be accurate.
> 
> Did you set the 'content-length' key in the response header from your server?

Hi @lehcar09 I told about this to my backend team and they investigating about content-length in response header when they give me any update related to this i will let you know, between that time of period not close this issue.
