### ISSUE TITLE
Analytics - duplicated events in Debug View / Debug build

### ISSUE THREAD

**Issue by leonardosgcit** [firebase/firebase-android-sdk#5858]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 Patch 2
  * Firebase Component: Analytics
  * Component version: 32.8.0

### [REQUIRED] Step 3: Describe the problem

Some events are duplicated when using the Debug View.
It doesn't seem to happen in a release build.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

![2024-04-01_16-27-21](https://github.com/firebase/firebase-android-sdk/assets/112174545/2b936262-12a6-494f-a237-979922ab9d15)

Adding logs before each "logEvent" call and enabling the **FA** and **FA-SVC** logs, I noticed that a single call to "logEvent" caused two "Logging event" messages and the events have the same parameter values:

![2024-04-11_08-10-15](https://github.com/firebase/firebase-android-sdk/assets/112174545/a5d7d41b-6c1c-4167-a091-2de3f26e9632)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by lehcar09** [comment]
Hi @leonardosgcit, thank you for reaching out. I tried reproducing the issue, but I was unable to encounter the behavior. Can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) or code snippet  to help us investigate the issue? Thanks!

**Comment by lehcar09** [comment]
Can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) with me? Here's how I log the similar event, but seeing just one instance in the debug view. 
```
firebaseAnalytics.logEvent("login_app_success") {
          param("custom_uuid", "test")
      }
```
<img width="228" alt="Screenshot 2024-04-13 at 1 03 54 AM" src="https://github.com/firebase/firebase-android-sdk/assets/155964350/89d7aa92-09c8-43e8-a773-36f408d9897b">

**Comment by lehcar09** [comment]
Thanks for sharing that. Could you share a code snippet on how you are logging the event? Is there another event that duplicates?

Aside from that, could you try to move the logging of events (i.e another function call)? Another possibility I could think of for this to happen is, if you are creating an event based on an existing event. Per checking, if you have created an event from the console, it also shows up in the verbose log. You could check this [documentation](https://support.google.com/analytics/answer/12844695?hl=en) for reference.

**Comment by chopfitzroy** [comment]
Seeing this as well when trying to send an event for each item in a cart, so same event sent X number of times with different values.

Instead what I get is X number of events with all the values combined.

**Comment by lehcar09** [comment]
Hi @leonardosgcit, just wanted to check if you heard anything from your team about the possiblity that you have event created from console?

**Comment by lehcar09** [comment]
Hi @leonardosgcit. I understand. Based in my investigation, the `_syn` parameter is added to events created from Firebase console. That being said. I'll be closing this thread for now. Let me know if we need to  re-open the issue for investigation. Thanks!
