### ISSUE TITLE
onNewToken() returns the wrong token

### ISSUE THREAD

**Issue by night556** [firebase/firebase-android-sdk#5863]
### [READ] Step 1: Are you in the right place?

  I think it's in the right place.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component:  firebase-bom:31.1.0
  * Component version: 31.1.0
  * Network: have vpn network

#### Steps to reproduce:

I'm using fcm to push offline messages, but often encountered "Requested entity was not found." error, after investigation, we found that the token mainly comes from two functions: getToken() and onNewToken(). There are two cases:
1. when the application starts for the first time, getToken() gets TokenA (valid token), the server sends an offline message to the client, and onNewToken() gives a new tokenB (invalid token).
2. when the application starts for the first time, getToken() gets TokenA (invalid token), server sends an offline message to the client, then onNewToken() still gives TokenA (invalid token).

*After getting TokenA, if server doesn't send offline message, onNewToken() won't report new token to server.*

#### Relevant Code:

onNewToken()
```
override fun onNewToken(token: String) {
       super.onNewToken(token)
       updateFCMToken(token) // Upload token to server
}
```

**Comment by lehcar09** [comment]
Hi @night556, thank you for reaching out. I tried reproducing the issue, however, I did not encounter an issue with the token  I received in my app. I was able to send a message successfully in the app using Admin SDK - Node.js and Firebase console. I'ts possible that the VPN is what's causing the issue. Have you tried disabling your VPN?

**Comment by night556** [comment]
Thank you for your reply, for some reason we need to use a VPN to get the token. we can't get more information about the situation without a VPN, but we will be adding logs to record the situation later, I will reply here if there is more information.
Lastly, I would like to know if in this case it can be assumed with a high probability that it is due to the VPN that is causing the issue.

**Comment by night556** [comment]
If it's due to a VPN, what's the root cause usually?

**Comment by lehcar09** [comment]
Hi @night556, based on our [documentation](https://firebase.google.com/docs/cloud-messaging/concept-options#vpns),

> VPNs mask the underlying information that FCM needs to tune its connection to maximize reliability & battery life.  In some cases VPNs actively break long lived connections resulting in a bad user experience due to missed or delayed messages or a high battery cost...Different VPNs will have different methods for controlling whether or not it can be bypassed. Consult the documentation for your specific VPN for instructions.

I suggest reaching out to the [Firebase support channel ](https://firebase.google.com/support/)instead. We'd need access to your project settings (including projectID, SHA-1 etc) to troubleshoot this type of issue.

**Comment by night556** [comment]
Thanks for the advice.
