### ISSUE TITLE
R.txt files contain transitive resources

### ISSUE THREAD

**Issue by ashwinraghav** [firebase/firebase-android-sdk#59]
It seems like the R.txt files contain transitive resources in all our releases.

Seems like this is a well known issue that is fixed in the alpha release of the Android Gradle Plugin
https://twitter.com/JakeWharton/status/1032396242062594048

**Comment by vkryachko** [comment]
@ashwinraghav Is this still a problem?

**Comment by vkryachko** [comment]
The issue has been inactive for a long time, will close for now. Feel free to reopen if it is still an issue
