### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException fid must not be null

### ISSUE THREAD

**Issue by wahyupermadie** [firebase/firebase-android-sdk#5912]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment
Android Studio version: Iguana Build #AI-232.10227.8.2321.11479570
Firebase Component: Crashlytics
Component version:
fireBaseBomVersion = '32.8.0'
firebaseSession = '1.2.3'

### [REQUIRED] Step 3: Describe the problem
In production app we got this kind of error after updating the firebase version, we update it for the Crash Free Sesson on Firebase Crashlytics.
```
Fatal Exception: java.lang.NullPointerException: fid must not be null
       at com.google.firebase.sessions.InstallationId$Companion.create(InstallationId.kt:46)
       at com.google.firebase.sessions.InstallationId$Companion$create$1.invokeSuspend(InstallationId.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:47)
       at java.lang.Thread.run(Thread.java:919)
```
#### Steps to reproduce:
We not able to reproduce locally, only seen the issue on firebase crashlytics report. Previously we facing this issue https://github.com/firebase/firebase-android-sdk/issues/5765, after we bump the firebase bom based on those fix version, we got this new crash

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by lehcar09** [comment]
Hi @wahyupermadie, thank you for reaching out. Based on the latest [release notes](https://firebase.google.com/support/release-notes/android#crashlytics_v18-6-4), there has been a fix in Firebase Crashlytics that force validation or rotation of Firebase Installation ID. Could you try updating to the latest [BOM 32.8.1](https://firebase.google.com/support/release-notes/android#bom_v32-8-1)?

**Comment by wahyupermadie** [comment]
Thank you @lehcar09 , btw is there any PR i can take look related those changes ?

**Comment by lehcar09** [comment]
Hi @wahyupermadie, this is the PR (#5812) to that fix.

I'll be closing this case for now. Should the issue persists, let me know so we can re-open this ticket and investigate the issue further.
