### ISSUE TITLE
Add API for isCrashlyticsCollectionEnabled()

### ISSUE THREAD

**Issue by david-livefront** [firebase/firebase-android-sdk#5919]
## What feature would you like to see?

We would like an Android API for determining if Crashlytics data collection is enabled similar to the [isCrashlyticsCollectionEnabled()](https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/Crashlytics#iscrashlyticscollectionenabled) API in Swift Project.

Ideally the new function would be part of [FirebaseCrashlytics](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java) and it would return a boolean indicating if Crashlytics data collection is currently enabled or disabled.

```java
public boolean isCrashlyticsCollectionEnabled()
```

## How would you use it?

We want to be able to allow users to easily see whether crash logging is enabled or disabled in our app.

**Comment by andjv5** [comment]
[https://firebase.google.com/docs/reference/swift/firebasecrashlytics/api/reference/Classes/Crashlytics#crashlytics_1](url)
