### ISSUE TITLE
uses-sdk:minSdkVersion 21 cannot be smaller than version 23 

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#5927]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: **N/A**
  * Firebase Component: **Auth** (Database, Firestore, Storage, Functions, etc)
  * Component version: **23.0.0**

### [REQUIRED] Step 3: Describe the problem

Updating from 22.3.1 to 23.0.0 cause error due to minSdk

#### Steps to reproduce:

Updating from 22.3.1 to 23.0.0

Question. Why do we need to update minSdk from 21 to 23? Why the library is forcing us? Can anyone describe the changes for this to be necessary? If this is related to Android 14 that requires `targetSdk` to be at least 23 then this is incorrect and not necessary.

**Comment by lehcar09** [comment]
Hi @ArcherEmiya05, thank you for reaching out. I was able to replicate the issue. Per checking on the Firebase Auth documentation and release notes, there are no mentions that the minSdk is bumped to 23. I’ll notify our engineers and see what we can do here. Thanks!

**Comment by thatfiredev** [comment]
Release notes are on the way. :)

@ArcherEmiya05 we had to upgrade to minSdk 23 because some of our internal dependencies that also got upgraded to 23. If you still need minSdk 21, you can continue using `22.3.1`. 

I'll leave this issue open in case more developers are unable to upgrade to minSdk 23.

**Comment by ArcherEmiya05** [comment]
> Release notes are on the way. :)
> 
> @ArcherEmiya05 we had to upgrade to minSdk 23 because some of our internal dependencies that also got upgraded to 23. If you still need minSdk 21, you can continue using `22.3.1`. (this is unrelated to Android 14)
> 
> I'll leave this issue open in case more developers are unable to upgrade to minSdk 23 - please leave a thumbs up on the first message on the thread.

Thanks for the explanation, but this would mean we no longer get the latest patch or fixes if we stay in `22.3.1`. Other services like storage or firestore does not even require this breaking changes, has this something to do with vulnerability?

**Comment by thatfiredev** [comment]
@ArcherEmiya05 Yes, this was indeed due to a security issue on the Auth side.
