### ISSUE TITLE
Metadata for `firebase-crashlytics-gradle` version `3.0.0` is missing the dependencies on 

### ISSUE THREAD

**Issue by yogurtearl** [firebase/firebase-android-sdk#5929]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 8.4.0
  * Firebase Component: `firebase-crashlytics-gradle`
  * Component version: `3.0.0` (was working in `2.9.9` 

#### Steps to reproduce:

Create a small gradle plugin that relies on the firebase crashlytics gradle plugin (see code below)

`3.0.0` seems to have added a reference to `com.android.build.api.variant.ApplicationAndroidComponentsExtension` 
in the file `com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsPlugin`

but it didn't add the needed dependency in the published [`.pom` file ](https://dl.google.com/android/maven2/com/google/firebase/firebase-crashlytics-gradle/3.0.0/firebase-crashlytics-gradle-3.0.0.pom)or the [`.module` file](https://dl.google.com/android/maven2/com/google/firebase/firebase-crashlytics-gradle/3.0.0/firebase-crashlytics-gradle-3.0.0.module). 

Those files should declare dependencies on all other things that are in use. 

in this case, they need to have a dependency on `com.android.tools.build:gradle-api`

#### Relevant Code:

in `src/main/kotlin/firebase-crashlytics.gradle.kts`
```
plugins {
    id("com.google.firebase.crashlytics")
}
```

in `build.gradle.kts` 
```kotlin
plugins {
    `kotlin-dsl`
}

dependencies {
    implementation("org.apache.httpcomponents:httpclient:4.5.14")
    implementation("com.google.firebase.crashlytics:com.google.firebase.crashlytics.gradle.plugin:3.0.0")
}
```

### Context: 

This is similar to this issue: https://github.com/firebase/firebase-android-sdk/issues/5473

### workaround

add this to the `build.gradle.kts` file of your plugin that depends on the firebase crashlytics plugin: 
```kotlin
   implementation("com.android.tools.build:gradle-api:8.4.0")
```

**Comment by Ma7moud3ly** [comment]
Once I have updated to firebase-crashlytics 3.0.0, I keep getting this error ```Circular dependency between the following tasks```
I had to revert to 2.9.9 🤔

**Comment by lehcar09** [comment]
Hi @yogurtearl, thank you for reaching out and reporting the issue. I tried reproducing the issue, however, I’m having a hard time in replicating it. Is there any chance you could share an MCVE to help us investigate the issue?

You mentioned that this is similar [#5473](https://github.com/firebase/firebase-android-sdk/issues/5473). It’s possible that the cause is similar to https://github.com/firebase/firebase-android-sdk/issues/5473#issuecomment-1960211191. Let me check this with our engineer.

**Comment by lehcar09** [comment]
> Once I have updated to firebase-crashlytics 3.0.0, I keep getting this error `Circular dependency between the following tasks` I had to revert to 2.9.9 🤔

Hi @Ma7moud3ly. The error you're experiencing is related to this issue. The fix has not been released yet as per https://github.com/firebase/firebase-android-sdk/issues/5925#issuecomment-2093184082. You can try the latest changes from the pre-release build https://github.com/firebase/firebase-android-sdk/issues/5733.

**Comment by mrober** [comment]
@yogurtearl can you please explain a little bit why you setup the plugin like this? In the other issue, you mentioned a build script. But I still don't understand why you define the dependencies like this, instead of in the `plugins` block?

Also, what version of the Android Gradle plugin do you use? You should get a much more friendly error message with a link to documentation in it.

**Comment by yogurtearl** [comment]
Using AGP 8.4.0 in this example. 

If I want to create a plugin that applies the firebase crashlytics gradle plugin and does some additional config, I need to add the firebase crashlytics plugin as a dependency. 

Is there a downside for firebase crashlytics gradle plugin correctly declaring all of its dependencies in the meta-data?

**Comment by rlazo** [comment]
Hey @yogurtearl we released version `3.0.1` last Monday to address your issue. Please update and confirm if it works for you. Thanks!

**Comment by Climbatize** [comment]
@rlazo I confirm it works. I was awaiting for this one but my dependency manager did not warn me about 3.0.1

The reason is I usually use the same version variable for `firebase-crashlytics-buildtools` and it's not matching `firebase-crashlytics-gradle` anymore. I guess it was a bad practice

**Comment by rlazo** [comment]
Thanks for the confirmation!
