### ISSUE TITLE
Firebase App Distribution 17.0.0 isn't available

### ISSUE THREAD

**Issue by joshafeinberg** [firebase/firebase-android-sdk#5932]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Jellyfish
  * Firebase Component: App Distribution(Database, Firestore, Storage, Functions, etc)
  * Component version: 17.0.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

It appears that version 17.0.0 wasn't released properly. The page is unable to load (https://maven.google.com/web/index.html#com.google.firebase:firebase-appdistribution:17.0.0) and I get errors both locally and on CI when I attempt to download.

**Comment by lehcar09** [comment]
Hi @joshafeinberg, thank you for reaching out. Currently, the latest version of Firebase App Distribution is 16.0.0-beta12. You can check the latest versions and release notes from [here](https://firebase.google.com/support/release-notes/android).  

The v17.0.0 might be a placeholder for the next version. However, I understand if this might be confusing.  I'll notify our engineers about this and see what we can do here. 

For now, I suggest using the version posted from our official release notes.

**Comment by rlazo** [comment]
Hi @joshafeinberg thanks for your report.

Due to an internal error, a `17.0.0` artifact was pushed and later pulled from maven. We know this is a disruptive process and we are sorry. We are creating additional safeguards to prevent this from happening in the future.

**Please, use `16.0.0-beta12` instead**, as it's the latest version.

**Comment by rlazo** [comment]
The invalid artifacts are no longer included in the maven index.
