### ISSUE TITLE
[firebase_crashlytics] clarify the "Proximity on" on the device status tab

### ISSUE THREAD

**Issue by michaelxue19** [firebase/firebase-android-sdk#5953]
I am not sure that I posted to the appropriate channel. please let me know where is the best place if needed.

I have a constant FireTV fatal exception reported to the Crashlytics console. And I have no idea what causes this as it lacks clear stack trace or information.

This exception is reported from enormous(100k+) devices and operating systems.
Devices - various. 100% is Amazon though
Operating systems - various. Android 7 - 11
Device states - 0% in background, <1% rooted, 2.19 GB Free space, 136.31 MB GB Free RAM, 100% proximity on

I wonder if I can clarify the meaning of "background" and "proximity on". 
1) Does the "0% in background" mean this crash occurred in foreground(when it is visible to users)? 
2) What does the meaning of the "100% proximity on"?  Was the proximity sensor enable?

**Comment by lehcar09** [comment]
Hi @michaelxue19, thank you for reaching out.

>Does the "0% in background" mean this crash occurred in foreground(when it is visible to users)?

That's correct. `0% in background` means that the crash did not occur when the app was in the background. Crashlytics collect a boolean indicating whether or not the app was in the background at the time it crashed. 

>What is the meaning of the "100% proximity on"? Was the proximity sensor enable?

Proximity On - displays the percentage of the devices that had their[ proximity sensors](https://source.android.com/devices/sensors/sensor-types) on when the crash occurred.
