### ISSUE TITLE
Asking for self repository for project

### ISSUE THREAD

**Issue by Stromlight** [firebase/firebase-android-sdk#5956]
I was building app on firebase adding Google developer and GitHub I like you to collaborate on my project lifeeducation.

**Comment by Stromlight** [comment]
I know but what I had is might you dont

**Comment by lehcar09** [comment]
Hi @Stromlight, thank you for reaching out. This channel is for Firebase Android SDK related issue. You could check the Firebase Extended repositories for projects that are not officially staffed by Googlers but may be of use to Firebase developers. 

You can also reach out to the [Firebase Support team](https://firebase.google.com/support/troubleshooter/contact) for feature requests.

**Comment by Stromlight** [comment]
Hey thank you , I am excited to be part in here ,I like you to stay with me on new app building journey , did you like to give any suggestions for Progressive we app building , I am doing that.
