### ISSUE TITLE
SQLiteEventStore.runCriticalSection : java.lang.IllegalStateException - attempt to re-open an already-closed object: SQLiteDatabase

### ISSUE THREAD

**Issue by lklong1551019** [firebase/firebase-android-sdk#6010]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 

  Android Studio Jellyfish | 2023.3.1 Patch 1
Build #AI-233.14808.21.2331.11842104, built on May 15, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
  ide.instant.shutdown=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  io.github.stefansjs.flatbuffersplugin (0.5+31)
  name.kropp.intellij.makefile (233.13135.65)

  * Firebase Component: com.google.gms:google-services:4.4.1, com.google.firebase:firebase-crashlytics-gradle:2.9.9, org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21, com.google.firebase:firebase-bom:32.8.0
  * Component version: org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21

#### Steps to reproduce:

After updating firebase bom from 31.2.3 to 32.8.0, for the past few days we have been experiencing random crashes (~ 7 crashes per day on avg) on a variety of devices, across every android version (58% android 13), with 95% events happened while in background. It happened on app start, eg, the first 5 seconds.

We cannot reproduce this. Here is an example stack trace:

```
 Fatal Exception: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/our-package-name/databases/com.google.android.datatransport.events
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:587)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:772)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:164)
       at com.google.android.datatransport.runtime.ForcedSender.sendBlocking(ForcedSender.java:36)
       at com.google.firebase.crashlytics.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0(ReportQueue.java:138)
       at java.lang.Thread.run(Thread.java:1012)
```

<img width="1060" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/4029771f-e858-4ce1-8f20-f95194b2fb53">

<img width="1176" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/b6897914-a38c-48eb-ba63-2f03a271a81b">

Is there anything we could do? Any insight would be appreciated.

**Comment by lehcar09** [comment]
Hi @lklong1551019, thank you for reporting the issue. This issue seems related to the issue #6001 you reported. I have raised this issue to our engineers and are already taking a look. Please hang tight!

**Comment by lklong1551019** [comment]
thank you, glad to hear that. I'm looking forward to hearing updates, cheers.

**Comment by lehcar09** [comment]
I'll be closing this thread now. To streamline the updates from our engineer, moving forward, you can check on the issue #6001. Thanks!
