### ISSUE TITLE
Fix Functions Call Timeouts

### ISSUE THREAD

**Issue by allisonbm92** [firebase/firebase-android-sdk#604]
Firebase Functions incorrectly implements call timeouts. This was originally raised in #212 but was never correctly fixed.

OkHttp provides four different kinds of timeouts: connect, read, write, and call. Functions only configures the call timeout. The default connect, read, and write timeouts are still enforced, meaning the server must respond within 10 seconds. The default Functions timeout of 70 seconds, or any user provided timeout, are essentially ignored.

This can be seen from this test run: https://storage.cloud.google.com/android-ci/pr-logs/pull/firebase_firebase-android-sdk/578/new-smoke-tests/1149370348362272769/artifacts/walleye-26-en-portrait/test_cases/0006_logcat

**Comment by mikemilla** [comment]
@allisonbm92 Not sure if this is the place to reference the test for this, but might want to ensure this fix is succeeding in the tests?

https://github.com/firebase/firebase-android-sdk/blob/c4f0bb30a2ded40c2757e0c115b3894e3463b978/firebase-functions/src/androidTest/java/com/google/firebase/functions/CallTest.java#L218

_I'm also not sure this tests is accurate either_

Thanks for the fix btw! Been needing this for a while 😊

**Comment by shc2018** [comment]
Thank you for the fix. Is it possible to know estimate date/days for this release?

**Comment by allisonbm92** [comment]
@shc2018 We're planning on releasing it by the end of next week!

**Comment by shc2018** [comment]
Great! Thank you.

**Comment by permadiberlianto** [comment]
Waiting for updates, I am getting this error too. Thank you.
