### ISSUE TITLE
App Crash due to firebase-messaging's unsolicited directBootAware service

### ISSUE THREAD

**Issue by gipartha** [firebase/firebase-android-sdk#6047]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Jellyfish | 2023.3.1 Patch 1
     Build #AI-233.14808.21.2331.11842104, built on May 15, 2024
     Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

  * Firebase Component: com.google.firebase:firebase-messaging
  * Component version: 23.2.1

### [REQUIRED] Step 3: Describe the problem
- MS Teams application crashing on boot due to below exception:
_Exception java.lang.RuntimeException: Unable to instantiate application com.xxx.TeamsApplication package com.xxx.teams: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 10) is unlocked_
 Same has been observed for Outlook app as well.
 
Google Play Console Crash Link [here](https://play.google.com/console/u/0/developers/6720847872553662727/app/4974609607564367381/vitals/crashes/5a17e14b6356036b34d491c4e3a49fb0/details?days=28)

From the direct boot mode Android [documentation](https://developer.android.com/privacy-and-security/direct-boot), it's clear that this crash can occur only if some component is registering for direct boot mode.
No component in our app does this and from the merged manifest we could find that below Firebase components are using the same.

```
<service
    android:name="com.google.firebase.components.ComponentDiscoveryService"
    android:directBootAware="true"
    android:exported="false" >
    ...
</service>

<service
    android:name="com.google.firebase.messaging.FirebaseMessagingService"
    android:exported="false"
    android:directBootAware="true">
    ...
</service>

<provider
    android:name="com.google.firebase.provider.FirebaseInitProvider"
    android:exported="false"
    android:authorities="com.microsoft.skype.teams.dev.firebaseinitprovider"
    android:initOrder="100"
    android:directBootAware="true" />

```

#### Steps to reproduce:
We have been observing this app crash due to _IllegalStateException_ in Play Console:
![Screenshot 2024-06-19 at 11 30 42 AM](https://github.com/firebase/firebase-android-sdk/assets/84557759/9c3ea5d4-cdd8-4836-8cd3-d56aec21705e)
Issue is seen across all OS versions.
This crash majorly occurs on Oneplus and Huwaie devices more. (Samsung, RealMe also can be found though)
And we are unable to repro this issue locally.

Seems like this has been already reported [here](https://github.com/firebase/firebase-android-sdk/issues/4712) and closed without any fix from Firebase side. 
Hence requesting to provide some options to disable the direct boot aware attribute which is enabled by default for the Firebase components mentioned above or a fix which doesn't start our app on direct boot mode due to Firebase component launch.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by lehcar09** [comment]
Hi @gipartha, thanks you for reaching out. The issue you're experiencing is manufacturer/ OEM specific. Unfortunately, without being able to replicate the issue it will be difficult to conduct a deeper investigation.

For now, I suggest try adding the `tools:remove` the `android:directBootAware` from `ComponentDiscoveryService` in the merged manifest as suggested in [here](https://github.com/firebase/firebase-android-sdk/issues/4712#issuecomment-1489203834).

That said, I'll close this for now. If there are more developers that are encountering this issue and can share an MCVE then we can prioritize a deeper investigation and reopen this thread. Thank you!

**Comment by gipartha** [comment]
HI 
As I mentioned earlier it's occurring in all manufacturer devices.
Not sure why you need local repro for the issues which are getting reported in the play console.

May I know what you mean by MCVE? 
Also will you be able to get whether all app developers who use Firebase are facing this issue or not with some telemetry at your end?

The problem with `tools:remove` is code maintainability:
- Any change in the Firebase component package or attributes, we may need to identify and make same changes in our manifest 
- There are 3 components which we may need to override for this: 
   1. ComponentDiscoveryService
   2. FirebaseMessagingService
   3. FirebaseInitProvider
