### ISSUE TITLE
Update gRPC to 1.64.0

### ISSUE THREAD

**Issue by larssn** [firebase/firebase-android-sdk#6048]
Hello

The current version (1.57.2) is almost a year old, so I request an update to 1.64.0 (latest as of writing).

We're seeing what seemingly is gRPC specific errors recently (downstream in Flutter), so I'm hoping something has been fixed in the last year, regarding this. The error is: `[cloud_firestore/internal] Internal errors. Means some invariants expected by underlying system has been broken. If you see one of these errors, something is very broken.`

I've also created an issue over at java-firestore: https://github.com/googleapis/java-firestore/issues/1708

**Comment by lehcar09** [comment]
Hi @larssn, thank you for reaching out. I'll inform our engineers about this. In the meantime, you can actually specify the `grpc` dependency explicitly and it should override the version bundled in firestore.

Could you check if this resolves the issue you're experiencing?

    implementation 'io.grpc:grpc-android:1.64.0'
    implementation 'io.grpc:grpc-okhttp:1.64.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.64.0'
    implementation 'io.grpc:grpc-stub:1.64.0'

**Comment by larssn** [comment]
To prevent the bot from aggressively closing: Thanks for the workaround!

**Comment by tom-andersen** [comment]
Hi @larssn

Upgrading gRPC was held back due to Firebase support of older devices. Two months ago, we upped the min SDK version of Android to 21, which no makes upgrading gRPC possible.

I have created a PR to make this upgrade: https://github.com/firebase/firebase-android-sdk/pull/6062

**Comment by tom-andersen** [comment]
@larssn

We are a little hesitant to bring Firebase up to the bleeding edge of gRPC. Does the previous version 1.62.2 solve your problem as well?

**Comment by larssn** [comment]
Unknown, I've never seen a `[cloud_firestore/internal] Internal errors. Means some invariants expected by underlying system has been broken. If you see one of these errors, something is very broken.`-error myself. But there's a lot of them in our crashlytics.

If that's the highest you're willing to go, I completely understand. I just hope you will keep bumping it once in a while. 🙏🏻😊

**Comment by tom-andersen** [comment]
We upgraded to gRPC version 1.62.2 https://github.com/firebase/firebase-android-sdk/pull/6070

Please let us know if you continue to experience problems.
