### ISSUE TITLE
firebase get token authentication failed for new users

### ISSUE THREAD

**Issue by gkkzz** [firebase/firebase-android-sdk#6058]
firebase-annotations-16.2.0
firebase-messaging-23.2.0
firebase-common-20.3.1

[REQUIRED] Step 3: Describe the problem

not emulator

After registering FCM,FirebaseMessagingService onNewToken no call back ,so  I tried to go to get fcm token , but hint

Fetch FCM token failed: java.io.IOException: java.util.concurrent.ExecutionException: java
.io.IOException: AUTHENTICATION_FAILED

not a recurrent problem,We see that this issue happens only for new users, who is registering for the first time.

**Comment by gkkzz** [comment]
It can be solved after restarting this device , but it is not a good solution

So I want to know the reason

**Comment by lehcar09** [comment]
Hi @gkkzz, thank you for reaching out. Just wanted to clarify, you mentioned that, “After registering FCM, FirebaseMessagingService onNewToken no call back”, does this mean the user's existing token gets invalidated and is expecting a new registration token, but the `onNewToken` is not triggered?

The `IOException: AUTHENTICATION_FAILED` error message, usually means that the device does not have a valid registration (Android ID). Factory resetting the device causes the Android ID to be reset and it will try to register the new ID, so this may be why that fixed it in those cases.

**Comment by gkkzz** [comment]
IOException: AUTHENTICATION_FAILED
Does this error only reset if it happens to do a factory reset? After this happened, we didn't do a factory reset, we just restarted the device and it was restored

**Comment by gkkzz** [comment]
“After registering FCM, FirebaseMessagingService onNewToken no call back”
I mean
When I first registered, I understood that `onNewToken `would also have a callback and would tell me which token was successfully registered，I take this token to the Server

**Comment by lehcar09** [comment]
Thanks for the clarification @gkkzz. I tried reproducing the issue, however, I wasn't able to encounter the issue. The `onNewToken` was triggered accordingly. Could you share an MCVE to help us investigate the issue?

As for the IOException: AUTHENTICATION_FAILED, there was a similar issue https://github.com/firebase/firebase-android-sdk/issues/1286 reported before. Can you share the FirebaseInstallation version you're using?

Aside from that, Aside from that, are you constantly experiencing this error? Could you provide the steps to reproduce the issue? or does the issue occur on certain devices and/or android versions?
