### ISSUE TITLE
Analytics: Does resetAnalyticsData reset user ID and user properties?

### ISSUE THREAD

**Issue by gibachan** [firebase/firebase-android-sdk#6107]
According to the documentation for [resetAnalyticsData()](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#resetAnalyticsData()), it clears all analytics data for the app. However, it is not clear what exactly is included in "all analytics data." 

We would like to clarify if `resetAnalyticsData()` will also reset the user ID and user properties that were set using [setUserId](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setUserId(java.lang.String)) and [setUserProperty](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setUserProperty(java.lang.String,java.lang.String)).

Do we need to set `null` for both user ID and user properties after calling `resetAnalyticsData`? or will `resetAnalyticsData` handle resetting those properties as well?

**Comment by lehcar09** [comment]
Hi @gibachan, thank you for reaching out. [resetAnalyticsData()](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#resetAnalyticsData())API resets the user ID and user properties.

For context, Google Analytics uses the App Instance Id as the primary user identifier. App Instance ID is automatically generated and assigned to each instance of your app and is used to compute user metrics throughout Analytics. When you resetAnalyticsData API, it also resets the app instance id, thus, there won't be data associated with it. You can check this [documentation](https://support.google.com/analytics/answer/9019185?hl=en#delete-on-mobile-device&zippy=%2Cin-this-article) for reference.

I'll go ahead and close this issue now. Let me know I misunderstood anything and we need to re-open the issue for further investigation. Thanks!

**Comment by gibachan** [comment]
Thanks!
