### ISSUE TITLE
⭐ [Android] Support 16kb page size for Android 15+ devices

### ISSUE THREAD

**Issue by k-saparia** [firebase/firebase-android-sdk#6142]
### Description
I am encountering issues when running my app on Android 15 devices with a 16 KB page size, particularly with some native components. Are there any plans to recompile the library to address these issues and ensure compatibility with phones that have a 16 KB page size?

As stated on Android [doc](https://developer.android.com/guide/practices/page-sizes#compile-16-kb-alignment),

> Beginning with Android 15, Android supports devices that are configured to use a page size of 16 KB (16 KB devices). If your app uses any [NDK](https://developer.android.com/ndk) libraries, either directly or indirectly through an SDK, then you will need to rebuild your app for it to work on these 16 KB devices.

An analysis of my app using the APK Analyzer [as described by Android](https://developer.android.com/guide/practices/page-sizes#16-kb-impact) shows that it does use **libcrashlytics-common.so** as native code.
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/9917fbf1-b50c-4366-bdb1-a49234a5a2a2">
This is the native binary reported by the APK analysis:

libcrashlytics-common.so

### Describe the solution you'd like
I would like for **libcrashlytics-common** to support 16kb page size phones so that apps supporting sdk 35 do not crash
### Additional context
Android doc: https://developer.android.com/guide/practices/page-sizes#compile-16-kb-alignment
react-native thread: https://github.com/facebook/react-native/issues/45054
### What Platforms whould this feature/enhancement affect?
Android

### Alternatives/Workarounds
No workaround I have investigated so far.

**Comment by lehcar09** [comment]
Hi @k-saparia, thank you for reaching out. We have released an updated Crashlytics NDK [version 19.0.2](https://firebase.google.com/support/release-notes/android?hl=en#crashlytics-ndk_v19-0-2) last Jun 20, 2024 that supports 16Kb page sizes.

Could you share the version of Crashlytics that you're using?

**Comment by k-saparia** [comment]
I'm using firebase bom `implementation(platform("com.google.firebase:firebase-bom:32.7.2"))`

**Comment by lehcar09** [comment]
Thank you for the details @k-saparia. Yes, you will need to update to the Firebase version BOM 33.1.1 or latest. 

With that, I'll be closing this issue. If you encounter an issue, please file a new ticket with the details that can help us investigate the issue. Thanks!
