### ISSUE TITLE
DefaultFirebaseAppCheck.addAppCheckTokenListener app crashes.

### ISSUE THREAD

**Issue by siyoon123** [firebase/firebase-android-sdk#6160]
Environment
Unity Version: 2021.3.31f1
Firebase Component: AppCheck, Auth, Crashlytics, Database
Firebase Version: 11.9.0

Describe the problem
Since the Firebase 11.9.0 version update, I am experiencing abnormal ANR.

The app seems to terminate as soon as it runs, and the logs look like this
This only seems to happen on Android devices.

![IMG_3020](https://github.com/user-attachments/assets/53791e81-b8c8-4f5f-ac44-5a734bc9a205)
![IMG_3019](https://github.com/user-attachments/assets/e94d33e5-75d9-4190-ba31-55d6755a3a70)

**Comment by lehcar09** [comment]
Hi @siyoon123, thank you for reaching out. Could you answer a few questions below for us to further investigate this:

* Were you able to reproduce the issue? By any chance can you share an MCVE to help us investigate the issue. 
* Does this issue only occurring on the specific devices? or does it also occur on emulators of different versions?
* Is it possible to share the whole error message? 

In addition to that, is the Firebase version 11.9.0 refer to Firebase App Check? If so, were you able to check if the issue persists with the latest version. Currently, Firebase App Check is in version 18.0.0 ([release notes](https://firebase.google.com/support/release-notes/android#latest_sdk_versions)).

**Comment by siyoon123** [comment]
Hi @lehcar09, 

Unfortunately, this ANR is not reproducible in our test cases and seems to occur irregularly for deployed users only.
This issue occurs on almost all devices, Android versions, and there is no specific version.
As mentioned earlier, it's hard to give you an error message because it's not reproduced in the test case.

**Comment by lehcar09** [comment]
Hey @siyoon123, pardon me, I just noticed that you're using Firebase Unity SDK. To get better help, I suggest filing the issue in the [Firebase Unit SDK](https://github.com/firebase/firebase-unity-sdk/issues). The Firebase Android SDK repository handles issues related to native Android. Thanks!
