### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'FirebaseCppApp-12_1_0'

### ISSUE THREAD

**Issue by ClairePeta-36** [firebase/firebase-android-sdk#6170]
### Describe your environment

  * Android Studio version: 12.1.0
  * Firebase Component: Analytics, Crashlytics, Messaging, Remote Config
  * Component version: 12.1.0
  * Unity version: 2022.3.35f1
  * installation method: .unitypackage
  * platform: android
  * unity editor platform: windows
  * scripting runtime: IL2CPP
  * gradle version: 7.2
  * android gradle plug-in version: 7.1.2+
  * min/target api: 23/34

### Describe the problem

`Exception: System.TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE.SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'FirebaseCppApp-12_0_0'. Tried the load the following dynamic libraries: Unable to load dynamic library 'FirebaseCppApp-12_0_0' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "FirebaseCppApp-12_0_0" not found`

`DllNotFoundException: Unable to load DLL 'FirebaseCppApp-12_0_0'. Tried the load the following dynamic libraries: Unable to load dynamic library 'FirebaseCppApp-12_0_0' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "FirebaseCppApp-12_0_0" not found`

#### Steps to reproduce:

We are in the process of updating out app to unity 2022.3.35f1
We updated our firebase version from 9.1.0 to 12.1.0. while the build succeeds, on arriving to the home screen we get the above errors. We have done some research into others who have faced this problem however none of their fixes have worked for us

#### Attempted Resolutions:

- higher min sdk version (23 > 24)
- Force resolving using EDM
- Tried removing firebase/EDM and reinstalling
- Tried removing firebase and install using the .tgz/package manager method
- Tried updating EDM to the newest version
- Tried relocating the FirebaseCppApp-12_1_0 files
- Tried enabling 'any platform' for all FirebaseCppApp-12_1_0 files
- Update Microsoft Visual C++ 2015-2022 Redistributable to the latest version
- Updating Gradle to 8.0+
- Updating NDK (not sure this valid)
- Fresh unity install
- Rolling back Firebase to Unity 12.0

**Comment by lehcar09** [comment]
Hi @ClairePeta-36, thank you for reaching out. The Firebase Android SDK repository handles issues related to native Android . To get better help, I suggest filing the issue in the [Firebase Unit SDK](https://github.com/firebase/firebase-unity-sdk/issues). Thanks!
