### ISSUE TITLE
 duplicate logEvents & logEvent 's parameter value inside debugView

### ISSUE THREAD

**Issue by mss-mukesh** [firebase/firebase-android-sdk#6171]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by mss-mukesh** [comment]
![Screenshot 2024-08-12 at 12 56 38 PM](https://github.com/user-attachments/assets/74860877-9c21-4c54-95e1-1203b91d16ac)
I have added screenshot. Only subscription events show in two times and also parameter values of two times.
Please help on this issue.

**Comment by lehcar09** [comment]
Hi @mss-mukesh, thank you for reaching out. I tried reproducing the issue, however, I wasn't able to encounter the behavior you raised. Does the event log twice in the verbose log too? By any chance, can you share the verbose log without the PIIs?

Can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android) and see if you can reproduce the issue? Thanks!
