### ISSUE TITLE
<!DOCTYPE html>

### ISSUE THREAD

**Issue by Dayzer20** [firebase/firebase-android-sdk#6190]
<!DOCTYPE html>
<html><body><h1>Size Report <sup><a href="#ptSWsqGsJq">1</a></sup></h1><h3>Affected Products</h3><ul><li><h4><code>firebase-abt</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">12.4 kB</td><td align="center">12.4 kB</td><td align="center">+2 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-appcheck</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">39.2 kB</td><td align="center">39.2 kB</td><td align="center">+5 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-appcheck-debug</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">9.34 kB</td><td align="center">9.34 kB</td><td align="center">-1 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-appcheck-debug-testing</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">5.38 kB</td><td align="center">5.39 kB</td><td align="center">+5 B (+0.1%)</td></tr></tbody></table></li><li><h4><code>firebase-appcheck-playintegrity</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">9.12 kB</td><td align="center">9.12 kB</td><td align="center">-1 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-appdistribution</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">230 kB</td><td align="center">230 kB</td><td align="center">-6 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-appdistribution-api</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">18.9 kB</td><td align="center">18.9 kB</td><td align="center">+2 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-config</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">108 kB</td><td align="center">108 kB</td><td align="center">+12 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-crashlytics</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">409 kB</td><td align="center">409 kB</td><td align="center">+3 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-crashlytics-ndk</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">1.65 MB</td><td align="center">1.65 MB</td><td align="center">-1 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-database</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">543 kB</td><td align="center">543 kB</td><td align="center">-2 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-datatransport</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">4.28 kB</td><td align="center">4.28 kB</td><td align="center">+1 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-dynamic-links</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">61.7 kB</td><td align="center">61.7 kB</td><td align="center">-2 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-firestore</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">1.43 MB</td><td align="center">1.43 MB</td><td align="center">-3 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-functions</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">50.1 kB</td><td align="center">50.1 kB</td><td align="center">-3 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-inappmessaging</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">460 kB</td><td align="center">460 kB</td><td align="center">-2 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-inappmessaging-display</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">163 kB</td><td align="center">163 kB</td><td align="center">+7 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-installations</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">57.7 kB</td><td align="center">57.7 kB</td><td align="center">-1 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-messaging</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">148 kB</td><td align="center">148 kB</td><td align="center">-1 B (-0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-sessions</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">167 kB</td><td align="center">167 kB</td><td align="center">+1 B (+0.0%)</td></tr></tbody></table></li><li><h4><code>firebase-storage</code></h4><table><thead><tr><th align="center">Type</th><th align="center">Base (743f2eb)</th><th align="center">Merge (26fefff)</th><th align="center">Diff</th></tr></thead><tbody><tr><td align="left">aar</td><td align="center">134 kB</td><td align="center">134 kB</td><td align="center">-6 B (-0.0%)</td></tr></tbody></table></li></ul><h3>Test Logs</h3><ul><li>Base (743f2eb): <a href="https://github.com/firebase/firebase-android-sdk/actions/runs/8930984914">https://github.com/firebase/firebase-android-sdk/actions/runs/8930984914</a></li><li>Merge (26fefff): <a href="https://github.com/firebase/firebase-android-sdk/actions/runs/8931561016">https://github.com/firebase/firebase-android-sdk/actions/runs/8931561016</a></li></ul><h1></h1><footer><ol><li id="ptSWsqGsJq"><a href="https://storage.googleapis.com/firebase-sdk-metric-reports/ptSWsqGsJq.html">https://storage.googleapis.com/firebase-sdk-metric-reports/ptSWsqGsJq.html</a></li></ol></footer></body></html>

_Originally posted by @google-oss-bot in https://github.com/firebase/firebase-android-sdk/issues/5923#issuecomment-2091432246_

**Comment by lehcar09** [comment]
Hi @Dayzer20 , thank you for reaching out. In order for us to help you, please file a new issue thread with the complete details regarding the specific security bug and issue that you're referring to so that we may assist you properly. Thanks!
