### ISSUE TITLE
Remove auto-value-annotation dependency from firebase-common

### ISSUE THREAD

**Issue by samtstern** [firebase/firebase-android-sdk#625]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: any
  * Firebase Component: common
  * Component version: 18.0.0.

#### Steps to reproduce:

If you look at https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-common/18.0.0/firebase-common-18.0.0.pom

You can see this dependency:
```
    <dependency>
      <groupId>com.google.auto.value</groupId>
      <artifactId>auto-value-annotations</artifactId>
      <version>1.6.3</version>
      <scope>compile</scope>
      <type>jar</type>
    </dependency>
```

This adds a new dependency (a 5kB JAR so not a big one) to every app that uses Firebase:
https://mvnrepository.com/artifact/com.google.auto.value/auto-value-annotations/1.6.3'

I believe it also causes issues with apps that are using auto-value at a different version than we are:
https://github.com/google/auto/issues/620

We only use this dependency inside `common` in one place:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-common/src/main/java/com/google/firebase/platforminfo/LibraryVersion.java

We would probably be better off just hand-writing the value class and dropping the dep.

#### Relevant Code:

N/A

**Comment by vkryachko** [comment]
Fixed by #1472
