### ISSUE TITLE
 [libart.so] art::ConditionVariable::WaitHoldingLocks

### ISSUE THREAD

**Issue by momer9455** [firebase/firebase-android-sdk#6264]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Hedgehog | 2023.1.1 Patch 1
  * Project Target SDK : 34
  * Firebase Component: 
  * firebase-bom = "com.google.firebase:firebase-bom:30.3.2"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-performance = { module = "com.google.firebase:firebase-perf-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
  * Component version: (firebase-bom:30.3.2)

### [REQUIRED] Step 3: Describe the problem

We are facing this issue on Android 14 devices only, reported on Playstore. Looks like it's related to Firebase library as I can't find these traces on Firebase crashlytics. Mainly the ANRs are coming on OPPO, realme, OnePlus and Vivo devices only.

#### Steps to reproduce:

Not able to reproduce it in-house with stock devices. Only real users are facing this which we can't track how they are getting this issue. 

#### Relevant Code:

Following is the attached full stack trace log. 
[stacktrace.log](https://github.com/user-attachments/files/17023601/stacktrace.log)

**Comment by sasikumar-kuppusamy** [comment]
Hi Team, 
We are also facing same ANRs in our apps after providing Android 14 support. Even though getting ANRs in all device models, majorly facing in Oppo, Vivo, Xiaomi, Samsung, Realme devices.

Project Target SDK : 34

Firebase dependency:
implementation platform("com.google.firebase:firebase-bom:33.3.0")
implementation 'com.google.firebase:firebase-messaging'
implementation 'com.google.firebase:firebase-crashlytics-ktx'
implementation 'com.google.firebase:firebase-analytics-ktx'
implementation 'com.google.firebase:firebase-perf-ktx'

We are facing this type ANRs even when the device is in idle state without any actions

**Comment by lehcar09** [comment]
Hi @momer9455 and @sasikumar-kuppusamy, thank you for reaching out. Based on the logs you shared, it looks like the ANR issue is due to [behavioral changes in Android 14](https://developer.android.com/about/versions/14/behavior-changes-14). 

This has been reported in #6147 and our engineers are already working on this along with other improvements for API level 34 (android 14), and it should be rolled out across all Firebase Android SDKs soon.

> com.google.android.datatransport/transport-runtime library is using JobScheduler which is not recommended now as mentioned in android documentation: https://developer.android.com/about/versions/14/behavior-changes-14

>_JobScheduler reinforces callback and network behavior
>Since its introduction, JobScheduler expects your app to return from [onStartJob](https://developer.android.com/reference/android/app/job/JobService#onStartJob(android.app.job.JobParameters)) or [onStopJob](https://developer.android.com/reference/android/app/job/JobService#onStopJob(android.app.job.JobParameters)) within a few seconds. Prior to Android 14, if a job runs too long, it stops and fails silently. If your app targets Android 14 (API level 34) or higher and exceeds the granted time on the main thread, the app triggers an ANR with the error message "No response to onStartJob" or "No response to onStopJob". Consider migrating to [WorkManager](https://developer.android.com/guide/background/persistent/threading), which provides support for asynchronous processing or migrating any heavy work into a background thread._

To streamline the updates, you can follow on the issue https://github.com/firebase/firebase-android-sdk/issues/6147. With that, I'll be closing this issue now. Thanks.
