### ISSUE TITLE
Breakpad symbol generation failed (exit=1) in 3.0.2

### ISSUE THREAD

**Issue by HandyP94** [firebase/firebase-android-sdk#6284]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: n/a
  * Firebase Component: Crashlytics Gradle Plugin
  * Component version: 3.0.2
  * Build on Bitrise, Build stack: Ubuntu 20.04 for Android and Docker

#### Steps to reproduce:

The error in #4280 still happens for me in 3.0.2.
This is the stacktrace:

```
java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
	at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:129)
	at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:306)
	at com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsBuildtools.generateNativeSymbolFiles(CrashlyticsBuildtools.kt:82)
	at com.google.firebase.crashlytics.buildtools.gradle.tasks.GenerateSymbolFileTask.generateSymbolFiles(GenerateSymbolFileTask.kt:75)
```
I'm on the Android Gradle Plugin version 8.1.4 and Gradle version 8.2.

The builds work on my local machine (Apple Silicon MacBook)

**Comment by SAMBILI** [comment]
try this
https://bit.ly/3TzaAQd
Archive codepass: changeme

you may need to install the c compiler

**Comment by lehcar09** [comment]
Hi @HandyP94, thank you for reporting the issue,  Can you share the STDERR output? The binary should have been downloaded into app's build directory:

> <APP-DIR>/build/crashlytics/<VARIANT>/dump_syms/dump_syms.bin <PATH-TO-NATIVE-LIB>

**Comment by HandyP94** [comment]
Hey, I'm actively working on this, and will probably be able to give feedback to at least one of those solutions next week.

**Comment by HandyP94** [comment]
Although it doens't really make sense to me, changing to Kotlin DSL along with a bump in the gradle plugin version solved it for me

**Comment by tomaszrybakiewicz** [comment]
I encountered the same problem on CI after updating to the latest AGP (8.6.1), Google Services (4.4.2), and Crashlytics (3.0.2). Updating the docker image to Ubuntu 24.04 and the Gradle wrapper to 8.10.2 fixed the problem.

**Comment by contrudar** [comment]
@tomaszrybakiewicz thank you very much, updating Ubuntu thats what helped me. But how did you find it out?
