### ISSUE TITLE
[Storage] java.lang.OutOfMemoryError after repeated use of putData()/putFile()

### ISSUE THREAD

**Issue by CloudMountain** [firebase/firebase-android-sdk#6310]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 

> Android Studio Hedgehog | 2023.1.1 Patch 2
> Build #AI-231.9392.1.2311.11330709, built on January 18, 2024
> Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 aarch64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 14.4.1
> GC: G1 Young Generation, G1 Old Generation
> Memory: 2048M
> Cores: 8
> Metal Rendering is ON
> Registry:
>     external.system.auto.import.disabled=true
>     debugger.watches.in.variables=false
>     ide.text.editor.with.preview.show.floating.toolbar=false
> 
> Non-Bundled Plugins:
>     Dart (231.9411)
>     io.flutter (77.2.1)

  * Firebase Component: 
Storage

  * Component version: 
21.0.0 (I am using the flutter firebase_core plugin version 3.3.0 which uses firebase-bom version 33.1.0)

### [REQUIRED] Step 3: Describe the problem

I originally posted about a problem I was having in the flutterfire repo here: https://github.com/firebase/flutterfire/issues/13385, and was told this was an problem with the native sdk and to raise a new issue here. Apologies in advance as I have limited experience in writing native code, and so can only really present the issue using Flutter terminology.

As can be seen in the original issue, the problem I am having is that I am trying to upload byte buffers of ~5MB on the order of a few hundred times during the course of a user session. Some users are experiencing OOM crashes of the following form: `Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 2576 byte allocation with 1020864 free bytes and 996KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.`

After doing some memory profiling with Android Studio, I was able to narrow down the issue to calls of the `ref().putData()`and/or `ref().putFile()`functions from the firebase_storage flutter plugin. 

#### Steps to reproduce:

Make a button in a flutter app which simply creates a Uint8List of length 5,000,000 and then uploads it using either `putData()` or `putFile()`. Recording Java/Kotlin allocations whilst tapping that button shows the following byte buffers are allocated and then never deallocated:
![Screenshot 2024-09-23 at 16 11 54](https://github.com/user-attachments/assets/b9f9c4a5-2bf9-4e91-b475-c67440ef045b)
![Screenshot 2024-09-23 at 16 12 19](https://github.com/user-attachments/assets/8371e6d9-6a0d-43fe-8dae-a002b519f191)

#### Relevant Code:

```
Uint8List buffer = Uint8List(5000000);
Reference ref =  FirebaseStorage.instance.ref();
UploadTask? uploadTask = await ref.child(path/to/file.pcm).putData(buffer);
```

**Comment by lehcar09** [comment]
Hi @CloudMountain, thank you for reaching out. The Firebase Storage `putBytes()` or `putData()` (in Flutter) and `putFile()` are asynchronous methods. It returns a `Task`object that you can use to monitor the upload progress and handle its completion or failure.

Calling multiple `putBytes` methods in Firebase Storage without proper management can potentially lead to Out-of-Memory (OOM) exceptions, especially on devices with limited RAM. 

Are you calling the `putBytes()` concurrently? If there are 50 concurrent calls with 5MB file size to upload, it's possible that the memory allocation used for this operation is more than the memory available on your device

I tried reproducing the issue and I was able to encounter the OOM exception on the 32nd concurrent call. Is there any chance you can share a bit more code snippet on how you did the “upload byte buffers of ~5MB on the order of a few hundred times during the course of a user session”? Thanks!

**Comment by avishayw** [comment]
This crash reproduced for me as well.

System:
> Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 months ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

Device specifications:
> Processor	12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
Installed RAM	16.0 GB (15.6 GB usable)
System type	64-bit operating system, x64-based processor

Windows specifications
> Edition	Windows 11 Home
Version	23H2
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0


Packages:
> firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+3

## Steps to reproduce
1. Have some file to upload (mine is a few KBs in size)
2. Upload at a rate of once per second, but only if not uploading already:
```dart
Future<void> _uploadLogsToStorage() async {
    if (_uploading) {
      return;
    }
    // List logs in path
    final logsDir = await _getLogsDir();
    try {
      List<String> logs = path_utils.listFilesInDir(logsDir);
      if (logs.isNotEmpty) {
        final storageRef = MsGlobals().storage.ref();
        for (String log in logs) {
          // Verify again that not uploading already due to the loop
          if (_uploading) {
            break;
          }
          _uploading = true;
          final filename = path.basename(log);
          Reference logRef =
              storageRef.child('logs/${MsGlobals().userUuid}/$filename');
          final byteData = await File(log).readAsBytes();
          logRef
              .putData(byteData, SettableMetadata(contentType: 'text/plain'))
              .snapshotEvents
              .listen((taskSnapshot) async {
            switch (taskSnapshot.state) {
              case TaskState.running:
                break;
              case TaskState.paused:
                break;
              case TaskState.success:
                // Check if log is older than 2 hours
                final String dateString = filename.split('.')[0];
                final DateTime logDateTime = parseFormattedDateTime(dateString);
                if (DateTime.now()
                    .toUtc()
                    .isAfter(logDateTime.add(const Duration(hours: 2)))) {
                  await path_utils.deleteFile(path: log);
                }
                _uploading = false;
                break;
              case TaskState.canceled:
                _uploading = false;
                break;
              case TaskState.error:
                _uploading = false;
                break;
            }
          });
        }
      } else {
        _uploading = false;
      }
    } catch (e) {
      debugPrint(e.toString());
      _uploading = false;
    }
  }
```

## Steps to reproduce **FASTER**
Just increase the size of the file to upload:
```dart
Future<void> _uploadLogsToStorage() async {
    if (_uploading) {
      return;
    }
    // List logs in path
    final logsDir = await _getLogsDir();
    try {
      List<String> logs = path_utils.listFilesInDir(logsDir);
      if (logs.isNotEmpty) {
        final storageRef = MsGlobals().storage.ref();
        for (String log in logs) {
          // Verify again that not uploading already due to the loop
          if (_uploading) {
            break;
          }
          _uploading = true;
          final filename = path.basename(log);
          Reference logRef =
              storageRef.child('logs/${MsGlobals().userUuid}/$filename');
          Uint8List byteData = await File(log).readAsBytes();
		  if (const String.fromEnvironment('MEMORY_TEST',
                  defaultValue: 'false') ==
              'true') {
            /// Because there is OutOfMemory crash after about an hour or two,
            /// I want to make the app crash quicker by multiplying the byte
            /// data, and uploading to a separate folder in bucket.
            logRef = storageRef.child(
                'logs/${MsGlobals().userUuid}-MEMORY_TEST-$_sessionTime/$filename');
            const byteDataMultiplier = 1000;
            final repeatedBytes =
                List.generate(byteDataMultiplier, (_) => byteData)
                    .expand((e) => e)
                    .toList();
            byteData = Uint8List.fromList(repeatedBytes);
          }
          logRef
              .putData(byteData, SettableMetadata(contentType: 'text/plain'))
              .snapshotEvents
              .listen((taskSnapshot) async {
            switch (taskSnapshot.state) {
              case TaskState.running:
                break;
              case TaskState.paused:
                break;
              case TaskState.success:
                // Check if log is older than 2 hours
                final String dateString = filename.split('.')[0];
                final DateTime logDateTime = parseFormattedDateTime(dateString);
                if (DateTime.now()
                    .toUtc()
                    .isAfter(logDateTime.add(const Duration(hours: 2)))) {
                  await path_utils.deleteFile(path: log);
                }
                _uploading = false;
                break;
              case TaskState.canceled:
                _uploading = false;
                break;
              case TaskState.error:
                _uploading = false;
                break;
            }
          });
        }
      } else {
        _uploading = false;
      }
    } catch (e) {
      debugPrint(e.toString());
      _uploading = false;
    }
  }
```

## Additional information
From MemoryView, it can be seen that RSS is constantly increasing, while Dart/Flutter VM & Native stay pretty consistent and managed to be cleaned by garabage collector:
<img width="445" alt="Pasted image 20241007162737" src="https://github.com/user-attachments/assets/1012379e-da8d-4393-8535-3ce60ace878f">
![Pasted image 20241007124313](https://github.com/user-attachments/assets/f55bbf95-7673-4a02-8d90-e6248680bab0)



Help please. I'm out of ideas on how to debug this.

Thanks in advance, let me know if additional details are needed.
