### ISSUE TITLE
Crash on app launch at com.google.firebase.sessions.SessionLifecycleService$MessageHandler.maybeSendSessionToClient 

### ISSUE THREAD

**Issue by xxrlzzz** [firebase/firebase-android-sdk#6323]
Android version: 14,13,12,11,10...
Firebase version:
firebase-crashlytics:19.0.1
firebase-analytics:22.0.1

Steps to reproduce:
app crash after init firebase sdk

Relevant Code:
Exception java.lang.IllegalStateException:
  at com.google.firebase.FirebaseApp.getInstance (FirebaseApp.java:179)
  at com.google.firebase.FirebaseKt.getApp (Firebase.kt:42)
  at com.google.firebase.sessions.SessionDatastore$Companion.getInstance (SessionDatastore.kt:56)
  at com.google.firebase.sessions.SessionLifecycleService$MessageHandler.maybeSendSessionToClient (SessionLifecycleService.kt:153)
  at com.google.firebase.sessions.SessionLifecycleService$MessageHandler.handleClientBound (SessionLifecycleService.kt:124)
  at com.google.firebase.sessions.SessionLifecycleService$MessageHandler.handleMessage (SessionLifecycleService.kt:82)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at android.os.HandlerThread.run (HandlerThread.java:67)

After upgrade our firebase sdk, crash start. We notice that introduce from `firebase-sessions`, it require Firebase.app finish initialization during sdk init, which cause a potential circular dependencies. Plz check this crash as soon as possible.

https://github.com/firebase/firebase-android-sdk/blob/e98a4b630e8d477935b530d8ed3d9e43dbb05635/firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt#L148
```
    private fun maybeSendSessionToClient(client: Messenger) {
      if (hasForegrounded) {
        sendSessionToClient(client, SessionGenerator.instance.currentSession.sessionId)
      } else {
        // Send the value from the datastore before the first foregrounding it exists
        val storedSession = SessionDatastore.instance.getCurrentSessionId()
        Log.d(TAG, "App has not yet foregrounded. Using previously stored session: $storedSession")
        storedSession?.let { sendSessionToClient(client, it) }
      }
    }
```

```
  companion object {
    val instance: SessionDatastore
      get() = Firebase.app[SessionDatastore::class.java]
  }
// firebase-common/src/main/java/com/google/firebase/Firebase.kt
val Firebase.app: FirebaseApp
  get() = FirebaseApp.getInstance()

```

**Comment by lehcar09** [comment]
Hi @xxrlzzz, thank you for reaching out. I tried reproducing the issue, however, I did not encounter the issue. 

By any chance, can you share an MCVE to help is investigate the issue? In addition to that, can you try using the latest Firebase SDK version ([v33.3.0](https://firebase.google.com/support/release-notes/android#bom_v33-3-0)) and see if the issue persists?

**Comment by lehcar09** [comment]
Thank you for that additional information. I'm still having trouble in reproducing the issue. Pardon me, but, could you share an MCVE? That will help us a lot to investigate the issue. If it's too much work, you can use our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and work from there until you replicate the issue.
