### ISSUE TITLE
protobuf-javalite version 3.21.11 contains a high-severity CVE

### ISSUE THREAD

**Issue by michal-murin** [firebase/firebase-android-sdk#6336]
### Environment
  * Android Studio version: Android Studio Koala Feature Drop | 2024.1.2 Patch 1
  * Firebase Component: Performance
  * Component version: 21.0.1

### [REQUIRED] Step 3: Describe the problem
This is not a bug per-se I wasn't sure about reporting the vulnerability the suggested way as it wouldn't meet the requirements.

There's a quite new high-severity CVE concerning the `protobuf` libs - https://github.com/advisories/GHSA-735f-pc8j-v9w8.
While there are `protobuf` versions which have this fixed I can't see any issue/PR for updating the `protobuf-javalite` version in this Firebase project.

I specified the Performance component because for us it was reported in this component, but the vulnerable version of `protobuf-javalite 3.21.11` is used for the whole project.

#### Steps to reproduce:
N/A

#### Relevant Code:
In the version file `gradle/libs.versions.toml`:
```
javalite = "3.21.11"
```

**Comment by rlazo** [comment]
Hi @michal-murin! we are working on updating our dependencies. We'll keep this up to date as we make progress. Thanks
