### ISSUE TITLE
Crash report not uploading after updating firebase crashlytics to 19.2.0 and bom to 33.4.0

### ISSUE THREAD

**Issue by Dudi111** [firebase/firebase-android-sdk#6363]
Not able to upload Crash report after updating firebase crashlytics to 19.2.0 and bom to 33.4.0. Working fine in firebase crashlytics version 19.1.0 and bom version 33.3.0

**Comment by Dudi111** [comment]
Hi @lehcar09, I have crashed application 3 times but did not find any log stating :"Crashlytics report upload complete"
Logs are only getting printed at time of firebase initialization and on crash no logs getting printed. Below are the logs details:

10-11 11:17:52.954  2899  3038 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:18:54.476  3319  3319 I FirebaseCrashlytics: Initializing Firebase Crashlytics 19.2.0 for quipment.qristal.qds
10-11 11:18:54.483  3319  3319 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:18:54.489  3319  3349 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:18:54.489  3319  3319 D FirebaseCrashlytics: Could not find resources: 0 0 0
10-11 11:18:54.489  3319  3319 D FirebaseCrashlytics: Mapping file ID is: 00000000000000000000000000000000
10-11 11:18:54.493  3319  3319 D FirebaseCrashlytics: Checking for cached settings...
10-11 11:18:54.500  3319  3319 D FirebaseCrashlytics: Loaded cached settings: {"settings_version":3,"cache_duration":176961,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false,"collect_anrs":true,"collect_metric_kit":false,"collect_build_ids":true},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"63e5f71c3bfaf198dad2f8de","bundle_id":"quipment.qristal.qds"},"on_demand_upload_rate_per_minute":10,"on_demand_backoff_base":1.2,"on_demand_backoff_step_duration_seconds":60,"app_quality":{"sessions_enabled":true,"sampling_rate":1,"session_timeout_seconds":1800},"expires_at":1728728451293}
10-11 11:18:54.530  3319  3319 D FirebaseCrashlytics: Successfully configured exception handler.
10-11 11:18:54.531  3319  3319 D FirebaseCrashlytics: Initializing Crashlytics blocked main for 56 ms
10-11 11:18:54.531  3319  3345 D FirebaseCrashlytics: Opening a new session with ID 6708BC4601F600010CF7A8A731F5308B
10-11 11:18:54.532  3319  3345 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:18:54.570  3319  3349 D FirebaseCrashlytics: Could not register handler for breadcrumbs events.
10-11 11:18:54.570  3319  3349 I FirebaseCrashlytics: No version control information found
10-11 11:18:54.581  3319  3349 D FirebaseCrashlytics: Loaded userId 861380061727487 for session 6708BC08012B00010B5368358864C368
10-11 11:18:55.079  3319  3346 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:19:56.595  3505  3505 I FirebaseCrashlytics: Initializing Firebase Crashlytics 19.2.0 for quipment.qristal.qds
10-11 11:19:56.602  3505  3505 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:19:56.607  3505  3536 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:19:56.607  3505  3505 D FirebaseCrashlytics: Could not find resources: 0 0 0
10-11 11:19:56.608  3505  3505 D FirebaseCrashlytics: Mapping file ID is: 00000000000000000000000000000000
10-11 11:19:56.611  3505  3505 D FirebaseCrashlytics: Checking for cached settings...
10-11 11:19:56.619  3505  3505 D FirebaseCrashlytics: Loaded cached settings: {"settings_version":3,"cache_duration":176961,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false,"collect_anrs":true,"collect_metric_kit":false,"collect_build_ids":true},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"63e5f71c3bfaf198dad2f8de","bundle_id":"quipment.qristal.qds"},"on_demand_upload_rate_per_minute":10,"on_demand_backoff_base":1.2,"on_demand_backoff_step_duration_seconds":60,"app_quality":{"sessions_enabled":true,"sampling_rate":1,"session_timeout_seconds":1800},"expires_at":1728728451293}
10-11 11:19:56.647  3505  3505 D FirebaseCrashlytics: Successfully configured exception handler.
10-11 11:19:56.647  3505  3505 D FirebaseCrashlytics: Initializing Crashlytics blocked main for 54 ms
10-11 11:19:56.648  3505  3532 D FirebaseCrashlytics: Opening a new session with ID 6708BC84026C00010DB1C69070181034
10-11 11:19:56.651  3505  3532 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:19:56.678  3505  3532 D FirebaseCrashlytics: Could not register handler for breadcrumbs events.
10-11 11:19:56.678  3505  3532 I FirebaseCrashlytics: No version control information found
10-11 11:19:56.693  3505  3532 D FirebaseCrashlytics: Loaded userId 861380061727487 for session 6708BC4601F600010CF7A8A731F5308B
10-11 11:19:57.189  3505  3533 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:20:58.694  3901  3901 I FirebaseCrashlytics: Initializing Firebase Crashlytics 19.2.0 for quipment.qristal.qds
10-11 11:20:58.701  3901  3901 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:20:58.706  3901  3978 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:20:58.706  3901  3901 D FirebaseCrashlytics: Could not find resources: 0 0 0
10-11 11:20:58.706  3901  3901 D FirebaseCrashlytics: Mapping file ID is: 00000000000000000000000000000000
10-11 11:20:58.710  3901  3901 D FirebaseCrashlytics: Checking for cached settings...
10-11 11:20:58.717  3901  3901 D FirebaseCrashlytics: Loaded cached settings: {"settings_version":3,"cache_duration":176961,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false,"collect_anrs":true,"collect_metric_kit":false,"collect_build_ids":true},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"63e5f71c3bfaf198dad2f8de","bundle_id":"quipment.qristal.qds"},"on_demand_upload_rate_per_minute":10,"on_demand_backoff_base":1.2,"on_demand_backoff_step_duration_seconds":60,"app_quality":{"sessions_enabled":true,"sampling_rate":1,"session_timeout_seconds":1800},"expires_at":1728728451293}
10-11 11:20:58.745  3901  3901 D FirebaseCrashlytics: Successfully configured exception handler.
10-11 11:20:58.745  3901  3901 D FirebaseCrashlytics: Initializing Crashlytics blocked main for 53 ms
10-11 11:20:58.745  3901  3971 D FirebaseCrashlytics: Opening a new session with ID 6708BCC202CE00010F3D608876CC080E
10-11 11:20:58.750  3901  3971 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.
10-11 11:20:58.770  3901  3972 D FirebaseCrashlytics: Could not register handler for breadcrumbs events.
10-11 11:20:58.770  3901  3972 I FirebaseCrashlytics: No version control information found
10-11 11:20:58.778  3901  3972 D FirebaseCrashlytics: Loaded userId 861380061727487 for session 6708BC84026C00010DB1C69070181034
10-11 11:20:59.297  3901  3971 D FirebaseCrashlytics: Crashlytics automatic data collection ENABLED by API.

**Comment by lehcar09** [comment]
Thank you for sharing the logs @Dudi111. I tried running on similar API version 32, 33, and 34 but still unable to reproduce the issue. The crash reports was uploaded. Below are the dependencies I used.

app/build.gradle.kts
```
dependencies {
   ...
   implementation("com.google.firebase:firebase-crashlytics:19.2.0")
   ...
}
```

build.gradle.kts
```
plugins {
    id("com.android.application") version "8.7.0" apply false
    id("com.android.library") version "8.7.0" apply false
    id("org.jetbrains.kotlin.android") version "2.0.20" apply false
    id("com.google.gms.google-services") version "4.4.2" apply false
    id("com.google.firebase.crashlytics") version "3.0.2" apply false
}
```

By any chance, can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?

**Comment by Dudi111** [comment]
Hello @lehcar09, Let me share MCVE for this. My application is just a foreground service with no UI. 
In my application class onCreate method i have initialised firebase as below:
FirebaseApp.initializeApp(this)
Firebase.crashlytics.setCustomKey("Key", boolean value)    //can not provide key and values details
Firebase.crashlytics.setCustomKey("Key", boolean value)    //can not provide key and values details
Firebase.crashlytics.setUserId(My number)                           //can not provide my number details
 FirebaseDatabase.getInstance().setPersistenceEnabled(false)
 
 In my foreground service, I am crashing app using below code:
         CoroutineScope(Dispatchers.IO).launch {
            delay(60000)
            throw IllegalStateException("Test error2")    //This is of type java. lang. IllegalStateException
        }
I am receiving uncaught exception in below var :
var unCaughtExceptionHandler =
        Thread.UncaughtExceptionHandler { _, ex ->
            Firebase.crashlytics.recordException(ex)
            restartService()
        }
Below are my plugin info.:
plugins {
    id("com.android.application") version "8.7.0" apply false
    id("org.jetbrains.kotlin.android") version "2.0.20" apply false
    id("com.google.gms.google-services") version "4.4.2" apply false
    id("com.google.firebase.crashlytics") version "3.0.2" apply false
}
app/build.gradle
dependencies {
 implementation("com.google.firebase:firebase-auth-ktx:23.0.0")
 implementation("com.google.firebase:firebase-common-ktx:21.0.0")
   implementation("com.google.firebase:firebase-crashlytics:19.2.0")
}

In my application if i user firebase crashlytics v19.1.0 it is working fine but not with v19.2.0. Apart from crashlytics i am using storage, realtime database and those things are working as per expected.
NOTE: For dependency i am using lib.versions.toml file and my application is a system app

**Comment by lehcar09** [comment]
I have created an [MCVE](https://github.com/lehcar09/Issue6363) while trying to reproduce the issue. Could you check and update the related files to replicate the issue? Thanks!

**Comment by Dudi111** [comment]
Hi @lehcar09 I have updated code to reproduce issue but i am not able to push code to this repository : https://github.com/lehcar09/Issue6363
Please provide necessary permission so that i can push the code.

**Comment by lehcar09** [comment]
I've added you as the collaborator in the MCVE. Let me know if you encounter another blocker.

**Comment by Dudi111** [comment]
Hi @lehcar09 Still getting below issue while pushing code:
User cancelled dialog. remote: Permission to lehcar09/Issue6363.git denied to Dudi111. unable to access 'https://github.com/lehcar09/Issue6363.git/': The requested URL returned error: 403

**Comment by Dudi111** [comment]
Hello @lehcar09 @argzdev Any update on this???

**Comment by Tomoshi3104** [comment]
@Dudi111 
I don't know if this is the same case as mine, but my issue has been resolved when I tried exactly as the site below suggests.
[https://stackoverflow.com/questions/78469914/firebasecrashlytics-no-userid-set-for-session](https://stackoverflow.com/questions/78469914/firebasecrashlytics-no-userid-set-for-session)

What I have done, is to add these in the AndroidManifest.xml inside ```<application>```.
```
<meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="true" />
```

**Comment by lehcar09** [comment]
Hi @Dudi111, thank you for updating the MCVE. I was able to reproduce the issue. After some debugging, when I comment out the custom uncaught exception handler (`uncaughtExceptionInitialization()`) from the Service the crash is reported successfully. 

Let me consult this to our engineers and get back to you. I just want to clarify one thing, can you share why you have a custom uncaught exception handler?

**Comment by Dudi111** [comment]
Hi @lehcar09 I have used uncaught exception handler because i want to restart my service if it gets killed due to any uncaught exception.

**Comment by themiswang** [comment]
Hey @Dudi111,

Sorry for getting into this now. For 19.2.0 release we did a lot of refactor work to improve the efficiency of the SDK so many disk I/O processes we moved to a dedicated background thread. So after the update, while non-fatal writing to the persistence it is likely the process is already getting killed by that time. We would suggest to propagate exceptions to our exception handler instead of using non-fatal log. For the example test code, instead of recording non-fatal in you custom uncaught exception handler, you can change in `restartService()`:
```
    fun restartService(t: Thread, ex: Throwable) {
        val service = PendingIntent.getService(
            applicationContext,
            1012,
            Intent(applicationContext, MyForegroundService::class.java),
            PendingIntent.FLAG_IMMUTABLE
        )
        val alarmManager = getSystemService(ALARM_SERVICE) as AlarmManager
        alarmManager[AlarmManager.ELAPSED_REALTIME_WAKEUP, 4000] = service
        defaultUEH?.uncaughtException(t, ex) // propagate exception to Crashlytics uncaught exception handler
        // Runtime.getRuntime().exit(0)  Note: no need to exit here, eventually process will exit
    }
```

**Comment by Dudi111** [comment]
Hey @themiswang After making changes suggested by you its working fine. Thankyou
