### ISSUE TITLE
[SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 INVALID_PROJECT_ID:Project ID does not match MFA pending credential

### ISSUE THREAD

**Issue by 0xPr0xy** [firebase/firebase-android-sdk#6364]
Please reopen https://github.com/firebase/firebase-android-sdk/issues/6348 as it wasn't clear what the assignee ran into when not being able to reproduce the issue.
Also I would appreciate a response to the other points mentioned in my last reply.

**Comment by lehcar09** [comment]
Hi @0xPr0xy, I have re-opened the issue #6348. To streamline our conversation, I'll close this issue and respond to the original ticket. Thanks!
