### ISSUE TITLE
Seemingly no way to recover from remote config after retries are used up

### ISSUE THREAD

**Issue by spiricn** [firebase/firebase-android-sdk#6398]
* Android Studio version: `Android Studio Koala Feature Drop | 2024.1.2 Patch 1 Build #AI-241.19072.14.2412.12360217`
  * Firebase Component: Remote Config
  * Component version: BOM 33.4.0

#### Steps to reproduce:

Under bad network conditions it is possible for `ConfigRealtimeHttpClient` to end up in an un-recoverable state due to which the application will stop receiving real time updates until restarted.

`ConfigRealtimeHttpClient:httpRetriesRemaining` is decremented on every connection attempt; and reset to `ORIGINAL_RETRIES` (8) an every successful attempt.

If for some reason all retries are used up, and `httpRetriesRemaining` reaches zero, there doesn't seem to be a way to attempt another connection (Other than deleting and creating the firebase application again).

When this happens the following error is thrown (line 389):

`Unable to connect to the server. Check your connection and try again.`

**Comment by lehcar09** [comment]
Hi @spiricn, thank you for reaching out and reporting the issue. Looking into it, you're right, the `httpRetriesRemaining` does not reset if it's all used up and will throw an error `Unable to connect to the server. Check your connection and try again.`. 

However, It looks to me that this is an intended behavior. The real-time update is implemented with exponential-backoff https://github.com/firebase/firebase-android-sdk/blob/a00c3109de58cb4e6c53c80e05b9f79a6d3f64c9/firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java#L71

and based on our [documentation](https://firebase.google.com/docs/remote-config/real-time?platform=android#listen-for-updates),

> To listen for updates, call [addOnConfigUpdateListener](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/remoteconfig/FirebaseRemoteConfig#addOnConfigUpdateListener(com.google.firebase.remoteconfig.ConfigUpdateListener)), implementing a callback that is invoked whenever a Remote Config update is available in the app. **Behind the scenes, this call starts listening for updates from the Remote Config server.**

If the connection cannot be established after some time, the SDK stops its attempt to make a connection, possibly to avoid exhausting the device resources. 

Let me consult our engineers about this and get back to you once I hear from them.
