### ISSUE TITLE
FID rotate unexpectedly with daily active user

### ISSUE THREAD

**Issue by b95505017** [firebase/firebase-android-sdk#6415]
According from [Document](https://firebase.google.com/docs/projects/manage-installations#monitor-id-lifecycle):
>Here are some cases where FIDs could be deleted or rotated:
>
>* Uninstallation or reinstallation of the app, for instance when an end user installs on a new device.
>* The end user clears the cache of the app or the device.
>* FID deletion is triggered in the backend due to app inactivity (currently the threshold for this is 270 days of inactivity).

We use FID as the base of database encrypted key by its lifecycle (only if user reaches three cases above). But in reality, our daily active user still may face to FID rotate unexpectedly, thus database decryption failed. 

For a daily active user, is there any other reason causing FID rotation?
I face this issue as well after updating app through Google Play. Just use our app normally a hours ago.

**Comment by lehcar09** [comment]
Hi @b95505017, thank you for reaching out. From what I've gathered, ​​In some cases, especially for major updates that significantly change the app's structure or functionality, the update process might require a full reinstallation. This is to ensure that the new version of the app can work correctly with the old data and settings. It’s possible that in such instances, FIS ID could be deleted or rotated.

In my opinion, FIS ID might not be suitable as a key for your decryption. With that, I’ll be closing this issue. Let me know if there’s any misunderstanding so we can re-open the issue for further investigation. Thanks!
