### ISSUE TITLE
Realtime Database has no callback for write operation when app is offline

### ISSUE THREAD

**Issue by BijayKumarPun** [firebase/firebase-android-sdk#642]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: ___3.4.1__
  * Firebase Component: __Database___ (Database, Firestore, Storage, Functions, etc)
  * Component version: __17.0.0___

### [REQUIRED] Step 3: Describe the problem

When app is offline and tries to perform write operation to the realtime database, there is no way to tell if the write operation was successful or failed. The callbacks available viz. `.addOnCompleteListener()` and `.addOnFailureListener()` are only when app is online. This issue is there specially when my app needs disk persistence to be disabled, read `FirebaseDatabase.getInstance().setPersistenceEnabled(false);`

I think it's more of a common thing, I want to perform a write operation and if that wasn't successful, I want users to notify about it, and not have to guess if that actually failed if I didn't receive any callback for more than, say, 3 seconds.

I could have tried to solve it with `.addValueEventListener()` on the same node I'm trying to perform the write operation, but it becomes even a bigger issue as multiple users may write in the same node.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Perfom write operation to firebase database in offline mode.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by schmidt-sebastian** [comment]
@BijayKumarPun Thanks for filing this issue! 

If a write operation doesn't throw an exception, the contents were successfully persisted either on disk or in memory. The task callback is only used to inform you whether the write to the backend succeeded. When you are offline, we will retry the writes when you get back online. With disk persistence, this even happens across app restarts.

Please note that we currently do not plan to offer more visibility into this for the RTDB SDK. Our suggested work-around is to use Value listeners as you suggested as well. For what it is worth, we do offer some more fine-grained control with Firestore.

**Comment by BijayKumarPun** [comment]
@schmidt-sebastian Thanks for replying!
Right now, value listeners are not quite the thing that I'm looking for. But yes, I am now more clear to how the callback works.
Can you please help me on how I can just completely disable the disk persistence when app is offline? So that at least I can throw TIMEOUT_ERROR upon not getting any callback after a certain time interval instead of having to worry because disk persistence may cause the data to be written on next app usage and that isn't something I want at all !

**Comment by argzdev** [comment]
Hi @BijayKumarPun, just bumping this thread. You could try detecting connection states for your type of use case by adding an `addValueEventListener` on the reference of `.info/connected`. This will be triggered every time your app goes online/offline. I'm not exactly sure how you will be using this in your use case, but this is definitely something you can take a look into. Here is the [documentation](https://firebase.google.com/docs/database/android/offline-capabilities#section-connection-state).

With that said, since a solution for this exists, I will be closing this now.
