### ISSUE TITLE
Firebase Database component not present

### ISSUE THREAD

**Issue by gautamkunwar** [firebase/firebase-android-sdk#646]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.2
  * Firebase Component:  Firebase Database (Database, Firestore, Storage, Functions, etc)
  * Component version: 18.0.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
FirebaseDatabase database = FirebaseDatabase.getInstance();

Caused by: java.lang.NullPointerException: Firebase Database component is not present.
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:11)
        at com.google.firebase.database.FirebaseDatabase.getInstance(com.google.firebase:firebase-database@@17.0.0:120)
        at com.google.firebase.database.FirebaseDatabase.getInstance(com.google.firebase:firebase-database@@17.0.0:60)
        at com.vkeel.Dependencies.init(Dependencies.java:52)
        at com.vkeel.BaseActivity.onCreate(BaseActivity.java:15)
        at com.vkeel.ui.login.LoginActivity.onCreate(LoginActivity.java:59)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
```

**Comment by schmidt-sebastian** [comment]
@gautamkunwar Thanks for filing this issue! I suspect your dependencies are not getting resolved correctly. Can you share your output from `mvn dependency:tree`? Thank you!

**Comment by Allansk2** [comment]
Do you fix the problem, I am going the same error.

**Comment by schmidt-sebastian** [comment]
@Allansk2 Can you share your dependencies from the `build.gradle` file?

**Comment by gautamkunwar** [comment]
Hey Sebastian i have to downgrade my android studio as well as firebase
version in order to get it work.

**Comment by SilverFoxA** [comment]
I have a similar issue for `Cloud Firestore` @schmidt-sebastian 

Please find the details you required detailed below

Here's my project level Gradle project/build.gradle

```
buildscript {

    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.0'
        classpath 'io.fabric.tools:gradle:1.31.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
App-level gradle has the following `app/build.gradle`

    
    implementation 'com.google.firebase:firebase-core:17.0.1'
    implementation 'com.google.firebase:firebase-analytics:17.0.1'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    implementation 'com.google.firebase:firebase-ads:18.1.1'
    implementation 'com.google.firebase:firebase-firestore:20.2.0'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'

and gradle.properies

```
android.enableJetifier=true
android.useAndroidX=true
```

Initialized Firestore in application

`FirebaseApp.initializeApp(this);`

In my activity

    db = FirebaseFirestore.getInstance();
        FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
                .setPersistenceEnabled(true)
                .build();

        db.setFirestoreSettings(settings);

**Comment by vkryachko** [comment]
This is similar to #685 , please provide answers to questions I posted in https://github.com/firebase/firebase-android-sdk/issues/685#issuecomment-518688578

**Comment by ashwinraghav** [comment]
Folks,
We are not sure if you are continuing to face the same problems, since it's been a while. Please let us know.
