### ISSUE TITLE
Firebase InAppMessaging: Duplicate class javax.annotation.CheckForNull found in modules jsr305-1.3.9.jar

### ISSUE THREAD

**Issue by Sub-Zero-1** [firebase/firebase-android-sdk#647]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.1
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version:    
    implementation 'com.google.firebase:firebase-inappmessaging-display:18.0.2'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'
    implementation 'com.google.firebase:firebase-core:17.0.1'
    implementation 'com.firebaseui:firebase-ui-auth:4.2.1'
    implementation 'com.google.firebase:firebase-config:18.0.0'
    implementation 'com.google.firebase:firebase-auth:18.1.0'

### [REQUIRED] Step 3: Describe the problem

Tried to implement Firebase In App Messaging now for the 3th times during 2 years, and never got it working. I already tried to fix this error with stackoverflow:
https://stackoverflow.com/questions/35485716/android-gradle-build-dependency-error

Nothing works for me. Still getting same error.

If I do this:

configurations {
    all*.exclude module: 'jsr305'
}

The code compiles, but the app crash at startup due to memory leak, which is insane!

#### Relevant Code:

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class javax.annotation.CheckForNull found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.CheckForSigned found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.CheckReturnValue found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Detainted found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.MatchesPattern found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.MatchesPattern$Checker found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Nonnegative found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Nonnegative$Checker found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Nonnull found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Nonnull$Checker found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Nullable found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.OverridingMethodsMustInvokeSuper found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.ParametersAreNonnullByDefault found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.ParametersAreNullableByDefault found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.PropertyKey found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.RegEx found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.RegEx$Checker found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Signed found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Syntax found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Tainted found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.Untainted found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.WillClose found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.WillCloseWhenClosed found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.WillNotClose found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.concurrent.GuardedBy found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.concurrent.Immutable found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.concurrent.NotThreadSafe found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.concurrent.ThreadSafe found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.meta.Exclusive found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.meta.Exhaustive found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.meta.TypeQualifier found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.meta.TypeQualifierDefault found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.meta.TypeQualifierNickname found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.meta.TypeQualifierValidator found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)
  Duplicate class javax.annotation.meta.When found in modules jsr305-1.3.9.jar (jsr305-1.3.9.jar) and jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2)

**Comment by aguatno** [comment]
Hi @Sub-Zero-1 sorry for my late response here. It looks like these error didn't persist in the latest version. I was wondering if you're still having this issue? If so, could you provide the following so that I can investigate the issue further:

- Minimal repro of your code that I can run locally
- Firebase SDK version you're using
- Any other relevant information
