### ISSUE TITLE
Android apps do not receive notifications after a period of inactivity

### ISSUE THREAD

**Issue by chenlindev** [firebase/firebase-android-sdk#6533]
My problem is the same as this guy(https://github.com/firebase/firebase-android-sdk/issues/4317), I push the following configuration using AWS SNS data:

```
let content = {
    android: { priority: 'high' }
    data: { ... }
}

let payload = {
    default: '',
    'APNS': ...
    GCM: JSON.Stringfy(content)
}

sns.push(payload)

```

**Comment by lehcar09** [comment]
Hi @chenlindev, thank you for reaching out. Just to give an insight, there are factors that could affect message delivery. You can check this [blog post](https://firebase.blog/posts/2019/02/life-of-a-message#android-message-delivery-factors) for some of those factors. Aside from that, high priority messages are prioritized for immediate delivery. However, they are not guaranteed to be delivered if the device is offline or has limited network connectivity. You can check this [docs](https://firebase.google.com/docs/cloud-messaging/android/message-priority) for more details.

Could you answer a few questions below for us to further investigate this:

- Were you able to reproduce the issue? Could you provide the steps to reproduce the issue?
- Can you share the Firebase Messaging version you’re using? 

Thanks!
