### ISSUE TITLE
Service not registered: com.google.firebase.iid.zzae@72d55c0

### ISSUE THREAD

**Issue by leeManong** [firebase/firebase-android-sdk#656]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.1
  * Firebase Component:firebase-core and firebase-messaging
  * Component version: 16.0.9,18.0.0

### [REQUIRED] Step 3: Describe the problem
I got this crash report from a crash report platform.
#### Relevant Code:
The crash log.
```
android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1352)
 android.app.ContextImpl.unbindService(ContextImpl.java:1536)
 android.content.ContextWrapper.unbindService(ContextWrapper.java:700)
 com.google.android.gms.common.stats.ConnectionTracker.unbindService(Unknown Source)
 com.google.firebase.iid.zzae.zzz(Unknown Source)
 com.google.firebase.iid.zzae.zza(Unknown Source)
 com.google.firebase.iid.zzad.handleMessage(Unknown Source)
 android.os.Handler.dispatchMessage(Handler.java:98)
 com.google.android.gms.internal.firebase_messaging.zze.dispatchMessage(Unknown Source)
 android.os.Looper.loop(Looper.java:154)
 android.app.ActivityThread.main(ActivityThread.java:6682)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)
```

**Comment by aguatno** [comment]
Hi @leeManong sorry for the delay. I haven't seen that error before, I was wondering if you have numbers to show how frequent this crash is?

You may also consider upgrading your [SDK to the latest version](https://firebase.google.com/docs/android/setup#available-libraries), and see if the persists from there.

Thanks!
