### ISSUE TITLE
Firebase is restricting my app messages. I have deleted accts. Why aren't I receiving all in app messages m please release 

### ISSUE THREAD

**Issue by Vonssgh** [firebase/firebase-android-sdk#6580]
### [READ] Step 1: Are you in the right place? Please remove firebase and firebase rules 

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by lehcar09** [comment]
Hi @Vonssgh, thank you for reaching out. In order for us to help you, could you file a new issue thread with the complete details  of the issue that you're referring to so that we may assist you properly. These information will be helpful for us to conduct an initial investigation. Thanks!

**Comment by Vonssgh** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>Firebase Status Dashboard Updates</title>
  <updated>2024-12-09T23:00:48+00:00</updated>
  <link href="https://status.firebase.google.com/" rel="alternate" type="text/html"></link>
  <link href="https://status.firebase.google.com/en/feed.atom" rel="self"></link>
  <author>
    <name>Firebase</name>
  </author>
  <id>https://status.firebase.google.com/</id>
  <entry>
    <title>RESOLVED: Firebase Test Lab is experiencing longer wait times for all test executions.
Next update in four hours or when something significantly changes.</title>
    <link href="https://status.firebase.google.com/incidents/qt3DfVtThvMkLXLvc6zz" rel="alternate" type="text/html"></link>
    <id>tag:status.firebase.google.com,2024:feed:qt3DfVtThvMkLXLvc6zz.o9jHQnE2tLJoAE6fDkYb</id>
    <updated>2024-12-09T23:00:48+00:00</updated>
    <summary type="html">&lt;p&gt; Incident began at &lt;strong&gt;2024-12-09 13:00&lt;/strong&gt; and ended at &lt;strong&gt;2024-12-09 15:00&lt;/strong&gt; &lt;span&gt;(all times are &lt;strong&gt;US/Pacific&lt;/strong&gt;).&lt;/span&gt;&lt;/p&gt;&lt;div class="cBIRi14aVDP__status-update-text"&gt;&lt;p&gt;Tests are running now for all form factors (iOS and Android virtual, Arm, physical). Customers may still see some higher wait times for iOS devices.&lt;/p&gt;
&lt;/div&gt;&lt;hr&gt;&lt;p&gt;Affected products: Test Lab&lt;/p&gt;</summary>
  </entry><entry>
    <title>UPDATE: Firebase Test Lab is experiencing longer wait times for all test executions.
Next update in four hours or when something significantly changes.</title>
    <link href="https://status.firebase.google.com/incidents/qt3DfVtThvMkLXLvc6zz" rel="alternate" type="text/html"></link>
    <id>tag:status.firebase.google.com,2024:feed:qt3DfVtThvMkLXLvc6zz.Q8fkyFZt2rQSSg5ecNFX</id>
    <updated>2024-12-09T22:59:58+00:00</updated>
    <summary type="html">&lt;p&gt; Incident began at &lt;strong&gt;2024-12-09 13:00&lt;/strong&gt; and ended at &lt;strong&gt;2024-12-09 15:00&lt;/strong&gt; &lt;span&gt;(all times are &lt;strong&gt;US/Pacific&lt;/strong&gt;).&lt;/span&gt;&lt;/p&gt;&lt;div class="cBIRi14aVDP__status-update-text"&gt;&lt;p&gt;We are currently investigating the cause and are applying mitigations.&lt;/p&gt;
&lt;/div&gt;&lt;hr&gt;&lt;p&gt;Affected products: Test Lab&lt;/p&gt;</summary>
  </entry>
</feed>

**Comment by Vonssgh** [comment]
Why are my messages being intercepted by your platform. I want all traffic via notifications coming directly to my apps. Why are you guys involved
