### ISSUE TITLE
Int/Long values being sent to Firebase is being converted to a Double

### ISSUE THREAD

**Issue by georgekarkavitsasreed** [firebase/firebase-android-sdk#6603]
### [READ] Step 1: Are you in the right place?
Hi team!
Yes, this issue pertains to a possible bug in the Firebase Analytics SDK code.

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Koala | 2024.1.1
  * Firebase Component: Analytics
  * Component version: 33.1.1

### [REQUIRED] Step 3: Describe the problem

**Steps to reproduce:**

- Use the Firebase Analytics SDK to send an event with a large Int or Long parameter (e.g., 54102976).
- Verify the parameter in Firebase Debug View.
- Observe that the parameter is displayed as a Double instead of the original type (Int or Long).

Example:
When logging an event like this:

```
eventName = click_job
bundle = Bundle[{job_type=permanent, job_age=18, job_location=Horsforth, job_id=54102976, search_term=Android, data_key_metric=true, af_id=1734431107002-2738929145351857341, recruiter_ECID=10449222, recruiter_OUID=386308, recruiter_type=direct_employer, job_recruiter_tier=2, job_easy_apply_status=Easy Apply Job: External + No Screening Question, job_title=Technical Systems Administrator, data_screen_component=job_card, data_screen_category=search_results, data_element=click_job, job_card_position=1}]

firebaseAnalytics.logEvent(eventName, bundle)
```

The Debug View displays the following:
job_id: 5.4103e+07 (Double format) and
recruiter_ECID = 1.04492e+07 (Double format)

**Expected Behavior:**
Numeric parameters sent as Int or Long should retain their original data type in Debug View.

**Actual Behavior:**
Parameters sent as Int or Long are converted to Double in Debug View.

Debug View Snapshot:
![Screenshot 2024-12-17 at 15 01 04](https://github.com/user-attachments/assets/f7d929ad-d813-4ba7-a89f-831346cace72)
![Screenshot 2024-12-17 at 15 01 17](https://github.com/user-attachments/assets/60b8d772-70a8-4acf-9015-d33feecb4ca3)

**Relevant Log Output**
Android studio Logs of the event sent:
FirebaseAnalytics logged ga4 event click_job, with params: Bundle[{job_type=permanent, job_age=18, job_location=Horsforth, job_id=54102976, search_term=Android, data_key_metric=true, af_id=1734431107002-2738929145351857341, recruiter_ECID=10449222, recruiter_OUID=386308, recruiter_type=direct_employer, job_recruiter_tier=2, job_easy_apply_status=Easy Apply Job: External + No Screening Question, job_title=Technical Systems Administrator, data_screen_component=job_card, data_screen_category=search_results, data_element=click_job, job_card_position=1}]

**Firebase SDK Version**
SDK version: 33.1.1

**Firebase Product(s)**
Product: Analytics

**Targeted Platforms**
Platform: Android

**Comment by lehcar09** [comment]
Hi –, thank you for reaching out. I tried reproducing the issue, however, I was able to log integer and long value properly.

```
val parameter1 = Bundle().apply {
   this.putString("int_eventName", "Int event")
   this.putInt("int_eventValue", 386308)
}

analytics.logEvent("int_event", parameter1)

val parameter2 = Bundle().apply {
   this.putString("long_eventName", "Long event")
   this.putLong("long_eventValue", “54102976”)
}

analytics.logEvent("long_event", parameter2)
``` 

![Image](https://github.com/user-attachments/assets/5cfcd931-e108-4a31-934f-f7e1e5da79ff)
![Image](https://github.com/user-attachments/assets/d34e3118-ece5-4196-973b-c645b4785869)

By any chance, can you share a code snippet and [verbose logs](https://firebase.google.com/docs/analytics/events?platform=android#view_events_in_the_android_studio_debug_log)? 

Aside from that, I suggest updating to the [latest Firebase SDK](https://firebase.google.com/support/release-notes/android) version to ensure that you have the latest bug fixes that might be causing issue. Thanks!

**Comment by georgekarkavitsasreed** [comment]
Hi team,

Thank you for your prompt response and assistance. Your feedback helped us identify a custom configuration in our implementation that was causing the issue. We've resolved it on our end.

If possible, please feel free to close this ticket. We truly appreciate your support and the work you do to help developers!

Wishing you a Merry Christmas and a wonderful holiday season!

**Comment by lehcar09** [comment]
Thank you for the confirmation. I'll be closing this issue now. Thanks and Happy Holidays!
