### ISSUE TITLE
Error 12500 on Google Sign In

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/firebase-android-sdk#664]
### Step 1: Are you in the right place?
Yes

## Step 2: Describe your environment

  * Android Studio version: 3.4.2
  * Firebase Component: Authentication
  * Component version: 
```
    implementation 'com.google.firebase:firebase-auth:18.0.0'
    implementation 'com.google.android.gms:play-services-auth:17.0.0'
```
### Step 3: Describe the problem
I used [this](https://github.com/firebase/quickstart-android/blob/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt) code as it is without any change.

I created a new Firebase project, then I performed all the important steps:
- Used Latest Google Play support libraries and Firebase libraries
- Added DEBUG SHA-1 Key in console
- Enabled Google Sign-In Method
- Added support email for authentication.
- Checked that my device is having the latest Google Play Services installed.

 After performing this, downloaded latest `google-services.json` and imported in the project. Though it is showing me error 12500.

Then, I again checked the Google Cloud API Console OAuth2.0 page and checked my URL and it's correct.

After this, I created 3 different projects, with different accounts and performed the same things again and again. Though I didn't get success. Please Help me in that issue.
I tried all other authentications like **PhoneAuth**, **EmailAuth**, etc. But an error occurs in Google Sign-In only.

#### Steps to reproduce:
While signing in with Google, It fails and then here is a log.
```
2019-07-26 07:54:38.432 31194-31194/com.example.firebaserecyclerpagination W/GoogleActivity: Google sign in failed
    com.google.android.gms.common.api.ApiException: 12500: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source)
        at com.google.firebase.quickstart.auth.kotlin.GoogleSignInActivity.onActivityResult(GoogleSignInActivity.kt:76)
        at android.app.Activity.dispatchActivityResult(Activity.java:7109)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4192)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

#### Relevant Code:
I used [this](https://github.com/firebase/quickstart-android/blob/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInActivity.kt) code as it is without any change.

**Comment by samtstern** [comment]
@PatilShreyas can you try setting an email and logo in the "OAuth consent screen" settings in the Google Cloud console?

**Comment by PatilShreyas** [comment]
Oh, thanks! 😃 This helped me a lot. But I want to ask, is it a new setting? Earlier I haven't any need of such OR it's not mentioned anywhere in Firebase.

**Comment by samtstern** [comment]
@PatilShreyas it's not a new setting but it seems like something has changed recently causing a lot more people to get error 12500.  The backend team is investigating.

**Comment by PatilShreyas** [comment]
Oh okay. Thanks.

**Comment by joaocamiloulhoa** [comment]
I have an android app that works well, but I'm trying to build a new one, so I copied and pasted the old code, making the proper updates, but it doesn't work !!! how boring that is !!! This is bugging the same error 12500.

**Comment by PatilShreyas** [comment]
Do this setting, it helped.

https://github.com/firebase/firebase-android-sdk/issues/664#issuecomment-515519636

**Comment by LordOfBytes** [comment]
> @PatilShreyas can you try setting an email and logo in the "OAuth consent screen" settings in the Google Cloud console?

This helped me to !
After two days (with a lot of foul language) the problem was fixed by oploading a "missing" logo at console.developers.google.com !
OMG ! :-/ 

I had no chance of guessing that by looking at Firebase console site where everything looked fine.... 

PatilShreyas ...Thanks ! :-)

**Comment by PatilShreyas** [comment]
@LordOfBytes Welcome!

**Comment by ronanwilliams3890** [comment]
https://www.wikicue.com/fix-google-sign-in-error-on-android you can visit this link and it may be helpfull for you
