### ISSUE TITLE
"Program type already present" problem

### ISSUE THREAD

**Issue by sabreys** [firebase/firebase-android-sdk#668]
problem : you get "Program type already present androidx.appcompat.R$anim "  when you add inappmessaging. you cant find the right solution and change too many dependencies.
Solution :
```
 implementation('com.google.firebase:firebase-messaging:17.3.4') {
        exclude group: 'com.google.guava'
        exclude module: 'firebase-common'
    }
implementation 'com.google.firebase:firebase-inappmessaging-display:18.0.2'
```
[https://stackoverflow.com/a/48742381/11777442](source)
i tried so many thinks for fix this bug. its not about picasso  or guava  i guess.

**Comment by aguatno** [comment]
Hi @sabreys sorry for not answering you sooner. I tried the said dependencies using the latest SDK version and it seems to be working fine.

![Screenshot from 2019-11-14 03-28-14](https://user-images.githubusercontent.com/56451054/68797126-f3956b80-068e-11ea-8aac-5740a5ba183b.png)

Could you try upgrading your SDK to the latest version, and see if the persists from there?

Thanks.
