### ISSUE TITLE
Unable to get credentials: account-exists-with-different-credentials

### ISSUE THREAD

**Issue by ncapdevi** [firebase/firebase-android-sdk#679]
### Step 2: Describe your environment

  * Android device: Emulator Pixel 2
  * Android OS version: API 28

### Step 3: Describe the problem:
Both iOS and Web detail how to handle the error account-exists-with-different-credential which occurs when trying to sign in to an account that is already set in firebase auth with a given email. However the Android documentation has no such details and in fact the explicit error documentation doesn't provide any additional info. The piece that seems to be missing is that with iOS and Web, when the error occurs, the credentials are still returned, but I can't seem to find them with the exception on Android. So how do you use the link with credentials methods if you never received the credentials (even though the sign in was successful)?

https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthUserCollisionException getUpdatedCredentials() is null in this case, but shouldn't be.

#### Steps to reproduce:

  1.  Create an account with a provider
  2.  Try to login with another provider (that doesn't have a verified email)
  3.  The other SDKs return the credentials so that they can be linked
  
#### Observed Results:

  * GetUpdatedCredentials is null
  
#### Expected Results:

  * GetUpdatedCredentials should provide the credentials so they can be used to link the accounts

**Comment by samtstern** [comment]
@ncapdevi issue transferred!

**Comment by lsirac** [comment]
@ncapdevi we are going to release this functionality on Android very soon. I'll post here when we've released it so you're aware, but also keep an eye out for an update in our docs. 

Also, you only need getUpdatedCredential for linking flows when using Generic IDP. You can keep a reference to the credential in other flows.

**Comment by ncapdevi** [comment]
Perfect. Thanks so much for the feedback and help!
