### ISSUE TITLE
Cannot obtain OAuth Access Token using getAccessToken()

### ISSUE THREAD

**Issue by josh1dev** [firebase/firebase-android-sdk#688]
Dear Firebase,

**Platform:** Android 
**Language**: Kotlin 
**Firebase SDK:** Latest versions on everything 
**Play Services APIs:** Latest versions
**Documentation:** https://firebase.google.com/docs/auth/android/github-auth

I cannot seem to call the ``authResult.getCredential().getAccessToken()`` function for some reason. I'm using GitHub OAuth, however I don't seem to be able to get the access token using your provided functions. The function just doesn't exist. 

Logging in, obtaining client information, all other functions work fine so I think this is just something which has to be released or is deprecated? I hope someone can help me out on this one. 

Thanks!

**Comment by koza4e4ok** [comment]
Have same issue `authResult.credential.accessToken` not found in `'com.google.firebase:firebase-auth:18.1.0'` api

**Comment by vkryachko** [comment]
/cc @malcolmdeck 
Malcolm, can you pls take a look at this?

**Comment by malcolmdeck** [comment]
[AuthCredential](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AuthCredential.html) doesn't have a method getIdToken() - you have to cast an AuthCredential to the appropriate subclass, which is probably [OAuthCredential](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/OAuthCredential) in this circumstance.

Manually inspecting the public AAR for version 18.1.0, I can see that the method is there - let me know if casting resolves your issue.

Thanks!
~Malcolm

**Comment by vkryachko** [comment]
If the issue is still not resolved, feel free to re-open
