### ISSUE TITLE
"Sign in with Apple" support

### ISSUE THREAD

**Issue by triplef** [firebase/firebase-android-sdk#700]
## What feature would you like to see?

Add support for authenticating via ["Sign in with Apple"](https://developer.apple.com/sign-in-with-apple/) in Android apps using Firebase.

## How would you use it?

"Sign in with Apple" is Apple’s new authentication solution that allows users to sign in to 3rd party apps using their Apple ID. It is available both as a native [iOS SDK](https://developer.apple.com/documentation/authenticationservices?language=objc) and a [JavaScript SDK](https://developer.apple.com/documentation/signinwithapplejs). Later this year (2019) it will be [mandatory for iOS apps also support "Sign in with Apple"](https://developer.apple.com/news/?id=06032019j) if they also support 3rd party sign in (Facebook, Google, etc.):

> Sign In with Apple will be available for beta testing this summer. It will be required as an option for users in apps that support third-party sign-in when it is commercially available later this year.

Given this, developers using Firebase cross-platform on iOS and Android will want to also offer "Sign in with Apple" in their Android app, so that users switching from iOS to Android can continue to sign in to the app.

As this feature is already being [worked on](https://github.com/firebase/firebase-ios-sdk/pull/3162) for the Firebase iOS SDK and a feature request for the Web SDK, it would be great to also see this natively in the Firebase Android SDK.

https://github.com/firebase/firebase-ios-sdk/issues/3145
https://github.com/firebase/firebase-js-sdk/issues/1931

As a workaround, it should be possible to e.g. use the [Sign In with Apple Button for Android](https://github.com/willowtreeapps/sign-in-with-apple-button-android) library to do this manually.

**Comment by sylvioleblanc** [comment]
+1

**Comment by bojeil-google** [comment]
We launched Apple sign-in support today across all 3 platforms.

https://firebase.google.com/docs/auth/ios/apple
https://firebase.google.com/docs/auth/android/apple
https://firebase.google.com/docs/auth/web/apple
