### ISSUE TITLE
Fabric Gradle Plugin uses obsolete Android Gradle Plugin APIs for Crashlytics

### ISSUE THREAD

**Issue by gildor** [firebase/firebase-android-sdk#711]
* Firebase Component: Crashlytics
  * Component version: Fabric Gradle Plugin 1.31.0, Crashlytics 2.10.1
  * Gradle 5.6
  * Android Gradle Plugin 3.5-rc03

Fabric Gradle plugin uses obsolete Android Gradle Plugin API:
> Task :app:crashlyticsUploadDistributionStageDebug
> WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced 
> with 'variant.getPackageApplicationProvider()'.
> It will be removed at the end of 2019.

This is full stack trace with `-Pandroid.debug.obsoleteApi=true` flag:
https://gist.github.com/gildor/60b4dc330fee12b929baeae758df1ab5

As you can see it caused by the usage of `variantOutput.getPackageApplication()` getter in FabricTaskBuilder.crashlyticsUploadDistribution task builder

**Comment by aguatno** [comment]
Hi @gildor sorry for the long wait. I found a bug (https://issuetracker.google.com/139974869) with exact the same error log and it has been fixed on Nov 7, 2019.

If you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.

Thanks.

**Comment by gildor** [comment]
Yes, it fixed on never versions of Crashlytics, thanks
