### ISSUE TITLE
Update dagger to 2.24

### ISSUE THREAD

**Issue by hameno** [firebase/firebase-android-sdk#712]
## What feature would you like to see?

Newer dagger version (2.24+) so that we can upgrade our app. This currently fails with:

    dagger.android.support.DaggerApplication_MembersInjector: can't find referenced method 'void injectBroadcastReceiverInjector(dagger.android.DaggerApplication,dagger.android.DispatchingAndroidInjector)' in program class dagger.android.DaggerApplication_MembersInjector

## How would you use it?

n/a

**Comment by ashwinraghav** [comment]
Thanks for notifying us.
Seems like this needs to change across inappmessaging and transport runtime!

**Comment by prakhar1989** [comment]
test
