### ISSUE TITLE
Error : "failed to get document because the client is offline"

### ISSUE THREAD

**Issue by luckymanreal** [firebase/firebase-android-sdk#717]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____3.4.1
  * Firebase Component: __Firestore___ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____20.1.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

FirebaseFirestore db = FirebaseFirestore.getInstance();

            db.collection("XXX").document("xxx")
                    .get().addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
                @Override
                public void onComplete(@NonNull Task<DocumentSnapshot> task) {
                  if (task.isSuccessful()) {
                         ... ... ... 
                  }else{
                      -- print task.getException() <------- here error often occurs
                  }
               }
         }

**Comment by var-const** [comment]
Can you please enable logging (`FirebaseFirestore.setLoggingEnabled(true);`) and post your logs (make sure they contain no sensitive information)? This exception would occur if the device is actually offline, so to solve the issue, it would be necessary to understand why the device is having network problems.
