### ISSUE TITLE
Migrate to Android 28

### ISSUE THREAD

**Issue by iamyaoxi** [firebase/firebase-android-sdk#72]
Since now we have Android 28, with the latest Gradle plugin, why don't we just use the latest dependencies?

**Comment by ashwinraghav** [comment]
Hey Yosi,
This seems reasonable. Please send us a pull request with the upgrades you have in mind.

**Comment by iamyaoxi** [comment]
Hi @ashwinraghav 
I already made one. It's in the Pull Requests pool. Over there, it's pull requests #73
