### ISSUE TITLE
Fatal Exception: com.google.firebase.database.DatabaseException  No properties to serialize found on class com.google.firebase.firestore.FieldValue$ServerTimestampFieldValue site:stackoverflow.com

### ISSUE THREAD

**Issue by adfaous** [firebase/firebase-android-sdk#731]
Hello, my android app keeps crashing anytime I tried to write data to firebase realtime database, I went to firebase console and check the crashlytics, but I saw the above error code.. 

Below is my code line that causes the crash.. 
Map<String, Object> questionList = new HashMap<>(); 
questionList.put("question", "_____"); 
questionList.put("a", "_______"); 
questionList.put("b", "_______"); 

mDatabasee.child("subject").child(year).push().setValue(questionList) ;

**Comment by wilhuff** [comment]
Somewhere in your code you're adding Firestore's `FieldValue.serverTimetamp()` to the value you're trying to store to RTDB. This isn't going to wok.

**Comment by adfaous** [comment]
That is true, I save the data to both realtime database and firestore..  
So I added the FieldValue.serverTimeStamp() to part of the questionList value, just to take note of the write time.

**Comment by adfaous** [comment]
Thanks so much sir, should I close the issue or you will sir?
