### ISSUE TITLE
Databinding issue with the androidx update of June 17, 2019

### ISSUE THREAD

**Issue by benjaminledet** [firebase/firebase-android-sdk#742]
Whatever library I tried to update from the androidx migration of June 17, 2019 (tested with config, analytics and messaging), I get this error in all the layouts using a swipeRefreshLayout : 

```
error: cannot find symbol public final SwipeRefreshLayout swipeRefreshLayout;   
symbol:   class SwipeRefreshLayout
location: class FragmentHomeBinding
```

For example, with `com.google.firebase:firebase-inappmessaging-display:17.2.0` everything works fine but all the versions after `18.0.0` are causing the bug.

Here are the release notes : 
https://firebase.google.com/support/release-notes/android#update_-_june_17_2019

I really have no idea of how to resolve this.

My app is built with androidx, here are some versions I use that might be useful : 

> android studio: 3.5 from August 9, 2019
> compile version : 29
> kotlin: 1.3.41
> gradle : 3.5.0
> appCompat: 1.0.2
> google-services: 4.3.1

**Comment by benjaminledet** [comment]
Thanks for your detailed answer but like I said, my whole project is built with androidx since the beginning, I have always used all the androidx artifacts so all of my views comes from androidx.

**Comment by benjaminledet** [comment]
Well thank you for the tip, I should have done that in the first place! 

So I've created a minimal project by keeping all of my app's dependencies and then I removed then one by one. I found that it's the material library causing the trouble.

I'm using the last version which is `com.google.android.material:material:1.1.0-alpha09`.
https://github.com/material-components/material-components-android/releases

I tried revert back to the alpha08 and it's work fine, so the problem is with alpha09, it seems there is a conflict between this version and the last firebase versions.

Is the problem caused by the material library or by firebase? Should I open a ticket on the material library?

**Comment by rsgowman** [comment]
My testapp happens to already have material, but was using 1.0.0. Using either 1.1.0-alpha08 or 1.1.0-alpha09 seemed to work for me as well though. Perhaps it's an interaction with -alpha09, firebase, and some other dependency? Could you post your full app/build.gradle file?

**Comment by benjaminledet** [comment]
Thank you for your time,
I've re-check and found that it was caused by the multi-module architecture.
I've placed all the firebase dependencies in a module "firebase"  like this : 
```
implementation platform("com.google.firebase:firebase-bom:22.0.0")   
implementation "com.google.firebase:firebase-analytics"
implementation "com.google.firebase:firebase-inappmessaging-display"
implementation "com.google.firebase:firebase-messaging"
implementation "com.google.firebase:firebase-config"
```

And my app gradle looks like : 
```
dataBinding {
     enabled = true
}
...
implementation project(":firebase")
implementation "com.google.android.material:material:1.1.0-alpha08"
```

If I change the `implementation` in the firebase gradle by `api` it works.

But still, I shouldn't have to do do this and mostly, this issue occurs only with the `alpha09 ` and with dataBinding enabled! Without dataBinding it works

I've created a minimal project to demonstrate de bug, it happen without DataBinding too.

**Comment by benjaminledet** [comment]
Sorry I closed the issue by mistake.

**Comment by rsgowman** [comment]
I've taken a look at your repro and using it, I see the same error you do.

I can comment out `implementation project(":firebase")` and still see the same behaviour. This  implies that the issue may not have anything to do with either firebase, or with multi-modules at all. (Or at least, I can reproduce it without those.)

So I think the "issue" is with material. Specifically, I think this might be the problem:
https://github.com/material-components/material-components-android/commit/68ddfee0ed086d2c4d448dafc2b9bdc81d373e20

They've narrowed down their dependencies and no longer include androidx.legacy:legacy-support-core-ui. My suspicion, is that this package is pulling in the swiperefreshlayout package.

So a solution then, would be for you to include swiperefreshlayout in your gradle file. i.e.:

```
$ git diff
diff --git a/app/build.gradle b/app/build.gradle
index ad20a3a..bb3a55b 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -38,6 +38,7 @@ dependencies {
     implementation 'androidx.appcompat:appcompat:1.0.2'
     implementation 'androidx.core:core-ktx:1.0.2'
     implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
+    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'
     testImplementation 'junit:junit:4.12'
     androidTestImplementation 'androidx.test:runner:1.2.0'
     androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
```

This seems to work for me. Give it a try and let me know.

**Comment by benjaminledet** [comment]
You are right, it works by adding this dependency and it probably has nothing to do with firebase.
It's weird though, I hope they will fix this issue!

Thanks for your help!
