### ISSUE TITLE
Remote Config - Encode Problems

### ISSUE THREAD

**Issue by hrossi** [firebase/firebase-android-sdk#768]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 
Android Studio 3.5
Build #AI-191.8026.42.35.5791312, built on August 8, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.9-arch1-1-ARCH

  * Firebase Component:
Remote Config

  * Component version: 
19.0.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I use Remote Config to change the content in one of our applications.

I'm facing a encode problem in the last version of Remote Config. 

Input (Firebase Console) -> "Olá Mundo"
Output (Android App) -> "OlÃ¡ Mundo"

Create a Android Project
Add Firebase-Core dependencie
Add Firebase-Remote-Config dependencie
Add your google-services.json to the project
Create a new Remote Config on Firebase console with the text "Olá Mundo" (Hello World in portuguese)
Create a new Activity with a simple textview and add the following code:

```kotlin
        FirebaseRemoteConfig.getInstance().run {
            fetchAndActivate().addOnSuccessListener {
                Log.d("FIREBASE_TEST", this.getString("PARAM_KEY"))
            }
        }
```

It will log the following text: "OlÃ¡ Mundo"

#### Relevant Code:
https://github.com/hrossi/FirebaseTest

###
Dependencies
![Screenshot_20190905_142214](https://user-images.githubusercontent.com/4356793/64366364-7396b980-cfec-11e9-9bbc-bcbbbe5c4d76.png)

Firebase Console
![Screenshot_20190905_142317-1](https://user-images.githubusercontent.com/4356793/64366407-890be380-cfec-11e9-9191-c117e9cf8cce.png)

Using in a TextView
![Screenshot_20190905_142243](https://user-images.githubusercontent.com/4356793/64366453-a6d94880-cfec-11e9-8f65-3ceababeb86c.png)

Result 
![Screenshot_20190905-145317](https://user-images.githubusercontent.com/4356793/64366746-40085f00-cfed-11e9-835f-c31a72de0a44.png)

**Comment by hnljp** [comment]
I can verify the same for the Danish æ, ø and å.
firebase-core (or firebase-analytics) 17.2.0 is not a problem.
Reverting firebase-config from 19.0.0 to 18.0.0 and the encoding is correct again.

**Comment by hnljp** [comment]
Looks like it is a known issue:
https://github.com/firebase/firebase-android-sdk/pull/718
https://github.com/firebase/firebase-android-sdk/commit/88d909cde4e3a1dfcf1d851bf61c2fb0349b9893#diff-06c1f65f710525a1aa3dcda7ac544fe0

**Comment by hrossi** [comment]
I've just tested on remoteconfig v19.0.1 and it's fixed.

Thanks.
