### ISSUE TITLE
Firebase Upload

### ISSUE THREAD

**Issue by Atlas789** [firebase/firebase-android-sdk#780]
How can I upload text, image and pdf file at the same time under one root?

**Comment by schmidt-sebastian** [comment]
@Atlas789 Thanks for your question. Please take a look here: https://firebase.google.com/docs/storage/android/upload-files

Note that Cloud Storage for Firebase does not support atomic uploads for more than one file. If you have any usage questions, you can reach out to use via our Google Group (https://groups.google.com/forum/#!forum/firebase-talk) or via StackOverflow. We generally want to keep our GitHub discussions to bugs and feature requests.
