### ISSUE TITLE
[CI BLOCKED] :database-test-app:setupSmokeTest failing with "Request had insufficient authentication scopes"

### ISSUE THREAD

**Issue by mikelehen** [firebase/firebase-android-sdk#79]
See e.g. https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/76/smoke-tests-release/1052700842647359492/
```
I1017 23:33:19.862] > Task :database-test-app:setupSmokeTest
W1017 23:33:19.963] 
W1017 23:33:19.963] Error: HTTP Error: 403, Request had insufficient authentication scopes.
I1017 23:33:21.862] 
I1017 23:33:21.862] > Task :database-test-app:setupSmokeTest FAILED
```

**Comment by allisonbm92** [comment]
I've rebuilt and redeployed the CI image used by the smoke tests. This should resolve the issue.

The debug smoke tests pass in a test PR. The release tests are still running, but this error occurs during test setup, so it should be fine.

**Comment by allisonbm92** [comment]
Closing this as smoke tests are passing and https://github.com/firebase/firebase-android-sdk/pull/76 is unblocked.
