### ISSUE TITLE
W/FirebaseMessaging: Error while parsing timestamp in GCM event

### ISSUE THREAD

**Issue by auchaphon** [firebase/firebase-android-sdk#82]
**Firebase version 15.0.0**

Please Help (Android)

When trigger click notification on Background Not working
show error message **W/FirebaseMessaging: Error while parsing timestamp in GCM event**

Platform ios it's working

**Comment by morepork** [comment]
You can safely ignore this warning message, it won't affect how FCM works in your app.

Starting with firebase-messaging version 17.2.0 and newer the SDK should be fixed so that it doesn't log this message any more.
