### ISSUE TITLE
Dynamic Links redirect uri is private

### ISSUE THREAD

**Issue by heyarny** [firebase/firebase-android-sdk#834]
I'm trying to get the decoded redirect Uri to verify the campaign and other parameters I've set when creating a dynamic link, but there's just `pendingDynamicLinkData.getLink();` and that's it.

I require more insight. What campaign, what source, what medium..
How do I get those as a workaround?

**Comment by rosariopfernandes** [comment]
@heyarny I'm not 100% sure, but can you please try:
```java
Uri link = pendingDynamicLinkData.getLink();
String source = link.getQueryParameter("utm_source");
```

**Comment by heyarny** [comment]
pendingDynamicLinkData.getLink() Is the deep link, not dynamic link.

**Comment by aguatno** [comment]
Based on the documentation, the [getLink()](https://firebase.google.com/docs/reference/android/com/google/firebase/dynamiclinks/PendingDynamicLinkData.html#getLink()) method returns the link parameter of the dynamic link. If this isn't the case, I would suggest filing a new feature request and we'd be happy to look into it.
