### ISSUE TITLE
Remote config listeners not called

### ISSUE THREAD

**Issue by mnayef95** [firebase/firebase-android-sdk#835]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component: Remote config
  * Component version: 19.0.1

#### Steps to reproduce:
Try fetch data from remote config no one of listeners will be called
The code inside a module called data.
and firebase initialization inside the app module
keep in mind the firebase real-time database working fine

#### Relevant Code:

```
firebaseRemoteConfig.fetch(0)
                .addOnCompleteListener {
                    Log.e("", "")
                    // Not called, i have waited 2 minutes
                }
                .addOnSuccessListener {
                    Log.e("", "")
                    // Not called, i have waited 2 minutes
                }
                .addOnFailureListener {
                    Log.e("", "")
                    // Not called, i have waited 2 minutes
                }
                .addOnCanceledListener {
                    Log.e("", "")
                    // Not called, i have waited 2 minutes
                }
```

**Comment by aguatno** [comment]
Hi @mnayef95 Thanks for reporting this issue. It looks like there's an updated version "19.0.3" of Remote Config. Could you try to update to the latest version and see if the issue persists?

Thanks.
