### ISSUE TITLE
FIAM deprecated in Java

### ISSUE THREAD

**Issue by xuaninbox** [firebase/firebase-android-sdk#855]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component: InAppMessaging
  * Component version: 19.0.1

### [REQUIRED] Step 3: Describe the problem

Same as iOS https://github.com/firebase/firebase-ios-sdk/issues/3545

For customs InAppMessagingDisplay, these method should not be deprecated

Text title;
Text body;
messageClicked()
etc.

**Comment by MeghaB** [comment]
The 'FIAM' model object getters are deprecated in favor of the template-specific model getters, so this deprecation is as-intended:

ex: ModalMessage.getTitle() vs InAppMessage.getTitle() -> https://github.com/firebase/firebase-android-sdk/blob/master/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/ModalMessage.java#L93

Additionally, messageClicked() is deprecated in favor of messageClicked(Action), which provides more information as to the part of the message that end-users engaged with. This was updated when multi-button/action messages were introduced -> https://github.com/firebase/firebase-android-sdk/blob/6e293abbfaa8f6a36edde6ddde1dc496d78b2746/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingDisplayCallbacks.java#L38

**Comment by xuaninbox** [comment]
Thanks for the reply!

But to use custom InAppMessagingDisplay I have to call

`setMessageDisplayComponent(@NonNull FirebaseInAppMessagingDisplay messageDisplay)`

which only takes FirebaseInAppMessagingDisplay interface

`
void displayMessage(@NonNull InAppMessage var1, @NonNull FirebaseInAppMessagingDisplayCallbacks var2);
`

Which only has InAppMessage, is there a way to get ModalMessage?

Thanks again!

**Comment by xuaninbox** [comment]
also it seems 

https://github.com/firebase/firebase-android-sdk/blob/6e293abbfaa8f6a36edde6ddde1dc496d78b2746/firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingDisplayCallbacks.java#L34

caused the

`Task<Void> messageClicked(@NonNull Action action); `

to be wrongfully marked as deprecated.

**Comment by xuaninbox** [comment]
@MeghaB any update on this issue? Thank!
