### ISSUE TITLE
Pre-download data before displaying background notification.

### ISSUE THREAD

**Issue by CodyEngel** [firebase/firebase-android-sdk#878]
## What feature would you like to see?

I'd like to ensure that our application has data downloaded and ready to display before notifying the user via a push notification. From looking at https://github.com/firebase/firebase-android-sdk/issues/46 it doesn't look to be possible today.

## How would you use it?

Before telling the user they have something new and cool to look at, we would first prime the application so it was ready for them and then would allow the system to display the notification as usual.

**Comment by JasonAHeron** [comment]
In this for in-app messaging or firebase messaging?
