### ISSUE TITLE
Recoverable exception while reading cache

### ISSUE THREAD

**Issue by aglt** [firebase/firebase-android-sdk#881]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.1
  * Firebase Component: InAppMessaging
  * Component version: 'com.google.firebase:firebase-inappmessaging-display:19.0.1'

### [REQUIRED] Step 3: Describe the problem
I am unable to get the In App Message to display on the app. I get the following messages in the log when I try to trigger an in app message

Launching the app
> I/FIAM.Headless: Setting display event listener
> I/FIAM.Headless: went foreground
> D/FIAM-Quickstart: InstanceId: [InstanceId]
> I/FIAM.Headless: Removing display event listener
> I/FIAM.Headless: Setting display event listener

Triggering the event by pushing the button

> W/FIAM.Headless: Recoverable exception while reading cache: /data/user/0/[PackageName]/files/fiam_impressions_store_file (No such file or directory)
> I/FIAM.Headless: Already impressed [CampaignName-1] ? : false
> W/FIAM.Headless: Recoverable exception while reading cache: /data/user/0/[PackageName]/files/fiam_impressions_store_file (No such file or directory)
> I/FIAM.Headless: Already impressed [CampaignName-2] campaign ? : false
> W/FIAM.Headless: Recoverable exception while reading cache: /data/user/0/[PackageName]/files/fiam_impressions_store_file (No such file or directory)
> I/FIAM.Headless: Already impressed [CampaignName-1] ? : false
> W/FIAM.Headless: Recoverable exception while reading cache: /data/user/0/[PackageName]/files/fiam_impressions_store_file (No such file or directory)
> I/FIAM.Headless: Already impressed [CampaignName-2] campaign ? : false
> I/FIAM.Headless: Removing display event listener

#### Steps to reproduce:

I have created a couple of campaigns in the firebase console. I have a contextual trigger setup for the event ("trigger_event_1") in the console under "schedule" and when I log this event on my android client I get this error

> W/FIAM.Headless: Recoverable exception while reading cache: /data/user/0/[PackageName]/files/fiam_impressions_store_file (No such file or directory)
> I/FIAM.Headless: Already impressed [CampaignName-1] ? : false

Logging the event:

> D/FA: Logging event (FE): trigger_event_1, Bundle[{ga_event_origin(_o)=app, ga_screen_class(_sc)=KotlinMainActivity, ga_screen_id(_si)=6834218401587332572}]

#### Relevant Code:
```
        eventTriggerButton.setOnClickListener { view ->
            firebaseIam.triggerEvent(TRIGGER_EVENT)
            firebaseAnalytics.logEvent(TRIGGER_EVENT, Bundle())

            Snackbar.make(view, "Triggering '$TRIGGER_EVENT'!", Snackbar.LENGTH_LONG)
                .setAction("Action", null)
                .show()
        }
```
Here is the code:
https://github.com/aglt/fiam

it is based on https://github.com/firebase/quickstart-android/blob/master/inappmessaging/README.md

**Comment by JasonAHeron** [comment]
So the warning log you're seeing is a red herring unfortunately. It has nothing to do with your issue as far as I can tell. I think it might be something to do with your use of suppressing messages based on a quick glance at your code. I would suggest trying to reproduce this issue with a simpler example (maybe try not suppressing messages) rather than your current implementation that you linked to.
