### ISSUE TITLE
FirebaseApp#DEFAULT_NAME not marked as part of the @PublicApi

### ISSUE THREAD

**Issue by bjornick** [firebase/firebase-android-sdk#89]
This results in the constant being inlined in the last release of firebase-common because of pre-guarding.  Now that we aren't pre-guarding, this isn't as big of an issue, but it is still nice to be clear about what our public apis are.

**Comment by samtstern** [comment]
Vlad is this fixed / obsolete?

**Comment by vkryachko** [comment]
It is in fact obsolete as we no longer proguard, closing
