### ISSUE TITLE
Support For Fixed-line/Landline Phone authentication

### ISSUE THREAD

**Issue by moriswala** [firebase/firebase-android-sdk#893]
## What feature would you like to see?

I want to authenticate landline phone, just in case user does not have mobile phone or He/She does not willing to provide their personal phone number.

* Can we have the feature to get voice call on specified landline number ?
* Same feature can be used in case user is not able to get SMS.

## How would you use it?

I would like to give flexibility to the user to select any phone number not just a Mobile number.

**Comment by samtstern** [comment]
@moriswala thanks for your feedback!  I can see how this would be useful, but Firebase Authentication has no plans to add this feature.
