### ISSUE TITLE
allow developer to override api endpoint for firebase-storage and any other api hosting at *.googleapis.com

### ISSUE THREAD

**Issue by chandlerding** [firebase/firebase-android-sdk#906]
## What feature would you like to see?

Allow override the default *.googleapis.com hostname when calling API.
For well-know reason the *.googleapis.com is inaccessible in some place, however developers can host reverse proxy under their own domain name to workaround that.
e.g.
firebasestorage.googleapis.com -> firebasestorage.example.io

## How would you use it?

Add a method to allow developer customize the hostname when calling firebase apis that are hosted under *.googleapis.com.

**Comment by wudh147** [comment]
+1

**Comment by aguatno** [comment]
Thank you for sending this feature request. We will keep this FR open and update it as we prioritize new features. Thank you.

**Comment by argzdev** [comment]
Duplicate of #905
