### ISSUE TITLE
Dynamic links fail to open on custom browsers as Facebook

### ISSUE THREAD

**Issue by DanGDroid** [firebase/firebase-android-sdk#915]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: __latest___
  * Firebase Component: ___latest__ (Database, Firestore, Storage, Functions, etc)
  * Component version: ___latest__

### [REQUIRED] Step 3: Describe the problem
i generated a short link and copied the url to facebook or just share the link through Facebook.
when try to open the link on Facebook - in Facebook browser - fail to redirect
if i choose to open via Crome browser - opens as expected

example link:
https://farmerdirecto.page.link/EZmK
screen shots:
![WhatsApp Image 2019-10-15 at 12 38 32](https://user-images.githubusercontent.com/10976856/66821083-8769ff80-ef4a-11e9-8b6b-0acc26eec2c0.jpeg)
![WhatsApp Image 2019-10-15 at 12 39 03](https://user-images.githubusercontent.com/10976856/66821084-8769ff80-ef4a-11e9-9a39-9f6b8981f73e.jpeg)

**Comment by samtstern** [comment]
I have transferred the other issue to this repo, closing this one as a duplicate:
https://github.com/firebase/firebase-android-sdk/issues/916

**Comment by DanGDroid** [comment]
@samtstern 
when you change in Facebook setting and privacy -> setting-> media and contacts -> open links externally -> on - to open external links it works fine.
but by default this is disabled - and prevents users to open a firebase link

i think FB made some changes on there browser - my app now opens but `firebase.links().getInitialLink()` returns null
or
```javascript
firebase.links().onLink((url) => {
            console.log("firebase onLink ::: link = "+JSON.stringify(url));
            this.handleDeepLinkUrl(url)
                }); 
```
is not invoked
when i open by external link browser or by device default browser all is fine
something is broken with firebase link and FB browser
