### ISSUE TITLE
FirebaseDynamicLinks created from non-default FirebaseApp uses apikey from default FirebaseApp

### ISSUE THREAD

**Issue by VasyaFromRussia** [firebase/firebase-android-sdk#921]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.1
  * Firebase Component: Dynamic Links
  * Component version: com.google.firebase:firebase-dynamic-links:19.0.0

### [REQUIRED] Step 3: Describe the problem

I have 2 `FirebaseApp` instances in my app – for production and staging environments.
The production instance is configured with `google-services.json` and the Gradle plugin. The staging one is configured with `FirebaseOptions`. Hence I create an instance of `FirebaseDynamicLinks` using an appropriate instance of `FirebaseApp`.

When I try to create a short link with staging instance of `FirebaseDynamicLinks`, I got an error: `Error: 400: Your project does not own Dynamic Links domain`. But it does.

The reason is that in [this line](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/DynamicLink.java#L99) the API key is taken from the default instance of `FirebaseApp`, I suppose.

#### Steps to reproduce:
1. Put `google-services.json` to your project.
2. Create an instance of `FirebaseApp` with `FirebaseOptions` containing another API key.
3. Instantiate `FirebaseDynamicLinks` with the instance of `FirebaseApp` from `2`.
4. Try to `buildShortDynamicLink()` with it.

**Comment by aguatno** [comment]
Hi @VasyaFromRussia Thank you for reporting this issue. I'm a bit confused here. My understanding is that there are two projects. The first one is configured with google-services.json and the other one is manually configured using FirebaseOptions. Let me know if this is not the case. If possible, can you please provide the actual code to recreate this? It will make it easier for us to debug. It'll also be great if you could provide what would be the expected/actual output. Thanks 🙂
