### ISSUE TITLE
i cant handell this error

### ISSUE THREAD

**Issue by Mkhira** [firebase/firebase-android-sdk#926]
Launching lib\main.dart on SM J500F in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "E:\flater_projects\arabete\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\flater_projects\arabete\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
  Command: E:\flater_projects\arabete\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by aguatno** [comment]
Hello @Mkhira, thank you for taking time on filing this issue. I am a little confused though. If you really think this is a bug, could you provide steps to replicate or reproduction sample in order for us to be able to look into it? Thanks!

**Comment by Mkhira** [comment]
It handeld when i changed the
classpath 'com.google.gms:google-services:4.3.2'   to   classpath
'com.google.gms:google-services:4.2.0'

On 21 Oct 2019 4:18 p.m., "Arel Guatno" <notifications@github.com> wrote:

Hello @Mkhira <https://github.com/Mkhira>, thank you for taking time on
filing this issue. I am a little confused though. If you really think this
is a bug, could you provide steps to replicate or reproduction sample in
order for us to be able to look into it? Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/firebase/firebase-android-sdk/issues/926?email_source=notifications&email_token=AKZJXAGBJIDKNRJ7NZ4J5ALQPW24DA5CNFSM4JB4CH4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB2PNYI#issuecomment-544536289>,
or unsubscribe

**Comment by aguatno** [comment]
Thanks for the information @Mkhira. Could you confirm if you're developing your app using Flutter? If you could provide us a minimal code or project that can demonstrate and run locally, would be a great help to troubleshoot the issue quickly.

Thanks
