### ISSUE TITLE
license problem for not open source package in firebase-android-sdk

### ISSUE THREAD

**Issue by EmilyChai** [firebase/firebase-android-sdk#933]
Hi, firebase-android-sdk team

Our team use firebase-android-sdk  according to https://firebase.google.com/docs/android/setup
for integrating firebase messaging.

However, this will introduce 3 packages in gradle file and
also in apk file.
implementation 'com.google.firebase:firebase-core:XXX'
implementation 'com.google.firebase:firebase-iid:XXX'
implementation 'com.google.firebase:firebase-messaging:XXX' 

We get license from MVN
https://mvnrepository.com/artifact/com.google.firebase/firebase-iid/17.1.0
https://developer.android.com/studio/terms.html

Our legal team found that
3.4 You may not use the SDK for any purpose not expressly permitted by the License Agreement.  Except to the extent required by applicable third party licenses, you may not copy (except for backup purposes), modify, adapt, redistribute, decompile, reverse engineer, disassemble, or create derivative works of the SDK or any part of the SDK.

So we cannot use this 3 packages in our app?
Because build them in apk means "redistribute" and if use, it will be a violation of Google’s rules.

Could you please help to check if our legal team's comprehensive is right?
If so, I understand everyone cannot use firebase messging in android app? 
If not, Could you give some legal document or other relate service term for use in android app?

Thanks.
BRs.
Emily

--

**Comment by vkryachko** [comment]
I am not a lawyer so don't take it as legal advice but looking at section 3.1 of the license:

```
Google grants you a limited, worldwide, royalty-free, non-assignable,
non-exclusive, and non-sublicensable license to use the SDK solely to develop
applications for compatible implementations of Android.
```

It sounds like you can use it in android apps.

fwiw a lot of Google's closed-source Android SDKs are under this license, including Firebase, Play Services SDKs, etc.

If you want more details/want to be sure you should reach out to [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) as this issue channel is for software related questions and bug reports and here you won't find people who have the knowledge to answer license questions. Thanks

**Comment by ashwinraghav** [comment]
Similar to https://github.com/firebase/firebase-android-sdk/issues/125#issuecomment-545183043
Thanks for bringing this to our attention. Obviously our SDKs are intended to be included in your apps, as described in the setup guides and documentation. We'll look into clarifying the licensing language.

**Comment by ojj11** [comment]
I note that this is closed and I can see com.google.firebase:firebase-common is clearly licensed as Apache 2 in this repository, however, I can't find any licensing information for dependencies:

 - com.google.firebase:firebase-iid
 - com.google.firebase:firebase-iid-interop
 - com.google.firebase:firebase-measurement-connector

This is being flagged by our internal systems here and I'd like to be able to point the team in the direction of some clear documentation that clarifies that these libraries are also licensed under Apache 2.

**Comment by EmilyChai** [comment]
@ojj11 Yes, we need an explicit license note for those packages, otherwise some legal teams will not permit development team to use them for potential legal issues. The current license for those packages are Android SDK license, and very confuse for term 3.4.
