### ISSUE TITLE
App crashes when Firebase auth gets completed.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [firebase/firebase-android-sdk#945]
I am a new flutter firebase developer.
my app crashes when firebase authentication is completed.

>`Launching lib\main.dart on Redmi 5A in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
I/Choreographer(25166): Skipped 45 frames!  The application may be doing too much work on its main thread.
W/Looper  (25166): Slow Frame: doFrame is 754ms late
D/vndksupport(25166): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport(25166): Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
E/SpannableStringBuilder(25166): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(25166): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(25166): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(25166): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(25166): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(25166): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
I/zygote64(25166): Do partial code cache collection, code=61KB, data=40KB
I/zygote64(25166): After code cache collection, code=61KB, data=40KB
I/zygote64(25166): Increasing code cache capacity to 256KB
W/IInputConnectionWrapper(25166): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(25166): setComposingRegion on inactive InputConnection
W/IInputConnectionWrapper(25166): endBatchEdit on inactive InputConnection
W/BiChannelGoogleApi(25166): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@6910546
E/JavaBinder(25166): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder(25166): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/JavaBinder(25166): 	at com.google.firebase.auth.internal.zzam.zzc(Unknown Source:22)
E/JavaBinder(25166): 	at com.google.firebase.auth.internal.zzam.zzde(Unknown Source:17)
E/JavaBinder(25166): 	at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source:8)
E/JavaBinder(25166): 	at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source:1)
E/JavaBinder(25166): 	at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source:47)
E/JavaBinder(25166): 	at com.google.firebase.auth.internal.zzat.zzi(Unknown Source:57)
E/JavaBinder(25166): 	at com.google.firebase.auth.internal.zzat.zzg(Unknown Source:10)
E/JavaBinder(25166): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
E/JavaBinder(25166): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
E/JavaBinder(25166): 	at com.google.firebase.auth.api.internal.zzax.zzdx(Unknown Source:15)
E/JavaBinder(25166): 	at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source:35)
E/JavaBinder(25166): 	at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source:41)
E/JavaBinder(25166): 	at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source:9)
E/JavaBinder(25166): 	at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source:9)
E/JavaBinder(25166): 	at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source:13)
E/JavaBinder(25166): 	at android.os.Binder.execTransact(Binder.java:704)
E/JavaBinder(25166): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.segura_manegerial-Ga0SqT6804edugCRUePruA==/base.apk"],nativeLibraryDirectories=[/data/app/com.segura_manegerial-Ga0SqT6804edugCRUePruA==/lib/arm64, /data/app/com.segura_manegerial-Ga0SqT6804edugCRUePruA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/JavaBinder(25166): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/JavaBinder(25166): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/JavaBinder(25166): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/JavaBinder(25166): 	... 16 more
E/AndroidRuntime(25166): FATAL EXCEPTION: Binder:25166_4
E/AndroidRuntime(25166): Process: com.segura_manegerial, PID: 25166
E/AndroidRuntime(25166): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/AndroidRuntime(25166): 	at com.google.firebase.auth.internal.zzam.zzc(Unknown Source:22)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.internal.zzam.zzde(Unknown Source:17)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source:8)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source:1)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source:47)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.internal.zzat.zzi(Unknown Source:57)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.internal.zzat.zzg(Unknown Source:10)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.api.internal.zzax.zzdx(Unknown Source:15)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source:35)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source:41)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source:9)
E/AndroidRuntime(25166): 	at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source:9)
E/AndroidRuntime(25166): 	at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source:13)
E/AndroidRuntime(25166): 	at android.os.Binder.execTransact(Binder.java:704)
E/AndroidRuntime(25166): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.segura_manegerial-Ga0SqT6804edugCRUePruA==/base.apk"],nativeLibraryDirectories=[/data/app/com.segura_manegerial-Ga0SqT6804edugCRUePruA==/lib/arm64, /data/app/com.segura_manegerial-Ga0SqT6804edugCRUePruA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/AndroidRuntime(25166): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/AndroidRuntime(25166): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(25166): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(25166): 	... 16 more
I/Process (25166): Sending signal. PID: 25166 SIG: 9
Lost connection to device.
Exited (sigterm)
`
It is having PID 25166
i have used this method for firebase
```
 `final _auth = FirebaseAuth.instance;
onpressed: () async {
                Navigator.pushNamed(context, WelcomeScreen.id);
                final user = await _auth.createUserWithEmailAndPassword(email: email,password: password);
                
              },`
```

**Comment by samtstern** [comment]
@Abhishek-kumar09 please file issues with Flutter+Firebase here:
https://github.com/FirebaseExtended/flutterfire
