### ISSUE TITLE
Firestore connection state listener

### ISSUE THREAD

**Issue by kuhnp** [firebase/firebase-android-sdk#947]
## What feature would you like to see?

There is currently no way to get updates on the connection state of the firestore client with the remote database. A simple listener exposing something like ```onConnected()``` and ```onDisconnected()``` would be very useful. 

## How would you use it?

Let's say the user is on a chat application, where the messages of the conversation are stored in a firestore cloud database. When the user's connection drops, it'd be nice to notify him that he won't see new incoming messages. The firestore instance could expose a method to register a connection update listener. This solution would be more accurate/elegant than having a listener on the global network state.

**Comment by thebrianchen** [comment]
@kuhnp You can listen to network changes by passing `MetadataChanges.INCLUDE` into your snapshot listener ([example](https://firebase.google.com/docs/firestore/query-data/listen)). Whenever Firestore detects that its network connectivity state has changed, all active listeners fire with metadata changes. The `fromCache` field in `snapshot.metadata` will be `true` when Firestore goes offline, and `false` when it goes online.

**Comment by kuhnp** [comment]
@thebrianchen Thanks for your response. I just tried it and it works 👍. However I don't feel like this is a very nice api, might be worth to improve it in something more idiomatic? Thanks anyway!

**Comment by wilhuff** [comment]
The basic problem we have is that until you're successfully listening to some query we don't have any notion of the connection state. To save server side resources the client doesn't connect unless it actually needs the connection to get data. Similarly, if the client goes idle we tear down the connection. Changing this is sufficiently expensive that we can't consider it.

This means that a top level connectivity listener would have a weird contract: it wouldn't work unless you were actively listening to something. Tying the connection state to the snapshot makes it clearer that you can't get at this state without listening. This has the unfortunate side effect of hiding it somewhat though.

For now we believe this is the least worst way to do this but we appreciate the feedback. Cheers!
