### ISSUE TITLE
Remote Config crash on Android 7.x

### ISSUE THREAD

**Issue by agap** [firebase/firebase-android-sdk#948]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component: Remote Config
  * Component version: 19.0.0

#### Steps to reproduce:

Our app is crashing in production with the stacktrace, which starts with these lines:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.FirebaseRemoteConfig com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault()' on a null object reference
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance()
       at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance()
```

The crash happens **only** on devices running Android OS 7.x.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @agap thank you for taking time filling this issue. I was wondering if you have numbers to show how frequent this crash is?

You may also consider upgrading your SDK to the latest version (19.0.3), and see if the persists from there.

Thanks!

**Comment by agap** [comment]
1. We've had ~50 crashes within the last week, 24 users affected, which is sort of big percentage, considering that we have something around 200 users on Android 7.x.
2. I've updated to 19.0.3 and will post my results here once we roll this version out. :)
