### ISSUE TITLE
APK Size Tooling needs support for FIAM

### ISSUE THREAD

**Issue by allisonbm92** [firebase/firebase-android-sdk#95]
In-app messaging display in ow open-source, but there isn't a corresponding test app under tools/apksize

**Comment by vkryachko** [comment]
@yifanyang is this planned? if not pls feel free to close the bug

**Comment by yifanyang** [comment]
Wasn't aware of this feature request. I definitely want to include fiam in size measurement.

Right now the way of generating an apk for fiam always leads to OOM (https://github.com/firebase/firebase-android-sdk/pull/1480/files#diff-3cd85539008a8e42f091dd35a65b9b8eR33), so I decided to exclude them in that PR. But let's keep this open and I'll work on it.

**Comment by ashwinraghav** [comment]
Fixed
