### ISSUE TITLE
Admob ads don't open on click in the second process！

### ISSUE THREAD

**Issue by zhangchaojiong** [firebase/firebase-android-sdk#987]
` W/FA: Failed to retrieve Firebase Instance Id
  W/Ads: Received non-success response code 302 from pinging URL: https://click.liftoff.io/v1/campaign_click/b9RjINgY2hi`

Hi :
   Admob ads don't open on click，I have two processes in my app, and the ads in the second process (non-main process) cannot be opened！Can anyone tell me why？(sorry, my english is no good)

**Comment by zhangchaojiong** [comment]
> 我不知道如何标记这个问题，所以我将其标记为便于分类。等一下

thx, I wait for you！

**Comment by aguatno** [comment]
Thank you for reporting the issue @zhangchaojiong. I’m finding it quite difficult replicating your issue without an [mcve](https://stackoverflow.com/help/minimal-reproducible-example), could you provide a minimal runnable repro of your app so I can also test this one locally? Thanks
