### ISSUE TITLE
FirebaseMessagingService not working with TWA

### ISSUE THREAD

**Issue by janfous** [firebase/firebase-android-sdk#989]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.2
  * Firebase Component: Cloud messaging(Database, Firestore, Storage, Functions, etc)
  * Component version: 20.0.1

### [REQUIRED] Step 3: Describe the problem
FirebaseMessagingService doesn't work properly when using TWA to create app. A notification sent from the Firebase console will get delivered correcly, however trying to do something like:
```java
public class MyFirebaseMessagingService extends FirebaseMessagingService {
    public void onMessageReceived(RemoteMessage remoteMessage) {
        ...
    }
}
```
just doesn't work - the `onMessageReceived` method is never called. The same code works when using WebView instead of TWA. 
#### Steps to reproduce:

1. Create a TWA project 
2. Pair with Firebase, add cloud messaging component
3. Create a class extending FirebaseMessagingService and onMessageReceived method
4. Delcare the service in AndroidManifest
5. Try to send a notification through the Firebase console. It will be received, but onMessageReceived won't be executed

#### Relevant Code:

***LauncherActivity***
```java
public class LauncherActivityTWA extends AppCompatActivity {
    private static final String TAG = "TWALauncherActivity";
    private LauncherActivityMetadata mMetadata;
    private TwaLauncher mTwaLauncher;
    private PwaWrapperSplashScreenStrategy mSplashScreenStrategy;
    private boolean mBrowserWasLaunched;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        this.mMetadata = LauncherActivityMetadata.parse(this);

        TrustedWebActivityBuilder twaBuilder = (new TrustedWebActivityBuilder(this, this.getLaunchingUrl())).setStatusBarColor(this.getColorCompat(this.mMetadata.statusBarColorId));
        this.mTwaLauncher = new TwaLauncher(this);
        this.mTwaLauncher.launch(twaBuilder, this.mSplashScreenStrategy, () -> {
            this.mBrowserWasLaunched = true;
        });  //.launch causes the incorrect behaviour, launch(Uri uri), understandably, behaves identically
    }
   ...
```
***AndroidManifest.xml***
```xml
        <service
            android:name=".MyFirebaseMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```
***MyFirebaseMessagingService***
```java
public class MyFirebaseMessagingService extends FirebaseMessagingService {

    private static final String TAG = "Notification";

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        
        if (remoteMessage == null) {
            Log.d(TAG,"Message is null");
            return;

        }

        // Check if message contains a notification payload.
        if (remoteMessage.getNotification() != null) {
            Log.d(TAG,"Message is not null");            
            handleNotification(remoteMessage.getNotification().getBody());
        }
    }
}
```

**Comment by aguatno** [comment]
Thank you for reporting the issue @janfous. Can you share your dependencies from the build.gradle file?

**Comment by janfous** [comment]
```
    implementation 'com.google.firebase:firebase-analytics:17.2.1'
    implementation 'com.google.firebase:firebase-messaging:20.0.1'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.github.GoogleChrome:custom-tabs-client:3e2f06a3b37748e4071b4d9924ccbfb7a9e60e2e'
```

**Comment by ciarand** [comment]
>5. Try to send a notification through the Firebase console. It will be received, but onMessageReceived won't be executed

When you say "it will be received," do you mean the notification is being shown?

**Comment by janfous** [comment]
>When you say "it will be received," do you mean the notification is being shown?
Yes, exactly.

**Comment by aguatno** [comment]
I can reproduce the issue using the Android Quickstart code where I only change the onCreate method and added dependencies for TWA.

I'll be raising this to the team, and I'll let you know once I've heard from them.

**Comment by aguatno** [comment]
Hi @janfous qq, may we know your expectation when the app is in the foreground?

**Comment by janfous** [comment]
Hi, my goal is to "intercept" the message using `onMessageReceived` and read the "data":{...} part of the message

**Comment by janfous** [comment]
Just tested it with data messages and it works. The problem only seems to be with notification messages. Maybe it has something to with the fact that notification messages only trigger `onMessageReceived` when app is in foreground?

**Comment by aguatno** [comment]
Hi @janfous, currently If your application is in the foreground you should see the incoming message printed in the logs from onMessageReceived() method. If it is in the background, a system notification should be displayed. More info [here](https://firebase.google.com/docs/cloud-messaging/android/receive)

**Comment by janfous** [comment]
Yeah, I know that's how notification messages work, but it still doesn't explain why my override of onMessageReceived is never triggered in the case of notification messages. Data messages work as expected

**Comment by aguatno** [comment]
Hi @janfous I'll consult internally to see if there are any other explanations for this. I''ll get back to you once I got an update.

**Comment by aguatno** [comment]
Hi @janfous sorry for the late in response. For notification messages, the onMessageReceived method will be called only when the app is in foreground and for data messages, the onMessageReceived method will be called regardless.

That being said, I would like to compare WebView vs TWA, and to ask code snippet for the same code that works when using WebView instead of TWA. I'll be also sharing the information with our engineering team. Thanks

**Comment by janfous** [comment]
Hi, don't worry about it! Yes, I am aware and that's what's causing the problem. See, I somehow missed this message: `D/FA: Application going to the background` that's logged just as the app/website finishes loading everything. That leads me to believe I should have posted this issue on TWA's github instead of here. 

Anyways, here are the code snippets you wanted:

**TWA**
```java
Uri launch_url = getLaunchingUrl();
this.mMetadata = LauncherActivityMetadata.parse(this);
TrustedWebActivityBuilder twaBuilder = (new TrustedWebActivityBuilder(this, launch_url)).setStatusBarColor(this.getColorCompat(this.mMetadata.statusBarColorId));
Log.d(TAG, launch_url.toString());
this.mTwaLauncher = new TwaLauncher(this);
this.mTwaLauncher.launch(twaBuilder, null, () -> this.mBrowserWasLaunched = true);
if (!sChromeVersionChecked) {
    TrustedWebUtils.promptForChromeUpdateIfNeeded(this, this.mTwaLauncher.getProviderPackage());
    sChromeVersionChecked = true;
}
```

**WebView**
```java
Uri url = getLaunchingUrl();
setContentView(R.layout.activity_launcher);
webView = findViewById(R.id.webview);
webView.getSettings().setUserAgentString(Helper.getApplicationId());
webView.getSettings().setJavaScriptEnabled(true);
webView.loadUrl(url.toString());
```

**Comment by aguatno** [comment]
I noticed that message too, and it seems TWA is launching a splash screen that pushes the app to background, hence FCM will treat this behavior as Background instead of Foreground. You may also post this on TWA's Github.

**Comment by janfous** [comment]
Good to know it wasn't caused by some bug in my code. I guess you can close this issue now, since it isn't caused by a bug in your system. I will post a solution if I find one.

Thank you for your assistance and sorry for wasting your time with this.

**Comment by aguatno** [comment]
You're welcome. I’ll be closing this issue now. If you want to continue the discussion just leave a comment here and we are happy to re-open this.
